Repository influxdata/influxdb_iox, pull requests merged in 2021-02, with the labels that each got.

#788 fix: enable tokio::fs for object_store crate
  object_store/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#789 fix: Make --api-bind et.al. support localhost
  src/commands/config.rs
Labels: automerge

#781 feat: Add an optional Flight client to the IOx client library
  Cargo.lock
  Cargo.toml
  influxdb_iox_client/Cargo.toml
  influxdb_iox_client/README.md
  influxdb_iox_client/src/builder.rs
  influxdb_iox_client/src/client.rs
  influxdb_iox_client/src/client/flight.rs
  influxdb_iox_client/src/errors/grpc_error.rs
  influxdb_iox_client/src/errors/grpc_query_error.rs
  influxdb_iox_client/src/errors/http_error.rs
  influxdb_iox_client/src/errors/mod.rs
  influxdb_iox_client/src/lib.rs
  tests/end_to_end_cases/flight_api.rs
Labels: automerge

#792 refactor: Change ReadBuffer column_names to return Option<BTreeSet>
  read_buffer/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#787 fix: Avoid clashing ports when running e2e tests
  tests/end-to-end.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#783 feat: Implement Cross Chunk Schema / RecordBatch merging at query time
  Cargo.lock
  data_types/src/schema.rs
  data_types/src/selection.rs
  query/Cargo.toml
  query/src/frontend/sql.rs
  query/src/lib.rs
  query/src/provider.rs
  query/src/provider/adapter.rs
  query/src/provider/make_null.rs
  query/src/provider/physical.rs
  query/src/util.rs
  server/src/db/chunk.rs
  server/src/db/streams.rs
  server/src/query_tests/scenarios.rs
  server/src/query_tests/sql.rs
Labels: automerge, kodiak: merge.method = 'squash'

#793 feat: Enable/Disable logging in tests via RUST_LOG environment variable
  CONTRIBUTING.md
  Cargo.lock
  server/src/query_tests/sql.rs
  server/src/query_tests/table_schema.rs
  test_helpers/Cargo.toml
  test_helpers/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#794 fix: Report a failure to parse an AWS datetime
  object_store/src/aws.rs
Labels: automerge, kodiak: merge.method = 'squash'

#796 chore: Cleaning things in prep for rust 2021
  influxdb_iox_client/src/client.rs
  influxdb_tsm/src/key.rs
  influxdb_tsm/src/reader.rs
  mutable_buffer/src/database.rs
  read_buffer/src/column.rs
  src/commands/input.rs
  src/influxdb_ioxd/http.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#798 feat: Use Bytes instead of Vec<u8> in prost generated code
  Cargo.lock
  Cargo.toml
  generated_types/Cargo.toml
  generated_types/build.rs
  generated_types/src/lib.rs
  google_types/Cargo.toml
  google_types/build.rs
  google_types/protos/google/protobuf/types.proto
  google_types/protos/google/rpc/error_details.proto
  google_types/protos/google/rpc/status.proto
  google_types/src/lib.rs
  src/influxdb_ioxd/rpc/input.rs
  src/influxdb_ioxd/rpc/service.rs
  tests/end-to-end.rs
  tests/end_to_end_cases/grpc_api.rs
Labels: automerge

#800 ci: Add nightly-2021-02-12 to quay.io/influxdb/rust:ci
  docker/Dockerfile.ci
Labels: automerge, kodiak: merge.method = 'rebase'

#806 chore: Update arrow deps, remove make_null_column
  Cargo.lock
  arrow_deps/Cargo.toml
  query/src/provider.rs
  query/src/provider/adapter.rs
  query/src/provider/make_null.rs
Labels: automerge

#803 feat: tool to graphically display plans
  CONTRIBUTING.md
  tools/iplan
Labels: automerge, kodiak: merge.method = 'squash'

#807 refactor: introduce clone_on_ref_ptr clippy lint
  arrow_deps/src/lib.rs
  data_types/src/lib.rs
  data_types/src/schema.rs
  generated_types/src/lib.rs
  google_types/src/lib.rs
  influxdb2_client/src/lib.rs
  influxdb_iox_client/src/client/flight.rs
  influxdb_iox_client/src/lib.rs
  influxdb_line_protocol/src/lib.rs
  influxdb_tsm/src/lib.rs
  ingest/src/lib.rs
  ingest/src/parquet/writer.rs
  mutable_buffer/src/database.rs
  mutable_buffer/src/lib.rs
  mutable_buffer/src/partition.rs
  mutable_buffer/src/table.rs
  object_store/src/azure.rs
  object_store/src/lib.rs
  packers/src/lib.rs
  panic_logging/src/lib.rs
  query/src/exec.rs
  query/src/exec/context.rs
  query/src/exec/fieldlist.rs
  query/src/exec/schema_pivot.rs
  query/src/exec/seriesset.rs
  query/src/exec/stringset.rs
  query/src/func/selectors.rs
  query/src/lib.rs
  query/src/provider.rs
  query/src/provider/adapter.rs
  query/src/provider/physical.rs
  query/src/test.rs
  read_buffer/src/lib.rs
  src/influxdb_ioxd.rs
  src/influxdb_ioxd/flight.rs
  src/influxdb_ioxd/http.rs
  src/influxdb_ioxd/rpc.rs
  src/influxdb_ioxd/rpc/service.rs
  src/main.rs
  test_helpers/src/lib.rs
  test_helpers/src/tracing.rs
  wal/src/lib.rs
Labels: automerge

#795 feat: implement `tag_keys` in gRPC planner and across mutable buffer
  data_types/src/schema.rs
  mutable_buffer/src/chunk.rs
  mutable_buffer/src/database.rs
  mutable_buffer/src/table.rs
  query/src/exec.rs
  query/src/exec/schema_pivot.rs
  query/src/frontend/influxrpc.rs
  query/src/frontend/sql.rs
  query/src/lib.rs
  query/src/plan/stringset.rs
  query/src/predicate.rs
  query/src/test.rs
  query/src/util.rs
  server/src/db.rs
  server/src/db/chunk.rs
  server/src/query_tests/influxrpc.rs
  server/src/query_tests/influxrpc/table_names.rs
  server/src/query_tests/influxrpc/tag_column_names.rs
  server/src/query_tests/scenarios.rs
  server/src/query_tests/table_schema.rs
  src/influxdb_ioxd/rpc/service.rs
Labels: automerge, kodiak: merge.method = 'squash'

#814 refactor: move gRPC storage into own module
  src/influxdb_ioxd.rs
  src/influxdb_ioxd/rpc.rs
  src/influxdb_ioxd/rpc/flight.rs
  src/influxdb_ioxd/rpc/storage.rs
  src/influxdb_ioxd/rpc/storage/data.rs
  src/influxdb_ioxd/rpc/storage/expr.rs
  src/influxdb_ioxd/rpc/storage/id.rs
  src/influxdb_ioxd/rpc/storage/input.rs
  src/influxdb_ioxd/rpc/storage/service.rs
  src/influxdb_ioxd/rpc/testing.rs
  tests/end_to_end_cases/grpc_api.rs
Labels: automerge, kodiak: merge.method = 'squash'

#817 refactor: apply clippy clone lint
  server/src/buffer.rs
  server/src/config.rs
  server/src/db.rs
  server/src/db/chunk.rs
  server/src/db/streams.rs
  server/src/lib.rs
  server/src/snapshot.rs
  server/src/tracker.rs
Labels: automerge

#816 feat: implement `size` on Read Buffer
  read_buffer/src/chunk.rs
  read_buffer/src/column.rs
  read_buffer/src/column/encoding/bool.rs
  read_buffer/src/column/encoding/dictionary/rle.rs
  read_buffer/src/column/encoding/fixed_null.rs
  read_buffer/src/lib.rs
  read_buffer/src/row_group.rs
  read_buffer/src/table.rs
  read_buffer/src/value.rs
Labels: automerge

#821 chore: Update dependencies
  Cargo.lock
  arrow_deps/Cargo.toml
  query/src/func/window.rs
Labels: automerge, kodiak: merge.method = 'squash'

#824 chore: use docker image inspect in get-deploy-tags.sh
  .circleci/get-deploy-tags.sh
Labels: automerge

#825 feat: get writer ID endpoint
  influxdb_iox_client/src/client.rs
  src/influxdb_ioxd/http.rs
Labels: automerge, enhancement

#826 refactor: derive Clone for API client
  influxdb_iox_client/src/client.rs
Labels: automerge, enhancement

#819 feat: implement field_columns plan
  mutable_buffer/src/database.rs
  mutable_buffer/src/table.rs
  query/src/exec.rs
  query/src/frontend/influxrpc.rs
  query/src/lib.rs
  query/src/plan.rs
  query/src/plan/fieldlist.rs
  query/src/test.rs
  server/src/db.rs
  server/src/query_tests/influxrpc.rs
  server/src/query_tests/influxrpc/field_columns.rs
  server/src/query_tests/influxrpc/table_names.rs
  server/src/query_tests/influxrpc/tag_column_names.rs
  server/src/query_tests/scenarios.rs
  server/src/query_tests/sql.rs
  server/src/query_tests/table_schema.rs
  src/influxdb_ioxd/rpc/storage/service.rs
Labels: automerge, kodiak: merge.method = 'squash'

#828 fix: do not use `println!` on server startup
  src/influxdb_ioxd.rs
Labels: automerge, kodiak: merge.method = 'squash'

#829 feat: Include GIT_HASH in startup log message
  build.rs
  src/influxdb_ioxd.rs
Labels: automerge, kodiak: merge.method = 'squash'

#832 chore: update Arrow dependencies
  Cargo.lock
  arrow_deps/Cargo.toml
  query/src/frontend/sql.rs
  query/src/func/selectors.rs
Labels: automerge

#830 feat: Allow to put streams of unknown length to objectstore
  Cargo.lock
  object_store/Cargo.toml
  object_store/src/aws.rs
  object_store/src/azure.rs
  object_store/src/buffer.rs
  object_store/src/disk.rs
  object_store/src/gcp.rs
  object_store/src/lib.rs
  object_store/src/memory.rs
  server/src/buffer.rs
  server/src/lib.rs
  server/src/snapshot.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#834 feat: Implement list_with_delimiter for Azure
  Cargo.lock
  docs/env.example
  object_store/Cargo.toml
  object_store/src/azure.rs
Labels: automerge

#837 refactor: make certain Database method sync
  mutable_buffer/src/database.rs
  query/src/frontend/influxrpc.rs
  query/src/frontend/sql.rs
  query/src/lib.rs
  query/src/test.rs
  server/src/db.rs
  server/src/query_tests/scenarios.rs
  server/src/query_tests/table_schema.rs
  server/src/snapshot.rs
  src/influxdb_ioxd/http.rs
Labels: automerge

#822 refactor: enable string fields in read buffer
  read_buffer/src/lib.rs
  read_buffer/src/row_group.rs
  server/src/query_tests/scenarios.rs
Labels: automerge

#831 docs: Rename read group to row group
  read_buffer/src/row_group.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#845 docs: Fix typo
  object_store/src/buffer.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#842 fix: remove workaround query code
  server/src/query_tests/scenarios.rs
Labels: automerge, kodiak: merge.method = 'squash'

#774 chore: Compile examples and benches continue in CI tests
  .github/workflows/rust.yml
Labels: automerge

#846 feat: encoding of standard gRPC error details payloads
  Cargo.lock
  google_types/Cargo.toml
  google_types/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#840 refactor: Use parking_lot::Mutex instead of std::sync::Mutex
  Cargo.lock
  Cargo.toml
  ingest/Cargo.toml
  ingest/src/lib.rs
  logfmt/Cargo.toml
  logfmt/tests/logging.rs
  query/Cargo.toml
  query/src/test.rs
  server/Cargo.toml
  server/src/buffer.rs
  server/src/db.rs
  server/src/lib.rs
  server/src/snapshot.rs
  server/src/tracker.rs
  src/commands/config.rs
  src/influxdb_ioxd/http.rs
  test_helpers/Cargo.toml
  test_helpers/src/tracing.rs
  wal/Cargo.toml
Labels: automerge

#851 docs: Refer to the example env file and clarify comments
  README.md
  docs/env.example
Labels: automerge, kodiak: merge.method = 'squash'

#805 feat: Add functionality to limit mutable buffer size and evict partitions
  data_types/benches/benchmark.rs
  data_types/src/data.rs
  data_types/src/database_rules.rs
  mutable_buffer/src/database.rs
  mutable_buffer/src/partition.rs
  query/src/test.rs
  server/src/db.rs
Labels: automerge

#802 feat: Implements list_with_delimiter for Google Cloud
  Cargo.lock
  object_store/Cargo.toml
  object_store/src/gcp.rs
Labels: automerge

#856 feat: Add S3 plumbing to iodx config
  docs/env.example
  object_store/src/aws.rs
  src/commands/config.rs
  src/influxdb_ioxd.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#860 refactor: rename tag_column_names --> tag_keys in InfluxRPCPlanner
  mutable_buffer/src/table.rs
  query/src/frontend/influxrpc.rs
  server/src/query_tests/influxrpc.rs
  server/src/query_tests/influxrpc/tag_keys.rs
  src/influxdb_ioxd/rpc/storage/service.rs
Labels: automerge, kodiak: merge.method = 'squash'

#854 feat: Plug GCS list_with_delimiter impl
  docs/env.example
  object_store/src/lib.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#864 chore: add DS_Store into .gitignore to avoid unecessary noises
  .gitignore
Labels: automerge

#866 feat: Implement /iox/api/v1/databases/:name/query?q=
  src/influxdb_ioxd/http.rs
Labels: automerge

#847 feat: gRPC management api stubs
  .github/workflows/rust.yml
  buf.yaml
  data_types/src/database_rules.rs
  generated_types/build.rs
  generated_types/protos/com/github/influxdata/idpe/storage/read/source.proto
  generated_types/protos/influxdata/iox/management/v1/base_types.proto
  generated_types/protos/influxdata/iox/management/v1/database_rules.proto
  generated_types/protos/influxdata/iox/management/v1/service.proto
  generated_types/protos/influxdata/platform/storage/predicate.proto
  generated_types/protos/influxdata/platform/storage/service.proto
  generated_types/protos/influxdata/platform/storage/storage_common.proto
  generated_types/protos/influxdata/platform/storage/storage_common_idpe.proto
  generated_types/protos/influxdata/platform/storage/test.proto
  generated_types/protos/wal.fbs
  generated_types/src/lib.rs
Labels: automerge

#867 fix: Escape empty string PathPart
  object_store/src/path/parts.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#871 fix: Remove test for non-existing DNS record
  src/commands/config.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#859 feat: Port tag_values to the InfluxRPCPlanner
  mutable_buffer/src/chunk.rs
  mutable_buffer/src/database.rs
  mutable_buffer/src/table.rs
  query/src/frontend/influxrpc.rs
  query/src/lib.rs
  query/src/test.rs
  server/src/db.rs
  server/src/db/chunk.rs
  server/src/query_tests/influxrpc.rs
  server/src/query_tests/influxrpc/tag_values.rs
  src/influxdb_ioxd/rpc/storage/service.rs
Labels: automerge, kodiak: merge.method = 'squash'

#862 feat: add basic gRPC health service
  Cargo.lock
  Cargo.toml
  README.md
  buf.yaml
  generated_types/build.rs
  generated_types/protos/grpc/health/v1/service.proto
  generated_types/src/lib.rs
  influxdb_iox_client/Cargo.toml
  influxdb_iox_client/src/client.rs
  influxdb_iox_client/src/client/health.rs
  src/influxdb_ioxd/http.rs
  src/influxdb_ioxd/rpc.rs
  tests/end-to-end.rs
Labels: automerge, kodiak: merge.method = 'squash'

#876 chore: Update arrow/datafusion deps again
  Cargo.lock
  arrow_deps/Cargo.toml
Labels: automerge

#877 feat: smaller IOx build images
  .circleci/config.yml
  .dockerignore
  docker/Dockerfile.iox
Labels: automerge

#874 feat: Consolidate all bucket config into one option/env var
  docs/README.md
  docs/env.example
  docs/testing.md
  object_store/src/aws.rs
  object_store/src/azure.rs
  object_store/src/gcp.rs
  src/commands/config.rs
  src/influxdb_ioxd.rs
Labels: automerge

#878 refactor: move SeriesSetPlans into its own module
  mutable_buffer/src/database.rs
  mutable_buffer/src/table.rs
  query/src/exec.rs
  query/src/lib.rs
  query/src/plan.rs
  query/src/plan/seriesset.rs
  query/src/test.rs
  server/src/db.rs
  src/influxdb_ioxd/rpc/storage/service.rs
Labels: automerge, kodiak: merge.method = 'squash'

#848 feat: conversion to/from data_types and generated_types
  data_types/src/database_rules.rs
  data_types/src/field_validation.rs
  data_types/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#870 feat: implement format parameter on sql query endpoint
  src/influxdb_ioxd/http.rs
  src/influxdb_ioxd/http/format.rs
  tests/end-to-end.rs
  tests/end_to_end_cases/read_api.rs
Labels: automerge, kodiak: merge.method = 'squash'

#865 chore: improve readme
  README.md
Labels: automerge

#879 feat: Add iterators over different types of columns in Schema
  data_types/src/schema.rs
Labels: automerge, kodiak: merge.method = 'squash'

#888 chore: Update arrow deps, remove custom JsonArrayWriter
  Cargo.lock
  arrow_deps/Cargo.toml
  src/influxdb_ioxd/http/format.rs
Labels: automerge, kodiak: merge.method = 'squash'
