Repository influxdata/influxdb_iox, pull requests merged in 2021-04, with the labels that each got.

#1098 chore: Add the serde feature to bytes dep
  Cargo.lock
  Cargo.toml
  generated_types/Cargo.toml
  google_types/Cargo.toml
Labels: automerge, kodiak: merge.method = 'rebase'

#1095 refactor: Add rwlock around db rules
  server/src/db.rs
  server/src/lib.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#1091 feat: automated chunk lifecycle
  data_types/src/database_rules.rs
  server/Cargo.toml
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/partition.rs
  server/src/db/chunk.rs
  server/src/db/lifecycle.rs
  server/src/lib.rs
  tests/end_to_end_cases/management_api.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1101 refactor: remove Db::writeable
  server/src/db.rs
  server/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1102 feat: add SHOW TABLES and `select * from information_schema.columns`
  Cargo.lock
  arrow_deps/Cargo.toml
  server/src/query_tests/sql.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1103 refactor: push chunk and partition summary into catalog
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/catalog/partition.rs
  src/influxdb_ioxd/rpc/management.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1097 feat: Write Chunks to Parquet Files in Object Store
  Cargo.lock
  data_types/src/database_rules.rs
  parquet_file/Cargo.toml
  parquet_file/src/chunk.rs
  parquet_file/src/lib.rs
  server/Cargo.toml
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/chunk.rs
  server/src/snapshot.rs
Labels: automerge

#1108 feat: add 2 more chunk states for writing chunks to object store
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/chunk.rs
Labels: automerge

#1111 feat: add Prometheus metrics endpoint
  Cargo.lock
  Cargo.toml
  src/commands/metrics.rs
  src/influxdb_ioxd.rs
  src/influxdb_ioxd/http.rs
  src/main.rs
  tracing_deps/Cargo.toml
  tracing_deps/src/lib.rs
Labels: automerge

#1114 docs: Improve influxdb_iox_client module descriptions
  influxdb_iox_client/src/client.rs
Labels: automerge

#1115 chore: Remove GitHub Actions config
  .github/workflows/rust.yml
Labels: automerge

#1116 docs: Codify our preference for no return type in test functions
  docs/style_guide.md
Labels: automerge, kodiak: merge.method = 'squash'

#1112 feat: continue building foundation for writing RB chunks to parquet files
  Cargo.lock
  parquet_file/Cargo.toml
  parquet_file/src/chunk.rs
  parquet_file/src/lib.rs
  parquet_file/src/storage.rs
  parquet_file/src/table.rs
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/snapshot.rs
Labels: automerge

#1124 refactor: move tracking utilities into separate crate
  Cargo.lock
  Cargo.toml
  server/Cargo.toml
  server/src/buffer.rs
  server/src/db.rs
  server/src/db/lifecycle.rs
  server/src/lib.rs
  src/influxdb_ioxd/rpc/operations.rs
  tracker/Cargo.toml
  tracker/src/lib.rs
  tracker/src/task.rs
  tracker/src/task/future.rs
  tracker/src/task/history.rs
  tracker/src/task/registry.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1126 chore: Update arrow / datafusion deps again
  Cargo.lock
  arrow_deps/Cargo.toml
  server/src/query_tests/sql.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1127 refactor: use DatabaseName in DatabaseRules
  data_types/src/database_rules.rs
  internal_types/benches/benchmark.rs
  query/src/test.rs
  server/src/buffer.rs
  server/src/config.rs
  server/src/db.rs
  server/src/lib.rs
  server/src/query_tests/utils.rs
  server/src/snapshot.rs
  src/influxdb_ioxd/http.rs
  src/influxdb_ioxd/rpc/management.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1128 fix: disable minimum age by default
  src/commands/database.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1131 feat: write once writer id
  server/src/lib.rs
  src/commands/run.rs
  src/influxdb_ioxd.rs
  src/influxdb_ioxd/http.rs
  src/influxdb_ioxd/rpc/management.rs
  tests/common/server_fixture.rs
  tests/end_to_end_cases/management_cli.rs
  tests/end_to_end_cases/read_cli.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1129 fix: avoid spamming the logs with errors that are not errors
  server/src/db/lifecycle.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1134 refactor: extract OnceNonZeroU32
  internal_types/src/lib.rs
  internal_types/src/once.rs
  server/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1122 feat: implement line protocol to flatbuffers
  data_types/src/database_rules.rs
  generated_types/protos/influxdata/iox/write/v1/entry.fbs
  generated_types/src/entry_generated.rs
  internal_types/src/entry.rs
  internal_types/src/lib.rs
Labels: automerge

#1136 fix: Deep clone small results over flight
  src/influxdb_ioxd/rpc/flight.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#1138 chore: update tech talk links in README
  README.md
Labels: automerge, kodiak: merge.method = 'squash'

#1140 feat: Return newline delimited database names in database list
  src/commands/database.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#1125 feat: add basic memory tracking
  Cargo.lock
  mutable_buffer/Cargo.toml
  mutable_buffer/src/chunk.rs
  mutable_buffer/src/table.rs
  parquet_file/Cargo.toml
  parquet_file/src/chunk.rs
  server/src/buffer.rs
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/partition.rs
  server/src/db/lifecycle.rs
  server/src/lib.rs
  server/src/snapshot.rs
  src/influxdb_ioxd/rpc/operations.rs
  tracker/src/lib.rs
  tracker/src/mem.rs
  tracker/src/task.rs
  tracker/src/task/future.rs
  tracker/src/task/history.rs
  tracker/src/task/registry.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1120 fix: Don't return Result from test functions
  data_types/src/database_rules.rs
  influxdb2_client/src/api/ready.rs
  influxdb2_client/src/api/setup.rs
  influxdb2_client/src/data_point.rs
  influxdb2_client/src/lib.rs
  influxdb_line_protocol/src/lib.rs
  influxdb_tsm/src/mapper.rs
  ingest/src/lib.rs
  mutable_buffer/src/column.rs
  object_store/src/aws.rs
  object_store/src/azure.rs
  object_store/src/buffer.rs
  object_store/src/disk.rs
  object_store/src/gcp.rs
  object_store/src/memory.rs
  query/src/exec.rs
  query/src/exec/schema_pivot.rs
  query/src/exec/seriesset.rs
  server/src/lib.rs
  src/commands/run.rs
  src/influxdb_ioxd/http.rs
  src/influxdb_ioxd/rpc/storage/service.rs
  wal/src/lib.rs
  wal/tests/no_concurrency.rs
Labels: automerge

#1093 chore: Add integration tests for influxdb2_client against InfluxDB 2.0 OSS
  .circleci/config.yml
  Cargo.lock
  docs/testing.md
  influxdb2_client/Cargo.toml
  influxdb2_client/src/api/ready.rs
  influxdb2_client/src/api/setup.rs
  influxdb2_client/src/lib.rs
  influxdb2_client/tests/common/mod.rs
  influxdb2_client/tests/common/server_fixture.rs
  influxdb2_client/tests/setup.rs
Labels: automerge

#1119 feat: add line protocol ingest metrics
  Cargo.toml
  src/commands/metrics.rs
  src/influxdb_ioxd/http.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1148 chore: Update datafusion / arrow deps again
  Cargo.lock
  arrow_deps/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#1142 feat: Switch to jemalloc
  Cargo.lock
  Cargo.toml
  src/main.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#1150 feat: continue supporting write chunks to parquet files
  data_types/src/partition_metadata.rs
  influxdb_iox_client/src/client/management.rs
  parquet_file/src/chunk.rs
  parquet_file/src/storage.rs
  parquet_file/src/table.rs
  query/src/test.rs
  server/src/config.rs
  server/src/db.rs
  server/src/lib.rs
  server/src/query_tests/scenarios.rs
  server/src/query_tests/utils.rs
  server/src/snapshot.rs
  src/influxdb_ioxd/http.rs
  src/influxdb_ioxd/rpc/management.rs
Labels: automerge

#1121 chore: CI check that generated flatbuffers code has been updated if needed
  .circleci/config.yml
  generated_types/check-flatbuffers.sh
  generated_types/regenerate-flatbuffers.sh
Labels: automerge

#1149 feat: add sequenced entry builder
  generated_types/protos/influxdata/iox/write/v1/entry.fbs
  generated_types/src/entry_generated.rs
  internal_types/benches/benchmark.rs
  internal_types/src/entry.rs
Labels: automerge

#1076 feat: Add support for query API to influxdb_client
  Cargo.lock
  influxdb2_client/Cargo.toml
  influxdb2_client/examples/query.rs
  influxdb2_client/src/api/mod.rs
  influxdb2_client/src/api/query.rs
  influxdb2_client/src/common.rs
  influxdb2_client/src/lib.rs
  influxdb2_client/src/models/ast/call_expression.rs
  influxdb2_client/src/models/ast/dialect.rs
  influxdb2_client/src/models/ast/dict_item.rs
  influxdb2_client/src/models/ast/duration.rs
  influxdb2_client/src/models/ast/expression.rs
  influxdb2_client/src/models/ast/identifier.rs
  influxdb2_client/src/models/ast/import_declaration.rs
  influxdb2_client/src/models/ast/member_expression.rs
  influxdb2_client/src/models/ast/mod.rs
  influxdb2_client/src/models/ast/node.rs
  influxdb2_client/src/models/ast/package.rs
  influxdb2_client/src/models/ast/package_clause.rs
  influxdb2_client/src/models/ast/property.rs
  influxdb2_client/src/models/ast/property_key.rs
  influxdb2_client/src/models/ast/statement.rs
  influxdb2_client/src/models/ast/string_literal.rs
  influxdb2_client/src/models/ast/variable_assignment.rs
  influxdb2_client/src/models/file.rs
  influxdb2_client/src/models/mod.rs
  influxdb2_client/src/models/query.rs
Labels: automerge

#1159 chore: testing
  docs/regenerating_flatbuffers.md
  generated_types/regenerate-flatbuffers.sh
Labels: automerge

#1066 feat: Implement Update API for Database (rules)
  Cargo.lock
  Cargo.toml
  buf.yaml
  data_types/src/field_validation.rs
  data_types/src/lib.rs
  generated_types/protos/influxdata/iox/management/v1/service.proto
  influxdb_iox_client/src/client/management.rs
  server/src/config.rs
  server/src/lib.rs
  src/influxdb_ioxd/rpc/management.rs
  tests/end_to_end_cases/management_api.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#1161 feat: Add edit_db_rules script
  scripts/edit_db_rules
Labels: automerge, kodiak: merge.method = 'rebase'

#1162 refactor: lift chunk and table summaries out of DBChunk
  query/src/lib.rs
  query/src/test.rs
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/chunk.rs
  server/src/snapshot.rs
  src/influxdb_ioxd/http.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1165 chore: update cloud-storage to 0.9
  Cargo.lock
  object_store/Cargo.toml
  object_store/src/gcp.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1164 chore: Revert "Merge pull request #1159 from influxdata/er/flatbuffers"
  docs/regenerating_flatbuffers.md
  generated_types/regenerate-flatbuffers.sh
Labels: automerge, kodiak: merge.method = 'rebase'

#1170 feat: Add tests for writing RB chunks to Object Store
  Cargo.lock
  data_types/src/chunk.rs
  generated_types/protos/influxdata/iox/management/v1/chunk.proto
  parquet_file/src/chunk.rs
  parquet_file/src/table.rs
  server/Cargo.toml
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/chunk.rs
  server/src/query_tests/utils.rs
Labels: automerge

#1180 fix: check filename to have deterministic output
  server/src/db.rs
Labels: automerge

#1179 feat: mutable buffer snapshotting
  Cargo.toml
  data_types/src/timestamp.rs
  generated_types/Cargo.toml
  influxdb2_client/Cargo.toml
  internal_types/src/schema.rs
  mutable_buffer/src/chunk.rs
  mutable_buffer/src/chunk/snapshot.rs
  mutable_buffer/src/column.rs
  object_store/Cargo.toml
  parquet_file/Cargo.toml
  query/Cargo.toml
  server/Cargo.toml
  server/src/db/chunk.rs
  server/src/db/streams.rs
  server/src/snapshot.rs
  tracker/Cargo.toml
  wal/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#1189 fix: Use debug level to log requests
  src/influxdb_ioxd/http.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#1184 feat: basic snapshot caching
  Cargo.lock
  mutable_buffer/Cargo.toml
  mutable_buffer/src/chunk.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1195 chore: Update datafusion / arrow deps again
  Cargo.lock
  arrow_deps/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#1186 refactor: remove mutable buffer predicate logic
  mutable_buffer/src/chunk.rs
  mutable_buffer/src/lib.rs
  mutable_buffer/src/table.rs
  server/src/db/pred.rs
  server/src/db/streams.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1199 refactor: reduce module coupling in mutable buffer
  mutable_buffer/src/chunk.rs
  mutable_buffer/src/chunk/snapshot.rs
  mutable_buffer/src/column.rs
  mutable_buffer/src/pred.rs
  mutable_buffer/src/table.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1193 feat: Implement WriteBuffer gRPC
  generated_types/protos/influxdata/iox/write/v1/service.proto
  server/src/db.rs
  server/src/lib.rs
  src/influxdb_ioxd/rpc/error.rs
  src/influxdb_ioxd/rpc/write.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#1197 docs: update multi core design doc
  docs/multi_core_tasks.md
Labels: automerge, kodiak: merge.method = 'squash'

#1200 refactor: Remove async from `InfluxRPCPlanner`
  query/src/frontend/influxrpc.rs
  server/src/query_tests/influxrpc/field_columns.rs
  server/src/query_tests/influxrpc/read_filter.rs
  server/src/query_tests/influxrpc/read_group.rs
  server/src/query_tests/influxrpc/read_window_aggregate.rs
  server/src/query_tests/influxrpc/table_names.rs
  server/src/query_tests/influxrpc/tag_keys.rs
  server/src/query_tests/influxrpc/tag_values.rs
  src/influxdb_ioxd/rpc/storage/service.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1185 chore: Use a DID newtype instead of u32 for dictionary ids
  mutable_buffer/src/chunk.rs
  mutable_buffer/src/column.rs
  mutable_buffer/src/dictionary.rs
  mutable_buffer/src/table.rs
  server/src/query_tests/sql.rs
  tests/end_to_end_cases/management_api.rs
  tests/end_to_end_cases/management_cli.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#1201 feat: Add 2 main functions table_schema and table_names for Parquet Chunk to pay a foundation for querying it
  Cargo.lock
  parquet_file/Cargo.toml
  parquet_file/src/chunk.rs
  parquet_file/src/table.rs
  read_buffer/src/chunk.rs
  server/src/db.rs
  server/src/db/chunk.rs
Labels: automerge

#1174 feat: RB -> OS lifecycle
  data_types/src/database_rules.rs
  data_types/src/job.rs
  generated_types/protos/influxdata/iox/management/v1/database_rules.proto
  generated_types/protos/influxdata/iox/management/v1/jobs.proto
  server/src/db.rs
  server/src/db/lifecycle.rs
  src/commands/database.rs
Labels: automerge

#1191 feat: Add a dedicated threadpool for running queries
  Cargo.lock
  query/Cargo.toml
  query/src/exec.rs
  query/src/exec/context.rs
  query/src/exec/task.rs
  query/src/plan/stringset.rs
  query/src/test.rs
  server/Cargo.toml
  server/benches/tag_values.rs
  server/src/db.rs
  server/src/lib.rs
  server/src/query_tests/influxrpc/field_columns.rs
  server/src/query_tests/influxrpc/read_filter.rs
  server/src/query_tests/influxrpc/read_group.rs
  server/src/query_tests/influxrpc/read_window_aggregate.rs
  server/src/query_tests/influxrpc/table_names.rs
  server/src/query_tests/influxrpc/tag_keys.rs
  server/src/query_tests/influxrpc/tag_values.rs
  server/src/query_tests/sql.rs
  src/commands/run.rs
  src/influxdb_ioxd.rs
  src/influxdb_ioxd/http.rs
  src/influxdb_ioxd/rpc/flight.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1205 fix: Remove mutex acquisition in impl `std::fmt::Debug` for DedicatedExecutor
  query/src/exec/task.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1209 perf: use column_values in read buffer
  server/src/db/chunk.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#1212 refactor: use read_buffer column range for time range
  read_buffer/src/chunk.rs
  read_buffer/src/table.rs
  server/src/db.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#1198 feat: Use single db-wide executor for running queries
  arrow_deps/src/test_util.rs
  query/src/exec.rs
  query/src/exec/context.rs
  query/src/exec/task.rs
  query/src/frontend/sql.rs
  server/benches/tag_values.rs
  server/src/config.rs
  server/src/db.rs
  server/src/lib.rs
  server/src/query_tests/influxrpc/field_columns.rs
  server/src/query_tests/influxrpc/read_filter.rs
  server/src/query_tests/influxrpc/read_group.rs
  server/src/query_tests/influxrpc/read_window_aggregate.rs
  server/src/query_tests/influxrpc/table_names.rs
  server/src/query_tests/influxrpc/tag_keys.rs
  server/src/query_tests/influxrpc/tag_values.rs
  server/src/query_tests/influxrpc/util.rs
  server/src/query_tests/sql.rs
  server/src/query_tests/utils.rs
  server/src/snapshot.rs
  src/influxdb_ioxd/http.rs
  src/influxdb_ioxd/rpc/flight.rs
  src/influxdb_ioxd/rpc/management.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1070 feat: Add support for labels API to influxdb2_client
  influxdb2_client/examples/label.rs
  influxdb2_client/src/api/label.rs
  influxdb2_client/src/api/mod.rs
  influxdb2_client/src/models/label.rs
  influxdb2_client/src/models/mod.rs
Labels: automerge, influxdb_client

#1218 feat: implement a few more functions as part of supporting query from parquet file
  data_types/src/timestamp.rs
  parquet_file/src/chunk.rs
  parquet_file/src/table.rs
  server/src/db.rs
  server/src/db/chunk.rs
Labels: automerge

#1211 feat: Initial scaffolding for routing layer
  Cargo.lock
  data_types/src/database_rules.rs
  generated_types/protos/influxdata/iox/management/v1/shard.proto
  internal_types/src/entry.rs
  server/Cargo.toml
  server/src/lib.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#1210 feat: Run query plans on the database wide executor as well
  query/src/exec.rs
  query/src/exec/seriesset.rs
  query/src/frontend/influxrpc.rs
  src/influxdb_ioxd.rs
  src/influxdb_ioxd/http.rs
  src/influxdb_ioxd/planner.rs
  src/influxdb_ioxd/rpc/flight.rs
  src/influxdb_ioxd/rpc/storage/service.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1223 fix: Crash early when writer id is passed on cmdline and cannot loaddb from objectstore
  src/influxdb_ioxd.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#1229 fix: Flight Query API Internal error "There were no results from ticket"
  src/influxdb_ioxd/rpc/flight.rs
  tests/end_to_end_cases/flight_api.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1177 chore: Changes to the CI docker image to enable flatbuffer regeneration and InfluxDB 2.0 integration tests
  docker/Dockerfile.ci
Labels: automerge, kodiak: merge.method = 'rebase'

#1228 fix: Use MAX (window end) for timestamps in read_group
  query/src/frontend/influxrpc.rs
  server/src/query_tests/influxrpc/read_group.rs
  tests/end_to_end_cases/storage_api.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1235 fix: Fix edit_db_rules script
  scripts/edit_db_rules
Labels: automerge, kodiak: merge.method = 'rebase'

#1234 feat: Implement sharding logic
  data_types/src/consistent_hasher.rs
  data_types/src/database_rules.rs
  data_types/src/lib.rs
  generated_types/protos/influxdata/iox/management/v1/shard.proto
Labels: automerge, kodiak: merge.method = 'rebase'

#1230 feat: Use TimestampNanosecondArray for timestamps in IOx
  arrow_deps/src/util.rs
  internal_types/src/schema.rs
  mutable_buffer/src/chunk.rs
  mutable_buffer/src/table.rs
  parquet_file/Cargo.toml
  query/src/exec/fieldlist.rs
  query/src/func/selectors.rs
  query/src/func/selectors/internal.rs
  query/src/func/window.rs
  query/src/test.rs
  read_buffer/src/chunk.rs
  read_buffer/src/row_group.rs
  server/src/db.rs
  server/src/lib.rs
  server/src/query_tests/influxrpc/field_columns.rs
  server/src/query_tests/influxrpc/read_filter.rs
  server/src/query_tests/influxrpc/read_group.rs
  server/src/query_tests/influxrpc/read_window_aggregate.rs
  server/src/query_tests/sql.rs
  src/influxdb_ioxd/http.rs
  src/influxdb_ioxd/rpc/storage/data.rs
  src/influxdb_ioxd/rpc/storage/service.rs
  tests/end_to_end_cases/read_cli.rs
  tests/end_to_end_cases/scenario.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1241 fix: don't clone arrays to make TimestampNanosecondArrays
  mutable_buffer/src/table.rs
  query/src/func/window.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1238 feat: add jq_edit_db_rules script
  scripts/edit_db_rules
  scripts/jq_edit_db_rules
Labels: automerge, kodiak: merge.method = 'rebase'

#1232 fix: set defaults for `persist` and `drop_non_persisted` to `true`
  data_types/src/database_rules.rs
  generated_types/protos/influxdata/iox/management/v1/database_rules.proto
  src/commands/database.rs
Labels: automerge

#1249 chore: upgrade arrow and Rust
  .circleci/config.yml
  Cargo.lock
  arrow_deps/Cargo.toml
  arrow_deps/src/util.rs
  benches/packers.rs
  data_types/src/field_validation.rs
  docker/Dockerfile.ci
  influxdb_iox_client/src/format.rs
  influxdb_line_protocol/src/lib.rs
  influxdb_tsm/src/reader.rs
  internal_types/src/schema/builder.rs
  mem_qe/src/column.rs
  mutable_buffer/src/chunk/snapshot.rs
  mutable_buffer/src/dictionary.rs
  mutable_buffer/src/table.rs
  object_store/src/aws.rs
  object_store/src/disk.rs
  packers/src/packers.rs
  query/src/exec/context.rs
  query/src/exec/field.rs
  query/src/frontend/influxrpc.rs
  query/src/func/selectors/internal.rs
  query/src/group_by.rs
  read_buffer/src/column.rs
  read_buffer/src/column/cmp.rs
  read_buffer/src/column/encoding/dictionary.rs
  read_buffer/src/column/encoding/dictionary/rle.rs
  read_buffer/src/column/string.rs
  read_buffer/src/row_group.rs
  read_buffer/src/table.rs
  read_buffer/src/value.rs
  rust-toolchain
  server/src/config.rs
  server/src/db.rs
  server/src/lib.rs
  src/commands/convert.rs
  src/commands/input.rs
  src/commands/meta.rs
  src/commands/stats.rs
  src/influxdb_ioxd/http.rs
  src/influxdb_ioxd/rpc/storage/data.rs
  src/influxdb_ioxd/rpc/storage/expr.rs
  src/influxdb_ioxd/rpc/storage/input.rs
  tests/common/server_fixture.rs
  tracker/src/task.rs
Labels: automerge

#1172 feat: Add support for health API to influxdb_client
  influxdb2_client/examples/health.rs
  influxdb2_client/src/api/health.rs
  influxdb2_client/src/api/mod.rs
  influxdb2_client/src/models/health.rs
  influxdb2_client/src/models/mod.rs
  influxdb2_client/tests/health.rs
Labels: automerge, influxdb_client

#1263 chore: update circle job
  docker/Dockerfile.ci
Labels: automerge

#1265 chore: update circle job
  .circleci/config.yml
  docker/Dockerfile.ci
Labels: automerge

#1267 fix: specify stable version
  .circleci/config.yml
  docker/Dockerfile.ci
  rust-toolchain
  rustfmt.toml
Labels: automerge, kodiak: merge.method = 'squash'

#1240 feat(tracing): improve logs and tracing
  Cargo.lock
  Cargo.toml
  logfmt/src/lib.rs
  observability_deps/Cargo.toml
  observability_deps/src/lib.rs
  src/commands/logging.rs
  src/commands/metrics.rs
  src/commands/run.rs
  src/commands/tracing.rs
  src/influxdb_ioxd.rs
  src/main.rs
  tests/commands.rs
Labels: automerge

#1264 feat: enable disabling MUB snapshot caching (#1203)
  mutable_buffer/Cargo.toml
  mutable_buffer/src/chunk.rs
  server/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#1266 feat: signal tracker completion from Drop
  tracker/src/task.rs
  tracker/src/task/future.rs
  tracker/src/task/registry.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1268 chore: update tonic to 0.4.2
  Cargo.lock
Labels: automerge, kodiak: merge.method = 'squash'

#1194 refactor: update schema conflicts to display column name
  mutable_buffer/src/table.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#1259 feat: Implement write_entry_downstream
  Cargo.lock
  data_types/src/consistent_hasher.rs
  data_types/src/database_rules.rs
  influxdb_iox_client/src/client/write.rs
  internal_types/src/entry.rs
  server/Cargo.toml
  server/src/config.rs
  server/src/lib.rs
  src/influxdb_ioxd/rpc/error.rs
  tests/end_to_end_cases/write_api.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#1271 feat: MUB benchmarks (#635)
  Cargo.lock
  mutable_buffer/Cargo.toml
  mutable_buffer/benches/snapshot.rs
  mutable_buffer/benches/write.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1275 feat: Log git_hash when starting
  src/influxdb_ioxd.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#1277 test: Don't run any integration tests unless TEST_INTEGRATION is set
  docs/testing.md
  influxdb2_client/tests/common/server_fixture.rs
  object_store/src/aws.rs
  object_store/src/azure.rs
  object_store/src/gcp.rs
Labels: automerge

#1273 feat: fast MUB dictionary arrow conversion
  Cargo.lock
  mutable_buffer/Cargo.toml
  mutable_buffer/src/chunk.rs
  mutable_buffer/src/column.rs
  mutable_buffer/src/dictionary.rs
  mutable_buffer/src/table.rs
  server/src/db.rs
  server/src/query_tests/sql.rs
  tests/end_to_end_cases/management_api.rs
  tests/end_to_end_cases/management_cli.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1272 refactor: make chunks per-table
  data_types/src/chunk.rs
  data_types/src/job.rs
  generated_types/protos/influxdata/iox/management/v1/chunk.proto
  generated_types/protos/influxdata/iox/management/v1/jobs.proto
  generated_types/protos/influxdata/iox/management/v1/service.proto
  influxdb_iox_client/src/client/management.rs
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/partition.rs
  server/src/db/lifecycle.rs
  server/src/db/system_tables.rs
  server/src/lib.rs
  server/src/query_tests/influxrpc/read_window_aggregate.rs
  server/src/query_tests/scenarios.rs
  server/src/query_tests/sql.rs
  server/src/snapshot.rs
  src/commands/database/partition.rs
  src/influxdb_ioxd/http.rs
  src/influxdb_ioxd/rpc/error.rs
  src/influxdb_ioxd/rpc/management.rs
  tests/end_to_end_cases/management_api.rs
  tests/end_to_end_cases/management_cli.rs
Labels: automerge

#1283 feat(iox): Log write points errors at debug level
  src/influxdb_ioxd/http.rs
Labels: automerge

#1291 fix: don't over count new chunks
  server/src/db.rs
Labels: automerge

#1300 chore: update arrow versions
  Cargo.lock
  arrow_deps/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#1303 chore: fix observability dependency key
  read_buffer/Cargo.toml
Labels: automerge

#1305 fix: Set a global log/tracing subscriber
  src/commands/tracing.rs
  src/main.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1289 feat: use bitmasks within MUB (#1274)
  Cargo.lock
  data_types/src/partition_metadata.rs
  internal_types/src/entry.rs
  internal_types/src/schema.rs
  internal_types/src/schema/builder.rs
  mutable_buffer/Cargo.toml
  mutable_buffer/src/bitset.rs
  mutable_buffer/src/chunk/snapshot.rs
  mutable_buffer/src/column.rs
  mutable_buffer/src/lib.rs
  mutable_buffer/src/table.rs
  server/src/db.rs
  server/src/db/system_tables.rs
  server/src/query_tests/sql.rs
  tests/end_to_end_cases/management_api.rs
  tests/end_to_end_cases/management_cli.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1245 refactor: remove unused PersistSegment job
  data_types/src/job.rs
  generated_types/protos/influxdata/iox/management/v1/jobs.proto
Labels: automerge, kodiak: merge.method = 'squash'

#1246 refactor: use `FromIter` rather than array builders to create system table arrays
  server/src/db/system_tables.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1312 feat: ingest_points_bytes_total records both success and errors
  src/influxdb_ioxd/http.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1309 fix: Log sha256sum before running docker build
  .circleci/config.yml
  docker/Dockerfile.iox
Labels: automerge, kodiak: merge.method = 'squash'

#1301 feat: throttled stores
  object_store/src/lib.rs
  object_store/src/throttle.rs
  src/commands/run.rs
  src/influxdb_ioxd.rs
Labels: automerge

#1316 fix: Remove authorization header in middleware
  src/influxdb_ioxd/http.rs
Labels: automerge

#1262 feat: string dictionary encoding (#1220)
  internal_types/src/schema.rs
  internal_types/src/schema/builder.rs
  mutable_buffer/src/column.rs
  mutable_buffer/src/dictionary.rs
  mutable_buffer/src/table.rs
  query/src/exec.rs
  query/src/exec/seriesset.rs
  query/src/exec/stringset.rs
  query/src/frontend/influxrpc.rs
  query/src/test.rs
  read_buffer/src/chunk.rs
  read_buffer/src/column.rs
  read_buffer/src/column/string.rs
  read_buffer/src/row_group.rs
  server/src/query_tests/sql.rs
  src/influxdb_ioxd/rpc/flight.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1323 fix: Disable docker layer caching in CI
  .circleci/config.yml
Labels: automerge

#1307 refactor: chunks shall always have data (= 1 table)
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/partition.rs
  server/src/db/lifecycle.rs
  server/src/query_tests/scenarios.rs
  src/influxdb_ioxd/http.rs
Labels: automerge

#1321 docs: deny broken intradoc links
  .circleci/config.yml
  arrow_deps/src/lib.rs
  data_types/src/lib.rs
  generated_types/protos/influxdata/iox/write/v1/service.proto
  generated_types/src/lib.rs
  google_types/src/lib.rs
  influxdb2_client/src/lib.rs
  influxdb_iox_client/src/client/flight.rs
  influxdb_iox_client/src/client/write.rs
  influxdb_iox_client/src/connection.rs
  influxdb_iox_client/src/lib.rs
  influxdb_line_protocol/src/lib.rs
  influxdb_tsm/src/lib.rs
  ingest/src/lib.rs
  internal_types/src/lib.rs
  internal_types/src/schema.rs
  logfmt/src/lib.rs
  mem_qe/src/lib.rs
  metrics/src/lib.rs
  mutable_buffer/src/lib.rs
  object_store/src/lib.rs
  packers/src/lib.rs
  panic_logging/src/lib.rs
  parquet_file/src/lib.rs
  query/src/lib.rs
  query/src/predicate.rs
  read_buffer/src/lib.rs
  server/src/db/pred.rs
  server/src/lib.rs
  src/commands/run.rs
  src/influxdb_ioxd/planner.rs
  src/main.rs
  test_helpers/src/lib.rs
  tracker/src/lib.rs
  write_buffer/src/lib.rs
Labels: automerge

#1322 fix: Histogram boundaries are durations not percentiles
  metrics/src/lib.rs
Labels: automerge

#1325 ci: pass `--document-private-items` to `cargo doc`
  .circleci/config.yml
  query/src/exec/seriesset.rs
  server/src/db/catalog/partition.rs
Labels: automerge

#1327 feat: pushdown table and partition key predicates to catalog (#736)
  Cargo.lock
  query/src/frontend/influxrpc.rs
  query/src/lib.rs
  query/src/test.rs
  server/Cargo.toml
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/catalog/partition.rs
  server/src/db/chunk.rs
  server/src/query_tests/table_schema.rs
  server/src/snapshot.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1308 feat: sort RUB (read buffer) chunks
  internal_types/src/arrow.rs
  internal_types/src/arrow/sort.rs
  internal_types/src/lib.rs
  server/src/db.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1320 docs: add design docs for catalog persistence
  docs/README.md
  docs/catalog_persistence.md
Labels: automerge

#1329 feat: move closing chunks as soon as possible
  data_types/src/database_rules.rs
  generated_types/protos/influxdata/iox/management/v1/database_rules.proto
  server/src/db/lifecycle.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1336 feat: Build a perf_image image for every commit in main
  .circleci/config.yml
Labels: automerge

#1334 chore: fix usize 32-bit overflow
  influxdb_tsm/src/encoders/simple8b.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#1331 fix: emit correct number of rows in log line
  read_buffer/src/chunk.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#1330 feat: Make background task period configurable
  data_types/src/database_rules.rs
  generated_types/protos/influxdata/iox/management/v1/database_rules.proto
  server/src/db.rs
  src/commands/database.rs
Labels: automerge

#1344 fix: Validate ServerId when creating structs from flatbuffers
  internal_types/src/data.rs
  internal_types/src/entry.rs
  server/src/buffer.rs
Labels: automerge

#1346 fix: Validate that ClockValue is never 0
  internal_types/benches/benchmark.rs
  internal_types/src/entry.rs
  mutable_buffer/benches/snapshot.rs
  mutable_buffer/benches/write.rs
  mutable_buffer/src/chunk.rs
  mutable_buffer/src/table.rs
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/lifecycle.rs
Labels: automerge

#1332 feat: Add interactive SQL repl
  Cargo.lock
  Cargo.toml
  src/commands/sql.rs
  src/commands/sql/repl.rs
  src/commands/sql/repl_command.rs
  src/main.rs
  tests/end_to_end_cases/mod.rs
  tests/end_to_end_cases/sql_cli.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1343 feat: Add the git-log-prs script
  scripts/git-log-prs
Labels: automerge, kodiak: merge.method = 'rebase'

#1310 fix: Only show current database's system.operations table
  data_types/src/database_name.rs
  server/src/db.rs
  server/src/db/system_tables.rs
  server/src/query_tests/sql.rs
  server/src/query_tests/utils.rs
  tests/end_to_end_cases/flight_api.rs
  tests/end_to_end_cases/mod.rs
  tests/end_to_end_cases/scenario.rs
  tests/end_to_end_cases/system_tables.rs
  tracker/src/task.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1338 feat: Add multiple matchers to shard config
  data_types/src/database_rules.rs
  generated_types/protos/influxdata/iox/management/v1/shard.proto
  tests/end_to_end_cases/write_api.rs
Labels: automerge

#1350 fix: tracker join shouldn't return if pending registrations
  tracker/src/task.rs
  tracker/src/task/future.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1365 chore: update deps
  Cargo.lock
  arrow_deps/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#1347 feat: change background worker to use backoff instead of poll (#1339)
  data_types/src/database_rules.rs
  generated_types/protos/influxdata/iox/management/v1/database_rules.proto
  server/src/db.rs
  server/src/db/lifecycle.rs
  src/commands/database.rs
  tracker/src/task.rs
  tracker/src/task/registry.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1367 feat: Improve git-log-pr
  scripts/git-log-prs
Labels: automerge

#1349 feat: Add `OBSERVER` mode to SQL repl along with SQL primer / cookbook
  docs/README.md
  docs/sql.md
  src/commands/sql.rs
  src/commands/sql/observer.rs
  src/commands/sql/repl.rs
  src/commands/sql/repl_command.rs
  tests/end_to_end_cases/sql_cli.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1369 feat: Add ingest_entries_bytes_total counter
  server/src/lib.rs
Labels: automerge

#1371 feat: add instrumentation via RED metrics in gRPC API
  Cargo.lock
  metrics/src/tests.rs
  query/Cargo.toml
  query/src/test.rs
  src/influxdb_ioxd/rpc.rs
  src/influxdb_ioxd/rpc/storage.rs
  src/influxdb_ioxd/rpc/storage/service.rs
Labels: automerge

#1373 feat: add row_count to chunks system table
  data_types/src/chunk.rs
  generated_types/protos/influxdata/iox/management/v1/chunk.proto
  mutable_buffer/src/chunk.rs
  read_buffer/src/chunk.rs
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/system_tables.rs
  server/src/query_tests/sql.rs
  tests/end_to_end_cases/management_api.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1383 fix(ci): Push each image into its own tag
  .circleci/config.yml
Labels: automerge

#1377 feat: add chunk size histogram
  metrics/src/lib.rs
  server/src/db.rs
  server/src/query_tests/utils.rs
Labels: automerge

#1387 fix: set nullability correctly for system tables
  server/src/db/system_tables.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1348 feat: tests for cases when data are in both RUB and OS
  object_store/src/disk.rs
  parquet_file/src/chunk.rs
  parquet_file/src/storage.rs
  parquet_file/src/table.rs
  server/Cargo.toml
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/chunk.rs
  server/src/query_tests/influxrpc/read_window_aggregate.rs
  server/src/query_tests/scenarios.rs
  server/src/query_tests/utils.rs
Labels: automerge

#1388 docs: Fix typo in comment
  metrics/src/tests.rs
Labels: automerge

#1378 refactor: remove additional uses of RecordBatch::try_new
  arrow_deps/src/util.rs
  query/src/exec.rs
  query/src/provider/adapter.rs
  src/commands/sql/repl.rs
  src/influxdb_ioxd/rpc/flight.rs
  src/influxdb_ioxd/rpc/storage/data.rs
  tests/end_to_end_cases/scenario.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1368 refactor: rename assert_table_eq to assert_batches_eq
  arrow_deps/src/test_util.rs
  internal_types/src/arrow/sort.rs
  mutable_buffer/src/chunk.rs
  query/src/provider/adapter.rs
  server/src/db.rs
  server/src/db/system_tables.rs
  server/src/lib.rs
  server/src/query_tests/influxrpc/field_columns.rs
  src/influxdb_ioxd/http.rs
  tests/end_to_end_cases/flight_api.rs
  tests/end_to_end_cases/system_tables.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1390 feat: Add gauge metric
  Cargo.lock
  metrics/Cargo.toml
  metrics/src/lib.rs
  metrics/src/metrics.rs
  metrics/src/tests.rs
Labels: automerge

#1391 refactor: include default labels
  server/src/db.rs
Labels: automerge

#1392 feat: allow gauges to be increased or decreased
  metrics/src/lib.rs
  metrics/src/metrics.rs
Labels: automerge

#1385 feat: add a id() method to `management::Operations`
  generated_types/src/google.rs
  tests/end_to_end_cases/management_api.rs
  tests/end_to_end_cases/sql_cli.rs
  tests/end_to_end_cases/system_tables.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1395 feat: warn on dropping from open partition
  server/src/db/lifecycle.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1396 refactor: rename closing to closed
  data_types/src/chunk.rs
  data_types/src/database_rules.rs
  generated_types/protos/influxdata/iox/management/v1/chunk.proto
  generated_types/protos/influxdata/iox/management/v1/database_rules.proto
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/chunk.rs
  server/src/db/lifecycle.rs
  server/src/db/system_tables.rs
  src/commands/database.rs
  tests/end_to_end_cases/management_api.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1398 refactor: write buffer to use sequenced entry and new segment
  data_types/src/database_rules.rs
  data_types/src/write_buffer.rs
  generated_types/protos/write_buffer.fbs
  generated_types/src/lib.rs
  generated_types/src/write_buffer_generated.rs
  internal_types/benches/benchmark.rs
  internal_types/src/data.rs
  internal_types/src/entry.rs
  internal_types/src/lib.rs
  server/src/buffer.rs
  server/src/config.rs
  server/src/db.rs
  server/src/lib.rs
  src/influxdb_ioxd/http.rs
Labels: automerge

#1399 feat: unload chunks from read buffer but keep them in object store
  parquet_file/src/chunk.rs
  parquet_file/src/table.rs
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/chunk.rs
  server/src/db/lifecycle.rs
Labels: automerge
