Repository influxdata/influxdb_iox, pull requests merged in 2021-09, with the labels that each got.

#2450 test: simplify testing around preserved catalog
  generated_types/build.rs
  iox_object_store/src/paths/parquet_file.rs
  parquet_file/src/catalog/api.rs
  parquet_file/src/catalog/cleanup.rs
  parquet_file/src/catalog/rebuild.rs
  parquet_file/src/catalog/test_helpers.rs
  parquet_file/src/metadata.rs
  parquet_file/src/storage.rs
  parquet_file/src/test_utils.rs
  server/src/db/catalog/chunk.rs
Labels: automerge

#2444 feat: Wire database deletion through the CLI, add tests for not including deleted databases in database list
  server/src/lib.rs
  src/commands/database.rs
  src/influxdb_ioxd/rpc/error.rs
  tests/end_to_end_cases/management_api.rs
  tests/end_to_end_cases/management_cli.rs
Labels: automerge

#2447 test: Database startup error when there are multiple active generations
  server/src/lib.rs
Labels: automerge

#2453 feat: "dump catalog" debug CLI
  Cargo.lock
  Cargo.toml
  parquet_file/src/catalog/dump.rs
  parquet_file/src/catalog/mod.rs
  src/commands/debug.rs
  src/commands/run.rs
  src/influxdb_ioxd.rs
  src/main.rs
  src/server_id.rs
  tests/end_to_end_cases/debug_cli.rs
  tests/end_to_end_cases/mod.rs
Labels: automerge

#2459 docs: add massif guide
  .gitignore
  Cargo.toml
  docs/images/screenshot_massif_visualizer.jpeg
  docs/valgrind.md
Labels: automerge

#2458 refactor: more flexible writer buffer config
  data_types/src/database_rules.rs
  generated_types/protos/influxdata/iox/management/v1/database_rules.proto
  generated_types/src/database_rules.rs
  iox_data_generator/src/bin/create_database.rs
  server/src/database.rs
  server/src/lib.rs
  tests/end_to_end_cases/scenario.rs
  tests/end_to_end_cases/write_buffer.rs
  write_buffer/src/config.rs
Labels: automerge

#2460 feat: forward connection config to Kafka write buffer
  tests/end_to_end_cases/scenario.rs
  write_buffer/src/config.rs
  write_buffer/src/kafka.rs
Labels: automerge

#2456 feat: correctly account MUB sizes
  arrow_util/src/string.rs
  mutable_buffer/src/chunk.rs
  mutable_buffer/src/column.rs
  query_tests/src/sql.rs
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/metrics.rs
  server/src/db/chunk.rs
  server/src/db/replay.rs
  tests/end_to_end_cases/management_api.rs
  tests/end_to_end_cases/management_cli.rs
Labels: automerge

#2358 feat: create initial performance test
  iox_data_generator/README.md
  perf/.gitignore
  perf/README.md
  perf/battery-0/datagen.toml
  perf/battery-0/foo.csv
  perf/battery-0/queries.toml
  perf/perf.py
  perf/requirements.txt
Labels: automerge, kodiak: merge.method = 'squash'

#2457 feat: Add list_deleted_databases API
  Cargo.lock
  data_types/src/deleted_database.rs
  data_types/src/lib.rs
  generated_types/protos/influxdata/iox/management/v1/service.proto
  generated_types/src/deleted_database.rs
  generated_types/src/lib.rs
  influxdb_iox_client/src/client/management.rs
  iox_object_store/Cargo.toml
  iox_object_store/src/lib.rs
  object_store/src/lib.rs
  object_store/src/memory.rs
  server/src/lib.rs
  src/commands/database.rs
  src/influxdb_ioxd/rpc/management.rs
  tests/end_to_end_cases/management_api.rs
  tests/end_to_end_cases/management_cli.rs
Labels: automerge

#2435 feat: migrate jemalloc metrics to `metric` crate
  Cargo.lock
  metric/src/lib.rs
  server/Cargo.toml
  server/src/lib.rs
  src/influxdb_ioxd.rs
  src/influxdb_ioxd/jemalloc.rs
  tests/end_to_end_cases/metrics.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2451 feat: expose job metrics
  data_types/src/job.rs
  server/src/application.rs
  server/src/job.rs
  server/src/lib.rs
  server/src/utils.rs
  tracker/src/task/history.rs
Labels: automerge

#2475 build: feature-gate arrow dep for mgmt client
  influxdb_iox_client/Cargo.toml
Labels: automerge

#2476 chore: `iox_data_generator` QA
  iox_data_generator/src/bin/create_database.rs
  iox_data_generator/src/bin/iox_data_generator.rs
  iox_data_generator/src/lib.rs
  iox_data_generator/src/substitution.rs
  iox_data_generator/src/write.rs
Labels: automerge

#2258 feat: row-level pruning during replay
  entry/src/entry.rs
  mutable_buffer/src/chunk.rs
  mutable_buffer/src/column.rs
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/catalog/chunk.rs
  server/src/db/replay.rs
  server_benchmarks/benches/snapshot.rs
  server_benchmarks/benches/write.rs
Labels: automerge

#2448 feat: API and framework for Delete parsing and testing
  Cargo.lock
  data_types/src/job.rs
  data_types/src/partition_metadata.rs
  generated_types/Cargo.toml
  generated_types/protos/influxdata/iox/management/v1/jobs.proto
  generated_types/protos/influxdata/iox/management/v1/parse_delete.proto
  generated_types/protos/influxdata/iox/management/v1/service.proto
  generated_types/src/job.rs
  generated_types/src/lib.rs
  generated_types/src/parse_delete.rs
  influxdb_iox_client/Cargo.toml
  influxdb_iox_client/src/client/flight.rs
  influxdb_iox_client/src/client/management.rs
  influxdb_line_protocol/Cargo.toml
  influxdb_line_protocol/src/delete_parser.rs
  influxdb_line_protocol/src/lib.rs
  query/src/lib.rs
  query/src/predicate.rs
  query/src/test.rs
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/chunk.rs
  server/src/lib.rs
  src/commands/database/partition.rs
  src/influxdb_ioxd/rpc/error.rs
  src/influxdb_ioxd/rpc/management.rs
  tests/end_to_end_cases/management_api.rs
Labels: automerge

#2474 feat: auto-creation of sequencers by write buffer
  data_types/src/database_rules.rs
  generated_types/protos/influxdata/iox/management/v1/database_rules.proto
  generated_types/src/database_rules.rs
  server/src/database.rs
  server/src/db.rs
  server/src/db/replay.rs
  src/influxdb_ioxd/rpc/error.rs
  tests/end_to_end_cases/scenario.rs
  tests/end_to_end_cases/write_buffer.rs
  write_buffer/Cargo.toml
  write_buffer/src/config.rs
  write_buffer/src/core.rs
  write_buffer/src/kafka.rs
  write_buffer/src/mock.rs
Labels: automerge

#2481 feat: migrate lock metrics to metric crate
  Cargo.lock
  metric/src/lib.rs
  server/src/database.rs
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/catalog/metrics.rs
  server/src/db/catalog/partition.rs
  server/src/db/catalog/table.rs
  server/src/db/load.rs
  server/src/utils.rs
  tracker/Cargo.toml
  tracker/src/lock.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2479 fix: perf broken after Protobuf changes
  .circleci/config.yml
  perf/perf.py
  perf/requirements.txt
Labels: automerge, kodiak: merge.method = 'squash'

#2486 feat: migrate catalog timestamp summary to metric crate
  metric/src/duration.rs
  metric/src/histogram.rs
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/metrics.rs
  tests/end_to_end_cases/metrics.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2482 fix: job metrics
  Cargo.lock
  metric_exporters/Cargo.toml
  metric_exporters/src/lib.rs
  server/src/job.rs
  server/src/lib.rs
Labels: automerge

#2495 refactor: remove process clock
  entry/src/entry.rs
  server/src/db.rs
  server/src/db/process_clock.rs
Labels: automerge

#2496 chore: fix perf again, after another protobuf change
  perf/perf.py
Labels: automerge

#2494 feat: add RecorderCollection
  metric/src/cumulative.rs
  metric/src/metric.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2492 fix: test_logging port collision
  tests/end_to_end_cases/influxdb_ioxd.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2491 feat: migrate chunk metrics
  Cargo.lock
  mutable_buffer/Cargo.toml
  mutable_buffer/src/chunk.rs
  parquet_file/Cargo.toml
  parquet_file/src/chunk.rs
  server/src/database.rs
  server/src/db.rs
  server/src/db/catalog/metrics.rs
  server/src/db/lifecycle/write.rs
  server/src/db/load.rs
  server/src/utils.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2488 feat: Finally have the delete predicate parsed and invoked from client
  Cargo.lock
  generated_types/protos/influxdata/iox/management/v1/service.proto
  generated_types/src/lib.rs
  generated_types/src/parse_delete.rs
  influxdb_iox_client/Cargo.toml
  influxdb_iox_client/src/client/management.rs
  influxdb_line_protocol/Cargo.toml
  influxdb_line_protocol/src/delete_parser.rs
  query/src/predicate.rs
  server/src/lib.rs
  src/influxdb_ioxd/rpc/error.rs
  src/influxdb_ioxd/rpc/management.rs
  tests/end_to_end_cases/management_api.rs
Labels: automerge

#2500 refactor: move ParseDeletePredicate to predicate.rs
  Cargo.lock
  influxdb_line_protocol/Cargo.toml
  influxdb_line_protocol/src/delete_parser.rs
  influxdb_line_protocol/src/lib.rs
  query/Cargo.toml
  query/src/predicate.rs
  src/influxdb_ioxd/rpc/management.rs
Labels: automerge

#2502 feat: response classification (#2273)
  src/influxdb_ioxd.rs
  trace/src/span.rs
  trace_http/src/tower.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2489 feat: remove deprecated catalog metrics
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/metrics.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2433 feat: Less errors on update_database_rules
  server/src/database.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2503 chore: Rust 1.55
  influxdb_line_protocol/src/lib.rs
  iox_object_store/src/lib.rs
  query/src/provider/overlap.rs
  rust-toolchain.toml
  server/src/db/lifecycle/persist.rs
  trace/src/lib.rs
  trace_exporters/src/lib.rs
  trace_http/src/lib.rs
  tracker/src/task.rs
Labels: automerge

#2498 feat: enable tracing for http API (#2273)
  Cargo.lock
  Cargo.toml
  src/influxdb_ioxd.rs
  src/influxdb_ioxd/http.rs
  src/influxdb_ioxd/http/tower.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2507 docs: Add instructions for locally seeing distributed tracing
  CONTRIBUTING.md
Labels: automerge, kodiak: merge.method = 'squash'

#2504 docs: Add usecase to freezable doc string
  internal_types/src/freezable.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2501 fix: checksum rustup in CI
  .circleci/config.yml
  scripts/install_rustup.sh
Labels: automerge, kodiak: merge.method = 'squash'

#2506 chore: log tracing config
  trace_exporters/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2509 chore: Update datafusion (and arrow et al) dependencies
  Cargo.lock
  datafusion/Cargo.toml
  query/src/frontend/influxrpc.rs
  query/src/func/selectors.rs
  query_tests/src/sql.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2510 feat: migrate read buffer metrics to metric crate
  Cargo.lock
  data_types/src/chunk_metadata.rs
  metric/src/cumulative.rs
  metric/src/lib.rs
  metric/src/metric.rs
  read_buffer/Cargo.toml
  read_buffer/src/chunk.rs
  server/src/db.rs
  server/src/db/catalog/partition.rs
  server/src/db/lifecycle.rs
  server/src/db/lifecycle/compact.rs
  server/src/db/lifecycle/move_chunk.rs
  server/src/db/lifecycle/persist.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2516 feat: migrate chunk pruning metrics
  Cargo.lock
  query/Cargo.toml
  query_tests/Cargo.toml
  query_tests/src/pruning.rs
  server/src/db.rs
  server/src/db/access.rs
  server/src/db/chunk.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2490 feat: migrate remaining catalog metrics to new crate
  metric/src/cumulative.rs
  metric/src/metric.rs
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/metrics.rs
  server/src/db/catalog/partition.rs
  server/src/db/catalog/table.rs
  server/src/db/load.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2466 docs: update help text to show command to run the server
  src/main.rs
Labels: automerge

#2467 fix: Return same error when querying deleted vs uncreated database
  server/src/lib.rs
Labels: automerge

#2511 feat: save delete predicates in chunks
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/partition.rs
  server/src/db/chunk.rs
  server/src/db/lifecycle/compact.rs
  server/src/db/lifecycle/persist.rs
  server/src/db/load.rs
  tests/end_to_end_cases/management_api.rs
Labels: automerge

#2465 test: Ensure that a deleted and recreated database returns new data
  tests/end_to_end_cases/deletes.rs
  tests/end_to_end_cases/mod.rs
Labels: automerge

#2508 feat: migrate http metrics to metric crate
  Cargo.lock
  metric/src/duration.rs
  metric/src/lib.rs
  server/src/lib.rs
  src/influxdb_ioxd/http.rs
  src/influxdb_ioxd/http/tower.rs
  src/influxdb_ioxd/rpc.rs
  src/influxdb_ioxd/rpc/storage.rs
  src/influxdb_ioxd/rpc/storage/service.rs
  trace_http/Cargo.toml
  trace_http/src/classify.rs
  trace_http/src/lib.rs
  trace_http/src/metrics.rs
  trace_http/src/tower.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2520 fix: MockBufferForReading waker registration
  write_buffer/src/mock.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2521 chore: Update dependencies (including datafusion)
  Cargo.lock
  datafusion/Cargo.toml
  perf/battery-0/foo.csv
  perf/battery-0/queries.toml
  query/src/exec/schema_pivot.rs
  query/src/exec/split.rs
  query/src/provider.rs
  query/src/provider/deduplicate.rs
  query/src/provider/physical.rs
  query/src/statistics.rs
  query_tests/cases/in/stats_plans.expected
  server/src/db/system_tables.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2499 feat: Add pre-generated values and tag sets to data generator
  Cargo.lock
  iox_data_generator/Cargo.toml
  iox_data_generator/benches/point_generation.rs
  iox_data_generator/schemas/storage_cardinality_example.toml
  iox_data_generator/src/bin/iox_data_generator.rs
  iox_data_generator/src/lib.rs
  iox_data_generator/src/specification.rs
  iox_data_generator/src/substitution.rs
  iox_data_generator/src/tag_set.rs
  iox_data_generator/src/write.rs
Labels: automerge

#2517 feat: show number of stripped bytes in catalog dump
  parquet_file/src/catalog/dump.rs
  src/commands/debug.rs
Labels: automerge

#2524 feat: prune old transactions from preserved catalog
  Cargo.lock
  Cargo.toml
  data_types/src/database_rules.rs
  generated_types/protos/influxdata/iox/management/v1/database_rules.proto
  generated_types/src/database_rules/lifecycle.rs
  parquet_file/src/catalog/mod.rs
  parquet_file/src/catalog/prune.rs
  server/src/db.rs
  src/commands/database.rs
  tests/end_to_end_cases/management_api.rs
Labels: automerge

#2526 refactor: stricter delete predicate TS parsing
  Cargo.lock
  query/Cargo.toml
  query/src/predicate.rs
Labels: automerge

#2480 fix: order chunks correctly during query processing
  data_types/src/chunk_metadata.rs
  generated_types/protos/influxdata/iox/catalog/v1/parquet_metadata.proto
  generated_types/protos/influxdata/iox/management/v1/chunk.proto
  generated_types/src/chunk.rs
  lifecycle/src/lib.rs
  lifecycle/src/policy.rs
  parquet_file/src/catalog/api.rs
  parquet_file/src/catalog/dump.rs
  parquet_file/src/catalog/rebuild.rs
  parquet_file/src/metadata.rs
  parquet_file/src/storage.rs
  parquet_file/src/test_utils.rs
  query/src/lib.rs
  query/src/provider.rs
  query/src/test.rs
  query_tests/cases/in/chunk_order.expected
  query_tests/cases/in/chunk_order.sql
  query_tests/src/cases.rs
  query_tests/src/scenarios.rs
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/partition.rs
  server/src/db/chunk.rs
  server/src/db/lifecycle.rs
  server/src/db/lifecycle/compact.rs
  server/src/db/lifecycle/drop.rs
  server/src/db/lifecycle/persist.rs
  server/src/db/lifecycle/write.rs
  server/src/db/load.rs
  server/src/db/system_tables/chunks.rs
  server/src/db/system_tables/columns.rs
  tests/end_to_end_cases/management_api.rs
Labels: automerge

#2523 fix: emit traces to Jaeger in perf.py
  .circleci/config.yml
  perf/perf.py
Labels: automerge

#2527 refactor: move `predicate` into its own crate
  Cargo.lock
  Cargo.toml
  parquet_file/Cargo.toml
  parquet_file/src/chunk.rs
  parquet_file/src/storage.rs
  predicate/Cargo.toml
  predicate/src/lib.rs
  predicate/src/predicate.rs
  predicate/src/regex.rs
  query/Cargo.toml
  query/src/frontend/influxrpc.rs
  query/src/func.rs
  query/src/lib.rs
  query/src/provider.rs
  query/src/provider/physical.rs
  query/src/pruning.rs
  query_tests/Cargo.toml
  query_tests/src/influxrpc/field_columns.rs
  query_tests/src/influxrpc/read_filter.rs
  query_tests/src/influxrpc/read_group.rs
  query_tests/src/influxrpc/read_window_aggregate.rs
  query_tests/src/influxrpc/table_names.rs
  query_tests/src/influxrpc/tag_keys.rs
  query_tests/src/influxrpc/tag_values.rs
  query_tests/src/pruning.rs
  query_tests/src/table_schema.rs
  server/Cargo.toml
  server/src/db.rs
  server/src/db/access.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/partition.rs
  server/src/db/chunk.rs
  server/src/db/lifecycle/compact.rs
  server/src/db/lifecycle/persist.rs
  server/src/db/load.rs
  server/src/db/pred.rs
  server_benchmarks/Cargo.toml
  server_benchmarks/benches/read_filter.rs
  server_benchmarks/benches/read_group.rs
  server_benchmarks/benches/tag_values.rs
  src/influxdb_ioxd/planner.rs
  src/influxdb_ioxd/rpc/management.rs
  src/influxdb_ioxd/rpc/storage/expr.rs
  src/influxdb_ioxd/rpc/storage/service.rs
Labels: automerge

#2531 refactor: introduce `ChunkOrder` type
  data_types/src/chunk_metadata.rs
  generated_types/src/chunk.rs
  lifecycle/src/lib.rs
  lifecycle/src/policy.rs
  parquet_file/src/catalog/dump.rs
  parquet_file/src/catalog/rebuild.rs
  parquet_file/src/metadata.rs
  parquet_file/src/storage.rs
  parquet_file/src/test_utils.rs
  query/src/lib.rs
  query/src/test.rs
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/partition.rs
  server/src/db/chunk.rs
  server/src/db/lifecycle.rs
  server/src/db/lifecycle/compact.rs
  server/src/db/lifecycle/persist.rs
  server/src/db/system_tables/chunks.rs
  server/src/db/system_tables/columns.rs
Labels: automerge

#2530 fix: reset Database background worker on deletion
  server/src/database.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2532 refactor: decouple `parquet_file` from `query`
  Cargo.lock
  datafusion_util/Cargo.toml
  datafusion_util/src/lib.rs
  parquet_file/Cargo.toml
  parquet_file/src/storage.rs
  query/src/exec.rs
  query/src/exec/split.rs
  query/src/exec/stream.rs
  query/src/provider/deduplicate.rs
Labels: automerge

#2535 refactor: make `time_of_write` a parameter
  server/src/db.rs
  server/src/db/replay.rs
  server/src/lib.rs
  server/src/write_buffer.rs
Labels: automerge

#2533 feat: shutdown WriteBufferConsumer on drop
  server/src/write_buffer.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2537 feat: `Predicate` serialization
  Cargo.lock
  generated_types/build.rs
  generated_types/protos/influxdata/iox/catalog/v1/predicate.proto
  predicate/Cargo.toml
  predicate/src/lib.rs
  predicate/src/serialize.rs
Labels: automerge

#2536 feat: migrate write buffer metrics
  entry/src/entry.rs
  metric/src/metric.rs
  server/src/database.rs
  server/src/db/replay.rs
  server/src/write_buffer.rs
  server/src/write_buffer/metrics.rs
  trace_http/src/metrics.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2543 fix: report correct DatabaseStateCode
  data_types/src/database_state.rs
  data_types/src/lib.rs
  generated_types/protos/influxdata/iox/management/v1/service.proto
  generated_types/src/database_state.rs
  server/src/database.rs
  server/src/lib.rs
  src/influxdb_ioxd/rpc/management.rs
  tests/end_to_end_cases/management_api.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2529 feat: Translate DataFusion execution metrics to IOx Spans
  query/src/exec.rs
  query/src/exec/context.rs
  query/src/exec/query_tracing.rs
  src/influxdb_ioxd.rs
  trace/src/span.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2542 feat: migrate http ingest metrics
  Cargo.lock
  Cargo.toml
  data_types/src/database_rules.rs
  generated_types/src/database_rules/shard.rs
  server/src/database.rs
  server/src/database/metrics.rs
  server/src/lib.rs
  src/influxdb_ioxd/http.rs
  src/influxdb_ioxd/http/metrics.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2552 feat: remove metrics crate
  Cargo.lock
  Cargo.toml
  metrics/Cargo.toml
  metrics/src/gauge.rs
  metrics/src/lib.rs
  metrics/src/metrics.rs
  metrics/src/observer.rs
  metrics/src/tests.rs
  mutable_buffer/src/chunk.rs
  parquet_file/src/chunk.rs
  query_tests/src/pruning.rs
  read_buffer/src/chunk.rs
  server/Cargo.toml
  server/src/application.rs
  server/src/database.rs
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/metrics.rs
  server/src/db/lifecycle/compact.rs
  server/src/db/lifecycle/move_chunk.rs
  server/src/db/lifecycle/persist.rs
  server/src/db/lifecycle/write.rs
  server/src/db/load.rs
  server/src/job.rs
  server/src/lib.rs
  server/src/utils.rs
  server/src/write_buffer.rs
  src/influxdb_ioxd.rs
  src/influxdb_ioxd/http.rs
  src/influxdb_ioxd/rpc.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2547 test: Check for other error Database States
  tests/end_to_end_cases/management_api.rs
Labels: automerge

#2545 chore: Update datafusion + other deps (again!)
  Cargo.lock
  datafusion/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#2556 refactor: split preserved catalog `api` into `core` and `interface`
  parquet_file/src/catalog/cleanup.rs
  parquet_file/src/catalog/core.rs
  parquet_file/src/catalog/dump.rs
  parquet_file/src/catalog/interface.rs
  parquet_file/src/catalog/mod.rs
  parquet_file/src/catalog/prune.rs
  parquet_file/src/catalog/rebuild.rs
  parquet_file/src/catalog/test_helpers.rs
  parquet_file/src/metadata.rs
  server/src/database.rs
  server/src/db.rs
  server/src/db/lifecycle/error.rs
  server/src/db/lifecycle/write.rs
  server/src/db/load.rs
  server/src/lib.rs
Labels: automerge

#2555 fix: Ensure byte trimmed floats can handle arbitrary float literals
  read_buffer/src/column.rs
  read_buffer/src/column/encoding/scalar/fixed.rs
  read_buffer/src/column/encoding/scalar/fixed_null.rs
  read_buffer/src/column/encoding/scalar/rle.rs
  read_buffer/src/column/encoding/scalar/transcoders.rs
  read_buffer/src/column/float.rs
Labels: automerge

#2551 refactor: Add SpanContext:new() to make a new span
  query/src/exec/query_tracing.rs
  trace/src/ctx.rs
  trace/src/span.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2541 test: even more time-related lifting
  server/src/db.rs
  server/src/db/chunk.rs
  server/src/db/lifecycle/compact.rs
Labels: automerge

#2522 feat: push delete predicate down to RUB and OS chunks to eliminate deleted data at query time
  predicate/src/predicate.rs
  query/src/frontend/influxrpc.rs
  query/src/lib.rs
  query/src/provider/physical.rs
  query/src/test.rs
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/chunk.rs
  server/src/db/lifecycle/persist.rs
  server/src/db/lifecycle/write.rs
  server/src/db/load.rs
Labels: automerge

#2553 fix: Capture query execution traces for storage gRPC queries as well
  query/src/exec/context.rs
  query/src/exec/query_tracing.rs
  server/src/db/lifecycle/compact.rs
  server/src/db/lifecycle/move_chunk.rs
  server/src/db/lifecycle/persist.rs
  src/influxdb_ioxd.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2561 refactor: `Arc<Vec<...>>` => `Vec<Arc<...>>` for del predicates
  predicate/src/predicate.rs
  query/src/lib.rs
  query/src/test.rs
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/partition.rs
  server/src/db/chunk.rs
  server/src/db/lifecycle/compact.rs
  server/src/db/lifecycle/persist.rs
  server/src/db/load.rs
  src/influxdb_ioxd/rpc/management.rs
Labels: automerge

#2560 feat: add pbjson bytes support
  Cargo.lock
  pbjson/Cargo.toml
  pbjson/src/lib.rs
  pbjson_build/src/generator/message.rs
  pbjson_build/src/message.rs
  pbjson_test/protos/syntax3.proto
  pbjson_test/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2557 feat: remove legacy http list partitions endpoint
  src/influxdb_ioxd/http.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2461 perf: Don't open the output file each time we write.
  iox_data_generator/src/lib.rs
  iox_data_generator/src/write.rs
Labels: automerge

#2562 feat: migrate operations CLI to use pbjson
  data_types/src/job.rs
  generated_types/protos/influxdata/iox/management/v1/jobs.proto
  generated_types/src/google.rs
  generated_types/src/job.rs
  influxdb_iox_client/src/client/management.rs
  influxdb_iox_client/src/client/operations.rs
  src/commands/database/partition.rs
  src/commands/database/recover.rs
  src/commands/operations.rs
  tests/end_to_end_cases/management_api.rs
  tests/end_to_end_cases/management_cli.rs
  tests/end_to_end_cases/operations_api.rs
  tests/end_to_end_cases/operations_cli.rs
  tests/end_to_end_cases/persistence.rs
  tests/end_to_end_cases/scenario.rs
  tests/end_to_end_cases/sql_cli.rs
  tests/end_to_end_cases/system_tables.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2565 test: tests for delete
  query_tests/Cargo.toml
  query_tests/src/scenarios.rs
  query_tests/src/sql.rs
  server/src/db.rs
Labels: automerge

#2464 feat: Add an API for restoring a database that was marked deleted
  generated_types/protos/influxdata/iox/management/v1/service.proto
  influxdb_iox_client/src/client/management.rs
  iox_object_store/src/lib.rs
  server/src/database.rs
  server/src/lib.rs
  src/commands/database.rs
  src/influxdb_ioxd/rpc/error.rs
  src/influxdb_ioxd/rpc/management.rs
  tests/end_to_end_cases/management_cli.rs
Labels: automerge

#2566 feat: Detailed database list command
  data_types/src/detailed_database.rs
  data_types/src/lib.rs
  generated_types/protos/influxdata/iox/management/v1/service.proto
  generated_types/src/deleted_database.rs
  generated_types/src/detailed_database.rs
  generated_types/src/lib.rs
  influxdb_iox_client/src/client/management.rs
  iox_object_store/src/lib.rs
  server/src/database.rs
  server/src/lib.rs
  src/commands/database.rs
  src/influxdb_ioxd/rpc/management.rs
  tests/end_to_end_cases/management_cli.rs
Labels: automerge

#2559 feat: alter http query endpoint
  perf/perf.py
  src/influxdb_ioxd/http.rs
  tests/common/server_fixture.rs
  tests/end_to_end_cases/read_api.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2577 feat: remove human format
  Cargo.lock
  packers/Cargo.toml
  packers/src/stats.rs
Labels: automerge, kodiak: merge.method = 'squash', dependencies

#2574 feat: remove parse_duration
  Cargo.lock
  Cargo.toml
  iox_data_generator/Cargo.toml
  iox_data_generator/src/agent.rs
  src/commands/database.rs
Labels: automerge, kodiak: merge.method = 'squash', dependencies, security

#2573 feat: disable Snafu futures feature
  Cargo.lock
  object_store/Cargo.toml
  object_store/src/aws.rs
  object_store/src/disk.rs
  object_store/src/gcp.rs
Labels: automerge, kodiak: merge.method = 'squash', dependencies

#2576 feat: don't use opentelemetry async trace exporter
  Cargo.lock
  trace_exporters/Cargo.toml
  trace_exporters/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash', dependencies

#2528 feat: compress encoded parquet metadata
  Cargo.lock
  generated_types/build.rs
  generated_types/protos/influxdata/iox/catalog/v1/catalog.proto
  generated_types/protos/influxdata/iox/catalog/v1/parquet_metadata.proto
  parquet_file/Cargo.toml
  parquet_file/src/catalog/core.rs
  parquet_file/src/catalog/dump.rs
  parquet_file/src/metadata.rs
  server/src/db.rs
  server/src/db/lifecycle.rs
  server/src/db/lifecycle/persist.rs
  server/src/db/lifecycle/write.rs
Labels: automerge

#2586 feat: remove routerify
  Cargo.lock
  Cargo.toml
  src/influxdb_ioxd/http.rs
  src/influxdb_ioxd/http/tower.rs
Labels: automerge, kodiak: merge.method = 'squash', dependencies

#2580 feat: disable bytes serde
  Cargo.lock
  generated_types/Cargo.toml
  google_types/Cargo.toml
  grpc-router/Cargo.toml
  influxdb2_client/Cargo.toml
  server/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash', dependencies

#2578 feat: disable prometheus protobuf
  Cargo.lock
  metric_exporters/Cargo.toml
  metric_exporters/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash', dependencies

#2564 feat: delete catalog pres. catalog <=> in-mem catalog API
  Cargo.lock
  data_types/src/timestamp.rs
  datafusion/Cargo.toml
  parquet_file/src/catalog/cleanup.rs
  parquet_file/src/catalog/core.rs
  parquet_file/src/catalog/interface.rs
  parquet_file/src/catalog/prune.rs
  parquet_file/src/catalog/test_helpers.rs
  predicate/src/predicate.rs
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/load.rs
Labels: automerge

#2572 feat: apply negated delete predicates during scan
  predicate/src/predicate.rs
  predicate/src/serialize.rs
  query/src/provider.rs
  query/src/util.rs
  query_tests/src/scenarios.rs
  query_tests/src/sql.rs
  server/src/db/chunk.rs
  server/src/db/lifecycle/move_chunk.rs
  tests/end_to_end_cases/influxdb_ioxd.rs
  tests/end_to_end_cases/management_api.rs
Labels: automerge

#2588 refactor: introduce `ChunkId` type
  data_types/src/chunk_metadata.rs
  data_types/src/job.rs
  generated_types/src/chunk.rs
  generated_types/src/job.rs
  iox_object_store/src/lib.rs
  iox_object_store/src/paths/parquet_file.rs
  lifecycle/src/lib.rs
  lifecycle/src/policy.rs
  parquet_file/src/catalog/dump.rs
  parquet_file/src/catalog/interface.rs
  parquet_file/src/catalog/rebuild.rs
  parquet_file/src/catalog/test_helpers.rs
  parquet_file/src/metadata.rs
  parquet_file/src/storage.rs
  parquet_file/src/test_utils.rs
  query/src/frontend/influxrpc.rs
  query/src/lib.rs
  query/src/provider.rs
  query/src/test.rs
  query_tests/src/scenarios.rs
  server/src/db.rs
  server/src/db/access.rs
  server/src/db/catalog.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/partition.rs
  server/src/db/chunk.rs
  server/src/db/lifecycle.rs
  server/src/db/system_tables/chunks.rs
  server/src/db/system_tables/columns.rs
  server/src/db/system_tables/operations.rs
  server/src/lib.rs
  server_benchmarks/benches/catalog_persistence.rs
  src/influxdb_ioxd/rpc/management.rs
  src/influxdb_ioxd/rpc/storage/service.rs
  tests/end_to_end_cases/management_cli.rs
  tests/end_to_end_cases/persistence.rs
Labels: automerge

#2579 feat: disable rustyline dirs-next dependency
  Cargo.lock
  Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash', dependencies

#2589 feat: teach preserved catalog to handle delete predicates
  generated_types/protos/influxdata/iox/catalog/v1/catalog.proto
  parquet_file/src/catalog/core.rs
  parquet_file/src/catalog/dump.rs
  parquet_file/src/catalog/test_helpers.rs
Labels: automerge

#2592 chore: update DataFusion
  Cargo.lock
  datafusion/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#2596 test: do not (ab)use the panic hook for replay tests
  server/src/db/replay.rs
Labels: automerge

#2597 chore: upgrade azure dependencies
  .github/dependabot.yml
  Cargo.lock
  object_store/Cargo.toml
  object_store/src/azure.rs
Labels: automerge

#2599 chore: fix dependabot config
  .github/dependabot.yml
Labels: automerge

#2598 fix: bubble up write errors
  influxdb_iox_client/src/client/write.rs
  server/src/database.rs
  server/src/lib.rs
  src/influxdb_ioxd/rpc/error.rs
  tests/end_to_end_cases/write_api.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2595 ci: add cargo audit
  .cargo/audit.toml
  .circleci/config.yml
Labels: automerge

#2594 test: Add end to end tracing test with mock Jaeger agent
  .circleci/config.yml
  tests/common/mod.rs
  tests/common/server_fixture.rs
  tests/common/udp_listener.rs
  tests/end_to_end_cases/metrics.rs
  tests/end_to_end_cases/mod.rs
  tests/end_to_end_cases/scenario.rs
  tests/end_to_end_cases/storage_api.rs
  tests/end_to_end_cases/tracing.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2601 fix: All chunks now are applied delete predicates during scan
  predicate/src/predicate.rs
  query/src/provider.rs
  query_tests/src/scenarios.rs
  query_tests/src/scenarios/delete.rs
  query_tests/src/sql.rs
Labels: automerge

#2604 test: turn all delete tests on
  query_tests/src/scenarios/delete.rs
  server/src/db/load.rs
Labels: automerge

#2605 feat: optimize scan for chunks without delete preidcates and without the need to sort output
  query/src/provider.rs
Labels: automerge

#2608 chore: clean up dependencies a bit
  Cargo.lock
  generated_types/Cargo.toml
  internal_types/Cargo.toml
  mutable_buffer/Cargo.toml
  object_store/Cargo.toml
  parquet_file/Cargo.toml
  write_buffer/Cargo.toml
Labels: automerge

#2602 chore: Update datafusion
  Cargo.lock
  datafusion/Cargo.toml
  query/src/exec/context.rs
  query/src/frontend.rs
  query/src/frontend/reorg.rs
  query/src/frontend/sql.rs
  query/src/provider.rs
  query_tests/src/pruning.rs
  query_tests/src/runner.rs
  query_tests/src/sql.rs
  server/src/db.rs
  server/src/db/lifecycle/compact.rs
  server/src/db/lifecycle/move_chunk.rs
  server/src/db/lifecycle/persist.rs
  server/src/db/replay.rs
  server/src/db/system_tables.rs
  server/src/lib.rs
  server/src/write_buffer.rs
  src/influxdb_ioxd/planner.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2591 feat: Add support for custom tracing header name via JAEGER_TRACE_CONTEXT_HEADER_NAME
  src/influxdb_ioxd.rs
  src/influxdb_ioxd/http.rs
  src/influxdb_ioxd/rpc.rs
  src/influxdb_ioxd/rpc/storage/service.rs
  tests/end_to_end_cases/tracing.rs
  trace/src/lib.rs
  trace_exporters/src/lib.rs
  trace_http/src/ctx.rs
  trace_http/src/tower.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2609 refactor: convert macros in `query_tests` to functions
  query_tests/src/influxrpc/field_columns.rs
  query_tests/src/influxrpc/read_filter.rs
  query_tests/src/influxrpc/read_group.rs
  query_tests/src/influxrpc/read_window_aggregate.rs
  query_tests/src/influxrpc/table_names.rs
  query_tests/src/influxrpc/tag_keys.rs
  query_tests/src/influxrpc/tag_values.rs
  query_tests/src/sql.rs
  query_tests/src/table_schema.rs
Labels: automerge

#2612 chore: update latest datafusion and use its lit_timestamp_nano
  Cargo.lock
  datafusion/Cargo.toml
  predicate/src/predicate.rs
Labels: automerge

#2606 feat: teach `Db` to preserve delete predicates
  parquet_file/src/catalog/cleanup.rs
  parquet_file/src/catalog/core.rs
  parquet_file/src/catalog/interface.rs
  parquet_file/src/catalog/test_helpers.rs
  server/src/db.rs
  server/src/db/lifecycle/write.rs
  server/src/db/load.rs
Labels: automerge

#2600 feat: Add support to create new traces in IOx via JAEGER_DEBUG_HEADER
  CONTRIBUTING.md
  perf/perf.py
  src/influxdb_ioxd.rs
  src/influxdb_ioxd/http.rs
  tests/end_to_end_cases/tracing.rs
  trace_exporters/src/lib.rs
  trace_http/src/ctx.rs
  trace_http/src/tower.rs
Labels: automerge

#2607 feat: implement jaeger-agent protocol directly
  .circleci/config.yml
  .gitattributes
  CONTRIBUTING.md
  Cargo.lock
  Cargo.toml
  Dockerfile
  perf/perf.py
  src/influxdb_ioxd.rs
  tests/end_to_end_cases/tracing.rs
  trace/src/span.rs
  trace_exporters/Cargo.toml
  trace_exporters/README.md
  trace_exporters/src/export.rs
  trace_exporters/src/jaeger.rs
  trace_exporters/src/jaeger/span.rs
  trace_exporters/src/lib.rs
  trace_exporters/src/otel.rs
  trace_exporters/src/thrift/agent.rs
  trace_exporters/src/thrift/jaeger.rs
  trace_exporters/src/thrift/zipkincore.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2615 chore: update itertools
  Cargo.lock
  iox_data_generator/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#2619 refactor: `CatalogChunk::add_delete_predicate` cannot fail
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/load.rs
Labels: automerge

#2617 test: more delete tests
  .circleci/config.yml
  README.md
  query_tests/src/scenarios/delete.rs
  query_tests/src/sql.rs
  tests/end_to_end_cases/management_api.rs
Labels: automerge

#2624 test: query with selection predicate on deleted data
  query_tests/src/sql.rs
Labels: automerge

#2621 refactor: make `Partition::force_drop_chunk` similar to `Partition::drop_chunk`
  server/src/db/catalog/partition.rs
  server/src/db/lifecycle/compact.rs
  server/src/db/lifecycle/persist.rs
Labels: automerge

#2623 fix: Revert "feat: remove routerify (#2586)"
  Cargo.lock
  Cargo.toml
  src/influxdb_ioxd/http.rs
  src/influxdb_ioxd/http/tower.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2620 feat: correct pbjson serialization of Timestamp and Duration
  Cargo.lock
  google_types/Cargo.toml
  google_types/build.rs
  google_types/src/duration.rs
  google_types/src/lib.rs
  google_types/src/timestamp.rs
  pbjson_build/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2631 feat: validate Read Buffer predicates
  read_buffer/benches/read_filter.rs
  read_buffer/src/chunk.rs
  read_buffer/src/table.rs
  server/src/db/chunk.rs
Labels: automerge

#2616 fix: `TRACES_EXPORTER_` to `JAEGER_DEBUG_NAME` and `JAEGER_TRACE_CONTEXT_HEADER_NAME`
  tests/end_to_end_cases/tracing.rs
  trace_exporters/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2632 refactor: tidy up debug CLI help
  src/commands/debug.rs
Labels: automerge

#2570 fix: Await on freeze handles instead of try_freeze/returning Transition errors
  server/src/database.rs
  src/influxdb_ioxd/rpc/management.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2634 refactor: store chunks in iteration order
  server/src/db/catalog/partition.rs
  server/src/db/lifecycle/compact.rs
  server/src/db/lifecycle/persist.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2635 chore: Update datafusion
  .circleci/config.yml
  Cargo.lock
  datafusion/Cargo.toml
  datafusion_util/src/lib.rs
  predicate/Cargo.toml
  predicate/src/predicate.rs
  query/Cargo.toml
  query_tests/cases/in/pushdown.expected
  query_tests/cases/in/stats_plans.expected
Labels: automerge, kodiak: merge.method = 'squash'

#2618 test: enable disabled predicate pushdown test
  query_tests/src/sql.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2641 revert: "feat(iox): Enable heappy again"
  .circleci/config.yml
Labels: automerge, kodiak: merge.method = 'squash'

#2639 fix: suppress dependabot thrift upgrade
  .github/dependabot.yml
Labels: automerge, kodiak: merge.method = 'squash'

#2648 feat: remove http tokio-tracing spans
  src/influxdb_ioxd/http.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2649 revert: "fix: Revert "feat: remove routerify (#2586)" (#2623)"
  Cargo.lock
  Cargo.toml
  src/influxdb_ioxd/http.rs
  src/influxdb_ioxd/http/tower.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2650 feat: use upstream pbjson
  Cargo.lock
  Cargo.toml
  generated_types/Cargo.toml
  generated_types/build.rs
  generated_types/src/chunk.rs
  generated_types/src/database_rules/lifecycle.rs
  generated_types/src/google.rs
  google_types/Cargo.toml
  google_types/build.rs
  google_types/protos/google/protobuf/types.proto
  google_types/src/duration.rs
  google_types/src/lib.rs
  google_types/src/timestamp.rs
  parquet_file/Cargo.toml
  parquet_file/src/metadata.rs
  pbjson/Cargo.toml
  pbjson/src/lib.rs
  pbjson_build/Cargo.toml
  pbjson_build/src/descriptor.rs
  pbjson_build/src/escape.rs
  pbjson_build/src/generator.rs
  pbjson_build/src/generator/enumeration.rs
  pbjson_build/src/generator/message.rs
  pbjson_build/src/lib.rs
  pbjson_build/src/message.rs
  pbjson_test/Cargo.toml
  pbjson_test/build.rs
  pbjson_test/protos/syntax3.proto
  pbjson_test/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2651 refactor: exhaust delete test scenarios (except multi partitions)
  query_tests/src/scenarios/delete.rs
  query_tests/src/sql.rs
Labels: automerge

#2655 chore: Make query logging a bit less verbose
  query/src/provider.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2654 fix: remove unused imports in proto
  generated_types/protos/influxdata/iox/management/v1/service.proto
Labels: automerge, kodiak: merge.method = 'squash'

#2625 fix: Retry S3 requests that fail with 5xx and remove streaming put API that wasn't used
  Cargo.lock
  iox_object_store/src/lib.rs
  object_store/Cargo.toml
  object_store/src/aws.rs
  object_store/src/azure.rs
  object_store/src/disk.rs
  object_store/src/dummy.rs
  object_store/src/gcp.rs
  object_store/src/lib.rs
  object_store/src/memory.rs
  object_store/src/throttle.rs
  parquet_file/src/catalog/core.rs
  parquet_file/src/catalog/internals/proto_io.rs
  parquet_file/src/storage.rs
  server/src/db.rs
  server/src/lib.rs
  server_benchmarks/benches/catalog_persistence.rs
  src/object_store.rs
Labels: automerge

#2656 test: more tests that includes the repro of 2546
  query_tests/src/scenarios/delete.rs
  query_tests/src/sql.rs
Labels: automerge

#2662 refactor: remove spurious warning
  src/influxdb_ioxd/rpc/flight.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2669 chore: suppress RUSTSEC-2021-0116, RUSTSEC-2021-0117 and RUSTSEC-2021-0118
  .cargo/audit.toml
Labels: automerge, kodiak: merge.method = 'squash'

#2661 fix: fallback to DataFusion predicates if unable to execute on RUB
  query_tests/src/sql.rs
  read_buffer/src/chunk.rs
  read_buffer/src/row_group.rs
  read_buffer/src/table.rs
  server/src/db/chunk.rs
  server/src/db/pred.rs
Labels: automerge

#2659 chore: expand protobuf documentation
  docs/protobuf.md
  generated_types/protos/influxdata/iox/management/v1/database_rules.proto
  generated_types/protos/influxdata/iox/management/v1/parse_delete.proto
  generated_types/protos/influxdata/iox/management/v1/partition.proto
  generated_types/protos/influxdata/iox/management/v1/service.proto
Labels: automerge, kodiak: merge.method = 'squash'

#2657 chore: update tracing and logging docs
  CONTRIBUTING.md
  docs/README.md
  docs/logging.md
  docs/tracing.md
Labels: automerge, kodiak: merge.method = 'squash'

#2671 fix: Reduce log noise when no files are deleted
  parquet_file/src/catalog/cleanup.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2673 test: use integer in predicates
  query_tests/src/sql.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2674 feat: remove move lifecycle action
  data_types/src/chunk_metadata.rs
  data_types/src/job.rs
  generated_types/protos/influxdata/iox/management/v1/chunk.proto
  generated_types/protos/influxdata/iox/management/v1/jobs.proto
  generated_types/src/chunk.rs
  generated_types/src/job.rs
  lifecycle/src/lib.rs
  lifecycle/src/policy.rs
  query_tests/cases/in/duplicates.expected
  query_tests/cases/in/duplicates.sql
  query_tests/src/README.md
  query_tests/src/pruning.rs
  query_tests/src/scenarios.rs
  query_tests/src/scenarios/delete.rs
  query_tests/src/sql.rs
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/partition.rs
  server/src/db/lifecycle.rs
  server/src/db/lifecycle/compact.rs
  server/src/db/lifecycle/move_chunk.rs
  server/src/lib.rs
  server_benchmarks/benches/catalog_persistence.rs
  tests/end_to_end_cases/management_api.rs
  tests/end_to_end_cases/management_cli.rs
  tests/end_to_end_cases/persistence.rs
  tests/end_to_end_cases/sql_cli.rs
  tests/end_to_end_cases/system_tables.rs
Labels: automerge, kodiak: merge.method = 'squash'
