Repository influxdata/influxdb_iox, pull requests merged in 2021-06, with the labels that each got.

#1585 refactor: change state structure for chunks
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/partition.rs
  server/src/db/chunk.rs
  server/src/db/lifecycle.rs
Labels: automerge

#1575 feat: Cache TableSummary, Schema in chunks
  mutable_buffer/src/chunk/snapshot.rs
  parquet_file/src/chunk.rs
  parquet_file/src/table.rs
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/chunk.rs
  server/src/db/lifecycle.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1593 chore: update dependencies
  Cargo.lock
Labels: automerge, kodiak: merge.method = 'squash'

#1591 refactor: avoid copying encoding name for stats
  read_buffer/src/column.rs
  read_buffer/src/column/boolean.rs
  read_buffer/src/column/float.rs
  read_buffer/src/column/integer.rs
  read_buffer/src/column/string.rs
Labels: automerge

#1580 refactor: Use ParquetExec from DataFusion to read parquet files
  Cargo.lock
  parquet_file/Cargo.toml
  parquet_file/src/storage.rs
  query/src/exec/context.rs
  server/src/query_tests/influxrpc/read_group.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1594 chore: update datafusion
  Cargo.lock
  datafusion/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#1597 fix: fix confusing log message during catalog replay
  server/src/db.rs
Labels: automerge

#1588 refactor: Remove last vestiges of multi-table chunks from PartitionChunk API
  mutable_buffer/src/chunk.rs
  mutable_buffer/src/chunk/snapshot.rs
  parquet_file/src/chunk.rs
  parquet_file/src/table.rs
  query/src/frontend/influxrpc.rs
  query/src/lib.rs
  query/src/plan/stringset.rs
  query/src/predicate.rs
  query/src/test.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/partition.rs
  server/src/db/chunk.rs
  server/src/query_tests/table_schema.rs
  src/influxdb_ioxd/rpc/storage/service.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1599 feat: Add more details to WritePoints error log
  src/influxdb_ioxd/http.rs
Labels: automerge

#1600 fix: Log more details on http errors
  src/influxdb_ioxd/http.rs
Labels: automerge

#1601 chore: update deps for datafusion
  Cargo.lock
  datafusion/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#1602 refactor: macro and tests for explains
  query/src/exec/context.rs
  query/src/provider.rs
  server/src/db/chunk.rs
  server/src/query_tests/sql.rs
Labels: automerge

#1598 refactor: clean-up chunk structure + add tests
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/partition.rs
  server/src/db/chunk.rs
  server/src/db/lifecycle.rs
Labels: automerge

#1589 feat: preserve and read timestamps to/from preserved catalog
  Cargo.lock
  generated_types/protos/influxdata/iox/catalog/v1/catalog.proto
  parquet_file/Cargo.toml
  parquet_file/src/catalog.rs
Labels: automerge

#1596 feat: add RLE support for integer columns
  read_buffer/src/column/encoding/scalar/rle.rs
  read_buffer/src/column/float.rs
  read_buffer/src/column/integer.rs
Labels: automerge

#1606 refactor: isolate DB loading and streamline error handling
  server/src/lib.rs
Labels: automerge

#1604 refactor: More cleanup related to multi-table chunks
  mutable_buffer/src/chunk/snapshot.rs
  parquet_file/src/chunk.rs
  server/src/db.rs
  server/src/db/chunk.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1610 test: prepare tests for deduplicate work
  query/src/provider.rs
  server/src/db/chunk.rs
  server/src/query_tests/scenarios.rs
  server/src/query_tests/sql.rs
Labels: automerge

#1611 feat: Add pruning module to query crate
  query/src/lib.rs
  query/src/pruning.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1605 feat: jitter background clean-up job + wait on first job
  Cargo.lock
  data_types/src/database_rules.rs
  generated_types/protos/influxdata/iox/management/v1/database_rules.proto
  generated_types/src/database_rules.rs
  parquet_file/src/cleanup.rs
  server/Cargo.toml
  server/src/db.rs
  server/src/lib.rs
  server/src/query_tests/utils.rs
  tests/end_to_end_cases/management_api.rs
Labels: automerge

#1616 fix: do not error on `list_with_delimiter` w/ non-existing prefix
  object_store/src/disk.rs
  object_store/src/lib.rs
Labels: automerge

#1608 refactor: Make it clear only partition_key and table name pruning happens in catalog
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/catalog/partition.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1617 feat: Compress Floats columns containg natural numbers
  read_buffer/src/chunk.rs
  read_buffer/src/column/encoding/scalar/transcoders.rs
  read_buffer/src/column/float.rs
  server/src/db.rs
Labels: automerge

#1619 feat: Preserve full debug infos in release builds
  .circleci/config.yml
Labels: automerge

#1592 feat: recover failed lifecycle actions (#1099)
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/catalog/chunk.rs
  server/src/db/lifecycle.rs
  tracker/src/task.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1609 ci: verify gpg signatures of dependencies in CI
  docker/Dockerfile.ci
Labels: automerge, kodiak: merge.method = 'squash'

#1622 fix: Fix logfmt escaping
  logfmt/src/lib.rs
  logfmt/tests/logging.rs
Labels: automerge

#1621 feat: limit number of files during storage cleanup
  parquet_file/src/cleanup.rs
  server/src/db.rs
Labels: automerge

#1625 feat: Add logfmts script to humanize timestamps
  scripts/logfmts
Labels: automerge

#1567 feat: Implement Chunk Pruning
  data_types/src/partition_metadata.rs
  query/src/frontend/influxrpc.rs
  query/src/lib.rs
  query/src/predicate.rs
  query/src/provider.rs
  query/src/provider/physical.rs
  query/src/test.rs
  server/src/db.rs
  server/src/db/access.rs
  server/src/db/catalog.rs
  server/src/db/chunk.rs
  server/src/db/lifecycle.rs
  server/src/query_tests.rs
  server/src/query_tests/pruning.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1626 fix: Revert Add more details to WritePoints error log
  src/influxdb_ioxd/http.rs
Labels: automerge

#1620 docs: add query for computing time ranges to cookbook
  docs/sql.md
Labels: automerge, kodiak: merge.method = 'squash'

#1628 refactor: Move `query_tests` and `server_benchmarks` into their own crate --> smaller `server`
  Cargo.lock
  Cargo.toml
  query_tests/Cargo.toml
  query_tests/src/influxrpc.rs
  query_tests/src/influxrpc/field_columns.rs
  query_tests/src/influxrpc/read_filter.rs
  query_tests/src/influxrpc/read_group.rs
  query_tests/src/influxrpc/read_window_aggregate.rs
  query_tests/src/influxrpc/table_names.rs
  query_tests/src/influxrpc/tag_keys.rs
  query_tests/src/influxrpc/tag_values.rs
  query_tests/src/influxrpc/util.rs
  query_tests/src/lib.rs
  query_tests/src/pruning.rs
  query_tests/src/scenarios.rs
  query_tests/src/sql.rs
  query_tests/src/table_schema.rs
  server/Cargo.toml
  server/src/db.rs
  server/src/db/process_clock.rs
  server/src/lib.rs
  server/src/utils.rs
  server_benchmarks/Cargo.toml
  server_benchmarks/benches/influxrpc.rs
  server_benchmarks/benches/read_filter.rs
  server_benchmarks/benches/read_group.rs
  server_benchmarks/benches/tag_values.rs
  server_benchmarks/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1635 feat: full foundation for deduplicate with todo functions to finish
  query/src/provider.rs
Labels: automerge

#1637 fix: Fix garbled log lines
  src/commands/tracing.rs
Labels: automerge

#1638 docs: add a comment w/ rationale for LineWriter
  src/commands/tracing.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1640 fix: give xlarge image to perf_image build step
  .circleci/config.yml
Labels: automerge

#1643 chore: fix flaky test
  tests/end_to_end_cases/management_api.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1639 chore: cleanup legacy TSM -> parquet code
  Cargo.lock
  Cargo.toml
  benches/line_protocol_to_parquet.rs
  ingest/Cargo.toml
  ingest/src/lib.rs
  ingest/src/parquet.rs
  ingest/src/parquet/error.rs
  ingest/src/parquet/metadata.rs
  ingest/src/parquet/stats.rs
  ingest/src/parquet/writer.rs
  ingest/tests/read_write.rs
  internal_types/src/schema/builder.rs
  src/commands/convert.rs
  src/commands/input.rs
  src/commands/meta.rs
  src/commands/stats.rs
  src/main.rs
  tests/commands.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1642 refactor: use field metadata to store influx types
  internal_types/src/schema.rs
  internal_types/src/schema/builder.rs
  mutable_buffer/src/table.rs
  parquet_file/src/test_utils.rs
  read_buffer/src/schema.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1511 fix: Delete all write-buffer related code
  CONTRIBUTING.md
  Cargo.lock
  Cargo.toml
  data_types/src/database_rules.rs
  data_types/src/http.rs
  data_types/src/lib.rs
  entry/Cargo.toml
  entry/benches/benchmark.rs
  entry/src/entry.fbs
  entry/src/entry.rs
  entry/src/entry_generated.rs
  generated_types/protos/influxdata/iox/management/v1/database_rules.proto
  generated_types/src/database_rules.rs
  generated_types/src/database_rules/write_buffer.rs
  influxdb_iox_client/src/client/write.rs
  mutable_buffer/benches/snapshot.rs
  mutable_buffer/benches/write.rs
  mutable_buffer/src/chunk.rs
  mutable_buffer/src/table.rs
  server/src/buffer.rs
  server/src/config.rs
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/catalog/chunk.rs
  server/src/db/lifecycle.rs
  server/src/db/process_clock.rs
  server/src/lib.rs
  server/src/utils.rs
  tests/end_to_end_cases/management_api.rs
  write_buffer/Cargo.toml
  write_buffer/src/lib.rs
  write_buffer/src/writer.rs
  write_buffer/tests/delete-up-to.rs
  write_buffer/tests/file_rollover.rs
  write_buffer/tests/helpers/mod.rs
  write_buffer/tests/no_concurrency.rs
  write_buffer/tests/total_size.rs
Labels: automerge

#1562 refactor: Preparations for optional Kafka write buffer
  entry/src/entry.rs
  server/src/db.rs
Labels: automerge

#1648 refactor: Remove a layer of channels in parquet read stream
  parquet_file/src/storage.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1629 feat: Prune on boolean column predicates too
  Cargo.lock
  datafusion/Cargo.toml
  query/src/pruning.rs
  query_tests/src/sql.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1631 feat: Mock write buffer + trait
  data_types/src/database_rules.rs
  entry/src/entry.fbs
  entry/src/entry.rs
  generated_types/protos/influxdata/iox/management/v1/database_rules.proto
  generated_types/src/database_rules.rs
  server/src/config.rs
  server/src/db.rs
  server/src/lib.rs
  server/src/utils.rs
  server/src/write_buffer.rs
  tests/end_to_end_cases/management_api.rs
Labels: automerge

#1657 feat: enable not equal operator for the influxrpc frontend
  query/src/frontend/influxrpc.rs
  query_tests/src/influxrpc/read_filter.rs
Labels: automerge

#1654 feat: Group chunks by potential overlap
  data_types/src/partition_metadata.rs
  internal_types/src/schema/builder.rs
  query/src/duplicate.rs
  query/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1659 refactor: move primary_key calculation to TableSummary
  data_types/src/partition_metadata.rs
  query/src/duplicate.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1662 feat: Hook up chunk grouping into provider
  query/src/lib.rs
  query/src/provider.rs
  query/src/pruning.rs
  query/src/test.rs
  server/src/db/chunk.rs
Labels: automerge

#1663 docs: Improve comments + whitespace
  query/src/provider.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1653 refactor: schema merge to give more control over field merging
  Cargo.lock
  internal_types/Cargo.toml
  internal_types/src/schema.rs
  internal_types/src/schema/builder.rs
  internal_types/src/schema/merge.rs
  query/src/frontend/influxrpc.rs
  query/src/provider.rs
  query/src/test.rs
  server/src/db/access.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1618 feat: move DB loading into background worker
  generated_types/protos/influxdata/iox/management/v1/service.proto
  influxdb_iox_client/src/client/management.rs
  server/src/lib.rs
  src/commands/server.rs
  src/influxdb_ioxd.rs
  src/influxdb_ioxd/http.rs
  src/influxdb_ioxd/rpc/error.rs
  src/influxdb_ioxd/rpc/management.rs
  tests/common/server_fixture.rs
  tests/end_to_end_cases/management_api.rs
  tests/end_to_end_cases/preservation.rs
  tests/end_to_end_cases/read_cli.rs
  tests/end_to_end_cases/write_api.rs
Labels: automerge

#1658 chore: remove more unused dependencies
  Cargo.lock
  Cargo.toml
  internal_types/Cargo.toml
  mutable_buffer/Cargo.toml
  server_benchmarks/Cargo.toml
  server_benchmarks/benches/encoders.rs
  server_benchmarks/benches/fixtures.rs
  server_benchmarks/benches/line_parser.rs
  server_benchmarks/benches/mapper.rs
  server_benchmarks/benches/packers.rs
  server_benchmarks/benches/run_bench.sh
  server_benchmarks/benches/scrape_benches.sh
  server_benchmarks/benches/snapshot.rs
  server_benchmarks/benches/storectl-bench.sh
  server_benchmarks/benches/write.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1669 fix: Fix bug in chunk overlap calculation due to nulls
  query/src/duplicate.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1666 feat: Add Sort operator into the deduplicate plan
  query/src/lib.rs
  query/src/provider.rs
  query/src/test.rs
  server/src/db/chunk.rs
Labels: automerge

#1670 refactor: extract server init code
  server/src/init.rs
  server/src/lib.rs
  src/influxdb_ioxd/http.rs
  src/influxdb_ioxd/rpc/error.rs
  src/influxdb_ioxd/rpc/management.rs
Labels: automerge

#1671 chore: enforce `clippy::future_not_send` for `parquet_file,object_store`
  object_store/src/buffer.rs
  object_store/src/lib.rs
  parquet_file/src/catalog.rs
  parquet_file/src/cleanup.rs
  parquet_file/src/lib.rs
  parquet_file/src/rebuild.rs
  server/src/db.rs
Labels: automerge

#1677 chore: enforce `clippy::future_not_send` for `influxdb_iox_client,influxdb2_client,query,tracker`
  influxdb2_client/src/api/write.rs
  influxdb2_client/src/lib.rs
  influxdb_iox_client/src/client/flight.rs
  influxdb_iox_client/src/client/health.rs
  influxdb_iox_client/src/client/management.rs
  influxdb_iox_client/src/client/write.rs
  influxdb_iox_client/src/connection.rs
  influxdb_iox_client/src/lib.rs
  query/src/lib.rs
  tracker/src/lib.rs
  tracker/src/task.rs
  tracker/src/task/history.rs
  tracker/src/task/registry.rs
Labels: automerge

#1673 chore: update dependencies
  Cargo.lock
  datafusion/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#1668 feat: catalog checkpointing infrastructure
  Cargo.lock
  generated_types/protos/influxdata/iox/catalog/v1/catalog.proto
  parquet_file/src/catalog.rs
  parquet_file/src/cleanup.rs
  parquet_file/src/rebuild.rs
  server/src/db.rs
  server_benchmarks/Cargo.toml
  server_benchmarks/benches/catalog_persistence.rs
  server_benchmarks/benches/influxrpc.rs
Labels: automerge

#1679 chore: enforce `clippy::future_not_send` for `server` + top-level crate
  server/src/lib.rs
  src/influxdb_ioxd/planner.rs
  src/influxdb_ioxd/rpc/operations.rs
  src/main.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1678 refactor: swap order of partition and table in in-memory catalog
  Cargo.lock
  data_types/src/partition_metadata.rs
  influxdb_iox_client/src/client/management.rs
  query_tests/src/influxrpc/read_window_aggregate.rs
  query_tests/src/pruning.rs
  query_tests/src/scenarios.rs
  server/Cargo.toml
  server/src/db.rs
  server/src/db/access.rs
  server/src/db/catalog.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/metrics.rs
  server/src/db/catalog/partition.rs
  server/src/db/catalog/table.rs
  server/src/db/lifecycle.rs
  server/src/db/system_tables.rs
  server/src/lib.rs
  src/commands/database/partition.rs
  src/influxdb_ioxd/rpc/error.rs
  src/influxdb_ioxd/rpc/management.rs
  tests/end_to_end_cases/management_api.rs
  tests/end_to_end_cases/preservation.rs
  tests/end_to_end_cases/sql_cli.rs
  tests/end_to_end_cases/system_tables.rs
  tracker/src/lock.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1676 feat: hook SortPreservingMergeExec into deduplication framework
  data_types/src/partition_metadata.rs
  query/src/provider.rs
  query/src/util.rs
Labels: automerge

#1684 fix: make pruning debug log less confusing
  query/src/pruning.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1687 fix: persistence to parquet by swapping order of arguments
  server/src/db/lifecycle.rs
  tests/end_to_end_cases/mod.rs
  tests/end_to_end_cases/persistence.rs
  tests/end_to_end_cases/scenario.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1688 fix: Expose jaeger knobs and default max-packet-size to something that works everywhere
  src/commands/run.rs
  src/commands/tracing.rs
Labels: automerge

#1690 refactor: inline `Table` into `parquet_file::chunk::Chunk`
  parquet_file/src/chunk.rs
  parquet_file/src/lib.rs
  parquet_file/src/metadata.rs
  parquet_file/src/table.rs
  parquet_file/src/test_utils.rs
  server/src/db.rs
  server/src/db/chunk.rs
Labels: automerge

#1692 refactor: combine preservation.rs and persistence.rs e2e tests
  tests/end_to_end_cases/mod.rs
  tests/end_to_end_cases/persistence.rs
  tests/end_to_end_cases/preservation.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1693 feat: add UnionExec on top of the scan activities
  query/src/provider.rs
  query/src/test.rs
Labels: automerge

#1681 feat: Implement LayeredTracing
  Cargo.lock
  Cargo.toml
  src/commands/layered_tracing.rs
  src/main.rs
Labels: automerge

#1700 refactor: export Read Buffer Chunk as RBChunk
  read_buffer/benches/database.rs
  read_buffer/benches/read_filter.rs
  read_buffer/src/lib.rs
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/chunk.rs
  server/src/db/lifecycle.rs
Labels: automerge

#1696 feat: wire up catalog checkpointing
  Cargo.lock
  data_types/src/database_rules.rs
  generated_types/protos/influxdata/iox/management/v1/database_rules.proto
  generated_types/src/database_rules/lifecycle.rs
  parquet_file/src/catalog.rs
  parquet_file/src/chunk.rs
  parquet_file/src/test_utils.rs
  server/Cargo.toml
  server/src/db.rs
  server/src/db/lifecycle.rs
  server/src/lib.rs
  server/src/utils.rs
  server_benchmarks/benches/catalog_persistence.rs
  src/commands/database.rs
  tests/end_to_end_cases/management_api.rs
Labels: automerge

#1706 refactor: read_filter debugging
  query/src/exec.rs
  src/influxdb_ioxd/rpc/storage/service.rs
Labels: automerge

#1708 chore: Update deps to get latest arrow
  Cargo.lock
  data_types/src/partition_metadata.rs
  influxdb_tsm/src/reader.rs
  metrics/src/lib.rs
  query/src/func/regex.rs
  rust-toolchain
Labels: automerge, kodiak: merge.method = 'squash'

#1709 refactor: more debug logging
  query/src/exec/seriesset.rs
Labels: automerge

#1702 refactor: Rename catalog::Chunk --> catalog::CatalogChunk
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/partition.rs
  server/src/db/chunk.rs
  server/src/db/lifecycle.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1707 refactor: wrap upstream parquet MD into struct + clean up interface
  Cargo.lock
  parquet_file/src/catalog.rs
  parquet_file/src/chunk.rs
  parquet_file/src/cleanup.rs
  parquet_file/src/metadata.rs
  parquet_file/src/rebuild.rs
  parquet_file/src/storage.rs
  parquet_file/src/storage_testing.rs
  parquet_file/src/test_utils.rs
  server/Cargo.toml
  server/src/db.rs
Labels: automerge

#1704 refactor: inline Table into mutable_buffer::chunk::Chunk
  mutable_buffer/src/chunk.rs
  mutable_buffer/src/chunk/snapshot.rs
  mutable_buffer/src/lib.rs
  mutable_buffer/src/table.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1710 fix: fix NaN+NULL handling in parquet stats
  parquet_file/src/metadata.rs
  parquet_file/src/storage_testing.rs
  parquet_file/src/test_utils.rs
Labels: automerge

#1701 feat: Lifecycle manager unloads, rather than drop, chunks when soft limit is hit
  query_tests/src/scenarios.rs
  server/src/db.rs
  server/src/db/lifecycle.rs
  server_benchmarks/benches/catalog_persistence.rs
  tests/common/server_fixture.rs
  tests/end_to_end_cases/persistence.rs
  tests/end_to_end_cases/scenario.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1711 refactor: rename mutable_buffer::Chunk --> mutable_buffer::MBChunk
  mutable_buffer/src/chunk.rs
  mutable_buffer/src/chunk/snapshot.rs
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/partition.rs
  server/src/db/lifecycle.rs
  server_benchmarks/benches/snapshot.rs
  server_benchmarks/benches/write.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1697 feat: create checkpoint during catalog rebuild
  parquet_file/src/rebuild.rs
Labels: automerge

#1713 fix: ensure values are different
  query/src/exec/seriesset.rs
Labels: automerge

#1680 feat: expose server and DB init errors over gRPC
  server/src/config.rs
  server/src/init.rs
  server/src/lib.rs
  src/influxdb_ioxd/rpc/management.rs
  tests/common/server_fixture.rs
  tests/end_to_end_cases/management_api.rs
Labels: automerge

#1720 refactor: revert "refactor: read_filter debugging"
  query/src/exec.rs
  src/influxdb_ioxd/rpc/storage/service.rs
Labels: automerge

#1667 feat: sort order in schema (#1357)
  Cargo.lock
  internal_types/Cargo.toml
  internal_types/src/schema.rs
  internal_types/src/schema/builder.rs
  internal_types/src/schema/merge.rs
  internal_types/src/schema/sort.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1723 chore: update to rust 1.52.1 to avoid incremental complation panics
  rust-toolchain
Labels: automerge

#1714 feat: remove path parsing functionality
  parquet_file/src/catalog.rs
  parquet_file/src/chunk.rs
  parquet_file/src/cleanup.rs
  parquet_file/src/metadata.rs
  parquet_file/src/rebuild.rs
  parquet_file/src/storage.rs
  parquet_file/src/test_utils.rs
  server/src/db.rs
Labels: automerge

#1728 refactor: improve server background task logging
  server/src/db.rs
Labels: automerge

#1726 fix: bump catalog version
  parquet_file/src/catalog.rs
  parquet_file/src/metadata.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1727 feat: info-log server ID during init
  server/src/init.rs
Labels: automerge

#1722 refactor: Rename parquet_file::Chunk --> ParquetChunk
  parquet_file/src/chunk.rs
  parquet_file/src/test_utils.rs
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/partition.rs
  server/src/db/chunk.rs
  server/src/db/lifecycle.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1719 chore: Pull tracing+logging setup in its own crate
  Cargo.lock
  Cargo.toml
  logfmt/src/lib.rs
  src/commands/tracing.rs
  src/main.rs
  trogging/Cargo.toml
  trogging/src/config.rs
  trogging/src/lib.rs
Labels: automerge

#1729 refactor: traitify lifecycle policy
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/lifecycle.rs
  tracker/src/task.rs
  tracker/src/task/registry.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1730 refactor: split lifecycle into separate crate
  Cargo.lock
  Cargo.toml
  lifecycle/Cargo.toml
  lifecycle/src/lib.rs
  lifecycle/src/policy.rs
  server/Cargo.toml
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/lifecycle.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1721 chore: update datafusion deps
  Cargo.lock
  datafusion/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#1731 chore: remove unused query dependency
  Cargo.lock
  query/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#1734 feat: Factor out tracing/logging CLI options
  Cargo.lock
  Cargo.toml
  src/commands/run.rs
  src/commands/tracing.rs
  trogging/Cargo.toml
  trogging/src/cli.rs
  trogging/src/config.rs
  trogging/src/lib.rs
Labels: automerge, conductor

#1738 chore: Allow custom default log filter
  trogging/src/cli.rs
  trogging/src/lib.rs
Labels: automerge, conductor

#1742 chore: Split LoggingConfig out of TracingConfig
  src/commands/run.rs
  src/commands/tracing.rs
  trogging/src/cli.rs
Labels: automerge, conductor

#1724 feat: Add persistence windows ingestion tracking
  Cargo.lock
  mutable_buffer/Cargo.toml
  mutable_buffer/src/lib.rs
  mutable_buffer/src/persistence_windows.rs
Labels: automerge

#1739 feat: make DB catalog work w/ transaction aborts
  parquet_file/src/catalog.rs
  parquet_file/src/cleanup.rs
  parquet_file/src/rebuild.rs
  server/src/db.rs
  server/src/db/catalog/chunk.rs
Labels: automerge

#1744 chore: Add proper format for SchemaPivotNode
  query/src/exec/schema_pivot.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1745 refactor: add ChunkAddr to describe location of chunk in catalog
  data_types/src/chunk_metadata.rs
  parquet_file/src/catalog.rs
  parquet_file/src/cleanup.rs
  parquet_file/src/metadata.rs
  parquet_file/src/storage_testing.rs
  parquet_file/src/test_utils.rs
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/partition.rs
  server/src/db/catalog/table.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1733 feat: Implement DeduplicateExec
  Cargo.lock
  query/Cargo.toml
  query/src/provider.rs
  query/src/provider/deduplicate.rs
  query/src/provider/deduplicate/algo.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1749 chore: Ignore flaky test
  query_tests/src/influxrpc/tag_keys.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1750 chore: Update itertools + deps
  Cargo.lock
  Cargo.toml
  internal_types/Cargo.toml
  object_store/Cargo.toml
  read_buffer/Cargo.toml
  server/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#1754 refactor: Rename query::PartitionChunk --> query::QueryChunk
  query/src/frontend/influxrpc.rs
  query/src/lib.rs
  query/src/provider.rs
  query/src/provider/physical.rs
  query/src/test.rs
  query_tests/src/pruning.rs
  query_tests/src/scenarios.rs
  query_tests/src/table_schema.rs
  server/src/db.rs
  server/src/db/access.rs
  server/src/db/chunk.rs
  server/src/lib.rs
  server/src/utils.rs
  src/influxdb_ioxd/http.rs
  src/influxdb_ioxd/planner.rs
  src/influxdb_ioxd/rpc/management.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1755 refactor: Unify schema handling in query crate
  query/src/duplicate.rs
  query/src/lib.rs
  query/src/pruning.rs
  query/src/test.rs
  server/src/db/access.rs
  server/src/db/chunk.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1756 refactor: Remove PartitionChunk::table_schema
  internal_types/src/schema.rs
  mutable_buffer/src/chunk/snapshot.rs
  parquet_file/src/chunk.rs
  query/src/frontend/influxrpc.rs
  query/src/lib.rs
  query/src/provider.rs
  query/src/provider/physical.rs
  query/src/test.rs
  query_tests/src/table_schema.rs
  server/src/db/access.rs
  server/src/db/chunk.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1751 chore: Switch to smaller cache dep
  Cargo.lock
  server/Cargo.toml
  server/src/lib.rs
  src/influxdb_ioxd.rs
  src/influxdb_ioxd/http.rs
Labels: automerge

#1758 fix: fix flaky test by updating datafusion dep
  Cargo.lock
  datafusion/Cargo.toml
  query_tests/src/influxrpc/tag_keys.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1757 refactor: use Schema to compute InfluxDB primary keys
  data_types/src/partition_metadata.rs
  internal_types/src/schema.rs
  query/src/duplicate.rs
  query/src/provider.rs
  query/src/util.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1760 chore: remove more dead code
  parquet_file/src/chunk.rs
  parquet_file/src/metadata.rs
  parquet_file/src/storage_testing.rs
  server/src/db/catalog/chunk.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1759 refactor: delete unused code
  mutable_buffer/src/chunk/snapshot.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1572 feat: wire catalog wiping all the way to the CLI
  data_types/src/job.rs
  docs/README.md
  docs/server_startup.md
  generated_types/protos/influxdata/iox/management/v1/jobs.proto
  generated_types/protos/influxdata/iox/management/v1/service.proto
  generated_types/src/job.rs
  influxdb_iox_client/src/client/management.rs
  parquet_file/src/catalog.rs
  parquet_file/src/rebuild.rs
  server/src/config.rs
  server/src/db.rs
  server/src/init.rs
  server/src/lib.rs
  server/src/utils.rs
  src/commands/database.rs
  src/commands/database/catalog.rs
  src/influxdb_ioxd/rpc/management.rs
  tests/end_to_end_cases/management_api.rs
  tests/end_to_end_cases/management_cli.rs
Labels: automerge

#1753 feat: transactional lifecycle API
  lifecycle/src/guard.rs
  lifecycle/src/lib.rs
  lifecycle/src/policy.rs
  query_tests/src/pruning.rs
  query_tests/src/scenarios.rs
  server/src/db.rs
  server/src/db/lifecycle.rs
  server/src/lib.rs
  server_benchmarks/benches/catalog_persistence.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1675 test: Starting Kafka Write Buffer integration tests
  .circleci/config.yml
  Cargo.lock
  Cargo.toml
  docker/Dockerfile.ci.integration
  docker/Dockerfile.ci.integration.dockerignore
  docker/ci-kafka-docker-compose.yml
  docs/testing.md
  tests/end_to_end_cases/mod.rs
  tests/end_to_end_cases/scenario.rs
  tests/end_to_end_cases/write_buffer.rs
Labels: automerge

#1765 refactor: remove multiple tables from Read Buffer Chunk
  read_buffer/benches/database.rs
  read_buffer/benches/read_filter.rs
  read_buffer/src/chunk.rs
  read_buffer/src/lib.rs
  read_buffer/src/table.rs
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/chunk.rs
Labels: automerge

#1761 feat: Handle merging chunks that have different schemas
  datafusion_util/src/lib.rs
  internal_types/src/schema.rs
  mutable_buffer/src/chunk/snapshot.rs
  query/src/provider.rs
  query/src/provider/physical.rs
  query/src/util.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1769 fix: Report error to stderr in git-log-prs
  scripts/git-log-prs
Labels: automerge

#1762 feat: Turn on deduplication for all queries
  query/src/provider.rs
  query_tests/src/influxrpc/field_columns.rs
  query_tests/src/influxrpc/read_group.rs
  query_tests/src/sql.rs
  server/src/db.rs
  server/src/db/chunk.rs
  src/influxdb_ioxd/http.rs
  tests/end_to_end_cases/flight_api.rs
  tests/end_to_end_cases/read_api.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1766 refactor: decouple preserved and in-mem catalog (part 1)
  parquet_file/src/catalog.rs
  parquet_file/src/cleanup.rs
  parquet_file/src/rebuild.rs
  server/src/config.rs
  server/src/db.rs
  server/src/db/lifecycle.rs
  server/src/init.rs
  server/src/lib.rs
  server/src/utils.rs
Labels: automerge

#1773 chore: lint `lifecycle` crate
  lifecycle/src/guard.rs
  lifecycle/src/lib.rs
  lifecycle/src/policy.rs
Labels: automerge

#1767 feat: make lifecycle partition-aware
  lifecycle/src/lib.rs
  lifecycle/src/policy.rs
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/catalog/partition.rs
  server/src/db/lifecycle.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1772 refactor: decouple preserved and in-mem catalog (part 2)
  parquet_file/src/catalog.rs
  parquet_file/src/cleanup.rs
  parquet_file/src/rebuild.rs
  server/src/config.rs
  server/src/db.rs
  server/src/init.rs
  server/src/lib.rs
Labels: automerge

#1775 fix: auto-wipe should still be enabled
  server/src/init.rs
Labels: automerge

#1779 refactor: rename deduplicate --> overlap
  query/src/lib.rs
  query/src/provider.rs
  query/src/provider/overlap.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1771 fix: Select the correct timestamp for min/max selectors
  Cargo.lock
  query/Cargo.toml
  query/src/func/selectors.rs
  query/src/func/selectors/internal.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1782 chore: Store generated rustdoc as circleci artifacts
  .circleci/config.yml
Labels: automerge

#1781 feat: eagerly check object store during CLI run
  Cargo.lock
  Cargo.toml
  object_store/src/disk.rs
  src/influxdb_ioxd.rs
  tests/end_to_end_cases/management_api.rs
  tests/end_to_end_cases/mod.rs
  tests/end_to_end_cases/run_cli.rs
Labels: automerge

#1778 refactor: decouple preserved and in-mem catalog (part 3)
  parquet_file/src/catalog.rs
  parquet_file/src/cleanup.rs
  parquet_file/src/rebuild.rs
  server/src/db.rs
Labels: automerge

#1786 fix: improve "server not initialized" error
  server/src/lib.rs
  src/influxdb_ioxd/rpc/error.rs
Labels: automerge

#1780 feat: Reorg Planner for merge plans
  query/src/frontend.rs
  query/src/frontend/reorg.rs
  query/src/provider.rs
  query/src/test.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1789 fix: correct row count for object store chunks
  parquet_file/src/chunk.rs
  parquet_file/src/metadata.rs
  server/src/db/catalog/chunk.rs
  tests/end_to_end_cases/persistence.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1787 refactor: decouple preserved and in-mem catalog (part 4)
  parquet_file/src/catalog.rs
  parquet_file/src/rebuild.rs
  server/src/config.rs
  server/src/db.rs
Labels: automerge

#1788 feat: include UUIDv4 into parquet file names
  parquet_file/src/rebuild.rs
  parquet_file/src/storage.rs
  parquet_file/src/test_utils.rs
  server/src/db.rs
Labels: automerge

#1783 feat: Implement grpc-router crate
  Cargo.lock
  Cargo.toml
  grpc-router/Cargo.toml
  grpc-router/grpc-router-test-gen/Cargo.toml
  grpc-router/grpc-router-test-gen/build.rs
  grpc-router/grpc-router-test-gen/protos/test.proto
  grpc-router/grpc-router-test-gen/src/lib.rs
  grpc-router/src/connection_manager.rs
  grpc-router/src/lib.rs
  grpc-router/src/router.rs
Labels: automerge

#1790 chore: Add our linting rules to the trogging crate
  trogging/src/cli.rs
  trogging/src/config.rs
  trogging/src/lib.rs
Labels: automerge

#1792 fix: Escape non-printable characters in logfmt
  logfmt/src/lib.rs
Labels: automerge

#1793 refactor: pull Channel --> Stream adapater into its own module
  parquet_file/src/storage.rs
  query/src/exec.rs
  query/src/exec/stream.rs
  query/src/provider/deduplicate.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1743 feat: Write entries to Kafka
  Cargo.lock
  query_tests/src/influxrpc/read_window_aggregate.rs
  query_tests/src/pruning.rs
  query_tests/src/scenarios.rs
  server/Cargo.toml
  server/src/config.rs
  server/src/db.rs
  server/src/init.rs
  server/src/lib.rs
  server/src/utils.rs
  server/src/write_buffer.rs
  server_benchmarks/benches/catalog_persistence.rs
  tests/end_to_end_cases/write_buffer.rs
Labels: automerge

#1748 chore: small CI improvements
  .circleci/config.yml
  docker/Dockerfile.ci
  rust-toolchain
  rust-toolchain.toml
Labels: automerge

#1776 feat: compact chunks
  data_types/src/database_rules.rs
  data_types/src/job.rs
  data_types/src/partition_metadata.rs
  generated_types/protos/influxdata/iox/management/v1/database_rules.proto
  generated_types/protos/influxdata/iox/management/v1/jobs.proto
  generated_types/src/database_rules/lifecycle.rs
  generated_types/src/job.rs
  lifecycle/src/lib.rs
  lifecycle/src/policy.rs
  query/src/frontend/reorg.rs
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/partition.rs
  server/src/db/lifecycle.rs
  server/src/db/lifecycle/compact.rs
  server/src/lib.rs
  server/src/utils.rs
  src/commands/database.rs
  tests/end_to_end_cases/management_api.rs
  tests/end_to_end_cases/persistence.rs
  tests/end_to_end_cases/scenario.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1794 feat: Implement split_plans
  query/src/exec.rs
  query/src/exec/context.rs
  query/src/exec/schema_pivot.rs
  query/src/exec/split.rs
  query/src/frontend/reorg.rs
  query/src/provider.rs
  server/src/db/lifecycle/compact.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1802 chore: Reduce debug logging in query crate
  query/src/exec/context.rs
  query/src/exec/seriesset.rs
  query/src/exec/split.rs
  query/src/frontend/influxrpc.rs
  query/src/provider.rs
  query/src/provider/deduplicate/algo.rs
  query/src/pruning.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1803 chore: update CONTRIBUTING with instructions for running and debugging end-to-end tests
  CONTRIBUTING.md
  README.md
Labels: automerge

#1804 test: Ensure disabled logs don't eval args
  trogging/src/lib.rs
Labels: automerge

#1800 feat: Sort the output of split_plans as well
  query/src/frontend/reorg.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1807 feat: temporary log information on record batch data
  read_buffer/src/chunk.rs
Labels: automerge, kodiak: merge.method = 'squash'
