Repository influxdata/influxdb_iox, pull requests merged in 2021-05, with the labels that each got.

#1394 feat: Add jemalloc stats
  Cargo.lock
  Cargo.toml
  server/Cargo.toml
  server/src/lib.rs
Labels: automerge

#1386 feat: implement transaction handling for catalog
  Cargo.lock
  docs/catalog_persistence.md
  generated_types/build.rs
  generated_types/protos/influxdata/iox/catalog/v1/catalog.proto
  generated_types/src/lib.rs
  object_store/src/path.rs
  object_store/src/path/parsed.rs
  parquet_file/Cargo.toml
  parquet_file/src/catalog.rs
  parquet_file/src/lib.rs
Labels: automerge

#1403 fix(storage rpc): do not send back tags with empty values
  query/src/exec/seriesset.rs
  server/src/query_tests/influxrpc/read_filter.rs
  tests/end_to_end_cases/storage_api.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1405 feat: add row counts to SQL repl output
  src/commands/sql/repl.rs
  tests/end_to_end_cases/sql_cli.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1404 feat: implement --format and `SET FORMAT <pretty,csv,json>` in SQL repl
  src/commands/sql.rs
  src/commands/sql/repl.rs
  src/commands/sql/repl_command.rs
  tests/end_to_end_cases/sql_cli.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1410 feat: metrics for total size of chunks across stages
  server/src/db.rs
Labels: automerge

#1419 refactor: spelling and log info
  query/src/frontend/influxrpc.rs
  read_buffer/src/chunk.rs
Labels: automerge

#1412 refactor: Use slice patterns for CLI command matching 504f530
  src/commands/sql/repl_command.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1409 feat: implement parquet metadata handling
  Cargo.lock
  arrow_deps/Cargo.toml
  arrow_deps/src/lib.rs
  arrow_deps/src/util.rs
  parquet_file/Cargo.toml
  parquet_file/src/chunk.rs
  parquet_file/src/lib.rs
  parquet_file/src/metadata.rs
  parquet_file/src/table.rs
  server/src/db/chunk.rs
  server/src/db/streams.rs
Labels: automerge

#1406 feat: Actually route SequencedEntry to the Write Buffer, if present
  internal_types/src/entry.rs
  server/src/buffer.rs
  server/src/db.rs
  server/src/lib.rs
  server/src/query_tests/utils.rs
  server/src/snapshot.rs
Labels: automerge

#1423 feat: Add debug to update_chunk_state metrics
  server/src/db.rs
Labels: automerge

#1422 docs: fix greater than / less than comment
  data_types/src/database_rules.rs
Labels: automerge, documentation

#1424 refactor: move private test helpers to utils module to be used by many modules
  parquet_file/src/lib.rs
  parquet_file/src/metadata.rs
  parquet_file/src/utils.rs
Labels: automerge

#1431 feat: Enable gRPC reflection
  Cargo.lock
  Cargo.toml
  generated_types/build.rs
  generated_types/src/lib.rs
  src/influxdb_ioxd.rs
  src/influxdb_ioxd/rpc.rs
Labels: automerge

#1430 chore: update hashbrown
  Cargo.lock
  mutable_buffer/Cargo.toml
  read_buffer/Cargo.toml
  tracker/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#1433 chore: update arrow/datafusion deps
  Cargo.lock
  arrow/Cargo.toml
  arrow_flight/Cargo.toml
  datafusion/Cargo.toml
  parquet/Cargo.toml
  parquet_file/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#1389 ci: disable incremental compilation
  .circleci/config.yml
Labels: automerge

#1429 refactor: initial split of observability_deps
  Cargo.lock
  Cargo.toml
  mem_qe/Cargo.toml
  mem_qe/src/bin/main.rs
  metrics/Cargo.toml
  metrics/src/lib.rs
  metrics/src/tests.rs
  observability_deps/Cargo.toml
  observability_deps/src/lib.rs
  src/commands/tracing.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1421 feat: instrumentable RwLocks (#1355)
  Cargo.lock
  tracker/Cargo.toml
  tracker/src/lib.rs
  tracker/src/lock.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1435 chore: remove unused dependency from influxdb_line_protocol
  Cargo.lock
  influxdb_line_protocol/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#1428 refactor: split entry out into separate crate
  .circleci/config.yml
  Cargo.lock
  Cargo.toml
  docs/regenerating_flatbuffers.md
  entry/Cargo.toml
  entry/benches/benchmark.rs
  entry/check-flatbuffers.sh
  entry/regenerate-flatbuffers.sh
  entry/src/entry.fbs
  entry/src/entry.rs
  entry/src/entry_generated.rs
  entry/src/lib.rs
  generated_types/src/lib.rs
  internal_types/Cargo.toml
  internal_types/src/lib.rs
  mutable_buffer/Cargo.toml
  mutable_buffer/benches/snapshot.rs
  mutable_buffer/benches/write.rs
  mutable_buffer/src/chunk.rs
  mutable_buffer/src/column.rs
  mutable_buffer/src/table.rs
  server/Cargo.toml
  server/src/buffer.rs
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/partition.rs
  server/src/db/lifecycle.rs
  server/src/lib.rs
  tests/end_to_end_cases/write_api.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1440 feat: Add more logs to shed light on the curious incident with missing metrics in the nighttime
  server/src/db.rs
Labels: automerge

#1415 feat: add column_type and influxdb_column_type, remove row_count from system.columns
  data_types/src/partition_metadata.rs
  docs/README.md
  docs/sql.md
  mutable_buffer/src/table.rs
  parquet_file/src/metadata.rs
  parquet_file/src/utils.rs
  read_buffer/src/chunk.rs
  read_buffer/src/schema.rs
  read_buffer/src/table.rs
  server/src/db.rs
  server/src/db/system_tables.rs
  server/src/query_tests/sql.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1437 refactor: move protobuf conversion logic to generated_types
  Cargo.lock
  data_types/Cargo.toml
  data_types/src/chunk.rs
  data_types/src/database_rules.rs
  data_types/src/field_validation.rs
  data_types/src/job.rs
  data_types/src/lib.rs
  generated_types/Cargo.toml
  generated_types/src/chunk.rs
  generated_types/src/database_rules.rs
  generated_types/src/database_rules/lifecycle.rs
  generated_types/src/database_rules/partition.rs
  generated_types/src/database_rules/shard.rs
  generated_types/src/database_rules/write_buffer.rs
  generated_types/src/google.rs
  generated_types/src/job.rs
  generated_types/src/lib.rs
  server/src/lib.rs
  src/influxdb_ioxd/rpc/management.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1414 feat: pull-based metrics (#1355)
  metrics/src/lib.rs
  metrics/src/metrics.rs
  server/src/db.rs
  server/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1442 refactor: use Arc<str> instead of Arc<String>
  data_types/src/chunk.rs
  datafusion_util/src/lib.rs
  generated_types/src/chunk.rs
  query/src/exec/field.rs
  query/src/exec/seriesset.rs
  query/src/frontend/influxrpc.rs
  query/src/plan/seriesset.rs
  query/src/provider.rs
  query/src/provider/physical.rs
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/chunk.rs
  server/src/db/system_tables.rs
  server/src/query_tests/influxrpc/util.rs
  src/influxdb_ioxd/rpc/storage/data.rs
  test_helpers/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1439 feat: instrument catalog locks (#1355)
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/catalog/partition.rs
  server/src/db/lifecycle.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1416 feat: s3 compatibility storages support
  docs/env.example
  object_store/src/aws.rs
  src/commands/run.rs
  src/influxdb_ioxd.rs
Labels: automerge

#1445 chore: Update Rust version
  influxdb_iox_client/src/client/management.rs
  influxdb_tsm/src/reader.rs
  internal_types/src/arrow/sort.rs
  metrics/src/lib.rs
  metrics/src/metrics.rs
  query/src/exec/seriesset.rs
  rust-toolchain
  server/src/db.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1438 feat: preserve parquet metadata + proper path in catalog
  generated_types/protos/influxdata/iox/catalog/v1/catalog.proto
  object_store/src/path.rs
  object_store/src/path/parsed.rs
  object_store/src/path/parts.rs
  parquet_file/src/catalog.rs
  parquet_file/src/metadata.rs
  parquet_file/src/utils.rs
Labels: automerge

#1446 feat: Only calculate system.chunks table "on demand"
  server/src/db/system_tables.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1449 chore: revert to Rust 1.51.0
  influxdb_tsm/src/reader.rs
  rust-toolchain
Labels: automerge

#1447 feat: add shard sink indirection
  data_types/src/database_rules.rs
  generated_types/protos/influxdata/iox/management/v1/shard.proto
  generated_types/src/database_rules/shard.rs
  server/src/lib.rs
  tests/end_to_end_cases/write_api.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1441 feat: Expose the storage usage for each column in system.chunk_columns
  data_types/src/chunk.rs
  data_types/src/partition_metadata.rs
  mutable_buffer/src/chunk.rs
  mutable_buffer/src/column.rs
  mutable_buffer/src/table.rs
  read_buffer/src/chunk.rs
  read_buffer/src/row_group.rs
  read_buffer/src/table.rs
  server/src/db/catalog.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/partition.rs
  server/src/db/system_tables.rs
  server/src/query_tests/scenarios.rs
  server/src/query_tests/sql.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1443 feat: Add Regex matching support to IOx's gRPC API
  Cargo.lock
  query/Cargo.toml
  query/src/frontend/influxrpc.rs
  query/src/func.rs
  query/src/func/regex.rs
  query/src/func/selectors.rs
  query/src/predicate.rs
  server/src/query_tests/influxrpc/read_filter.rs
  src/influxdb_ioxd/rpc/storage/expr.rs
  tests/end_to_end_cases/storage_api.rs
Labels: automerge

#1455 feat: Include `system.chunk_columns` in the tables that are scraped by observer mode
  src/commands/sql/observer.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1458 fix: Use PathBuf rather than debug formatting and back to String
  parquet_file/src/storage.rs
Labels: automerge

#1453 feat: Query Parquet files
  parquet_file/src/catalog.rs
  parquet_file/src/lib.rs
  parquet_file/src/metadata.rs
  parquet_file/src/storage.rs
  parquet_file/src/storage_testing.rs
  parquet_file/src/utils.rs
  server/src/db.rs
  server/src/query_tests/scenarios.rs
Labels: automerge

#1456 fix: Load only databases for which a config exists
  server/src/lib.rs
Labels: automerge

#1452 feat: Calculate all system tables "on demand"
  server/src/db/system_tables.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1466 chore: update deps
  Cargo.lock
  datafusion/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#1448 refactor: make `StatValues::{min,max}` optional + handle NaNs
  data_types/src/partition_metadata.rs
  mutable_buffer/src/chunk/snapshot.rs
  mutable_buffer/src/column.rs
  parquet_file/src/metadata.rs
  parquet_file/src/utils.rs
  read_buffer/src/chunk.rs
  read_buffer/src/table.rs
  server/src/db.rs
  server/src/db/system_tables.rs
Labels: automerge

#1459 feat: move dictionary and bitset into arrow_utils
  Cargo.lock
  arrow/Cargo.toml
  arrow_util/Cargo.toml
  arrow_util/src/bitset.rs
  arrow_util/src/dictionary.rs
  arrow_util/src/lib.rs
  arrow_util/src/string.rs
  mutable_buffer/Cargo.toml
  mutable_buffer/src/chunk.rs
  mutable_buffer/src/chunk/snapshot.rs
  mutable_buffer/src/column.rs
  mutable_buffer/src/dictionary.rs
  mutable_buffer/src/lib.rs
  mutable_buffer/src/table.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1464 feat: instrument catalog locks
  Cargo.lock
  metrics/src/lib.rs
  metrics/src/tests.rs
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/catalog/partition.rs
  tracker/Cargo.toml
  tracker/src/lock.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1480 refactor: shuffle encodings around in Read Buffer
  read_buffer/Cargo.toml
  read_buffer/benches/string.rs
  read_buffer/benches/sum_fixed.rs
  read_buffer/src/column.rs
  read_buffer/src/column/encoding.rs
  read_buffer/src/column/encoding/scalar.rs
  read_buffer/src/column/encoding/scalar/fixed.rs
  read_buffer/src/column/encoding/scalar/fixed_null.rs
  read_buffer/src/column/encoding/string.rs
  read_buffer/src/column/encoding/string/dictionary.rs
  read_buffer/src/column/encoding/string/rle.rs
  read_buffer/src/column/float.rs
  read_buffer/src/column/integer.rs
  read_buffer/src/column/string.rs
  read_buffer/src/lib.rs
Labels: automerge

#1483 chore: upgrade arrow and datafusion
  Cargo.lock
  arrow/Cargo.toml
  arrow_flight/Cargo.toml
  datafusion/Cargo.toml
  parquet/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#1484 feat: Report num_cpus seen by IOx on startup
  Cargo.lock
  Cargo.toml
  src/influxdb_ioxd.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1486 feat: we now can read parquet files from all kind of object stores
  parquet_file/src/catalog.rs
  parquet_file/src/lib.rs
  parquet_file/src/metadata.rs
  parquet_file/src/storage.rs
  parquet_file/src/storage_testing.rs
  parquet_file/src/utils.rs
  server/src/db.rs
  server/src/query_tests/utils.rs
Labels: automerge

#1476 feat: use PackedStringArray in mutable buffer
  arrow_util/src/string.rs
  mutable_buffer/src/column.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1492 fix: Add ingest_fields_total
  server/src/lib.rs
  src/influxdb_ioxd/http.rs
Labels: automerge

#1494 feat: add uncompressed read buffer size metric
  read_buffer/src/chunk.rs
  read_buffer/src/column.rs
  read_buffer/src/column/boolean.rs
  read_buffer/src/column/encoding/bool.rs
  read_buffer/src/column/encoding/scalar/fixed_null.rs
  read_buffer/src/column/encoding/string/dictionary.rs
  read_buffer/src/column/encoding/string/rle.rs
  read_buffer/src/column/float.rs
  read_buffer/src/column/integer.rs
  read_buffer/src/column/string.rs
  read_buffer/src/row_group.rs
  read_buffer/src/table.rs
Labels: automerge

#1493 feat: implement Read Buffer run-length encoding for scalars
  read_buffer/src/column.rs
  read_buffer/src/column/cmp.rs
  read_buffer/src/column/encoding/scalar.rs
  read_buffer/src/column/encoding/scalar/rle.rs
  read_buffer/src/column/float.rs
Labels: automerge

#1444 feat: Add a process clock to Db and use it for Sequenced Entries
  server/src/db.rs
  server/src/db/process_clock.rs
Labels: automerge

#1497 refactor: RLE selector target
  read_buffer/src/column/float.rs
Labels: automerge

#1498 fix: don't test snapshotting when disabled (#1496)
  mutable_buffer/src/chunk.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1488 feat: push metrics into catalog
  Cargo.lock
  metrics/Cargo.toml
  metrics/src/gauge.rs
  metrics/src/lib.rs
  metrics/src/metrics.rs
  metrics/src/tests.rs
  mutable_buffer/Cargo.toml
  mutable_buffer/benches/snapshot.rs
  mutable_buffer/benches/write.rs
  mutable_buffer/src/chunk.rs
  mutable_buffer/src/chunk/snapshot.rs
  parquet_file/Cargo.toml
  parquet_file/src/chunk.rs
  parquet_file/src/utils.rs
  read_buffer/benches/database.rs
  read_buffer/src/chunk.rs
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/metrics.rs
  server/src/db/catalog/partition.rs
  server/src/db/lifecycle.rs
  tracker/src/lib.rs
  tracker/src/mem.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1499 chore: update deps
  Cargo.lock
  datafusion/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#1500 refactor: rename data_types/src/chunk.rs -> data_types/src/chunk_metadata
  data_types/src/chunk_metadata.rs
  data_types/src/lib.rs
  generated_types/src/chunk.rs
  query/src/lib.rs
  query/src/test.rs
  read_buffer/src/chunk.rs
  read_buffer/src/table.rs
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/partition.rs
  server/src/db/system_tables.rs
  server/src/query_tests/utils.rs
  src/commands/database/chunk.rs
  src/commands/database/partition.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1502 feat: simplify shutdown
  server/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1503 refactor: track ingest metrics in one place
  server/src/lib.rs
  src/influxdb_ioxd/http.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1482 feat: wire up catalog preservation write path
  object_store/src/lib.rs
  parquet_file/src/catalog.rs
  parquet_file/src/metadata.rs
  parquet_file/src/storage.rs
  parquet_file/src/utils.rs
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/lifecycle.rs
Labels: automerge

#1501 fix: Add context to panic error on tools
  data_types/src/error.rs
  mutable_buffer/src/chunk/snapshot.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1505 feat: extend Byte trimming to all nullable integer encodings
  read_buffer/benches/plain.rs
  read_buffer/benches/sum_fixed.rs
  read_buffer/src/column/encoding/scalar/fixed.rs
  read_buffer/src/column/encoding/scalar/fixed_null.rs
  read_buffer/src/column/integer.rs
Labels: automerge

#1508 chore: Improve DataFusion plan logging
  query/src/exec/context.rs
  query/src/provider/physical.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1514 refactor: empty transaction during catalog creation
  parquet_file/src/catalog.rs
  server/src/config.rs
  server/src/db.rs
  server/src/db/process_clock.rs
  server/src/lib.rs
  server/src/query_tests/influxrpc/read_window_aggregate.rs
  server/src/query_tests/scenarios.rs
  server/src/query_tests/utils.rs
  server/src/snapshot.rs
Labels: automerge

#1518 feat: Add /debug/pprof/profile
  Cargo.lock
  Cargo.toml
  src/influxdb_ioxd/http.rs
Labels: automerge

#1519 feat: Implement Display for query::predicate to improve debug printing of plans
  query/src/predicate.rs
  query/src/provider/physical.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1525 fix: Cache outbound gRPC connections
  Cargo.lock
  server/Cargo.toml
  server/src/lib.rs
Labels: automerge

#1526 docs: tweak profiling.md
  docs/profiling.md
Labels: automerge, kodiak: merge.method = 'squash'

#1521 refactor: store chunk IDs only in catalog
  mutable_buffer/benches/snapshot.rs
  mutable_buffer/benches/write.rs
  mutable_buffer/src/chunk.rs
  mutable_buffer/src/chunk/snapshot.rs
  parquet_file/src/chunk.rs
  parquet_file/src/utils.rs
  read_buffer/benches/database.rs
  read_buffer/src/chunk.rs
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/partition.rs
  server/src/db/chunk.rs
  server/src/db/lifecycle.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1528 feat: Log cached connections
  server/src/lib.rs
Labels: automerge

#1524 perf: teach Read Buffer to materialise string column results in dictionary format
  Cargo.lock
  arrow_util/src/bitset.rs
  read_buffer/Cargo.toml
  read_buffer/benches/read.rs
  read_buffer/benches/read_filter.rs
  read_buffer/benches/read_group.rs
  read_buffer/src/chunk.rs
  read_buffer/src/column.rs
  read_buffer/src/column/string.rs
  read_buffer/src/lib.rs
  read_buffer/src/row_group.rs
  read_buffer/src/value.rs
Labels: automerge

#1530 feat: Add remote_template for simpler remote configuration
  server/src/config.rs
  server/src/lib.rs
  src/commands/run.rs
  src/influxdb_ioxd.rs
  src/influxdb_ioxd/http.rs
Labels: automerge

#1529 feat: remove snapshot feature
  server/src/lib.rs
  server/src/snapshot.rs
  src/influxdb_ioxd/http.rs
Labels: automerge

#1523 feat: read perserved catalog during DB startup
  object_store/src/disk.rs
  object_store/src/path/file.rs
  parquet_file/src/catalog.rs
  server/src/config.rs
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/partition.rs
  server/src/lib.rs
  server/src/query_tests/utils.rs
  tests/common/server_fixture.rs
  tests/end_to_end_cases/mod.rs
  tests/end_to_end_cases/preservation.rs
Labels: automerge

#1532 refactor: consolidate Read Buffer scalar encodings
  read_buffer/src/column/encoding/scalar.rs
  read_buffer/src/column/encoding/scalar/fixed.rs
  read_buffer/src/column/encoding/scalar/fixed_null.rs
  read_buffer/src/column/encoding/scalar/rle.rs
Labels: automerge

#1397 refactor: split lifecycle tracking from chunk state (#1361) (#1099)
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/catalog/chunk.rs
  server/src/db/chunk.rs
  server/src/db/lifecycle.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1535 fix: gRPC health reporter registration
  src/influxdb_ioxd/rpc.rs
Labels: automerge

#1536 fix: support converse binary expressions
  read_buffer/src/column/cmp.rs
  read_buffer/src/row_group.rs
Labels: automerge

#1527 feat: Part 1 of predicate push down - Send predicates to RUB
  query/src/predicate.rs
  query/src/provider.rs
  read_buffer/src/row_group.rs
  server/src/db/chunk.rs
  server/src/db/pred.rs
  server/src/query_tests/scenarios.rs
  server/src/query_tests/sql.rs
Labels: automerge

#1539 refactor: remove MutableChunk::has_table
  mutable_buffer/src/chunk.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1541 refactor: Remove multiple table support from Parquet Chunk
  parquet_file/src/chunk.rs
  parquet_file/src/metadata.rs
  parquet_file/src/table.rs
  parquet_file/src/utils.rs
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/chunk.rs
  server/src/db/lifecycle.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1512 fix: Set default line timestamp and default partition time to same value
  data_types/src/database_rules.rs
  entry/benches/benchmark.rs
  entry/src/entry.rs
  server/src/lib.rs
  src/influxdb_ioxd/http.rs
  src/influxdb_ioxd/rpc/write.rs
  tests/end_to_end_cases/write_api.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1546 chore: Update datafusion and use released version of arrow crates
  Cargo.lock
  Cargo.toml
  arrow/Cargo.toml
  arrow/src/lib.rs
  arrow_flight/Cargo.toml
  arrow_flight/src/lib.rs
  arrow_util/Cargo.toml
  datafusion/Cargo.toml
  influxdb_iox_client/Cargo.toml
  ingest/Cargo.toml
  internal_types/Cargo.toml
  mem_qe/Cargo.toml
  mutable_buffer/Cargo.toml
  packers/Cargo.toml
  parquet/Cargo.toml
  parquet/src/lib.rs
  parquet_file/Cargo.toml
  parquet_file/src/storage.rs
  query/Cargo.toml
  read_buffer/Cargo.toml
  server/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#1543 refactor: remove special case timestamp_range in parquet chunk
  parquet_file/src/chunk.rs
  parquet_file/src/metadata.rs
  parquet_file/src/storage_testing.rs
  parquet_file/src/table.rs
  parquet_file/src/utils.rs
  server/src/db.rs
  server/src/db/lifecycle.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1548 feat: teach Read Buffer to compare literals of different integer types
  read_buffer/src/value.rs
  server/src/query_tests/sql.rs
Labels: automerge

#1550 feat: support predicate pushdown for parquet files
  server/src/query_tests/scenarios.rs
  server/src/query_tests/sql.rs
Labels: automerge

#1553 feat: Use jemalloc everywhere instead of malloc
  Cargo.toml
Labels: automerge

#1552 feat: log jemalloc build conf
  src/influxdb_ioxd.rs
Labels: automerge

#1551 fix: Fix 'active' jemalloc stat misreporting
  server/src/lib.rs
Labels: automerge

#1537 feat: wait for task shutdown on DedicatedExecutor
  Cargo.lock
  query/Cargo.toml
  query/src/exec/task.rs
  tracker/src/task.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1542 feat: Implement service readiness API
  generated_types/protos/influxdata/iox/management/v1/service.proto
  influxdb_iox_client/src/client/management.rs
  src/commands/run.rs
  src/influxdb_ioxd.rs
  src/influxdb_ioxd/rpc.rs
  src/influxdb_ioxd/rpc/flight.rs
  src/influxdb_ioxd/rpc/management.rs
  src/influxdb_ioxd/rpc/storage.rs
  src/influxdb_ioxd/rpc/storage/service.rs
  src/influxdb_ioxd/rpc/write.rs
  src/influxdb_ioxd/serving_readiness.rs
  tests/end_to_end_cases/management_api.rs
Labels: automerge

#1555 feat: Add simpler RoutingConfig
  data_types/src/database_rules.rs
  generated_types/protos/influxdata/iox/management/v1/database_rules.proto
  generated_types/src/database_rules.rs
  generated_types/src/database_rules/shard.rs
  server/src/lib.rs
  tests/end_to_end_cases/management_api.rs
  tests/end_to_end_cases/write_api.rs
Labels: automerge

#1557 chore: Update datafusion + other deps
  Cargo.lock
  datafusion/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#1531 feat: preserve transaction metadata in parquets
  Cargo.lock
  parquet_file/Cargo.toml
  parquet_file/src/catalog.rs
  parquet_file/src/metadata.rs
  parquet_file/src/storage.rs
  parquet_file/src/storage_testing.rs
  parquet_file/src/utils.rs
  server/src/db.rs
Labels: automerge

#1558 refactor: remove tables from ChunkSnapshot (#1295)
  mutable_buffer/src/chunk/snapshot.rs
  server/src/db/chunk.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1554 feat: add background task to clean up OS
  parquet_file/src/catalog.rs
  parquet_file/src/cleanup.rs
  parquet_file/src/lib.rs
  parquet_file/src/metadata.rs
  parquet_file/src/storage.rs
  parquet_file/src/storage_testing.rs
  parquet_file/src/test_utils.rs
  server/src/config.rs
  server/src/db.rs
Labels: automerge

#1566 chore: enable arrow prettyprint
  Cargo.toml
  arrow_util/Cargo.toml
  ingest/Cargo.toml
  internal_types/Cargo.toml
  mem_qe/Cargo.toml
  mutable_buffer/Cargo.toml
  packers/Cargo.toml
  parquet_file/Cargo.toml
  query/Cargo.toml
  read_buffer/Cargo.toml
  server/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#1560 feat: only store ChunkSnapshot in Closed state
  data_types/src/partition_metadata.rs
  mutable_buffer/src/chunk.rs
  mutable_buffer/src/chunk/snapshot.rs
  mutable_buffer/src/column.rs
  mutable_buffer/src/table.rs
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/chunk.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1564 feat: extend AWS configs for prod and test
  docs/env.example
  object_store/src/aws.rs
  src/commands/run.rs
  src/influxdb_ioxd.rs
Labels: automerge

#1556 feat: associate tracker with lifecycle action (#1099)
  query/src/exec/task.rs
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/lifecycle.rs
  server/src/query_tests/scenarios.rs
  tracker/src/task.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1569 feat: Cache TableSummary in Catalog rather than computing it on demand
  parquet_file/src/chunk.rs
  parquet_file/src/metadata.rs
  parquet_file/src/table.rs
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/partition.rs
  server/src/query_tests/sql.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1574 refactor: Chunks can have at most one object store path
  server/src/db.rs
  server/src/db/chunk.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1563 refactor: traitify column encodings in Read Buffer
  read_buffer/benches/plain.rs
  read_buffer/benches/sum_fixed.rs
  read_buffer/src/chunk.rs
  read_buffer/src/column.rs
  read_buffer/src/column/boolean.rs
  read_buffer/src/column/encoding/scalar.rs
  read_buffer/src/column/encoding/scalar/fixed.rs
  read_buffer/src/column/encoding/scalar/fixed_null.rs
  read_buffer/src/column/encoding/scalar/rle.rs
  read_buffer/src/column/encoding/scalar/transcoders.rs
  read_buffer/src/column/float.rs
  read_buffer/src/column/integer.rs
  read_buffer/src/column/string.rs
  read_buffer/src/lib.rs
Labels: automerge

#1559 feat: implement catalog rebuilding from files
  parquet_file/src/catalog.rs
  parquet_file/src/lib.rs
  parquet_file/src/metadata.rs
  parquet_file/src/rebuild.rs
Labels: automerge

#1573 refactor: Remove unnecessary code
  server/src/db/chunk.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1577 refactor: remove `ChunkState::Invalid`
  server/src/db/catalog/chunk.rs
  server/src/db/chunk.rs
Labels: automerge

#1570 feat: per-column dictionaries in MUB
  Cargo.lock
  mutable_buffer/Cargo.toml
  mutable_buffer/src/chunk.rs
  mutable_buffer/src/chunk/snapshot.rs
  mutable_buffer/src/column.rs
  mutable_buffer/src/table.rs
  server/src/db.rs
  server/src/query_tests/sql.rs
  tests/end_to_end_cases/management_api.rs
  tests/end_to_end_cases/management_cli.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1583 chore: remove (moar!) unused dependencies
  Cargo.lock
  Cargo.toml
  arrow_util/Cargo.toml
  data_types/Cargo.toml
  generated_types/Cargo.toml
  google_types/Cargo.toml
  mutable_buffer/Cargo.toml
  parquet_file/Cargo.toml
  read_buffer/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#1581 chore: remove unused sqlparser dependency
  Cargo.lock
  query/Cargo.toml
  query/src/frontend/sql.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1584 refactor: Remove `table_name` from PartitionChunk API
  query/src/frontend/influxrpc.rs
  query/src/lib.rs
  query/src/provider/physical.rs
  query/src/test.rs
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/catalog/chunk.rs
  server/src/db/chunk.rs
  server/src/query_tests/table_schema.rs
  src/influxdb_ioxd/rpc/storage/service.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1587 chore: remove unused dependency in server
  Cargo.lock
  server/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#1586 feat: don't recompute chunk size on every iteration
  server/src/db/lifecycle.rs
Labels: automerge, kodiak: merge.method = 'squash'
