Repository influxdata/influxdb_iox, pull requests merged in 2021-03, with the labels that each got.

#882 feat: Make read_filter work for mutable buffer and read buffer
  arrow_deps/src/util.rs
  mutable_buffer/src/database.rs
  mutable_buffer/src/table.rs
  query/src/frontend/influxrpc.rs
  query/src/lib.rs
  query/src/plan/seriesset.rs
  query/src/test.rs
  server/src/db.rs
  server/src/db/chunk.rs
  server/src/query_tests/influxrpc.rs
  server/src/query_tests/influxrpc/read_filter.rs
  server/src/query_tests/scenarios.rs
  src/influxdb_ioxd/rpc/storage/service.rs
Labels: automerge, kodiak: merge.method = 'squash'

#892 refactor: use structopt for CLI root
  src/commands/logging.rs
  src/commands/meta.rs
  src/commands/server.rs
  src/commands/stats.rs
  src/influxdb_ioxd.rs
  src/main.rs
  tests/commands.rs
Labels: automerge, kodiak: merge.method = 'squash'

#891 refactor: Add Predicate::is_empty() and EMPTY_PREDICATE
  query/src/predicate.rs
  server/src/db/chunk.rs
  server/src/query_tests/influxrpc/read_filter.rs
  server/src/query_tests/influxrpc/table_names.rs
  server/src/snapshot.rs
Labels: automerge, kodiak: merge.method = 'squash'

#893 refactor: tidy up with clippy
  read_buffer/src/column.rs
  read_buffer/src/column/encoding/bool.rs
  read_buffer/src/column/encoding/dictionary.rs
  read_buffer/src/column/encoding/dictionary/plain.rs
  read_buffer/src/column/encoding/dictionary/rle.rs
  read_buffer/src/column/encoding/fixed_null.rs
  read_buffer/src/column/float.rs
  read_buffer/src/column/integer.rs
  read_buffer/src/lib.rs
  read_buffer/src/row_group.rs
  read_buffer/src/schema.rs
  read_buffer/src/table.rs
  read_buffer/src/value.rs
Labels: automerge

#895 feat(docker): add one-command Dockerfile
  Dockerfile
  Dockerfile.dockerignore
  README.md
  docker/Dockerfile.ci
  docker/Dockerfile.ci.dockerignore
  docker/Dockerfile.iox.dockerignore
Labels: automerge

#902 ci: Remove nightly-2021-02-12
  docker/Dockerfile.ci
Labels: automerge, kodiak: merge.method = 'rebase'

#853 feat: implement gRPC API and migrate influxdb_iox_client to use it
  Cargo.lock
  data_types/src/database_rules.rs
  influxdb_iox_client/Cargo.toml
  influxdb_iox_client/src/builder.rs
  influxdb_iox_client/src/client.rs
  influxdb_iox_client/src/client/flight.rs
  influxdb_iox_client/src/client/health.rs
  influxdb_iox_client/src/client/management.rs
  influxdb_iox_client/src/connection.rs
  influxdb_iox_client/src/errors/client_error.rs
  influxdb_iox_client/src/errors/create_database.rs
  influxdb_iox_client/src/errors/grpc_error.rs
  influxdb_iox_client/src/errors/grpc_query_error.rs
  influxdb_iox_client/src/errors/http_error.rs
  influxdb_iox_client/src/errors/mod.rs
  influxdb_iox_client/src/errors/server_error_response.rs
  influxdb_iox_client/src/lib.rs
  src/influxdb_ioxd/http.rs
  src/influxdb_ioxd/rpc.rs
  src/influxdb_ioxd/rpc/management.rs
  tests/end-to-end.rs
  tests/end_to_end_cases/flight_api.rs
  tests/end_to_end_cases/management_api.rs
  tests/end_to_end_cases/mod.rs
  tests/end_to_end_cases/storage_api.rs
Labels: automerge, kodiak: merge.method = 'squash'

#903 feat: Simplify Dockerfile
  Dockerfile
Labels: automerge, kodiak: merge.method = 'rebase'

#910 docs: Include INFLUXDB_IOX_OBJECT_STORE in env.example
  docs/env.example
Labels: automerge, kodiak: merge.method = 'rebase'

#911 refactor: Use `vec![]` instead of inlined strings, for legibility, in tests
  server/src/query_tests/influxrpc/read_filter.rs
  server/src/query_tests/scenarios.rs
Labels: automerge, kodiak: merge.method = 'squash'

#907 feat: MVP Management CLI
  Cargo.lock
  Cargo.toml
  src/commands/database.rs
  src/commands/writer.rs
  src/influxdb_ioxd.rs
  src/main.rs
  tests/commands.rs
  tests/end-to-end.rs
  tests/end_to_end_cases/management_cli.rs
  tests/end_to_end_cases/mod.rs
Labels: automerge, kodiak: merge.method = 'squash'

#894 refactor: Set up adding object store config
  src/influxdb_ioxd.rs
Labels: automerge

#925 fix: build of influxdb_iox_client with flight disabled
  influxdb_iox_client/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#924 feat: Integrate the object store configuration into the config system
  docs/env.example
  object_store/src/aws.rs
  object_store/src/azure.rs
  object_store/src/gcp.rs
  src/commands/server.rs
  src/influxdb_ioxd.rs
  src/main.rs
Labels: automerge

#905 feat: make read_group and read_window_aggregate work across chunks
  mutable_buffer/src/database.rs
  query/src/frontend/influxrpc.rs
  query/src/lib.rs
  query/src/plan/seriesset.rs
  query/src/predicate.rs
  query/src/test.rs
  server/src/db.rs
  server/src/query_tests/influxrpc.rs
  server/src/query_tests/influxrpc/read_filter.rs
  server/src/query_tests/influxrpc/read_group.rs
  server/src/query_tests/influxrpc/read_window_aggregate.rs
  server/src/query_tests/influxrpc/util.rs
  server/src/query_tests/scenarios.rs
  src/influxdb_ioxd/rpc/storage/service.rs
Labels: automerge, kodiak: merge.method = 'squash'

#926 fix(README): make docker instructions clearer
  README.md
Labels: automerge

#912 refactor: Remove query stuff from mutable buffer
  mutable_buffer/src/database.rs
  mutable_buffer/src/table.rs
Labels: automerge, kodiak: merge.method = 'squash'

#914 refactor: Remove impl of `query::Database` in mutable_buffer
  mutable_buffer/src/database.rs
  server/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#930 chore: Update arrow deps, turn off optional datafusion features
  Cargo.lock
  arrow_deps/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#922 refactor: Move chunk predicate creation from query::Predicate into server crate
  mutable_buffer/src/chunk.rs
  mutable_buffer/src/lib.rs
  mutable_buffer/src/pred.rs
  mutable_buffer/src/table.rs
  server/src/db/chunk.rs
  server/src/db/pred.rs
Labels: automerge, kodiak: merge.method = 'squash'

#923 refactor: Remove impl of `query::PartititionChunk` in mutable_buffer
  mutable_buffer/src/chunk.rs
  server/src/db.rs
  server/src/snapshot.rs
Labels: automerge, kodiak: merge.method = 'squash'

#927 refactor: Remove mutable_buffer crate dependency on query
  Cargo.lock
  arrow_deps/src/util.rs
  data_types/src/lib.rs
  data_types/src/timestamp.rs
  mutable_buffer/Cargo.toml
  mutable_buffer/src/pred.rs
  mutable_buffer/src/table.rs
  query/src/frontend/influxrpc.rs
  query/src/group_by.rs
  query/src/predicate.rs
  query/src/util.rs
  src/influxdb_ioxd/rpc/storage/expr.rs
  src/influxdb_ioxd/rpc/storage/service.rs
Labels: automerge, kodiak: merge.method = 'squash'

#929 fix: Test using the object store wrapper interface
  object_store/src/aws.rs
  object_store/src/azure.rs
  object_store/src/disk.rs
  object_store/src/gcp.rs
  object_store/src/lib.rs
  object_store/src/memory.rs
Labels: automerge

#933 fix: Move rand to a dev-dependency of packers
  packers/Cargo.toml
Labels: automerge

#938 docs: Document how to use grpcurl to play with API
  README.md
  scripts/grpcurl
Labels: automerge, kodiak: merge.method = 'rebase'

#941 docs: Use console type for interactive shell snippets
  README.md
Labels: automerge, kodiak: merge.method = 'rebase'

#939 feat: Add Service + CLI command to write line protocol to IOx
  generated_types/build.rs
  generated_types/protos/influxdata/iox/write/v1/service.proto
  generated_types/src/lib.rs
  google_types/src/lib.rs
  influxdb_iox_client/src/client.rs
  influxdb_iox_client/src/client/write.rs
  influxdb_iox_client/src/lib.rs
  src/commands/database.rs
  src/influxdb_ioxd/rpc.rs
  src/influxdb_ioxd/rpc/error.rs
  src/influxdb_ioxd/rpc/management.rs
  src/influxdb_ioxd/rpc/write.rs
  tests/end-to-end.rs
  tests/end_to_end_cases/management_api.rs
  tests/end_to_end_cases/mod.rs
  tests/end_to_end_cases/util.rs
  tests/end_to_end_cases/write_api.rs
  tests/end_to_end_cases/write_cli.rs
Labels: automerge, kodiak: merge.method = 'squash'

#935 chore: remove cruft from config/database rules
  data_types/src/database_rules.rs
  generated_types/protos/influxdata/iox/management/v1/base_types.proto
  generated_types/protos/influxdata/iox/management/v1/database_rules.proto
  server/src/config.rs
  server/src/lib.rs
  tests/end_to_end_cases/management_api.rs
Labels: automerge, kodiak: merge.method = 'squash'

#945 refactor: Move end-to-end test server fixture into its own module
  Cargo.lock
  Cargo.toml
  tests/common/mod.rs
  tests/common/server_fixture.rs
  tests/end-to-end.rs
  tests/end_to_end_cases/read_api.rs
  tests/end_to_end_cases/write_api.rs
Labels: automerge, kodiak: merge.method = 'squash'

#948 refactor: rework all end-to-end.rs tests to use the server fixture rather than const connection strings
  tests/common/server_fixture.rs
  tests/end-to-end.rs
  tests/end_to_end_cases/flight_api.rs
  tests/end_to_end_cases/management_cli.rs
  tests/end_to_end_cases/write_api.rs
  tests/end_to_end_cases/write_cli.rs
Labels: automerge, kodiak: merge.method = 'squash'

#906 fix(line-protocol): add unsigned integer field type
  data_types/src/data.rs
  influxdb_line_protocol/src/lib.rs
  ingest/src/lib.rs
  mutable_buffer/src/column.rs
  mutable_buffer/src/table.rs
  packers/src/packers.rs
Labels: automerge

#943 feat: Add CLI to query the database using SQL
  README.md
  influxdb_iox_client/src/format.rs
  influxdb_iox_client/src/lib.rs
  src/commands/database.rs
  src/influxdb_ioxd/http.rs
  src/influxdb_ioxd/http/format.rs
  tests/end-to-end.rs
  tests/end_to_end_cases/mod.rs
  tests/end_to_end_cases/read_cli.rs
Labels: automerge, kodiak: merge.method = 'squash'

#947 feat: Implement CRUD for remote addresses
  generated_types/protos/influxdata/iox/management/v1/service.proto
  influxdb_iox_client/src/client/management.rs
  server/src/config.rs
  server/src/lib.rs
  src/influxdb_ioxd/rpc/management.rs
  tests/end_to_end_cases/management_api.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#949 refactor: Port end-to-end tests that modify global state to their own fixture
  tests/common/server_fixture.rs
  tests/end-to-end.rs
  tests/end_to_end_cases/management_api.rs
  tests/end_to_end_cases/management_cli.rs
  tests/end_to_end_cases/read_cli.rs
  tests/end_to_end_cases/write_api.rs
  tests/end_to_end_cases/write_cli.rs
Labels: automerge, kodiak: merge.method = 'squash'

#955 fix: Do not leave child processes around after the end-to-end tes
  Cargo.lock
  Cargo.toml
  tests/common/server_fixture.rs
Labels: automerge, kodiak: merge.method = 'squash'

#957 fix: Revert "fix: Shutdown stest fixture on test harness exit"
  scripts/cargo_bin_no_orphan.bash
  tests/common/mod.rs
  tests/common/no_orphan_cargo.rs
  tests/common/server_fixture.rs
Labels: automerge

#953 test: Detect if talking to the wrong test server
  tests/common/server_fixture.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#940 feat: Make server no longer the default command
  Dockerfile
  README.md
  docker/Dockerfile.iox
  src/commands/server.rs
  src/main.rs
  tests/common/server_fixture.rs
Labels: automerge

#959 feat: add google longrunning operations stubs
  .gitattributes
  Cargo.lock
  buf.yaml
  generated_types/Cargo.toml
  generated_types/build.rs
  generated_types/protos/google/api/annotations.proto
  generated_types/protos/google/api/client.proto
  generated_types/protos/google/api/http.proto
  generated_types/protos/google/longrunning/operations.proto
  generated_types/protos/google/rpc/error_details.proto
  generated_types/protos/google/rpc/status.proto
  generated_types/src/google.rs
  generated_types/src/lib.rs
  google_types/Cargo.toml
  google_types/build.rs
  google_types/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#960 chore: Simplify server command
  src/commands/server.rs
  src/influxdb_ioxd.rs
  src/main.rs
Labels: automerge

#931 feat: remove now redundant parts of the HTTP API
  data_types/src/http.rs
  src/influxdb_ioxd/http.rs
Labels: automerge, kodiak: merge.method = 'squash'

#963 fix: remove unused proto files
  google_types/protos/google/rpc/error_details.proto
  google_types/protos/google/rpc/status.proto
Labels: automerge, kodiak: merge.method = 'squash'

#962 refactor: Turn server in a proper command
  src/commands/server.rs
  src/main.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#964 refactor: run some more end to end tests as tokio tests
  tests/end-to-end.rs
  tests/end_to_end_cases/storage_api.rs
Labels: automerge, kodiak: merge.method = 'squash'

#965 refactor: remove unnecessary async from DatabaseStore trait
  query/src/lib.rs
  query/src/test.rs
  server/src/lib.rs
  src/influxdb_ioxd/http.rs
  src/influxdb_ioxd/rpc/flight.rs
  src/influxdb_ioxd/rpc/management.rs
  src/influxdb_ioxd/rpc/storage/service.rs
Labels: automerge, kodiak: merge.method = 'squash'

#967 feat: Add subcommands to server
  Dockerfile
  docker/Dockerfile.iox
  src/commands/logging.rs
  src/commands/server.rs
  src/influxdb_ioxd.rs
  src/main.rs
  tests/common/server_fixture.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#970 feat: Add server remote [set|remove|list] commands
  Cargo.lock
  Cargo.toml
  src/commands/server.rs
  src/commands/server_remote.rs
  src/main.rs
  tests/end_to_end_cases/management_cli.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#968 feat: Add management API and CLI to list chunks
  data_types/src/chunk.rs
  data_types/src/lib.rs
  generated_types/build.rs
  generated_types/protos/influxdata/iox/management/v1/chunk.proto
  generated_types/protos/influxdata/iox/management/v1/service.proto
  generated_types/protos/influxdata/iox/write/v1/service.proto
  influxdb_iox_client/src/client/management.rs
  influxdb_iox_client/src/client/write.rs
  mutable_buffer/src/database.rs
  mutable_buffer/src/partition.rs
  query/src/lib.rs
  query/src/test.rs
  read_buffer/src/lib.rs
  server/src/db.rs
  server/src/db/chunk.rs
  server/src/snapshot.rs
  src/commands/database.rs
  src/commands/database/chunk.rs
  src/influxdb_ioxd/rpc/error.rs
  src/influxdb_ioxd/rpc/management.rs
  src/influxdb_ioxd/rpc/write.rs
  tests/end_to_end_cases/management_api.rs
  tests/end_to_end_cases/management_cli.rs
  tests/end_to_end_cases/util.rs
  tests/end_to_end_cases/write_api.rs
Labels: automerge, kodiak: merge.method = 'squash'

#975 refactor: impl Error for FieldViolation
  generated_types/src/google.rs
  src/commands/database/chunk.rs
Labels: automerge, kodiak: merge.method = 'squash'

#974 feat: make CLI to listing database consistent with other commands
  src/commands/database.rs
  tests/end_to_end_cases/management_cli.rs
Labels: automerge, kodiak: merge.method = 'squash'

#956 feat: add fanout task tracking
  Cargo.lock
  data_types/src/job.rs
  data_types/src/lib.rs
  generated_types/build.rs
  generated_types/protos/influxdata/iox/management/v1/jobs.proto
  generated_types/protos/influxdata/iox/management/v1/service.proto
  server/Cargo.toml
  server/src/buffer.rs
  server/src/lib.rs
  server/src/tracker.rs
  server/src/tracker/future.rs
  server/src/tracker/registry.rs
  src/influxdb_ioxd.rs
  src/influxdb_ioxd/rpc.rs
  src/influxdb_ioxd/rpc/management.rs
  src/influxdb_ioxd/rpc/operations.rs
Labels: automerge, kodiak: merge.method = 'squash'

#978 feat: Rename server run command to just run
  Dockerfile
  README.md
  docker/Dockerfile.iox
  docs/env.example
  docs/testing.md
  src/commands/logging.rs
  src/commands/run.rs
  src/commands/server.rs
  src/influxdb_ioxd.rs
  src/main.rs
  tests/common/server_fixture.rs
Labels: automerge

#984 docs: Add links to tech talks
  docs/README.md
Labels: automerge, kodiak: merge.method = 'rebase'

#972 feat: add configuration for routing rules
  Cargo.lock
  data_types/Cargo.toml
  data_types/src/database_rules.rs
Labels: automerge

#985 refactor: Use prost's enum helper functions for converting from ints
  src/influxdb_ioxd/rpc/storage/expr.rs
  tests/end_to_end_cases/storage_api.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#971 feat: configure databases created with CLI with reasonable defaults
  data_types/src/database_rules.rs
  src/commands/database.rs
  tests/end_to_end_cases/management_cli.rs
Labels: automerge, kodiak: merge.method = 'squash'

#980 feat: Make S3 auth parameters optional
  object_store/src/aws.rs
  src/influxdb_ioxd.rs
Labels: automerge

#987 refactor: complete migration of end-to-end.rs test to use #[tokio::test]
  tests/common/server_fixture.rs
  tests/end-to-end.rs
  tests/end_to_end_cases/flight_api.rs
  tests/end_to_end_cases/http.rs
  tests/end_to_end_cases/management_api.rs
  tests/end_to_end_cases/management_cli.rs
  tests/end_to_end_cases/mod.rs
  tests/end_to_end_cases/read_api.rs
  tests/end_to_end_cases/read_cli.rs
  tests/end_to_end_cases/scenario.rs
  tests/end_to_end_cases/storage_api.rs
  tests/end_to_end_cases/util.rs
  tests/end_to_end_cases/write_api.rs
  tests/end_to_end_cases/write_cli.rs
Labels: automerge, kodiak: merge.method = 'squash'

#991 fix: Use InstanceMetadataProvider directly
  object_store/src/aws.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#989 fix: use consistent versions
  Cargo.lock
  Cargo.toml
  benches/encoders.rs
  benches/packers.rs
  data_types/Cargo.toml
  generated_types/Cargo.toml
  influxdb_iox_client/Cargo.toml
  influxdb_tsm/Cargo.toml
  influxdb_tsm/src/encoders/simple8b.rs
  mem_qe/Cargo.toml
  mutable_buffer/Cargo.toml
  packers/Cargo.toml
  packers/src/sorter.rs
  query/Cargo.toml
  read_buffer/Cargo.toml
  read_buffer/benches/dictionary.rs
  read_buffer/benches/row_group.rs
  server/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#990 feat: Management API + CLI command to create a new chunk (rollover partition)
  generated_types/protos/influxdata/iox/management/v1/service.proto
  influxdb_iox_client/src/client/management.rs
  mutable_buffer/src/database.rs
  mutable_buffer/src/partition.rs
  server/src/db.rs
  src/commands/database/partition.rs
  src/influxdb_ioxd/rpc/management.rs
  tests/end_to_end_cases/management_api.rs
  tests/end_to_end_cases/management_cli.rs
Labels: automerge, kodiak: merge.method = 'squash'

#993 fix: Add ca-certificates to iox docker image
  Dockerfile
  docker/Dockerfile.iox
Labels: automerge, kodiak: merge.method = 'rebase'

#982 docs: Update README.md to refer to the command and CLI help
  README.md
  src/main.rs
Labels: automerge, kodiak: merge.method = 'squash'

#996 docs: Add README for influxdb_client
  influxdb2_client/README.md
Labels: automerge, kodiak: merge.method = 'squash'

#999 feat: Add support for ready API to influxdb_client
  influxdb2_client/examples/ready.rs
  influxdb2_client/src/lib.rs
  influxdb2_client/src/ready.rs
Labels: automerge, influxdb_client, kodiak: merge.method = 'squash'

#981 feat: add longrunning operations client
  Cargo.lock
  Cargo.toml
  data_types/Cargo.toml
  data_types/src/job.rs
  generated_types/src/lib.rs
  influxdb_iox_client/Cargo.toml
  influxdb_iox_client/src/client.rs
  influxdb_iox_client/src/client/management.rs
  influxdb_iox_client/src/client/operations.rs
  influxdb_iox_client/src/lib.rs
  src/commands/operations.rs
  src/influxdb_ioxd/rpc/operations.rs
  src/main.rs
  tests/common/server_fixture.rs
  tests/end_to_end_cases/mod.rs
  tests/end_to_end_cases/operations_api.rs
  tests/end_to_end_cases/operations_cli.rs
Labels: automerge, kodiak: merge.method = 'squash'

#995 feat: Management API + CLI command to list chunks in a partition
  generated_types/protos/influxdata/iox/management/v1/service.proto
  influxdb_iox_client/src/client/management.rs
  server/src/db.rs
  src/commands/database/partition.rs
  src/influxdb_ioxd/rpc/management.rs
  tests/end_to_end_cases/management_api.rs
  tests/end_to_end_cases/management_cli.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1003 chore: update deps (including arrow)
  Cargo.lock
  arrow_deps/Cargo.toml
  arrow_deps/src/test_util.rs
  ingest/src/parquet/writer.rs
  query/src/provider.rs
  server/src/db/chunk.rs
Labels: automerge

#1004 refactor: remove interior mutability from TrackerRegistry
  server/src/lib.rs
  server/src/tracker.rs
  server/src/tracker/registry.rs
Labels: automerge, kodiak: merge.method = 'squash'

#994 fix: prevent observing inconsistent tracker states
  server/src/tracker.rs
  server/src/tracker/future.rs
  src/influxdb_ioxd/rpc/operations.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1002 feat: Management API + CLI command to close a chunk and move to read buffer
  data_types/src/job.rs
  generated_types/protos/influxdata/iox/management/v1/jobs.proto
  generated_types/protos/influxdata/iox/management/v1/service.proto
  influxdb_iox_client/src/client/management.rs
  server/src/db.rs
  server/src/lib.rs
  src/commands/database/partition.rs
  src/influxdb_ioxd/rpc/error.rs
  src/influxdb_ioxd/rpc/management.rs
  tests/end_to_end_cases/management_api.rs
  tests/end_to_end_cases/management_cli.rs
  tests/end_to_end_cases/operations_api.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1005 feat: retain limited tracker history
  Cargo.lock
  data_types/Cargo.toml
  data_types/src/job.rs
  server/src/lib.rs
  server/src/tracker.rs
  server/src/tracker/history.rs
  server/src/tracker/registry.rs
  tests/end_to_end_cases/operations_cli.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1011 chore: Improve use of logging macros in storage service
  src/influxdb_ioxd/rpc/storage/service.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1021 fix: remove unneeded cpu feature check
  Cargo.toml
  src/cpu_feature_check/main.rs
Labels: automerge

#1018 feat: graceful shutdown (#827)
  Cargo.lock
  Cargo.toml
  server/src/lib.rs
  src/influxdb_ioxd.rs
  src/influxdb_ioxd/http.rs
  src/influxdb_ioxd/rpc.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1015 refactor: Move some types (not yet exposed to clients) into internal_types
  Cargo.lock
  Cargo.toml
  benches/line_protocol_to_parquet.rs
  data_types/Cargo.toml
  data_types/README.md
  data_types/src/lib.rs
  ingest/Cargo.toml
  ingest/src/lib.rs
  ingest/src/parquet/writer.rs
  ingest/tests/read_write.rs
  internal_types/Cargo.toml
  internal_types/README.md
  internal_types/benches/benchmark.rs
  internal_types/src/data.rs
  internal_types/src/lib.rs
  internal_types/src/schema.rs
  internal_types/src/schema/builder.rs
  internal_types/src/selection.rs
  mutable_buffer/Cargo.toml
  mutable_buffer/src/chunk.rs
  mutable_buffer/src/column.rs
  mutable_buffer/src/database.rs
  mutable_buffer/src/partition.rs
  mutable_buffer/src/pred.rs
  mutable_buffer/src/table.rs
  packers/Cargo.toml
  packers/src/lib.rs
  packers/src/packers.rs
  query/Cargo.toml
  query/src/exec/field.rs
  query/src/exec/fieldlist.rs
  query/src/frontend/influxrpc.rs
  query/src/frontend/sql.rs
  query/src/lib.rs
  query/src/plan/stringset.rs
  query/src/predicate.rs
  query/src/provider.rs
  query/src/provider/physical.rs
  query/src/test.rs
  query/src/util.rs
  read_buffer/Cargo.toml
  read_buffer/benches/database.rs
  read_buffer/src/chunk.rs
  read_buffer/src/lib.rs
  read_buffer/src/row_group.rs
  read_buffer/src/schema.rs
  read_buffer/src/table.rs
  server/Cargo.toml
  server/src/buffer.rs
  server/src/db.rs
  server/src/db/chunk.rs
  server/src/db/streams.rs
  server/src/lib.rs
  server/src/query_tests/table_schema.rs
  server/src/snapshot.rs
  src/commands/convert.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1023 chore: Add debuginfo=0 to CI builds
  .github/workflows/rust.yml
Labels: automerge, kodiak: merge.method = 'rebase'

#1024 chore: install lld in CI image and remove musl
  docker/Dockerfile.ci
Labels: automerge, kodiak: merge.method = 'squash'

#1022 chore: use lld on linux
  .cargo/config
Labels: automerge, kodiak: merge.method = 'squash'

#1027 fix(ci): Pass debuginfo=1 to have line numbers in tracebacks
  .github/workflows/rust.yml
Labels: automerge, kodiak: merge.method = 'rebase'

#1017 chore: Upgrade flatbuffers and check in generated code
  .gitattributes
  CONTRIBUTING.md
  Cargo.lock
  README.md
  docker/Dockerfile.ci
  docs/README.md
  docs/regenerating_flatbuffers.md
  generated_types/.gitignore
  generated_types/Cargo.toml
  generated_types/build.rs
  generated_types/regenerate-flatbuffers.sh
  generated_types/src/lib.rs
  generated_types/src/wal_generated.rs
  internal_types/Cargo.toml
  internal_types/benches/benchmark.rs
  internal_types/src/data.rs
  mutable_buffer/Cargo.toml
  mutable_buffer/src/column.rs
  mutable_buffer/src/database.rs
  mutable_buffer/src/partition.rs
  mutable_buffer/src/table.rs
  server/Cargo.toml
  server/src/buffer.rs
Labels: automerge

#1035 chore: e2e test for unsigned types
  server/src/query_tests/scenarios.rs
  server/src/query_tests/sql.rs
  server/src/query_tests/table_schema.rs
Labels: automerge, iox

#1037 refactor: don't implement serialize for Db
  server/src/db.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1038 feat: share job registry with Db struct
  server/src/config.rs
  server/src/db.rs
  server/src/lib.rs
  server/src/query_tests/utils.rs
  server/src/snapshot.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1036 feat: sequence server shutdown
  src/influxdb_ioxd.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1026 refactor: remove some dead code
  read_buffer/src/chunk.rs
  read_buffer/src/column.rs
  read_buffer/src/lib.rs
  read_buffer/src/row_group.rs
  read_buffer/src/table.rs
  read_buffer/src/value.rs
Labels: automerge

#1032 feat: per-Db background tasks
  server/src/config.rs
  server/src/db.rs
  server/src/lib.rs
  server/src/tracker/history.rs
  server/src/tracker/registry.rs
  src/influxdb_ioxd.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1043 feat: Rework Db to use Catalog for chunk state
  Cargo.lock
  Cargo.toml
  influxdb_iox_client/src/client/management.rs
  mutable_buffer/src/database.rs
  server/Cargo.toml
  server/src/db.rs
  server/src/lib.rs
  server/src/query_tests/scenarios.rs
  src/influxdb_ioxd/rpc/error.rs
  tests/end_to_end_cases/management_api.rs
  tests/end_to_end_cases/management_cli.rs
Labels: automerge, kodiak: merge.method = 'squash'

#936 fix: Sends 404 status code for invalid write path
  src/influxdb_ioxd/http.rs
Labels: automerge

#1044 refactor: Make `Db::mutable_buffer_chunks` and `Db::read_buffer_chunks` private
  server/src/db.rs
  server/src/query_tests/scenarios.rs
  server/src/query_tests/utils.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1046 chore: Upgrade arrow deps
  Cargo.lock
  arrow_deps/Cargo.toml
  query/src/frontend/influxrpc.rs
  query/src/frontend/sql.rs
  query/src/func/selectors.rs
  read_buffer/src/column/encoding/bool.rs
  read_buffer/src/column/encoding/fixed_null.rs
  read_buffer/src/row_group.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1047 refactor: unify serialization of database rules (#973)
  data_types/src/database_rules.rs
  server/src/config.rs
  server/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1052 fix: increase timing tolerance for tracker timing test (#1051)
  server/src/tracker.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1050 fix: support upper case for scientific notation
  influxdb_line_protocol/src/lib.rs
Labels: automerge

#1055 feat: Add prototxt script
  docs/README.md
  docs/protobuf.md
  scripts/prototxt
Labels: automerge, kodiak: merge.method = 'rebase'

#1053 refactor: Add fine grained (object level) catalog locking
  Cargo.lock
  Cargo.toml
  catalog/Cargo.toml
  catalog/src/lib.rs
  server/Cargo.toml
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/partition.rs
  src/influxdb_ioxd/rpc/error.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1056 feat: Add ShardConfig to DatabaseRules proto
  data_types/src/database_rules.rs
  generated_types/protos/influxdata/iox/management/v1/database_rules.proto
  generated_types/protos/influxdata/iox/management/v1/shard.proto
  tests/end_to_end_cases/management_api.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#1049 docs: Use Scan rather than InMemoryScan for clarity
  query/src/frontend/influxrpc.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1060 refactor: Remove async from `PartitionChunk::table_schema`
  query/src/frontend/influxrpc.rs
  query/src/frontend/sql.rs
  query/src/lib.rs
  query/src/test.rs
  server/src/db/chunk.rs
  server/src/query_tests/table_schema.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1030 refactor: write nanosecond timestamps to parquet
  Cargo.lock
  arrow_deps/Cargo.toml
  influxdb_tsm/src/mapper.rs
  ingest/src/lib.rs
  ingest/src/parquet/writer.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1058 feat: use CatalogProvider and SchemaProvider
  query/src/exec.rs
  query/src/exec/context.rs
  query/src/frontend/sql.rs
  query/src/lib.rs
  server/src/db.rs
  server/src/db/catalog/partition.rs
  server/src/lib.rs
  server/src/query_tests/sql.rs
  src/influxdb_ioxd/http.rs
  src/influxdb_ioxd/rpc/flight.rs
  tests/end_to_end_cases/read_cli.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1063 refactor: Remove async from Database trait
  mutable_buffer/src/database.rs
  query/src/lib.rs
  query/src/test.rs
  server/src/db.rs
  server/src/lib.rs
  server/src/query_tests/influxrpc/read_window_aggregate.rs
  server/src/query_tests/scenarios.rs
  server/src/snapshot.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1062 refactor: Remove async from PartitionChunk
  query/src/frontend/influxrpc.rs
  query/src/lib.rs
  query/src/provider/physical.rs
  query/src/test.rs
  server/src/db/chunk.rs
  server/src/snapshot.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1045 feat: lifecycle rules (RFC)
  README.md
  data_types/Cargo.toml
  data_types/src/chunk.rs
  data_types/src/database_rules.rs
  generated_types/protos/influxdata/iox/management/v1/database_rules.proto
  mutable_buffer/src/database.rs
  server/src/config.rs
  server/src/db.rs
  src/commands/database.rs
  tests/end_to_end_cases/management_api.rs
  tests/end_to_end_cases/management_cli.rs
  tests/end_to_end_cases/read_cli.rs
  tests/end_to_end_cases/scenario.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1057 refactor: Manage storage directly in the Catalog
  mutable_buffer/src/chunk.rs
  query/src/lib.rs
  query/src/test.rs
  read_buffer/src/lib.rs
  server/src/config.rs
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/partition.rs
  server/src/db/chunk.rs
  server/src/lib.rs
  server/src/query_tests/utils.rs
  server/src/snapshot.rs
  src/influxdb_ioxd/rpc/error.rs
  tests/end_to_end_cases/management_api.rs
Labels: automerge, kodiak: merge.method = 'squash'

#998 feat: Add support for setup API to influxdb_client
  influxdb2_client/Cargo.toml
  influxdb2_client/examples/setup.rs
  influxdb2_client/src/api/mod.rs
  influxdb2_client/src/api/ready.rs
  influxdb2_client/src/api/setup.rs
  influxdb2_client/src/lib.rs
  influxdb2_client/src/models/authorization.rs
  influxdb2_client/src/models/bucket.rs
  influxdb2_client/src/models/label.rs
  influxdb2_client/src/models/links.rs
  influxdb2_client/src/models/mod.rs
  influxdb2_client/src/models/onboarding.rs
  influxdb2_client/src/models/organization.rs
  influxdb2_client/src/models/permission.rs
  influxdb2_client/src/models/resource.rs
  influxdb2_client/src/models/retention_rule.rs
  influxdb2_client/src/models/user.rs
Labels: automerge

#1067 refactor: remove DbCatalog newtype wrapper
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/catalog/chunk.rs
  server/src/lib.rs
  server/src/query_tests/sql.rs
  src/influxdb_ioxd/http.rs
  src/influxdb_ioxd/rpc/error.rs
  src/influxdb_ioxd/rpc/flight.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1071 refactor: use optional non-zero types
  data_types/src/database_rules.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1068 refactor: Remove `MutableBufferDb` and Partition
  mutable_buffer/src/chunk.rs
  mutable_buffer/src/database.rs
  mutable_buffer/src/lib.rs
  mutable_buffer/src/partition.rs
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/partition.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1072 feat: Add support for listing tables via information_schema.tables
  Cargo.lock
  arrow_deps/Cargo.toml
  query/src/exec/context.rs
  server/src/query_tests/sql.rs
Labels: automerge

#1069 feat: Derive serde for protos
  Cargo.lock
  Cargo.toml
  generated_types/Cargo.toml
  generated_types/build.rs
  google_types/Cargo.toml
  google_types/build.rs
  src/commands/database.rs
  tests/end_to_end_cases/management_cli.rs
Labels: automerge, kodiak: merge.method = 'rebase'

#1074 feat: automated chunk closing
  server/src/db.rs
  server/src/db/catalog.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/partition.rs
  server/src/db/chunk.rs
  src/influxdb_ioxd/rpc/error.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1078 feat: make it easy to get OperationMetadata from Operation
  Cargo.lock
  influxdb_iox_client/Cargo.toml
  influxdb_iox_client/src/client/operations.rs
  src/commands/operations.rs
  tests/end_to_end_cases/management_api.rs
  tests/end_to_end_cases/operations_api.rs
Labels: automerge

#1077 feat: chunk sorting
  server/Cargo.toml
  server/src/db.rs
  server/src/db/catalog.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1065 chore: Move regular CI to CircleCI
  .circleci/config.yml
Labels: automerge

#1090 feat: Add ability to get `PartitionSummary` statistics from a Db
  mutable_buffer/src/chunk.rs
  mutable_buffer/src/table.rs
  query/src/lib.rs
  query/src/test.rs
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/chunk.rs
  server/src/snapshot.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1092 feat: Add TableSummary calculation to ReadBuffer
  Cargo.lock
  data_types/src/partition_metadata.rs
  read_buffer/Cargo.toml
  read_buffer/src/chunk.rs
  read_buffer/src/lib.rs
  read_buffer/src/table.rs
  server/src/db.rs
  server/src/db/chunk.rs
Labels: automerge, kodiak: merge.method = 'squash'

#1080 feat: add new flatbuffer definitions for entries
  generated_types/protos/influxdata/iox/write/v1/entry.fbs
  generated_types/regenerate-flatbuffers.sh
  generated_types/src/entry_generated.rs
  generated_types/src/lib.rs
Labels: automerge
