Repository influxdata/influxdb_iox, pull requests merged in 2021-11, with the labels that each got.

#2771 feat: add negated predicate support to column_names in Read Buffer
  read_buffer/src/chunk.rs
  read_buffer/src/row_group.rs
  read_buffer/src/table.rs
  server/src/db/chunk.rs
Labels: automerge

#2982 feat: add `RemoteService`
  generated_types/build.rs
  generated_types/protos/influxdata/iox/management/v1/service.proto
  generated_types/protos/influxdata/iox/remote/v1/remote.proto
  generated_types/protos/influxdata/iox/remote/v1/service.proto
  generated_types/protos/influxdata/iox/router/v1/service.proto
  generated_types/src/lib.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/mod.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/remote.rs
  influxdb_iox/tests/common/server_fixture.rs
  influxdb_iox/tests/end_to_end_cases/mod.rs
  influxdb_iox/tests/end_to_end_cases/remote_api.rs
  influxdb_iox_client/src/client.rs
  influxdb_iox_client/src/client/remote.rs
Labels: automerge

#3003 feat: migrate write buffer consumer to use DbWrite (#2724)
  Cargo.lock
  data_types/src/sequence.rs
  influxdb_iox/tests/end_to_end_cases/write_buffer.rs
  mutable_batch/src/lib.rs
  mutable_batch/src/payload.rs
  mutable_batch_entry/src/lib.rs
  server/src/db/replay.rs
  server/src/write_buffer.rs
  server/src/write_buffer/metrics.rs
  write_buffer/Cargo.toml
  write_buffer/src/core.rs
  write_buffer/src/file.rs
  write_buffer/src/kafka.rs
  write_buffer/src/mock.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2983 feat: add `DeleteService`
  generated_types/build.rs
  generated_types/protos/influxdata/iox/delete/v1/service.proto
  generated_types/protos/influxdata/iox/management/v1/service.proto
  generated_types/src/lib.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/delete.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/mod.rs
  influxdb_iox/tests/common/server_fixture.rs
  influxdb_iox/tests/end_to_end_cases/delete_api.rs
  influxdb_iox/tests/end_to_end_cases/mod.rs
  influxdb_iox_client/src/client.rs
  influxdb_iox_client/src/client/delete.rs
Labels: automerge

#3002 refactor: move `catalog` protobuf to `preserved_catalog`
  generated_types/build.rs
  generated_types/protos/influxdata/iox/preserved_catalog/v1/catalog.proto
  generated_types/protos/influxdata/iox/preserved_catalog/v1/parquet_metadata.proto
  generated_types/protos/influxdata/iox/preserved_catalog/v1/predicate.proto
  generated_types/src/lib.rs
  parquet_catalog/src/core.rs
  parquet_catalog/src/dump.rs
  parquet_catalog/src/internals/proto_io.rs
  parquet_catalog/src/internals/proto_parse.rs
  parquet_catalog/src/internals/types.rs
  parquet_file/src/metadata.rs
  predicate/src/delete_expr.rs
  predicate/src/serialize.rs
Labels: automerge

#2988 fix: Only use timestamps in first/last when there is a corresponding …
  query/src/func/selectors/internal.rs
  query_tests/src/influxrpc/read_group.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3008 refactor: decouple new router server configs from old management system
  data_types/src/database_rules.rs
  data_types/src/lib.rs
  data_types/src/write_buffer.rs
  generated_types/build.rs
  generated_types/protos/influxdata/iox/management/v1/database_rules.proto
  generated_types/protos/influxdata/iox/router/v1/router.proto
  generated_types/protos/influxdata/iox/router/v1/shard.proto
  generated_types/protos/influxdata/iox/write_buffer/v1/write_buffer.proto
  generated_types/src/database_rules.rs
  generated_types/src/lib.rs
  generated_types/src/write_buffer.rs
  influxdb_iox/tests/end_to_end_cases/scenario.rs
  influxdb_iox/tests/end_to_end_cases/write_buffer.rs
  influxdb_iox_client/src/client/management.rs
  iox_data_generator/src/bin/create_database.rs
  server/src/database.rs
  server/src/lib.rs
  server/tests/write_buffer.rs
  write_buffer/src/config.rs
  write_buffer/src/file.rs
  write_buffer/src/kafka.rs
  write_buffer/src/mock.rs
Labels: automerge, incompatible protobuf

#3013 feat: reduce lock metric cardinality
  server/src/db.rs
  server/src/db/catalog/metrics.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3012 chore: Update DataFusion
  Cargo.lock
  datafusion/Cargo.toml
  parquet_file/src/storage.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3006 feat: add alternative string encodings to pbdata (#2724)
  entry/src/entry.rs
  generated_types/protos/influxdata/pbdata/v1/influxdb_pb_data_protocol.proto
  influxdb_iox/tests/end_to_end_cases/write_pb.rs
  mutable_batch_pb/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3009 feat: pbdata encode (#2724)
  Cargo.lock
  arrow_util/src/string.rs
  mutable_batch/src/column.rs
  mutable_batch_pb/Cargo.toml
  mutable_batch_pb/src/decode.rs
  mutable_batch_pb/src/encode.rs
  mutable_batch_pb/src/lib.rs
  mutable_batch_pb/tests/encode.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3017 refactor: extract codec module for write buffer (#2724)
  write_buffer/src/codec.rs
  write_buffer/src/file.rs
  write_buffer/src/kafka.rs
  write_buffer/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3018 feat: use protobuf encoding in write buffer (#2724)
  Cargo.lock
  generated_types/protos/influxdata/iox/write_buffer/v1/write_buffer.proto
  mutable_batch_pb/src/decode.rs
  write_buffer/Cargo.toml
  write_buffer/src/codec.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3019 refactor: warn when we receive broken data from write buffer
  server/src/write_buffer.rs
Labels: automerge

#3015 refactor: remove chunk module from mutable_buffer
  mutable_buffer/src/chunk.rs
  mutable_buffer/src/lib.rs
  mutable_buffer/src/snapshot.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3010 fix: dockerfiles should select database server mode by default
  Dockerfile
  docker/Dockerfile.iox
Labels: automerge, kodiak: merge.method = 'squash'

#3011 feat: add mutable_batch_tests (#2724)
  Cargo.lock
  Cargo.toml
  mutable_batch_lp/Cargo.toml
  mutable_batch_lp/benches/write_lp.rs
  mutable_batch_tests/Cargo.toml
  mutable_batch_tests/benches/write_entry.rs
  mutable_batch_tests/benches/write_lp.rs
  mutable_batch_tests/benches/write_pb.rs
  mutable_batch_tests/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2990 fix: Handle errors and rule updates correctly with UUIDs
  generated_types/protos/influxdata/iox/management/v1/service.proto
  influxdb_iox/src/commands/database.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/error.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/management.rs
  influxdb_iox/tests/end_to_end_cases/management_api.rs
  influxdb_iox/tests/end_to_end_cases/management_cli.rs
  influxdb_iox_client/src/client/management.rs
  iox_object_store/src/lib.rs
  server/src/database.rs
  server/src/lib.rs
  server/src/rules.rs
Labels: automerge

#3025 chore: update dependencies
  Cargo.lock
  server/src/db.rs
Labels: automerge

#3021 feat: migrate write buffer producer to MutableBatch and pbdata (#2743)
  Cargo.lock
  arrow_util/src/bitset.rs
  arrow_util/src/dictionary.rs
  arrow_util/src/string.rs
  influxdb_iox/tests/end_to_end_cases/scenario.rs
  influxdb_iox/tests/end_to_end_cases/write_buffer.rs
  mutable_batch/src/column.rs
  mutable_batch/src/lib.rs
  mutable_batch/src/payload.rs
  server/Cargo.toml
  server/src/database.rs
  server/src/db.rs
  server/src/db/replay.rs
  server/src/write_buffer.rs
  server/tests/write_buffer.rs
  write_buffer/Cargo.toml
  write_buffer/src/codec.rs
  write_buffer/src/core.rs
  write_buffer/src/file.rs
  write_buffer/src/kafka.rs
  write_buffer/src/mock.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3027 refactor: remove Entry from Db interfaces (#2724)
  influxdb_iox/src/influxdb_ioxd/server_type/database/http.rs
  server/src/database.rs
  server/src/database/metrics.rs
  server/src/db.rs
  server/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#2989 feat: new data generator
  Cargo.lock
  iox_data_generator/Cargo.toml
  iox_data_generator/README.md
  iox_data_generator/benches/point_generation.rs
  iox_data_generator/schemas/cap-write.toml
  iox_data_generator/schemas/full_example.toml
  iox_data_generator/schemas/fully-supported.toml
  iox_data_generator/schemas/storage_cardinality_example.toml
  iox_data_generator/schemas/telegraf.toml
  iox_data_generator/schemas/tracing-spec.toml
  iox_data_generator/src/agent.rs
  iox_data_generator/src/bin/iox_data_generator.rs
  iox_data_generator/src/field.rs
  iox_data_generator/src/lib.rs
  iox_data_generator/src/measurement.rs
  iox_data_generator/src/specification.rs
  iox_data_generator/src/substitution.rs
  iox_data_generator/src/tag.rs
  iox_data_generator/src/tag_pair.rs
  iox_data_generator/src/tag_set.rs
  iox_data_generator/src/write.rs
  perf/battery-0/datagen.toml
Labels: automerge

#3028 feat: add basic CRUD operations for router configs
  data_types/src/consistent_hasher.rs
  data_types/src/lib.rs
  data_types/src/router.rs
  generated_types/Cargo.toml
  generated_types/protos/influxdata/iox/router/v1/router.proto
  generated_types/protos/influxdata/iox/router/v1/service.proto
  generated_types/src/lib.rs
  generated_types/src/router.rs
  influxdb_iox/src/influxdb_ioxd/server_type/router/rpc/mod.rs
  influxdb_iox/src/influxdb_ioxd/server_type/router/rpc/router.rs
  influxdb_iox/tests/common/server_fixture.rs
  influxdb_iox/tests/end_to_end_cases/mod.rs
  influxdb_iox/tests/end_to_end_cases/router_api.rs
  influxdb_iox_client/src/client.rs
  influxdb_iox_client/src/client/router.rs
  router/src/lib.rs
  router/src/router.rs
  router/src/server.rs
Labels: automerge

#3033 feat: implement `RemoteService` for new router mode
  influxdb_iox/src/commands/run/router.rs
  influxdb_iox/src/influxdb_ioxd/server_type/router/rpc/mod.rs
  influxdb_iox/src/influxdb_ioxd/server_type/router/rpc/remote.rs
  influxdb_iox/tests/end_to_end_cases/remote_api.rs
  router/src/lib.rs
  router/src/resolver.rs
  router/src/server.rs
Labels: automerge

#3031 feat: simplify sharding
  data_types/src/database_rules.rs
  entry/src/entry.rs
  generated_types/protos/influxdata/iox/management/v1/shard.proto
  generated_types/src/database_rules/shard.rs
  influxdb_iox/tests/end_to_end_cases/scenario.rs
  influxdb_iox/tests/end_to_end_cases/write_api.rs
  server/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3039 feat: implement sharder for new router
  Cargo.lock
  router/Cargo.toml
  router/src/lib.rs
  router/src/sharder.rs
Labels: automerge

#3035 feat: migrate server to DbWrite (#2724)
  .circleci/config.yml
  Cargo.lock
  influxdb_iox/Cargo.toml
  influxdb_iox/src/influxdb_ioxd/server_type/database/http.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/error.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/write.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/write_pb.rs
  influxdb_iox/tests/end_to_end_cases/http.rs
  influxdb_iox/tests/end_to_end_cases/write_api.rs
  mutable_batch/src/payload.rs
  mutable_batch_entry/src/lib.rs
  mutable_batch_lp/src/lib.rs
  router/src/sharder.rs
  server/Cargo.toml
  server/src/connection.rs
  server/src/db.rs
  server/src/lib.rs
  server/src/write_buffer.rs
  write_buffer/src/codec.rs
  write_buffer/src/core.rs
  write_buffer/src/file.rs
  write_buffer/src/kafka.rs
  write_buffer/src/mock.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3036 fix: Change database paths to be under /dbs/ instead of under /[server id]/
  influxdb_iox/src/commands/debug/dump_catalog.rs
  influxdb_iox/tests/end_to_end_cases/scenario.rs
  iox_object_store/src/lib.rs
  iox_object_store/src/paths.rs
  iox_object_store/src/paths/parquet_file.rs
  iox_object_store/src/paths/transaction_file.rs
  parquet_file/src/test_utils.rs
  server/src/database.rs
  server/src/db/load.rs
  server/src/lib.rs
  server/src/utils.rs
Labels: automerge

#3046 feat: add redpanda to CI image
  docker/Dockerfile.ci
  docker/Dockerfile.ci.dockerignore
  docker/redpanda.gpg
Labels: automerge, kodiak: merge.method = 'squash'

#3034 chore: use latest DataFusion to fix the min/max(dictionary string) bug
  Cargo.lock
  datafusion/Cargo.toml
  query_tests/cases/in/basic.expected
  query_tests/cases/in/basic.sql
  query_tests/cases/in/delete_multi_expr_one_chunk.expected
  query_tests/cases/in/delete_multi_expr_one_chunk.sql
  query_tests/cases/in/delete_three_delete_three_chunks.expected
  query_tests/cases/in/delete_three_delete_three_chunks.sql
  query_tests/src/sql.rs
Labels: automerge

#3043 feat: remove legacy write service from influxdb_iox_client
  Cargo.lock
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/database.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/mod.rs
  influxdb_iox/tests/end_to_end_cases/delete_api.rs
  influxdb_iox/tests/end_to_end_cases/deletes.rs
  influxdb_iox/tests/end_to_end_cases/deployment_api.rs
  influxdb_iox/tests/end_to_end_cases/freeze.rs
  influxdb_iox/tests/end_to_end_cases/management_api.rs
  influxdb_iox/tests/end_to_end_cases/persistence.rs
  influxdb_iox/tests/end_to_end_cases/scenario.rs
  influxdb_iox/tests/end_to_end_cases/system_tables.rs
  influxdb_iox/tests/end_to_end_cases/write_api.rs
  influxdb_iox/tests/end_to_end_cases/write_buffer.rs
  influxdb_iox_client/Cargo.toml
  influxdb_iox_client/src/client/write.rs
  iox_data_generator/src/bin/create_database.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3051 test: add negative test for CREATE EXTERNAL TABLE
  query_tests/src/sql.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3044 feat: remove influxdata.iox.write.v1.WriteService
  generated_types/build.rs
  generated_types/protos/influxdata/iox/write/v1/service.proto
  generated_types/src/lib.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/mod.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/write.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3047 feat: unify workflows and add ability to manually trigger CI image
  .circleci/config.yml
Labels: automerge, kodiak: merge.method = 'squash'

#3045 feat: remove flatbuffer entry
  .circleci/config.yml
  CONTRIBUTING.md
  Cargo.lock
  Cargo.toml
  docker/Dockerfile.ci
  docs/README.md
  docs/regenerating_flatbuffers.md
  entry/Cargo.toml
  entry/check-flatbuffers.sh
  entry/regenerate-flatbuffers.sh
  entry/src/entry.fbs
  entry/src/entry.rs
  entry/src/entry_generated.rs
  entry/src/lib.rs
  influxdb_iox/Cargo.toml
  mutable_batch_entry/Cargo.toml
  mutable_batch_entry/src/lib.rs
  mutable_batch_tests/Cargo.toml
  mutable_batch_tests/benches/write_entry.rs
  mutable_buffer/Cargo.toml
  query_tests/check-generated.sh
  server_benchmarks/Cargo.toml
  write_buffer/Cargo.toml
  write_buffer/src/codec.rs
  write_buffer/src/kafka.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3060 chore: ignore `RUSTSEC-2021-0122`
  .cargo/audit.toml
Labels: automerge

#3040 feat: add connection management for router
  Cargo.lock
  data_types/src/write_buffer.rs
  generated_types/src/write_buffer.rs
  router/Cargo.toml
  router/src/connection_pool.rs
  router/src/grpc_client.rs
  router/src/lib.rs
  write_buffer/src/kafka.rs
Labels: automerge

#3061 ci: use new, public `quay.io/influxdb/iox` image
  .circleci/config.yml
Labels: automerge

#3064 ci: fix `get-deploy-tags.sh`
  .circleci/get-deploy-tags.sh
Labels: automerge

#3065 refactor: move delete predicate proto to own package (#2731)
  generated_types/build.rs
  generated_types/protos/influxdata/iox/predicate/v1/predicate.proto
  generated_types/protos/influxdata/iox/preserved_catalog/v1/catalog.proto
  generated_types/src/lib.rs
  predicate/src/delete_expr.rs
  predicate/src/serialize.rs
Labels: automerge, kodiak: merge.method = 'squash', incompatible protobuf

#3042 feat: router core logic
  data_types/src/router.rs
  influxdb_iox/src/commands/run/router.rs
  router/src/lib.rs
  router/src/router.rs
  router/src/server.rs
  router/src/write_sink.rs
Labels: automerge

#3066 ci: fix quay login for image promotion
  .circleci/config.yml
Labels: automerge, kodiak: merge.method = 'squash'

#3054 fix: statistics for max/min(time) should have data type timstamp
  Cargo.lock
  query/src/pruning.rs
  query/src/statistics.rs
  query_tests/cases/in/delete_multi_expr_one_chunk.expected
  query_tests/cases/in/delete_multi_expr_one_chunk.sql
  query_tests/cases/in/delete_simple_pred_one_chunk.expected
  query_tests/cases/in/delete_simple_pred_one_chunk.sql
  query_tests/cases/in/delete_three_delete_three_chunks.expected
  query_tests/cases/in/delete_three_delete_three_chunks.sql
  query_tests/src/scenarios/delete.rs
  query_tests/src/sql.rs
Labels: automerge

#3069 test: add group by tests
  query_tests/cases/in/delete_multi_expr_one_chunk.expected
  query_tests/cases/in/delete_multi_expr_one_chunk.sql
  query_tests/cases/in/delete_three_delete_three_chunks.expected
  query_tests/cases/in/delete_three_delete_three_chunks.sql
  query_tests/src/sql.rs
Labels: automerge

#3067 feat: gRPC PB-write interface for new router
  influxdb_iox/src/influxdb_ioxd/server_type/router/rpc/mod.rs
  influxdb_iox/src/influxdb_ioxd/server_type/router/rpc/write_pb.rs
  influxdb_iox/tests/end_to_end_cases/scenario.rs
  influxdb_iox/tests/end_to_end_cases/write_pb.rs
Labels: automerge

#3072 chore(github): new issue template for developer experience
  .github/ISSUE_TEMPLATE/developer_experience.md
Labels: automerge

#3078 ci: also push `:main` tag in addition to SHA-based ones
  .circleci/config.yml
Labels: automerge

#3079 ci: fix usage of old docker version
  .circleci/config.yml
Labels: automerge

#3049 refactor: merge CI integration tests
  .circleci/config.yml
  docker/Dockerfile.ci.integration
  docker/Dockerfile.ci.integration.dockerignore
  docker/ci-kafka-docker-compose.yml
  docs/testing.md
Labels: automerge, kodiak: merge.method = 'squash'

#3077 feat: HTTP write interface for new router
  Cargo.lock
  influxdb_iox/Cargo.toml
  influxdb_iox/src/influxdb_ioxd/http/test_utils.rs
  influxdb_iox/src/influxdb_ioxd/http/write.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/http.rs
  influxdb_iox/src/influxdb_ioxd/server_type/router/http.rs
  influxdb_iox/src/influxdb_ioxd/server_type/router/mod.rs
  router/src/server.rs
  trace/src/lib.rs
  trace_exporters/src/export.rs
Labels: automerge

#3082 ci: run clippy for all features
  .circleci/config.yml
  influxdb_iox/Cargo.toml
  influxdb_iox/src/influxdb_ioxd.rs
  influxdb_iox/src/main.rs
  object_store/src/aws.rs
  object_store/src/azure.rs
Labels: automerge

#3084 refactor: extract DML types (#2731)
  Cargo.lock
  Cargo.toml
  dml/Cargo.toml
  dml/src/lib.rs
  influxdb_iox/Cargo.toml
  influxdb_iox/src/influxdb_ioxd/http/write.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/http.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/write_pb.rs
  influxdb_iox/src/influxdb_ioxd/server_type/router/http.rs
  influxdb_iox/src/influxdb_ioxd/server_type/router/rpc/write_pb.rs
  influxdb_iox/tests/end_to_end_cases/write_pb.rs
  influxdb_iox_client/Cargo.toml
  influxdb_iox_client/src/client/write.rs
  mutable_batch/Cargo.toml
  mutable_batch/src/lib.rs
  mutable_batch/src/payload.rs
  mutable_batch_pb/Cargo.toml
  mutable_batch_pb/src/encode.rs
  mutable_batch_tests/Cargo.toml
  mutable_batch_tests/benches/write_pb.rs
  router/Cargo.toml
  router/src/grpc_client.rs
  router/src/router.rs
  router/src/sharder.rs
  router/src/write_sink.rs
  server/Cargo.toml
  server/src/connection.rs
  server/src/database.rs
  server/src/db.rs
  server/src/db/write.rs
  server/src/lib.rs
  server/src/write_buffer.rs
  server/src/write_buffer/metrics.rs
  write_buffer/Cargo.toml
  write_buffer/src/codec.rs
  write_buffer/src/core.rs
  write_buffer/src/file.rs
  write_buffer/src/kafka.rs
  write_buffer/src/mock.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3083 refactor: remove unused once
  internal_types/src/lib.rs
  internal_types/src/once.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3048 fix: Store the restore database UUID as bytes instead of as a string
  generated_types/protos/influxdata/iox/management/v1/service.proto
  influxdb_iox/src/commands/database.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/management.rs
  influxdb_iox/tests/end_to_end_cases/management_api.rs
  influxdb_iox_client/src/client/management.rs
Labels: automerge, incompatible protobuf

#3087 feat: remove legacy per-line partitioning logic
  Cargo.lock
  data_types/Cargo.toml
  data_types/src/database_rules.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3085 docs: add build instructions for Apple Silicon
  README.md
Labels: automerge

#3088 chore: allow image server mode to be chosen via env var
  docker/Dockerfile.iox
  docker/entrypoint.sh
Labels: automerge

#3081 chore: faster and smaller IOx binaries
  .circleci/config.yml
  Cargo.toml
Labels: automerge

#3092 fix: also export `write_buffer` gRPC types from router client
  influxdb_iox_client/src/client/router.rs
Labels: automerge

#3093 fix: `perf_image` docker ignore
  docker/Dockerfile.iox.dockerignore
Labels: automerge

#3038 feat: Database disown API
  generated_types/protos/influxdata/iox/management/v1/server_config.proto
  generated_types/protos/influxdata/iox/management/v1/service.proto
  influxdb_iox/src/commands/database.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/error.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/management.rs
  influxdb_iox/tests/end_to_end_cases/management_api.rs
  influxdb_iox/tests/end_to_end_cases/management_cli.rs
  influxdb_iox_client/src/client/management.rs
  server/src/database.rs
  server/src/lib.rs
Labels: automerge

#3086 refactor: align HTTP error handling w/ cloud 2
  influxdb_iox/src/influxdb_ioxd/http/error.rs
  influxdb_iox/src/influxdb_ioxd/http/mod.rs
  influxdb_iox/src/influxdb_ioxd/http/utils.rs
  influxdb_iox/src/influxdb_ioxd/http/write.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/http.rs
  influxdb_iox/src/influxdb_ioxd/server_type/mod.rs
  influxdb_iox/src/influxdb_ioxd/server_type/router/http.rs
  influxdb_iox/tests/end_to_end_cases/http.rs
Labels: automerge

#3099 fix: Remove unused dependencies
  Cargo.lock
  influxdb_iox/Cargo.toml
Labels: automerge

#3096 feat: WriteBufferReader use DmlOperation (#2731)
  dml/src/lib.rs
  influxdb_iox/tests/end_to_end_cases/write_buffer.rs
  influxdb_iox/tests/end_to_end_cases/write_pb.rs
  server/src/db/replay.rs
  server/src/write_buffer.rs
  server/src/write_buffer/metrics.rs
  write_buffer/src/codec.rs
  write_buffer/src/core.rs
  write_buffer/src/file.rs
  write_buffer/src/mock.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3094 refactor: move delete predicate into data_types (#2731)
  Cargo.lock
  data_types/Cargo.toml
  data_types/src/delete_predicate.rs
  data_types/src/lib.rs
  dml/Cargo.toml
  influxdb_iox/src/influxdb_ioxd/server_type/database/http.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/delete.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/management.rs
  parquet_catalog/src/cleanup.rs
  parquet_catalog/src/core.rs
  parquet_catalog/src/interface.rs
  parquet_catalog/src/test_helpers.rs
  predicate/src/delete_expr.rs
  predicate/src/delete_predicate.rs
  predicate/src/serialize.rs
  query/src/lib.rs
  query/src/test.rs
  query_tests/src/influxrpc/read_filter.rs
  query_tests/src/influxrpc/read_group.rs
  query_tests/src/influxrpc/read_window_aggregate.rs
  query_tests/src/scenarios.rs
  query_tests/src/scenarios/delete.rs
  query_tests/src/scenarios/util.rs
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/partition.rs
  server/src/db/chunk.rs
  server/src/db/lifecycle/compact.rs
  server/src/db/lifecycle/persist.rs
  server/src/db/load.rs
  server/tests/delete.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3091 fix: server IDs for routers on startup + improve client error handling
  influxdb_iox/src/commands/run/router.rs
  influxdb_iox/tests/common/server_fixture.rs
  influxdb_iox/tests/end_to_end_cases/deployment_api.rs
  influxdb_iox/tests/end_to_end_cases/metrics.rs
  influxdb_iox/tests/end_to_end_cases/scenario.rs
  influxdb_iox/tests/end_to_end_cases/tracing.rs
  influxdb_iox/tests/end_to_end_cases/write_buffer.rs
  influxdb_iox_client/Cargo.toml
  influxdb_iox_client/src/client/deployment.rs
Labels: automerge

#3107 feat: improve `RouterClient` errors
  influxdb_iox/tests/end_to_end_cases/router_api.rs
  influxdb_iox_client/src/client/router.rs
Labels: automerge

#3108 refactor: move delete predicate proto serialization to generated_types
  Cargo.lock
  generated_types/src/delete_predicate.rs
  generated_types/src/lib.rs
  generated_types/src/write_buffer.rs
  parquet_catalog/src/core.rs
  predicate/Cargo.toml
  predicate/src/delete_expr.rs
  predicate/src/lib.rs
  predicate/src/serialize.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3109 refactor: improve usability of proto conversion traits
  generated_types/src/chunk.rs
  generated_types/src/database_rules.rs
  generated_types/src/database_rules/lifecycle.rs
  generated_types/src/database_rules/partition.rs
  generated_types/src/database_rules/shard.rs
  generated_types/src/database_rules/sink.rs
  generated_types/src/delete_predicate.rs
  generated_types/src/google.rs
  generated_types/src/router.rs
  generated_types/src/write_buffer.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/delete.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/management.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/operations.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/write_pb.rs
  influxdb_iox/src/influxdb_ioxd/server_type/router/rpc/router.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3115 refactor: clarify `ServerType` background worker handling
  influxdb_iox/src/influxdb_ioxd.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/mod.rs
  influxdb_iox/src/influxdb_ioxd/server_type/mod.rs
  influxdb_iox/src/influxdb_ioxd/server_type/router/mod.rs
Labels: automerge

#3090 feat: Add an Adopt Database API
  generated_types/protos/influxdata/iox/management/v1/service.proto
  influxdb_iox/src/commands/database.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/error.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/management.rs
  influxdb_iox/tests/end_to_end_cases/management_api.rs
  influxdb_iox/tests/end_to_end_cases/management_cli.rs
  influxdb_iox_client/src/client/management.rs
  server/src/database.rs
  server/src/lib.rs
Labels: automerge

#3111 feat: Rename database disown/adopt to release/claim
  generated_types/protos/influxdata/iox/management/v1/server_config.proto
  generated_types/protos/influxdata/iox/management/v1/service.proto
  influxdb_iox/src/commands/database.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/error.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/management.rs
  influxdb_iox/tests/end_to_end_cases/management_api.rs
  influxdb_iox/tests/end_to_end_cases/management_cli.rs
  influxdb_iox_client/src/client/management.rs
  server/src/database.rs
  server/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3113 fix: ensure `ConsistenHasher` is consistent
  Cargo.lock
  data_types/Cargo.toml
  data_types/src/consistent_hasher.rs
Labels: automerge

#3121 refactor: DMLOperation write path (#2731)
  dml/src/lib.rs
  influxdb_iox/src/influxdb_ioxd/server_type/router/http.rs
  influxdb_iox/src/influxdb_ioxd/server_type/router/rpc/write_pb.rs
  router/src/grpc_client.rs
  router/src/router.rs
  router/src/sharder.rs
  router/src/write_sink.rs
  server/src/database.rs
  server/src/db.rs
  server/src/lib.rs
  write_buffer/src/codec.rs
  write_buffer/src/core.rs
  write_buffer/src/file.rs
  write_buffer/src/kafka.rs
  write_buffer/src/mock.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3120 feat: emit Kafka stats as metrics instead of logs
  Cargo.lock
  router/src/connection_pool.rs
  router/src/server.rs
  router/src/write_sink.rs
  server/src/application.rs
  write_buffer/Cargo.toml
  write_buffer/src/config.rs
  write_buffer/src/kafka.rs
Labels: automerge

#3130 fix: capture all panic messages in logs
  influxdb_iox/src/influxdb_ioxd/rpc/testing.rs
  panic_logging/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3135 chore: upgrade tokio to 1.14.0 to fix RUSTSEC-2021-0124
  Cargo.lock
Labels: automerge

#3134 ci: update CI images from docker buster to bullseye
  .circleci/config.yml
  Dockerfile
  docker/Dockerfile.ci
  docker/Dockerfile.iox
Labels: automerge

#3131 fix: Default kafka timeout to be shorter than gRPC timeout (60 sec --> 10 sec)
  influxdb_iox/tests/end_to_end_cases/management_api.rs
  write_buffer/src/kafka.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3137 build: remove proc-macro2 pin
  Cargo.lock
  generated_types/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#3136 chore: Update datafusion + arrow/parquet/arrow-flight 6.2.0
  Cargo.lock
  datafusion/Cargo.toml
  server/src/db/access.rs
  server/src/db/system_tables.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3129 feat: Add kafka write buffer consumer metrics
  write_buffer/src/kafka.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3127 feat: add write buffer delete encoding (#2731)
  data_types/src/lib.rs
  data_types/src/non_empty.rs
  dml/src/lib.rs
  generated_types/protos/influxdata/iox/delete/v1/service.proto
  generated_types/protos/influxdata/iox/write_buffer/v1/write_buffer.proto
  influxdb_iox/src/influxdb_ioxd/server_type/database/http.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/delete.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/management.rs
  influxdb_iox/tests/end_to_end_cases/write_buffer.rs
  query_tests/src/scenarios/util.rs
  router/src/grpc_client.rs
  router/src/sharder.rs
  server/src/db.rs
  server/src/db/lifecycle/compact.rs
  server/src/db/lifecycle/persist.rs
  server/src/db/replay.rs
  server/src/write_buffer.rs
  server/src/write_buffer/metrics.rs
  server/tests/delete.rs
  server/tests/write_buffer_compaction.rs
  server/tests/write_buffer_delete.rs
  write_buffer/src/codec.rs
  write_buffer/src/core.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3142 refactor: extract Mailbox type (#3126)
  internal_types/src/lib.rs
  internal_types/src/mailbox.rs
  server/src/db.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3138 ci: update CI image builder to use newer docker
  .circleci/config.yml
Labels: automerge

#3148 docs: document differences between Mailbox and channel
  internal_types/src/mailbox.rs
Labels: kodiak: merge.method = 'squash'

#3152 docs: Tweak comments on Mailbox
  internal_types/src/mailbox.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3118 fix: Make delete/restore aliases for release/claim; remove tombstone
  Cargo.lock
  generated_types/protos/influxdata/iox/management/v1/service.proto
  influxdb_iox/src/commands/database.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/error.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/management.rs
  influxdb_iox/tests/end_to_end_cases/deletes.rs
  influxdb_iox/tests/end_to_end_cases/management_api.rs
  influxdb_iox/tests/end_to_end_cases/management_cli.rs
  influxdb_iox_client/src/client/management.rs
  iox_object_store/Cargo.toml
  iox_object_store/src/lib.rs
  iox_object_store/src/paths.rs
  server/src/database.rs
  server/src/lib.rs
Labels: automerge

#3133 chore: update one-shot Dockerfile to not depend on rust:ci
  Dockerfile
Labels: automerge, kodiak: merge.method = 'squash'

#3160 fix: Small cleanups in Cargo.tomls
  Cargo.toml
  arrow_util/Cargo.toml
  client_util/Cargo.toml
  influxdb_iox/Cargo.toml
  mutable_batch_pb/Cargo.toml
  parquet_catalog/Cargo.toml
  query_tests/Cargo.toml
  server/Cargo.toml
  write_buffer/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#3147 feat: flush delete mailbox on persist (#3126)
  data_types/src/non_empty.rs
  server/src/db/lifecycle/write.rs
  server/src/db/replay.rs
  write_buffer/src/mock.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3144 feat: Move server config paths beneath 'nodes'
  influxdb_iox/tests/end_to_end_cases/management_api.rs
  iox_object_store/src/lib.rs
  iox_object_store/src/paths.rs
  server/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3159 fix: reduce verbosity of logs
  query/src/provider.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3163 refactor: add parquet chunk generator (#2209)
  parquet_file/src/metadata.rs
  parquet_file/src/storage.rs
  parquet_file/src/test_utils.rs
  parquet_file/src/test_utils/generator.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3155 refactor: form `system.column_chunks` column by column rather than row by row
  server/src/db/system_tables/columns.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3169 feat: reduce cardinality of job metrics
  server/src/job.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3167 refactor: use ChunkGenerator in parquet_catalog (#2209)
  parquet_catalog/src/cleanup.rs
  parquet_catalog/src/core.rs
  parquet_catalog/src/dump.rs
  parquet_catalog/src/interface.rs
  parquet_catalog/src/test_helpers.rs
  parquet_file/src/test_utils.rs
  parquet_file/src/test_utils/generator.rs
  server/src/db/catalog/chunk.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3153 feat: skip applying deletes to persisted chunks during replay (#3125)
  server/src/db.rs
  server/src/db/replay.rs
  server/src/db/write.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3156 feat: compact_object_store_chunks : initial implementation that also lists steps to complete
  data_types/src/chunk_metadata.rs
  data_types/src/job.rs
  generated_types/build.rs
  generated_types/protos/influxdata/iox/management/v1/chunk.proto
  generated_types/protos/influxdata/iox/management/v1/jobs.proto
  generated_types/src/chunk.rs
  generated_types/src/job.rs
  lifecycle/src/lib.rs
  lifecycle/src/policy.rs
  server/src/db.rs
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/partition.rs
  server/src/db/lifecycle.rs
  server/src/db/lifecycle/compact_object_store.rs
  server/src/db/lifecycle/error.rs
Labels: automerge

#3168 feat: Add a workspace hack crate by using `cargo hakari`
  .circleci/config.yml
  .guppy/hakari.toml
  Cargo.lock
  Cargo.toml
  arrow_util/Cargo.toml
  client_util/Cargo.toml
  data_types/Cargo.toml
  datafusion/Cargo.toml
  datafusion_util/Cargo.toml
  dml/Cargo.toml
  generated_types/Cargo.toml
  influxdb2_client/Cargo.toml
  influxdb_iox/Cargo.toml
  influxdb_line_protocol/Cargo.toml
  influxdb_storage_client/Cargo.toml
  influxdb_tsm/Cargo.toml
  internal_types/Cargo.toml
  iox_object_store/Cargo.toml
  lifecycle/Cargo.toml
  logfmt/Cargo.toml
  metric/Cargo.toml
  metric_exporters/Cargo.toml
  mutable_batch/Cargo.toml
  mutable_batch_lp/Cargo.toml
  mutable_batch_pb/Cargo.toml
  mutable_buffer/Cargo.toml
  object_store/Cargo.toml
  observability_deps/Cargo.toml
  packers/Cargo.toml
  panic_logging/Cargo.toml
  parquet_catalog/Cargo.toml
  parquet_file/Cargo.toml
  persistence_windows/Cargo.toml
  predicate/Cargo.toml
  query/Cargo.toml
  query_tests/Cargo.toml
  read_buffer/Cargo.toml
  router/Cargo.toml
  schema/Cargo.toml
  server/Cargo.toml
  test_helpers/Cargo.toml
  time/Cargo.toml
  trace/Cargo.toml
  trace_exporters/Cargo.toml
  trace_http/Cargo.toml
  tracker/Cargo.toml
  workspace-hack/.gitattributes
  workspace-hack/Cargo.toml
  workspace-hack/README.md
  workspace-hack/build.rs
  workspace-hack/src/lib.rs
  write_buffer/Cargo.toml
Labels: automerge

#3183 refactor: address review comments
  server/src/db/lifecycle/compact_object_store.rs
Labels: automerge

#3178 chore: update Storage gRPC protobuf defintitions
  generated_types/build.rs
  generated_types/protos/influxdata/platform/storage/service.proto
  generated_types/protos/influxdata/platform/storage/source.proto
  generated_types/protos/influxdata/platform/storage/storage_common.proto
  generated_types/protos/influxdata/platform/storage/storage_common_idpe.proto
  generated_types/src/lib.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/storage/service.rs
  influxdb_iox/tests/end_to_end_cases/storage_api.rs
  influxdb_iox/tests/end_to_end_cases/tracing.rs
  influxdb_storage_client/src/lib.rs
Labels: automerge, incompatible protobuf

#3161 fix: don't retry "forever" sending Kafka messages
  write_buffer/src/kafka.rs
Labels: automerge

#3184 chore: guide community engagement
  README.md
Labels: automerge, kodiak: merge.method = 'squash'

#3188 chore: Update datafusion
  Cargo.lock
  datafusion/Cargo.toml
  query/src/exec.rs
  query_tests/cases/in/duplicates.expected
  query_tests/cases/in/no_stats_plans.expected
  query_tests/cases/in/pushdown.expected
  query_tests/cases/in/stats_plans.expected
Labels: automerge, kodiak: merge.method = 'squash'

#3189 refactor: lifecycle observability cleanup (#2286)
  lifecycle/src/guard.rs
  lifecycle/src/lib.rs
  lifecycle/src/policy.rs
  server/src/db.rs
  server/src/db/lifecycle.rs
  server/src/db/lifecycle/compact.rs
  server/src/db/lifecycle/compact_object_store.rs
  server/src/db/lifecycle/persist.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3195 refactor: remove methods from `ManagementService` that were moved to `DeleteService`.
  generated_types/protos/influxdata/iox/management/v1/service.proto
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/management.rs
  influxdb_iox/tests/end_to_end_cases/management_api.rs
  influxdb_iox_client/src/client/management.rs
Labels: automerge

#3198 fix: flaky incrementing_i64_that_resets (#3197)
  iox_data_generator/src/field.rs
Labels: automerge

#3193 refactor: update tag set ordering for gRPC API
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/storage/data.rs
  influxdb_iox/tests/end_to_end_cases/storage_api.rs
  query/src/exec/seriesset/series.rs
  query_tests/src/influxrpc/read_filter.rs
  query_tests/src/influxrpc/read_group.rs
  query_tests/src/influxrpc/read_window_aggregate.rs
Labels: automerge

#3196 feat: reduce lifecycle log verbosity (#2286)
  lifecycle/src/policy.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3200 fix: flaky test_chunk_access_time (#3197)
  influxdb_iox/tests/end_to_end_cases/management_api.rs
  server/src/db.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3185 feat: compute max checkpoints from chunks' IOx Metadata and tests for contiguous chunks
  server/src/db/catalog/chunk.rs
  server/src/db/catalog/partition.rs
  server/src/db/lifecycle/compact_object_store.rs
  server/src/db/lifecycle/error.rs
Labels: automerge

#3199 feat: support emitting measurement/field tag keys in binary format
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/storage/data.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/storage/service.rs
  query/src/exec/seriesset/series.rs
Labels: automerge

#3201 refactor: remove methods from `ManagementService` that were moved to `DeploymentService`
  generated_types/protos/influxdata/iox/management/v1/service.proto
  influxdb_iox/src/commands/server.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/management.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/mod.rs
  influxdb_iox/tests/end_to_end_cases/management_api.rs
  influxdb_iox/tests/end_to_end_cases/management_cli.rs
  influxdb_iox/tests/end_to_end_cases/metrics.rs
  influxdb_iox/tests/end_to_end_cases/persistence.rs
  influxdb_iox/tests/end_to_end_cases/scenario.rs
  influxdb_iox/tests/end_to_end_cases/tracing.rs
  influxdb_iox/tests/end_to_end_cases/write_api.rs
  influxdb_iox/tests/end_to_end_cases/write_buffer.rs
  influxdb_iox_client/src/client/management.rs
Labels: automerge

#3194 refactor: use serialized predicates instead of strings for gRPC deletes
  generated_types/protos/influxdata/iox/delete/v1/service.proto
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/delete.rs
  influxdb_iox/src/influxdb_ioxd/server_type/router/rpc/delete.rs
  influxdb_iox/tests/end_to_end_cases/delete_api.rs
  influxdb_iox_client/src/client/delete.rs
  router/src/grpc_client.rs
Labels: automerge

#3203 refactor: remove methods from `ManagementService` that were moved to `RemoteService`
  generated_types/protos/influxdata/iox/management/v1/service.proto
  influxdb_iox/src/commands/server_remote.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/management.rs
  influxdb_iox/tests/end_to_end_cases/management_api.rs
  influxdb_iox/tests/end_to_end_cases/write_api.rs
  influxdb_iox_client/src/client/management.rs
Labels: automerge

#3205 refactor: add debug logging for meta queries
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/storage/service.rs
Labels: automerge

#3180 fix: do not forget outputs of file-based write buffer
  Cargo.lock
  write_buffer/Cargo.toml
  write_buffer/src/core.rs
  write_buffer/src/file.rs
Labels: automerge

#3191 feat: HTTP delete support for router
  influxdb_iox/src/influxdb_ioxd/http/dml.rs
  influxdb_iox/src/influxdb_ioxd/http/mod.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/http.rs
  influxdb_iox/src/influxdb_ioxd/server_type/router/http.rs
Labels: automerge

#3204 refactor: prepare to remove router functionality from `server` crate
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/mod.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/remote.rs
  influxdb_iox/src/influxdb_ioxd/server_type/router/rpc/write_pb.rs
  influxdb_iox/tests/end_to_end_cases/deployment_cli.rs
  influxdb_iox/tests/end_to_end_cases/management_cli.rs
  influxdb_iox/tests/end_to_end_cases/mod.rs
  influxdb_iox/tests/end_to_end_cases/remote_api.rs
  influxdb_iox/tests/end_to_end_cases/remote_cli.rs
  influxdb_iox/tests/end_to_end_cases/write_api.rs
Labels: automerge

#3208 fix: ensure time column not returned
  query/src/frontend/influxrpc.rs
  query_tests/src/influxrpc/tag_keys.rs
  query_tests/src/scenarios.rs
Labels: automerge

#3210 refactor: use new router mode in `perf.py`
  perf/perf.py
Labels: automerge

#3206 refactor: clean up write buffer end2end tests
  influxdb_iox/tests/common/server_fixture.rs
  influxdb_iox/tests/end_to_end_cases/scenario.rs
  influxdb_iox/tests/end_to_end_cases/write_buffer.rs
Labels: automerge

#3213 fix: don't project on schema metadata mismatch
  query/src/provider.rs
  query/src/test.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3207 refactor: remove write routing logic from `Server`
  influxdb_iox/src/influxdb_ioxd/server_type/database/http.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/error.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/write_pb.rs
  influxdb_iox/tests/end_to_end_cases/write_buffer.rs
  server/src/db.rs
  server/src/lib.rs
  server/src/resolver.rs
Labels: automerge

#3218 refactor: remove connection manager and resolver from `Server`
  influxdb_iox/src/influxdb_ioxd/server_type/database/http.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/mod.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/delete.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/deployment.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/flight.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/management.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/mod.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/write_pb.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/setup.rs
  server/src/connection.rs
  server/src/lib.rs
  server/src/resolver.rs
  server/tests/write_buffer_delete.rs
Labels: automerge

#3215 feat: test bench
  Cargo.toml
  test_bench/README.md
  test_bench/k8s/base/debug-sidecar-patch.yml
  test_bench/k8s/base/glue-entrypoint.bash
  test_bench/k8s/base/kustomization.yml
  test_bench/k8s/base/minio.yml
  test_bench/k8s/base/query.yml
  test_bench/k8s/base/redpanda.yml
  test_bench/k8s/base/router.yml
  test_bench/k8s/overlays/demo/database-1.json
  test_bench/k8s/overlays/demo/kustomization.yaml
  test_bench/k8s/overlays/demo/router-1.json
Labels: automerge

#3217 feat: disallow unsequenced deletes when reading from write buffer
  influxdb_iox/src/influxdb_ioxd/server_type/database/http.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/delete.rs
  influxdb_iox/tests/end_to_end_cases/write_buffer.rs
  server/src/db.rs
Labels: automerge

#3219 refactor: remove write buffer producer logic from `Db`
  influxdb_iox/src/influxdb_ioxd/server_type/database/http.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/delete.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/write_pb.rs
  query_tests/src/cancellation.rs
  query_tests/src/influxrpc/read_window_aggregate.rs
  query_tests/src/pruning.rs
  query_tests/src/scenarios.rs
  query_tests/src/scenarios/util.rs
  server/src/database.rs
  server/src/db.rs
  server/src/db/chunk.rs
  server/src/db/lifecycle/compact.rs
  server/src/db/lifecycle/compact_object_store.rs
  server/src/db/lifecycle/persist.rs
  server/src/utils.rs
  server/tests/delete.rs
  server_benchmarks/benches/catalog_persistence.rs
Labels: automerge

#3221 refactor: remove write buffer direction
  data_types/src/write_buffer.rs
  generated_types/protos/influxdata/iox/write_buffer/v1/write_buffer.proto
  generated_types/src/write_buffer.rs
  influxdb_iox/tests/end_to_end_cases/management_api.rs
  influxdb_iox/tests/end_to_end_cases/scenario.rs
  influxdb_iox/tests/end_to_end_cases/write_buffer.rs
  iox_data_generator/README.md
  iox_data_generator/src/bin/create_database.rs
  perf/perf.py
  router/src/write_sink.rs
  server/src/database.rs
  server/src/lib.rs
  server/tests/write_buffer_compaction.rs
  server/tests/write_buffer_delete.rs
  test_bench/k8s/overlays/demo/database-1.json
  test_bench/k8s/overlays/demo/router-1.json
  write_buffer/src/config.rs
Labels: automerge

#3220 feat: Add a simple script to decode the IOx metadata of a parquet file
  scripts/parquet-meta-iox
Labels: automerge

#3212 refactor: remove delete predicates from read filter interface
  query/src/lib.rs
  query/src/provider/physical.rs
  query/src/test.rs
  server/src/db.rs
  server/src/db/chunk.rs
  server/src/db/lifecycle/write.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3223 fix: Implement a dummy Storage.Offsets method
  generated_types/protos/influxdata/platform/storage/service.proto
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/storage/service.rs
Labels: automerge

#3232 test: add end to end tests for Storage/Offsets gRPC call
  influxdb_iox/tests/end_to_end_cases/storage_api.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3228 feat: error if persist_age_threshold less than late arrival (#2005)
  generated_types/src/database_rules/lifecycle.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3222 refactor: consolidate sharding implementation
  Cargo.lock
  dml/Cargo.toml
  dml/src/lib.rs
  router/src/lib.rs
  router/src/router.rs
  router/src/sharder.rs
Labels: automerge

#3243 refactor: improve Kafka client usage
  write_buffer/src/kafka.rs
Labels: automerge

#3216 feat: reload chunk back into read buffer (#3209)
  data_types/src/chunk_metadata.rs
  data_types/src/job.rs
  generated_types/build.rs
  generated_types/protos/influxdata/iox/management/v1/chunk.proto
  generated_types/protos/influxdata/iox/management/v1/jobs.proto
  generated_types/src/chunk.rs
  generated_types/src/job.rs
  lifecycle/src/lib.rs
  lifecycle/src/policy.rs
  parquet_file/src/storage.rs
  parquet_file/src/test_utils.rs
  read_buffer/src/row_group.rs
  server/src/db/catalog/chunk.rs
  server/src/db/lifecycle.rs
  server/src/db/lifecycle/error.rs
  server/src/db/lifecycle/load.rs
  server/src/db/lifecycle/unload.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3244 refactor: remove old routing / sharding config
  data_types/src/database_rules.rs
  generated_types/build.rs
  generated_types/protos/influxdata/iox/management/v1/database_rules.proto
  generated_types/protos/influxdata/iox/management/v1/shard.proto
  generated_types/src/database_rules.rs
  generated_types/src/database_rules/shard.rs
  generated_types/src/database_rules/sink.rs
  influxdb_iox/tests/end_to_end_cases/management_api.rs
  influxdb_iox/tests/end_to_end_cases/scenario.rs
  iox_data_generator/src/bin/create_database.rs
  perf/perf.py
  server/src/database.rs
  server/src/lib.rs
  test_bench/k8s/overlays/demo/database-1.json
Labels: automerge

#3246 ci: add `yamllint` and `shellcheck` to CI image
  docker/Dockerfile.ci
Labels: automerge

#3211 feat: test interaction of write buffer and lifecycle (#2811)
  server/src/db.rs
  server/tests/write_buffer_compaction.rs
  server/tests/write_buffer_delete.rs
  server/tests/write_buffer_lifecycle.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3248 ci: run shellcheck and yamllint
  .circleci/config.yml
  .github/dependabot.yml
  .github/semantic.yml
  .yamllint.yml
  buf.yaml
  scripts/logfmts
  scripts/valigrind_leak
Labels: automerge

#3245 refactor: cleanup database recovery (#3225)
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/error.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/management.rs
  influxdb_iox/tests/end_to_end_cases/management_api.rs
  influxdb_iox/tests/end_to_end_cases/management_cli.rs
  server/src/database.rs
  server/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3249 feat: support forcing persistence of partition irrespective of arrival time
  generated_types/protos/influxdata/iox/management/v1/service.proto
  influxdb_iox/src/commands/database/partition.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/management.rs
  influxdb_iox/tests/end_to_end_cases/management_api.rs
  influxdb_iox_client/src/client/management.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3253 feat: rebuild catalog (#3225)
  data_types/src/job.rs
  generated_types/protos/influxdata/iox/management/v1/jobs.proto
  generated_types/protos/influxdata/iox/management/v1/service.proto
  generated_types/src/job.rs
  influxdb_iox/src/commands/database/recover.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/error.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/management.rs
  influxdb_iox/tests/common/server_fixture.rs
  influxdb_iox/tests/end_to_end_cases/management_api.rs
  influxdb_iox/tests/end_to_end_cases/scenario.rs
  influxdb_iox_client/src/client/management.rs
  parquet_catalog/src/rebuild.rs
  server/src/database.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3254 chore: Update `arrow`, `arrow-flight`, and `parquet` to 6.3.0
  Cargo.lock
  parquet_catalog/src/dump.rs
  server/src/db.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3250 feat: load RUB from object store (#3224)
  generated_types/build.rs
  generated_types/protos/influxdata/iox/management/v1/service.proto
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/management.rs
  influxdb_iox/tests/end_to_end_cases/management_api.rs
  influxdb_iox_client/src/client/management.rs
  server/src/db.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3261 chore: ignore `RUSTSEC-2021-0127`
  .cargo/audit.toml
Labels: automerge

#3258 refactor: cleanup Db write path error handling
  influxdb_iox/src/influxdb_ioxd/http/dml.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/http.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/delete.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/error.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/write_pb.rs
  influxdb_iox/tests/end_to_end_cases/delete_api.rs
  influxdb_iox/tests/end_to_end_cases/write_api.rs
  influxdb_iox/tests/end_to_end_cases/write_buffer.rs
  server/src/database.rs
  server/src/db.rs
  server/src/db/replay.rs
  server/src/write_buffer.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3262 fix: GIT version in `--version`
  influxdb_iox/build.rs
  influxdb_iox/tests/end_to_end_cases/debug_cli.rs
Labels: automerge
