Repository influxdata/influxdb_iox, pull requests merged in 2022-06, with the labels that each got.

#4700 test: "optimize" ingesterrecord batches in query tests
  Cargo.lock
  ingester/src/data.rs
  ingester/src/querier_handler.rs
  query_tests/Cargo.toml
  query_tests/src/scenarios/util.rs
Labels: automerge

#4751 feat: add tooling to instrument async semaphores
  tracker/src/async_semaphore.rs
  tracker/src/lib.rs
Labels: automerge

#4753 chore: naming / comment cleanups from namespace semaphore
  clap_blocks/src/querier.rs
  querier/src/database.rs
  querier/src/namespace/mod.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4747 chore: let aggressively increase compactor job size and concurrency level
  clap_blocks/src/compactor.rs
Labels: automerge

#4757 refactor: constructor for ParquetFileWithTombstone
  compactor/src/compact.rs
  compactor/src/utils.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4699 refactor: warn for silly object store configs
  influxdb_iox/src/commands/remote/partition.rs
  influxdb_iox/tests/end_to_end_cases/cli.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4721 fix: Support `_field != <name>` predicates
  predicate/src/lib.rs
  predicate/src/rpc_predicate.rs
  predicate/src/rpc_predicate/field_rewrite.rs
  query_tests/src/influxrpc/read_filter.rs
  service_grpc_influxrpc/src/expr.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4759 refactor: always panic for empty parquet files
  parquet_file/src/serialize.rs
  parquet_file/tests/metadata.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4760 refactor: rework querier concurrency limiting
  Cargo.lock
  querier/src/database.rs
  querier/src/namespace/mod.rs
  service_common/Cargo.toml
  service_common/src/lib.rs
  service_common/src/test_util.rs
  service_grpc_flight/src/lib.rs
  service_grpc_influxrpc/Cargo.toml
  service_grpc_influxrpc/src/service.rs
Labels: automerge

#4722 feat: Cache read buffer chunks
  parquet_file/src/chunk.rs
  parquet_file/src/storage.rs
  querier/src/cache/read_buffer.rs
  querier/src/chunk/mod.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4772 chore: add debug info to see how many concurrent partitions being compacted in each cycle
  compactor/src/handler.rs
Labels: automerge

#4768 docs(various): Improve Readability
  CONTRIBUTING.md
  README.md
  compactor/src/compact.rs
  docs/dedup_and_sort.md
  docs/valgrind.md
  influxdb2_client/README.md
  ingester/src/test_util.rs
  iox_catalog/README.md
  iox_query/src/lib.rs
  iox_query/src/provider.rs
  parquet_file/src/metadata.rs
  parquet_file/tests/metadata.rs
  sqlx-hotswap-pool/README.md
Labels: automerge, kodiak: merge.method = 'squash'

#4770 feat: add owned versions of instrumented semaphores
  tracker/src/async_semaphore.rs
Labels: automerge

#4769 test: query limits
  service_grpc_flight/src/lib.rs
  service_grpc_influxrpc/src/service.rs
Labels: automerge

#4743 chore: Update datafusion + `arrow`/`parquet`/`arrow-flight` to `15.0.0`
  Cargo.lock
  arrow_util/Cargo.toml
  arrow_util/src/dictionary.rs
  arrow_util/src/optimize.rs
  arrow_util/src/string.rs
  compactor/Cargo.toml
  datafusion/Cargo.toml
  influxdb_iox/Cargo.toml
  influxdb_iox_client/Cargo.toml
  ingester/Cargo.toml
  iox_query/Cargo.toml
  iox_query/src/provider.rs
  iox_tests/Cargo.toml
  ioxd_querier/Cargo.toml
  mutable_batch/Cargo.toml
  mutable_batch/src/column.rs
  packers/Cargo.toml
  parquet_file/Cargo.toml
  parquet_file/src/metadata.rs
  parquet_file/src/serialize.rs
  parquet_file/src/storage.rs
  predicate/Cargo.toml
  querier/Cargo.toml
  querier/src/system_tables/mod.rs
  querier/src/table/query_access.rs
  query_functions/Cargo.toml
  query_tests/Cargo.toml
  read_buffer/Cargo.toml
  read_buffer/src/chunk.rs
  read_buffer/src/column/encoding/bool.rs
  read_buffer/src/column/encoding/scalar/fixed_null.rs
  read_buffer/src/column/integer.rs
  read_buffer/src/value.rs
  schema/Cargo.toml
  service_grpc_flight/Cargo.toml
  service_grpc_influxrpc/Cargo.toml
  test_helpers_end_to_end/Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#4775 docs: Add some comments to InstrumentedAsyncOwnedSemaphorePermit
  tracker/src/async_semaphore.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4764 docs: Clean up docs
  docs/README.md
  docs/testing.md
Labels: automerge, kodiak: merge.method = 'squash'

#4766 docs: update logging
  docs/logging.md
Labels: automerge, kodiak: merge.method = 'squash'

#4781 docs: Improving Readability r2
  datafusion/Cargo.toml
  docs/valgrind.md
  iox_data_generator/benches/point_generation.rs
  iox_data_generator/schemas/big_db.toml
  iox_data_generator/schemas/cap-write.toml
  iox_data_generator/schemas/full_example.toml
  iox_data_generator/schemas/storage_cardinality_example.toml
Labels: automerge, kodiak: merge.method = 'squash'

#4779 feat: compact all overlapped files no matter how large they are
  compactor/src/compact.rs
Labels: automerge

#4791 chore: remove irrelevant comments
  compactor/src/compact.rs
Labels: automerge

#4788 chore: Update datafusion (again)
  Cargo.lock
  datafusion/Cargo.toml
  datafusion_util/src/lib.rs
  iox_query/src/util.rs
  predicate/src/lib.rs
  predicate/src/rewrite.rs
  querier/src/namespace/query_access.rs
  query_tests/cases/in/duplicates.expected
  query_tests/cases/in/pushdown.expected
  query_tests/cases/in/several_chunks.expected
  query_tests/cases/in/two_chunks.expected
  query_tests/src/influxrpc/read_group.rs
  service_grpc_influxrpc/src/expr.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4798 feat: wire up RB metrics for querier chunks
  querier/src/cache/mod.rs
  querier/src/cache/read_buffer.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4802 refactor: make `Cache` a trait
  cache_system/src/cache/driver.rs
  cache_system/src/cache/mod.rs
  cache_system/src/cache/test_util.rs
  cache_system/src/lib.rs
  cache_system/src/loader/mod.rs
  querier/src/cache/namespace.rs
  querier/src/cache/parquet_file.rs
  querier/src/cache/partition.rs
  querier/src/cache/processed_tombstones.rs
  querier/src/cache/read_buffer.rs
  querier/src/cache/table.rs
  querier/src/cache/tombstones.rs
Labels: automerge

#4803 chore: remove some unused deps
  Cargo.lock
  object_store_metrics/Cargo.toml
  query_tests/Cargo.toml
Labels: automerge

#4799 refactor: consolidate `PredicateBuilder` into `Predicate`
  generated_types/src/ingester.rs
  ingester/src/querier_handler.rs
  ingester/src/query.rs
  iox_query/src/frontend/influxrpc.rs
  iox_query/src/provider.rs
  iox_query/src/pruning.rs
  predicate/src/lib.rs
  predicate/src/rpc_predicate.rs
  querier/src/table/query_access.rs
  query_tests/src/influxrpc/field_columns.rs
  query_tests/src/influxrpc/read_filter.rs
  query_tests/src/influxrpc/read_group.rs
  query_tests/src/influxrpc/read_window_aggregate.rs
  query_tests/src/influxrpc/table_names.rs
  query_tests/src/influxrpc/tag_keys.rs
  query_tests/src/influxrpc/tag_values.rs
  service_grpc_influxrpc/src/expr.rs
  service_grpc_influxrpc/src/service.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4805 refactor: remove redundant code in `Predicate`
  predicate/src/lib.rs
  predicate/src/rpc_predicate.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4809 fix: Do not run DataFusion optimizer pass twice
  compactor/src/compact.rs
  ingester/src/compact.rs
  ingester/src/querier_handler.rs
  iox_query/src/exec/context.rs
  iox_query/src/frontend.rs
  iox_query/src/frontend/reorg.rs
  query_tests/src/influxrpc/read_filter.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4804 refactor: expose `CacheGetStatus` (and improve tests)
  cache_system/src/cache/driver.rs
  cache_system/src/cache/mod.rs
  cache_system/src/cache/test_util.rs
Labels: automerge

#4810 docs: Add some docs about `StreamSplit`
  iox_query/src/exec/split.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4778 fix: do not return 'readable' until a write is completely readable
  ingester/src/data.rs
  write_summary/src/progress.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4811 feat: expose hit-miss metrics for querier caches
  cache_system/src/cache/metrics.rs
  cache_system/src/cache/mod.rs
  cache_system/src/cache/test_util.rs
  querier/src/cache/namespace.rs
  querier/src/cache/parquet_file.rs
  querier/src/cache/partition.rs
  querier/src/cache/processed_tombstones.rs
  querier/src/cache/read_buffer.rs
  querier/src/cache/table.rs
  querier/src/cache/tombstones.rs
Labels: automerge

#4814 feat: add LRU cache eviction counter
  cache_system/src/backend/lru.rs
Labels: automerge

#4825 docs: fix README for influxdb_iox_client
  influxdb_iox_client/README.md
  influxdb_iox_client/src/client/write.rs
Labels: automerge

#4823 refactor: Move `scan_and_filter` into a `common` module for reuse
  ingester/src/querier_handler.rs
  iox_query/src/frontend.rs
  iox_query/src/frontend/common.rs
  iox_query/src/frontend/influxrpc.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4826 chore: Incrementally migrate sort_key to array type
  iox_catalog/migrations/20220610102325_add_sort_key_array_column.sql
Labels: automerge

#4782 test: account for active writes when reporting readable status
  ingester/src/data.rs
  ingester/src/data/triggers.rs
  ingester/src/data/triggers/prod.rs
  ingester/src/data/triggers/test.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4801 feat: Change data type of catalog partition's sort_key from a string to an array of string
  data_types/src/lib.rs
  generated_types/protos/influxdata/iox/catalog/v1/service.proto
  ingester/src/compact.rs
  ingester/src/data.rs
  iox_catalog/migrations/20220610131325_rename_sort_key_arr.sql
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_query/src/provider.rs
  iox_tests/src/util.rs
  querier/src/cache/partition.rs
  schema/src/sort.rs
  service_grpc_catalog/src/lib.rs
Labels: automerge

#4831 chore: Revert "feat: compact all overlapped files no matter how large they are (#4779)"
  compactor/src/compact.rs
Labels: automerge

#4822 refactor: Switch ReorgPlanner to use `scan_and_filter`
  influxdb_iox/src/commands/query_ingester.rs
  ingester/src/querier_handler.rs
  iox_query/src/frontend/reorg.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4832 refactor: Consolidate `Selection` creation, add tests
  querier/src/chunk/query_access.rs
  querier/src/ingester/mod.rs
  schema/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4836 feat: expose query semaphore metrics
  Cargo.lock
  querier/Cargo.toml
  querier/src/database.rs
  service_common/Cargo.toml
  service_common/src/lib.rs
  service_common/src/test_util.rs
  service_grpc_flight/Cargo.toml
  service_grpc_flight/src/lib.rs
  service_grpc_influxrpc/Cargo.toml
  service_grpc_influxrpc/src/service.rs
Labels: automerge

#4813 feat: measure "seen" cache loads
  Cargo.lock
  cache_system/Cargo.toml
  cache_system/src/loader/metrics.rs
  querier/src/cache/read_buffer.rs
  workspace-hack/Cargo.toml
Labels: automerge

#4841 fix: Use debug rather than dbg in test helpers
  Cargo.lock
  iox_tests/Cargo.toml
  iox_tests/src/util.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4842 chore: Update datafusion
  Cargo.lock
  datafusion/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#4852 refactor: PartitionKey type
  compactor/src/compact.rs
  compactor/src/garbage_collector.rs
  data_types/src/lib.rs
  influxdb_iox/src/commands/remote/partition.rs
  ingester/src/compact.rs
  ingester/src/data.rs
  ingester/src/handler.rs
  ingester/src/partioning.rs
  ingester/src/test_util.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_tests/src/util.rs
  parquet_file/src/metadata.rs
  querier/src/cache/parquet_file.rs
  query_tests/src/scenarios/util.rs
  service_grpc_catalog/src/lib.rs
  service_grpc_object_store/src/lib.rs
Labels: kodiak: merge.method = 'merge'

#4837 refactor: consolidate plan creation from `QueryChunk`s in `iox_query`
  ingester/src/querier_handler.rs
  iox_query/src/frontend.rs
  iox_query/src/frontend/common.rs
  iox_query/src/frontend/influxrpc.rs
  iox_query/src/frontend/reorg.rs
  iox_query/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4854 feat: extend duration histograms down to 1ms
  metric/src/duration.rs
Labels: automerge

#4855 refactor: remove one buffer copy in the ingester
  ingester/src/querier_handler.rs
  ingester/src/query.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4830 fix: reduce memory usage in ingester with less buffering prior to query engine
  arrow_util/src/util.rs
  ingester/src/querier_handler.rs
  ingester/src/query.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4858 fix: Fix `build_release`
  iox_data_generator/Cargo.toml
Labels: automerge

#4859 chore: Add debug info of sort_key for ingester
  Cargo.lock
  ingester/src/data.rs
  iox_catalog/src/postgres.rs
  schema/Cargo.toml
  schema/src/sort.rs
Labels: automerge

#4839 refactor: Remove some `Option` in `iox_query`
  iox_query/src/frontend/influxrpc.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4857 chore: Update CI checks to verify data generator build
  .circleci/config.yml
Labels: automerge

#4862 refactor: remove some `&` use in iox_catalog
  compactor/src/compact.rs
  compactor/src/garbage_collector.rs
  data_types/src/lib.rs
  influxdb_iox/src/commands/remote/partition.rs
  ingester/src/data.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_tests/src/util.rs
  service_grpc_catalog/src/lib.rs
  service_grpc_object_store/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4853 feat: extend flight client to accept multiple (changing) schemas
  influxdb_iox/src/commands/query_ingester.rs
  influxdb_iox/tests/end_to_end_cases/ingester.rs
  influxdb_iox_client/src/client/flight.rs
  influxdb_iox_client/src/client/flight/low_level.rs
  influxdb_iox_client/src/client/flight/mod.rs
  querier/src/ingester/flight_client.rs
Labels: automerge

#4863 refactor: prepare new ingester<>querier protocol on the querier side
  generated_types/protos/influxdata/iox/ingester/v1/query.proto
  ingester/src/server/grpc.rs
  querier/src/ingester/flight_client.rs
  querier/src/ingester/mod.rs
  query_tests/src/scenarios/util.rs
Labels: automerge

#4864 refactor: add partition key to DmlWrite
  data_types/src/lib.rs
  dml/src/lib.rs
  influxdb_iox_client/src/client/write.rs
  ingester/src/data.rs
  ingester/src/handler.rs
  ingester/src/stream_handler/handler.rs
  ingester/src/stream_handler/sink_instrumentation.rs
  ioxd_common/src/http/dml.rs
  mutable_batch/src/payload.rs
  mutable_batch/src/payload/partition.rs
  mutable_batch_pb/tests/encode.rs
  mutable_batch_tests/benches/write_pb.rs
  query_tests/src/scenarios/util.rs
  router/src/dml_handlers/partitioner.rs
  router/src/dml_handlers/sharded_write_buffer.rs
  write_buffer/src/codec.rs
  write_buffer/src/core.rs
  write_buffer/src/file.rs
  write_buffer/src/kafka/aggregator.rs
  write_buffer/src/kafka/mod.rs
  write_buffer/src/mock.rs
Labels: kodiak: merge.method = 'merge'

#4835 feat: Make a sharder available in the querier
  Cargo.lock
  Cargo.toml
  clap_blocks/src/querier.rs
  clap_blocks/src/write_buffer.rs
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/src/commands/run/querier.rs
  influxdb_iox/tests/end_to_end_cases/logging.rs
  iox_tests/Cargo.toml
  iox_tests/src/util.rs
  ioxd_querier/Cargo.toml
  ioxd_querier/src/lib.rs
  ioxd_querier/src/rpc/namespace.rs
  ioxd_router/Cargo.toml
  ioxd_router/src/lib.rs
  querier/Cargo.toml
  querier/src/database.rs
  querier/src/handler.rs
  querier/src/lib.rs
  router/Cargo.toml
  router/benches/e2e.rs
  router/benches/schema_validator.rs
  router/src/dml_handlers/sharded_write_buffer.rs
  router/src/lib.rs
  router/src/namespace_cache/sharded_cache.rs
  router/src/sharder/mod.rs
  router/tests/http.rs
  sharder/Cargo.toml
  sharder/benches/sharder.rs
  sharder/src/jumphash.rs
  sharder/src/lib.rs
  sharder/src/mock.rs
  sharder/src/trait.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4868 feat(ingester): log when partitions are written due to going over size
  ingester/src/lifecycle.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4867 refactor: use new ingester<>querier wire protocol
  Cargo.lock
  docs/README.md
  docs/ingester_querier_protocol.md
  generated_types/protos/influxdata/iox/ingester/v1/query.proto
  influxdb_iox/tests/end_to_end_cases/ingester.rs
  influxdb_iox_client/src/client/flight/low_level.rs
  ingester/Cargo.toml
  ingester/src/data.rs
  ingester/src/querier_handler.rs
  ingester/src/server/grpc.rs
  querier/src/ingester/flight_client.rs
  querier/src/ingester/mod.rs
  query_tests/src/scenarios/util.rs
Labels: automerge

#4876 feat: instrument semaphore "cancelled while pending" requests
  tracker/src/async_semaphore.rs
Labels: automerge

#4874 fix(ingester): Distinguish between "not found" and other flight errors
  ingester/src/handler.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4870 fix(ingester): make ingester metrics start with `ingester`
  ingester/src/stream_handler/handler.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4875 refactor: stream query results from ingester to querier
  ingester/src/handler.rs
  ingester/src/querier_handler.rs
  query_tests/src/scenarios/util.rs
Labels: automerge

#4878 fix: respect partition key when batching dml ops
  write_buffer/src/core.rs
  write_buffer/src/file.rs
  write_buffer/src/kafka/aggregator.rs
  write_buffer/src/kafka/mod.rs
Labels: kodiak: merge.method = 'merge'

#4879 refactor: make querier->ingester request metrics per-ingester
  querier/src/cache/mod.rs
  querier/src/ingester/mod.rs
  querier/src/table/mod.rs
Labels: automerge

#4881 chore: more info for i64-to-u128 panic message
  compactor/src/query.rs
Labels: automerge

#4884 chore: debug info about sequence number while it gets converted into ChunkOrder
  compactor/src/query.rs
Labels: automerge

#4894 chore(deps): Bump sqlx to 0.6.0 and uuid to 1
  Cargo.lock
  clap_blocks/Cargo.toml
  compactor/Cargo.toml
  data_types/Cargo.toml
  data_types/src/lib.rs
  influxdb2_client/Cargo.toml
  influxdb_iox/Cargo.toml
  ingester/Cargo.toml
  iox_catalog/Cargo.toml
  iox_catalog/src/postgres.rs
  iox_data_generator/Cargo.toml
  iox_data_generator/src/substitution.rs
  iox_tests/Cargo.toml
  parquet_file/Cargo.toml
  querier/Cargo.toml
  service_grpc_catalog/Cargo.toml
  service_grpc_object_store/Cargo.toml
  sqlx-hotswap-pool/Cargo.toml
  sqlx-hotswap-pool/src/lib.rs
  test_helpers_end_to_end/Cargo.toml
  workspace-hack/Cargo.toml
  write_buffer/Cargo.toml
Labels: automerge

#4898 test: assert backfill partitioning in router
  router/src/dml_handlers/partitioner.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4899 fix: categorize `NamespaceNotFound` as ingester not found errors for metrics
  ingester/src/handler.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4906 chore: reduce dependencies and run `cargo update`
  .guppy/hakari.toml
  Cargo.lock
  Cargo.toml
  grpc-router-test-gen/Cargo.toml
  grpc-router-test-gen/build.rs
  grpc-router-test-gen/protos/test.proto
  grpc-router-test-gen/src/lib.rs
  grpc-router/Cargo.toml
  grpc-router/src/connection_manager.rs
  grpc-router/src/lib.rs
  grpc-router/src/router.rs
  read_buffer/Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge

#4908 refactor: store per-file column set in catalog
  compactor/src/compact.rs
  compactor/src/garbage_collector.rs
  data_types/src/lib.rs
  generated_types/protos/influxdata/iox/catalog/v1/parquet_file.proto
  influxdb_iox/src/commands/remote/partition.rs
  ingester/src/data.rs
  iox_catalog/migrations/20220620160136_parquet_file_columns.sql
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
  iox_tests/src/util.rs
  parquet_file/src/metadata.rs
  querier/src/cache/parquet_file.rs
  service_grpc_catalog/src/lib.rs
  service_grpc_object_store/src/lib.rs
Labels: automerge

#4909 refactor: pass path instead of metadata around to load parquet files
  parquet_file/src/chunk.rs
  parquet_file/src/storage.rs
  querier/src/cache/read_buffer.rs
Labels: automerge

#4910 refactor: remove table name from read buffer
  querier/src/cache/read_buffer.rs
  querier/src/chunk/mod.rs
  read_buffer/benches/database.rs
  read_buffer/benches/read_filter.rs
  read_buffer/src/chunk.rs
  read_buffer/src/lib.rs
  read_buffer/src/table.rs
Labels: automerge

#4917 fix: fix heappy + update docs
  Cargo.lock
  docs/images/heappy_graph.png
  docs/profiling.md
  influxdb_iox/Cargo.toml
  influxdb_iox/tests/end_to_end_cases/mod.rs
  ioxd_common/Cargo.toml
Labels: automerge

#4923 fix: pass write buffer tests w/o Kafka
  write_buffer/src/core.rs
  write_buffer/src/kafka/mod.rs
Labels: automerge

#4922 refactor: make querier internals private
  Cargo.lock
  compactor/Cargo.toml
  compactor/src/compact.rs
  querier/src/cache/namespace.rs
  querier/src/cache/parquet_file.rs
  querier/src/cache/table.rs
  querier/src/cache/tombstones.rs
  querier/src/chunk/mod.rs
  querier/src/lib.rs
Labels: automerge

#4925 fix: `ParquetFile::size` must include column set
  data_types/src/lib.rs
  querier/src/cache/parquet_file.rs
Labels: automerge

#4924 feat: do not rely on encoded parquet metadata for RB chunks
  iox_tests/src/util.rs
  querier/src/cache/namespace.rs
  querier/src/cache/partition.rs
  querier/src/chunk/mod.rs
  querier/src/database.rs
  querier/src/ingester/mod.rs
  querier/src/table/mod.rs
  querier/src/table/state_reconciler.rs
Labels: automerge

#4926 refactor: do not fetch parquet MD from catalog in querier
  querier/src/cache/parquet_file.rs
  querier/src/table/state_reconciler.rs
  querier/src/table/state_reconciler/interface.rs
Labels: automerge

#4916 docs: Update tracing.md for NG
  docs/tracing.md
Labels: automerge, kodiak: merge.method = 'squash'

#4927 chore: Update datafusion
  Cargo.lock
  datafusion/Cargo.toml
  iox_query/src/exec/context.rs
  iox_query/src/exec/non_null_checker.rs
  iox_query/src/exec/schema_pivot.rs
  iox_query/src/exec/split.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4929 refactor: Make some structures in `LifecycleManager` non pub
  ingester/src/lifecycle.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4933 refactor: remove unused errors
  ingester/src/data.rs
  ingester/src/stream_handler/sink_instrumentation.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4934 refactor: slim down parquet chunk (remove Metadata)
  Cargo.lock
  compactor/src/utils.rs
  parquet_file/Cargo.toml
  parquet_file/src/chunk.rs
  parquet_file/src/lib.rs
  querier/src/cache/read_buffer.rs
  querier/src/chunk/mod.rs
  querier/src/chunk/query_access.rs
Labels: automerge

#4941 fix: account for partition memory until persist is completed
  ingester/src/lifecycle.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4918 feat: Compact now can split compacted results into multiple non-overlapped files based on config max file size
  compactor/src/compact.rs
  compactor/src/handler.rs
  iox_query/src/exec.rs
  iox_query/src/exec/context.rs
  iox_query/src/exec/split.rs
  iox_query/src/frontend.rs
  iox_query/src/frontend/reorg.rs
  iox_tests/src/util.rs
Labels: automerge

#4937 refactor: ensure that SQL parquet file column sets are not NULL
  iox_catalog/migrations/20220623143430_non_null_parquet_file_columns.sql
Labels: automerge

#4944 chore: remove unused sort_key_old from catalog partition
  iox_catalog/migrations/20220624104030_remove_column_sort_key_old.sql
Labels: automerge

#4935 refactor: do not use in-parquet IOx metadata in compactor (*)
  compactor/src/compact.rs
  compactor/src/handler.rs
  compactor/src/utils.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
  querier/src/cache/namespace.rs
Labels: automerge

#4938 refactor: remove binary parquet file MD from compactor
  compactor/src/compact.rs
  compactor/src/handler.rs
  compactor/src/utils.rs
  iox_query/src/provider/overlap.rs
  querier/src/chunk/mod.rs
Labels: automerge

#4950 fix: size estimates
  data_types/src/lib.rs
  querier/src/cache/partition.rs
  querier/src/cache/tombstones.rs
Labels: automerge

#4946 docs: Readability improvements
  docs/ingester_querier_protocol.md
  docs/profiling.md
  influxdb_iox_client/README.md
Labels: automerge, kodiak: merge.method = 'squash'

#4953 ci: fix image deploy
  .circleci/config.yml
Labels: automerge

#4952 refactor: fetch RB chunks in parallel
  querier/src/table/state_reconciler.rs
Labels: automerge

#4955 chore: readability improvements
  arrow_util/src/bitset.rs
  arrow_util/src/dictionary.rs
  arrow_util/src/test_util.rs
  arrow_util/src/util.rs
  cache_system/src/backend/addressable_heap.rs
  cache_system/src/backend/lru.rs
  cache_system/src/backend/mod.rs
  tracker/src/async_semaphore.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4964 fix: parquet reader sort order
  parquet_file/src/storage.rs
Labels: automerge

#4961 ci: fix `docker load` paths
  .circleci/config.yml
Labels: automerge

#4977 ci: IOx still needs to push its image tags
  .circleci/config.yml
Labels: automerge

#4969 chore: Update datafusion pin
  Cargo.lock
  datafusion/Cargo.toml
  iox_query/src/exec/context.rs
  querier/src/namespace/query_access.rs
  querier/src/system_tables/mod.rs
  query_tests/cases/in/duplicates.expected
  query_tests/cases/in/pushdown.expected
  query_tests/cases/in/several_chunks.expected
  query_tests/cases/in/two_chunks.expected
  query_tests/src/influxrpc/read_filter.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4707 chore: update object_store to 0.3.0
  Cargo.lock
  clap_blocks/Cargo.toml
  clap_blocks/src/object_store.rs
  compactor/Cargo.toml
  influxdb_iox/Cargo.toml
  ingester/Cargo.toml
  iox_tests/Cargo.toml
  ioxd_compactor/Cargo.toml
  ioxd_ingester/Cargo.toml
  ioxd_querier/Cargo.toml
  ioxd_router/Cargo.toml
  object_store_metrics/Cargo.toml
  object_store_metrics/src/dummy.rs
  object_store_metrics/src/lib.rs
  parquet_file/Cargo.toml
  parquet_file/src/storage.rs
  querier/Cargo.toml
  router/Cargo.toml
  service_grpc_object_store/Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge

#4993 fix: Fix typo in const name
  clap_blocks/src/catalog_dsn.rs
  iox_catalog/src/postgres.rs
Labels: automerge

#4980 fix: ensure panic is propagated through `AdapterStream`
  Cargo.lock
  datafusion_util/Cargo.toml
  datafusion_util/src/lib.rs
  datafusion_util/src/sender.rs
  datafusion_util/src/watch.rs
  iox_query/src/exec/non_null_checker.rs
  iox_query/src/exec/schema_pivot.rs
  iox_query/src/exec/split.rs
  iox_query/src/provider/deduplicate.rs
  parquet_file/src/storage.rs
Labels: automerge

#4887 feat: Only query the ingesters relevant to the table
  Cargo.lock
  clap_blocks/Cargo.toml
  clap_blocks/src/querier.rs
  data_types/src/lib.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/tests/end_to_end_cases/querier/multi_ingester.rs
  ioxd_querier/src/lib.rs
  ioxd_querier/src/rpc/namespace.rs
  ioxd_querier/src/rpc/write_info.rs
  querier/src/database.rs
  querier/src/handler.rs
  querier/src/ingester/mod.rs
  querier/src/ingester/test_util.rs
  querier/src/lib.rs
  querier/src/namespace/mod.rs
  querier/src/namespace/test_util.rs
  querier/src/table/mod.rs
  querier/src/table/test_util.rs
  query_tests/Cargo.toml
  query_tests/src/scenarios/util.rs
  sharder/src/jumphash.rs
  test_helpers_end_to_end/src/config.rs
  test_helpers_end_to_end/src/mini_cluster.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4982 test: document how to run tests
  CONTRIBUTING.md
  clap_blocks/src/object_store.rs
  docs/testing.md
  influxdb_iox/tests/end_to_end_cases/cli.rs
  integration-docker-compose.yml
Labels: automerge

#4965 refactor: use IDs for `parquet_file.column_set`
  compactor/src/compact.rs
  compactor/src/garbage_collector.rs
  compactor/src/utils.rs
  data_types/src/lib.rs
  generated_types/protos/influxdata/iox/catalog/v1/parquet_file.proto
  influxdb_iox/src/commands/remote/partition.rs
  ingester/src/data.rs
  iox_catalog/migrations/20220628085556_column_set_via_IDs.sql
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_tests/src/util.rs
  parquet_file/src/metadata.rs
  parquet_file/tests/metadata.rs
  querier/src/cache/namespace.rs
  querier/src/cache/parquet_file.rs
  querier/src/cache/processed_tombstones.rs
  querier/src/chunk/mod.rs
  service_grpc_catalog/src/lib.rs
  service_grpc_object_store/src/lib.rs
Labels: automerge, incompatible protobuf

#4994 fix: docs+assertions for `TimestampRange`
  data_types/src/lib.rs
Labels: automerge

#5004 refactor: `ChunkOrder::new` cannot fail
  compactor/src/query.rs
  data_types/src/lib.rs
  querier/src/chunk/mod.rs
  querier/src/ingester/mod.rs
Labels: automerge

#5012 chore: remove perf.py
  .circleci/config.yml
  perf/.gitignore
  perf/README.md
  perf/battery-0/datagen.toml
  perf/battery-0/foo.csv
  perf/battery-0/queries.toml
  perf/perf.py
  perf/requirements.txt
Labels: automerge, kodiak: merge.method = 'squash'
