Repository influxdata/influxdb_iox, pull requests merged in 2022-03, with the labels that each got.

#3876 feat: offer metrics for in-mem catalog
  influxdb_iox/src/clap_blocks/catalog_dsn.rs
  influxdb_iox/src/commands/catalog.rs
  influxdb_iox/src/commands/catalog/topic.rs
  influxdb_iox/src/commands/run/compactor.rs
  influxdb_iox/src/commands/run/ingester.rs
  influxdb_iox/src/commands/run/querier.rs
  influxdb_iox/src/commands/run/router2.rs
  ingester/src/data.rs
  ingester/src/handler.rs
  ingester/src/test_util.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
  querier/src/chunk.rs
  querier/src/database.rs
  router2/benches/e2e.rs
  router2/src/dml_handlers/ns_autocreation.rs
  router2/src/dml_handlers/schema_validation.rs
  router2/tests/http.rs
Labels: automerge

#3883 chore: reset release codegen-units to default
  Cargo.toml
Labels: automerge

#3882 refactor: generic top-level flight implementation
  influxdb_iox/src/influxdb_ioxd/rpc.rs
  influxdb_iox/src/influxdb_ioxd/rpc/flight.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/flight.rs
Labels: automerge

#3885 fix: Use bigger executor for test job
  .circleci/config.yml
Labels: automerge

#3835 feat: `DedicatedExecutor` async `join` and job `detach`.
  executor/src/lib.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/mod.rs
  ingester/src/data.rs
  ingester/src/handler.rs
  ingester/src/querier_handler.rs
  query/src/exec.rs
  query/src/frontend.rs
  query/src/frontend/influxrpc.rs
  query/src/frontend/reorg.rs
  query/src/plan/stringset.rs
  server/src/application.rs
Labels: automerge

#3886 fix: check arrow instead of storage gRPC health for SQL REPL
  influxdb_iox/src/commands/sql.rs
Labels: automerge

#3879 feat: split release build and deploy
  .circleci/config.yml
Labels: automerge

#3887 feat: additional write buffer logging (#3805)
  Cargo.lock
  write_buffer/Cargo.toml
  write_buffer/src/kafka/aggregator.rs
Labels: automerge

#3890 fix: remove rskafka from valid options for INFLUXDB_IOX_WRITE_BUFFER_TYPE
  influxdb_iox/src/clap_blocks/write_buffer.rs
Labels: automerge

#3880 refactor: clean up `querier` a bit
  querier/src/cache.rs
  querier/src/chunk.rs
  querier/src/database.rs
  querier/src/lib.rs
  querier/src/namespace.rs
  querier/src/test_util.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3881 test: querier shutdown and background task handling
  Cargo.lock
  querier/Cargo.toml
  querier/src/database.rs
  querier/src/handler.rs
  querier/src/lib.rs
  querier/src/poison.rs
Labels: automerge

#3889 feat: wire up flight into the querier
  Cargo.lock
  db/src/access.rs
  influxdb_iox/src/commands/run/querier.rs
  influxdb_iox/src/influxdb_ioxd/server_type/querier/mod.rs
  influxdb_iox/src/influxdb_ioxd/server_type/querier/rpc/flight.rs
  influxdb_iox/src/influxdb_ioxd/server_type/querier/rpc/mod.rs
  querier/Cargo.toml
  querier/src/database.rs
  querier/src/handler.rs
  querier/src/lib.rs
  querier/src/namespace.rs
  querier/src/test_util.rs
Labels: automerge

#3896 feat: update to latest rskafka logging (#3805)
  Cargo.lock
  write_buffer/Cargo.toml
Labels: automerge

#3898 feat: http ingest metrics
  influxdb_iox/src/commands/run/router2.rs
  router2/benches/e2e.rs
  router2/src/server/http.rs
  router2/tests/http.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3894 fix: make catalog db migration idempotent again
  iox_catalog/README.md
  iox_catalog/src/interface.rs
  iox_catalog/src/postgres.rs
Labels: automerge

#3804 feat: add tracing down to the chunk level
  db/src/access.rs
  db/src/chunk.rs
  db/src/lib.rs
  db/src/lifecycle/write.rs
  db/src/streams.rs
  influxdb_iox/src/influxdb_ioxd/planner.rs
  ingester/src/query.rs
  querier/src/chunk.rs
  query/src/exec/context.rs
  query/src/frontend/influxrpc.rs
  query/src/frontend/reorg.rs
  query/src/lib.rs
  query/src/provider.rs
  query/src/provider/physical.rs
  query/src/test.rs
  query_tests/src/influxrpc/field_columns.rs
  query_tests/src/influxrpc/read_filter.rs
  query_tests/src/influxrpc/read_group.rs
  query_tests/src/influxrpc/read_window_aggregate.rs
  query_tests/src/influxrpc/table_names.rs
  query_tests/src/influxrpc/tag_keys.rs
  query_tests/src/influxrpc/tag_values.rs
  query_tests/src/pruning.rs
  schema/src/selection.rs
  server_benchmarks/benches/read_filter.rs
  server_benchmarks/benches/read_group.rs
  server_benchmarks/benches/tag_values.rs
  trace/src/span.rs
Labels: automerge

#3900 feat: sync partitions in querier
  db/src/catalog.rs
  querier/src/namespace.rs
Labels: automerge

#3910 feat: update rskafka (#3805)
  Cargo.lock
  write_buffer/Cargo.toml
  write_buffer/src/core.rs
  write_buffer/src/file.rs
  write_buffer/src/kafka/mod.rs
  write_buffer/src/mock.rs
Labels: automerge

#3906 refactor: address PR feedback
  db/src/access.rs
  db/src/lifecycle/write.rs
  query/src/frontend/influxrpc.rs
  query/src/frontend/reorg.rs
  query/src/provider.rs
Labels: automerge

#3874 feat: allow persisting all partitions and/or all tables from CLI
  influxdb_iox/src/commands/database/partition.rs
  influxdb_iox/tests/end_to_end_cases/management_cli.rs
  influxdb_iox/tests/end_to_end_cases/scenario.rs
Labels: automerge

#3897 feat: batch column upsert
  Cargo.lock
  ingester/src/data.rs
  ingester/src/handler.rs
  iox_catalog/Cargo.toml
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  router2/src/dml_handlers/schema_validation.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3902 fix: jemalloc feature flag
  influxdb_iox/Cargo.toml
  influxdb_iox/src/influxdb_ioxd.rs
  influxdb_iox/tests/end_to_end_cases/metrics.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3901 feat: rustls as TLS backend
  .guppy/hakari.toml
  Cargo.lock
  README.md
  data_types2/Cargo.toml
  influxdb2_client/Cargo.toml
  influxdb_iox/Cargo.toml
  iox_catalog/Cargo.toml
  iox_gitops_adapter/Cargo.toml
  object_store/Cargo.toml
  object_store/src/aws.rs
  object_store/src/azure.rs
  sqlx-hotswap-pool/Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'merge'

#3913 feat: add tracing to all remaining influx RPC calls
  db/src/chunk.rs
  db/src/streams.rs
  influxdb_iox/src/influxdb_ioxd/planner.rs
  ingester/src/query.rs
  query/src/frontend/influxrpc.rs
  query/src/lib.rs
  query/src/test.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3903 fix: apply `_field` restrictions that do not match any fields
  db/src/access.rs
  query_tests/src/influxrpc/tag_values.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3915 feat: make wait-server-initialized wait for database init
  influxdb_iox/src/commands/server.rs
  influxdb_iox/tests/end_to_end_cases/management_cli.rs
Labels: automerge

#3916 feat: allow unencrypted HTTP connections to AWS via flag
  clap_blocks/src/object_store.rs
  object_store/src/aws.rs
  object_store/src/dummy.rs
  object_store/src/lib.rs
Labels: automerge

#3923 feat: include trace ID in query log (#3912)
  db/src/access.rs
  db/src/lib.rs
  db/src/query_log.rs
  db/src/system_tables/queries.rs
  influxdb_iox/tests/end_to_end_cases/system_tables.rs
  influxdb_ioxd/src/rpc/flight.rs
  influxdb_ioxd/src/server_type/database/http.rs
  influxdb_ioxd/src/server_type/database/rpc/storage/service.rs
  querier/src/namespace.rs
  query/src/exec/context.rs
  query/src/lib.rs
  query/src/test.rs
Labels: automerge

#3892 refactor: Clean up some future clippy warnings from nightly
  influxdb2_client/src/api/label.rs
  influxdb2_client/src/api/write.rs
  influxdb_iox_client/src/client/operations.rs
  iox_catalog/src/lib.rs
  lifecycle/src/policy.rs
  mutable_batch/src/payload/filter.rs
  mutable_batch/tests/writer_fuzz.rs
  parquet_catalog/src/core.rs
  parquet_file/src/test_utils.rs
  server/src/lib.rs
  sqlx-hotswap-pool/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3868 feat: update max_persisted_sequence_number in table on persist
  data_types2/src/lib.rs
  ingester/src/data.rs
  ingester/src/handler.rs
  ingester/src/querier_handler.rs
  ingester/src/test_util.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
Labels: automerge

#3911 feat: sync chunks in querier
  Cargo.lock
  data_types/src/chunk_metadata.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  querier/Cargo.toml
  querier/src/chunk.rs
  querier/src/namespace.rs
  querier/src/test_util.rs
Labels: automerge

#3927 feat: more router metrics
  influxdb_iox/src/commands/run/router2.rs
  router2/Cargo.toml
  router2/benches/e2e.rs
  router2/benches/schema_validator.rs
  router2/src/dml_handlers/sharded_write_buffer.rs
  router2/src/namespace_cache/metrics.rs
  router2/src/sequencer.rs
  router2/src/server/http.rs
  router2/tests/http.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3930 fix: fix read-window-aggregate CLI defaults
  influxdb_iox/src/commands/storage.rs
Labels: automerge

#3925 feat: Send parquet and tombstone seq nums with ingester query response
  generated_types/protos/influxdata/iox/ingester/v1/query.proto
  ingester/src/data.rs
  ingester/src/querier_handler.rs
  ingester/src/server/grpc.rs
  querier/src/flight.rs
Labels: automerge

#3924 feat: Auto commit cargo hakari generate changes
  .circleci/config.yml
Labels: automerge, kodiak: merge.method = 'merge'

#3929 chore: remove uneeded dependencies
  Cargo.lock
  compactor/Cargo.toml
  influxdb_ioxd/Cargo.toml
  object_store/Cargo.toml
  server/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#3943 chore: Update datafusion
  Cargo.lock
  datafusion/Cargo.toml
  parquet_file/src/storage.rs
  predicate/src/rewrite.rs
  query/src/func/selectors.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#3937 test: Add tests to verify deduplicating is working with timestamps and string columns
  query/src/provider/deduplicate.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3939 fix: correctly set nulls in string columns
  arrow_util/src/dictionary.rs
  arrow_util/src/string.rs
  mutable_batch/src/column.rs
  mutable_batch_lp/src/lib.rs
  query_tests/src/influxrpc/field_columns.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3936 feat: router grpc write handler
  Cargo.lock
  influxdb_iox/src/commands/run/router2.rs
  router2/Cargo.toml
  router2/benches/e2e.rs
  router2/src/dml_handlers/mock.rs
  router2/src/dml_handlers/trait.rs
  router2/src/server.rs
  router2/src/server/grpc.rs
  router2/src/server/http.rs
  router2/tests/http.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3960 chore: reduce router log verbosity (#3805)
  write_buffer/src/kafka/aggregator.rs
Labels: automerge

#3931 feat: improve trace naming
  influxdb_ioxd/src/server_type/database/mod.rs
  query/src/exec/query_tracing.rs
  trace/src/span.rs
Labels: automerge

#3928 feat: add a flag to enable per-partition tracing
  clap_blocks/src/lib.rs
  data_types/src/boolean_flag.rs
  data_types/src/lib.rs
  docs/tracing.md
  influxdb_iox/src/commands/run/database.rs
  query/src/exec/query_tracing.rs
Labels: automerge

#3961 build: remove openssl dependency
  Cargo.lock
  influxdb_ioxd/Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'merge'

#3959 feat: generic InfluxRPC impl, used by querier
  influxdb_ioxd/src/rpc.rs
  influxdb_ioxd/src/rpc/common.rs
  influxdb_ioxd/src/rpc/flight.rs
  influxdb_ioxd/src/rpc/storage/data.rs
  influxdb_ioxd/src/rpc/storage/expr.rs
  influxdb_ioxd/src/rpc/storage/id.rs
  influxdb_ioxd/src/rpc/storage/input.rs
  influxdb_ioxd/src/rpc/storage/mod.rs
  influxdb_ioxd/src/rpc/storage/service.rs
  influxdb_ioxd/src/server_type/database/rpc/flight.rs
  influxdb_ioxd/src/server_type/database/rpc/mod.rs
  influxdb_ioxd/src/server_type/database/rpc/query.rs
  influxdb_ioxd/src/server_type/querier/mod.rs
  influxdb_ioxd/src/server_type/querier/rpc/flight.rs
  influxdb_ioxd/src/server_type/querier/rpc/mod.rs
  influxdb_ioxd/src/server_type/querier/rpc/query.rs
  server/src/lib.rs
Labels: automerge

#3964 build: propagate feature flags to influxdb_ioxd
  influxdb_iox/Cargo.toml
  influxdb_ioxd/Cargo.toml
Labels: automerge, kodiak: merge.method = 'merge'

#3966 feat: add distinct count to chunk summary table
  db/src/system_tables/columns.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3942 feat: ingester persists on cold partitions
  influxdb_iox/src/commands/run/ingester.rs
  ingester/src/data.rs
  ingester/src/handler.rs
  ingester/src/lifecycle.rs
Labels: automerge

#3970 refactor: remove unused error enums
  influxdb_iox/src/commands/catalog.rs
  influxdb_iox/src/commands/catalog/topic.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3962 feat: wire up tombstones into querier
  db/src/catalog/chunk.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  querier/src/cache.rs
  querier/src/chunk.rs
  querier/src/namespace.rs
  querier/src/test_util.rs
Labels: automerge

#3975 refactor: split `querier::namespace` into submodules
  querier/src/namespace/mod.rs
  querier/src/namespace/query_access.rs
  querier/src/namespace/test_util.rs
Labels: automerge

#3976 refactor: remove `QueryDatabase::partition_addr`
  db/src/access.rs
  db/src/lib.rs
  db/src/lifecycle/compact.rs
  db/src/lifecycle/persist.rs
  querier/src/namespace/query_access.rs
  query/src/lib.rs
  query/src/test.rs
Labels: automerge

#3977 refactor: remove `QueryDatabase::chunk_summaries`
  db/src/access.rs
  db/src/lib.rs
  db/src/lifecycle/load.rs
  influxdb_ioxd/src/server_type/database/rpc/management.rs
  querier/src/namespace/query_access.rs
  query/src/lib.rs
  query/src/test.rs
  query_tests/src/scenarios/util.rs
  server/src/lib.rs
  server/tests/write_buffer_lifecycle.rs
Labels: automerge

#3978 perf: get_table_persist_info indexes for joins
  iox_catalog/migrations/20220308120917_ingester-missing-indexes.sql
Labels: automerge, kodiak: merge.method = 'merge'

#3969 refactor: decouple router2 setup and creation logic from the config structs, switch to `Arc<dyn ServerType>`
  influxdb_iox/src/commands/run/router2.rs
  influxdb_ioxd/src/http/mod.rs
  influxdb_ioxd/src/lib.rs
  influxdb_ioxd/src/rpc.rs
  influxdb_ioxd/src/server_type/compactor.rs
  influxdb_ioxd/src/server_type/database/mod.rs
  influxdb_ioxd/src/server_type/ingester.rs
  influxdb_ioxd/src/server_type/mod.rs
  influxdb_ioxd/src/server_type/querier/mod.rs
  influxdb_ioxd/src/server_type/router/mod.rs
  influxdb_ioxd/src/server_type/router2.rs
  influxdb_ioxd/src/server_type/test.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3982 refactor: impl Debug for ingester types
  ingester/src/data.rs
  ingester/src/handler.rs
  ingester/src/lib.rs
  ingester/src/lifecycle.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3973 feat: NG Compactor - main function for finding and compacting parquet files
  Cargo.lock
  compactor/Cargo.toml
  compactor/src/compact.rs
  compactor/src/handler.rs
  compactor/src/lib.rs
  influxdb_iox/src/commands/run/compactor.rs
Labels: automerge

#3940 feat: ingester seeks kafka partition on initialization
  ingester/src/handler.rs
Labels: automerge

#3987 refactor: move parquet chunk's new and decode to parquet_file crate
  parquet_file/src/chunk.rs
  querier/src/chunk.rs
Labels: automerge

#3986 refactor: Remove serving readiness gate
  Cargo.lock
  Cargo.toml
  clap_blocks/Cargo.toml
  clap_blocks/src/run_config.rs
  generated_types/protos/influxdata/iox/deployment/v1/service.proto
  influxdb_iox/tests/end_to_end_cases/deployment_api.rs
  influxdb_iox_client/src/client/deployment.rs
  influxdb_ioxd/Cargo.toml
  influxdb_ioxd/src/lib.rs
  influxdb_ioxd/src/rpc.rs
  influxdb_ioxd/src/server_type/common_state.rs
  influxdb_ioxd/src/server_type/database/mod.rs
  influxdb_ioxd/src/server_type/database/rpc/deployment.rs
  influxdb_ioxd/src/server_type/database/rpc/mod.rs
  influxdb_ioxd/src/server_type/ingester.rs
  influxdb_ioxd/src/server_type/router/mod.rs
  influxdb_ioxd/src/server_type/router/rpc/deployment.rs
  influxdb_ioxd/src/server_type/router/rpc/mod.rs
  serving_readiness/Cargo.toml
  serving_readiness/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3944 fix: Use more consistent env vars for database connections
  .circleci/config.yml
  iox_catalog/README.md
  iox_catalog/src/postgres.rs
  sqlx-hotswap-pool/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3993 fix: Remove data_types as a dependency of ng compactor
  Cargo.lock
  compactor/Cargo.toml
Labels: automerge

#3990 refactor: drop trace log verbosity
  trace_http/src/ctx.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3991 feat: querier test system, ground work
  querier/src/cache.rs
  querier/src/cache/mod.rs
  querier/src/cache/namespace.rs
  querier/src/cache/partition.rs
  querier/src/cache/table.rs
  querier/src/cache/test_util.rs
  querier/src/cache_system/driver.rs
  querier/src/cache_system/loader.rs
  querier/src/cache_system/mod.rs
  querier/src/chunk.rs
  querier/src/lib.rs
  querier/src/namespace/mod.rs
Labels: automerge

#3998 chore: Run dependabot more frequently
  .github/dependabot.yml
Labels: automerge, kodiak: merge.method = 'squash'

#4011 fix: allow manual merge messages in semantic commit checker
  .github/workflows/semantic_check.sh
Labels: automerge, kodiak: merge.method = 'squash'

#4000 chore: Update datafusion, arrow, flight and parquet
  Cargo.lock
  arrow_util/Cargo.toml
  datafusion/Cargo.toml
  db/Cargo.toml
  db/src/lib.rs
  influxdb_iox/Cargo.toml
  influxdb_iox_client/Cargo.toml
  influxdb_ioxd/Cargo.toml
  ingester/Cargo.toml
  mutable_batch/Cargo.toml
  mutable_buffer/Cargo.toml
  packers/Cargo.toml
  parquet_catalog/Cargo.toml
  parquet_catalog/src/dump.rs
  parquet_file/Cargo.toml
  parquet_file/src/metadata.rs
  predicate/Cargo.toml
  querier/Cargo.toml
  query/Cargo.toml
  query/src/pruning.rs
  query_tests/Cargo.toml
  read_buffer/Cargo.toml
  schema/Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#3972 feat: add compaction_level and created_at to parquet_file
  data_types2/src/lib.rs
  ingester/src/data.rs
  iox_catalog/migrations/20220307201050_add_parquet_level_and_created_at.sql
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  parquet_file/src/metadata.rs
  querier/src/test_util.rs
Labels: automerge

#4013 refactor: move querier's test utils to a new crate to get reused by tests in other crates
  Cargo.lock
  Cargo.toml
  influxdb_iox/Cargo.toml
  iox_tests/Cargo.toml
  iox_tests/src/lib.rs
  iox_tests/src/util.rs
  querier/Cargo.toml
  querier/src/cache/namespace.rs
  querier/src/cache/partition.rs
  querier/src/cache/table.rs
  querier/src/chunk.rs
  querier/src/database.rs
  querier/src/lib.rs
  querier/src/namespace/mod.rs
  querier/src/namespace/query_access.rs
  querier/src/namespace/test_util.rs
Labels: automerge

#4012 refactor: Extract a ParquetFileParams catalog type for use in ParquetFileRepo create
  data_types2/src/lib.rs
  ingester/src/data.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_tests/src/util.rs
  parquet_file/src/metadata.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3992 refactor(ingester): eliminate unnecessary lock
  ingester/src/data.rs
  ingester/src/handler.rs
  ingester/src/lifecycle.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4015 feat: extract "backend" from querier cache
  querier/src/cache/namespace.rs
  querier/src/cache/partition.rs
  querier/src/cache/table.rs
  querier/src/cache_system/backend/hash_map.rs
  querier/src/cache_system/backend/mod.rs
  querier/src/cache_system/backend/test_util.rs
  querier/src/cache_system/driver.rs
  querier/src/cache_system/mod.rs
Labels: automerge

#4017 refactor: extract out querier creation from config
  influxdb_iox/src/commands/run/querier.rs
  influxdb_ioxd/src/server_type/querier/mod.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4020 refactor: decouple ingester setup and creation logic from the config structs
  clap_blocks/src/ingester.rs
  clap_blocks/src/lib.rs
  influxdb_iox/src/commands/run/ingester.rs
  influxdb_ioxd/src/server_type/ingester.rs
  ingester/src/data.rs
  ingester/src/handler.rs
  ingester/src/test_util.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4001 feat: Implement the compact function for NG Compactor
  Cargo.lock
  compactor/Cargo.toml
  compactor/src/compact.rs
  compactor/src/handler.rs
  compactor/src/lib.rs
  compactor/src/query.rs
  compactor/src/utils.rs
  data_types2/src/lib.rs
  influxdb_iox/src/commands/run/compactor.rs
  influxdb_ioxd/src/server_type/compactor.rs
  ingester/src/compact.rs
  ingester/src/query.rs
  iox_tests/src/util.rs
  query/Cargo.toml
  query/src/util.rs
Labels: automerge

#4021 feat: Add catalog/compactor functions for getting level 0 and level 1 files; marking files as level 1
  compactor/src/compact.rs
  compactor/src/utils.rs
  data_types2/src/lib.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4016 feat: add addressable heap for query cache
  querier/src/cache_system/backend/addressable_heap.rs
  querier/src/cache_system/backend/mod.rs
Labels: automerge

#4025 test: add proptest for `AddressableHeap`
  Cargo.lock
  querier/Cargo.toml
  querier/src/cache_system/backend/addressable_heap.rs
Labels: automerge

#4028 fix: Remove partition_id from metric attributes
  ingester/src/job.rs
Labels: automerge

#4029 fix: Kick c2updater
  .circleci/get-deploy-tags.sh
Labels: automerge

#4027 refactor: add TTL cache backend
  querier/src/cache_system/backend/hash_map.rs
  querier/src/cache_system/backend/mod.rs
  querier/src/cache_system/backend/ttl.rs
Labels: automerge

#4022 chore: Update datafusion
  Cargo.lock
  datafusion/Cargo.toml
  generated_types/src/ingester.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4030 feat: cache processed tombstones
  iox_tests/src/util.rs
  querier/src/cache/mod.rs
  querier/src/cache/processed_tombstones.rs
  querier/src/chunk.rs
  querier/src/database.rs
  querier/src/namespace/mod.rs
  querier/src/namespace/test_util.rs
Labels: automerge

#4036 feat: `Cache::set`
  querier/src/cache_system/driver.rs
Labels: automerge

#4019 feat: object store instrumentation
  Cargo.lock
  object_store/Cargo.toml
  object_store/src/instrumentation.rs
  object_store/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4041 build: manually clone advisory-db repo
  .circleci/config.yml
Labels: automerge, kodiak: merge.method = 'merge'

#3965 feat: all in 1 IOx NG mode
  clap_blocks/src/write_buffer.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/src/commands/run/compactor.rs
  influxdb_iox/src/commands/run/database.rs
  influxdb_iox/src/commands/run/ingester.rs
  influxdb_iox/src/commands/run/mod.rs
  influxdb_iox/src/commands/run/querier.rs
  influxdb_iox/src/commands/run/router.rs
  influxdb_iox/src/commands/run/router2.rs
  influxdb_iox/src/commands/run/test.rs
  influxdb_ioxd/src/lib.rs
  influxdb_ioxd/src/server_type/common_state.rs
  influxdb_ioxd/src/server_type/database/mod.rs
  ingester/src/lib.rs
  write_buffer/src/file.rs
Labels: automerge

#4042 feat: emit object store metrics
  clap_blocks/src/object_store.rs
  compactor/src/compact.rs
  compactor/src/handler.rs
  compactor/src/utils.rs
  db/src/lib.rs
  db/src/lifecycle/persist.rs
  db/src/load.rs
  db/src/replay.rs
  db/src/utils.rs
  influxdb_iox/src/commands/debug/dump_catalog.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/src/commands/run/compactor.rs
  influxdb_iox/src/commands/run/ingester.rs
  influxdb_iox/src/commands/run/querier.rs
  influxdb_ioxd/src/server_type/compactor.rs
  influxdb_ioxd/src/server_type/database/http.rs
  influxdb_ioxd/src/server_type/database/setup.rs
  influxdb_ioxd/src/server_type/ingester.rs
  influxdb_ioxd/src/server_type/querier/mod.rs
  ingester/src/data.rs
  ingester/src/handler.rs
  ingester/src/persist.rs
  ingester/src/test_util.rs
  iox_object_store/src/lib.rs
  iox_object_store/src/paths.rs
  iox_object_store/src/paths/parquet_file.rs
  iox_object_store/src/paths/transaction_file.rs
  iox_tests/src/util.rs
  object_store/src/aws.rs
  object_store/src/azure.rs
  object_store/src/cache.rs
  object_store/src/disk.rs
  object_store/src/dummy.rs
  object_store/src/gcp.rs
  object_store/src/instrumentation.rs
  object_store/src/lib.rs
  object_store/src/memory.rs
  object_store/src/throttle.rs
  parquet_catalog/src/cleanup.rs
  parquet_catalog/src/core.rs
  parquet_catalog/src/dump.rs
  parquet_catalog/src/internals/proto_io.rs
  parquet_catalog/src/prune.rs
  parquet_file/src/test_utils.rs
  querier/src/chunk.rs
  querier/src/database.rs
  querier/src/handler.rs
  querier/src/namespace/mod.rs
  query_tests/src/cancellation.rs
  server/src/application.rs
  server/src/config/object_store.rs
  server/src/database.rs
  server/src/database/init.rs
  server/src/lib.rs
  server_benchmarks/benches/catalog_persistence.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4043 fix: propagate shutdown into QuerierHandlerImpl
  influxdb_ioxd/src/server_type/querier/mod.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4044 fix: propagate shutdown into CompactorHandler
  influxdb_ioxd/src/server_type/compactor.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4045 feat: do not attempt to store entries that will immediately expire
  querier/src/cache_system/backend/ttl.rs
Labels: automerge

#4038 fix: race condition in `Cache::set`
  querier/src/cache_system/driver.rs
Labels: automerge

#4040 feat: `OptionalValueTtlProvider`
  querier/src/cache_system/backend/ttl.rs
Labels: automerge

#4047 refactor: make `QueryDatabase::chunks` async
  db/src/access.rs
  db/src/lib.rs
  influxdb_ioxd/src/planner.rs
  querier/src/namespace/query_access.rs
  query/src/frontend/influxrpc.rs
  query/src/lib.rs
  query/src/test.rs
  query_tests/src/influxrpc/field_columns.rs
  query_tests/src/influxrpc/read_filter.rs
  query_tests/src/influxrpc/read_group.rs
  query_tests/src/influxrpc/read_window_aggregate.rs
  query_tests/src/influxrpc/table_names.rs
  query_tests/src/influxrpc/tag_keys.rs
  query_tests/src/influxrpc/tag_values.rs
  query_tests/src/pruning.rs
  query_tests/src/table_schema.rs
  server/tests/delete.rs
  server_benchmarks/benches/read_filter.rs
  server_benchmarks/benches/read_group.rs
  server_benchmarks/benches/tag_values.rs
Labels: automerge

#4048 feat: Group files by whether they overlap in time
  compactor/src/compact.rs
Labels: automerge

#4039 feat: add "dual" cache pattern
  querier/src/cache_system/backend/dual.rs
  querier/src/cache_system/backend/mod.rs
Labels: automerge

#4051 fix: docker server fixture had mistake in run command
  influxdb2_client/tests/common/server_fixture.rs
Labels: automerge

#4052 refactor: lower pg idle connection timeout
  iox_catalog/src/postgres.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4057 feat: more ingester metrics
  Cargo.lock
  ingester/Cargo.toml
  ingester/src/data.rs
  ingester/src/handler.rs
  ingester/src/test_util.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4053 refactor: dyn-typed DB for `query_tests`
  Cargo.lock
  query_tests/Cargo.toml
  query_tests/src/db.rs
  query_tests/src/influxrpc/field_columns.rs
  query_tests/src/influxrpc/read_filter.rs
  query_tests/src/influxrpc/read_group.rs
  query_tests/src/influxrpc/read_window_aggregate.rs
  query_tests/src/influxrpc/table_names.rs
  query_tests/src/influxrpc/tag_keys.rs
  query_tests/src/influxrpc/tag_values.rs
  query_tests/src/lib.rs
  query_tests/src/scenarios.rs
  query_tests/src/scenarios/library.rs
  query_tests/src/scenarios/util.rs
  query_tests/src/table_schema.rs
  server_benchmarks/benches/read_filter.rs
  server_benchmarks/benches/read_group.rs
  server_benchmarks/benches/tag_values.rs
Labels: automerge

#4065 refactor: reduce INFO verbosity
  db/src/catalog/partition.rs
  db/src/lifecycle/compact.rs
  tracker/src/task/history.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4068 feat: add ttbr metric to ingester
  influxdb_ioxd/src/server_type/ingester.rs
  ingester/src/handler.rs
Labels: automerge

#4061 refactor: make `QueryChunk` object-safe
  compactor/src/query.rs
  db/src/chunk.rs
  influxdb_ioxd/src/rpc/storage/service.rs
  ingester/src/query.rs
  query/src/frontend/influxrpc.rs
  query/src/lib.rs
  query/src/test.rs
  query_tests/src/db.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4079 refactor: steps towards dynamic database type dispatch
  db/src/access.rs
  db/src/lib.rs
  querier/src/namespace/query_access.rs
  query/src/exec.rs
  query/src/lib.rs
  query/src/test.rs
  query_tests/src/db.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4054 refactor: rework `TableCache
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  querier/src/cache/mod.rs
  querier/src/cache/table.rs
  querier/src/chunk.rs
  querier/src/namespace/mod.rs
Labels: automerge

#4058 feat: For each compacted data set, persist new parquet file to object store
  Cargo.lock
  compactor/Cargo.toml
  compactor/src/compact.rs
Labels: automerge

#4063 refactor: `querier` w/o `db`
  Cargo.lock
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  querier/Cargo.toml
  querier/src/chunk/mod.rs
  querier/src/chunk/query_access.rs
  querier/src/lib.rs
  querier/src/namespace/mod.rs
  querier/src/namespace/query_access.rs
  querier/src/table/mod.rs
  querier/src/table/query_access.rs
  querier/src/table/test_util.rs
  querier/src/tombstone.rs
Labels: automerge

#4091 chore: revert "fix: propagate shutdown into CompactorHandler"
  influxdb_ioxd/src/server_type/compactor.rs
Labels: automerge

#4090 chore: revert "fix: propagate shutdown into QuerierHandlerImpl"
  influxdb_ioxd/src/server_type/querier/mod.rs
Labels: automerge

#4083 refactor: dyn-dispatch database in query subsystem
  db/src/access.rs
  db/src/lib.rs
  predicate/src/rpc_predicate.rs
  querier/src/namespace/query_access.rs
  query/src/frontend/influxrpc.rs
  query/src/lib.rs
  query/src/test.rs
  query_tests/src/db.rs
  query_tests/src/influxrpc/field_columns.rs
  query_tests/src/influxrpc/read_filter.rs
  query_tests/src/influxrpc/read_group.rs
  query_tests/src/influxrpc/read_window_aggregate.rs
  query_tests/src/influxrpc/table_names.rs
  query_tests/src/influxrpc/tag_keys.rs
  query_tests/src/influxrpc/tag_values.rs
  query_tests/src/runner.rs
  query_tests/src/scenarios.rs
  query_tests/src/scenarios/library.rs
  query_tests/src/scenarios/util.rs
  query_tests/src/sql.rs
  query_tests/src/table_schema.rs
  server_benchmarks/benches/read_filter.rs
  server_benchmarks/benches/read_group.rs
  server_benchmarks/benches/tag_values.rs
Labels: automerge

#4081 feat: schema grpc server & proto in router2
  generated_types/build.rs
  generated_types/protos/influxdata/iox/schema/v1/service.proto
  generated_types/src/lib.rs
  influxdb_ioxd/src/server_type/router2.rs
  router2/src/server.rs
  router2/src/server/grpc.rs
Labels: automerge

#4095 fix: have ingester use single mutable batch for buffer
  ingester/src/data.rs
  ingester/src/test_util.rs
Labels: automerge

#4098 test: run SOME query tests for querier
  Cargo.lock
  querier/src/cache/mod.rs
  querier/src/cache/namespace.rs
  querier/src/cache/partition.rs
  querier/src/cache/processed_tombstones.rs
  querier/src/cache/table.rs
  querier/src/lib.rs
  query_tests/Cargo.toml
  query_tests/cases/in/delete_multi_expr_one_chunk.expected
  query_tests/cases/in/delete_multi_expr_one_chunk.sql
  query_tests/src/db.rs
  query_tests/src/scenarios/delete.rs
  query_tests/src/scenarios/util.rs
Labels: automerge

#4105 feat: schema client and CLI
  influxdb_iox/src/commands/schema.rs
  influxdb_iox/src/main.rs
  influxdb_iox_client/src/client.rs
  influxdb_iox_client/src/client/schema.rs
Labels: automerge

#4107 feat: add compactor configuration for kafka topic and sequencers
  clap_blocks/src/compactor.rs
  clap_blocks/src/lib.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/src/commands/run/compactor.rs
  influxdb_ioxd/src/server_type/compactor.rs
Labels: automerge

#4112 test: improve query test runner output
  query_tests/src/runner.rs
Labels: automerge

#4115 fix: fix all in one mode argument handling so it can start
  influxdb_iox/src/commands/run/all_in_one.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4110 feat: store sort key in NG metadata
  Cargo.lock
  compactor/src/compact.rs
  generated_types/protos/influxdata/iox/ingester/v1/parquet_metadata.proto
  ingester/src/compact.rs
  ingester/src/persist.rs
  ingester/src/test_util.rs
  iox_tests/Cargo.toml
  iox_tests/src/util.rs
  parquet_file/src/metadata.rs
  querier/src/chunk/mod.rs
Labels: automerge

#4117 fix: Change to_delete column on parquet_files to be a time
  compactor/src/compact.rs
  data_types2/src/lib.rs
  ingester/src/data.rs
  iox_catalog/migrations/20220323150705_change_to_delete_to_timestamp.sql
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
Labels: automerge

#4111 refactor: make query tests less OG-specific
  query_tests/cases/in/no_stats_plans.expected
  query_tests/cases/in/no_stats_plans.sql
  query_tests/cases/in/sql_system_tables.expected
  query_tests/cases/in/sql_system_tables.sql
  query_tests/cases/in/stats_plans.expected
  query_tests/cases/in/stats_plans.sql
  query_tests/src/scenarios.rs
  query_tests/src/scenarios/library.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4106 refactor: extract influxrpc, flight and testing gRPC out of influxdb_ioxd
  Cargo.lock
  Cargo.toml
  influxdb_ioxd/Cargo.toml
  influxdb_ioxd/src/lib.rs
  influxdb_ioxd/src/rpc.rs
  influxdb_ioxd/src/server_type/database/http.rs
  influxdb_ioxd/src/server_type/database/rpc/query.rs
  influxdb_ioxd/src/server_type/querier/rpc/query.rs
  querier/Cargo.toml
  querier/src/database.rs
  server/Cargo.toml
  server/src/lib.rs
  service_common/Cargo.toml
  service_common/src/lib.rs
  service_common/src/planner.rs
  service_grpc_flight/Cargo.toml
  service_grpc_flight/src/lib.rs
  service_grpc_influxrpc/Cargo.toml
  service_grpc_influxrpc/src/data.rs
  service_grpc_influxrpc/src/expr.rs
  service_grpc_influxrpc/src/id.rs
  service_grpc_influxrpc/src/input.rs
  service_grpc_influxrpc/src/lib.rs
  service_grpc_influxrpc/src/service.rs
  service_grpc_testing/Cargo.toml
  service_grpc_testing/src/lib.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#4118 refactor: Fix some random clippy lints from the future
  data_types/src/delete_predicate.rs
  data_types2/src/lib.rs
  ingester/src/server/http.rs
  iox_object_store/src/paths/transaction_file.rs
  read_buffer/src/value.rs
  tracker/src/task.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4103 refactor: generalize query test scenarios a bit
  query_tests/src/scenarios/library.rs
  query_tests/src/scenarios/util.rs
  query_tests/src/table_schema.rs
Labels: automerge

#4113 test: two-chunk scenarios for NG
  query_tests/cases/in/sql_information_schema.expected
  query_tests/cases/in/sql_information_schema.sql
  query_tests/cases/in/sql_system_tables.expected
  query_tests/cases/in/sql_system_tables.sql
  query_tests/src/scenarios/library.rs
  query_tests/src/scenarios/util.rs
Labels: automerge

#4069 test: assert uniform-ish sharder distribution
  router2/src/sharder/jumphash.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4114 test: add end to end test for all in one mode, restructure fixture
  Cargo.lock
  Cargo.toml
  docs/testing.md
  influxdb_iox/Cargo.toml
  influxdb_iox/tests/common_ng/server_fixture.rs
  influxdb_iox/tests/end_to_end_ng.rs
  influxdb_iox/tests/end_to_end_ng_cases/all_in_one.rs
  influxdb_iox/tests/end_to_end_ng_cases/mod.rs
  influxdb_iox/tests/end_to_end_ng_cases/ng.rs
  test_helpers_end_to_end_ng/Cargo.toml
  test_helpers_end_to_end_ng/src/addrs.rs
  test_helpers_end_to_end_ng/src/client.rs
  test_helpers_end_to_end_ng/src/config.rs
  test_helpers_end_to_end_ng/src/database.rs
  test_helpers_end_to_end_ng/src/lib.rs
  test_helpers_end_to_end_ng/src/server_fixture.rs
  test_helpers_end_to_end_ng/src/server_type.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#4127 fix: remove unecessary test setup
  test_helpers_end_to_end_ng/src/server_fixture.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4119 chore: Update deps: datafusion, arrow/arrow-flight/parquet to 11, zstd to 0.11
  Cargo.lock
  arrow_util/Cargo.toml
  compactor/Cargo.toml
  datafusion/Cargo.toml
  db/Cargo.toml
  db/src/access.rs
  db/src/lib.rs
  influxdb_iox/Cargo.toml
  influxdb_iox_client/Cargo.toml
  influxdb_ioxd/Cargo.toml
  ingester/Cargo.toml
  iox_tests/Cargo.toml
  mutable_batch/Cargo.toml
  mutable_buffer/Cargo.toml
  packers/Cargo.toml
  parquet_catalog/Cargo.toml
  parquet_file/Cargo.toml
  predicate/Cargo.toml
  querier/Cargo.toml
  querier/src/namespace/query_access.rs
  query/Cargo.toml
  query_tests/Cargo.toml
  query_tests/src/sql.rs
  read_buffer/Cargo.toml
  schema/Cargo.toml
  service_grpc_flight/Cargo.toml
  service_grpc_influxrpc/Cargo.toml
  test_helpers_end_to_end_ng/Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#4122 refactor: Make `server` an implementation detail in end to end harness
  influxdb_iox/tests/end_to_end_ng_cases/all_in_one.rs
  influxdb_iox/tests/end_to_end_ng_cases/ng.rs
  test_helpers_end_to_end_ng/src/server_fixture.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4126 refactor: use typed `TestConfig` rather than environment variable names for NG end to end tests
  influxdb_iox/tests/end_to_end_ng_cases/all_in_one.rs
  influxdb_iox/tests/end_to_end_ng_cases/ng.rs
  test_helpers_end_to_end_ng/src/config.rs
  test_helpers_end_to_end_ng/src/server_fixture.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4130 fix: propagate shutdown requests & compactor join() fix
  compactor/src/handler.rs
  influxdb_ioxd/src/server_type/compactor.rs
  influxdb_ioxd/src/server_type/querier/mod.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4134 fix: maybe_auto_create_directories infinite loop
  write_buffer/src/file.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4135 refactor: clean up querier public interface
  influxdb_iox/tests/end_to_end_ng_cases/ng.rs
  influxdb_ioxd/src/server_type/querier/mod.rs
  influxdb_ioxd/src/server_type/querier/rpc/query.rs
  querier/src/database.rs
  querier/src/flight.rs
  querier/src/lib.rs
  querier/src/namespace/mod.rs
  querier/src/namespace/query_access.rs
  querier/src/namespace/test_util.rs
  querier/src/table/mod.rs
  querier/src/table/test_util.rs
  query_tests/src/db.rs
  query_tests/src/scenarios/util.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4136 fix: service limit http code
  iox_catalog/src/interface.rs
  router2/src/dml_handlers/schema_validation.rs
  router2/src/server/http.rs
  router2/tests/http.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4133 chore: Update datafusion
  Cargo.lock
  datafusion/Cargo.toml
  generated_types/src/ingester.rs
  query_tests/cases/in/pushdown.expected
  query_tests/cases/in/stats_plans.expected
Labels: automerge, kodiak: merge.method = 'squash'

#4132 test: add e2e test for schema CLI
  influxdb_iox/tests/end_to_end_ng_cases/ng.rs
  test_helpers_end_to_end_ng/src/server_fixture.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4128 refactor: move object store configuration to TestConfig
  test_helpers_end_to_end_ng/src/config.rs
  test_helpers_end_to_end_ng/src/server_fixture.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4143 refactor: `QueryDatabaseProvider::db` should be async
  Cargo.lock
  querier/src/database.rs
  server/src/lib.rs
  service_common/Cargo.toml
  service_common/src/lib.rs
  service_grpc_flight/src/lib.rs
  service_grpc_influxrpc/src/service.rs
Labels: automerge

#4116 feat: delete fully processed tombstones & integration tests for find_and_compact
  Cargo.lock
  compactor/Cargo.toml
  compactor/src/compact.rs
  compactor/src/utils.rs
  data_types2/src/lib.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_tests/src/util.rs
  querier/src/chunk/mod.rs
  querier/src/lib.rs
Labels: automerge

#4142 feat: cache namespace schemas
  iox_tests/src/util.rs
  querier/src/cache/mod.rs
  querier/src/cache/namespace.rs
  querier/src/chunk/mod.rs
  querier/src/namespace/mod.rs
Labels: automerge

#4146 refactor: remove querier sync loop
  Cargo.lock
  querier/src/database.rs
  querier/src/handler.rs
  querier/src/namespace/mod.rs
  querier/src/namespace/query_access.rs
  querier/src/namespace/test_util.rs
  querier/src/poison.rs
  query_tests/Cargo.toml
  query_tests/src/scenarios/util.rs
Labels: automerge

#4131 feat: Clean up old parquet files in the catalog and object storage
  compactor/src/compact.rs
  compactor/src/garbage_collector.rs
  compactor/src/lib.rs
  data_types2/src/lib.rs
  ingester/src/data.rs
  ingester/src/persist.rs
  iox_catalog/migrations/20220324152729_add_namespace_id_to_parquet_file.sql
  iox_catalog/migrations/20220328150925_add_index_to_to_delete.sql
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_tests/src/util.rs
  object_store/src/lib.rs
  parquet_file/src/metadata.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4149 refactor: Extract common, OG database and router out of influxdb_ioxd
  Cargo.lock
  Cargo.toml
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/src/commands/run/compactor.rs
  influxdb_iox/src/commands/run/database.rs
  influxdb_iox/src/commands/run/ingester.rs
  influxdb_iox/src/commands/run/querier.rs
  influxdb_iox/src/commands/run/router.rs
  influxdb_iox/src/commands/run/router2.rs
  influxdb_iox/src/commands/run/test.rs
  influxdb_ioxd/Cargo.toml
  influxdb_ioxd/src/lib.rs
  influxdb_ioxd/src/server_type/compactor.rs
  influxdb_ioxd/src/server_type/ingester.rs
  influxdb_ioxd/src/server_type/mod.rs
  influxdb_ioxd/src/server_type/querier/mod.rs
  influxdb_ioxd/src/server_type/router2.rs
  influxdb_ioxd/src/server_type/test.rs
  ioxd_common/Cargo.toml
  ioxd_common/src/http/dml.rs
  ioxd_common/src/http/error.rs
  ioxd_common/src/http/heappy.rs
  ioxd_common/src/http/metrics.rs
  ioxd_common/src/http/mod.rs
  ioxd_common/src/http/pprof.rs
  ioxd_common/src/http/test_utils.rs
  ioxd_common/src/http/utils.rs
  ioxd_common/src/lib.rs
  ioxd_common/src/rpc.rs
  ioxd_common/src/server_type.rs
  ioxd_common/src/server_type/common_state.rs
  ioxd_database/Cargo.toml
  ioxd_database/src/config.rs
  ioxd_database/src/http.rs
  ioxd_database/src/lib.rs
  ioxd_database/src/rpc/delete.rs
  ioxd_database/src/rpc/deployment.rs
  ioxd_database/src/rpc/error.rs
  ioxd_database/src/rpc/management.rs
  ioxd_database/src/rpc/mod.rs
  ioxd_database/src/rpc/operations.rs
  ioxd_database/src/rpc/query.rs
  ioxd_database/src/rpc/write_pb.rs
  ioxd_database/src/setup.rs
  ioxd_router/Cargo.toml
  ioxd_router/src/http.rs
  ioxd_router/src/lib.rs
  ioxd_router/src/rpc/delete.rs
  ioxd_router/src/rpc/deployment.rs
  ioxd_router/src/rpc/mod.rs
  ioxd_router/src/rpc/remote.rs
  ioxd_router/src/rpc/router.rs
  ioxd_router/src/rpc/write_pb.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4160 refactor: make statistics null counts optional
  data_types/src/partition_metadata.rs
  db/src/chunk.rs
  db/src/lib.rs
  db/src/system_tables/columns.rs
  influxdb_iox/tests/end_to_end_cases/management_api.rs
  influxdb_iox/tests/end_to_end_cases/management_cli.rs
  ingester/src/server/grpc.rs
  mutable_batch/src/column.rs
  mutable_batch/src/writer.rs
  mutable_batch/tests/extend.rs
  mutable_batch/tests/extend_range.rs
  mutable_batch/tests/writer.rs
  mutable_batch/tests/writer_fuzz.rs
  mutable_buffer/src/lib.rs
  parquet_catalog/src/dump.rs
  parquet_file/src/metadata.rs
  parquet_file/src/test_utils.rs
  query/src/pruning.rs
  query/src/statistics.rs
  query/src/test.rs
  query_tests/cases/in/old_sql_system_tables.expected
  query_tests/cases/in/old_sql_system_tables2.expected
  read_buffer/src/chunk.rs
  read_buffer/src/table.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4163 fix: make sure the QueryableParquetChunks are always sorted correctly
  compactor/src/compact.rs
  compactor/src/query.rs
  data_types/src/chunk_metadata.rs
Labels: automerge

#4168 feat: Capture more extreme tail latency buckets for dml handler
  router2/src/dml_handlers/instrumentation.rs
Labels: automerge

#4167 refactor: remove partition key from `ParquetChunk`
  compactor/src/compact.rs
  compactor/src/utils.rs
  db/src/lib.rs
  db/src/lifecycle/compact_object_store.rs
  db/src/lifecycle/write.rs
  db/src/load.rs
  parquet_file/src/chunk.rs
  parquet_file/src/test_utils/generator.rs
  querier/src/chunk/mod.rs
Labels: automerge

#4171 fix: Use a bigger circleci machine for build_dev
  .circleci/config.yml
Labels: automerge

#4170 refactor: remove table name from `TableSummary`
  compactor/src/utils.rs
  data_types/src/partition_metadata.rs
  db/src/catalog/chunk.rs
  db/src/catalog/partition.rs
  db/src/lib.rs
  db/src/lifecycle/compact_object_store.rs
  db/src/lifecycle/write.rs
  db/src/load.rs
  db/src/system_tables/columns.rs
  mutable_buffer/src/lib.rs
  parquet_file/src/chunk.rs
  parquet_file/src/test_utils/generator.rs
  querier/src/chunk/mod.rs
  query/src/statistics.rs
  query/src/test.rs
  read_buffer/src/chunk.rs
  read_buffer/src/table.rs
Labels: automerge

#4157 feat: query log system table for querier
  querier/src/database.rs
  querier/src/lib.rs
  querier/src/namespace/mod.rs
  querier/src/namespace/query_access.rs
  querier/src/query_log.rs
  querier/src/system_tables/mod.rs
  querier/src/system_tables/queries.rs
  query_tests/cases/in/new_sql_system_tables.expected
  query_tests/cases/in/new_sql_system_tables.sql
  query_tests/src/cases.rs
  query_tests/src/scenarios.rs
  query_tests/src/scenarios/library.rs
Labels: automerge
