Repository influxdata/influxdb_iox, pull requests merged in 2022-07, with the labels that each got.

#4988 refactor: Clean up timestamp handling logic and avoid a conversion
  iox_time/src/lib.rs
  write_buffer/src/kafka/mod.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5011 fix: Fix docs for `schema::Schema::is_empty`
  schema/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4996 feat: filter chunks before requesting read buffers
  parquet_file/src/chunk.rs
  querier/src/cache/parquet_file.rs
  querier/src/chunk/mod.rs
  querier/src/table/mod.rs
  querier/src/table/state_reconciler.rs
  querier/src/table/state_reconciler/interface.rs
  query_tests/cases/in/several_chunks.expected
  query_tests/cases/in/several_chunks.sql
Labels: automerge

#5018 fix: do not panic on chunks with same range of sequence numbers but are not time-overlapped
  compactor/src/compact.rs
Labels: automerge

#5019 chore: Upgrade to Rust 1.62
  influxdb_line_protocol/src/lib.rs
  metric/src/gauge.rs
  packers/src/packers.rs
  read_buffer/src/column/encoding/string/dictionary.rs
  read_buffer/src/column/encoding/string/rle.rs
  read_buffer/src/row_group.rs
  read_buffer/src/value.rs
  rust-toolchain.toml
  test_helpers/src/tracing.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5009 refactor: Move sharding query from namespace to table
  querier/src/namespace/mod.rs
  querier/src/table/mod.rs
  querier/src/table/test_util.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5006 fix: Fix test bug for InfluxRPC `<unknown field> != <value>`
  query_tests/src/influxrpc/read_filter.rs
  query_tests/src/influxrpc/tag_keys.rs
  query_tests/src/influxrpc/util.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5020 chore: Update datafusion
  Cargo.lock
  datafusion/Cargo.toml
  querier/src/namespace/query_access.rs
  query_tests/cases/in/pushdown.expected
Labels: automerge, kodiak: merge.method = 'squash'

#4985 fix: optimize tag_keys to go only to schema when predicate is empty
  iox_query/src/frontend/influxrpc.rs
  predicate/src/rpc_predicate.rs
  query_tests/src/influxrpc/tag_keys.rs
  query_tests/src/scenarios/library.rs
  service_grpc_influxrpc/src/expr.rs
  service_grpc_influxrpc/src/service.rs
Labels: automerge

#5030 refactor: unify `apply_predicate_to_metadata`
  compactor/src/query.rs
  ingester/src/query.rs
  iox_query/src/lib.rs
  iox_query/src/util.rs
  parquet_file/src/chunk.rs
  querier/src/chunk/mod.rs
  querier/src/chunk/query_access.rs
  querier/src/chunk/util.rs
  querier/src/ingester/mod.rs
Labels: automerge

#5025 feat: add max desired file size config param
  clap_blocks/src/compactor.rs
  compactor/src/compact.rs
  compactor/src/handler.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ioxd_compactor/src/lib.rs
Labels: automerge

#5041 refactor: convert a panic into an error and throw a warning if we choose non-actionable compacting candidates
  compactor/src/compact.rs
  compactor/src/handler.rs
Labels: automerge

#5045 chore: c2updater to acs transition
  .circleci/config.yml
Labels: automerge

#5042 refactor: avoid write buffer cloning in `store_operation`
  router/src/sequencer.rs
  write_buffer/src/core.rs
  write_buffer/src/file.rs
  write_buffer/src/kafka/mod.rs
  write_buffer/src/mock.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5046 fix: optimize field columns for all-time predicates
  data_types/src/lib.rs
  iox_query/src/exec/context.rs
  iox_query/src/frontend/influxrpc.rs
  iox_query/src/plan/fieldlist.rs
  predicate/src/lib.rs
  query_tests/src/influxrpc/field_columns.rs
  query_tests/src/influxrpc/table_names.rs
  query_tests/src/influxrpc/tag_keys.rs
  service_grpc_influxrpc/src/service.rs
Labels: automerge

#5054 ci: clean up and fixes
  .circleci/config.yml
  .circleci/get-deploy-tags.sh
Labels: automerge

#5053 refactor: disable TTL (caching) for non-existing namespaces
  querier/src/cache/namespace.rs
Labels: automerge

#5056 fix: Correctly set up querier-to-ingester config, sequencers, and catalog for all-in-one ephemeral mode
  clap_blocks/src/catalog_dsn.rs
  influxdb_iox/tests/end_to_end_cases/all_in_one.rs
  influxdb_iox/tests/end_to_end_cases/metrics.rs
  influxdb_iox/tests/end_to_end_cases/tracing.rs
  iox_catalog/src/lib.rs
  test_helpers_end_to_end/src/config.rs
  test_helpers_end_to_end/src/server_fixture.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5049 feat: add "peek" functionality for caches
  cache_system/src/cache/driver.rs
  cache_system/src/cache/metrics.rs
  cache_system/src/cache/mod.rs
  cache_system/src/cache/test_util.rs
Labels: automerge

#5043 test: add test for "duration since production" in kafka `write_buffer` implementation
  dml/src/lib.rs
  ingester/src/stream_handler/handler.rs
  write_buffer/src/core.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5024 feat: Automatically remove old / unreferenced objects from the object store
  .guppy/hakari.toml
  Cargo.lock
  Cargo.toml
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/objectstore_garbage_collect.rs
  influxdb_iox/src/main.rs
  iox_objectstore_garbage_collect/Cargo.toml
  iox_objectstore_garbage_collect/src/checker.rs
  iox_objectstore_garbage_collect/src/deleter.rs
  iox_objectstore_garbage_collect/src/lib.rs
  iox_objectstore_garbage_collect/src/lister.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5069 docs: add consensus for the desired final output of the compactor
  compactor/README.md
  compactor/src/compact.rs
Labels: automerge

#5021 chore: Update datafusion + arrow/parquet/arrow-flight to `17.0.0`
  Cargo.lock
  arrow_util/Cargo.toml
  compactor/Cargo.toml
  datafusion/Cargo.toml
  datafusion_util/src/lib.rs
  influxdb_iox/Cargo.toml
  influxdb_iox_client/Cargo.toml
  ingester/Cargo.toml
  iox_query/Cargo.toml
  iox_query/src/provider/adapter.rs
  iox_query/src/provider/deduplicate.rs
  iox_tests/Cargo.toml
  ioxd_querier/Cargo.toml
  mutable_batch/Cargo.toml
  packers/Cargo.toml
  parquet_file/Cargo.toml
  predicate/Cargo.toml
  predicate/src/lib.rs
  querier/Cargo.toml
  querier/src/system_tables/queries.rs
  query_functions/Cargo.toml
  query_functions/src/selectors.rs
  query_tests/Cargo.toml
  read_buffer/Cargo.toml
  read_buffer/src/chunk.rs
  schema/Cargo.toml
  service_grpc_flight/Cargo.toml
  service_grpc_influxrpc/Cargo.toml
  test_helpers_end_to_end/Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#5064 feat: `ReadBufferCache::peek`
  querier/src/cache/read_buffer.rs
Labels: automerge

#5063 refactor: `QuerierParquet` + `QuerierRBChunk` = ❤️ (merge them together)
  querier/src/chunk/mod.rs
  querier/src/chunk/query_access.rs
  querier/src/table/mod.rs
  querier/src/table/state_reconciler.rs
  querier/src/table/state_reconciler/interface.rs
Labels: automerge

#5075 refactor: try to query "cheap" chunks first
  iox_query/src/frontend/influxrpc.rs
Labels: automerge

#5066 feat: Increase `DmlWrite` operation throughput by pipelining kafka read and decode
  write_buffer/src/core.rs
  write_buffer/src/kafka/mod.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5077 fix: Correct typo in constant name so searching for COMPACTION_LEVEL returns all
  compactor/src/compact.rs
  data_types/src/lib.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
  parquet_file/src/metadata.rs
  parquet_file/src/serialize.rs
  parquet_file/src/storage.rs
  parquet_file/tests/metadata.rs
Labels: automerge

#5087 chore: fix `perf` and friends
  .cargo/config
Labels: automerge

#5086 refactor: use less executors and threads during tests
  Cargo.lock
  iox_tests/Cargo.toml
  iox_tests/src/util.rs
  query_tests/src/runner.rs
  query_tests/src/scenarios/util.rs
Labels: automerge

#5089 test: do NOT create expensive bloom filters when we do not need them
  cache_system/src/loader/metrics.rs
  ioxd_querier/src/rpc/namespace.rs
  querier/src/cache/mod.rs
  querier/src/cache/namespace.rs
  querier/src/cache/parquet_file.rs
  querier/src/cache/partition.rs
  querier/src/cache/processed_tombstones.rs
  querier/src/cache/read_buffer.rs
  querier/src/cache/table.rs
  querier/src/cache/tombstones.rs
  querier/src/chunk/mod.rs
  querier/src/database.rs
  querier/src/handler.rs
  querier/src/ingester/mod.rs
  querier/src/namespace/test_util.rs
  querier/src/table/test_util.rs
  query_tests/src/scenarios/util.rs
Labels: automerge

#5092 fix: Clean up docs for `addressable_heap`
  cache_system/src/backend/addressable_heap.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5102 docs: extend profiling docs
  docs/images/getrandom_callgraph.svg
  docs/images/heaptrack.png
  docs/profiling.md
  docs/underground_guide.md
Labels: automerge

#5091 feat: load read buffer on demand
  iox_query/src/provider/adapter.rs
  parquet_file/src/storage.rs
  querier/src/chunk/mod.rs
  querier/src/chunk/query_access.rs
  querier/src/database.rs
  querier/src/lib.rs
  querier/src/namespace/mod.rs
  querier/src/namespace/test_util.rs
  querier/src/table/test_util.rs
  query_tests/src/runner.rs
  query_tests/src/scenarios/util.rs
  schema/src/selection.rs
Labels: automerge

#5113 fix: fix overeager Kafka message flushing
  write_buffer/src/kafka/aggregator.rs
  write_buffer/src/kafka/mod.rs
Labels: automerge

#5108 feat: config params for Compactor
  clap_blocks/src/compactor.rs
  compactor/src/compact.rs
  compactor/src/handler.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ioxd_compactor/src/lib.rs
Labels: automerge

#5115 feat: skip ingester buffering if INFLUXDB_IOX_INGESTER_SKIP_BUFFER is set
  ingester/src/stream_handler/sink_adaptor.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5114 chore: update all dependencies (esp. `time`)
  Cargo.lock
Labels: automerge

#5112 fix: do not force-load chunks into read buffer
  querier/src/chunk/mod.rs
  querier/src/table/mod.rs
  querier/src/table/state_reconciler.rs
  querier/src/table/test_util.rs
Labels: automerge

#5122 fix: Remove unused level 1 compaction; move level 2 to level 1
  compactor/src/compact.rs
  data_types/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5127 refactor: ingester seek log debug => info
  ingester/src/handler.rs
Labels: automerge

#5130 feat: add tracing to instrumented semaphores
  Cargo.lock
  querier/src/database.rs
  service_common/Cargo.toml
  service_common/src/lib.rs
  service_common/src/test_util.rs
  service_grpc_flight/Cargo.toml
  service_grpc_flight/src/lib.rs
  service_grpc_influxrpc/Cargo.toml
  service_grpc_influxrpc/src/service.rs
  tracker/Cargo.toml
  tracker/src/async_semaphore.rs
  workspace-hack/Cargo.toml
Labels: automerge

#5137 refactor: replace level_2 with level_1
  compactor/src/compact.rs
  data_types/src/lib.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  parquet_file/src/metadata.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5131 feat: Select compaction candidates
  clap_blocks/src/compactor.rs
  compactor/src/compact.rs
  compactor/src/handler.rs
  data_types/src/lib.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_query/src/provider/deduplicate/algo.rs
  iox_tests/src/util.rs
  ioxd_compactor/src/lib.rs
Labels: automerge

#5135 feat: make object store garbage collector into a long-running service
  Cargo.lock
  Cargo.toml
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/objectstore_garbage_collect.rs
  influxdb_iox/src/commands/run/garbage_collector.rs
  influxdb_iox/src/commands/run/mod.rs
  influxdb_iox/src/main.rs
  iox_objectstore_garbage_collect/Cargo.toml
  iox_objectstore_garbage_collect/src/lib.rs
  iox_objectstore_garbage_collect/src/lister.rs
  iox_objectstore_garbage_collect/src/server.rs
  ioxd_objectstore_garbage_collect/Cargo.toml
  ioxd_objectstore_garbage_collect/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5147 fix: warn if `--data-dir is specified but `--object_store` type is not file
  clap_blocks/src/object_store.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5134 feat: wire span all the way to `QuerierTable::chunks`
  iox_query/src/exec.rs
  iox_query/src/exec/context.rs
  iox_query/src/frontend/influxrpc.rs
  iox_query/src/lib.rs
  iox_query/src/test.rs
  querier/src/namespace/query_access.rs
  querier/src/table/mod.rs
  querier/src/table/query_access.rs
  query_tests/src/table_schema.rs
Labels: automerge

#5150 fix: Fix SeriesKey sort order for special _measurement and _field
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/read_filter.rs
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/read_group.rs
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/read_window_aggregate.rs
  iox_query/src/exec/seriesset/series.rs
  query_tests/src/influxrpc/read_filter.rs
  query_tests/src/influxrpc/read_group.rs
  query_tests/src/influxrpc/read_window_aggregate.rs
  service_grpc_influxrpc/src/data.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5149 chore: Add org and bucket ID parsing to tsm_reader
  influxdb_tsm/src/key.rs
Labels: Migration

#5160 fix: Add TagKeyMetaNamesCapability capability
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/metadata.rs
  service_grpc_influxrpc/src/service.rs
Labels: automerge

#5155 fix: tab complete from hints in `sql` relp (itch scratch)
  influxdb_iox/src/commands/sql/repl.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5159 feat: trace querier->ingester, stopping at gRPC layer
  querier/src/ingester/mod.rs
  querier/src/ingester/test_util.rs
  querier/src/table/mod.rs
Labels: automerge

#5146 feat: Improve logging for garbage collector service
  Cargo.lock
  iox_objectstore_garbage_collect/src/deleter.rs
  iox_objectstore_garbage_collect/src/lib.rs
  iox_objectstore_garbage_collect/src/lister.rs
  ioxd_objectstore_garbage_collect/Cargo.toml
  ioxd_objectstore_garbage_collect/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5161 feat: allow passing for extra arguments to `Cache::peek`
  cache_system/src/cache/driver.rs
  cache_system/src/cache/metrics.rs
  cache_system/src/cache/mod.rs
  cache_system/src/cache/test_util.rs
  querier/src/cache/namespace.rs
  querier/src/cache/parquet_file.rs
  querier/src/cache/partition.rs
  querier/src/cache/processed_tombstones.rs
  querier/src/cache/read_buffer.rs
  querier/src/cache/table.rs
  querier/src/cache/tombstones.rs
Labels: automerge

#5162 chore: Update datafusion pin
  Cargo.lock
  datafusion/Cargo.toml
  query_tests/cases/in/new_sql_system_tables.expected
  query_tests/cases/in/sql_information_schema.expected
Labels: automerge, kodiak: merge.method = 'squash'

#5158 refactor: enforce proper `IOxSessionContext`
  compactor/src/compact.rs
  ingester/src/compact.rs
  ingester/src/querier_handler.rs
  iox_query/src/exec.rs
  iox_query/src/exec/context.rs
  iox_query/src/frontend.rs
  iox_query/src/frontend/common.rs
  iox_query/src/frontend/influxrpc.rs
  iox_query/src/frontend/reorg.rs
  iox_query/src/provider.rs
  iox_query/src/provider/physical.rs
  iox_query/src/test.rs
  querier/src/chunk/mod.rs
  querier/src/namespace/mod.rs
  querier/src/table/mod.rs
  querier/src/table/query_access.rs
  querier/src/table/test_util.rs
Labels: automerge

#5163 refactor: improve cache system generic tests
  cache_system/src/cache/driver.rs
  cache_system/src/cache/metrics.rs
  cache_system/src/cache/test_util.rs
Labels: automerge

#5164 feat: cache tracing
  Cargo.lock
  cache_system/Cargo.toml
  cache_system/src/cache/driver.rs
  cache_system/src/cache/metrics.rs
  cache_system/src/cache/mod.rs
  cache_system/src/cache/test_util.rs
  querier/src/cache/namespace.rs
  querier/src/cache/parquet_file.rs
  querier/src/cache/partition.rs
  querier/src/cache/processed_tombstones.rs
  querier/src/cache/read_buffer.rs
  querier/src/cache/table.rs
  querier/src/cache/tombstones.rs
Labels: automerge

#5151 refactor: remove min_sequence_number from Compactor and Querier, add `count_by_overlaps_with_level_0` and `count_by_overlaps_with_level_1` to catalog
  compactor/src/compact.rs
  compactor/src/garbage_collector.rs
  compactor/src/parquet_file_filtering.rs
  compactor/src/query.rs
  compactor/src/utils.rs
  data_types/src/lib.rs
  generated_types/protos/influxdata/iox/catalog/v1/parquet_file.proto
  generated_types/protos/influxdata/iox/ingester/v1/parquet_metadata.proto
  influxdb_iox/src/commands/remote/partition.rs
  ingester/src/compact.rs
  ingester/src/data.rs
  ingester/src/test_util.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_objectstore_garbage_collect/src/checker.rs
  iox_tests/src/util.rs
  parquet_file/src/metadata.rs
  parquet_file/src/serialize.rs
  parquet_file/src/storage.rs
  parquet_file/tests/metadata.rs
  querier/src/cache/parquet_file.rs
  querier/src/chunk/mod.rs
  querier/src/namespace/query_access.rs
  querier/src/table/mod.rs
  querier/src/table/state_reconciler.rs
  querier/src/table/state_reconciler/interface.rs
  service_grpc_catalog/src/lib.rs
  service_grpc_object_store/src/lib.rs
Labels: automerge

#5175 feat: add sort key and partition key into PartitionCompactionCandidateWithInfo
  compactor/src/compact.rs
Labels: automerge

#5173 feat: wire up cache tracing (2/2)
  querier/src/cache/namespace.rs
  querier/src/cache/parquet_file.rs
  querier/src/cache/partition.rs
  querier/src/chunk/mod.rs
  querier/src/database.rs
  querier/src/ingester/mod.rs
  querier/src/table/mod.rs
  querier/src/table/state_reconciler.rs
  service_common/src/lib.rs
  service_common/src/test_util.rs
  service_grpc_flight/src/lib.rs
  service_grpc_influxrpc/src/service.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5178 chore: remove min sequence number from the catalog table as we no longer use it
  iox_catalog/migrations/20220721195556_drop_min_sequence_number.sql
Labels: automerge

#5176 feat: Compact filtered parquet files
  compactor/src/compact.rs
  compactor/src/lib.rs
  compactor/src/parquet_file_combining.rs
  compactor/src/query.rs
  compactor/src/utils.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5184 chore: Revert "Sync ReadWindowAggregate API: TagKeyMetaNames"
  generated_types/protos/influxdata/platform/storage/storage_common.proto
  influxdb_iox/src/commands/storage/request.rs
  service_grpc_influxrpc/src/service.rs
  test_helpers_end_to_end/src/grpc.rs
Labels: automerge

#5185 refactor: improve query gRPC logging
  service_grpc_flight/src/lib.rs
  service_grpc_influxrpc/src/expr.rs
  service_grpc_influxrpc/src/service.rs
Labels: automerge

#5186 chore: Roll forward: Sync ReadWindowAggregate API: TagKeyMetaNames
  generated_types/protos/influxdata/platform/storage/storage_common.proto
  influxdb_iox/src/commands/storage/request.rs
  service_grpc_influxrpc/src/service.rs
  test_helpers_end_to_end/src/grpc.rs
Labels: automerge, incompatible protobuf

#5180 refactor: Reduce boiler plate calling `SpanRecorder::child`
  querier/src/chunk/mod.rs
  querier/src/chunk/query_access.rs
  querier/src/database.rs
  querier/src/ingester/mod.rs
  querier/src/table/mod.rs
  querier/src/table/state_reconciler.rs
  trace/src/span.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5181 refactor: Reduce ceremony requried to create a `Span` from `SpanContext`
  ingester/src/stream_handler/sink_instrumentation.rs
  iox_query/src/exec.rs
  iox_query/src/exec/context.rs
  router/src/dml_handlers/instrumentation.rs
  service_grpc_flight/src/lib.rs
  service_grpc_influxrpc/src/service.rs
  trace/src/span.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5189 fix: Compact one level 0 file to avoid getting stuck on it
  compactor/src/parquet_file_combining.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5183 feat: Implement LineProtocol (LP) builder
  Cargo.lock
  influxdb_line_protocol/Cargo.toml
  influxdb_line_protocol/src/builder.rs
  influxdb_line_protocol/src/lib.rs
Labels: automerge

#5190 feat: metrics for selection partition candidates for compaction
  compactor/src/compact.rs
  compactor/src/handler.rs
Labels: automerge

#5192 fix: compute_split_time returns one value when min_time = max_time
  compactor/src/utils.rs
Labels: automerge

#5193 chore: Update datafusion
  Cargo.lock
  datafusion/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#5194 feat: Different branch to hook up new compaction algorithm
  compactor/src/compact.rs
  compactor/src/handler.rs
  compactor/src/lib.rs
  compactor/src/parquet_file_combining.rs
  compactor/src/parquet_file_filtering.rs
  compactor/src/parquet_file_lookup.rs
  compactor/src/utils.rs
  influxdb_iox/tests/end_to_end_cases/cli.rs
Labels: automerge

#5195 feat: split large compactions
  compactor/src/lib.rs
  compactor/src/parquet_file_combining.rs
  compactor/src/utils.rs
Labels: automerge

#5197 refactor: split up `test_cases_delete_three_delete_three_chunks_sql` to run in parallel
  query_tests/cases/in/delete_three_chunks_1.expected
  query_tests/cases/in/delete_three_chunks_1.sql
  query_tests/cases/in/delete_three_chunks_2.expected
  query_tests/cases/in/delete_three_chunks_2.sql
  query_tests/cases/in/delete_three_chunks_3.expected
  query_tests/cases/in/delete_three_chunks_3.sql
  query_tests/cases/in/delete_three_chunks_4.expected
  query_tests/cases/in/delete_three_chunks_4.sql
  query_tests/cases/in/delete_three_delete_three_chunks.expected
  query_tests/cases/in/delete_three_delete_three_chunks.sql
  query_tests/src/cases.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5199 feat: add debug log to `with_clear_timestamp_if_max_range`
  predicate/src/lib.rs
Labels: automerge

#5196 refactor: rename garbage collector crates for consistency
  .guppy/hakari.toml
  Cargo.lock
  Cargo.toml
  garbage_collector/Cargo.toml
  garbage_collector/src/checker.rs
  garbage_collector/src/deleter.rs
  garbage_collector/src/lib.rs
  garbage_collector/src/lister.rs
  garbage_collector/src/server.rs
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/run/garbage_collector.rs
  ioxd_garbage_collector/Cargo.toml
  ioxd_garbage_collector/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5200 refactor: allocate less memory for tracing
  trace/src/ctx.rs
  trace/src/span.rs
Labels: automerge

#5203 chore: always pass `ROARING_ARCH`
  .cargo/config
  Dockerfile
Labels: automerge

#5206 refactor: reduce compacting size and compacted file size to prevent compactor from waiting for reading a large file forever
  clap_blocks/src/compactor.rs
  parquet_file/src/serialize.rs
  parquet_file/src/storage.rs
Labels: automerge

#5205 docs: extend profiling guide
  docs/images/hotspot.png
  docs/images/jaeger_details.png
  docs/images/jaeger_overview.png
  docs/profiling.md
  docs/tracing.md
  scripts/lint_docs.py
Labels: automerge

#5212 fix: Run compactor streams in parallel to avoid deadlock
  compactor/src/parquet_file_combining.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5210 test: Add a test for LP quoting
  influxdb_line_protocol/src/builder.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5220 fix: Tell which column failed typecheck
  mutable_batch/src/column.rs
  mutable_batch/src/writer.rs
  mutable_batch/tests/writer.rs
  mutable_batch_pb/src/decode.rs
Labels: automerge

#5213 feat: cache projected chunk schemas in querier
  querier/src/cache/mod.rs
  querier/src/cache/projected_schema.rs
  querier/src/chunk/mod.rs
  schema/src/lib.rs
Labels: automerge

#5219 fix: Clarify error msg: line number is 1-based
  mutable_batch_lp/src/lib.rs
Labels: automerge

#5223 feat: limit per-table chunk data for every query
  clap_blocks/src/querier.rs
  compactor/src/query.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ingester/src/query.rs
  iox_query/src/lib.rs
  iox_query/src/provider.rs
  iox_query/src/test.rs
  ioxd_querier/src/lib.rs
  ioxd_querier/src/rpc/namespace.rs
  querier/src/chunk/mod.rs
  querier/src/chunk/query_access.rs
  querier/src/database.rs
  querier/src/handler.rs
  querier/src/ingester/mod.rs
  querier/src/namespace/mod.rs
  querier/src/namespace/query_access.rs
  querier/src/namespace/test_util.rs
  querier/src/table/mod.rs
  querier/src/table/query_access.rs
  querier/src/table/test_util.rs
  query_tests/src/scenarios/util.rs
Labels: automerge

#5222 fix: Fix typo in log message
  ingester/src/lifecycle.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5225 fix: reduce log verbosity for `found compaction candidates` message
  compactor/src/handler.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5230 feat: run many compact partitions in parallel
  compactor/src/handler.rs
Labels: automerge

#5229 chore: Update datafusion and `arrow`/`parquet`/`arrow-flight` to `19.0.0`
  Cargo.lock
  arrow_util/Cargo.toml
  arrow_util/src/optimize.rs
  compactor/Cargo.toml
  datafusion/Cargo.toml
  influxdb_iox/Cargo.toml
  influxdb_iox_client/Cargo.toml
  ingester/Cargo.toml
  iox_query/Cargo.toml
  iox_query/src/exec.rs
  iox_tests/Cargo.toml
  ioxd_querier/Cargo.toml
  mutable_batch/Cargo.toml
  packers/Cargo.toml
  parquet_file/Cargo.toml
  parquet_file/src/metadata.rs
  parquet_file/src/serialize.rs
  parquet_file/src/storage.rs
  parquet_file/tests/metadata.rs
  predicate/Cargo.toml
  querier/Cargo.toml
  query_functions/Cargo.toml
  query_tests/Cargo.toml
  read_buffer/Cargo.toml
  schema/Cargo.toml
  service_grpc_flight/Cargo.toml
  service_grpc_influxrpc/Cargo.toml
  test_helpers_end_to_end/Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#5231 fix: interpret [MIN_NANO_TIME, MAX_NANO_TIME) range as all time
  data_types/src/lib.rs
  predicate/src/lib.rs
  query_tests/src/influxrpc/field_columns.rs
  service_grpc_influxrpc/src/service.rs
Labels: automerge

#5187 feat: log external span for query gRPC requests
  Cargo.lock
  service_grpc_flight/Cargo.toml
  service_grpc_flight/src/lib.rs
  service_grpc_influxrpc/Cargo.toml
  service_grpc_influxrpc/src/service.rs
  trace/src/ctx.rs
  trace_exporters/src/jaeger.rs
  trace_http/src/ctx.rs
  trace_http/src/tower.rs
  write_buffer/src/codec.rs
Labels: automerge

#5235 feat: add a few helpful compactor debug logs
  compactor/src/compact.rs
  compactor/src/handler.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5224 fix: remove left over `dbg!` macro
  compactor/src/parquet_file_combining.rs
Labels: automerge, kodiak: merge.method = 'squash'
