Repository influxdata/influxdb_iox, pull requests merged in 2022-10, with the labels that each got.

#5763 feat: `EXPLAIN` statement
  influxdb_influxql_parser/src/explain.rs
  influxdb_influxql_parser/src/lib.rs
  influxdb_influxql_parser/src/statement.rs
Labels: automerge, influxql

#5786 fix(ingester): incorrect memory tracking of failed writes
  ingester/src/data/table.rs
  ingester/src/lifecycle/mock_handle.rs
  query_tests/src/scenarios/util.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5788 chore: Update SQL repl to refer to `namespace` rather than `database`
  influxdb_iox/src/commands/sql/repl.rs
  influxdb_iox/src/commands/sql/repl_command.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5791 refactor: reference buffer tree nodes by ID
  ingester/src/compact.rs
  ingester/src/data.rs
  ingester/src/data/namespace.rs
  ingester/src/data/partition.rs
  ingester/src/data/partition/resolver/cache.rs
  ingester/src/data/partition/resolver/trait.rs
  ingester/src/data/shard.rs
  ingester/src/data/table.rs
  ingester/src/lifecycle.rs
  query_tests/src/scenarios/util.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5798 refactor: carry namespace name in NamespaceData
  ingester/src/data.rs
  ingester/src/data/namespace.rs
  ingester/src/data/shard.rs
  ingester/src/handler.rs
  ingester/src/querier_handler.rs
  ingester/src/test_util.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5782 feat: Projection pushdown for querier -> ingester for rpc queries
  datafusion_util/src/lib.rs
  iox_query/src/exec/seriesset/converter.rs
  iox_query/src/frontend/influxrpc.rs
  iox_query/src/lib.rs
  iox_query/src/provider/adapter.rs
  iox_query/src/test.rs
  querier/src/cache/read_buffer.rs
  querier/src/namespace/query_access.rs
  query_tests/src/table_schema.rs
Labels: automerge

#5794 fix: Correct representation of 3-part measurement name
  influxdb_influxql_parser/src/common.rs
  influxdb_influxql_parser/src/delete.rs
  influxdb_influxql_parser/src/internal.rs
  influxdb_influxql_parser/src/select.rs
  influxdb_influxql_parser/src/show_measurements.rs
  influxdb_influxql_parser/src/simple_from_clause.rs
Labels: automerge, influxql

#5818 feat(influxrpc): rewrite missing column references to NULL
  predicate/src/lib.rs
  predicate/src/rpc_predicate.rs
  predicate/src/rpc_predicate/column_rewrite.rs
  predicate/src/rpc_predicate/field_rewrite.rs
  predicate/src/rpc_predicate/rewrite.rs
  query_tests/src/influxrpc/read_filter.rs
  service_grpc_influxrpc/src/expr.rs
  service_grpc_influxrpc/src/service.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5787 docs: Tweak local run guide
  docs/underground_guide.md
Labels: automerge

#5807 perf(ingester): deferred sort key load
  Cargo.lock
  ingester/Cargo.toml
  ingester/src/data/namespace.rs
  ingester/src/data/partition.rs
  ingester/src/data/partition/resolver/cache.rs
  ingester/src/data/partition/resolver/catalog.rs
  ingester/src/data/partition/resolver/mod.rs
  ingester/src/data/partition/resolver/sort_key.rs
  ingester/src/data/partition/resolver/trait.rs
  ingester/src/data/shard.rs
  ingester/src/data/table.rs
  ingester/src/handler.rs
  iox_catalog/src/interface.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5826 refactor: use TableName, not Arc<str>
  ingester/src/data.rs
  ingester/src/data/namespace.rs
  ingester/src/data/partition.rs
  ingester/src/data/partition/buffer.rs
  ingester/src/data/partition/resolver/cache.rs
  ingester/src/data/partition/resolver/catalog.rs
  ingester/src/data/partition/resolver/mock.rs
  ingester/src/data/partition/resolver/trait.rs
  ingester/src/data/table.rs
  ingester/src/handler.rs
  ingester/src/querier_handler.rs
  ingester/src/query.rs
  ingester/src/test_util.rs
Labels: kodiak: merge.method = 'merge'

#5800 feat: Swap Kafka Producer implementation back to rdkafka as diagnosis of latency problem
  Cargo.lock
  write_buffer/Cargo.toml
  write_buffer/src/config.rs
  write_buffer/src/core.rs
  write_buffer/src/kafka/instrumentation.rs
  write_buffer/src/kafka/mod.rs
  write_buffer/src/kafka/rdkafka.rs
  write_buffer/src/kafka/record_aggregator.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5829 chore: add trace log to ingester to aid debugging
  ingester/src/stream_handler/handler.rs
Labels: automerge

#5830 revert: rdkafka/rskafka swapping (#5800)
  Cargo.lock
  write_buffer/Cargo.toml
  write_buffer/src/config.rs
  write_buffer/src/core.rs
  write_buffer/src/kafka/instrumentation.rs
  write_buffer/src/kafka/mod.rs
  write_buffer/src/kafka/rdkafka.rs
  write_buffer/src/kafka/record_aggregator.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5831 refactor(ingester): remove tombstone support and delete tests from `query_tests`
  generated_types/protos/influxdata/iox/ingester/v1/query.proto
  influxdb_iox/tests/end_to_end_cases/ingester.rs
  ingester/src/compact.rs
  ingester/src/data.rs
  ingester/src/data/namespace.rs
  ingester/src/data/partition.rs
  ingester/src/data/partition/buffer.rs
  ingester/src/data/query_dedup.rs
  ingester/src/data/shard.rs
  ingester/src/data/table.rs
  ingester/src/querier_handler.rs
  ingester/src/query.rs
  ingester/src/server/grpc.rs
  ingester/src/stream_handler/handler.rs
  ingester/src/stream_handler/mod.rs
  ingester/src/stream_handler/periodic_watermark_fetcher.rs
  ingester/src/stream_handler/sink.rs
  ingester/src/stream_handler/sink_instrumentation.rs
  ingester/src/test_util.rs
  iox_catalog/src/postgres.rs
  querier/src/ingester/mod.rs
  query_tests/cases/in/delete_all.expected
  query_tests/cases/in/delete_all.sql
  query_tests/cases/in/delete_multi_expr_one_chunk.expected
  query_tests/cases/in/delete_multi_expr_one_chunk.sql
  query_tests/cases/in/delete_simple_pred_one_chunk.expected
  query_tests/cases/in/delete_simple_pred_one_chunk.sql
  query_tests/cases/in/delete_three_chunks_1.expected
  query_tests/cases/in/delete_three_chunks_1.sql
  query_tests/cases/in/delete_three_chunks_2.expected
  query_tests/cases/in/delete_three_chunks_2.sql
  query_tests/cases/in/delete_three_chunks_3.expected
  query_tests/cases/in/delete_three_chunks_3.sql
  query_tests/cases/in/delete_three_chunks_4.expected
  query_tests/cases/in/delete_three_chunks_4.sql
  query_tests/cases/in/delete_two_del_multi_expr_one_chunk.expected
  query_tests/cases/in/delete_two_del_multi_expr_one_chunk.sql
  query_tests/src/cases.rs
  query_tests/src/influxrpc/field_columns.rs
  query_tests/src/influxrpc/read_filter.rs
  query_tests/src/influxrpc/read_group.rs
  query_tests/src/influxrpc/read_window_aggregate.rs
  query_tests/src/influxrpc/table_names.rs
  query_tests/src/influxrpc/tag_keys.rs
  query_tests/src/influxrpc/tag_values.rs
  query_tests/src/scenarios/library.rs
  query_tests/src/scenarios/util.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5834 refactor: due to limit in size uploaded to S3, we need to split output file of cold compaction, too
  compactor/src/cold.rs
Labels: automerge

#5839 chore: add some tracing logs to the ingester
  ingester/src/data/partition.rs
  ingester/src/data/table.rs
  ingester/src/lifecycle.rs
Labels: automerge

#5845 refactor: split memory estimation into bytes to store and bytes to stream
  compactor/src/parquet_file.rs
  compactor/src/parquet_file_filtering.rs
  compactor/src/parquet_file_lookup.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5840 chore: remove vestigal DML handling from `ioxd_common`
  Cargo.lock
  ioxd_common/Cargo.toml
  ioxd_common/src/http/dml.rs
  ioxd_common/src/http/mod.rs
Labels: automerge

#5842 docs: Add some doc comments to the datafusion_util module
  datafusion_util/src/lib.rs
Labels: automerge

#5846 chore: update dependencies
  Cargo.lock
Labels: automerge, kodiak: merge.method = 'squash'

#5844 revert: "revert: rdkafka/rskafka swapping (#5800)"
  Cargo.lock
  clap_blocks/src/write_buffer.rs
  write_buffer/Cargo.toml
  write_buffer/src/config.rs
  write_buffer/src/core.rs
  write_buffer/src/kafka/instrumentation.rs
  write_buffer/src/kafka/mod.rs
  write_buffer/src/kafka/rdkafka.rs
  write_buffer/src/kafka/record_aggregator.rs
Labels: automerge

#5841 refactor: Move http delete parsing code into router along side other http code
  Cargo.lock
  predicate/Cargo.toml
  predicate/src/delete_predicate.rs
  router/Cargo.toml
  router/src/server/http.rs
  router/src/server/http/delete_predicate.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5850 perf(ingester): cheapen table lookup
  ingester/src/data/namespace.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
Labels: kodiak: merge.method = 'merge'

#5851 refactor: include sequence numbers in apply() logs
  ingester/src/stream_handler/handler.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5847 feat: add memory need for output streams into our estimation
  compactor/src/cold.rs
  compactor/src/lib.rs
  compactor/src/parquet_file_filtering.rs
Labels: automerge

#5852 perf(ingester): reduce catalog queries during persist()
  data_types/src/lib.rs
  ingester/src/compact.rs
  ingester/src/data.rs
  ingester/src/data/namespace.rs
  ingester/src/data/partition.rs
  ingester/src/data/partition/resolver/cache.rs
  ingester/src/data/partition/resolver/catalog.rs
  ingester/src/data/partition/resolver/mock.rs
  ingester/src/data/partition/resolver/trait.rs
  ingester/src/data/table.rs
  ingester/src/test_util.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5849 test: Add verification that aspects of L1 -> L2 compaction are working as expected
  compactor/src/cold.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5855 chore: Update datafusion again
  Cargo.lock
  compactor/src/parquet_file_combining.rs
  datafusion/Cargo.toml
  datafusion_util/src/lib.rs
  generated_types/src/ingester.rs
  ingester/src/querier_handler.rs
  iox_query/src/exec.rs
  iox_query/src/exec/context.rs
  iox_query/src/exec/non_null_checker.rs
  iox_query/src/exec/schema_pivot.rs
  iox_query/src/exec/split.rs
  iox_query/src/frontend/common.rs
  iox_query/src/frontend/influxrpc.rs
  iox_query/src/frontend/reorg.rs
  iox_query/src/plan/fieldlist.rs
  iox_query/src/plan/seriesset.rs
  iox_query/src/plan/stringset.rs
  iox_query/src/provider.rs
  iox_query/src/pruning.rs
  iox_query/src/util.rs
  predicate/src/delete_expr.rs
  predicate/src/delete_predicate.rs
  predicate/src/lib.rs
  predicate/src/rpc_predicate.rs
  predicate/src/rpc_predicate/column_rewrite.rs
  predicate/src/rpc_predicate/field_rewrite.rs
  predicate/src/rpc_predicate/measurement_rewrite.rs
  predicate/src/rpc_predicate/rewrite.rs
  predicate/src/rpc_predicate/value_rewrite.rs
  querier/src/system_tables/mod.rs
  querier/src/table/query_access/mod.rs
  query_functions/src/group_by.rs
  query_functions/src/lib.rs
  query_functions/src/regex.rs
  query_functions/src/registry.rs
  query_functions/src/selectors.rs
  query_tests/cases/in/pushdown.expected
  query_tests/src/influxrpc/field_columns.rs
  query_tests/src/influxrpc/read_filter.rs
  query_tests/src/influxrpc/table_names.rs
  query_tests/src/influxrpc/tag_keys.rs
  query_tests/src/influxrpc/tag_values.rs
  query_tests/src/influxrpc/util.rs
  read_buffer/src/column/cmp.rs
  read_buffer/src/row_group.rs
  service_grpc_influxrpc/src/expr.rs
  service_grpc_influxrpc/src/service.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5796 feat: AST traversal using Visitor pattern
  Cargo.lock
  Cargo.toml
  influxdb_influxql_parser/Cargo.toml
  influxdb_influxql_parser/src/common.rs
  influxdb_influxql_parser/src/delete.rs
  influxdb_influxql_parser/src/drop.rs
  influxdb_influxql_parser/src/explain.rs
  influxdb_influxql_parser/src/expression.rs
  influxdb_influxql_parser/src/expression/arithmetic.rs
  influxdb_influxql_parser/src/expression/conditional.rs
  influxdb_influxql_parser/src/expression/test_util.rs
  influxdb_influxql_parser/src/identifier.rs
  influxdb_influxql_parser/src/internal.rs
  influxdb_influxql_parser/src/keywords.rs
  influxdb_influxql_parser/src/lib.rs
  influxdb_influxql_parser/src/literal.rs
  influxdb_influxql_parser/src/parameter.rs
  influxdb_influxql_parser/src/select.rs
  influxdb_influxql_parser/src/show.rs
  influxdb_influxql_parser/src/show_field_keys.rs
  influxdb_influxql_parser/src/show_measurements.rs
  influxdb_influxql_parser/src/show_retention_policies.rs
  influxdb_influxql_parser/src/show_tag_keys.rs
  influxdb_influxql_parser/src/show_tag_values.rs
  influxdb_influxql_parser/src/simple_from_clause.rs
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__delete_statement-2.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__delete_statement-3.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__delete_statement-4.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__delete_statement.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__drop_measurement_statement.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__explain_statement.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__select_statement-2.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__select_statement-3.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__select_statement-4.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__select_statement-5.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__select_statement-6.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__select_statement.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__show_databases_statement.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__show_field_keys_statement-2.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__show_field_keys_statement-3.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__show_field_keys_statement-4.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__show_field_keys_statement.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__show_measurements_statement-2.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__show_measurements_statement-3.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__show_measurements_statement-4.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__show_measurements_statement-5.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__show_measurements_statement-6.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__show_measurements_statement-7.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__show_measurements_statement.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__show_retention_policies_statement-2.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__show_retention_policies_statement.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__show_tag_keys_statement-2.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__show_tag_keys_statement.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__show_tag_values_statement-2.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__show_tag_values_statement-3.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__show_tag_values_statement-4.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__show_tag_values_statement.snap
  influxdb_influxql_parser/src/string.rs
  influxdb_influxql_parser/src/visit.rs
  workspace-hack/Cargo.toml
Labels: automerge, influxql

#5819 feat: Enforce table column limits from the schema cache
  Cargo.lock
  data_types/src/lib.rs
  import/src/aggregate_tsm_schema/update_catalog.rs
  ingester/src/data.rs
  ingester/src/handler.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_tests/src/util.rs
  mutable_batch/src/lib.rs
  router/Cargo.toml
  router/src/dml_handlers/ns_autocreation.rs
  router/src/dml_handlers/schema_validation.rs
  router/src/namespace_cache/memory.rs
  router/src/namespace_cache/metrics.rs
  router/src/namespace_cache/sharded_cache.rs
  router/tests/http.rs
Labels: automerge

#5854 fix: only emit ttbr metric for applied ops
  ingester/src/data.rs
  ingester/src/data/namespace.rs
  ingester/src/data/shard.rs
  ingester/src/data/table.rs
  ingester/src/stream_handler/handler.rs
  ingester/src/stream_handler/mock_sink.rs
  ingester/src/stream_handler/sink.rs
  ingester/src/stream_handler/sink_adaptor.rs
  ingester/src/stream_handler/sink_instrumentation.rs
  query_tests/src/scenarios/util.rs
Labels: automerge

#5860 refactor(iox_catalog): reduce default column limit
  iox_catalog/migrations/20221014122742_lower-default-per-table-column-limit.sql
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
  router/src/dml_handlers/ns_autocreation.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5859 fix: Use Display rather than Debug when logging errors
  compactor/src/lib.rs
  ingester/src/server/grpc.rs
  service_grpc_flight/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5865 feat: Log object store configuration on startup
  clap_blocks/src/object_store.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5862 refactor: return HTTP 400 for service limits
  router/src/server/http.rs
  router/tests/http.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5857 fix: Address InfluxQL parsing issues
  Cargo.lock
  influxdb_influxql_parser/Cargo.toml
  influxdb_influxql_parser/src/common.rs
  influxdb_influxql_parser/src/delete.rs
  influxdb_influxql_parser/src/drop.rs
  influxdb_influxql_parser/src/explain.rs
  influxdb_influxql_parser/src/expression/arithmetic.rs
  influxdb_influxql_parser/src/expression/conditional.rs
  influxdb_influxql_parser/src/keywords.rs
  influxdb_influxql_parser/src/literal.rs
  influxdb_influxql_parser/src/select.rs
  influxdb_influxql_parser/src/show.rs
  influxdb_influxql_parser/src/show_field_keys.rs
  influxdb_influxql_parser/src/show_measurements.rs
  influxdb_influxql_parser/src/show_retention_policies.rs
  influxdb_influxql_parser/src/show_tag_keys.rs
  influxdb_influxql_parser/src/show_tag_values.rs
  influxdb_influxql_parser/src/simple_from_clause.rs
Labels: automerge, influxql

#5870 chore: update deps that dependabot cannot handle
  Cargo.lock
  workspace-hack/Cargo.toml
Labels: automerge

#5871 revert: rdkafka/rskafka swapping (#5844)
  Cargo.lock
  clap_blocks/src/write_buffer.rs
  write_buffer/Cargo.toml
  write_buffer/src/config.rs
  write_buffer/src/core.rs
  write_buffer/src/kafka/instrumentation.rs
  write_buffer/src/kafka/mod.rs
  write_buffer/src/kafka/rdkafka.rs
  write_buffer/src/kafka/record_aggregator.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5869 chore: update datafusion
  Cargo.lock
  datafusion/Cargo.toml
  datafusion_util/src/lib.rs
  predicate/src/lib.rs
  predicate/src/rpc_predicate.rs
  predicate/src/rpc_predicate/field_rewrite.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5868 docs: compactor document and how to resolve OOMs
  docs/compactor.md
Labels: automerge

#5873 feat: harden and polish backoff system
  backoff/src/lib.rs
Labels: automerge

#5879 feat: read from parquet and only parquet
  ioxd_querier/src/lib.rs
  ioxd_querier/src/rpc/namespace.rs
  querier/src/chunk/mod.rs
  querier/src/database.rs
  querier/src/handler.rs
  querier/src/namespace/mod.rs
  querier/src/namespace/test_util.rs
  querier/src/table/test_util.rs
  query_tests/src/scenarios/util.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5888 refactor: remove querier chunk load settings
  querier/src/cache/mod.rs
  querier/src/cache/read_buffer.rs
  querier/src/chunk/mod.rs
  querier/src/chunk/query_access.rs
  querier/src/database.rs
  querier/src/lib.rs
  querier/src/namespace/mod.rs
  querier/src/namespace/test_util.rs
  querier/src/table/mod.rs
  querier/src/table/test_util.rs
  query_tests/src/scenarios/util.rs
Labels: automerge

#5877 feat: add more logging to SQL execution via flight
  service_grpc_flight/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5864 fix: improve tonic status codes returned for query errors
  Cargo.lock
  service_common/Cargo.toml
  service_common/src/error.rs
  service_common/src/lib.rs
  service_grpc_flight/src/lib.rs
  service_grpc_influxrpc/src/service.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5890 refactor: remove querier dual chunk stage
  Cargo.lock
  querier/Cargo.toml
  querier/src/chunk/mod.rs
  querier/src/chunk/query_access.rs
Labels: automerge

#5891 refactor: remove read buffer
  Cargo.lock
  Cargo.toml
  read_buffer/Cargo.toml
  read_buffer/benches/database.rs
  read_buffer/benches/plain.rs
  read_buffer/benches/read.rs
  read_buffer/benches/read_filter.rs
  read_buffer/benches/read_group.rs
  read_buffer/benches/string.rs
  read_buffer/benches/sum_fixed.rs
  read_buffer/src/chunk.rs
  read_buffer/src/column.rs
  read_buffer/src/column/boolean.rs
  read_buffer/src/column/cmp.rs
  read_buffer/src/column/encoding.rs
  read_buffer/src/column/encoding/bool.rs
  read_buffer/src/column/encoding/scalar.rs
  read_buffer/src/column/encoding/scalar/fixed.rs
  read_buffer/src/column/encoding/scalar/fixed_null.rs
  read_buffer/src/column/encoding/scalar/rle.rs
  read_buffer/src/column/encoding/scalar/transcoders.rs
  read_buffer/src/column/encoding/string.rs
  read_buffer/src/column/encoding/string/dictionary.rs
  read_buffer/src/column/encoding/string/rle.rs
  read_buffer/src/column/float.rs
  read_buffer/src/column/integer.rs
  read_buffer/src/column/string.rs
  read_buffer/src/lib.rs
  read_buffer/src/metrics.rs
  read_buffer/src/row_group.rs
  read_buffer/src/schema.rs
  read_buffer/src/table.rs
  read_buffer/src/value.rs
Labels: automerge

#5895 refactor: use histogram to record TTBR
  ingester/src/stream_handler/handler.rs
Labels: kodiak: merge.method = 'merge'

#5893 refactor: remove old `packers` crate
  Cargo.lock
  Cargo.toml
  packers/Cargo.toml
  packers/benches/packers.rs
  packers/src/lib.rs
  packers/src/packers.rs
  packers/src/sorter.rs
  packers/src/stats.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5876 fix: Return an error for unsupported SQL queries
  influxdb_iox/tests/end_to_end_cases/cli.rs
  influxdb_iox/tests/end_to_end_cases/querier.rs
  influxdb_iox_client/src/client/flight/mod.rs
  iox_query/src/exec/context.rs
  test_helpers_end_to_end/src/steps.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5900 chore: Update datafusion and arrow / parquet / arrow-flight 25.0.0
  Cargo.lock
  arrow_util/Cargo.toml
  compactor/Cargo.toml
  datafusion/Cargo.toml
  influxdb_iox/Cargo.toml
  influxdb_iox_client/Cargo.toml
  ingester/Cargo.toml
  iox_query/Cargo.toml
  iox_query/src/util.rs
  iox_tests/Cargo.toml
  ioxd_querier/Cargo.toml
  mutable_batch/Cargo.toml
  parquet_file/Cargo.toml
  predicate/Cargo.toml
  predicate/src/delete_expr.rs
  predicate/src/delete_predicate.rs
  predicate/src/lib.rs
  predicate/src/rpc_predicate/rewrite.rs
  querier/Cargo.toml
  query_functions/Cargo.toml
  query_tests/Cargo.toml
  query_tests/cases/in/pushdown.expected
  schema/Cargo.toml
  service_grpc_flight/Cargo.toml
  service_grpc_influxrpc/Cargo.toml
  test_helpers_end_to_end/Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#5907 refactor: prep work for #5897
  Cargo.lock
  compactor/src/cold.rs
  compactor/src/compact.rs
  compactor/src/hot.rs
  compactor/src/lib.rs
  compactor/src/parquet_file_combining.rs
  compactor/src/query.rs
  ingester/src/data.rs
  iox_tests/Cargo.toml
  iox_tests/src/util.rs
  ioxd_compactor/src/lib.rs
  parquet_file/src/storage.rs
  parquet_file/tests/metadata.rs
  querier/src/chunk/mod.rs
Labels: automerge

#5908 test: ingester integration tests
  ingester/src/handler.rs
  ingester/src/lifecycle.rs
  ingester/src/querier_handler.rs
  ingester/src/stream_handler/handler.rs
  ingester/tests/common/mod.rs
  ingester/tests/write.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5911 refactor: use `SendableRecordBatchStream` to write parquets
  Cargo.lock
  iox_data_generator/Cargo.toml
  iox_data_generator/src/write.rs
  iox_tests/Cargo.toml
  iox_tests/src/util.rs
  parquet_file/src/metadata.rs
  parquet_file/src/serialize.rs
  parquet_file/src/storage.rs
  parquet_file/tests/metadata.rs
Labels: automerge

#5913 fix: reduce verbosity from `INFO querier::ingester: Time spent in ...` to `DEBUG`
  querier/src/ingester/mod.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5918 refactor: remove outdated observer sql repl mode
  docs/sql.md
  influxdb_iox/src/commands/sql.rs
  influxdb_iox/src/commands/sql/observer.rs
  influxdb_iox/src/commands/sql/repl.rs
  influxdb_iox/src/commands/sql/repl_command.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5919 feat: support queries via influxrpc with periods in field names
  datafusion_util/src/lib.rs
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/read_filter.rs
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/read_group.rs
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/read_window_aggregate.rs
  iox_query/src/frontend/influxrpc.rs
  query_tests/src/influxrpc/field_columns.rs
  query_tests/src/influxrpc/read_filter.rs
  query_tests/src/influxrpc/read_group.rs
  query_tests/src/influxrpc/read_window_aggregate.rs
  query_tests/src/influxrpc/table_names.rs
  query_tests/src/influxrpc/tag_keys.rs
  query_tests/src/influxrpc/tag_values.rs
  query_tests/src/scenarios/library.rs
  service_grpc_influxrpc/Cargo.toml
  service_grpc_influxrpc/src/expr.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5909 fix: improve ttbr histogram metric description
  ingester/src/stream_handler/handler.rs
Labels: automerge

#5916 feat: Add debug/tracing logging into influxrpc_storage_client
  Cargo.lock
  influxdb_storage_client/Cargo.toml
  influxdb_storage_client/src/lib.rs
Labels: automerge

#5915 fix: improve error message for storage read group command
  influxdb_iox/src/commands/storage.rs
Labels: automerge

#5912 fix: use structured errors for logging influxrpc errors
  service_grpc_influxrpc/src/service.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5910 refactor: replace `croaring` with `arrow`
  .cargo/config
  Cargo.lock
  README.md
  iox_query/Cargo.toml
  iox_query/src/exec/seriesset/converter.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#5926 fix: Add comments about rationale and context for headers
  service_grpc_influxrpc/src/service.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5927 refactor: arrow API usage cleanup
  iox_query/src/exec/seriesset/converter.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5920 feat: Pass trace id through Flight requests from querier to ingester
  Cargo.lock
  client_util/src/tower.rs
  influxdb_iox/src/commands/query_ingester.rs
  influxdb_iox/tests/end_to_end_cases/ingester.rs
  influxdb_iox_client/Cargo.toml
  influxdb_iox_client/src/client/flight/low_level.rs
  influxdb_iox_client/src/client/flight/mod.rs
  ingester/src/handler.rs
  ingester/src/querier_handler.rs
  ingester/src/server/grpc.rs
  ingester/tests/common/mod.rs
  querier/src/ingester/flight_client.rs
  querier/src/ingester/mod.rs
  query_tests/Cargo.toml
  query_tests/src/scenarios/util.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5943 feat(ingester): partition buffer state machine
  ingester/src/data/partition/buffer/always_some.rs
  ingester/src/data/partition/buffer/mutable_buffer.rs
  ingester/src/data/partition/buffer/state_machine.rs
  ingester/src/data/partition/buffer/state_machine/buffering.rs
  ingester/src/data/partition/buffer/state_machine/buffering_with_snapshot.rs
  ingester/src/data/partition/buffer/state_machine/persisting.rs
  ingester/src/data/partition/buffer/state_machine/snapshot.rs
  ingester/src/data/partition/buffer/traits.rs
  ingester/src/data/sequence_range.rs
Labels: kodiak: merge.method = 'merge'

#5944 refactor: disable incremental snapshot generation
  ingester/src/data/partition/buffer/mutable_buffer.rs
  ingester/src/data/partition/buffer/state_machine.rs
  ingester/src/data/partition/buffer/state_machine/buffering.rs
  ingester/src/data/partition/buffer/state_machine/buffering_with_snapshot.rs
  ingester/src/data/partition/buffer/state_machine/persisting.rs
  ingester/src/data/partition/buffer/state_machine/snapshot.rs
  ingester/src/data/partition/buffer/traits.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5931 feat: Add gRPC and CLI APIs to list skipped compactions
  Cargo.lock
  compactor/Cargo.toml
  compactor/src/handler.rs
  compactor/src/server.rs
  compactor/src/server/grpc.rs
  generated_types/build.rs
  generated_types/protos/influxdata/iox/compactor/v1/service.proto
  generated_types/src/compactor.rs
  generated_types/src/lib.rs
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/debug/mod.rs
  influxdb_iox/src/commands/debug/skipped_compactions.rs
  influxdb_iox_client/src/client.rs
  influxdb_iox_client/src/client/compactor.rs
  ioxd_compactor/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5945 feat: Add gRPC and CLI APIs to delete skipped compactions
  compactor/src/handler.rs
  compactor/src/server/grpc.rs
  generated_types/protos/influxdata/iox/compactor/v1/service.proto
  influxdb_iox/src/commands/debug/skipped_compactions.rs
  influxdb_iox_client/src/client/compactor.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5947 docs: Add skipped-compaction CLI to the compactor documentation
  docs/compactor.md
Labels: automerge, kodiak: merge.method = 'merge'

#5948 fix: Compactor skipped_at is in seconds, not nanoseconds oops
  influxdb_iox/src/commands/debug/skipped_compactions.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5953 fix: textwrap 0.15.1 was yanked
  Cargo.lock
  Cargo.toml
Labels: automerge

#5942 refactor: do NOT use fake DF context for parquet reading
  Cargo.lock
  compactor/src/cold.rs
  compactor/src/compact.rs
  compactor/src/hot.rs
  compactor/src/lib.rs
  compactor/src/query.rs
  influxdb_iox/src/commands/compactor.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/src/commands/run/compactor.rs
  iox_query/Cargo.toml
  iox_query/src/exec.rs
  iox_tests/src/util.rs
  ioxd_compactor/src/lib.rs
  ioxd_querier/src/lib.rs
  parquet_file/src/chunk.rs
  parquet_file/src/storage.rs
  querier/src/cache/mod.rs
  querier/src/chunk/mod.rs
  querier/src/chunk/query_access.rs
  querier/src/namespace/test_util.rs
  query_tests/src/scenarios/util.rs
Labels: automerge

#5955 revert: use histogram to record TTBR
  ingester/src/stream_handler/handler.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5954 refactor: `IOxReadFilterNode` can always accumulate statistics
  influxdb_iox/tests/end_to_end_cases/querier.rs
  iox_query/src/provider/deduplicate.rs
  iox_query/src/provider/physical.rs
  query_tests/cases/in/duplicates_ingester.expected
  query_tests/cases/in/duplicates_ingester.sql
  query_tests/cases/in/duplicates_parquet.expected
  query_tests/cases/in/duplicates_parquet.sql
Labels: automerge

#5946 fix: cardinality of each batch should use row count of the batch
  compactor/src/compact.rs
  compactor/src/handler.rs
  compactor/src/lib.rs
  compactor/src/parquet_file_lookup.rs
Labels: automerge

#5961 refactor: simplify `iox_query::provider::overlap`
  iox_query/src/provider/overlap.rs
Labels: automerge

#5960 refactor: do not project chunks in `TestDatabase::chunks`
  iox_query/src/frontend/influxrpc.rs
  iox_query/src/lib.rs
  iox_query/src/test.rs
Labels: automerge

#5964 refactor: make `SchemaBuilder::field` fallible
  iox_query/src/provider.rs
  iox_query/src/test.rs
  iox_query/src/util.rs
  predicate/src/lib.rs
  predicate/src/rpc_predicate.rs
  predicate/src/rpc_predicate/column_rewrite.rs
  predicate/src/rpc_predicate/field_rewrite.rs
  querier/src/cache/namespace.rs
  querier/src/chunk/mod.rs
  querier/src/ingester/mod.rs
  query_tests/src/table_schema.rs
  schema/src/builder.rs
  schema/src/lib.rs
  schema/src/merge.rs
  service_grpc_influxrpc/src/expr.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5971 chore: unpatch clap V3
  Cargo.lock
  Cargo.toml
Labels: automerge

#5972 refactor: enforce nullability for (known) IOx data types
  schema/src/builder.rs
  schema/src/lib.rs
  schema/src/merge.rs
Labels: automerge

#5973 chore: temporarily disable circle filter to build & push PRs
  .circleci/config.yml
Labels: automerge

#5810 feat: build a query plan without deduplication
  iox_query/src/frontend.rs
  iox_query/src/frontend/common.rs
  iox_query/src/provider.rs
Labels: automerge

#5979 refactor: parse HTTP trace header even w/o collector
  trace/src/ctx.rs
  trace_http/src/ctx.rs
  trace_http/src/tower.rs
  write_buffer/src/codec.rs
Labels: automerge

#5978 refactor: make influx column type mandatory in Schema
  arrow_util/src/optimize.rs
  data_types/src/lib.rs
  iox_query/src/frontend/influxrpc.rs
  iox_query/src/lib.rs
  iox_query/src/provider.rs
  iox_query/src/statistics.rs
  iox_query/src/test.rs
  parquet_file/src/metadata.rs
  parquet_file/tests/metadata.rs
  parquet_to_line_protocol/src/batch.rs
  predicate/src/lib.rs
  querier/src/chunk/util.rs
  query_tests/src/scenarios/util.rs
  schema/src/builder.rs
  schema/src/lib.rs
  schema/src/merge.rs
Labels: automerge

#5976 chore: Update datafusion and other dependencies
  Cargo.lock
  datafusion/Cargo.toml
  query_tests/cases/in/pushdown.expected
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#5968 feat: Use workspace dep inheritance for arrow crates
  Cargo.lock
  Cargo.toml
  arrow_util/Cargo.toml
  compactor/Cargo.toml
  datafusion/Cargo.toml
  datafusion/src/lib.rs
  datafusion_util/Cargo.toml
  generated_types/Cargo.toml
  generated_types/src/ingester.rs
  influxdb_iox/Cargo.toml
  influxdb_iox_client/Cargo.toml
  ingester/Cargo.toml
  iox_query/Cargo.toml
  iox_tests/Cargo.toml
  ioxd_querier/Cargo.toml
  mutable_batch/Cargo.toml
  parquet_file/Cargo.toml
  parquet_to_line_protocol/Cargo.toml
  predicate/Cargo.toml
  querier/Cargo.toml
  query_functions/Cargo.toml
  query_tests/Cargo.toml
  schema/Cargo.toml
  scripts/update_arrow_deps.py
  service_common/Cargo.toml
  service_grpc_flight/Cargo.toml
  service_grpc_influxrpc/Cargo.toml
  test_helpers_end_to_end/Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'merge'

#5983 feat: allow deploys to set Kafka client ID
  Cargo.lock
  write_buffer/Cargo.toml
  write_buffer/src/kafka/config.rs
  write_buffer/src/kafka/mod.rs
Labels: automerge

#5980 feat: log cancelled HTTP/gRPC requests
  trace_http/src/ctx.rs
  trace_http/src/tower.rs
Labels: automerge

#5988 fix: update rskafka to support throttling
  Cargo.lock
  write_buffer/Cargo.toml
Labels: automerge

#5982 refactor: enforce name of the one-and-only time column
  schema/src/builder.rs
  schema/src/lib.rs
Labels: automerge

#5984 feat: MVP of remote store get-table command
  generated_types/protos/influxdata/iox/catalog/v1/service.proto
  influxdb_iox/src/commands/remote.rs
  influxdb_iox/src/commands/remote/store.rs
  influxdb_iox/tests/end_to_end_cases/cli.rs
  influxdb_iox/tests/end_to_end_cases/mod.rs
  influxdb_iox/tests/end_to_end_cases/remote.rs
  influxdb_iox_client/src/client/catalog.rs
  service_grpc_catalog/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5990 feat: Some bonus features for `remote store get-table`
  generated_types/protos/influxdata/iox/catalog/v1/service.proto
  influxdb_iox/src/commands/remote.rs
  influxdb_iox/src/commands/remote/store.rs
  influxdb_iox/tests/end_to_end_cases/remote.rs
  influxdb_iox_client/src/client/catalog.rs
  influxdb_iox_client/src/client/error.rs
  service_grpc_catalog/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5958 refactor(ingester): use partition buffer FSM
  Cargo.lock
  ingester/Cargo.toml
  ingester/src/compact.rs
  ingester/src/data.rs
  ingester/src/data/namespace.rs
  ingester/src/data/partition.rs
  ingester/src/data/partition/buffer.rs
  ingester/src/data/partition/buffer/always_some.rs
  ingester/src/data/partition/buffer/state_machine.rs
  ingester/src/data/partition/buffer/state_machine/buffering.rs
  ingester/src/data/partition/resolver/catalog.rs
  ingester/src/data/sequence_range.rs
  ingester/src/data/table.rs
  ingester/src/lib.rs
  ingester/src/querier_handler.rs
  ingester/src/query_adaptor.rs
  ingester/src/test_util.rs
  iox_query/src/provider.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5992 refactor: Simplify manipulations of BooleanArray
  iox_query/src/exec/seriesset/converter.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5993 chore: Keep types in their respective modules
  influxdb_influxql_parser/src/common.rs
  influxdb_influxql_parser/src/delete.rs
  influxdb_influxql_parser/src/drop.rs
  influxdb_influxql_parser/src/explain.rs
  influxdb_influxql_parser/src/expression.rs
  influxdb_influxql_parser/src/lib.rs
  influxdb_influxql_parser/src/literal.rs
  influxdb_influxql_parser/src/select.rs
  influxdb_influxql_parser/src/show.rs
  influxdb_influxql_parser/src/show_field_keys.rs
  influxdb_influxql_parser/src/show_measurements.rs
  influxdb_influxql_parser/src/show_retention_policies.rs
  influxdb_influxql_parser/src/show_tag_keys.rs
  influxdb_influxql_parser/src/show_tag_values.rs
  influxdb_influxql_parser/src/simple_from_clause.rs
  influxdb_influxql_parser/src/statement.rs
  influxdb_influxql_parser/src/visit.rs
Labels: automerge, kodiak: merge.method = 'squash', influxql

#5963 refactor: remove `QueryChunkMeta::timestamp_min_max`
  compactor/src/query.rs
  ingester/src/query_adaptor.rs
  iox_query/src/lib.rs
  iox_query/src/provider/overlap.rs
  iox_query/src/test.rs
  iox_query/src/util.rs
  querier/src/chunk/mod.rs
  querier/src/chunk/query_access.rs
  querier/src/chunk/util.rs
  querier/src/ingester/mod.rs
  querier/src/ingester/test_util.rs
  querier/src/table/mod.rs
Labels: automerge

#5996 refactor(dml): PartitionKey required for writes
  dml/src/lib.rs
  ingester/src/data.rs
  ingester/src/data/namespace.rs
  ingester/src/handler.rs
  ingester/src/stream_handler/handler.rs
  ingester/src/stream_handler/sink_instrumentation.rs
  ingester/src/test_util.rs
  ingester/tests/common/mod.rs
  mutable_batch_pb/src/encode.rs
  mutable_batch_tests/benches/write_pb.rs
  query_tests/src/scenarios/util.rs
  router/src/dml_handlers/sharded_write_buffer.rs
  write_buffer/src/codec.rs
  write_buffer/src/core.rs
  write_buffer/src/kafka/mod.rs
  write_buffer/src/kafka/record_aggregator.rs
  write_buffer/src/mock.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5991 feat: Last 2 bonus features of remote store get-table
  Cargo.lock
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/remote/store.rs
  influxdb_iox/tests/end_to_end_cases/remote.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#5989 feat: Log how long each persist plan takes to complete
  ingester/src/data.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6005 feat: Add the catalog service to ingester, querier, and compactor
  Cargo.lock
  compactor/Cargo.toml
  compactor/src/server.rs
  compactor/src/server/grpc.rs
  ingester/Cargo.toml
  ingester/src/server.rs
  ingester/src/server/grpc.rs
  ioxd_compactor/src/lib.rs
  ioxd_ingester/src/lib.rs
  ioxd_querier/src/lib.rs
  querier/Cargo.toml
  querier/src/handler.rs
  router/Cargo.toml
  service_grpc_catalog/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6004 chore: Update datafusion
  Cargo.lock
  Cargo.toml
  iox_query/src/util.rs
  predicate/src/rpc_predicate.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#5997 refactor: mandatory `QueryChunkMeta::summary`
  compactor/src/query.rs
  ingester/src/query_adaptor.rs
  iox_query/src/lib.rs
  iox_query/src/provider/overlap.rs
  iox_query/src/provider/physical.rs
  iox_query/src/pruning.rs
  iox_query/src/test.rs
  querier/src/chunk/mod.rs
  querier/src/chunk/query_access.rs
  querier/src/ingester/mod.rs
  querier/src/table/mod.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6010 chore: Update datafusion pin... again
  Cargo.lock
  Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#6011 refactor: move `SessionConfig` creation into `datafusion_utils`
  datafusion_util/src/config.rs
  datafusion_util/src/lib.rs
  iox_query/src/exec.rs
  iox_query/src/exec/context.rs
  iox_query/src/lib.rs
  parquet_file/src/serialize.rs
  parquet_file/src/storage.rs
  querier/src/namespace/query_access.rs
Labels: automerge, kodiak: merge.method = 'squash'
