Repository influxdata/influxdb_iox, pull requests merged in 2022-09, with the labels that each got.

#5522 refactor: use concrete inner type in `CacheWithMetrics`
  cache_system/src/cache/metrics.rs
  cache_system/src/cache/mod.rs
  querier/src/cache/namespace.rs
  querier/src/cache/parquet_file.rs
  querier/src/cache/partition.rs
  querier/src/cache/processed_tombstones.rs
  querier/src/cache/projected_schema.rs
  querier/src/cache/read_buffer.rs
  querier/src/cache/tombstones.rs
Labels: automerge

#5473 feat: Implement gRPC binary logger
  Cargo.lock
  Cargo.toml
  grpc-binary-logger-proto/Cargo.toml
  grpc-binary-logger-proto/build.rs
  grpc-binary-logger-proto/proto/grpc/binlog/v1/binarylog.proto
  grpc-binary-logger-proto/src/lib.rs
  grpc-binary-logger-test-proto/Cargo.toml
  grpc-binary-logger-test-proto/build.rs
  grpc-binary-logger-test-proto/proto/test.proto
  grpc-binary-logger-test-proto/src/lib.rs
  grpc-binary-logger/Cargo.toml
  grpc-binary-logger/examples/README.md
  grpc-binary-logger/examples/client.rs
  grpc-binary-logger/examples/server.rs
  grpc-binary-logger/src/lib.rs
  grpc-binary-logger/src/middleware.rs
  grpc-binary-logger/src/predicate.rs
  grpc-binary-logger/src/sink.rs
  grpc-binary-logger/tests/end_to_end.rs
  grpc-binary-logger/tests/end_to_end_cases/mod.rs
  grpc-binary-logger/tests/end_to_end_cases/server.rs
  grpc-binary-logger/tests/end_to_end_cases/test_utils.rs
  grpc-binary-logger/tests/end_to_end_cases/tests.rs
Labels: automerge

#5525 refactor: use concrete type in `MetricsLoader`
  cache_system/src/loader/metrics.rs
  cache_system/src/loader/mod.rs
  querier/src/cache/namespace.rs
  querier/src/cache/parquet_file.rs
  querier/src/cache/partition.rs
  querier/src/cache/processed_tombstones.rs
  querier/src/cache/projected_schema.rs
  querier/src/cache/read_buffer.rs
  querier/src/cache/tombstones.rs
Labels: automerge

#5530 refactor: do not always box `FunctionLoader`
  cache_system/src/loader/mod.rs
Labels: automerge

#5475 feat: database rename
  data_types/src/lib.rs
  iox_catalog/migrations/20220819154515_sequencer_to_shard.sql
  iox_catalog/src/interface.rs
  iox_catalog/src/postgres.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5535 feat: make compactors to select candidates based on the last n minutes
  compactor/src/compact.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
Labels: automerge

#5534 test: Refactor and add some more compactor tests
  compactor/src/compact_hot_partitions.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5469 feat: Implementation of expression parsing for InfluxQL
  influxdb_influxql_parser/src/expression.rs
  influxdb_influxql_parser/src/keywords.rs
  influxdb_influxql_parser/src/lib.rs
  influxdb_influxql_parser/src/literal.rs
  influxdb_influxql_parser/src/parameter.rs
  influxdb_influxql_parser/src/string.rs
  influxdb_influxql_parser/src/test_util.rs
Labels: automerge, influxql

#5533 fix: Improve debugging ability for influxdb2_client
  influxdb2_client/src/api/query.rs
  influxdb2_client/src/lib.rs
Labels: automerge

#5527 feat: querier object store cache
  Cargo.lock
  ioxd_querier/src/lib.rs
  ioxd_querier/src/rpc/namespace.rs
  querier/Cargo.toml
  querier/src/cache/mod.rs
  querier/src/cache/object_store.rs
  querier/src/chunk/mod.rs
  querier/src/database.rs
  querier/src/handler.rs
  querier/src/ingester/mod.rs
  querier/src/namespace/test_util.rs
  querier/src/table/test_util.rs
  query_tests/src/scenarios/util.rs
Labels: automerge

#5542 chore: upgrade jemalloc to version 5.3.0
  Cargo.lock
  influxdb_iox/Cargo.toml
  ioxd_common/Cargo.toml
Labels: automerge

#5543 chore: Add test for running a query after swapping out a sqlx pool
  sqlx-hotswap-pool/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5532 refactor: use concrete loader type within `CacheDriver`
  cache_system/src/cache/driver.rs
  cache_system/src/cache/metrics.rs
  cache_system/src/loader/mod.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5544 feat: add index on parquet_file(shard_id, compaction_level, to_delete, created_at)
  iox_catalog/migrations/20220902145700_compactor_index.sql
Labels: automerge

#5547 fix: remove timestamp functions from SQLs to be able to use index for improving performance
  compactor/src/compact.rs
  compactor/src/compact_hot_partitions.rs
  compactor/src/handler.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
Labels: automerge

#5541 refactor: fine-grained file size mocking
  compactor/src/compact_hot_partitions.rs
  compactor/src/handler.rs
  compactor/src/lib.rs
  compactor/src/parquet_file.rs
  compactor/src/parquet_file_combining.rs
  compactor/src/parquet_file_filtering.rs
  compactor/src/parquet_file_lookup.rs
  iox_tests/src/util.rs
  querier/src/namespace/query_access.rs
Labels: automerge

#5531 refactor: use DataFusion to read parquet files
  compactor/src/lib.rs
  compactor/src/parquet_file_combining.rs
  parquet_file/src/chunk.rs
  parquet_file/src/storage.rs
  querier/src/cache/read_buffer.rs
Labels: automerge

#5559 chore: update `cpufeatures` to 0.2.5
  Cargo.lock
Labels: automerge

#5553 refactor: debug log improvements
  ingester/src/server/grpc.rs
  querier/src/cache/parquet_file.rs
  querier/src/chunk/query_access.rs
  querier/src/ingester/mod.rs
Labels: automerge

#5430 feat: Teach IOx to parse `SHOW MEASUREMENTS` statement
  influxdb_influxql_parser/src/common.rs
  influxdb_influxql_parser/src/expression.rs
  influxdb_influxql_parser/src/identifier.rs
  influxdb_influxql_parser/src/lib.rs
  influxdb_influxql_parser/src/show_measurements.rs
  influxdb_influxql_parser/src/string.rs
Labels: automerge, influxql

#5563 refactor: remove the write_buffer crate dependency from ioxd_querier
  Cargo.lock
  ioxd_querier/Cargo.toml
  ioxd_querier/src/lib.rs
Labels: automerge

#5568 refactor: do not always box `FunctionEstimator` function
  cache_system/src/backend/policy/integration_tests.rs
  cache_system/src/backend/policy/lru.rs
  cache_system/src/resource_consumption.rs
Labels: automerge

#5569 ci: fix
  .circleci/config.yml
  Cargo.lock
  backoff/Cargo.toml
  cache_system/Cargo.toml
  client_util/Cargo.toml
  compactor/Cargo.toml
  datafusion_util/Cargo.toml
  executor/Cargo.toml
  executor/src/lib.rs
  influxdb2_client/Cargo.toml
  influxdb_iox/Cargo.toml
  influxdb_iox_client/Cargo.toml
  ingester/Cargo.toml
  iox_catalog/Cargo.toml
  iox_data_generator/Cargo.toml
  iox_query/Cargo.toml
  iox_time/Cargo.toml
  ioxd_common/Cargo.toml
  ioxd_querier/Cargo.toml
  ioxd_router/Cargo.toml
  object_store_metrics/Cargo.toml
  parquet_file/Cargo.toml
  querier/Cargo.toml
  query_functions/Cargo.toml
  query_tests/Cargo.toml
  service_grpc_flight/Cargo.toml
  service_grpc_influxrpc/Cargo.toml
  sqlx-hotswap-pool/Cargo.toml
  test_helpers_end_to_end/Cargo.toml
  trace_exporters/Cargo.toml
  tracker/Cargo.toml
  workspace-hack/Cargo.toml
  write_buffer/Cargo.toml
Labels: automerge

#5551 chore: fix comment typo
  data_types/src/lib.rs
  docs/profiling.md
  executor/src/lib.rs
  generated_types/protos/influxdata/iox/ingester/v1/write_info.proto
  influxdb_iox/src/commands/sql/observer.rs
  influxdb_tsm/src/key.rs
  ingester/src/compact.rs
  ingester/src/data.rs
  ingester/src/test_util.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
  iox_query/src/exec/fieldlist.rs
  iox_query/src/exec/schema_pivot.rs
  iox_tests/src/util.rs
  ioxd_common/src/http/dml.rs
  predicate/src/rewrite.rs
  querier/src/ingester/mod.rs
  querier/src/table/state_reconciler.rs
  schema/src/lib.rs
  test_helpers_end_to_end/src/udp_listener.rs
Labels: automerge

#5550 chore: fix comment typo
  iox_query/src/provider.rs
Labels: automerge

#5562 refactor: avoid double-hash in `AddessableHeap::insert`
  cache_system/src/addressable_heap.rs
Labels: automerge

#5575 fix(ingester): connect to assigned Kafka partitions
  clap_blocks/src/write_buffer.rs
  ioxd_ingester/src/lib.rs
  ioxd_router/src/lib.rs
  write_buffer/src/config.rs
  write_buffer/src/kafka/mod.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5576 perf: use rskafka producer optimisations
  Cargo.lock
  write_buffer/Cargo.toml
  write_buffer/src/kafka/instrumentation.rs
  write_buffer/src/kafka/mod.rs
  write_buffer/src/kafka/record_aggregator.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5578 chore: update to pprof 0.10.1
  Cargo.lock
  ioxd_common/Cargo.toml
Labels: automerge

#5574 chore: `cargo update`
  Cargo.lock
  iox_time/Cargo.toml
Labels: automerge

#5582 fix: support `u64` in `query_functions::selectors`
  query_functions/src/selectors.rs
  query_functions/src/selectors/internal.rs
Labels: automerge

#5580 chore: `cargo update`
  Cargo.lock
  workspace-hack/Cargo.toml
Labels: automerge

#5536 refactor: Prepare for sharing some code between hot and cold compaction
  compactor/src/compact.rs
  compactor/src/compact_hot_partitions.rs
  compactor/src/handler.rs
  compactor/src/lib.rs
  iox_tests/src/util.rs
  ioxd_compactor/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5581 chore: update `tracing-subscriber`, fix trogging, fix CLI test port allocation
  Cargo.lock
  influxdb_iox/tests/end_to_end_cases/cli.rs
  test_helpers_end_to_end/src/lib.rs
  test_helpers_end_to_end/src/server_type.rs
  trogging/src/lib.rs
  workspace-hack/Cargo.toml
Labels: automerge

#5577 refactor: avoid double-hash when updating addressable heap orders
  cache_system/benches/addressable_heap.rs
  cache_system/src/addressable_heap.rs
  cache_system/src/backend/policy/lru.rs
Labels: automerge

#5603 revert: disable read buffer usage in querier (#5579)
  ioxd_querier/src/lib.rs
  ioxd_querier/src/rpc/namespace.rs
  querier/src/chunk/mod.rs
  querier/src/database.rs
  querier/src/handler.rs
  querier/src/namespace/mod.rs
  querier/src/namespace/test_util.rs
  querier/src/table/test_util.rs
  query_tests/src/scenarios/util.rs
Labels: automerge

#5594 fix: remove unnecessary warning
  parquet_file/src/serialize.rs
Labels: automerge

#5592 refactor: allocate more accurate length for a hashmap
  compactor/src/compact.rs
Labels: automerge

#5540 docs: Update instructions for protoc install
  README.md
Labels: automerge

#5605 fix: update comments
  query_functions/src/selectors.rs
Labels: automerge

#5607 feat: Record skipped compactions in memory
  compactor/src/compact_hot_partitions.rs
  data_types/src/lib.rs
  iox_catalog/migrations/20220909140048_create_skipped_compactions.sql
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5600 chore: Allow running all-in-one with external object store
  influxdb_iox/src/commands/run/all_in_one.rs
Labels: automerge

#5610 chore: update `quick-xml` (0.23.0 was yanked)
  Cargo.lock
Labels: automerge

#5601 feat: add "read group" support to storage CLI
  influxdb_iox/src/commands/storage.rs
  influxdb_iox/src/commands/storage/request.rs
  influxdb_iox/src/commands/storage/response.rs
Labels: automerge

#5611 chore: slim down `criterion`
  Cargo.lock
  cache_system/Cargo.toml
  iox_data_generator/Cargo.toml
  mutable_batch_lp/Cargo.toml
  mutable_batch_tests/Cargo.toml
  packers/Cargo.toml
  read_buffer/Cargo.toml
  router/Cargo.toml
  sharder/Cargo.toml
Labels: automerge

#5612 refactor: query code clean ups
  ingester/src/querier_handler.rs
  iox_query/src/provider.rs
Labels: automerge

#5613 fix: apply selection in `TestChunk::read_filter`
  iox_query/src/test.rs
  service_grpc_influxrpc/src/service.rs
Labels: automerge

#5614 refactor: make `QueryChunk::partition_id` non-optional
  compactor/src/query.rs
  ingester/src/compact.rs
  ingester/src/data.rs
  ingester/src/querier_handler.rs
  ingester/src/query.rs
  ingester/src/test_util.rs
  iox_query/src/lib.rs
  iox_query/src/provider.rs
  iox_query/src/provider/overlap.rs
  iox_query/src/test.rs
  querier/src/chunk/query_access.rs
  querier/src/ingester/mod.rs
  querier/src/table/state_reconciler.rs
  service_grpc_influxrpc/src/service.rs
Labels: automerge

#5386 feat: full cold compaction
  clap_blocks/src/compactor.rs
  compactor/src/cold.rs
  compactor/src/compact.rs
  compactor/src/handler.rs
  compactor/src/hot.rs
  compactor/src/lib.rs
  compactor/src/parquet_file_combining.rs
  compactor/src/parquet_file_filtering.rs
  compactor/src/parquet_file_lookup.rs
  compactor/src/query.rs
  data_types/src/lib.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/tests/end_to_end_cases/cli.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  ioxd_compactor/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5604 fix: Don't try to parse /api/v2/query response as JSON
  influxdb2_client/examples/query.rs
  influxdb2_client/src/api/query.rs
  influxdb2_client/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5591 chore: Update datafusion / `arrow` / `arrow-flight` / `parquet` to version 22.0.0
  Cargo.lock
  arrow_util/Cargo.toml
  compactor/Cargo.toml
  datafusion/Cargo.toml
  influxdb_iox/Cargo.toml
  influxdb_iox_client/Cargo.toml
  influxdb_iox_client/src/client/flight/low_level.rs
  ingester/Cargo.toml
  iox_query/Cargo.toml
  iox_tests/Cargo.toml
  ioxd_querier/Cargo.toml
  mutable_batch/Cargo.toml
  packers/Cargo.toml
  parquet_file/Cargo.toml
  predicate/Cargo.toml
  predicate/src/lib.rs
  querier/Cargo.toml
  query_functions/Cargo.toml
  query_tests/Cargo.toml
  query_tests/cases/in/pushdown.expected
  read_buffer/Cargo.toml
  read_buffer/src/chunk.rs
  read_buffer/src/column/encoding/bool.rs
  read_buffer/src/column/encoding/scalar/fixed_null.rs
  read_buffer/src/column/integer.rs
  schema/Cargo.toml
  service_grpc_flight/Cargo.toml
  service_grpc_influxrpc/Cargo.toml
  test_helpers_end_to_end/Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#5625 chore: update axum
  Cargo.lock
Labels: automerge

#5618 refactor: dedicated query path for querier tombstone materialization
  ingester/src/data.rs
  ingester/src/data/query_dedup.rs
Labels: automerge

#5619 chore: Update datafusion + object_store
  Cargo.lock
  Cargo.toml
  clap_blocks/Cargo.toml
  compactor/Cargo.toml
  datafusion/Cargo.toml
  garbage_collector/Cargo.toml
  import/Cargo.toml
  influxdb_iox/Cargo.toml
  ingester/Cargo.toml
  iox_tests/Cargo.toml
  ioxd_compactor/Cargo.toml
  ioxd_ingester/Cargo.toml
  ioxd_querier/Cargo.toml
  ioxd_router/Cargo.toml
  object_store_metrics/Cargo.toml
  parquet_file/Cargo.toml
  predicate/src/rewrite.rs
  querier/Cargo.toml
  query_functions/src/selectors.rs
  router/Cargo.toml
  service_grpc_object_store/Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#5620 chore: remove unnecessary empty batch check in parquet_file writing code
  parquet_file/src/serialize.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5621 feat: add a few more buckets for the histograms
  compactor/src/compact.rs
Labels: automerge

#5622 fix: Use `ColumnType` as an enum in more places; make `estimate_arrow_bytes_for_file` infallible
  compactor/src/cold.rs
  compactor/src/hot.rs
  compactor/src/parquet_file_filtering.rs
  data_types/src/lib.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
  router/tests/http.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5628 feat: Support calling influxql/flux selector aggregates from IOx SQL
  iox_query/src/exec/context.rs
  query_functions/src/selectors.rs
  query_functions/src/selectors/internal.rs
  query_tests/cases/in/selectors.expected
  query_tests/cases/in/selectors.sql
  query_tests/src/cases.rs
  query_tests/src/influxrpc/read_group.rs
  query_tests/src/scenarios.rs
  query_tests/src/scenarios/library.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5634 refactor(ingester): split data.rs into submodules
  ingester/src/compact.rs
  ingester/src/data.rs
  ingester/src/data/namespace.rs
  ingester/src/data/partition.rs
  ingester/src/data/partition/buffer.rs
  ingester/src/data/query_dedup.rs
  ingester/src/data/shard.rs
  ingester/src/data/table.rs
  ingester/src/data/triggers/test.rs
  ingester/src/handler.rs
  ingester/src/job.rs
  ingester/src/lifecycle.rs
  ingester/src/poison.rs
  ingester/src/querier_handler.rs
  ingester/src/query.rs
  ingester/src/server.rs
  ingester/src/server/grpc.rs
  ingester/src/server/http.rs
  ingester/src/stream_handler/handler.rs
  ingester/src/stream_handler/periodic_watermark_fetcher.rs
  ingester/src/stream_handler/sink_adaptor.rs
  ingester/src/stream_handler/sink_instrumentation.rs
  ingester/src/test_util.rs
  query_tests/src/scenarios/util.rs
Labels: kodiak: merge.method = 'merge'

#5635 refactor: slightly increase querier namespace cache TTLs
  querier/src/cache/namespace.rs
Labels: automerge

#5627 docs: Add comments about how to see debug logs via `cargo test`
  test_helpers/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5632 feat: Improved InfluxQL error messages
  influxdb_influxql_parser/src/common.rs
  influxdb_influxql_parser/src/expression.rs
  influxdb_influxql_parser/src/identifier.rs
  influxdb_influxql_parser/src/internal.rs
  influxdb_influxql_parser/src/keywords.rs
  influxdb_influxql_parser/src/lib.rs
  influxdb_influxql_parser/src/literal.rs
  influxdb_influxql_parser/src/parameter.rs
  influxdb_influxql_parser/src/show.rs
  influxdb_influxql_parser/src/show_measurements.rs
  influxdb_influxql_parser/src/statement.rs
  influxdb_influxql_parser/src/string.rs
  influxdb_influxql_parser/src/test_util.rs
Labels: automerge, influxql

#5641 chore: add parttion id into panic message
  compactor/src/parquet_file_combining.rs
  compactor/src/utils.rs
  querier/src/chunk/mod.rs
  schema/src/sort.rs
Labels: automerge

#5642 chore: Remove variants from Identifier and BindParameter types
  influxdb_influxql_parser/src/common.rs
  influxdb_influxql_parser/src/expression.rs
  influxdb_influxql_parser/src/identifier.rs
  influxdb_influxql_parser/src/parameter.rs
  influxdb_influxql_parser/src/show_measurements.rs
  influxdb_influxql_parser/src/string.rs
Labels: automerge, influxql

#5644 refactor: hoist per-partition persistence watermark from buffer
  ingester/src/data.rs
  ingester/src/data/namespace.rs
  ingester/src/data/partition.rs
  ingester/src/data/partition/buffer.rs
  ingester/src/data/table.rs
  ingester/src/test_util.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5646 feat: concurrent chunk creation
  querier/src/table/mod.rs
Labels: automerge

#5645 feat: split "pruned" metric into "early" and "late"
  querier/src/namespace/query_access.rs
  querier/src/table/mod.rs
  querier/src/table/query_access.rs
  querier/src/table/query_access/metrics.rs
  querier/src/table/query_access/mod.rs
  querier/src/table/test_util.rs
Labels: automerge

#5648 feat: store per partition persist markers
  data_types/src/lib.rs
  import/src/aggregate_tsm_schema/update_catalog.rs
  ingester/src/compact.rs
  ingester/src/data.rs
  iox_catalog/migrations/20220915085930_per-partition-persist-offset.sql
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5649 refactor: concurrent table scan for "table names"
  iox_query/src/frontend/influxrpc.rs
  query_tests/src/influxrpc/table_names.rs
  service_common/src/planner.rs
Labels: automerge

#5652 refactor(db): NULLable persisted_sequence_number
  data_types/src/lib.rs
  import/src/aggregate_tsm_schema/update_catalog.rs
  ingester/src/compact.rs
  ingester/src/data.rs
  iox_catalog/migrations/20220915155941_nullable-partition-persist-offset.sql
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5650 refactor: Clear up responsibilities of different parts of the compactor
  compactor/src/cold.rs
  compactor/src/compact.rs
  compactor/src/hot.rs
  compactor/src/lib.rs
  compactor/src/parquet_file.rs
  compactor/src/parquet_file_combining.rs
  compactor/src/parquet_file_filtering.rs
  compactor/src/parquet_file_lookup.rs
  iox_tests/src/util.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5657 perf: O(1) partition persist mark discovery
  ingester/src/data.rs
  ingester/src/data/table.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5660 refactor(ingester): remove redundant fn args
  ingester/src/data.rs
  ingester/src/data/namespace.rs
  ingester/src/data/partition.rs
  ingester/src/data/partition/buffer.rs
  ingester/src/data/shard.rs
  ingester/src/data/table.rs
  ingester/src/handler.rs
  ingester/src/querier_handler.rs
  ingester/src/query.rs
  ingester/src/test_util.rs
  query_tests/src/scenarios/util.rs
Labels: kodiak: merge.method = 'merge'

#5661 chore: reduce number of histogram buckets
  compactor/src/compact.rs
Labels: automerge

#5653 feat: Re-enable full compaction to level 2, limited by the memory budget
  compactor/src/cold.rs
  compactor/src/hot.rs
  compactor/src/lib.rs
  compactor/src/parquet_file_combining.rs
  compactor/src/parquet_file_filtering.rs
  compactor/src/parquet_file_lookup.rs
  compactor/src/query.rs
  compactor/src/utils.rs
  data_types/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5643 feat: Teach InfluxQL parser how to parse SHOW statements
  influxdb_influxql_parser/src/expression.rs
  influxdb_influxql_parser/src/lib.rs
  influxdb_influxql_parser/src/show.rs
  influxdb_influxql_parser/src/show_field_keys.rs
  influxdb_influxql_parser/src/show_measurements.rs
  influxdb_influxql_parser/src/show_retention_policies.rs
  influxdb_influxql_parser/src/show_tag_keys.rs
  influxdb_influxql_parser/src/show_tag_values.rs
  influxdb_influxql_parser/src/statement.rs
Labels: automerge, influxql

#5669 chore: replace `ansi_style` with `nu-ansi-style`
  Cargo.lock
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/sql/repl.rs
Labels: automerge

#5651 refactor: concurrent table scan in "field columns"
  iox_query/src/frontend/influxrpc.rs
  query_tests/src/influxrpc/field_columns.rs
  service_common/src/planner.rs
Labels: automerge

#5671 refactor: concurrent table scan for "tag values"
  iox_query/src/frontend/influxrpc.rs
  query_tests/src/db.rs
  query_tests/src/influxrpc/tag_values.rs
  service_common/src/planner.rs
  service_grpc_influxrpc/src/service.rs
Labels: automerge

#5675 refactor: Add helper methods for computing times to TimeProvider
  Cargo.lock
  compactor/src/cold.rs
  compactor/src/compact.rs
  compactor/src/garbage_collector.rs
  compactor/src/hot.rs
  data_types/Cargo.toml
  data_types/src/lib.rs
  garbage_collector/src/parquetfile/deleter.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
  iox_tests/src/util.rs
  iox_time/src/lib.rs
  parquet_file/src/metadata.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5681 chore: Lower sqlx logging verbosity
  Cargo.lock
  iox_catalog/Cargo.toml
  iox_catalog/src/postgres.rs
Labels: automerge

#5680 fix: Make us log logs from the log crate again
  influxdb_iox/src/commands/tracing.rs
  trogging/src/cli.rs
  trogging/src/lib.rs
Labels: automerge

#5656 feat: Add `DELETE` and `DROP MEASUREMENT` statements
  influxdb_influxql_parser/src/delete.rs
  influxdb_influxql_parser/src/drop.rs
  influxdb_influxql_parser/src/expression.rs
  influxdb_influxql_parser/src/lib.rs
  influxdb_influxql_parser/src/show.rs
  influxdb_influxql_parser/src/show_field_keys.rs
  influxdb_influxql_parser/src/show_retention_policies.rs
  influxdb_influxql_parser/src/show_tag_keys.rs
  influxdb_influxql_parser/src/show_tag_values.rs
  influxdb_influxql_parser/src/simple_from_clause.rs
  influxdb_influxql_parser/src/statement.rs
Labels: automerge, influxql

#5682 chore: Expose all DSN flags in all-in-one
  influxdb_iox/src/commands/run/all_in_one.rs
Labels: automerge

#5672 chore: Update datafusion
  Cargo.lock
  datafusion/Cargo.toml
  query_tests/cases/in/pushdown.expected
  query_tests/cases/in/sql_information_schema.expected
Labels: automerge, kodiak: merge.method = 'squash'

#5674 chore: Do not use ANSI colorization for logs by default if not connected to a tty
  Cargo.lock
  trogging/Cargo.toml
  trogging/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5691 fix: GC `parquet_file` table in batches
  Cargo.lock
  garbage_collector/Cargo.toml
  garbage_collector/src/lib.rs
  garbage_collector/src/objectstore/lister.rs
  garbage_collector/src/parquetfile/deleter.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/postgres.rs
Labels: automerge

#5673 refactor: improve "remove if" cache checks
  cache_system/src/backend/policy/integration_tests.rs
  cache_system/src/backend/policy/mod.rs
  cache_system/src/backend/policy/refresh.rs
  cache_system/src/backend/policy/remove_if.rs
Labels: automerge

#5693 refactor: improve consistent access under "remove if"
  cache_system/src/backend/policy/remove_if.rs
  querier/src/cache/namespace.rs
  querier/src/cache/parquet_file.rs
  querier/src/cache/partition.rs
  querier/src/cache/tombstones.rs
  querier/src/table/mod.rs
Labels: automerge

#5676 refactor: improve interaction of LRU and cache refreshs
  cache_system/src/backend/policy/integration_tests.rs
  cache_system/src/backend/policy/lru.rs
  cache_system/src/backend/policy/refresh.rs
Labels: automerge

#5695 refactor: retry querier->ingester requests
  backoff/src/lib.rs
  influxdb_iox/tests/end_to_end_cases/querier.rs
  querier/src/ingester/mod.rs
  query_tests/src/scenarios/util.rs
Labels: automerge

#5697 test: refactor ingester query tests
  ingester/src/data/namespace.rs
  ingester/src/data/partition.rs
  ingester/src/data/partition/buffer.rs
  ingester/src/data/shard.rs
  ingester/src/data/table.rs
  ingester/src/querier_handler.rs
  ingester/src/test_util.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5698 chore: turn cold compaction on but only compact L0s and their overlapped L1s
  compactor/src/cold.rs
  compactor/src/handler.rs
Labels: automerge

#5700 chore: disable cold compaction again since its step 1 is the culprit
  compactor/src/cold.rs
  compactor/src/handler.rs
Labels: automerge

#5699 chore: Improve debug logging when parquet files are created
  parquet_file/src/serialize.rs
  parquet_file/src/storage.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5708 fix: ingester retries
  ingester/src/querier_handler.rs
  querier/src/ingester/mod.rs
Labels: automerge

#5712 chore: upgrade sqlx to 0.6.2
  Cargo.lock
  workspace-hack/Cargo.toml
Labels: automerge

#5677 feat: Improve compactor code organization and test coverage
  compactor/src/cold.rs
  compactor/src/compact.rs
  compactor/src/hot.rs
  compactor/src/lib.rs
  compactor/src/utils.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5713 refactor: use cheaper hash keys for projected schemas
  querier/src/cache/namespace.rs
  querier/src/cache/projected_schema.rs
  querier/src/chunk/mod.rs
  querier/src/table/mod.rs
Labels: automerge

#5626 refactor: do not run de-dup in ingester for querier requests
  influxdb_iox/tests/end_to_end_cases/querier.rs
  ingester/src/querier_handler.rs
  querier/src/ingester/mod.rs
  query_tests/cases/in/duplicates_ingester.expected
  query_tests/cases/in/duplicates_ingester.sql
  query_tests/cases/in/duplicates_parquet.expected
  query_tests/cases/in/duplicates_parquet.sql
  query_tests/cases/in/several_chunks.expected
  query_tests/src/cases.rs
  query_tests/src/scenarios.rs
  query_tests/src/scenarios/library.rs
Labels: automerge

#5722 refactor: acquire table locks concurrently
  ingester/src/querier_handler.rs
Labels: automerge

#5726 chore: turn compaction cold partition step 1 on to work with our new …
  compactor/src/handler.rs
Labels: automerge

#5728 chore: turn full cold compaction on
  compactor/src/handler.rs
Labels: automerge

#5727 chore: Upgrade to Rust 1.64
  arrow_util/src/string.rs
  influxdb_iox/src/commands/storage.rs
  influxdb_tsm/src/reader.rs
  ingester/src/query.rs
  iox_catalog/src/mem.rs
  iox_data_generator/src/specification.rs
  iox_query/src/frontend/influxrpc.rs
  querier/src/system_tables/queries.rs
  read_buffer/src/column/encoding/scalar/rle.rs
  rust-toolchain.toml
  write_buffer/src/codec.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5732 refactor: avoid clones for `policy::Subscriber::set`
  cache_system/src/backend/policy/lru.rs
  cache_system/src/backend/policy/mod.rs
  cache_system/src/backend/policy/refresh.rs
  cache_system/src/backend/policy/ttl.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5731 chore: more verbose for the log message at the time of over-file-limit
  compactor/src/lib.rs
  compactor/src/parquet_file_filtering.rs
Labels: automerge

#5733 chore: always use a fixed number of rows (8192) per batch to estimate memory
  compactor/src/compact.rs
  compactor/src/lib.rs
Labels: automerge

#5735 chore: more verbose about the memory budget inserted in to the catalog table skipped_compaction
  compactor/src/lib.rs
Labels: automerge

#5736 fix: a silly bug that did not capture file limit if a lot of L0 files and very few or non overlapped L1
  compactor/src/parquet_file_filtering.rs
Labels: automerge

#5734 feat: Implement `debug parquet_to_lp` command to convert parquet to line protocol
  Cargo.lock
  Cargo.toml
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/debug/mod.rs
  influxdb_iox/src/commands/debug/parquet_to_lp.rs
  influxdb_iox/tests/end_to_end_cases/cli.rs
  influxdb_line_protocol/src/builder.rs
  parquet_file/src/metadata.rs
  parquet_file/src/serialize.rs
  parquet_to_line_protocol/Cargo.toml
  parquet_to_line_protocol/src/batch.rs
  parquet_to_line_protocol/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5678 feat: send only needed projection columns from querier to ingester in…
  influxdb_iox/tests/end_to_end_cases/querier.rs
  querier/src/ingester/test_util.rs
  querier/src/namespace/query_access.rs
  querier/src/table/mod.rs
  querier/src/table/query_access/mod.rs
  schema/src/lib.rs
Labels: automerge

#5742 feat: add columns in skipped_compactions catalog table
  compactor/src/lib.rs
  compactor/src/parquet_file_filtering.rs
  data_types/src/lib.rs
  iox_catalog/migrations/20220926182450_add_cols_to_skipped_compactions.sql
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
Labels: automerge

#5658 refactor(ingester): partition provider abstraction
  ingester/src/data.rs
  ingester/src/data/namespace.rs
  ingester/src/data/partition.rs
  ingester/src/data/partition/resolver/catalog.rs
  ingester/src/data/partition/resolver/mock.rs
  ingester/src/data/partition/resolver/mod.rs
  ingester/src/data/partition/resolver/trait.rs
  ingester/src/data/shard.rs
  ingester/src/data/table.rs
  ingester/src/test_util.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5694 chore: Update datafusion and `arrow`/`parquet`/`arrow-flight` to 23.0.0, `thrift` to 0.16.0
  Cargo.lock
  Cargo.toml
  arrow_util/Cargo.toml
  arrow_util/src/util.rs
  compactor/Cargo.toml
  datafusion/Cargo.toml
  influxdb_iox/Cargo.toml
  influxdb_iox_client/Cargo.toml
  ingester/Cargo.toml
  ingester/src/data/partition.rs
  iox_query/Cargo.toml
  iox_query/src/exec/seriesset/converter.rs
  iox_tests/Cargo.toml
  iox_tests/src/util.rs
  ioxd_querier/Cargo.toml
  mutable_batch/Cargo.toml
  packers/Cargo.toml
  parquet_file/Cargo.toml
  parquet_file/src/metadata.rs
  parquet_file/src/serialize.rs
  predicate/Cargo.toml
  querier/Cargo.toml
  query_functions/Cargo.toml
  query_tests/Cargo.toml
  query_tests/src/runner.rs
  read_buffer/Cargo.toml
  read_buffer/src/chunk.rs
  schema/Cargo.toml
  service_grpc_flight/Cargo.toml
  service_grpc_influxrpc/Cargo.toml
  test_helpers_end_to_end/Cargo.toml
  trace_exporters/Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#5745 refactor(ingester): limit visibility of internals
  ingester/src/compact.rs
  ingester/src/data.rs
  ingester/src/data/namespace.rs
  ingester/src/data/partition.rs
  ingester/src/data/partition/buffer.rs
  ingester/src/data/query_dedup.rs
  ingester/src/data/shard.rs
  ingester/src/data/table.rs
  ingester/src/handler.rs
  ingester/src/lib.rs
  ingester/src/lifecycle.rs
  ingester/src/query.rs
  ingester/src/stream_handler/handler.rs
  ingester/src/stream_handler/mod.rs
  ingester/src/stream_handler/periodic_watermark_fetcher.rs
  ingester/src/stream_handler/sink_adaptor.rs
  ingester/src/stream_handler/sink_instrumentation.rs
  ingester/src/test_util.rs
  query_tests/src/scenarios/util.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5746 feat(catalog): most recent N partitions
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
Labels: kodiak: merge.method = 'merge'

#5749 feat: use /api/v2 upload for write command rather than grpc `write_service`
  Cargo.lock
  README.md
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/write.rs
  influxdb_iox/src/main.rs
  influxdb_iox/tests/end_to_end_cases/cli.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5754 fix(write_buffer): spurious watermark < read offset panic
  ingester/src/handler.rs
  ingester/src/stream_handler/handler.rs
  write_buffer/src/core.rs
  write_buffer/src/file.rs
  write_buffer/src/kafka/mod.rs
  write_buffer/src/mock.rs
Labels: bug, automerge, kodiak: merge.method = 'merge'

#5747 perf(ingester): partition ID + persist marker cache
  data_types/src/lib.rs
  ingester/src/data.rs
  ingester/src/data/namespace.rs
  ingester/src/data/partition.rs
  ingester/src/data/partition/resolver/cache.rs
  ingester/src/data/partition/resolver/catalog.rs
  ingester/src/data/partition/resolver/mock.rs
  ingester/src/data/partition/resolver/mod.rs
  ingester/src/data/partition/resolver/trait.rs
  ingester/src/data/shard.rs
  ingester/src/handler.rs
  ingester/src/test_util.rs
  query_tests/src/scenarios/util.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5743 feat: Generate the requested num rows and compaction type
  influxdb_iox/src/commands/compactor/generate.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5764 fix: remove future offset read check
  write_buffer/src/kafka/mod.rs
Labels: kodiak: merge.method = 'merge'

#5756 refactor: Change influxdb_iox client to use http rather than grpc for write
  Cargo.lock
  client_util/Cargo.toml
  client_util/src/connection.rs
  client_util/src/lib.rs
  client_util/src/namespace_translation.rs
  import/src/aggregate_tsm_schema/update_catalog.rs
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/write.rs
  influxdb_iox/src/main.rs
  influxdb_iox/tests/end_to_end_cases/mod.rs
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/metadata.rs
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/read_filter.rs
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/read_group.rs
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/read_window_aggregate.rs
  influxdb_iox/tests/end_to_end_cases/router.rs
  influxdb_iox/tests/end_to_end_cases/tracing.rs
  influxdb_iox_client/Cargo.toml
  influxdb_iox_client/src/client/catalog.rs
  influxdb_iox_client/src/client/delete.rs
  influxdb_iox_client/src/client/error.rs
  influxdb_iox_client/src/client/flight/low_level.rs
  influxdb_iox_client/src/client/flight/mod.rs
  influxdb_iox_client/src/client/health.rs
  influxdb_iox_client/src/client/namespace.rs
  influxdb_iox_client/src/client/schema.rs
  influxdb_iox_client/src/client/store.rs
  influxdb_iox_client/src/client/test.rs
  influxdb_iox_client/src/client/write.rs
  influxdb_iox_client/src/client/write_info.rs
  influxdb_iox_client/src/lib.rs
  influxdb_storage_client/src/lib.rs
  service_grpc_influxrpc/src/service.rs
  test_helpers_end_to_end/Cargo.toml
  test_helpers_end_to_end/src/client.rs
  test_helpers_end_to_end/src/mini_cluster.rs
  test_helpers_end_to_end/src/steps.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5766 ci: add dbg!() lint
  arrow_util/src/lib.rs
  arrow_util/src/string.rs
  arrow_util/src/test_util.rs
  backoff/src/lib.rs
  cache_system/src/lib.rs
  clap_blocks/src/lib.rs
  client_util/src/lib.rs
  compactor/src/lib.rs
  data_types/src/lib.rs
  dml/src/lib.rs
  executor/src/lib.rs
  garbage_collector/src/lib.rs
  grpc-binary-logger/src/lib.rs
  influxdb2_client/src/lib.rs
  influxdb_influxql_parser/src/lib.rs
  influxdb_iox_client/src/lib.rs
  influxdb_line_protocol/src/lib.rs
  influxdb_storage_client/src/lib.rs
  influxdb_tsm/src/lib.rs
  influxrpc_parser/src/lib.rs
  ingester/src/lib.rs
  iox_catalog/src/lib.rs
  iox_data_generator/src/lib.rs
  iox_query/src/lib.rs
  iox_tests/src/lib.rs
  iox_time/src/lib.rs
  ioxd_garbage_collector/src/lib.rs
  metric/src/lib.rs
  metric_exporters/src/lib.rs
  mutable_batch/src/lib.rs
  mutable_batch_lp/src/lib.rs
  mutable_batch_pb/src/lib.rs
  packers/src/lib.rs
  panic_logging/src/lib.rs
  predicate/src/lib.rs
  querier/src/lib.rs
  query_functions/src/lib.rs
  read_buffer/src/column.rs
  read_buffer/src/column/encoding/scalar/rle.rs
  read_buffer/src/column/encoding/string/dictionary.rs
  read_buffer/src/lib.rs
  read_buffer/src/row_group.rs
  read_buffer/src/table.rs
  router/src/lib.rs
  router/src/namespace_cache/sharded_cache.rs
  service_grpc_catalog/src/lib.rs
  service_grpc_object_store/src/lib.rs
  sqlx-hotswap-pool/src/lib.rs
  test_helpers/src/lib.rs
  trace/src/lib.rs
  trace_exporters/src/lib.rs
  trace_http/src/lib.rs
  tracker/src/lib.rs
  trogging/src/lib.rs
  write_buffer/src/kafka/mod.rs
  write_buffer/src/lib.rs
Labels: kodiak: merge.method = 'merge'

#5768 refactor: PartitionData carries PartitionKey
  data_types/src/lib.rs
  ingester/src/data/partition.rs
  ingester/src/data/partition/resolver/cache.rs
  ingester/src/data/partition/resolver/catalog.rs
  ingester/src/data/partition/resolver/trait.rs
Labels: kodiak: merge.method = 'merge'

#5769 chore: use 'error' label in log instead of 'e'
  backoff/src/lib.rs
Labels: automerge

#5771 feat: Generate parquet files instead of line protocol
  Cargo.lock
  influxdb_iox/src/commands/compactor/generate.rs
  influxdb_iox/tests/end_to_end_cases/compactor.rs
  iox_data_generator/Cargo.toml
  iox_data_generator/benches/point_generation.rs
  iox_data_generator/src/agent.rs
  iox_data_generator/src/bin/iox_data_generator.rs
  iox_data_generator/src/lib.rs
  iox_data_generator/src/specification.rs
  iox_data_generator/src/write.rs
  iox_tests/src/util.rs
  parquet_file/src/metadata.rs
  parquet_to_line_protocol/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5692 feat: Add `SELECT` statement parsing
  Cargo.lock
  influxdb_influxql_parser/Cargo.toml
  influxdb_influxql_parser/src/common.rs
  influxdb_influxql_parser/src/delete.rs
  influxdb_influxql_parser/src/drop.rs
  influxdb_influxql_parser/src/expression.rs
  influxdb_influxql_parser/src/expression/arithmetic.rs
  influxdb_influxql_parser/src/expression/conditional.rs
  influxdb_influxql_parser/src/expression/test_util.rs
  influxdb_influxql_parser/src/identifier.rs
  influxdb_influxql_parser/src/internal.rs
  influxdb_influxql_parser/src/keywords.rs
  influxdb_influxql_parser/src/lib.rs
  influxdb_influxql_parser/src/literal.rs
  influxdb_influxql_parser/src/parameter.rs
  influxdb_influxql_parser/src/select.rs
  influxdb_influxql_parser/src/show.rs
  influxdb_influxql_parser/src/show_field_keys.rs
  influxdb_influxql_parser/src/show_measurements.rs
  influxdb_influxql_parser/src/show_tag_keys.rs
  influxdb_influxql_parser/src/show_tag_values.rs
  influxdb_influxql_parser/src/simple_from_clause.rs
  influxdb_influxql_parser/src/statement.rs
  influxdb_influxql_parser/src/string.rs
  influxdb_influxql_parser/src/test_util.rs
Labels: automerge, influxql

#5750 refactor: Remove protobuf based write service
  generated_types/protos/influxdata/pbdata/v1/influxdb_pb_data_protocol.proto
  ioxd_router/src/lib.rs
  router/src/server.rs
  router/src/server/grpc.rs
  test_helpers_end_to_end/src/server_fixture.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5778 refactor: LifecycleStats tracks Namespace/TableId
  ingester/src/data/table.rs
  ingester/src/lifecycle.rs
  query_tests/src/scenarios/util.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5772 feat: always pick cold partitions in next cycle even if it has been pa…
  influxdb_iox/tests/end_to_end_cases/cli.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
Labels: automerge

#5781 feat: not split output files in the first step of cold compaction
  compactor/src/cold.rs
Labels: automerge

#5780 test: refactor ingester helpers
  ingester/src/data/partition/resolver/cache.rs
  ingester/src/data/partition/resolver/mock.rs
  ingester/src/data/partition/resolver/trait.rs
  ingester/src/lifecycle.rs
  ingester/src/lifecycle/mock_handle.rs
  ingester/src/test_util.rs
  query_tests/src/scenarios/util.rs
Labels: automerge, kodiak: merge.method = 'merge'
