Repository influxdata/influxdb_iox, pull requests merged in 2022-04, with the labels that each got.

#4198 fix: add indexes to parquet_file
  iox_catalog/migrations/20220331222147_compactor-indexes.sql
  iox_catalog/src/postgres.rs
Labels: automerge

#4179 fix: create_or_get_multi for column in catalog now enforces limits
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
  router2/src/dml_handlers/schema_validation.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4204 feat: replace a compactor constant with an CLI config param
  clap_blocks/src/compactor.rs
  compactor/src/compact.rs
  compactor/src/handler.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ioxd/src/server_type/compactor.rs
Labels: automerge

#4138 feat: Compute a sort key in the ingester
  ingester/src/compact.rs
  ingester/src/data.rs
  ingester/src/lib.rs
  ingester/src/sort_key.rs
  query/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4202 feat: return write_token from HTTP writes to router2
  Cargo.lock
  Cargo.toml
  data_types2/src/lib.rs
  db/src/pred.rs
  generated_types/build.rs
  generated_types/protos/influxdata/iox/write_summary/v1/write_summary.proto
  generated_types/src/lib.rs
  influxdb_iox/tests/end_to_end_ng_cases/all_in_one.rs
  influxdb_iox/tests/end_to_end_ng_cases/querier.rs
  ioxd_router2/Cargo.toml
  ioxd_router2/src/lib.rs
  router2/Cargo.toml
  router2/benches/e2e.rs
  router2/src/dml_handlers/fan_out.rs
  router2/src/dml_handlers/instrumentation.rs
  router2/src/dml_handlers/mock.rs
  router2/src/dml_handlers/mod.rs
  router2/src/dml_handlers/sharded_write_buffer.rs
  router2/src/dml_handlers/write_summary.rs
  router2/src/server/grpc.rs
  router2/src/server/http.rs
  router2/tests/http.rs
  test_helpers_end_to_end_ng/src/client.rs
  write_summary/Cargo.toml
  write_summary/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4210 refactor: Extract `ioxd_test`, `ioxd_compactor`, `ioxd_ingester`; remove `ioxd`
  Cargo.lock
  Cargo.toml
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/src/commands/run/compactor.rs
  influxdb_iox/src/commands/run/database.rs
  influxdb_iox/src/commands/run/ingester.rs
  influxdb_iox/src/commands/run/main.rs
  influxdb_iox/src/commands/run/querier.rs
  influxdb_iox/src/commands/run/router.rs
  influxdb_iox/src/commands/run/router2.rs
  influxdb_iox/src/commands/run/test.rs
  ioxd/Cargo.toml
  ioxd/src/server_type/mod.rs
  ioxd_common/src/lib.rs
  ioxd_common/src/service.rs
  ioxd_compactor/Cargo.toml
  ioxd_compactor/src/lib.rs
  ioxd_ingester/Cargo.toml
  ioxd_ingester/src/lib.rs
  ioxd_test/Cargo.toml
  ioxd_test/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4225 refactor: add table_id index on column_name
  iox_catalog/migrations/20220404120116_column_name-table_id-index.sql
Labels: automerge, kodiak: merge.method = 'merge'

#4212 fix: ingester replay logic
  ingester/src/data.rs
  ingester/src/test_util.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
Labels: automerge

#4231 refactor: delete dead code
  data_types2/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4229 chore: update datafusion
  Cargo.lock
  datafusion/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#4232 feat: Add WriteSummary serialization and deserialization to protobuf
  Cargo.lock
  generated_types/protos/influxdata/iox/write_summary/v1/write_summary.proto
  write_summary/Cargo.toml
  write_summary/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash', incompatible protobuf

#4203 refactor: handle errors in ingester stream handler
  Cargo.lock
  ingester/Cargo.toml
  ingester/src/lib.rs
  ingester/src/stream_handler/handler.rs
  ingester/src/stream_handler/mock_sink.rs
  ingester/src/stream_handler/mod.rs
  ingester/src/stream_handler/sink.rs
  test_helpers/Cargo.toml
  test_helpers/src/lib.rs
  test_helpers/src/timeout.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4235 feat: periodic high watermark fetcher
  ingester/src/stream_handler/mod.rs
  ingester/src/stream_handler/periodic_watermark_fetcher.rs
  write_buffer/src/mock.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4239 chore: add compactor logs
  compactor/src/compact.rs
Labels: automerge

#4238 feat: Add `SequencerProgress` reporting to ingester
  Cargo.lock
  data_types/src/sequence.rs
  data_types2/src/lib.rs
  ingester/Cargo.toml
  ingester/src/data.rs
  ingester/src/handler.rs
  ingester/src/test_util.rs
  write_summary/Cargo.toml
  write_summary/src/lib.rs
  write_summary/src/progress.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4247 chore: Update datafusion
  Cargo.lock
  datafusion/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#4250 refactor: compactor debug logging
  compactor/src/compact.rs
  compactor/src/handler.rs
  compactor/src/utils.rs
  iox_object_store/src/paths/parquet_file.rs
  parquet_file/src/chunk.rs
  parquet_file/src/storage.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4243 feat: ingester op instrumentation
  ingester/src/stream_handler/mock_watermark_fetcher.rs
  ingester/src/stream_handler/mod.rs
  ingester/src/stream_handler/periodic_watermark_fetcher.rs
  ingester/src/stream_handler/sink_instrumentation.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4227 feat: Add API to ingester for write readability and persistence
  generated_types/build.rs
  generated_types/protos/influxdata/iox/ingester/v1/write_info.proto
  influxdb_iox/tests/end_to_end_ng_cases/all_in_one.rs
  influxdb_iox/tests/end_to_end_ng_cases/ingester.rs
  influxdb_iox/tests/end_to_end_ng_cases/querier.rs
  influxdb_iox_client/src/client.rs
  influxdb_iox_client/src/client/write_info.rs
  ingester/src/server/grpc.rs
  ioxd_ingester/src/lib.rs
  test_helpers_end_to_end_ng/src/client.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4256 refactor: extra debug in compactor
  compactor/src/compact.rs
  compactor/src/utils.rs
  parquet_file/src/storage.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4252 chore: Update datafusion again
  Cargo.lock
  datafusion/Cargo.toml
  db/src/system_tables.rs
  querier/src/system_tables/mod.rs
  query/src/exec/non_null_checker.rs
  query/src/exec/query_tracing.rs
  query/src/exec/schema_pivot.rs
  query/src/exec/split.rs
  query/src/provider/deduplicate.rs
  query/src/provider/physical.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4261 fix: fix pprof
  Cargo.lock
  influxdb_iox/Cargo.toml
  ioxd_common/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#4258 test: Add schema validation to end to end querier test
  influxdb_iox/tests/end_to_end_ng_cases/ingester.rs
  influxdb_iox/tests/end_to_end_ng_cases/namespace.rs
  querier/src/flight.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4260 feat: `QuerierDatabase::chunks` returns `Result`
  db/src/access.rs
  db/src/lib.rs
  querier/src/namespace/query_access.rs
  query/src/frontend/influxrpc.rs
  query/src/lib.rs
  query/src/test.rs
  query_tests/src/table_schema.rs
  server/tests/delete.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4264 fix: not to add IOxReadFilterNode for empty non-duplicated chunks
  compactor/src/compact.rs
  query/src/provider.rs
Labels: automerge

#4257 feat(ingester): use SequencedStreamHandler
  Cargo.lock
  ingester/Cargo.toml
  ingester/src/handler.rs
  ingester/src/stream_handler/handler.rs
  ingester/src/stream_handler/mod.rs
  ingester/src/stream_handler/sink_adaptor.rs
  ioxd_ingester/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4259 feat: Add basic Querier <--> Ingester "Service Configuration"
  client_util/src/connection.rs
  data_types2/src/lib.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/src/commands/run/querier.rs
  influxdb_iox/tests/end_to_end_ng_cases/all_in_one.rs
  influxdb_iox/tests/end_to_end_ng_cases/namespace.rs
  influxdb_iox/tests/end_to_end_ng_cases/querier.rs
  ioxd_querier/src/lib.rs
  ioxd_querier/src/rpc/namespace.rs
  querier/src/database.rs
  querier/src/handler.rs
  querier/src/ingester/mod.rs
  querier/src/ingester/test_util.rs
  querier/src/lib.rs
  querier/src/namespace/mod.rs
  querier/src/namespace/query_access.rs
  querier/src/namespace/test_util.rs
  querier/src/table/mod.rs
  querier/src/table/query_access.rs
  querier/src/table/test_util.rs
  query_tests/src/scenarios/util.rs
  test_helpers_end_to_end_ng/src/client.rs
  test_helpers_end_to_end_ng/src/config.rs
  test_helpers_end_to_end_ng/src/server_fixture.rs
  write_summary/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4269 build: use rust 1.60
  rust-toolchain.toml
Labels: automerge, kodiak: merge.method = 'merge'

#4271 feat: allow the querier to talk with multiple ingesters
  clap_blocks/src/lib.rs
  clap_blocks/src/querier.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/src/commands/run/querier.rs
  ioxd_querier/src/lib.rs
  querier/src/ingester/mod.rs
  test_helpers_end_to_end_ng/src/config.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4255 feat: MVP include un-persisted results from the ingester in query results
  Cargo.lock
  influxdb_iox/tests/end_to_end_ng_cases/querier.rs
  querier/Cargo.toml
  querier/src/ingester/mod.rs
  querier/src/ingester/test_util.rs
  querier/src/namespace/query_access.rs
  querier/src/table/mod.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4278 ci: remove duplicate RUSTFLAGS definition
  .circleci/config.yml
Labels: automerge, kodiak: merge.method = 'merge'

#4279 feat: tokio console support
  .circleci/config.yml
  Cargo.lock
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/tracing.rs
  observability_deps/Cargo.toml
  trogging/src/lib.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'merge'

#4281 fix: accept legacy flight requests
  service_grpc_flight/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4274 chore: add comments and `trace` calls to query provider regarding sort keys
  query/src/provider.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4286 refactor: querier<>ingester flight protocol adjustments
  data_types2/src/lib.rs
  generated_types/build.rs
  generated_types/protos/influxdata/iox/ingester/v1/query.proto
  generated_types/src/ingester.rs
  influxdb_iox/tests/end_to_end_ng_cases/ingester.rs
  ingester/src/data.rs
  ingester/src/querier_handler.rs
  ingester/src/server/grpc.rs
  querier/src/ingester/mod.rs
Labels: automerge

#4289 fix: Do not specify a querier address by default
  clap_blocks/src/querier.rs
  influxdb_iox/tests/end_to_end_ng_cases/querier.rs
  test_helpers_end_to_end_ng/src/config.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4254 feat: Use the sort key stored in the catalog during compaction
  compactor/src/compact.rs
  compactor/src/query.rs
  ingester/src/compact.rs
  ingester/src/lib.rs
  ingester/src/sort_key.rs
  iox_tests/src/util.rs
  query/src/provider.rs
  schema/src/sort.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4299 fix: Revert "feat: Use the sort key stored in the catalog during compaction"
  compactor/src/compact.rs
  compactor/src/query.rs
  ingester/src/compact.rs
  ingester/src/lib.rs
  ingester/src/sort_key.rs
  iox_tests/src/util.rs
  query/src/provider.rs
  schema/src/sort.rs
Labels: automerge

#4262 feat: Store parquet_metadata in catalog, but don't fetch it by default
  compactor/src/compact.rs
  compactor/src/query.rs
  compactor/src/utils.rs
  data_types2/src/lib.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_tests/src/util.rs
  parquet_file/src/chunk.rs
  querier/src/chunk/mod.rs
  querier/src/table/mod.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4305 test: improve NG server fixture
  Cargo.lock
  test_helpers_end_to_end_ng/Cargo.toml
  test_helpers_end_to_end_ng/src/mini_cluster.rs
  test_helpers_end_to_end_ng/src/server_fixture.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'merge'

#4304 test: use random catalog schema name for NG end2end tests
  clap_blocks/src/catalog_dsn.rs
  test_helpers_end_to_end_ng/src/config.rs
  test_helpers_end_to_end_ng/src/database.rs
  test_helpers_end_to_end_ng/src/server_fixture.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4308 chore: bump kube to version 0.71.0
  Cargo.lock
  iox_gitops_adapter/Cargo.toml
Labels: automerge, kodiak: merge.method = 'merge'

#4301 refactor: Use declarative steps to reduce duplication in end to end testing
  Cargo.lock
  influxdb_iox/tests/end_to_end_ng_cases/querier.rs
  test_helpers_end_to_end_ng/Cargo.toml
  test_helpers_end_to_end_ng/src/client.rs
  test_helpers_end_to_end_ng/src/lib.rs
  test_helpers_end_to_end_ng/src/steps.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4310 chore: add more compactor debug info
  compactor/src/compact.rs
  query/src/exec/non_null_checker.rs
  query/src/exec/schema_pivot.rs
  query/src/exec/split.rs
  query/src/provider.rs
  query/src/provider/deduplicate.rs
  query/src/provider/physical.rs
Labels: automerge

#4314 chore: use Nga's DF branch with debug information for compactor
  Cargo.lock
  datafusion/Cargo.toml
  predicate/src/rewrite.rs
Labels: automerge

#4302 fix: ingester min-unpersisted-sequence-number calc + doc
  ingester/src/handler.rs
  ingester/src/lifecycle.rs
Labels: automerge

#4321 test: add property test coverage to Read Buffer transcoders
  Cargo.lock
  read_buffer/Cargo.toml
  read_buffer/src/column/encoding/scalar/fixed_null.rs
  read_buffer/src/column/encoding/scalar/rle.rs
  read_buffer/src/column/encoding/scalar/transcoders.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'merge'

#4307 fix: unknown namespace/table in querier<>ingester flight protocol
  influxdb_iox/tests/end_to_end_ng_cases/ingester.rs
  influxdb_iox/tests/end_to_end_ng_cases/querier.rs
  ingester/src/querier_handler.rs
  ingester/src/server/grpc.rs
  querier/src/ingester/mod.rs
  test_helpers_end_to_end_ng/src/database.rs
  test_helpers_end_to_end_ng/src/steps.rs
Labels: automerge

#4325 fix: compactor deadlock
  datafusion_util/src/lib.rs
  query/src/exec/split.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4303 fix: Revert "fix: Revert "feat: Use the sort key stored in the catalog during compaction
  compactor/src/compact.rs
  compactor/src/query.rs
  compactor/src/utils.rs
  ingester/src/compact.rs
  ingester/src/lib.rs
  ingester/src/sort_key.rs
  iox_tests/src/util.rs
  query/src/provider.rs
  schema/src/sort.rs
Labels: automerge

#4322 chore: Update datafusion (and point back to apache)
  Cargo.lock
  datafusion/Cargo.toml
Labels: automerge

#4327 chore: Revert "fix: Revert "fix: Revert "feat: Use the sort key stored in the catalog during compaction" (#4299)" (#4303)"
  compactor/src/compact.rs
  compactor/src/query.rs
  compactor/src/utils.rs
  ingester/src/compact.rs
  ingester/src/lib.rs
  ingester/src/sort_key.rs
  iox_tests/src/util.rs
  query/src/provider.rs
  schema/src/sort.rs
Labels: automerge

#4316 feat: add initial catalog service to router
  Cargo.lock
  Cargo.toml
  generated_types/build.rs
  generated_types/protos/influxdata/iox/catalog/v1/parquet_file.proto
  generated_types/protos/influxdata/iox/catalog/v1/service.proto
  generated_types/src/lib.rs
  iox_catalog_service/Cargo.toml
  iox_catalog_service/src/lib.rs
  ioxd_router2/src/lib.rs
  router2/Cargo.toml
  router2/src/server/grpc.rs
Labels: automerge

#4319 test: deadlock test and add more debug log
  compactor/src/compact.rs
  query/src/provider/deduplicate.rs
  query/src/provider/deduplicate/algo.rs
Labels: automerge

#4320 test: mock gRPC ingester response for querier
  Cargo.lock
  querier/Cargo.toml
  querier/src/ingester/flight_client.rs
  querier/src/ingester/mod.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4329 feat: add catalog client and remote command
  influxdb_iox/src/commands/remote.rs
  influxdb_iox/src/commands/remote/partition.rs
  influxdb_iox/src/main.rs
  influxdb_iox/tests/end_to_end_ng_cases/cli.rs
  influxdb_iox/tests/end_to_end_ng_cases/mod.rs
  influxdb_iox_client/src/client.rs
  influxdb_iox_client/src/client/catalog.rs
Labels: automerge

#4338 feat: add object store service to router
  Cargo.lock
  Cargo.toml
  generated_types/build.rs
  generated_types/protos/influxdata/iox/object_store/v1/service.proto
  generated_types/src/lib.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/src/commands/run/router2.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_object_store_service/Cargo.toml
  iox_object_store_service/src/lib.rs
  ioxd_router2/src/lib.rs
  router2/Cargo.toml
  router2/src/server/grpc.rs
Labels: automerge

#4328 fix: Revert "chore: Revert "fx: Revert "fix: Revert "feat: Use the sort key stored in the catalog during compaction" (#4299)" (#4303)" (#4327)"
  compactor/src/compact.rs
  compactor/src/query.rs
  compactor/src/utils.rs
  ingester/src/compact.rs
  ingester/src/lib.rs
  ingester/src/sort_key.rs
  iox_tests/src/util.rs
  query/src/provider.rs
  schema/src/sort.rs
Labels: automerge

#4347 fix: actually transmit record-batch metadata from querier
  generated_types/protos/influxdata/iox/ingester/v1/query.proto
  influxdb_iox/tests/end_to_end_ng_cases/ingester.rs
  ingester/src/data.rs
  ingester/src/querier_handler.rs
  ingester/src/server/grpc.rs
Labels: automerge

#4323 feat: correctly dismantle ingester gRPC reponse in querier
  querier/src/ingester/flight_client.rs
  querier/src/ingester/mod.rs
Labels: automerge

#4342 chore: update datafusion
  Cargo.lock
  datafusion/Cargo.toml
  generated_types/src/ingester.rs
  predicate/src/regex.rs
  query/src/func/selectors.rs
  query/src/func/window.rs
Labels: automerge, kodiak: merge.method = 'squash', dependencies

#4348 feat: add sequencer ID and correct partition key to `IngesterPartition`
  iox_tests/src/util.rs
  ioxd_querier/src/lib.rs
  ioxd_querier/src/rpc/namespace.rs
  querier/src/cache/mod.rs
  querier/src/cache/partition.rs
  querier/src/database.rs
  querier/src/handler.rs
  querier/src/ingester/mod.rs
  querier/src/lib.rs
Labels: automerge

#4353 fix(logfmt): quote strings containing '='
  logfmt/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4343 feat: add client and CLI to get file from object store
  influxdb_iox/src/commands/remote.rs
  influxdb_iox/src/commands/remote/store.rs
  influxdb_iox/tests/end_to_end_ng_cases/cli.rs
  influxdb_iox_client/src/client.rs
  influxdb_iox_client/src/client/store.rs
Labels: automerge

#4337 refactor: rewrite schema command end to end tests to use new StepTest
  influxdb_iox/tests/end_to_end_ng_cases/schema.rs
  test_helpers_end_to_end_ng/src/steps.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4341 feat: add per kafka partition durability reporting to write info response
  generated_types/protos/influxdata/iox/ingester/v1/write_info.proto
  generated_types/protos/influxdata/iox/write_summary/v1/write_summary.proto
  influxdb_iox/Cargo.toml
  influxdb_iox/tests/end_to_end_ng_cases/querier.rs
  influxdb_iox_client/src/client/write_info.rs
  ingester/src/data.rs
  ingester/src/handler.rs
  ingester/src/server/grpc.rs
  test_helpers_end_to_end_ng/src/client.rs
  write_summary/src/lib.rs
  write_summary/src/progress.rs
Labels: automerge, kodiak: merge.method = 'squash', incompatible protobuf

#4344 chore: add semantic PR and commit message checks
  .github/semantic.yml
  .github/workflows/semantic.yml
  .github/workflows/semantic_check.sh
  .github/workflows/semantic_check.yml
Labels: automerge, kodiak: merge.method = 'squash'

#4356 docs: add note about write_info API being internal
  generated_types/protos/influxdata/iox/ingester/v1/write_info.proto
  influxdb_iox_client/src/client/write_info.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4358 chore: Install custom protoc in perf-builder image
  .circleci/config.yml
Labels: automerge, kodiak: merge.method = 'squash'

#4359 feat: Issue queries from querier to ingester in parallel
  querier/src/ingester/mod.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4357 chore: Update arrow, arrow-flight, parquet, tonic, prost, etc
  Cargo.lock
  arrow_util/Cargo.toml
  client_util/Cargo.toml
  compactor/Cargo.toml
  datafusion/Cargo.toml
  db/Cargo.toml
  db/src/lib.rs
  generated_types/Cargo.toml
  generated_types/build.rs
  grpc-router-test-gen/Cargo.toml
  grpc-router-test-gen/build.rs
  grpc-router/Cargo.toml
  influxdb_iox/Cargo.toml
  influxdb_iox_client/Cargo.toml
  influxdb_storage_client/Cargo.toml
  ingester/Cargo.toml
  iox_catalog_service/Cargo.toml
  iox_gitops_adapter/Cargo.toml
  iox_object_store_service/Cargo.toml
  iox_tests/Cargo.toml
  ioxd_common/Cargo.toml
  ioxd_common/src/http/mod.rs
  ioxd_compactor/Cargo.toml
  ioxd_database/Cargo.toml
  ioxd_ingester/Cargo.toml
  ioxd_querier/Cargo.toml
  ioxd_router/Cargo.toml
  ioxd_router2/Cargo.toml
  ioxd_test/Cargo.toml
  mutable_batch/Cargo.toml
  mutable_batch_tests/Cargo.toml
  mutable_buffer/Cargo.toml
  packers/Cargo.toml
  parquet_catalog/Cargo.toml
  parquet_file/Cargo.toml
  parquet_file/src/metadata.rs
  predicate/Cargo.toml
  querier/Cargo.toml
  query/Cargo.toml
  query_tests/Cargo.toml
  read_buffer/Cargo.toml
  router2/Cargo.toml
  schema/Cargo.toml
  service_grpc_flight/Cargo.toml
  service_grpc_influxrpc/Cargo.toml
  service_grpc_testing/Cargo.toml
  test_helpers_end_to_end_ng/Cargo.toml
  workspace-hack/Cargo.toml
  write_buffer/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#4367 feat: panic metrics
  Cargo.lock
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/src/commands/run/compactor.rs
  influxdb_iox/src/commands/run/database.rs
  influxdb_iox/src/commands/run/ingester.rs
  influxdb_iox/src/commands/run/main.rs
  influxdb_iox/src/commands/run/querier.rs
  influxdb_iox/src/commands/run/router.rs
  influxdb_iox/src/commands/run/router2.rs
  influxdb_iox/src/commands/run/test.rs
  panic_logging/Cargo.toml
  panic_logging/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4309 test: add end to end querier test with multiple ingesters
  influxdb_iox/tests/end_to_end_ng_cases/cli.rs
  influxdb_iox/tests/end_to_end_ng_cases/querier.rs
  influxdb_iox/tests/end_to_end_ng_cases/querier/multi_ingester.rs
  influxdb_iox/tests/end_to_end_ng_cases/schema.rs
  test_helpers_end_to_end_ng/src/client.rs
  test_helpers_end_to_end_ng/src/config.rs
  test_helpers_end_to_end_ng/src/lib.rs
  test_helpers_end_to_end_ng/src/mini_cluster.rs
  test_helpers_end_to_end_ng/src/steps.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4369 fix: Add protobuf compiler to docker build image
  Dockerfile
Labels: automerge, kodiak: merge.method = 'squash'

#4355 feat: fuse ingester and catalog states in querier
  querier/src/chunk/mod.rs
  querier/src/ingester/mod.rs
  querier/src/ingester/test_util.rs
  querier/src/table/mod.rs
  querier/src/table/state_reconciler.rs
Labels: automerge

#4374 chore: Update pprof, remove old versions of prost
  Cargo.lock
  influxdb_iox/Cargo.toml
  ioxd_common/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#4371 test: include materialized delete predicates in NG query tests
  Cargo.lock
  data_types/src/timestamp.rs
  datafusion_util/src/lib.rs
  ingester/Cargo.toml
  ingester/src/query.rs
  iox_tests/Cargo.toml
  iox_tests/src/util.rs
  query_tests/Cargo.toml
  query_tests/src/scenarios/delete.rs
  query_tests/src/scenarios/util.rs
Labels: automerge

#4372 test: Begin porting influxrpc tests to ng end to end tests
  influxdb_iox/tests/end_to_end_cases/influxrpc.rs
  influxdb_iox/tests/end_to_end_ng_cases/querier.rs
  influxdb_iox/tests/end_to_end_ng_cases/querier/influxrpc.rs
  influxdb_iox/tests/end_to_end_ng_cases/querier/influxrpc/data.rs
  influxdb_iox/tests/end_to_end_ng_cases/querier/influxrpc/dump.rs
  influxdb_iox/tests/end_to_end_ng_cases/querier/influxrpc/exprs.rs
  test_helpers_end_to_end_ng/src/lib.rs
  test_helpers_end_to_end_ng/src/mini_cluster.rs
  test_helpers_end_to_end_ng/src/steps.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4381 refactor: Move Connection in ServerFixture to make TestServer shareable
  influxdb_iox/tests/end_to_end_ng_cases/all_in_one.rs
  influxdb_iox/tests/end_to_end_ng_cases/querier/multi_ingester.rs
  test_helpers_end_to_end_ng/src/mini_cluster.rs
  test_helpers_end_to_end_ng/src/server_fixture.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4082 fix: incorrect overlapped grouping
  compactor/src/compact.rs
  query/src/provider/overlap.rs
Labels: automerge

#4385 chore: Update datafusion again
  Cargo.lock
  datafusion/Cargo.toml
  querier/src/table/query_access.rs
  query/src/provider.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4386 feat: Port end-to-end tracing tests to NG end-to-end tests
  Cargo.lock
  influxdb_iox/tests/end_to_end_ng_cases/mod.rs
  influxdb_iox/tests/end_to_end_ng_cases/tracing.rs
  test_helpers_end_to_end_ng/Cargo.toml
  test_helpers_end_to_end_ng/src/config.rs
  test_helpers_end_to_end_ng/src/lib.rs
  test_helpers_end_to_end_ng/src/mini_cluster.rs
  test_helpers_end_to_end_ng/src/udp_listener.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4379 fix: column summary conversion for "unknown" TS
  query/src/statistics.rs
Labels: automerge

#4382 refactor: Split up influxrpc end to end tests
  influxdb_iox/tests/end_to_end_ng_cases/querier/influxrpc.rs
  influxdb_iox/tests/end_to_end_ng_cases/querier/influxrpc/metadata.rs
  influxdb_iox/tests/end_to_end_ng_cases/querier/influxrpc/read_filter.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4380 refactor: use `info!` rather `println!` in end to end tests
  Cargo.lock
  influxdb_iox/tests/end_to_end_ng_cases/all_in_one.rs
  influxdb_iox/tests/end_to_end_ng_cases/cli.rs
  influxdb_iox/tests/end_to_end_ng_cases/ingester.rs
  influxdb_iox/tests/end_to_end_ng_cases/namespace.rs
  influxdb_iox/tests/end_to_end_ng_cases/querier.rs
  influxdb_iox/tests/end_to_end_ng_cases/querier/multi_ingester.rs
  influxdb_iox/tests/end_to_end_ng_cases/schema.rs
  test_helpers_end_to_end_ng/Cargo.toml
  test_helpers_end_to_end_ng/src/client.rs
  test_helpers_end_to_end_ng/src/database.rs
  test_helpers_end_to_end_ng/src/server_fixture.rs
  test_helpers_end_to_end_ng/src/steps.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4391 feat: Provide basic summaries for `IngesterPartition`
  data_types2/src/lib.rs
  querier/src/ingester/mod.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4396 chore: Update datafusion again
  Cargo.lock
  datafusion/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#4393 chore: port debug end to end tests to NG
  influxdb_iox/tests/end_to_end_ng_cases/debug.rs
  influxdb_iox/tests/end_to_end_ng_cases/mod.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4384 refactor: less `async` shenanigans in the end to end tests
  influxdb_iox/tests/end_to_end_ng_cases/querier/influxrpc/metadata.rs
  influxdb_iox/tests/end_to_end_ng_cases/querier/influxrpc/read_filter.rs
  test_helpers_end_to_end_ng/src/steps.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4400 feat: Port end-to-end logging test to NG
  influxdb_iox/tests/end_to_end_ng_cases/logging.rs
  influxdb_iox/tests/end_to_end_ng_cases/mod.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4402 fix: Typo in test helper method name
  influxdb_iox/tests/end_to_end_ng_cases/cli.rs
  influxdb_iox/tests/end_to_end_ng_cases/querier.rs
  test_helpers_end_to_end_ng/src/mini_cluster.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4398 fix: handle LP lines with duplicated fields/tags
  Cargo.lock
  influxdb_line_protocol/src/lib.rs
  mutable_batch_lp/Cargo.toml
  mutable_batch_lp/src/lib.rs
  router2/src/server/http.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4409 feat: benchmark LP -> MutableBuffer conversion
  Cargo.lock
  mutable_batch_lp/Cargo.toml
  mutable_batch_lp/benches/parse_lp.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4389 feat: group chunk overlaps based on time range only
  Cargo.lock
  compactor/Cargo.toml
  compactor/src/query.rs
  compactor/src/utils.rs
  db/Cargo.toml
  db/src/chunk.rs
  ingester/Cargo.toml
  ingester/src/query.rs
  parquet_file/src/chunk.rs
  querier/Cargo.toml
  querier/src/chunk/mod.rs
  querier/src/chunk/query_access.rs
  querier/src/ingester/mod.rs
  query/Cargo.toml
  query/src/frontend.rs
  query/src/frontend/reorg.rs
  query/src/lib.rs
  query/src/provider.rs
  query/src/provider/overlap.rs
  query/src/test.rs
Labels: automerge

#4418 fix: make all catalog IDs 64bit
  data_types2/src/lib.rs
  generated_types/protos/influxdata/iox/catalog/v1/parquet_file.proto
  generated_types/protos/influxdata/iox/ingester/v1/parquet_metadata.proto
  generated_types/protos/influxdata/iox/namespace/v1/service.proto
  generated_types/protos/influxdata/iox/schema/v1/service.proto
  influxdb_iox/src/commands/sql/repl.rs
  ingester/src/compact.rs
  ingester/src/test_util.rs
  iox_catalog/migrations/20220420142224_ids_bigint.sql
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog_service/src/lib.rs
  parquet_file/src/metadata.rs
  querier/src/cache/namespace.rs
  querier/src/cache/table.rs
  querier/src/system_tables/queries.rs
  router2/src/namespace_cache/sharded_cache.rs
  router2/src/server/grpc.rs
  router2/tests/http.rs
Labels: automerge, incompatible protobuf

#4404 feat: Rewrite the NG end-to-end metrics test
  Cargo.lock
  influxdb_iox/tests/end_to_end_ng_cases/metrics.rs
  influxdb_iox/tests/end_to_end_ng_cases/mod.rs
  influxdb_iox/tests/end_to_end_ng_cases/querier.rs
  influxdb_iox/tests/end_to_end_ng_cases/querier/influxrpc.rs
  influxdb_iox/tests/end_to_end_ng_cases/querier/influxrpc/exprs.rs
  influxdb_iox/tests/end_to_end_ng_cases/querier/influxrpc/metadata.rs
  influxdb_iox/tests/end_to_end_ng_cases/querier/influxrpc/read_filter.rs
  influxdb_iox/tests/end_to_end_ng_cases/tracing.rs
  test_helpers_end_to_end_ng/Cargo.toml
  test_helpers_end_to_end_ng/src/data_generator.rs
  test_helpers_end_to_end_ng/src/grpc.rs
  test_helpers_end_to_end_ng/src/lib.rs
  test_helpers_end_to_end_ng/src/steps.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4420 refactor: grouping overlaps now uses the same overlap function in both compactor and deduplication
  compactor/src/compact.rs
  query/src/lib.rs
  query/src/provider.rs
  query/src/provider/overlap.rs
Labels: automerge

#4415 test: chunks in ingester stage
  Cargo.lock
  iox_tests/Cargo.toml
  iox_tests/src/util.rs
  querier/src/ingester/test_util.rs
  querier/src/lib.rs
  query/src/provider.rs
  query/src/provider/deduplicate.rs
  query/src/provider/deduplicate/algo.rs
  query_tests/Cargo.toml
  query_tests/cases/in/delete_three_delete_three_chunks.expected
  query_tests/cases/in/delete_three_delete_three_chunks.sql
  query_tests/cases/in/old_duplicates.expected
  query_tests/cases/in/old_duplicates.sql
  query_tests/src/cases.rs
  query_tests/src/scenarios.rs
  query_tests/src/scenarios/delete.rs
  query_tests/src/scenarios/library.rs
  query_tests/src/scenarios/util.rs
  query_tests/src/table_schema.rs
Labels: automerge

#4419 feat(router2): http service protection limit
  Cargo.lock
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/src/commands/run/router2.rs
  ioxd_router2/src/lib.rs
  router2/Cargo.toml
  router2/benches/e2e.rs
  router2/src/server/http.rs
  router2/tests/http.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4430 fix: memorize max persisted tombstone
  ingester/src/data.rs
Labels: automerge

#4360 feat: use stored partition sort key to deduplicate data
  compactor/src/compact.rs
  compactor/src/query.rs
  compactor/src/utils.rs
  db/src/chunk.rs
  ingester/src/query.rs
  iox_tests/src/util.rs
  querier/src/cache/partition.rs
  querier/src/chunk/mod.rs
  querier/src/chunk/query_access.rs
  querier/src/ingester/mod.rs
  query/src/frontend/reorg.rs
  query/src/lib.rs
  query/src/provider.rs
  query/src/provider/overlap.rs
  query/src/test.rs
Labels: automerge

#4431 feat: Implement IOx Function Registry + `regex_match` / `regex_not_match` (2/3)
  Cargo.lock
  predicate/src/lib.rs
  query_functions/Cargo.toml
  query_functions/src/lib.rs
  query_functions/src/regex.rs
  query_functions/src/registry.rs
  service_grpc_influxrpc/src/expr.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4436 chore: Update datafusion
  Cargo.lock
  datafusion/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#4429 fix: extend + harden querier `ensure_schema`
  querier/src/ingester/mod.rs
  querier/src/table/mod.rs
Labels: automerge

#4432 feat: Add window_bounds to IOx Function Registry (2.5/3)
  Cargo.lock
  datafusion_util/src/lib.rs
  query/src/frontend/influxrpc.rs
  query_functions/Cargo.toml
  query_functions/src/lib.rs
  query_functions/src/regex.rs
  query_functions/src/registry.rs
  query_functions/src/window.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4441 chore: Ignore flaky OG end to end test `end_to_end_cases::persistence::test_full_lifecycle`
  influxdb_iox/tests/end_to_end_cases/persistence.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4442 fix: do not prune all-NULL columns from sort keys
  schema/src/sort.rs
Labels: automerge

#4443 fix: do not create empty batches in ingester
  ingester/src/data.rs
Labels: automerge

#4440 refactor: Use DataFusion `Expr` instead of our own custom wrapper for `ValueExpr`
  generated_types/protos/influxdata/iox/ingester/v1/query.proto
  generated_types/src/ingester.rs
  predicate/src/lib.rs
  predicate/src/rpc_predicate.rs
  query/src/frontend/influxrpc.rs
Labels: automerge, kodiak: merge.method = 'squash', incompatible protobuf

#4458 test: remove hard-coded metric count
  influxdb_iox/tests/end_to_end_ng_cases/metrics.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4421 fix: Use datafusion serialization code rather than our own copy of it
  Cargo.lock
  data_types2/src/lib.rs
  datafusion/Cargo.toml
  datafusion/src/lib.rs
  generated_types/protos/influxdata/iox/ingester/v1/query.proto
  generated_types/src/ingester.rs
  predicate/src/lib.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash', incompatible protobuf

#4444 fix: Support for computing series across multiple record batches
  query/src/exec/seriesset/converter.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4455 test: use "real" ingester in query tests
  Cargo.lock
  querier/src/ingester/mod.rs
  querier/src/lib.rs
  querier/src/namespace/mod.rs
  querier/src/namespace/test_util.rs
  query_tests/Cargo.toml
  query_tests/src/scenarios/util.rs
Labels: automerge

#4461 refactor: start using `with_timeout_panic` in end to end tests
  test_helpers_end_to_end_ng/Cargo.toml
  test_helpers_end_to_end_ng/src/server_fixture.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4452 docs: document for deduplication and sort key
  docs/README.md
  docs/dedup_and_sort.md
  query/src/frontend/reorg.rs
  query/src/provider.rs
Labels: automerge

#4387 feat: share server processes in end to end test
  Cargo.lock
  influxdb_iox/tests/end_to_end_ng_cases/cli.rs
  influxdb_iox/tests/end_to_end_ng_cases/ingester.rs
  influxdb_iox/tests/end_to_end_ng_cases/namespace.rs
  influxdb_iox/tests/end_to_end_ng_cases/querier.rs
  influxdb_iox/tests/end_to_end_ng_cases/querier/influxrpc.rs
  influxdb_iox/tests/end_to_end_ng_cases/router.rs
  influxdb_iox/tests/end_to_end_ng_cases/schema.rs
  test_helpers_end_to_end_ng/Cargo.toml
  test_helpers_end_to_end_ng/src/client.rs
  test_helpers_end_to_end_ng/src/config.rs
  test_helpers_end_to_end_ng/src/mini_cluster.rs
  test_helpers_end_to_end_ng/src/server_fixture.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4460 chore: Update dependencies via `cargo update`
  Cargo.lock
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#4433 feat: add CLI command `remote pull partition`
  generated_types/protos/influxdata/iox/catalog/v1/service.proto
  influxdb_iox/src/commands/remote/partition.rs
  influxdb_iox/tests/end_to_end_ng_cases/cli.rs
  influxdb_iox_client/src/client/catalog.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_catalog_service/src/lib.rs
Labels: automerge

#4465 chore: add some logging to flaky end to end test
  influxdb_iox/tests/end_to_end_ng_cases/querier/multi_ingester.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4472 feat: expose catalog timeouts via CLI/env
  Cargo.lock
  clap_blocks/Cargo.toml
  clap_blocks/src/catalog_dsn.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  iox_catalog/src/postgres.rs
Labels: automerge

#4456 docs: Fix typo in `data_organization_lifecycle.md`
  docs/data_organization_lifecycle.md
Labels: automerge, kodiak: merge.method = 'squash'

#4469 test: Added explain tests for querier. Found and fixed #4468
  Cargo.lock
  querier/Cargo.toml
  querier/src/namespace/query_access.rs
  querier/src/table/state_reconciler.rs
  query/src/provider.rs
  query/src/provider/overlap.rs
Labels: automerge

#4477 fix: Delete OG end-to-end tests
  Cargo.lock
  influxdb_iox/Cargo.toml
  influxdb_iox/tests/common/mod.rs
  influxdb_iox/tests/common/server_fixture.rs
  influxdb_iox/tests/common/udp_listener.rs
  influxdb_iox/tests/end_to_end.rs
  influxdb_iox/tests/end_to_end_cases/database_migration.rs
  influxdb_iox/tests/end_to_end_cases/debug_cli.rs
  influxdb_iox/tests/end_to_end_cases/delete_api.rs
  influxdb_iox/tests/end_to_end_cases/deletes.rs
  influxdb_iox/tests/end_to_end_cases/deployment_api.rs
  influxdb_iox/tests/end_to_end_cases/deployment_cli.rs
  influxdb_iox/tests/end_to_end_cases/flight_api.rs
  influxdb_iox/tests/end_to_end_cases/freeze.rs
  influxdb_iox/tests/end_to_end_cases/http.rs
  influxdb_iox/tests/end_to_end_cases/influxdb_ioxd.rs
  influxdb_iox/tests/end_to_end_cases/influxrpc.rs
  influxdb_iox/tests/end_to_end_cases/kafka.rs
  influxdb_iox/tests/end_to_end_cases/management_api.rs
  influxdb_iox/tests/end_to_end_cases/management_cli.rs
  influxdb_iox/tests/end_to_end_cases/metrics.rs
  influxdb_iox/tests/end_to_end_cases/mod.rs
  influxdb_iox/tests/end_to_end_cases/operations_api.rs
  influxdb_iox/tests/end_to_end_cases/operations_cli.rs
  influxdb_iox/tests/end_to_end_cases/persistence.rs
  influxdb_iox/tests/end_to_end_cases/read_api.rs
  influxdb_iox/tests/end_to_end_cases/read_cli.rs
  influxdb_iox/tests/end_to_end_cases/remote_api.rs
  influxdb_iox/tests/end_to_end_cases/remote_cli.rs
  influxdb_iox/tests/end_to_end_cases/router_api.rs
  influxdb_iox/tests/end_to_end_cases/router_cli.rs
  influxdb_iox/tests/end_to_end_cases/run_cli.rs
  influxdb_iox/tests/end_to_end_cases/scenario.rs
  influxdb_iox/tests/end_to_end_cases/sql_cli.rs
  influxdb_iox/tests/end_to_end_cases/system_tables.rs
  influxdb_iox/tests/end_to_end_cases/tracing.rs
  influxdb_iox/tests/end_to_end_cases/write_api.rs
  influxdb_iox/tests/end_to_end_cases/write_buffer.rs
  influxdb_iox/tests/end_to_end_cases/write_cli.rs
  influxdb_iox/tests/end_to_end_cases/write_pb.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4464 feat: port last `influxrpc` e2e tests to NG: read_group and read_window_aggregate
  influxdb_iox/tests/end_to_end_ng_cases/querier/influxrpc.rs
  influxdb_iox/tests/end_to_end_ng_cases/querier/influxrpc/read_filter.rs
  influxdb_iox/tests/end_to_end_ng_cases/querier/influxrpc/read_group.rs
  influxdb_iox/tests/end_to_end_ng_cases/querier/influxrpc/read_window_aggregate.rs
  test_helpers_end_to_end_ng/src/grpc.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4482 fix: Switch `list_database_names` to `get_namespaces`
  influxdb_iox/src/commands/sql/observer.rs
  influxdb_iox/src/commands/sql/repl.rs
  influxdb_iox/src/commands/sql/repl_command.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4481 chore(deps): Update datafusion again!!!
  Cargo.lock
  datafusion/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'
