Repository influxdata/influxdb_iox, pull requests merged in 2022-08, with the labels that each got.

#5250 refactor: increase batch size when reading parquet
  parquet_file/src/serialize.rs
  parquet_file/src/storage.rs
Labels: automerge

#5249 fix: do not panic on invalid timestamp ranges
  data_types/src/lib.rs
Labels: automerge

#5251 refactor: bump batch size
  iox_query/src/exec/context.rs
  querier/src/namespace/query_access.rs
  query_tests/cases/in/pushdown.expected
  query_tests/cases/in/several_chunks.expected
Labels: automerge

#5254 chore: reduce log info
  clap_blocks/src/compactor.rs
  parquet_file/src/storage.rs
Labels: automerge

#5256 feat: add metric for TTL cache expiration
  cache_system/src/backend/ttl.rs
  querier/src/cache/namespace.rs
  querier/src/cache/processed_tombstones.rs
  querier/src/cache/table.rs
Labels: automerge

#5257 feat: add metric for predicate-based cache entry removal
  cache_system/src/backend/shared.rs
  querier/src/cache/namespace.rs
  querier/src/cache/parquet_file.rs
  querier/src/cache/partition.rs
  querier/src/cache/read_buffer.rs
  querier/src/cache/tombstones.rs
Labels: automerge

#5268 fix: re-enable querier read buffer cache
  querier/src/chunk/mod.rs
Labels: automerge

#5270 test(influxdb_line_protocol): add value verification test
  influxdb_line_protocol/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5259 feat: fewer buckets but larger ranges for compaction duration histogram
  compactor/src/compact.rs
Labels: automerge

#5271 feat: use two RAM pools in querier
  querier/src/cache/mod.rs
Labels: automerge

#5267 chore: Expose a C API for the IOx LP parser
  Cargo.lock
  influxdb_line_protocol/Cargo.toml
  influxdb_line_protocol/influxdb_line_protocol.h
  influxdb_line_protocol/src/ffi.rs
  influxdb_line_protocol/src/lib.rs
Labels: automerge

#5275 feat: Add information about profiling using Instruments on macOS
  docs/images/instruments_heap_1.png
  docs/images/instruments_heap_stats.png
  docs/profiling.md
Labels: automerge

#5281 feat: support for regex comparisons in storage CLI
  influxrpc_parser/src/predicate.rs
Labels: automerge

#5285 chore: replace `dotenv` with `dotenvy`
  Cargo.lock
  influxdb_iox/Cargo.toml
  influxdb_iox/src/main.rs
  iox_catalog/Cargo.toml
  iox_catalog/src/postgres.rs
  object_store_metrics/Cargo.toml
  sqlx-hotswap-pool/Cargo.toml
  sqlx-hotswap-pool/src/lib.rs
  test_helpers/Cargo.toml
  test_helpers/src/lib.rs
  test_helpers_end_to_end/src/lib.rs
  write_buffer/Cargo.toml
  write_buffer/src/core.rs
Labels: automerge

#5286 feat: add sequencer reset count metric and log to ingester
  ingester/src/stream_handler/handler.rs
Labels: automerge

#5288 chore: Revert "refactor: bump batch size (#5251)"
  iox_query/src/exec/context.rs
  querier/src/namespace/query_access.rs
  query_tests/cases/in/pushdown.expected
  query_tests/cases/in/several_chunks.expected
Labels: automerge

#5255 refactor: remove `--ingster-address`
  clap_blocks/src/querier.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ioxd_querier/src/lib.rs
  querier/src/ingester/mod.rs
  querier/src/lib.rs
Labels: automerge

#5289 fix: make batch size back to 1024 to see if the OOM in the compactor go away
  parquet_file/src/serialize.rs
  parquet_file/src/storage.rs
Labels: automerge

#5291 docs: improve some docstrings in `iox_query`
  predicate/src/lib.rs
  predicate/src/rpc_predicate.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5283 feat: make querier RAM pool split a proper feature
  clap_blocks/src/querier.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ioxd_querier/src/lib.rs
  ioxd_querier/src/rpc/namespace.rs
  querier/src/cache/mod.rs
  querier/src/chunk/mod.rs
  querier/src/database.rs
  querier/src/handler.rs
  querier/src/ingester/mod.rs
  querier/src/namespace/test_util.rs
  querier/src/table/test_util.rs
  query_tests/src/scenarios/util.rs
Labels: automerge

#5290 chore: update datafusion pin
  Cargo.lock
  datafusion/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#5299 fix: compactor-related freeze and shutdown fixes
  compactor/src/handler.rs
  influxdb_iox/src/commands/run/main.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5293 chore: tweak rustc flags
  .cargo/config
  .circleci/config.yml
Labels: automerge

#5298 refactor: simplify creating AND expressions
  datafusion_util/src/lib.rs
  predicate/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5300 chore: Revert "chore: Revert "refactor: bump batch size (#5251)" (#588)"
  iox_query/src/exec/context.rs
  querier/src/namespace/query_access.rs
  query_tests/cases/in/pushdown.expected
  query_tests/cases/in/several_chunks.expected
Labels: automerge

#5309 fix: `compute_split_time` with small step sizes
  compactor/src/utils.rs
Labels: automerge

#5308 refactor: remove `split_members` and use `split_conjunction` from upstream DataFusion
  predicate/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5312 fix: buffer allocation while reading parquet files
  parquet_file/src/storage.rs
Labels: automerge

#5307 feat: instrument kafka aggregated DML batch size
  write_buffer/src/config.rs
  write_buffer/src/kafka/aggregator.rs
  write_buffer/src/kafka/mod.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5311 build: bump rskafka to latest
  .circleci/config.yml
  Cargo.lock
  write_buffer/Cargo.toml
  write_buffer/src/kafka/mod.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5273 feat: chunk pruning metrics
  iox_query/src/pruning.rs
  querier/src/chunk/mod.rs
  querier/src/database.rs
  querier/src/ingester/mod.rs
  querier/src/namespace/mod.rs
  querier/src/namespace/query_access.rs
  querier/src/table/mod.rs
  querier/src/table/query_access.rs
  querier/src/table/test_util.rs
Labels: automerge

#5313 docs: extend profiling docs with stuff I've learned
  docs/profiling.md
Labels: automerge

#5269 chore: add libprotobuf-dev to CI image
  docker/Dockerfile.ci
Labels: automerge

#5301 fix: Support RegExMatch and RegExNotMatch predicates on `_field`
  datafusion_util/src/lib.rs
  predicate/src/rpc_predicate.rs
  predicate/src/rpc_predicate/field_rewrite.rs
  query_functions/src/lib.rs
  query_functions/src/regex.rs
  query_tests/src/influxrpc/read_filter.rs
  query_tests/src/influxrpc/tag_values.rs
  schema/src/lib.rs
  service_grpc_influxrpc/src/expr.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5316 chore: fix `cargo audit`, update deps to get new chrono
  Cargo.lock
  iox_query/src/exec/query_tracing.rs
  iox_time/src/lib.rs
  workspace-hack/Cargo.toml
Labels: automerge

#5303 feat: Compact cold partitions; upgrade a single non-overlapping level 0 file to level 1 without running compaction
  clap_blocks/src/compactor.rs
  compactor/src/compact.rs
  compactor/src/handler.rs
  compactor/src/lib.rs
  compactor/src/parquet_file_filtering.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  ioxd_compactor/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5319 fix: Improve chunk pruning stats and extend with was_not_pruned
  iox_query/src/pruning.rs
  querier/src/namespace/query_access.rs
  querier/src/table/query_access.rs
Labels: automerge

#5317 fix: Install cargo deny in ci image
  .circleci/config.yml
  docker/Dockerfile.ci
Labels: automerge, kodiak: merge.method = 'squash'

#5329 feat: only sleep when there are neither hot nor cold partitions to compact
  compactor/src/handler.rs
Labels: automerge

#5315 fix: make it clear rpc_predicates are only ever specialized when a schema is known
  predicate/src/rpc_predicate.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5332 chore: reduce h2 and hyper logging level in tests
  .circleci/config.yml
Labels: automerge

#5337 chore: ignore a few profiling-related files
  .gitignore
Labels: automerge

#5339 chore: Update datafusion (to get fix for pruning bug)
  Cargo.lock
  datafusion/Cargo.toml
  query_functions/src/selectors.rs
  query_functions/src/selectors/internal.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5338 refactor: use a single chunk filter/pruning step in querier
  querier/src/table/mod.rs
Labels: automerge

#5345 fix: fix logging typo in querier
  querier/src/table/mod.rs
Labels: automerge

#5341 feat: instrument Kafka produce latency
  Cargo.lock
  Cargo.toml
  data_types/src/lib.rs
  iox_time/src/lib.rs
  write_buffer/Cargo.toml
  write_buffer/src/kafka/instrumentation.rs
  write_buffer/src/kafka/mod.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5342 chore: update to rusoto-less object_store
  .guppy/hakari.toml
  Cargo.lock
  Cargo.toml
  clap_blocks/src/object_store.rs
  object_store_metrics/Cargo.toml
  object_store_metrics/src/dummy.rs
  object_store_metrics/src/lib.rs
  workspace-hack/Cargo.toml
Labels: automerge

#5333 fix: update sort key in catalog before adding parquet file to catalog
  ingester/src/data.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5357 chore: temporary allow http always
  clap_blocks/src/object_store.rs
Labels: automerge

#5340 chore: Update datafusion, get `date_bin`
  Cargo.lock
  datafusion/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#5360 chore: Update datafusion / arrow/parquet/arrow-flight and prost/tonic ecosystem
  Cargo.lock
  arrow_util/Cargo.toml
  client_util/Cargo.toml
  compactor/Cargo.toml
  datafusion/Cargo.toml
  generated_types/Cargo.toml
  generated_types/protos/influxdata/platform/storage/predicate.proto
  influxdb_iox/Cargo.toml
  influxdb_iox_client/Cargo.toml
  influxdb_storage_client/Cargo.toml
  ingester/Cargo.toml
  iox_query/Cargo.toml
  iox_tests/Cargo.toml
  ioxd_common/Cargo.toml
  ioxd_querier/Cargo.toml
  mutable_batch/Cargo.toml
  mutable_batch_tests/Cargo.toml
  packers/Cargo.toml
  parquet_file/Cargo.toml
  predicate/Cargo.toml
  querier/Cargo.toml
  query_functions/Cargo.toml
  query_tests/Cargo.toml
  read_buffer/Cargo.toml
  router/Cargo.toml
  schema/Cargo.toml
  schema/src/builder.rs
  service_grpc_catalog/Cargo.toml
  service_grpc_flight/Cargo.toml
  service_grpc_influxrpc/Cargo.toml
  service_grpc_object_store/Cargo.toml
  service_grpc_schema/Cargo.toml
  service_grpc_testing/Cargo.toml
  test_helpers_end_to_end/Cargo.toml
  workspace-hack/Cargo.toml
  write_buffer/Cargo.toml
Labels: automerge

#5364 feat: concurrent garbage collector deletes
  Cargo.lock
  garbage_collector/Cargo.toml
  garbage_collector/src/deleter.rs
  garbage_collector/src/lib.rs
Labels: automerge

#5365 chore: enable and fix warnings for `clap_blocks`
  clap_blocks/src/catalog_dsn.rs
  clap_blocks/src/compactor.rs
  clap_blocks/src/ingester.rs
  clap_blocks/src/lib.rs
  clap_blocks/src/object_store.rs
  clap_blocks/src/querier.rs
  clap_blocks/src/run_config.rs
  clap_blocks/src/socket_addr.rs
  clap_blocks/src/write_buffer.rs
Labels: automerge

#5347 chore: Update docstrings for Partition::sort_keys
  data_types/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5349 chore: make terminology in iox_query::Provider consistent (remove super notation)
  iox_query/src/frontend/common.rs
  iox_query/src/frontend/reorg.rs
  iox_query/src/lib.rs
  iox_query/src/provider.rs
  schema/src/sort.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5368 chore: Warn if a parquet file has no sort key
  compactor/src/parquet_file_combining.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5367 chore: import validate merged schema
  Cargo.lock
  import/Cargo.toml
  import/src/lib.rs
  import/src/schema/fetch.rs
  import/src/schema/merge.rs
  import/src/schema/mod.rs
  import/src/schema/schema_parse.rs
  import/src/schema/validate.rs
  influxdb_iox/src/commands/import/schema.rs
  workspace-hack/Cargo.toml
Labels: automerge

#5371 chore: update libm to 0.2.5
  Cargo.lock
Labels: automerge

#5372 chore: added helper script for a docker catalog
  scripts/docker_catalog.sh
Labels: automerge

#5334 feat: Compactor e2e tests and a "run once" compactor command
  Cargo.lock
  clap_blocks/src/compactor.rs
  compactor/src/handler.rs
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/compactor.rs
  influxdb_iox/src/main.rs
  influxdb_iox/tests/end_to_end_cases/cli.rs
  influxdb_iox/tests/end_to_end_cases/error.rs
  ioxd_compactor/Cargo.toml
  ioxd_compactor/src/lib.rs
  test_helpers_end_to_end/src/lib.rs
  test_helpers_end_to_end/src/mini_cluster.rs
  test_helpers_end_to_end/src/server_fixture.rs
  test_helpers_end_to_end/src/steps.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5366 refactor: more readability improvements to sort key code
  iox_query/src/frontend/reorg.rs
  iox_query/src/provider.rs
  querier/src/ingester/mod.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5346 chore: return a struct with named and documented fields from `compact_persisting_batch`
  ingester/src/compact.rs
  ingester/src/data.rs
Labels: automerge

#5322 fix: do not loose data when Kafka reports that offset is above watermark
  ingester/src/handler.rs
  ingester/src/stream_handler/handler.rs
  write_buffer/src/core.rs
  write_buffer/src/file.rs
  write_buffer/src/kafka/mod.rs
  write_buffer/src/mock.rs
Labels: automerge

#5370 feat: new policy system for caches
  cache_system/src/backend/mod.rs
  cache_system/src/backend/policy/mod.rs
Labels: automerge

#5376 build: bump rskafka
  Cargo.lock
  write_buffer/Cargo.toml
Labels: automerge, kodiak: merge.method = 'merge'

#5215 feat: intern schemas during query planning
  compactor/src/query.rs
  iox_query/src/frontend.rs
  iox_query/src/frontend/reorg.rs
  iox_query/src/provider.rs
  iox_query/src/pruning.rs
  iox_query/src/test.rs
  schema/src/interner.rs
  schema/src/lib.rs
  schema/src/merge.rs
Labels: automerge

#5375 feat: improve cache policies and their testing
  cache_system/src/backend/policy/mod.rs
Labels: automerge

#5377 build: bump rskafka
  Cargo.lock
  write_buffer/Cargo.toml
  write_buffer/src/kafka/mod.rs
Labels: kodiak: merge.method = 'merge'

#5380 build: bump rskafka
  Cargo.lock
  write_buffer/Cargo.toml
Labels: kodiak: merge.method = 'merge'

#5383 docs: router writes to partitions
  router/src/lib.rs
Labels: kodiak: merge.method = 'merge'

#5384 refactor: parallelise Kafka partition client init
  write_buffer/src/kafka/mod.rs
Labels: kodiak: merge.method = 'merge'

#5382 refactor: abstract change requests for cache policies
  cache_system/src/backend/policy/mod.rs
Labels: automerge

#5399 docs: clarify clamping behavior in `TimestampRange::new`
  data_types/src/lib.rs
Labels: automerge

#5396 refactor: port TTL backend to policy framework
  Cargo.lock
  cache_system/Cargo.toml
  cache_system/src/backend/mod.rs
  cache_system/src/backend/policy/mod.rs
  cache_system/src/backend/policy/ttl.rs
  querier/src/cache/namespace.rs
  querier/src/cache/processed_tombstones.rs
  querier/src/cache/table.rs
  workspace-hack/Cargo.toml
Labels: automerge

#5400 chore: do not build benchmark binary for lib targets
  cache_system/Cargo.toml
  iox_data_generator/Cargo.toml
  mutable_batch_lp/Cargo.toml
  mutable_batch_tests/Cargo.toml
  packers/Cargo.toml
  read_buffer/Cargo.toml
  router/Cargo.toml
  sharder/Cargo.toml
Labels: automerge

#5398 refactor: convert `remove_if` feature to policy framework
  cache_system/src/backend/mod.rs
  cache_system/src/backend/policy/mod.rs
  cache_system/src/backend/policy/remove_if.rs
  cache_system/src/backend/policy/ttl.rs
  cache_system/src/backend/shared.rs
  querier/src/cache/namespace.rs
  querier/src/cache/parquet_file.rs
  querier/src/cache/partition.rs
  querier/src/cache/read_buffer.rs
  querier/src/cache/tombstones.rs
Labels: automerge

#5401 fix: `read_buffer` benchmarks array type creation
  read_buffer/benches/database.rs
Labels: automerge

#5385 feat: import schema updates iox catalog
  Cargo.lock
  import/Cargo.toml
  import/src/aggregate_tsm_schema/fetch.rs
  import/src/aggregate_tsm_schema/merge.rs
  import/src/aggregate_tsm_schema/mod.rs
  import/src/aggregate_tsm_schema/update_catalog.rs
  import/src/aggregate_tsm_schema/validate.rs
  import/src/lib.rs
  influxdb_iox/src/commands/import/schema.rs
  schema/src/lib.rs
Labels: automerge

#5405 chore: `cargo-update`
  Cargo.lock
Labels: automerge, kodiak: merge.method = 'squash'

#5411 feat: table name in schema validation errors
  Cargo.lock
  iox_catalog/Cargo.toml
  iox_catalog/src/lib.rs
  router/src/dml_handlers/schema_validation.rs
  router/tests/http.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5409 docs: Edit catalog API docs
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5404 refactor: some prep-work for LRU cache policy
  cache_system/src/backend/policy/mod.rs
Labels: automerge

#5418 chore: Update datafusion pin + other dependencies
  Cargo.lock
  datafusion/Cargo.toml
  predicate/src/rewrite.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5419 chore: Update to (almost) released object_store 0.4.0
  .guppy/hakari.toml
  Cargo.lock
  Cargo.toml
  clap_blocks/Cargo.toml
  compactor/Cargo.toml
  garbage_collector/Cargo.toml
  import/Cargo.toml
  influxdb_iox/Cargo.toml
  ingester/Cargo.toml
  iox_tests/Cargo.toml
  ioxd_compactor/Cargo.toml
  ioxd_ingester/Cargo.toml
  ioxd_querier/Cargo.toml
  ioxd_router/Cargo.toml
  object_store_metrics/Cargo.toml
  parquet_file/Cargo.toml
  querier/Cargo.toml
  router/Cargo.toml
  service_grpc_object_store/Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#5406 refactor: port LRU cache backend to policy framework
  cache_system/benches/addressable_heap.rs
  cache_system/src/addressable_heap.rs
  cache_system/src/backend/mod.rs
  cache_system/src/backend/policy/lru.rs
  cache_system/src/backend/policy/mod.rs
  cache_system/src/backend/policy/ttl.rs
  cache_system/src/lib.rs
  cache_system/src/resource_consumption.rs
  querier/src/cache/mod.rs
  querier/src/cache/namespace.rs
  querier/src/cache/parquet_file.rs
  querier/src/cache/partition.rs
  querier/src/cache/processed_tombstones.rs
  querier/src/cache/projected_schema.rs
  querier/src/cache/ram.rs
  querier/src/cache/read_buffer.rs
  querier/src/cache/table.rs
  querier/src/cache/tombstones.rs
Labels: automerge

#5417 feat: async sleep with `TimeProvider`
  Cargo.lock
  iox_time/Cargo.toml
  iox_time/src/lib.rs
Labels: automerge

#5420 feat: import schema override
  import/src/aggregate_tsm_schema/merge.rs
  import/src/lib.rs
  influxdb_iox/src/commands/import/schema.rs
Labels: automerge

#5348 feat: Add metrics on the size of files created by ingestion and used for compaction
  compactor/src/compact.rs
  compactor/src/lib.rs
  compactor/src/parquet_file_combining.rs
  compactor/src/parquet_file_filtering.rs
  ingester/src/data.rs
  ingester/src/handler.rs
  ingester/src/test_util.rs
  query_tests/src/scenarios/util.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5426 chore: `cargo update`
  Cargo.lock
Labels: automerge

#5415 feat: Add influxdb_influxql_parser crate
  Cargo.lock
  Cargo.toml
  influxdb_influxql_parser/Cargo.toml
  influxdb_influxql_parser/src/identifier.rs
  influxdb_influxql_parser/src/keywords.rs
  influxdb_influxql_parser/src/lib.rs
Labels: automerge, influxql

#5432 chore: `cargo update`
  Cargo.lock
Labels: automerge

#5437 fix: fix intermittent failures in `data::tests::persist`
  ingester/src/data.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5439 chore: cargo update
  Cargo.lock
Labels: automerge

#5431 feat: refresh policy for caches
  Cargo.lock
  cache_system/Cargo.toml
  cache_system/src/backend/policy/integration_tests.rs
  cache_system/src/backend/policy/mod.rs
  cache_system/src/backend/policy/refresh.rs
  cache_system/src/backend/policy/ttl.rs
Labels: automerge

#5427 feat: simple RecordAggregator for write buffer
  dml/src/lib.rs
  write_buffer/src/config.rs
  write_buffer/src/core.rs
  write_buffer/src/kafka/aggregator.rs
  write_buffer/src/kafka/mod.rs
  write_buffer/src/kafka/record_aggregator.rs
Labels: kodiak: merge.method = 'merge'

#5451 feat: sharder API definition
  generated_types/protos/influxdata/iox/sharder/v1/sharder.proto
Labels: automerge, kodiak: merge.method = 'merge'

#5452 refactor(router): use KafkaPartition in sequencer
  ioxd_router/src/lib.rs
  router/benches/e2e.rs
  router/src/dml_handlers/sharded_write_buffer.rs
  router/src/sequencer.rs
  router/tests/http.rs
Labels: kodiak: merge.method = 'merge'

#5456 feat: add file_count_threshold for comapcting cold partitions
  clap_blocks/src/compactor.rs
  compactor/src/compact.rs
  compactor/src/handler.rs
  compactor/src/lib.rs
  compactor/src/parquet_file_filtering.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ioxd_compactor/src/lib.rs
Labels: automerge

#5455 fix: Revert Bump dotenvy from 0.15.1 to 0.15.2 (#5450)
  Cargo.lock
  influxdb_iox/Cargo.toml
  iox_catalog/Cargo.toml
  object_store_metrics/Cargo.toml
  sqlx-hotswap-pool/Cargo.toml
  test_helpers/Cargo.toml
  write_buffer/Cargo.toml
Labels: automerge

#5461 test: Test dotenvy regression
  influxdb_iox/src/main.rs
Labels: automerge

#5462 refactor(proto): update ShardService gRPC defintion
  generated_types/build.rs
  generated_types/protos/influxdata/iox/sharder/v1/sharder.proto
  generated_types/src/lib.rs
Labels: automerge, incompatible protobuf, kodiak: merge.method = 'merge'

#5463 refactor: infallible JumpHash initialisation
  Cargo.lock
  ioxd_router/src/lib.rs
  querier/src/database.rs
  querier/src/namespace/test_util.rs
  querier/src/table/test_util.rs
  query_tests/src/scenarios/util.rs
  router/benches/e2e.rs
  router/benches/schema_validator.rs
  router/src/namespace_cache/sharded_cache.rs
  router/tests/http.rs
  sharder/Cargo.toml
  sharder/benches/sharder.rs
  sharder/src/jumphash.rs
Labels: kodiak: merge.method = 'merge'

#5465 feat(router): sharding lookup gRPC service
  ioxd_router/src/lib.rs
  router/src/server.rs
  router/src/server/grpc.rs
  router/src/server/grpc/sharder.rs
  sharder/src/jumphash.rs
  sharder/src/trait.rs
Labels: kodiak: merge.method = 'merge'

#5447 feat: upsert partition & update sort key for each day in bulk ingest
  Cargo.lock
  import/Cargo.toml
  import/src/aggregate_tsm_schema/merge.rs
  import/src/aggregate_tsm_schema/update_catalog.rs
  import/src/aggregate_tsm_schema/validate.rs
  import/src/lib.rs
  influxdb_iox/src/commands/import/mod.rs
  influxdb_iox/src/commands/import/schema.rs
  influxdb_iox/src/main.rs
Labels: automerge

#5448 test: extend cache-system policy integration tests
  cache_system/src/backend/policy/integration_tests.rs
  cache_system/src/backend/policy/lru.rs
  cache_system/src/backend/policy/refresh.rs
Labels: automerge

#5425 feat: Parse InfluxQL identifiers
  influxdb_influxql_parser/src/identifier.rs
Labels: automerge, influxql

#5479 chore: Upgrade lz4-sys due to RUSTSEC-2022-0051
  Cargo.lock
Labels: automerge

#5477 test: workaround for time > a number
  query_tests/cases/in/timestamps.expected
  query_tests/cases/in/timestamps.sql
Labels: automerge

#5483 refactor: clarify async/runtime requirement in cache system
  cache_system/src/backend/policy/integration_tests.rs
  cache_system/src/backend/policy/refresh.rs
Labels: automerge

#5449 feat: refresh namespace cache before expiration
  ioxd_querier/src/lib.rs
  ioxd_querier/src/rpc/namespace.rs
  querier/src/cache/mod.rs
  querier/src/cache/namespace.rs
  querier/src/chunk/mod.rs
  querier/src/database.rs
  querier/src/handler.rs
  querier/src/ingester/mod.rs
  querier/src/namespace/test_util.rs
  querier/src/table/test_util.rs
  query_tests/Cargo.toml
  query_tests/src/scenarios/util.rs
Labels: automerge

#5488 build: bump object_store
  .guppy/hakari.toml
  Cargo.lock
  Cargo.toml
  deny.toml
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'merge'

#5487 refactor: provide process-wide static strings (version, UUID)
  influxdb_iox/src/main.rs
Labels: automerge

#5474 feat: added rustup toolchain dir to docker buildkit cache
  Dockerfile
Labels: automerge

#5436 fix: Correctly lexigraphically sort `_field` and `_measurement` with upper case tag keys
  iox_query/src/exec/seriesset/series.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5489 feat: add deadline config to backoff system
  Cargo.lock
  backoff/Cargo.toml
  backoff/src/lib.rs
Labels: automerge

#5467 fix: optimizations for metadata fetch and chunk pruning
  iox_query/src/frontend/common.rs
  iox_query/src/provider.rs
  iox_query/src/pruning.rs
  querier/src/cache/mod.rs
  querier/src/cache/partition.rs
  querier/src/cache/table.rs
  querier/src/chunk/mod.rs
  querier/src/ingester/mod.rs
  querier/src/namespace/query_access.rs
  querier/src/table/mod.rs
  querier/src/table/query_access.rs
  querier/src/table/state_reconciler.rs
Labels: automerge

#5433 chore: Update datafusion (with new sqlparser release) - option 1
  Cargo.lock
  datafusion/Cargo.toml
  query_tests/cases/in/basic.expected
  query_tests/cases/in/basic.sql
  query_tests/cases/in/timestamps.expected
  query_tests/cases/in/timestamps.sql
Labels: automerge, kodiak: merge.method = 'squash'

#5470 feat: Renaming kafka topic types
  compactor/src/compact.rs
  compactor/src/garbage_collector.rs
  data_types/src/lib.rs
  garbage_collector/src/checker.rs
  generated_types/protos/influxdata/iox/schema/v1/service.proto
  import/src/aggregate_tsm_schema/update_catalog.rs
  influxdb_iox/src/commands/catalog.rs
  influxdb_iox/src/commands/catalog/topic.rs
  influxdb_iox/src/commands/remote/partition.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ingester/src/data.rs
  ingester/src/handler.rs
  ingester/src/lifecycle.rs
  ingester/src/stream_handler/handler.rs
  ingester/src/stream_handler/sink_instrumentation.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_tests/src/util.rs
  ioxd_compactor/src/lib.rs
  ioxd_ingester/src/lib.rs
  ioxd_querier/src/lib.rs
  ioxd_router/src/lib.rs
  querier/src/cache/namespace.rs
  querier/src/handler.rs
  router/src/dml_handlers/ns_autocreation.rs
  router/src/dml_handlers/schema_validation.rs
  router/src/lib.rs
  router/src/namespace_cache/memory.rs
  router/src/namespace_cache/metrics.rs
  router/src/namespace_cache/sharded_cache.rs
  router/src/server/grpc/sharder.rs
  router/tests/http.rs
  service_grpc_catalog/src/lib.rs
  service_grpc_object_store/src/lib.rs
  service_grpc_schema/src/lib.rs
  test_helpers_end_to_end/src/database.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5504 build: bump dotenvy
  Cargo.lock
Labels: kodiak: merge.method = 'merge'

#5505 revert: object store bump
  .guppy/hakari.toml
  Cargo.lock
  Cargo.toml
  deny.toml
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'merge'

#5492 refactor: improve namespace caching in querier
  querier/src/cache/namespace.rs
  querier/src/chunk/mod.rs
  querier/src/database.rs
  querier/src/namespace/mod.rs
  querier/src/namespace/test_util.rs
  querier/src/table/mod.rs
  query_tests/src/scenarios/util.rs
Labels: automerge

#5509 chore: update object_store to test IMDSv1 fallback
  .guppy/hakari.toml
  Cargo.lock
  Cargo.toml
  clap_blocks/src/object_store.rs
  deny.toml
  workspace-hack/Cargo.toml
Labels: automerge

#5510 fix: remove empty parquet panic
  compactor/src/parquet_file_combining.rs
  parquet_file/src/serialize.rs
  parquet_file/src/storage.rs
  parquet_file/tests/metadata.rs
Labels: kodiak: merge.method = 'merge'

#5471 feat: More accurate memory estimate for compaction
  clap_blocks/src/compactor.rs
  compactor/src/compact.rs
  compactor/src/handler.rs
  compactor/src/lib.rs
  compactor/src/parquet_file_filtering.rs
  data_types/src/lib.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ingester/src/data.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  ioxd_compactor/src/lib.rs
Labels: automerge

#5519 chore: Update datafusion + arrow/parquet to `21.0.0`
  Cargo.lock
  arrow_util/Cargo.toml
  compactor/Cargo.toml
  datafusion/Cargo.toml
  influxdb_iox/Cargo.toml
  influxdb_iox_client/Cargo.toml
  ingester/Cargo.toml
  iox_query/Cargo.toml
  iox_tests/Cargo.toml
  ioxd_querier/Cargo.toml
  mutable_batch/Cargo.toml
  packers/Cargo.toml
  parquet_file/Cargo.toml
  parquet_file/src/serialize.rs
  parquet_file/src/storage.rs
  predicate/Cargo.toml
  querier/Cargo.toml
  query_functions/Cargo.toml
  query_tests/Cargo.toml
  read_buffer/Cargo.toml
  schema/Cargo.toml
  scripts/update_arrow_deps.py
  service_grpc_flight/Cargo.toml
  service_grpc_influxrpc/Cargo.toml
  test_helpers_end_to_end/Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#5521 feat(ingester): restrict partition row count
  clap_blocks/src/ingester.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ingester/src/data.rs
  ingester/src/handler.rs
  ingester/src/lifecycle.rs
  ingester/src/stream_handler/handler.rs
  ioxd_ingester/src/lib.rs
  query_tests/src/scenarios/util.rs
Labels: kodiak: merge.method = 'merge'

#5520 refactor: use concrete backend type in `CacheDriver`
  cache_system/src/backend/mod.rs
  cache_system/src/cache/driver.rs
  cache_system/src/cache/metrics.rs
  querier/src/cache/namespace.rs
  querier/src/cache/parquet_file.rs
  querier/src/cache/partition.rs
  querier/src/cache/processed_tombstones.rs
  querier/src/cache/projected_schema.rs
  querier/src/cache/read_buffer.rs
  querier/src/cache/tombstones.rs
Labels: automerge

#5507 feat: router write line protocol duration
  router/src/server/http.rs
Labels: automerge

#5518 fix: loop forever in compact_hot_partition_candidates
  compactor/src/compact_hot_partitions.rs
  compactor/src/handler.rs
  compactor/src/lib.rs
  compactor/src/parquet_file_filtering.rs
Labels: automerge

#5523 refactor: Use more iox test utils in compactor tests
  compactor/src/compact_hot_partitions.rs
  iox_tests/src/util.rs
Labels: automerge, kodiak: merge.method = 'merge'

#5460 feat: Teach IOx how to parse InfluxQL literals
  influxdb_influxql_parser/src/identifier.rs
  influxdb_influxql_parser/src/keywords.rs
  influxdb_influxql_parser/src/lib.rs
  influxdb_influxql_parser/src/literal.rs
  influxdb_influxql_parser/src/string.rs
Labels: automerge, influxql
