Repository influxdata/influxdb_iox, pull requests merged in 2022-12, with the labels that each got.

#6247 feat: Add a feature flag to switch to the router RPC write path
  Cargo.lock
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/run/mod.rs
  influxdb_iox/src/commands/run/router_rpc_write.rs
  ioxd_router/Cargo.toml
  ioxd_router/src/lib.rs
  router/Cargo.toml
  router/src/dml_handlers/rpc_write.rs
  router/src/server.rs
  router/src/server/grpc.rs
Labels: automerge, kafkaless

#6294 Revert "chore: Update Datafusion and arrow/arrow-flight/parquet to `28.0.0` (#6279)"
  Cargo.lock
  Cargo.toml
  arrow_util/src/optimize.rs
  ingester2/Cargo.toml
  parquet_file/Cargo.toml
  parquet_file/src/metadata.rs
  schema/src/lib.rs
  trace_exporters/Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#6293 refactor(ingester2): document reordering / remove seqnum ranges
  ingester2/src/buffer_tree/namespace.rs
  ingester2/src/buffer_tree/partition.rs
  ingester2/src/buffer_tree/partition/buffer.rs
  ingester2/src/buffer_tree/partition/buffer/state_machine.rs
  ingester2/src/buffer_tree/partition/buffer/state_machine/buffering.rs
  ingester2/src/buffer_tree/partition/buffer/state_machine/snapshot.rs
  ingester2/src/buffer_tree/partition/resolver/cache.rs
  ingester2/src/buffer_tree/partition/resolver/catalog.rs
  ingester2/src/buffer_tree/partition/resolver/trait.rs
  ingester2/src/buffer_tree/root.rs
  ingester2/src/buffer_tree/table.rs
  ingester2/src/lib.rs
  ingester2/src/sequence_range.rs
Labels: automerge, kodiak: merge.method = 'merge', kafkaless

#6298 refactor: revert "simplify `SeriesSet` (#6277)"
  iox_query/src/exec/seriesset.rs
  iox_query/src/exec/seriesset/converter.rs
  iox_query/src/exec/seriesset/series.rs
  service_grpc_influxrpc/src/data.rs
Labels: automerge

#6299 refactor(ingester2): cache more hot partitions
  ingester2/src/init.rs
Labels: automerge, kodiak: merge.method = 'merge', kafkaless

#6296 chore: Update Datafusion and arrow/arrow-flight/parquet to `28.0.0` again
  Cargo.lock
  Cargo.toml
  arrow_util/src/optimize.rs
  ingester2/Cargo.toml
  parquet_file/Cargo.toml
  parquet_file/src/metadata.rs
  schema/src/lib.rs
  trace_exporters/Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge

#6301 refactor: bring back "stream-based `SeriesSetConvert::convert` interface (#6282)"
  iox_query/src/exec/context.rs
  iox_query/src/exec/seriesset/converter.rs
Labels: automerge

#6300 feat(ingester2): WAL entry replay at startup
  ingester2/src/init.rs
  ingester2/src/init/wal_replay.rs
  ingester2/src/test_util.rs
Labels: automerge, kodiak: merge.method = 'merge', kafkaless

#6302 feat(ingester2): periodic WAL rotation
  ingester2/src/init.rs
  ingester2/src/init/wal_replay.rs
  ingester2/src/wal/mod.rs
  ingester2/src/wal/rotate_task.rs
  wal/src/lib.rs
  wal/tests/end_to_end.rs
Labels: kodiak: merge.method = 'merge'

#6297 chore: Upgrade datafusion to get memory limits
  Cargo.lock
  Cargo.toml
  iox_query/src/frontend/influxrpc.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#6285 refactor: stream-based series-set conversion
  iox_query/src/exec/context.rs
  iox_query/src/exec/seriesset/converter.rs
  iox_query/src/exec/seriesset/series.rs
Labels: automerge

#6305 feat: Add cap limit on number of partitions to be compacted in parallel
  clap_blocks/src/compactor.rs
  compactor/src/cold.rs
  compactor/src/compact.rs
  compactor/src/handler.rs
  compactor/src/hot.rs
  compactor/src/lib.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ioxd_compactor/src/lib.rs
Labels: automerge

#6307 docs: Add 2 new config params that can be adjusted to avoid OOMs
  docs/compactor.md
Labels: automerge

#6292 feat: Add mutable visitor to InfluxQL parser crate
  influxdb_influxql_parser/src/lib.rs
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__delete_statement-2.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__delete_statement-3.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__delete_statement-4.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__delete_statement.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__drop_measurement_statement.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__explain_statement.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__select_statement-2.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__select_statement-3.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__select_statement-4.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__select_statement-5.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__select_statement-6.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__select_statement.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__show_databases_statement.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__show_field_keys_statement-2.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__show_field_keys_statement-3.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__show_field_keys_statement-4.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__show_field_keys_statement.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__show_measurements_statement-2.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__show_measurements_statement-3.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__show_measurements_statement-4.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__show_measurements_statement-5.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__show_measurements_statement-6.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__show_measurements_statement-7.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__show_measurements_statement.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__show_retention_policies_statement-2.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__show_retention_policies_statement.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__show_tag_keys_statement-2.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__show_tag_keys_statement.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__show_tag_values_statement-2.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__show_tag_values_statement-3.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__show_tag_values_statement-4.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__show_tag_values_statement.snap
  influxdb_influxql_parser/src/visit.rs
  influxdb_influxql_parser/src/visit_mut.rs
Labels: automerge, influxql

#6311 refactor: improve DF error handling
  datafusion_util/src/watch.rs
  iox_query/src/exec/context.rs
  service_common/src/error.rs
Labels: automerge

#6312 test: simplify test executors
  Cargo.lock
  executor/Cargo.toml
  executor/src/lib.rs
  ingester/src/compact.rs
  ingester/src/data.rs
  ingester/src/handler.rs
  ingester/src/test_util.rs
  ingester/tests/common/mod.rs
  iox_query/Cargo.toml
  iox_query/src/exec.rs
  iox_query/src/exec/context.rs
  iox_query/src/frontend.rs
  iox_query/src/frontend/influxrpc.rs
  iox_query/src/frontend/reorg.rs
  iox_query/src/plan/influxql.rs
  iox_query/src/plan/stringset.rs
  querier/src/handler.rs
  service_common/src/test_util.rs
Labels: automerge

#6306 refactor(ingester2): namespace name in partition
  ingester2/src/buffer_tree/namespace.rs
  ingester2/src/buffer_tree/partition.rs
  ingester2/src/buffer_tree/partition/resolver/cache.rs
  ingester2/src/buffer_tree/partition/resolver/catalog.rs
  ingester2/src/buffer_tree/partition/resolver/mock.rs
  ingester2/src/buffer_tree/partition/resolver/trait.rs
  ingester2/src/buffer_tree/root.rs
  ingester2/src/buffer_tree/table.rs
Labels: automerge, kodiak: merge.method = 'merge', kafkaless

#6316 perf(ingester2): partition persist queue
  ingester2/src/buffer_tree/partition.rs
  ingester2/src/buffer_tree/partition/persisting.rs
Labels: automerge, kodiak: merge.method = 'merge', kafkaless

#6320 fix: Use client_util GrpcConnection instead of tonic Channel
  ioxd_router/src/lib.rs
  router/src/dml_handlers/rpc_write.rs
  router/src/dml_handlers/rpc_write/client.rs
Labels: automerge

#6318 feat(ingester2): parallel partition persistence
  Cargo.lock
  ingester2/Cargo.toml
  ingester2/src/buffer_tree/partition.rs
  ingester2/src/lib.rs
  ingester2/src/persist/actor.rs
  ingester2/src/persist/compact.rs
  ingester2/src/persist/context.rs
  ingester2/src/persist/handle.rs
  ingester2/src/persist/mod.rs
Labels: automerge, kodiak: merge.method = 'merge', kafkaless

#6322 refactor(ingester2): BufferTree partition iterator
  ingester2/src/buffer_tree/namespace.rs
  ingester2/src/buffer_tree/root.rs
  ingester2/src/buffer_tree/table.rs
Labels: automerge, kodiak: merge.method = 'merge', kafkaless

#6323 feat(ingester2): persist data when rotating WAL segments
  Cargo.lock
  clap_blocks/src/ingester2.rs
  influxdb_iox/src/commands/run/ingester2.rs
  ingester2/src/init.rs
  ingester2/src/persist/actor.rs
  ingester2/src/persist/handle.rs
  ingester2/src/persist/mod.rs
  ingester2/src/wal/rotate_task.rs
  ioxd_ingester2/Cargo.toml
  ioxd_ingester2/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge', kafkaless

#6324 feat(ingester2): drop WAL segments after persist
  ingester2/src/wal/rotate_task.rs
Labels: kodiak: merge.method = 'merge', kafkaless

#6325 test: track_caller for make_write_op
  ingester2/src/test_util.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6326 feat(ingester2): drop empty WAL files
  ingester2/src/init/wal_replay.rs
Labels: automerge, kodiak: merge.method = 'merge', kafkaless

#6327 chore: remove old comment
  ingester2/src/init.rs
Labels: automerge, kodiak: merge.method = 'merge', kafkaless

#6328 fix: do not panic when writer disconnects
  wal/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge', kafkaless

#6314 fix: gRPC errors regarding group cols
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/read_group.rs
  iox_query/src/exec/seriesset/converter.rs
  iox_query/src/frontend/influxrpc.rs
  predicate/src/rpc_predicate.rs
Labels: automerge

#6343 fix: support InfluxRPC OR-chains w/ arbitrary child nodes
  service_grpc_influxrpc/src/expr.rs
Labels: automerge

#6346 feat: allow enabling/disabling ns autocreation in router
  clap_blocks/src/router.rs
  clap_blocks/src/router_rpc_write.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/src/commands/run/router_rpc_write.rs
  ioxd_router/src/lib.rs
  router/src/namespace_resolver.rs
  router/src/namespace_resolver/ns_autocreation.rs
  router/src/server/http.rs
  router/tests/http.rs
Labels: automerge

#6345 fix: account for memory allocations in InfluxRPC group outputs
  iox_query/src/exec/context.rs
  iox_query/src/exec/seriesset/converter.rs
  iox_query/src/exec/seriesset/series.rs
  query_tests/src/influxrpc/util.rs
  service_grpc_influxrpc/src/service.rs
Labels: automerge

#6349 chore: Upgrade datafusion to get correct support for multi-part identifiers
  Cargo.lock
  Cargo.toml
  datafusion_util/src/config.rs
  iox_query/src/frontend/influxrpc.rs
  iox_query/src/lib.rs
  iox_query/src/provider.rs
  iox_query/src/provider/physical.rs
  iox_query/src/test.rs
  parquet_to_line_protocol/Cargo.toml
  parquet_to_line_protocol/src/lib.rs
  querier/src/namespace/query_access.rs
  querier/src/system_tables/mod.rs
  querier/src/table/mod.rs
  querier/src/table/query_access/mod.rs
  query_tests/cases/in/dedup_and_predicates_parquet.expected
  query_tests/cases/in/dedup_and_predicates_parquet_ingester.expected
  query_tests/cases/in/duplicates_ingester.expected
  query_tests/cases/in/duplicates_parquet.expected
  query_tests/cases/in/duplicates_parquet_many.expected
  query_tests/cases/in/periods.expected
  query_tests/cases/in/periods.sql
  query_tests/cases/in/pushdown.expected
  query_tests/cases/in/retention.expected
  query_tests/cases/in/several_chunks.expected
  query_tests/cases/in/two_chunks.expected
  query_tests/src/cases.rs
  query_tests/src/scenarios.rs
  query_tests/src/table_schema.rs
  schema/src/lib.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#6353 refactor: add additional span around chunk spans
  querier/src/table/mod.rs
Labels: automerge

#6337 feat: Make a mode for the querier to use ingester2 instead, behind the rpc_write feature flag
  clap_blocks/Cargo.toml
  clap_blocks/src/querier.rs
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/src/commands/run/querier.rs
  ioxd_querier/src/lib.rs
  ioxd_querier/src/rpc/namespace.rs
  querier/src/database.rs
  querier/src/handler.rs
  querier/src/ingester/mod.rs
  querier/src/ingester/test_util.rs
  querier/src/lib.rs
  querier/src/namespace/mod.rs
  querier/src/table/mod.rs
  querier/src/table/test_util.rs
Labels: automerge, kodiak: merge.method = 'merge', kafkaless

#6355 fix: Remove conflicting arguments from the RouterRpcWriteConfig
  clap_blocks/src/router_rpc_write.rs
  influxdb_iox/src/commands/run/router_rpc_write.rs
  ioxd_router/src/lib.rs
Labels: automerge

#6354 feat: rate-limit Jaeger UDP messages
  Cargo.lock
  trace_exporters/Cargo.toml
  trace_exporters/src/export.rs
  trace_exporters/src/jaeger.rs
  trace_exporters/src/lib.rs
  trace_exporters/src/rate_limiter.rs
Labels: automerge

#6359 refactor: avoid string-hashing of parquet file column names
  querier/src/cache/namespace.rs
  querier/src/cache/projected_schema.rs
  querier/src/chunk/mod.rs
  querier/src/namespace/mod.rs
Labels: automerge

#6360 refactor: store reverse column ID map for cached tables
  querier/src/cache/namespace.rs
  querier/src/cache/projected_schema.rs
Labels: automerge

#6362 chore: patch object_store to get apache#3274
  Cargo.lock
  Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#6363 chore: Update DataFusion (get median fix and automatic string to timestamp coercion)
  Cargo.lock
  Cargo.toml
  predicate/src/lib.rs
  query_tests/cases/in/basic.expected
  query_tests/cases/in/basic.sql
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#6356 feat: Add --token CLI argument, improve update docs about writing
  docs/cli.md
  influxdb_iox/src/main.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6374 refactor: use column IDs for partition cache invalidation
  querier/src/cache/partition.rs
  querier/src/chunk/mod.rs
  querier/src/chunk/query_access.rs
  querier/src/ingester/mod.rs
  querier/src/ingester/test_util.rs
  querier/src/table/mod.rs
  querier/src/table/state_reconciler.rs
  querier/src/table/test_util.rs
Labels: automerge

#6375 refactor: faster sort key calculation
  querier/src/cache/partition.rs
  querier/src/chunk/mod.rs
Labels: automerge

#6357 feat: Identify each run of an ingester with a Uuid
  .circleci/config.yml
  Cargo.lock
  clap_blocks/src/querier.rs
  generated_types/protos/influxdata/iox/ingester/v1/query.proto
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/tests/end_to_end_cases/ingester.rs
  ingester/src/server/grpc/query.rs
  ingester2/src/init.rs
  ingester2/src/server/grpc/query.rs
  querier/src/ingester/mod.rs
  query_tests/src/scenarios/util.rs
  test_helpers_end_to_end/Cargo.toml
  test_helpers_end_to_end/src/config.rs
  test_helpers_end_to_end/src/mini_cluster.rs
  test_helpers_end_to_end/src/server_fixture.rs
  test_helpers_end_to_end/src/server_type.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6373 chore: Implemented ZeroOrMore item container
  influxdb_influxql_parser/src/common.rs
  influxdb_influxql_parser/src/select.rs
  influxdb_influxql_parser/src/show_tag_values.rs
  influxdb_influxql_parser/src/simple_from_clause.rs
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__explain_statement.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__select_statement-2.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__select_statement-3.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__select_statement-4.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__select_statement-5.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__select_statement-6.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__select_statement.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__explain_statement.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__select_statement-2.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__select_statement-3.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__select_statement-4.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__select_statement-5.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__select_statement-6.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__select_statement.snap
Labels: automerge, influxql

#6387 chore: editor config spacing for shell scripts
  .editorconfig
Labels: automerge, kodiak: merge.method = 'merge'

#6386 feat(ingester2): log persist active & queue timings
  ingester2/src/persist/context.rs
  ingester2/src/persist/handle.rs
  ingester2/src/wal/rotate_task.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6377 test(ingester2): WAL replay benchmark
  Cargo.lock
  ingester2/Cargo.toml
  ingester2/benches/README.md
  ingester2/benches/wal.rs
  ingester2/src/dml_sink/mock_sink.rs
  ingester2/src/dml_sink/mod.rs
  ingester2/src/dml_sink/trait.rs
  ingester2/src/init.rs
  ingester2/src/init/wal_replay.rs
  ingester2/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6393 fix(ingester2): persist deadlock
  clap_blocks/src/ingester2.rs
  ingester2/src/init.rs
  ingester2/src/persist/actor.rs
  ingester2/src/persist/context.rs
  ingester2/src/persist/handle.rs
  ingester2/src/persist/mod.rs
  ingester2/src/wal/rotate_task.rs
  ioxd_ingester2/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge', kafkaless

#6376 refactor: improve concurrency during parquet chunk creation
  querier/src/table/mod.rs
Labels: automerge

#6392 feat: Document IOx Flight API and add convenience methods
  generated_types/protos/influxdata/iox/querier/v1/flight.proto
  influxdb_iox/src/commands/query.rs
  influxdb_iox/src/commands/sql/repl.rs
  influxdb_iox_client/src/client.rs
  influxdb_iox_client/src/client/flight/low_level.rs
  influxdb_iox_client/src/client/flight/mod.rs
  test_helpers_end_to_end/src/client.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6389 test: regex baseline test, expose scalar functions via SQL
  iox_query/src/exec/context.rs
  query_functions/src/lib.rs
  query_functions/src/regex.rs
  query_functions/src/registry.rs
  query_functions/src/window.rs
  query_tests/cases/in/pushdown.expected
  query_tests/cases/in/pushdown.sql
Labels: automerge, kodiak: merge.method = 'squash'

#6396 chore: Upgrade datafusion / arrow to 29.0.0 to get flightsql client
  Cargo.lock
  Cargo.toml
  iox_query/src/exec/seriesset/series.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#6397 feat: make data generator handle failed requests
  iox_data_generator/benches/point_generation.rs
  iox_data_generator/src/agent.rs
  iox_data_generator/src/bin/iox_data_generator.rs
  iox_data_generator/src/lib.rs
Labels: automerge

#6400 refactor: speed up partition sort key syncing
  querier/src/chunk/mod.rs
  querier/src/ingester/mod.rs
  querier/src/table/mod.rs
  querier/src/table/state_reconciler.rs
Labels: automerge

#6365 feat: Keep track of & report # of Parquet files persisted, invalidate querier cache
  generated_types/protos/influxdata/iox/ingester/v1/query.proto
  influxdb_iox/src/commands/run/querier.rs
  influxdb_iox/tests/end_to_end_cases/ingester.rs
  ingester/src/server/grpc/query.rs
  ingester2/src/buffer_tree/partition.rs
  ingester2/src/buffer_tree/table.rs
  ingester2/src/query/partition_response.rs
  ingester2/src/server/grpc/query.rs
  ioxd_querier/src/lib.rs
  querier/src/cache/parquet_file.rs
  querier/src/ingester/mod.rs
  querier/src/table/mod.rs
  querier/src/table/test_util.rs
  query_tests/src/scenarios/util.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6399 feat: optimize wal with batching
  Cargo.lock
  generated_types/protos/influxdata/iox/wal/v1/wal.proto
  ingester2/benches/wal.rs
  ingester2/src/dml_sink/trait.rs
  ingester2/src/init.rs
  ingester2/src/init/wal_replay.rs
  ingester2/src/wal/rotate_task.rs
  ingester2/src/wal/traits.rs
  ingester2/src/wal/wal_sink.rs
  wal/Cargo.toml
  wal/src/blocking/reader.rs
  wal/src/blocking/writer.rs
  wal/src/lib.rs
  wal/tests/end_to_end.rs
Labels: automerge, kafkaless

#6405 feat: Increase default all-in-one compactor memory to 300MB and expose it as a setting
  influxdb_iox/src/commands/run/all_in_one.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6407 chore: Upgrade datafusion
  Cargo.lock
  Cargo.toml
  parquet_to_line_protocol/src/lib.rs
  query_functions/src/selectors.rs
  query_functions/src/selectors/internal.rs
  workspace-hack/Cargo.toml
Labels: automerge

#6404 refactor: clean up querier code base
  querier/src/cache/projected_schema.rs
  querier/src/database.rs
  querier/src/lib.rs
  querier/src/namespace/mod.rs
  querier/src/parquet/creation.rs
  querier/src/parquet/mod.rs
  querier/src/parquet/query_access.rs
  querier/src/table/mod.rs
  querier/src/table/query_access/metrics.rs
  querier/src/table/query_access/mod.rs
  querier/src/table/state_reconciler.rs
  querier/src/table/state_reconciler/interface.rs
  querier/src/table/test_util.rs
Labels: automerge

#6394 feat: lower Influx regex expressions to DF regex expressions
  iox_query/src/exec/context.rs
  iox_query/src/lib.rs
  iox_query/src/logical_optimizer/influx_regex_to_datafusion_regex.rs
  iox_query/src/logical_optimizer/mod.rs
  query_functions/src/lib.rs
  query_functions/src/regex.rs
  query_tests/cases/in/pushdown.expected
Labels: automerge

#6413 feat(ingester2): out-of-order partition persist
  ingester2/src/buffer_tree/partition.rs
Labels: kodiak: merge.method = 'merge', kafkaless

#6412 feat(deferred_load): peek() immediate values
  ingester2/src/deferred_load.rs
Labels: kodiak: merge.method = 'merge', kafkaless

#6406 fix: Remove the rpc_write feature flag and use INFLUXDB_IOX_MODE env var instead
  .circleci/config.yml
  Cargo.lock
  clap_blocks/Cargo.toml
  clap_blocks/src/lib.rs
  clap_blocks/src/querier.rs
  clap_blocks/src/router2.rs
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/src/commands/run/ingester.rs
  influxdb_iox/src/commands/run/ingester2.rs
  influxdb_iox/src/commands/run/mod.rs
  influxdb_iox/src/commands/run/querier.rs
  influxdb_iox/src/commands/run/router.rs
  influxdb_iox/src/commands/run/router2.rs
  influxdb_iox/tests/end_to_end_cases/ingester.rs
  influxdb_iox/tests/end_to_end_cases/mod.rs
  influxdb_iox/tests/end_to_end_cases/mode_switching.rs
  ioxd_querier/src/lib.rs
  ioxd_router/Cargo.toml
  ioxd_router/src/lib.rs
  test_helpers_end_to_end/Cargo.toml
  test_helpers_end_to_end/src/config.rs
  test_helpers_end_to_end/src/mini_cluster.rs
  test_helpers_end_to_end/src/server_fixture.rs
  test_helpers_end_to_end/src/server_type.rs
Labels: automerge, kodiak: merge.method = 'merge', kafkaless

#6416 feat(ingester2): optimal persist parallelism
  Cargo.lock
  clap_blocks/src/ingester2.rs
  ingester2/Cargo.toml
  ingester2/src/init.rs
  ingester2/src/persist/backpressure.rs
  ingester2/src/persist/context.rs
  ingester2/src/persist/handle.rs
  ingester2/src/server/grpc/rpc_write.rs
  iox_query/src/exec.rs
  ioxd_ingester2/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6192 feat: warm compaction
  clap_blocks/src/compactor.rs
  compactor/src/cold.rs
  compactor/src/compact.rs
  compactor/src/handler.rs
  compactor/src/hot.rs
  compactor/src/lib.rs
  compactor/src/warm.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_tests/src/util.rs
  ioxd_compactor/src/lib.rs
Labels: automerge

#6425 feat: add size_data to mutable batch
  Cargo.lock
  mutable_batch/Cargo.toml
  mutable_batch/src/column.rs
  mutable_batch/src/lib.rs
Labels: automerge

#6426 feat(ingester2): hot partition persistence
  clap_blocks/src/ingester2.rs
  ingester2/src/buffer_tree/mod.rs
  ingester2/src/buffer_tree/namespace.rs
  ingester2/src/buffer_tree/partition.rs
  ingester2/src/buffer_tree/partition/buffer.rs
  ingester2/src/buffer_tree/partition/buffer/always_some.rs
  ingester2/src/buffer_tree/partition/buffer/mutable_buffer.rs
  ingester2/src/buffer_tree/partition/buffer/state_machine/buffering.rs
  ingester2/src/buffer_tree/post_write/mock.rs
  ingester2/src/buffer_tree/post_write/mod.rs
  ingester2/src/buffer_tree/post_write/trait.rs
  ingester2/src/buffer_tree/root.rs
  ingester2/src/buffer_tree/table.rs
  ingester2/src/init.rs
  ingester2/src/persist/handle.rs
  ingester2/src/persist/hot_partitions.rs
  ingester2/src/persist/mod.rs
  ingester2/src/wal/rotate_task.rs
  ioxd_ingester2/src/lib.rs
Labels: kodiak: merge.method = 'merge', kafkaless

#6422 feat: Implement creating Tickets in gRPC service
  service_grpc_flight/src/lib.rs
  service_grpc_flight/src/request.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6428 fix: Correct *some* problems mkm found with ingester2/querier
  .circleci/config.yml
  ingester2/src/buffer_tree/namespace.rs
  ingester2/src/buffer_tree/partition.rs
  ingester2/src/buffer_tree/partition/resolver/cache.rs
  ingester2/src/buffer_tree/partition/resolver/catalog.rs
  ingester2/src/buffer_tree/partition/resolver/mock.rs
  ingester2/src/buffer_tree/partition/resolver/trait.rs
  ingester2/src/buffer_tree/root.rs
  ingester2/src/buffer_tree/table.rs
  ingester2/src/init.rs
  ingester2/src/lib.rs
  ingester2/src/persist/context.rs
  ingester2/src/persist/handle.rs
  ingester2/src/query/partition_response.rs
  ingester2/src/query/response.rs
  ingester2/src/server/grpc/query.rs
  ingester2/src/test_util.rs
Labels: automerge, kodiak: merge.method = 'merge', kafkaless

#6429 feat: add data generator schema to simulate eu load
  iox_data_generator/schemas/eu_central.toml
Labels: automerge

#6427 refactor: Extract common ArrowFlight client into iox_arrow_flight
  Cargo.lock
  Cargo.toml
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/query.rs
  influxdb_iox/src/commands/query_ingester.rs
  influxdb_iox/tests/end_to_end_cases/cli.rs
  influxdb_iox/tests/end_to_end_cases/ingester.rs
  influxdb_iox/tests/end_to_end_cases/querier.rs
  influxdb_iox_client/Cargo.toml
  influxdb_iox_client/src/client/flight/low_level.rs
  influxdb_iox_client/src/client/flight/mod.rs
  iox_arrow_flight/Cargo.toml
  iox_arrow_flight/src/client.rs
  iox_arrow_flight/src/error.rs
  iox_arrow_flight/src/lib.rs
  querier/Cargo.toml
  querier/src/ingester/circuit_breaker.rs
  querier/src/ingester/flight_client.rs
  querier/src/ingester/mod.rs
  querier/src/lib.rs
  query_tests/Cargo.toml
  query_tests/src/scenarios/util.rs
  test_helpers_end_to_end/src/error.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#6437 docs: fix incomplete comment
  ingester2/src/persist/backpressure.rs
Labels: kodiak: merge.method = 'merge'

#6436 refactor(ingester2): query types
  ingester2/src/buffer_tree/table.rs
  ingester2/src/query/partition_response.rs
  ingester2/src/query/response.rs
  ingester2/src/server/grpc/query.rs
Labels: automerge, kodiak: merge.method = 'merge', kafkaless

#6440 fix: Make multiple ingester addresses in the router work
  ioxd_router/src/lib.rs
Labels: automerge

#6438 refactor: Make arrow flight client return `futures::Streams`
  influxdb_iox/src/commands/query.rs
  influxdb_iox/src/commands/query_ingester.rs
  influxdb_iox/src/commands/sql/repl.rs
  influxdb_iox/tests/end_to_end_cases/ingester.rs
  influxdb_iox_client/src/client/flight/mod.rs
  iox_arrow_flight/src/client.rs
  querier/src/ingester/circuit_breaker.rs
  querier/src/ingester/flight_client.rs
  querier/src/ingester/mod.rs
  query_tests/src/scenarios/util.rs
  test_helpers_end_to_end/src/client.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6443 fix: Disable parquet file filtering in the querier based on max seq num in RPC write mode
  querier/src/table/mod.rs
  querier/src/table/state_reconciler.rs
Labels: automerge

#6442 chore: Update datafusion pin
  Cargo.lock
  Cargo.toml
  datafusion_util/src/lib.rs
  iox_query/src/exec/context.rs
  iox_query/src/exec/seriesset/converter.rs
  iox_query/src/frontend/influxrpc.rs
  iox_query/src/logical_optimizer/influx_regex_to_datafusion_regex.rs
  iox_query/src/logical_optimizer/mod.rs
  predicate/src/rpc_predicate/rewrite.rs
  query_tests/src/influxrpc/util.rs
  service_grpc_influxrpc/src/service.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#6441 fix: Do not panic when bad arguments are passed to selectors
  query_functions/src/selectors.rs
  query_tests/src/sql.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6447 feat(catalog): linearise sort key updates
  compactor/src/compact.rs
  import/src/aggregate_tsm_schema/update_catalog.rs
  ingester/src/buffer_tree/partition.rs
  ingester/src/buffer_tree/partition/resolver/sort_key.rs
  ingester/src/data.rs
  ingester2/src/buffer_tree/partition.rs
  ingester2/src/buffer_tree/partition/resolver/sort_key.rs
  ingester2/src/persist/context.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_tests/src/util.rs
  querier/src/cache/partition.rs
Labels: kodiak: merge.method = 'merge', kafkaless

#6448 fix(ingester2): handle concurrent sort key updates
  ingester2/src/persist/context.rs
  ingester2/src/persist/handle.rs
  ingester2/src/persist/worker.rs
Labels: kodiak: merge.method = 'merge', kafkaless

#6398 feat: FlightSQL Milestone 2 basic FlightSQL client and FlightSQL server implementation and plumbing
  Cargo.lock
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
  influxdb_iox/tests/end_to_end_cases/mod.rs
  iox_arrow_flight/src/flightsql.rs
  iox_arrow_flight/src/lib.rs
  service_grpc_flight/Cargo.toml
  service_grpc_flight/src/lib.rs
  service_grpc_flight/src/request.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6453 refactor(persist): explicit worker module
  ingester2/src/persist/context.rs
  ingester2/src/persist/handle.rs
  ingester2/src/persist/mod.rs
  ingester2/src/persist/worker.rs
Labels: kodiak: merge.method = 'merge', kafkaless

#6455 fix: Allow partitions from ingesters to overlap in RPC write mode
  querier/src/table/mod.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6456 fix(persist): invalidate cached sort key
  ingester2/src/persist/context.rs
  ingester2/src/persist/worker.rs
Labels: automerge, kodiak: merge.method = 'merge', kafkaless

#6454 feat(ingester2): persist saturation metric
  ingester2/src/init.rs
  ingester2/src/persist/backpressure.rs
  ingester2/src/persist/handle.rs
  ingester2/src/server/grpc/rpc_write.rs
Labels: kodiak: merge.method = 'merge', kafkaless

#6457 chore: Update to Rust 1.66
  arrow_util/src/display.rs
  cache_system/src/backend/policy/integration_tests.rs
  cache_system/src/backend/policy/lru.rs
  cache_system/src/backend/policy/mod.rs
  cache_system/src/backend/policy/refresh.rs
  cache_system/src/backend/policy/remove_if.rs
  cache_system/src/backend/policy/ttl.rs
  compactor/src/lib.rs
  data_types/src/lib.rs
  generated_types/src/write_info.rs
  grpc-binary-logger-proto/proto/grpc/binlog/v1/binarylog.proto
  influxdb2_client/src/api/buckets.rs
  influxdb2_client/src/api/health.rs
  influxdb2_client/src/api/label.rs
  influxdb2_client/src/api/query.rs
  influxdb2_client/src/api/ready.rs
  influxdb2_client/src/api/setup.rs
  influxdb2_client/src/api/write.rs
  influxdb_influxql_parser/src/expression/arithmetic.rs
  influxdb_iox/tests/end_to_end_cases/schema.rs
  influxdb_tsm/src/encoders/float.rs
  influxdb_tsm/src/encoders/unsigned.rs
  influxdb_tsm/src/key.rs
  ingester/src/data.rs
  iox_catalog/src/postgres.rs
  iox_query/src/exec/fieldlist.rs
  iox_query/src/lib.rs
  iox_query/src/provider/adapter.rs
  iox_query/src/pruning.rs
  parquet_file/src/metadata.rs
  querier/src/cache/namespace.rs
  querier/src/cache/object_store.rs
  querier/src/cache/parquet_file.rs
  querier/src/cache/partition.rs
  querier/src/cache/processed_tombstones.rs
  querier/src/cache/projected_schema.rs
  querier/src/cache/tombstones.rs
  query_functions/src/window/internal.rs
  query_tests/src/runner.rs
  rust-toolchain.toml
  schema/src/lib.rs
  service_grpc_influxrpc/src/data.rs
  service_grpc_influxrpc/src/service.rs
  test_helpers/src/lib.rs
  test_helpers_end_to_end/src/config.rs
  test_helpers_end_to_end/src/grpc.rs
  wal/src/lib.rs
  write_summary/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6462 refactor(ingester2): decouple persistence subsystem
  ingester2/src/init.rs
  ingester2/src/persist/backpressure.rs
  ingester2/src/persist/drain_buffer.rs
  ingester2/src/persist/handle.rs
  ingester2/src/persist/hot_partitions.rs
  ingester2/src/persist/mod.rs
  ingester2/src/persist/queue.rs
  ingester2/src/wal/rotate_task.rs
Labels: kodiak: merge.method = 'merge', kafkaless

#6463 fix: drop WAL segments after replay
  ingester2/Cargo.toml
  ingester2/benches/wal.rs
  ingester2/src/buffer_tree/mod.rs
  ingester2/src/buffer_tree/partition.rs
  ingester2/src/buffer_tree/partition/persisting.rs
  ingester2/src/dml_sink/trait.rs
  ingester2/src/init.rs
  ingester2/src/init/wal_replay.rs
  ingester2/src/lib.rs
  ingester2/src/persist/mod.rs
  ingester2/src/persist/queue.rs
  ingester2/src/query_adaptor.rs
  ingester2/src/wal/mod.rs
  ingester2/src/wal/rotate_task.rs
Labels: kodiak: merge.method = 'merge'

#6472 chore: add debug info for the investigation
  compactor/src/cold.rs
  influxdb_iox/tests/end_to_end_cases/cli.rs
Labels: automerge

#6475 chore: debug info of estimate file size
  compactor/src/parquet_file_filtering.rs
Labels: automerge

#6476 fix: make estimate memory of a query needs higher due to recent observation
  compactor/src/cold.rs
  compactor/src/parquet_file_lookup.rs
Labels: automerge
