Repository influxdata/influxdb_iox, pull requests merged in 2022-11, with the labels that each got.

#5998 chore: update rskafka
  Cargo.lock
  write_buffer/Cargo.toml
Labels: automerge

#6013 docs: Document new CLI commands
  docs/cli.md
Labels: automerge, kodiak: merge.method = 'squash'

#6021 fix: add missing content type in headers for `influxdb2_client`
  influxdb2_client/src/api/buckets.rs
  influxdb2_client/src/api/label.rs
  influxdb2_client/src/api/setup.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6018 chore: remove unecessary `--exclude datafusion` from `cargo doc`
  .circleci/config.yml
Labels: automerge, kodiak: merge.method = 'squash'

#6015 refactor: simplify `QueryChunk` data access
  compactor/src/query.rs
  ingester/src/query_adaptor.rs
  iox_query/src/lib.rs
  iox_query/src/provider/physical.rs
  iox_query/src/test.rs
  iox_tests/src/util.rs
  parquet_file/src/chunk.rs
  parquet_file/src/storage.rs
  querier/src/chunk/mod.rs
  querier/src/chunk/query_access.rs
  querier/src/ingester/mod.rs
  querier/src/ingester/test_util.rs
  querier/src/table/mod.rs
Labels: automerge

#6035 fix: actually enable zstd compression for write write buffer
  write_buffer/src/kafka/mod.rs
Labels: automerge

#6020 fix: handle recursing limit in querier<>ingester comm
  querier/src/ingester/flight_client.rs
  test_helpers_end_to_end/src/server_fixture.rs
Labels: automerge

#6003 refactor(router): pass TableId through handler stack
  ioxd_router/src/lib.rs
  router/src/dml_handlers/partitioner.rs
  router/src/dml_handlers/schema_validation.rs
  router/src/dml_handlers/sharded_write_buffer.rs
  router/src/server/http.rs
  router/tests/http.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6031 refactor: move `influxdb_iox debug namespace` command to `influxdb_iox namespace`
  docs/cli.md
  influxdb_iox/src/commands/debug/mod.rs
  influxdb_iox/src/commands/namespace.rs
  influxdb_iox/src/main.rs
  influxdb_iox/tests/end_to_end_cases/cli.rs
Labels: automerge

#6017 chore: Update datafusion pin
  Cargo.lock
  Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#6036 refactor(write_buffer): pass IDs in wire format
  Cargo.lock
  dml/src/lib.rs
  generated_types/protos/influxdata/pbdata/v1/influxdb_pb_data_protocol.proto
  ingester/Cargo.toml
  ingester/src/data.rs
  ingester/src/handler.rs
  ingester/src/stream_handler/handler.rs
  ingester/src/stream_handler/sink_instrumentation.rs
  ingester/src/test_util.rs
  ingester/tests/common/mod.rs
  mutable_batch_pb/src/decode.rs
  mutable_batch_pb/src/encode.rs
  mutable_batch_pb/tests/encode.rs
  mutable_batch_tests/Cargo.toml
  mutable_batch_tests/benches/write_pb.rs
  query_tests/src/scenarios/util.rs
  router/src/dml_handlers/sharded_write_buffer.rs
  write_buffer/src/codec.rs
  write_buffer/src/core.rs
  write_buffer/src/kafka/mod.rs
  write_buffer/src/kafka/record_aggregator.rs
  write_buffer/src/mock.rs
Labels: kodiak: merge.method = 'merge'

#6014 feat: Add object_store handler to querier so `remote get-table` works
  Cargo.lock
  influxdb_iox/tests/end_to_end_cases/remote.rs
  ioxd_querier/src/lib.rs
  querier/Cargo.toml
  querier/src/handler.rs
Labels: automerge, kodiak: merge.method = 'squash'

#5930 feat: Enable parquet predicate pushdown in IOx by default
  datafusion_util/src/config.rs
  iox_query/src/provider.rs
  iox_query/src/provider/metrics.rs
  iox_query/src/provider/physical.rs
  query_tests/src/lib.rs
  query_tests/src/sql_metrics.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6039 feat: add `MeasurementTagKeys` support to storage CLI
  influxdb_iox/src/commands/storage.rs
  influxdb_iox/src/commands/storage/request.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6037 refactor: Rename `schema::selection::Selection` to `schema::projection::Projection`
  compactor/src/query.rs
  dml/src/lib.rs
  ingester/src/compact.rs
  ingester/src/data/partition/buffer/mutable_buffer.rs
  ingester/src/data/partition/buffer/state_machine.rs
  ingester/src/data/partition/buffer/state_machine/buffering.rs
  ingester/src/querier_handler.rs
  ingester/src/query_adaptor.rs
  ingester/src/server/grpc.rs
  iox_data_generator/src/write.rs
  iox_query/src/frontend/influxrpc.rs
  iox_query/src/lib.rs
  iox_query/src/test.rs
  iox_tests/src/util.rs
  mutable_batch/src/lib.rs
  mutable_batch/tests/extend.rs
  mutable_batch/tests/extend_range.rs
  mutable_batch/tests/writer.rs
  mutable_batch/tests/writer_drop.rs
  mutable_batch/tests/writer_fuzz.rs
  mutable_batch_lp/src/lib.rs
  mutable_batch_pb/src/decode.rs
  mutable_batch_pb/tests/encode.rs
  parquet_file/src/chunk.rs
  parquet_file/src/storage.rs
  parquet_to_line_protocol/src/batch.rs
  querier/src/chunk/query_access.rs
  querier/src/ingester/mod.rs
  querier/src/ingester/test_util.rs
  querier/src/table/test_util.rs
  query_tests/src/scenarios/util.rs
  query_tests/src/table_schema.rs
  router/benches/schema_validator.rs
  schema/src/lib.rs
  schema/src/projection.rs
  schema/src/selection.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6034 fix: InfluxQL parser incompatibilities
  influxdb_influxql_parser/src/expression/arithmetic.rs
  influxdb_influxql_parser/src/literal.rs
  influxdb_influxql_parser/src/select.rs
  influxdb_influxql_parser/src/string.rs
Labels: bug, automerge, influxql

#6046 refactor: disable large variant lint
  predicate/src/delete_expr.rs
Labels: kodiak: merge.method = 'merge'

#6043 chore: Export metrics for parquet access to `EXPLAIN ANALYZE`
  iox_query/src/provider/metrics.rs
  iox_query/src/provider/physical.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6047 feat: add ArcMap map type
  ingester/src/arcmap.rs
  ingester/src/lib.rs
Labels: kodiak: merge.method = 'merge'

#6045 feat: support multiple bootstrap_broker server config
  write_buffer/src/config.rs
  write_buffer/src/kafka/mod.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6007 fix: Let's not all write to the same file at the same time
  iox_data_generator/benches/point_generation.rs
  iox_data_generator/src/agent.rs
  iox_data_generator/src/lib.rs
  iox_data_generator/src/write.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6044 feat: config param to set when partition is cold
  clap_blocks/src/compactor.rs
  compactor/src/cold.rs
  compactor/src/compact.rs
  compactor/src/handler.rs
  compactor/src/hot.rs
  compactor/src/lib.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ioxd_compactor/src/lib.rs
Labels: automerge

#6054 chore: Update datafusion pin
  Cargo.lock
  Cargo.toml
  query_tests/src/sql.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#6058 chore: Upgrade futures-intrusive to avoid a yanked version
  Cargo.lock
Labels: automerge, kodiak: merge.method = 'squash'

#6041 feat: grpc for updating namespace retention period
  data_types/src/lib.rs
  generated_types/protos/influxdata/iox/schema/v1/service.proto
  influxdb_iox/src/commands/namespace/mod.rs
  influxdb_iox/src/commands/namespace/retention.rs
  influxdb_iox/tests/end_to_end_cases/cli.rs
  influxdb_iox_client/src/client/schema.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  router/src/namespace_resolver/ns_autocreation.rs
  service_grpc_schema/src/lib.rs
Labels: automerge

#6052 refactor(write_buffer): propagate NamespaceId across Kafka boundary for DML deletes
  dml/src/lib.rs
  generated_types/protos/influxdata/iox/delete/v1/service.proto
  influxdb_iox_client/src/client/delete.rs
  ingester/src/data.rs
  ingester/src/stream_handler/handler.rs
  query_tests/src/scenarios/util.rs
  router/src/dml_handlers/sharded_write_buffer.rs
  router/tests/http.rs
  write_buffer/src/codec.rs
  write_buffer/src/kafka/mod.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6057 chore: delete metric duplicate character
  ingester/src/data/namespace.rs
  ingester/src/data/shard.rs
  ingester/src/stream_handler/handler.rs
  router/src/server/http.rs
  router/tests/http.rs
Labels: automerge

#6063 refactor: remove table name from chunks
  compactor/src/parquet_file_combining.rs
  compactor/src/query.rs
  compactor/src/utils.rs
  ingester/src/compact.rs
  ingester/src/data.rs
  ingester/src/data/partition.rs
  ingester/src/data/table.rs
  ingester/src/query_adaptor.rs
  iox_query/src/frontend.rs
  iox_query/src/frontend/common.rs
  iox_query/src/frontend/influxrpc.rs
  iox_query/src/frontend/reorg.rs
  iox_query/src/lib.rs
  iox_query/src/provider.rs
  iox_query/src/provider/overlap.rs
  iox_query/src/test.rs
  predicate/src/rpc_predicate.rs
  querier/src/chunk/mod.rs
  querier/src/chunk/query_access.rs
  querier/src/ingester/mod.rs
  querier/src/ingester/test_util.rs
  querier/src/table/mod.rs
  querier/src/table/query_access/mod.rs
  querier/src/table/test_util.rs
  query_tests/src/table_schema.rs
  service_grpc_influxrpc/src/expr.rs
Labels: automerge

#6061 chore: Update datafusion and arrow/arrow-flight/parquet to `26.0.0`
  Cargo.lock
  Cargo.toml
  arrow_util/Cargo.toml
  deny.toml
  influxdb_iox/src/commands/storage/response.rs
  ingester/Cargo.toml
  iox_query/src/exec/seriesset/series.rs
  iox_query/src/test.rs
  query_functions/src/lib.rs
  query_functions/src/selectors.rs
  query_functions/src/window.rs
  query_tests/cases/in/selectors.expected
  service_grpc_influxrpc/src/data.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#6065 refactor: rename ArcMap::get_or_insert_with()
  ingester/src/arcmap.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6060 chore: expose compactor's hot compaction hours thresholds as cfg
  clap_blocks/src/compactor.rs
  compactor/src/cold.rs
  compactor/src/compact.rs
  compactor/src/handler.rs
  compactor/src/hot.rs
  compactor/src/lib.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ioxd_compactor/src/lib.rs
Labels: automerge

#6068 perf(ingester): granular per-partition locking
  ingester/src/data.rs
  ingester/src/data/namespace.rs
  ingester/src/data/partition.rs
  ingester/src/data/table.rs
  ingester/src/querier_handler.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6070 feat: catalog function to soft delete based on retention
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
Labels: automerge

#6053 fix: use `ORDER BY` to prevent `INSERT` deadlocks
  import/src/aggregate_tsm_schema/update_catalog.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6062 feat: Add parser for `CREATE DATABASE` statement
  influxdb_influxql_parser/src/create.rs
  influxdb_influxql_parser/src/lib.rs
  influxdb_influxql_parser/src/statement.rs
  influxdb_influxql_parser/src/visit.rs
Labels: automerge, influxql

#6083 revert: granular locking
  ingester/src/data.rs
  ingester/src/data/namespace.rs
  ingester/src/data/partition.rs
  ingester/src/data/table.rs
  ingester/src/querier_handler.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6072 refactor: expose `ParquetExec` directly to DataFusion phys. plan
  Cargo.lock
  influxdb_iox/tests/end_to_end_cases/tracing.rs
  iox_query/src/frontend.rs
  iox_query/src/provider.rs
  iox_query/src/provider/metrics.rs
  iox_query/src/provider/physical.rs
  iox_query/src/provider/record_batch_exec.rs
  iox_query/src/statistics.rs
  querier/Cargo.toml
  querier/src/namespace/query_access.rs
  query_tests/Cargo.toml
  query_tests/cases/in/duplicates_ingester.expected
  query_tests/cases/in/duplicates_ingester.sql
  query_tests/cases/in/duplicates_parquet.expected
  query_tests/cases/in/duplicates_parquet.sql
  query_tests/cases/in/pushdown.expected
  query_tests/cases/in/pushdown.sql
  query_tests/cases/in/several_chunks.expected
  query_tests/cases/in/several_chunks.sql
  query_tests/cases/in/two_chunks.expected
  query_tests/cases/in/two_chunks.sql
  query_tests/src/runner.rs
  query_tests/src/runner/parse.rs
Labels: automerge

#6086 fix: cross-thread ArcMap::get()
  ingester/src/arcmap.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6088 perf(ingester): mutex pushdown
  ingester/src/data.rs
  ingester/src/data/namespace.rs
  ingester/src/data/partition.rs
  ingester/src/data/table.rs
  ingester/src/querier_handler.rs
Labels: kodiak: merge.method = 'merge'

#6069 perf(ingester): eliminate table / namespace queries
  dml/src/lib.rs
  ingester/src/data.rs
  ingester/src/data/namespace.rs
  ingester/src/data/shard.rs
  ingester/src/data/table.rs
  ingester/src/querier_handler.rs
  ingester/src/test_util.rs
  mutable_batch_pb/src/decode.rs
  mutable_batch_pb/src/encode.rs
  router/tests/http.rs
  write_buffer/src/codec.rs
Labels: kodiak: merge.method = 'merge'

#6073 feat: deletion flagging in GC based on retention policy
  garbage_collector/src/lib.rs
  garbage_collector/src/retention/flagger.rs
  garbage_collector/src/retention/mod.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
Labels: automerge

#6076 feat: Parse InfluxQL line and inline comments
  influxdb_influxql_parser/src/common.rs
  influxdb_influxql_parser/src/create.rs
  influxdb_influxql_parser/src/delete.rs
  influxdb_influxql_parser/src/drop.rs
  influxdb_influxql_parser/src/explain.rs
  influxdb_influxql_parser/src/expression/arithmetic.rs
  influxdb_influxql_parser/src/expression/conditional.rs
  influxdb_influxql_parser/src/keywords.rs
  influxdb_influxql_parser/src/lib.rs
  influxdb_influxql_parser/src/literal.rs
  influxdb_influxql_parser/src/select.rs
  influxdb_influxql_parser/src/show.rs
  influxdb_influxql_parser/src/show_field_keys.rs
  influxdb_influxql_parser/src/show_measurements.rs
  influxdb_influxql_parser/src/show_retention_policies.rs
  influxdb_influxql_parser/src/show_tag_keys.rs
  influxdb_influxql_parser/src/show_tag_values.rs
  influxdb_influxql_parser/src/simple_from_clause.rs
  influxdb_influxql_parser/src/test_util.rs
Labels: automerge, influxql

#6006 test: Ensure router's HTTP error messages are stable
  Cargo.lock
  router/Cargo.toml
  router/src/server/http.rs
Labels: automerge

#6093 feat: use IDs in ingester query API
  generated_types/protos/influxdata/iox/ingester/v1/query.proto
  generated_types/src/ingester.rs
  influxdb_iox/src/commands/query_ingester.rs
  influxdb_iox/tests/end_to_end_cases/cli.rs
  influxdb_iox/tests/end_to_end_cases/ingester.rs
  influxdb_iox/tests/end_to_end_cases/querier.rs
  ingester/src/handler.rs
  ingester/src/querier_handler.rs
  ingester/src/server/grpc.rs
  ingester/tests/common/mod.rs
  ingester/tests/write.rs
  querier/src/ingester/flight_client.rs
  querier/src/ingester/mod.rs
  querier/src/ingester/test_util.rs
  querier/src/namespace/mod.rs
  querier/src/table/mod.rs
  querier/src/table/test_util.rs
  service_grpc_flight/src/lib.rs
  test_helpers_end_to_end/src/mini_cluster.rs
Labels: kodiak: merge.method = 'squash'

#6075 feat: flag partitions for delete
  Cargo.lock
  data_types/src/lib.rs
  import/src/aggregate_tsm_schema/update_catalog.rs
  ingester/src/data/partition/resolver/cache.rs
  iox_catalog/Cargo.toml
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  workspace-hack/Cargo.toml
Labels: automerge

#6101 chore: delete dead code `PartitionAddr`
  data_types/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6094 refactor: chunk InfluxRPC `ReadResponses`
  service_grpc_influxrpc/src/service.rs
Labels: automerge

#6056 feat: make logging clearer when parquet files upload is retried
  parquet_file/src/storage.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6100 chore: Rename DatabaseName to NamespaceName
  data_types/src/lib.rs
  import/src/aggregate_tsm_schema/update_catalog.rs
  ioxd_router/src/lib.rs
  router/benches/schema_validator.rs
  router/src/dml_handlers/chain.rs
  router/src/dml_handlers/fan_out.rs
  router/src/dml_handlers/instrumentation.rs
  router/src/dml_handlers/mock.rs
  router/src/dml_handlers/nop.rs
  router/src/dml_handlers/ns_autocreation.rs
  router/src/dml_handlers/partitioner.rs
  router/src/dml_handlers/schema_validation.rs
  router/src/dml_handlers/sharded_write_buffer.rs
  router/src/dml_handlers/trait.rs
  router/src/dml_handlers/write_summary.rs
  router/src/namespace_cache.rs
  router/src/namespace_cache/memory.rs
  router/src/namespace_cache/metrics.rs
  router/src/namespace_cache/sharded_cache.rs
  router/src/namespace_resolver.rs
  router/src/namespace_resolver/mock.rs
  router/src/namespace_resolver/ns_autocreation.rs
  router/src/server/grpc/sharder.rs
  router/src/server/http.rs
  service_grpc_flight/src/lib.rs
  service_grpc_influxrpc/src/service.rs
  sharder/benches/sharder.rs
  sharder/src/jumphash.rs
  sharder/src/mock.rs
  sharder/src/trait.rs
  write_buffer/src/config.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6109 chore: Revert "feat: catalog delete old partitions (#6099)"
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
Labels: automerge

#6111 chore: Revert "feat: flag partitions for delete (#6075)"
  Cargo.lock
  data_types/src/lib.rs
  import/src/aggregate_tsm_schema/update_catalog.rs
  ingester/src/data/partition/resolver/cache.rs
  iox_catalog/Cargo.toml
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  workspace-hack/Cargo.toml
Labels: automerge

#6095 refactor: generic deferred loader helper
  ingester/src/data/partition.rs
  ingester/src/data/partition/resolver/cache.rs
  ingester/src/data/partition/resolver/sort_key.rs
  ingester/src/deferred_load.rs
  ingester/src/lib.rs
Labels: kodiak: merge.method = 'merge'

#6119 chore: update blake2 because version 0.10.4 was yanked
  Cargo.lock
Labels: automerge

#6118 fix: traverse some more DataFusion error to extract tonic error
  service_common/src/error.rs
Labels: automerge

#6120 refactor: remove redundant shard data init
  ingester/src/handler.rs
Labels: kodiak: merge.method = 'merge'

#6113 refactor: first step to remove unused retention_duration
  compactor/src/compact.rs
  compactor/src/garbage_collector.rs
  garbage_collector/src/objectstore/checker.rs
  import/src/aggregate_tsm_schema/update_catalog.rs
  influxdb_iox/src/commands/import/schema.rs
  influxdb_iox/src/commands/remote/partition.rs
  influxdb_iox/tests/end_to_end_cases/cli.rs
  ingester/src/data.rs
  ingester/src/data/partition/resolver/catalog.rs
  ingester/src/handler.rs
  ingester/src/test_util.rs
  ingester/tests/common/mod.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_tests/src/util.rs
  ioxd_router/src/lib.rs
  router/src/dml_handlers/ns_autocreation.rs
  router/src/namespace_resolver.rs
  router/src/namespace_resolver/ns_autocreation.rs
  router/tests/http.rs
  service_grpc_catalog/src/lib.rs
  service_grpc_object_store/src/lib.rs
  service_grpc_schema/src/lib.rs
Labels: automerge

#6123 chore: update SQL syntax after adding the new column to_delete into table partition
  docs/compactor.md
Labels: automerge

#6124 refactor: remove retention_duration field from namespace catalog table
  data_types/src/lib.rs
  iox_catalog/migrations/20221111133939_drop_retention_duration.sql
  iox_catalog/src/mem.rs
  router/src/dml_handlers/ns_autocreation.rs
  router/src/namespace_resolver/ns_autocreation.rs
Labels: automerge

#6127 fix: Rename more instances of "database" to "namespace"
  Dockerfile
  README.md
  dml/src/lib.rs
  docs/cli.md
  docs/env.example
  docs/local_filesystems.md
  docs/observability.md
  docs/sql.md
  docs/testing.md
  generated_types/protos/influxdata/iox/querier/v1/flight.proto
  influxdb_iox/src/commands/namespace/retention.rs
  influxdb_iox/src/commands/storage.rs
  influxdb_iox/src/commands/write.rs
  influxdb_iox/src/main.rs
  influxdb_iox_client/src/client/flight/low_level.rs
  influxdb_iox_client/src/client/flight/mod.rs
  influxdb_iox_client/src/client/write.rs
  influxdb_storage_client/src/lib.rs
  iox_catalog/src/interface.rs
  iox_query/src/frontend/influxrpc.rs
  iox_query/src/lib.rs
  iox_query/src/provider/adapter.rs
  iox_query/src/test.rs
  ioxd_common/src/lib.rs
  ioxd_common/src/server_type/common_state.rs
  ioxd_router/src/lib.rs
  parquet_file/src/chunk.rs
  parquet_file/src/lib.rs
  predicate/src/rpc_predicate.rs
  querier/src/database.rs
  querier/src/namespace/mod.rs
  querier/src/namespace/query_access.rs
  query_tests/src/db.rs
  query_tests/src/influxrpc/field_columns.rs
  query_tests/src/influxrpc/read_filter.rs
  query_tests/src/influxrpc/read_group.rs
  query_tests/src/influxrpc/read_window_aggregate.rs
  query_tests/src/influxrpc/table_names.rs
  query_tests/src/influxrpc/tag_keys.rs
  query_tests/src/influxrpc/tag_values.rs
  router/src/dml_handlers/instrumentation.rs
  router/src/dml_handlers/trait.rs
  router/src/namespace_cache/memory.rs
  router/src/namespace_cache/metrics.rs
  router/src/namespace_cache/sharded_cache.rs
  router/src/server/http.rs
  schema/src/builder.rs
  schema/src/lib.rs
  schema/src/merge.rs
  service_common/src/lib.rs
  service_common/src/planner.rs
  service_common/src/test_util.rs
  service_grpc_flight/src/lib.rs
  service_grpc_influxrpc/src/expr.rs
  service_grpc_influxrpc/src/lib.rs
  service_grpc_influxrpc/src/service.rs
  test_helpers_end_to_end/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6122 refactor: internalise PartitionProvider
  ingester/src/data.rs
  ingester/src/data/partition/resolver/catalog.rs
  ingester/src/data/partition/resolver/mock.rs
  ingester/src/data/partition/resolver/mod.rs
  ingester/src/data/partition/resolver/sort_key.rs
  ingester/src/data/partition/resolver/trait.rs
  ingester/src/handler.rs
  ingester/src/test_util.rs
  query_tests/src/scenarios/util.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6135 fix: Improve testing and documentation to clarify Go client behavior
  service_grpc_flight/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6138 fix: Remove namespace string from router -> write buffer -> ingester communication
  dml/src/lib.rs
  docs/ingester_querier_protocol.md
  generated_types/protos/influxdata/iox/delete/v1/service.proto
  generated_types/protos/influxdata/pbdata/v1/influxdb_pb_data_protocol.proto
  influxdb_iox_client/src/client/delete.rs
  ingester/src/data.rs
  ingester/src/data/namespace.rs
  ingester/src/data/shard.rs
  ingester/src/handler.rs
  ingester/src/stream_handler/handler.rs
  ingester/src/stream_handler/sink_instrumentation.rs
  ingester/src/test_util.rs
  ingester/tests/common/mod.rs
  mutable_batch_pb/src/encode.rs
  mutable_batch_tests/benches/write_pb.rs
  query_tests/src/scenarios/util.rs
  router/src/dml_handlers/sharded_write_buffer.rs
  router/tests/http.rs
  write_buffer/src/codec.rs
  write_buffer/src/core.rs
  write_buffer/src/file.rs
  write_buffer/src/kafka/mod.rs
  write_buffer/src/kafka/record_aggregator.rs
  write_buffer/src/mock.rs
Labels: kodiak: merge.method = 'merge'

#6145 feat: define router -> ingester write protocol
  generated_types/build.rs
  generated_types/protos/influxdata/iox/ingester/v1/write.proto
  generated_types/protos/influxdata/pbdata/v1/influxdb_pb_data_protocol.proto
  test_helpers_end_to_end/src/client.rs
Labels: kodiak: merge.method = 'merge'

#6137 test: tests in the reorg planner and query tests for merging parquet files
  iox_query/src/frontend/reorg.rs
  iox_query/src/test.rs
  query_tests/cases/in/duplicates_parquet_many.expected
  query_tests/cases/in/duplicates_parquet_many.sql
  query_tests/src/cases.rs
  query_tests/src/scenarios.rs
  query_tests/src/scenarios/library.rs
  query_tests/src/scenarios/util.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6136 test: test coverage for sorting and merging in compactor
  Cargo.lock
  compactor/Cargo.toml
  compactor/src/parquet_file_combining.rs
  iox_tests/src/util.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6147 feat: add querier->ingester circuit breaker
  clap_blocks/src/querier.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/tests/end_to_end_cases/querier.rs
  ingester/src/lifecycle.rs
  ioxd_querier/src/lib.rs
  querier/src/ingester/circuit_breaker.rs
  querier/src/ingester/flight_client.rs
  querier/src/ingester/mod.rs
  test_helpers_end_to_end/src/config.rs
  test_helpers_end_to_end/src/steps.rs
Labels: automerge

#6144 feat: compactor ignores max file count for first file
  compactor/src/lib.rs
  compactor/src/parquet_file_filtering.rs
Labels: automerge

#6108 chore: Update datafusion again
  Cargo.lock
  Cargo.toml
  iox_query/src/exec/non_null_checker.rs
  iox_query/src/exec/schema_pivot.rs
  iox_query/src/exec/split.rs
  iox_query/src/provider/deduplicate.rs
  iox_query/src/provider/physical.rs
  parquet_file/src/storage.rs
  parquet_to_line_protocol/src/lib.rs
  querier/src/ingester/flight_client.rs
  querier/src/namespace/query_access.rs
  query_tests/cases/in/duplicates_ingester.expected
  query_tests/cases/in/duplicates_parquet.expected
  query_tests/cases/in/duplicates_parquet_many.expected
  query_tests/cases/in/pushdown.expected
  query_tests/cases/in/several_chunks.expected
  query_tests/cases/in/two_chunks.expected
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#6151 chore: router namespace api
  Cargo.lock
  Cargo.toml
  generated_types/protos/influxdata/iox/namespace/v1/service.proto
  generated_types/protos/influxdata/iox/schema/v1/service.proto
  influxdb_iox/src/commands/namespace/retention.rs
  influxdb_iox_client/src/client/namespace.rs
  influxdb_iox_client/src/client/schema.rs
  ioxd_querier/src/rpc/namespace.rs
  ioxd_router/src/lib.rs
  router/Cargo.toml
  router/src/server/grpc.rs
  service_grpc_namespace/Cargo.toml
  service_grpc_namespace/src/lib.rs
  service_grpc_schema/src/lib.rs
Labels: automerge

#6154 docs: remove redundant comment
  router/src/dml_handlers/sharded_write_buffer.rs
Labels: kodiak: merge.method = 'merge'

#6158 chore: Revert "feat: compactor ignores max file count for first file (#6144)"
  compactor/src/lib.rs
  compactor/src/parquet_file_filtering.rs
Labels: automerge

#6152 build(arrow_util): datafusion is not a release dep
  arrow_util/Cargo.toml
Labels: automerge, kodiak: merge.method = 'merge'

#6153 feat(sharder): round robin
  sharder/benches/sharder.rs
  sharder/src/lib.rs
  sharder/src/round_robin.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6168 refactor: remove unused errors
  ingester/src/data.rs
  ingester/src/stream_handler/handler.rs
  ingester/src/stream_handler/sink_instrumentation.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6155 feat: improve error message on `storage` `--format` parse errors
  influxdb_iox/src/commands/storage.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6165 test: Refactor some ingester tests in preparation for removing table names
  ingester/src/data.rs
  ingester/src/data/namespace.rs
  ingester/src/data/shard.rs
  ingester/src/test_util.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6161 chore: marshal InfluxDbError into status details
  generated_types/build.rs
  generated_types/protos/influxdata/platform/errors/errors.proto
  generated_types/src/google.rs
  generated_types/src/lib.rs
  service_grpc_influxrpc/src/service.rs
Labels: automerge

#6148 feat: reject writes that are outside the retention period
  data_types/src/lib.rs
  influxdb_iox/tests/end_to_end_cases/all_in_one.rs
  ingester/src/data.rs
  ingester/src/handler.rs
  ingester/tests/common/mod.rs
  ingester/tests/write.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/mem.rs
  iox_tests/src/util.rs
  ioxd_querier/src/rpc/namespace.rs
  ioxd_router/src/lib.rs
  router/src/dml_handlers/mod.rs
  router/src/dml_handlers/retention_validator.rs
  router/src/dml_handlers/trait.rs
  router/src/namespace_cache/memory.rs
  router/src/namespace_cache/metrics.rs
  router/src/namespace_cache/sharded_cache.rs
  router/src/namespace_resolver.rs
  router/src/namespace_resolver/ns_autocreation.rs
  router/src/server/http.rs
  router/tests/http.rs
Labels: automerge

#6156 fix: only push safe select expression through de-dup
  iox_query/src/provider.rs
  predicate/src/lib.rs
  query_tests/cases/in/dedup_and_predicates_parquet.expected
  query_tests/cases/in/dedup_and_predicates_parquet.sql
  query_tests/cases/in/dedup_and_predicates_parquet_ingester.expected
  query_tests/cases/in/dedup_and_predicates_parquet_ingester.sql
  query_tests/src/cases.rs
  query_tests/src/scenarios.rs
  query_tests/src/scenarios/library.rs
Labels: automerge

#6042 feat: push down all predicates
  iox_query/src/provider.rs
  predicate/src/lib.rs
  query_tests/cases/in/pushdown.expected
Labels: automerge, kodiak: merge.method = 'squash'

#6174 feat(router): handler for direct write to ingester
  router/src/dml_handlers/mod.rs
  router/src/dml_handlers/partitioner.rs
  router/src/dml_handlers/rpc_write.rs
  router/src/dml_handlers/rpc_write/client.rs
  router/src/dml_handlers/trait.rs
  router/src/server/http.rs
Labels: automerge, kodiak: merge.method = 'merge', kafkaless

#6172 chore: copy iox images skopeo gar registry
  .circleci/config.yml
Labels: automerge

#6178 feat(ingester): rpc write handler
  Cargo.lock
  ingester/Cargo.toml
  ingester/src/server/grpc.rs
  ingester/src/server/grpc/query.rs
  ingester/src/server/grpc/rpc_write.rs
  ingester/src/server/grpc/write_info.rs
Labels: automerge, kodiak: merge.method = 'merge', kafkaless

#6187 feat: add `process_start_time_seconds` metric
  influxdb_iox/src/commands/catalog.rs
  influxdb_iox/src/commands/catalog/topic.rs
  influxdb_iox/src/commands/compactor.rs
  influxdb_iox/src/commands/import/schema.rs
  influxdb_iox/src/commands/remote/partition.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/src/commands/run/compactor.rs
  influxdb_iox/src/commands/run/garbage_collector.rs
  influxdb_iox/src/commands/run/ingester.rs
  influxdb_iox/src/commands/run/querier.rs
  influxdb_iox/src/commands/run/router.rs
  influxdb_iox/src/commands/run/test.rs
  influxdb_iox/src/main.rs
  influxdb_iox/src/process_info.rs
  influxdb_iox/tests/end_to_end_cases/metrics.rs
Labels: automerge

#6188 refactor: move DmlSink
  ingester/src/dml_sink/mock_sink.rs
  ingester/src/dml_sink/mod.rs
  ingester/src/dml_sink/trait.rs
  ingester/src/lib.rs
  ingester/src/server/grpc/rpc_write.rs
  ingester/src/stream_handler/handler.rs
  ingester/src/stream_handler/mod.rs
  ingester/src/stream_handler/sink_adaptor.rs
  ingester/src/stream_handler/sink_instrumentation.rs
Labels: kodiak: merge.method = 'merge'

#6189 refactor: decouple DmlSink error type
  ingester/src/dml_sink/mock_sink.rs
  ingester/src/dml_sink/trait.rs
  ingester/src/server/grpc/rpc_write.rs
  ingester/src/stream_handler/handler.rs
  ingester/src/stream_handler/sink_adaptor.rs
  ingester/src/stream_handler/sink_instrumentation.rs
Labels: kodiak: merge.method = 'merge'

#6193 refactor: move SequenceNumberRange
  ingester/src/data.rs
  ingester/src/data/partition.rs
  ingester/src/data/partition/buffer.rs
  ingester/src/data/partition/buffer/state_machine.rs
  ingester/src/lib.rs
  ingester/src/sequence_range.rs
Labels: kodiak: merge.method = 'merge', kafkaless

#6201 chore: Update crossbeam-utils
  Cargo.lock
Labels: automerge, dependencies

#6202 refactor: tune circuit breaker config
  querier/src/ingester/circuit_breaker.rs
  querier/src/ingester/mod.rs
Labels: automerge

#6205 fix: slice flight response batches
  arrow_util/src/optimize.rs
  ingester/src/querier_handler.rs
  service_grpc_flight/src/lib.rs
Labels: automerge

#6206 refactor(ingester): split out BufferTree from Shard
  ingester/src/buffer_tree/mod.rs
  ingester/src/buffer_tree/namespace.rs
  ingester/src/buffer_tree/namespace/name_resolver.rs
  ingester/src/buffer_tree/partition.rs
  ingester/src/buffer_tree/partition/buffer.rs
  ingester/src/buffer_tree/partition/buffer/always_some.rs
  ingester/src/buffer_tree/partition/buffer/mutable_buffer.rs
  ingester/src/buffer_tree/partition/buffer/state_machine.rs
  ingester/src/buffer_tree/partition/buffer/state_machine/buffering.rs
  ingester/src/buffer_tree/partition/buffer/state_machine/persisting.rs
  ingester/src/buffer_tree/partition/buffer/state_machine/snapshot.rs
  ingester/src/buffer_tree/partition/buffer/traits.rs
  ingester/src/buffer_tree/partition/resolver/cache.rs
  ingester/src/buffer_tree/partition/resolver/catalog.rs
  ingester/src/buffer_tree/partition/resolver/mock.rs
  ingester/src/buffer_tree/partition/resolver/mod.rs
  ingester/src/buffer_tree/partition/resolver/sort_key.rs
  ingester/src/buffer_tree/partition/resolver/trait.rs
  ingester/src/buffer_tree/root.rs
  ingester/src/buffer_tree/table.rs
  ingester/src/buffer_tree/table/name_resolver.rs
  ingester/src/compact.rs
  ingester/src/data.rs
  ingester/src/data/shard.rs
  ingester/src/handler.rs
  ingester/src/lib.rs
  ingester/src/query_adaptor.rs
  ingester/src/server/grpc.rs
  ingester/src/server/grpc/query.rs
  ingester/src/server/grpc/rpc_write.rs
  ingester/src/stream_handler/handler.rs
  ingester/src/stream_handler/sink_instrumentation.rs
Labels: kodiak: merge.method = 'merge', kafkaless

#6196 test: add tests to ensure compactor plans to not do unnecessary sorts
  compactor/src/lib.rs
  compactor/src/parquet_file_combining.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6160 chore: Upgrade datafusion again
  Cargo.lock
  Cargo.toml
  iox_query/src/exec/non_null_checker.rs
  iox_query/src/exec/schema_pivot.rs
  iox_query/src/exec/split.rs
  iox_query/src/provider.rs
  iox_query/src/provider/deduplicate.rs
  iox_query/src/provider/physical.rs
  parquet_file/src/storage.rs
  parquet_to_line_protocol/src/lib.rs
  querier/src/ingester/flight_client.rs
  querier/src/namespace/query_access.rs
  query_tests/cases/in/dedup_and_predicates_parquet.expected
  query_tests/cases/in/dedup_and_predicates_parquet_ingester.expected
  query_tests/cases/in/duplicates_ingester.expected
  query_tests/cases/in/duplicates_parquet.expected
  query_tests/cases/in/duplicates_parquet_many.expected
  query_tests/cases/in/pushdown.expected
  query_tests/cases/in/several_chunks.expected
  query_tests/cases/in/two_chunks.expected
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#6166 feat: Introduce InfluxQL to Flight
  Cargo.lock
  generated_types/protos/influxdata/iox/querier/v1/flight.proto
  influxdb_iox/src/commands/query.rs
  influxdb_iox/src/commands/sql/repl.rs
  influxdb_iox/tests/end_to_end_cases/all_in_one.rs
  influxdb_iox/tests/end_to_end_cases/cli.rs
  influxdb_iox/tests/end_to_end_cases/influxql.rs
  influxdb_iox/tests/end_to_end_cases/mod.rs
  influxdb_iox/tests/end_to_end_cases/querier.rs
  influxdb_iox_client/src/client/flight/mod.rs
  iox_query/Cargo.toml
  iox_query/src/frontend.rs
  iox_query/src/frontend/influxql.rs
  iox_query/src/plan.rs
  iox_query/src/plan/influxql.rs
  service_common/src/planner.rs
  service_grpc_flight/Cargo.toml
  service_grpc_flight/src/lib.rs
  test_helpers_end_to_end/src/client.rs
  test_helpers_end_to_end/src/steps.rs
Labels: automerge, influxql

#6207 chore: Update datafusion (2 of N) right before arrow 27 upgrade
  Cargo.lock
  Cargo.toml
  query_tests/cases/in/pushdown.expected
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#6208 chore: Update DataFusion (3 of N) and arrow/parquet to 27.0.0
  Cargo.lock
  Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#6181 feat: Add a WAL crate for ingester2 to use
  .circleci/config.yml
  Cargo.lock
  Cargo.toml
  generated_types/build.rs
  generated_types/protos/influxdata/iox/wal/v1/wal.proto
  generated_types/src/lib.rs
  wal/Cargo.toml
  wal/src/blocking.rs
  wal/src/blocking/reader.rs
  wal/src/blocking/writer.rs
  wal/src/lib.rs
  wal/tests/end_to_end.rs
Labels: kodiak: merge.method = 'squash', kafkaless

#6223 chore: identifier parser handles preceding whitespace
  influxdb_influxql_parser/src/common.rs
  influxdb_influxql_parser/src/create.rs
  influxdb_influxql_parser/src/drop.rs
  influxdb_influxql_parser/src/identifier.rs
  influxdb_influxql_parser/src/keywords.rs
  influxdb_influxql_parser/src/select.rs
  influxdb_influxql_parser/src/show.rs
  influxdb_influxql_parser/src/show_tag_values.rs
Labels: automerge, influxql

#6228 feat(ingester): ingester2 init
  Cargo.lock
  Cargo.toml
  ingester2/Cargo.toml
  ingester2/src/arcmap.rs
  ingester2/src/buffer_tree/mod.rs
  ingester2/src/buffer_tree/namespace.rs
  ingester2/src/buffer_tree/namespace/name_resolver.rs
  ingester2/src/buffer_tree/partition.rs
  ingester2/src/buffer_tree/partition/buffer.rs
  ingester2/src/buffer_tree/partition/buffer/always_some.rs
  ingester2/src/buffer_tree/partition/buffer/mutable_buffer.rs
  ingester2/src/buffer_tree/partition/buffer/state_machine.rs
  ingester2/src/buffer_tree/partition/buffer/state_machine/buffering.rs
  ingester2/src/buffer_tree/partition/buffer/state_machine/persisting.rs
  ingester2/src/buffer_tree/partition/buffer/state_machine/snapshot.rs
  ingester2/src/buffer_tree/partition/buffer/traits.rs
  ingester2/src/buffer_tree/partition/resolver/cache.rs
  ingester2/src/buffer_tree/partition/resolver/catalog.rs
  ingester2/src/buffer_tree/partition/resolver/mock.rs
  ingester2/src/buffer_tree/partition/resolver/mod.rs
  ingester2/src/buffer_tree/partition/resolver/sort_key.rs
  ingester2/src/buffer_tree/partition/resolver/trait.rs
  ingester2/src/buffer_tree/root.rs
  ingester2/src/buffer_tree/table.rs
  ingester2/src/buffer_tree/table/name_resolver.rs
  ingester2/src/deferred_load.rs
  ingester2/src/dml_sink/mock_sink.rs
  ingester2/src/dml_sink/mod.rs
  ingester2/src/dml_sink/trait.rs
  ingester2/src/lib.rs
  ingester2/src/query/exec.rs
  ingester2/src/query/instrumentation.rs
  ingester2/src/query/mock_query_exec.rs
  ingester2/src/query/mod.rs
  ingester2/src/query/partition_response.rs
  ingester2/src/query/response.rs
  ingester2/src/query/trait.rs
  ingester2/src/query_adaptor.rs
  ingester2/src/sequence_range.rs
  ingester2/src/test_util.rs
Labels: automerge, kodiak: merge.method = 'merge', kafkaless

#6233 feat(ingester2): gRPC methods & type-erased init
  Cargo.lock
  ingester2/Cargo.toml
  ingester2/src/init.rs
  ingester2/src/lib.rs
  ingester2/src/server/grpc.rs
  ingester2/src/server/grpc/query.rs
  ingester2/src/server/grpc/rpc_write.rs
  ingester2/src/server/mod.rs
Labels: kodiak: merge.method = 'merge'

#6229 refactor: avoid `tokio::spawn` for cache requests
  cache_system/src/cache/driver.rs
  cache_system/src/cancellation_safe_future.rs
  cache_system/src/lib.rs
Labels: automerge

#6212 fix: ignore fields when considering tag predicates
  iox_query/src/frontend/influxrpc.rs
  predicate/src/rpc_predicate.rs
  predicate/src/rpc_predicate/column_rewrite.rs
  query_tests/src/influxrpc/read_filter.rs
  query_tests/src/influxrpc/tag_values.rs
  query_tests/src/scenarios/library.rs
  service_grpc_influxrpc/src/service.rs
Labels: automerge

#6237 feat(ingester2): query tracing decorator
  ingester2/src/query/exec.rs
  ingester2/src/query/instrumentation.rs
  ingester2/src/query/mock_query_exec.rs
  ingester2/src/query/mod.rs
  ingester2/src/query/partition_response.rs
  ingester2/src/query/response.rs
  ingester2/src/query/tracing.rs
  ingester2/src/query/trait.rs
  ingester2/src/server/grpc/query.rs
Labels: automerge, kodiak: merge.method = 'merge', kafkaless

#6243 refactor: remove duplicate tests
  querier/src/namespace/query_access.rs
  query_tests/src/scenarios/library.rs
Labels: automerge

#6238 fix: avoid user error for unsupported querier<>ingester preds
  querier/src/ingester/flight_client.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6218 chore: Update datafusion again (N of N)
  Cargo.lock
  Cargo.toml
  iox_query/src/frontend.rs
  query_functions/src/selectors.rs
  query_functions/src/selectors/internal.rs
  query_tests/cases/in/dedup_and_predicates_parquet.expected
  query_tests/cases/in/dedup_and_predicates_parquet_ingester.expected
  query_tests/cases/in/duplicates_parquet.expected
  query_tests/cases/in/pushdown.expected
  query_tests/cases/in/retention.expected
  query_tests/cases/in/several_chunks.expected
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#6239 refactor: make `ReadResponse` chunking stream-based
  service_grpc_influxrpc/src/lib.rs
  service_grpc_influxrpc/src/response_chunking.rs
  service_grpc_influxrpc/src/service.rs
Labels: automerge

#6244 refactor: clean-up and stream-based `QueryCompletedToken` handling
  service_grpc_influxrpc/src/lib.rs
  service_grpc_influxrpc/src/permit.rs
  service_grpc_influxrpc/src/query_completed_token.rs
  service_grpc_influxrpc/src/service.rs
Labels: automerge

#6258 chore: update `rskafka`
  Cargo.lock
  workspace-hack/Cargo.toml
  write_buffer/Cargo.toml
Labels: automerge

#6259 perf(ingester2): streaming queries
  ingester2/src/query/instrumentation.rs
  ingester2/src/query/partition_response.rs
  ingester2/src/query/response.rs
  ingester2/src/query/tracing.rs
  ingester2/src/server/grpc/query.rs
Labels: kodiak: merge.method = 'merge', kafkaless

#6246 chore: Update datafusion (to get memory limiting code)
  Cargo.lock
  Cargo.toml
  arrow_util/src/optimize.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#6260 refactor: stream-based series-to-frame conversion
  service_grpc_influxrpc/src/data.rs
  service_grpc_influxrpc/src/response_chunking.rs
  service_grpc_influxrpc/src/service.rs
Labels: automerge

#6262 refactor: Remove unnecessary `optimize_record_batch`
  arrow_util/src/optimize.rs
  ingester/src/querier_handler.rs
  ingester2/src/server/grpc/query.rs
  service_grpc_flight/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6261 refactor: stream-based(TM) `to_series_and_groups`, part 1
  iox_query/src/exec/context.rs
  query_tests/src/influxrpc/util.rs
  service_grpc_influxrpc/src/service.rs
Labels: automerge

#6265 refactor: stream-based(TM) `to_series_and_groups`, part 2
  iox_query/src/exec/context.rs
  iox_query/src/exec/seriesset/converter.rs
Labels: automerge

#6263 perf(ingester2): streaming buffer tree queries
  ingester2/Cargo.toml
  ingester2/src/buffer_tree/namespace.rs
  ingester2/src/buffer_tree/root.rs
  ingester2/src/buffer_tree/table.rs
  ingester2/src/query/exec.rs
  ingester2/src/query/instrumentation.rs
  ingester2/src/query/mock_query_exec.rs
  ingester2/src/query/tracing.rs
  ingester2/src/query/trait.rs
  ingester2/src/server/grpc.rs
  ingester2/src/server/grpc/query.rs
Labels: kodiak: merge.method = 'merge', kafkaless

#6245 docs: data retention
  docs/README.md
  docs/retention_policy.md
Labels: automerge

#6267 chore: update dependencies
  Cargo.lock
  workspace-hack/Cargo.toml
Labels: automerge

#6278 feat: add router config parameter for retention
  clap_blocks/src/lib.rs
  clap_blocks/src/router.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/src/commands/run/router.rs
  ioxd_router/src/lib.rs
  router/src/dml_handlers/ns_autocreation.rs
Labels: automerge

#6275 refactor: stream-based(TM) `to_series_and_groups`, part 3
  iox_query/src/exec/context.rs
Labels: automerge

#6274 feat: sequence rpc writes
  Cargo.lock
  ingester2/Cargo.toml
  ingester2/src/init.rs
  ingester2/src/lib.rs
  ingester2/src/server/grpc.rs
  ingester2/src/server/grpc/rpc_write.rs
  ingester2/src/timestamp_oracle.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6279 chore: Update Datafusion and arrow/arrow-flight/parquet to `28.0.0`
  Cargo.lock
  Cargo.toml
  arrow_util/src/optimize.rs
  ingester2/Cargo.toml
  parquet_file/Cargo.toml
  parquet_file/src/metadata.rs
  schema/src/lib.rs
  trace_exporters/Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#6284 fix: Get the file stem rather than file name for the UUID
  wal/src/lib.rs
  wal/tests/end_to_end.rs
Labels: automerge

#6287 fix: Maintain WAL segment file ordering
  Cargo.lock
  wal/Cargo.toml
  wal/src/blocking/reader.rs
  wal/src/blocking/writer.rs
  wal/src/lib.rs
  wal/tests/end_to_end.rs
Labels: automerge

#6280 feat(ingester2): commit DML ops to WAL
  Cargo.lock
  ingester2/Cargo.toml
  ingester2/src/dml_sink/trait.rs
  ingester2/src/lib.rs
  ingester2/src/server/grpc/rpc_write.rs
  ingester2/src/wal/mod.rs
  ingester2/src/wal/traits.rs
  ingester2/src/wal/wal_sink.rs
  wal/src/lib.rs
  wal/tests/end_to_end.rs
Labels: automerge, kodiak: merge.method = 'merge'
