Repository influxdata/influxdb_iox, pull requests merged in 2022-05, with the labels that each got.

#4492 docs: fix the wrong link jumping in README
  README.md
Labels: automerge, kodiak: merge.method = 'squash'

#4494 fix: allow `--grpc-bind` and `--api-bind` args in all-in-one mode
  compactor/src/handler.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ioxd_compactor/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4487 refactor: query_tests - port a few OG to NG tests and remove many more that already ported
  query_tests/cases/in/chunk_order.expected
  query_tests/cases/in/chunk_order.sql
  query_tests/cases/in/duplicates.expected
  query_tests/cases/in/duplicates.sql
  query_tests/cases/in/no_stats_plans.expected
  query_tests/cases/in/no_stats_plans.sql
  query_tests/cases/in/old_sql_system_tables.expected
  query_tests/cases/in/old_sql_system_tables.sql
  query_tests/cases/in/old_sql_system_tables2.expected
  query_tests/cases/in/old_sql_system_tables2.sql
  query_tests/cases/in/old_stats_plans.expected
  query_tests/cases/in/old_stats_plans.sql
  query_tests/src/cases.rs
  query_tests/src/scenarios.rs
  query_tests/src/scenarios/delete.rs
  query_tests/src/scenarios/library.rs
  query_tests/src/scenarios/util.rs
  query_tests/src/sql.rs
Labels: automerge

#4495 fix: shutdown compactor more quickly on cancel
  compactor/src/handler.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4506 feat: Remove the server_benchmarks crate
  .guppy/hakari.toml
  Cargo.lock
  Cargo.toml
  query_tests/src/lib.rs
  server_benchmarks/Cargo.toml
  server_benchmarks/benches/catalog_persistence.rs
  server_benchmarks/benches/encoders.rs
  server_benchmarks/benches/fixtures.rs
  server_benchmarks/benches/influxrpc.rs
  server_benchmarks/benches/line_parser.rs
  server_benchmarks/benches/mapper.rs
  server_benchmarks/benches/read_filter.rs
  server_benchmarks/benches/read_group.rs
  server_benchmarks/benches/run_bench.sh
  server_benchmarks/benches/scrape_benches.sh
  server_benchmarks/benches/snapshot.rs
  server_benchmarks/benches/storectl-bench.sh
  server_benchmarks/benches/tag_values.rs
  server_benchmarks/src/lib.rs
Labels: automerge

#4507 feat: Remove outdated OG docs
  docs/README.md
  docs/catalog_persistence.md
  docs/catalogs.md
  docs/data_management.md
  docs/data_organization_lifecycle.md
  docs/drawings/data_lifecycle.monopic
  docs/drawings/data_organization.monopic
  docs/encoding_thoughts.md
  docs/ingest.md
  docs/server_startup.md
Labels: automerge

#4505 fix: Add go_package to protos
  generated_types/protos/influxdata/iox/catalog/v1/parquet_file.proto
  generated_types/protos/influxdata/iox/catalog/v1/service.proto
  generated_types/protos/influxdata/iox/ingester/v1/parquet_metadata.proto
  generated_types/protos/influxdata/iox/ingester/v1/query.proto
  generated_types/protos/influxdata/iox/ingester/v1/write_info.proto
  generated_types/protos/influxdata/iox/object_store/v1/service.proto
  generated_types/protos/influxdata/iox/predicate/v1/predicate.proto
  generated_types/protos/influxdata/iox/preserved_catalog/v1/catalog.proto
  generated_types/protos/influxdata/iox/preserved_catalog/v1/parquet_metadata.proto
  generated_types/protos/influxdata/iox/querier/v1/flight.proto
  generated_types/protos/influxdata/iox/write_summary/v1/write_summary.proto
Labels: automerge

#4516 chore: Update datafusion and upgrade arrow/parquet/arrow-flight to 13
  Cargo.lock
  arrow_util/Cargo.toml
  compactor/Cargo.toml
  datafusion/Cargo.toml
  db/Cargo.toml
  influxdb_iox/Cargo.toml
  influxdb_iox_client/Cargo.toml
  ingester/Cargo.toml
  iox_tests/Cargo.toml
  ioxd_database/Cargo.toml
  ioxd_querier/Cargo.toml
  ioxd_router2/Cargo.toml
  mutable_batch/Cargo.toml
  mutable_buffer/Cargo.toml
  packers/Cargo.toml
  parquet_catalog/Cargo.toml
  parquet_file/Cargo.toml
  parquet_file/src/metadata.rs
  predicate/Cargo.toml
  querier/Cargo.toml
  query/Cargo.toml
  query/src/exec/seriesset/series.rs
  query_functions/Cargo.toml
  query_tests/Cargo.toml
  read_buffer/Cargo.toml
  schema/Cargo.toml
  scripts/update_arrow_deps.py
  service_grpc_flight/Cargo.toml
  service_grpc_influxrpc/Cargo.toml
  test_helpers_end_to_end_ng/Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#4520 fix: Move schema pivot work out of `execute`
  Cargo.lock
  datafusion_util/Cargo.toml
  datafusion_util/src/lib.rs
  datafusion_util/src/watch.rs
  query/src/exec/non_null_checker.rs
  query/src/exec/schema_pivot.rs
  query/src/provider/deduplicate.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4518 chore: Update datafusion (again)
  Cargo.lock
  datafusion/Cargo.toml
  datafusion_util/src/lib.rs
  db/src/system_tables.rs
  querier/src/system_tables/mod.rs
  query/src/exec/context.rs
  query/src/exec/non_null_checker.rs
  query/src/exec/query_tracing.rs
  query/src/exec/schema_pivot.rs
  query/src/exec/split.rs
  query/src/provider/deduplicate.rs
  query/src/provider/physical.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4486 feat: Remove outdated management APIs / CLI commands
  .circleci/config.yml
  Cargo.lock
  Cargo.toml
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/database.rs
  influxdb_iox/src/commands/debug/mod.rs
  influxdb_iox/src/commands/debug/schema.rs
  influxdb_iox/src/commands/query.rs
  influxdb_iox/src/commands/run/database.rs
  influxdb_iox/src/commands/run/mod.rs
  influxdb_iox/src/commands/run/router.rs
  influxdb_iox/src/commands/write.rs
  influxdb_iox/src/main.rs
  influxdb_iox/tests/end_to_end_ng_cases/schema.rs
  ioxd_database/Cargo.toml
  ioxd_database/src/config.rs
  ioxd_database/src/http.rs
  ioxd_database/src/lib.rs
  ioxd_database/src/rpc/delete.rs
  ioxd_database/src/rpc/deployment.rs
  ioxd_database/src/rpc/error.rs
  ioxd_database/src/rpc/management.rs
  ioxd_database/src/rpc/mod.rs
  ioxd_database/src/rpc/operations.rs
  ioxd_database/src/rpc/query.rs
  ioxd_database/src/rpc/write_pb.rs
  ioxd_database/src/setup.rs
  ioxd_router/Cargo.toml
  ioxd_router/src/http.rs
  ioxd_router/src/lib.rs
  ioxd_router/src/rpc/delete.rs
  ioxd_router/src/rpc/deployment.rs
  ioxd_router/src/rpc/mod.rs
  ioxd_router/src/rpc/remote.rs
  ioxd_router/src/rpc/router.rs
  ioxd_router/src/rpc/write_pb.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4528 fix: Remove commented out code, fix rather than allow a clippy lint
  influxdb_iox/src/commands/query.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4517 fix: Remove OG proto definitions
  generated_types/build.rs
  generated_types/protos/influxdata/iox/deployment/v1/service.proto
  generated_types/protos/influxdata/iox/management/v1/chunk.proto
  generated_types/protos/influxdata/iox/management/v1/database_rules.proto
  generated_types/protos/influxdata/iox/management/v1/jobs.proto
  generated_types/protos/influxdata/iox/management/v1/partition.proto
  generated_types/protos/influxdata/iox/management/v1/partition_template.proto
  generated_types/protos/influxdata/iox/management/v1/server_config.proto
  generated_types/protos/influxdata/iox/management/v1/service.proto
  generated_types/protos/influxdata/iox/preserved_catalog/v1/catalog.proto
  generated_types/protos/influxdata/iox/preserved_catalog/v1/parquet_metadata.proto
  generated_types/protos/influxdata/iox/remote/v1/remote.proto
  generated_types/protos/influxdata/iox/remote/v1/service.proto
  generated_types/protos/influxdata/iox/router/v1/router.proto
  generated_types/protos/influxdata/iox/router/v1/service.proto
  generated_types/protos/influxdata/iox/router/v1/shard.proto
  generated_types/src/chunk.rs
  generated_types/src/database_rules.rs
  generated_types/src/database_rules/lifecycle.rs
  generated_types/src/database_rules/partition.rs
  generated_types/src/database_state.rs
  generated_types/src/google.rs
  generated_types/src/job.rs
  generated_types/src/lib.rs
  generated_types/src/router.rs
  generated_types/src/server_config.rs
  generated_types/src/write_buffer.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4544 refactor: rewrite all structs and functions to remove "new"
  query_tests/src/scenarios/delete.rs
  query_tests/src/scenarios/library.rs
  query_tests/src/scenarios/util.rs
Labels: automerge

#4534 refactor: simplify object_store path handling
  clap_blocks/Cargo.toml
  clap_blocks/src/object_store.rs
  compactor/src/compact.rs
  compactor/src/garbage_collector.rs
  influxdb_iox/src/commands/remote/partition.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/src/commands/run/compactor.rs
  influxdb_iox/src/commands/run/ingester.rs
  influxdb_iox/src/commands/run/querier.rs
  influxdb_iox/src/commands/run/router.rs
  ingester/src/data.rs
  ingester/src/handler.rs
  ingester/src/persist.rs
  ingester/src/test_util.rs
  iox_object_store_service/src/lib.rs
  iox_tests/src/util.rs
  object_store/src/aws.rs
  object_store/src/azure.rs
  object_store/src/buffer.rs
  object_store/src/cache.rs
  object_store/src/disk.rs
  object_store/src/dummy.rs
  object_store/src/gcp.rs
  object_store/src/instrumentation.rs
  object_store/src/lib.rs
  object_store/src/memory.rs
  object_store/src/path.rs
  object_store/src/path/cloud.rs
  object_store/src/path/file.rs
  object_store/src/path/mod.rs
  object_store/src/path/parsed.rs
  object_store/src/path/parts.rs
  object_store/src/throttle.rs
  parquet_file/src/lib.rs
  parquet_file/src/storage.rs
  querier/src/handler.rs
Labels: automerge

#4547 refactor: split out ObjectStoreMetrics
  Cargo.lock
  Cargo.toml
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/run/compactor.rs
  influxdb_iox/src/commands/run/ingester.rs
  influxdb_iox/src/commands/run/querier.rs
  influxdb_iox/src/commands/run/router.rs
  object_store/Cargo.toml
  object_store/src/lib.rs
  object_store_metrics/Cargo.toml
  object_store_metrics/src/dummy.rs
  object_store_metrics/src/lib.rs
Labels: automerge

#4546 test: explain tests for queries whose data come from both parquet and ingester
  query_tests/cases/in/new_sql_system_tables.expected
  query_tests/cases/in/new_sql_system_tables.sql
  query_tests/cases/in/several_chunks.expected
  query_tests/cases/in/several_chunks.sql
  query_tests/cases/in/two_chunks.expected
  query_tests/cases/in/two_chunks.sql
  query_tests/src/cases.rs
  query_tests/src/scenarios.rs
  query_tests/src/scenarios/library.rs
Labels: automerge

#4550 fix: feature flags
  clap_blocks/src/object_store.rs
  influxdb_iox/Cargo.toml
Labels: automerge

#4548 chore: rename INFLUXDB_IOX_BUCKET to OBJECT_STORE_BUCKET in object_store tests
  .circleci/config.yml
  object_store/src/aws.rs
  object_store/src/azure.rs
  object_store/src/gcp.rs
Labels: automerge

#4557 feat: Interrogate schema from querier (as well as router)
  Cargo.lock
  Cargo.toml
  influxdb_iox/tests/end_to_end_ng_cases/cli.rs
  ioxd_querier/src/lib.rs
  querier/Cargo.toml
  querier/src/handler.rs
  querier/src/server.rs
  router/Cargo.toml
  router/src/server/grpc.rs
  service_grpc_schema/Cargo.toml
  service_grpc_schema/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4564 chore: remove azure git pin
  .guppy/hakari.toml
  Cargo.lock
  object_store/Cargo.toml
Labels: automerge

#4566 chore: Update heappy
  Cargo.lock
  influxdb_iox/Cargo.toml
Labels: automerge, kodiak: merge.method = 'merge'

#4559 docs: Add docs for CLI
  docs/README.md
  docs/cli.md
Labels: automerge, kodiak: merge.method = 'squash'

#4569 feat(ingester): emit query latency metrics
  ingester/src/handler.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4553 feat: support HEAD requests against object storage
  object_store/src/aws.rs
  object_store/src/azure.rs
  object_store/src/disk.rs
  object_store/src/gcp.rs
  object_store/src/lib.rs
  object_store/src/memory.rs
  object_store/src/throttle.rs
  object_store_metrics/src/dummy.rs
  object_store_metrics/src/lib.rs
Labels: automerge

#4571 chore: dump out the diff for SQL tests
  Cargo.lock
  query_tests/Cargo.toml
  query_tests/src/cases.rs
  query_tests/src/runner.rs
Labels: automerge

#4575 feat: add more metrics for compactor
  compactor/src/compact.rs
Labels: automerge

#4573 feat: Querier can get write status from ingesters
  data_types/src/lib.rs
  generated_types/src/lib.rs
  generated_types/src/write_info.rs
  influxdb_iox/tests/end_to_end_ng_cases/all_in_one.rs
  influxdb_iox/tests/end_to_end_ng_cases/querier.rs
  influxdb_iox/tests/end_to_end_ng_cases/querier/multi_ingester.rs
  influxdb_iox_client/src/client/write_info.rs
  ingester/src/server/grpc.rs
  ioxd_querier/src/lib.rs
  ioxd_querier/src/rpc/mod.rs
  ioxd_querier/src/rpc/write_info.rs
  querier/src/database.rs
  querier/src/ingester/mod.rs
  querier/src/ingester/test_util.rs
  test_helpers_end_to_end_ng/src/client.rs
  test_helpers_end_to_end_ng/src/steps.rs
  write_summary/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4572 refactor: rename iox_object_store_service to `service_grpc_object_store` for consistency
  Cargo.lock
  Cargo.toml
  router/Cargo.toml
  router/src/server/grpc.rs
  service_grpc_object_store/Cargo.toml
  service_grpc_object_store/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4579 refactor: Rearrange delegation to remove one usage of generated types
  ioxd_querier/src/rpc/write_info.rs
  querier/src/database.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4580 feat: Add more logging to understand the flaky multi ingester test better
  .circleci/config.yml
  influxdb_iox/tests/end_to_end_ng_cases/querier/multi_ingester.rs
  trogging/src/cli.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4588 fix: Remove pprof feature; it fails to build
  .circleci/config.yml
Labels: automerge

#4589 chore: convert some debug to trace to reduce noises
  query/src/provider/deduplicate/algo.rs
  query_tests/cases/in/several_chunks.expected
  query_tests/cases/in/several_chunks.sql
Labels: automerge

#4590 chore: Enable pprof feature back
  .circleci/config.yml
  ioxd_common/Cargo.toml
Labels: automerge

#4189 feat: LRU cache infrastructure
  querier/src/cache_system/backend/addressable_heap.rs
  querier/src/cache_system/backend/lru.rs
  querier/src/cache_system/backend/mod.rs
  querier/src/cache_system/backend/resource_consumption.rs
  querier/src/lib.rs
Labels: automerge

#4583 fix: Use one (shared) http2 connection per querier and ingester pair
  querier/src/ingester/flight_client.rs
  querier/src/ingester/mod.rs
  query_tests/src/scenarios/util.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4592 refactor: move `querier::cache_system` into its own crate
  Cargo.lock
  Cargo.toml
  cache_system/Cargo.toml
  cache_system/benches/addressable_heap.rs
  cache_system/src/backend/addressable_heap.rs
  cache_system/src/backend/dual.rs
  cache_system/src/backend/hash_map.rs
  cache_system/src/backend/lru.rs
  cache_system/src/backend/mod.rs
  cache_system/src/backend/resource_consumption.rs
  cache_system/src/backend/test_util.rs
  cache_system/src/backend/ttl.rs
  cache_system/src/driver.rs
  cache_system/src/lib.rs
  cache_system/src/loader.rs
  querier/Cargo.toml
  querier/src/cache/namespace.rs
  querier/src/cache/partition.rs
  querier/src/cache/processed_tombstones.rs
  querier/src/cache/table.rs
  querier/src/cache_system/mod.rs
  querier/src/lib.rs
Labels: automerge

#4586 fix: Remove ChunkAddr and old_gen_partition_key
  compactor/src/query.rs
  data_types/src/lib.rs
  ingester/src/query.rs
  querier/src/cache/partition.rs
  querier/src/chunk/mod.rs
  querier/src/chunk/query_access.rs
  querier/src/ingester/mod.rs
  querier/src/table/mod.rs
  query/src/lib.rs
  query/src/test.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4581 refactor: rename `iox_catalog_service` to `service_grpc_catalog` for consistency
  Cargo.lock
  Cargo.toml
  router/Cargo.toml
  router/src/server/grpc.rs
  service_grpc_catalog/Cargo.toml
  service_grpc_catalog/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4599 chore: Update datafusion dependency
  Cargo.lock
  datafusion/Cargo.toml
  querier/src/system_tables/mod.rs
  query/src/provider.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4598 chore: move noisy debug to trace and fix some comments
  clap_blocks/src/compactor.rs
  compactor/src/compact.rs
  compactor/src/utils.rs
  parquet_file/src/chunk.rs
  parquet_file/src/storage.rs
  query/src/exec/split.rs
  query/src/provider.rs
  query/src/provider/deduplicate.rs
  query/src/provider/physical.rs
Labels: automerge

#4609 feat: Add more logging in particular situations to debug flaky test
  ingester/src/data.rs
  ingester/src/querier_handler.rs
  querier/src/ingester/flight_client.rs
  querier/src/ingester/mod.rs
  querier/src/table/mod.rs
  querier/src/table/state_reconciler.rs
  write_summary/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4607 chore(deps): Merge all the kube deps together
  Cargo.lock
  iox_gitops_adapter/Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'merge'

#4619 chore: Update datafusion + `arrow`/`parquet`/`arrow-flight` to `14.0.0`
  Cargo.lock
  arrow_util/Cargo.toml
  compactor/Cargo.toml
  datafusion/Cargo.toml
  influxdb_iox/Cargo.toml
  influxdb_iox_client/Cargo.toml
  influxdb_iox_client/src/client/flight.rs
  ingester/Cargo.toml
  iox_tests/Cargo.toml
  ioxd_querier/Cargo.toml
  mutable_batch/Cargo.toml
  packers/Cargo.toml
  parquet_file/Cargo.toml
  predicate/Cargo.toml
  predicate/src/lib.rs
  querier/Cargo.toml
  query/Cargo.toml
  query/src/exec.rs
  query/src/util.rs
  query_functions/Cargo.toml
  query_tests/Cargo.toml
  read_buffer/Cargo.toml
  schema/Cargo.toml
  service_grpc_flight/Cargo.toml
  service_grpc_flight/src/lib.rs
  service_grpc_influxrpc/Cargo.toml
  test_helpers_end_to_end/Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#4625 fix: bounds check BitSet access
  arrow_util/src/bitset.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4622 refactor: remove unused cache code
  cache_system/src/backend/dual.rs
  cache_system/src/backend/mod.rs
  querier/src/cache/namespace.rs
  querier/src/cache/table.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4620 fix: partition null column serialisation
  Cargo.lock
  arrow_util/src/bitset.rs
  mutable_batch_pb/Cargo.toml
  mutable_batch_pb/src/encode.rs
  mutable_batch_pb/tests/encode.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4633 feat: check for overlapping ingester partititions in querier
  querier/src/ingester/mod.rs
  querier/src/table/mod.rs
Labels: automerge

#4635 feat: instrument querier cache loaders w/ metrics
  cache_system/src/loader/metrics.rs
  cache_system/src/loader/mod.rs
  querier/src/cache/mod.rs
  querier/src/cache/namespace.rs
  querier/src/cache/partition.rs
  querier/src/cache/processed_tombstones.rs
  querier/src/cache/table.rs
Labels: automerge

#4640 ci: simplify cargo deny
  .circleci/config.yml
  deny.toml
Labels: automerge

#4637 chore: Remove dead code from QueryDatabase
  querier/src/database.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4641 refactor: parquet store
  Cargo.lock
  compactor/src/compact.rs
  compactor/src/handler.rs
  compactor/src/utils.rs
  ingester/src/data.rs
  ingester/src/persist.rs
  iox_tests/src/util.rs
  ioxd_compactor/Cargo.toml
  ioxd_compactor/src/lib.rs
  ioxd_querier/Cargo.toml
  ioxd_querier/src/lib.rs
  ioxd_querier/src/rpc/namespace.rs
  parquet_file/src/chunk.rs
  parquet_file/src/storage.rs
  querier/src/chunk/mod.rs
  querier/src/database.rs
  querier/src/handler.rs
  querier/src/namespace/mod.rs
  querier/src/namespace/test_util.rs
  querier/src/table/test_util.rs
  query_tests/Cargo.toml
  query_tests/src/scenarios/util.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4644 refactor: Encapsulate reconciliation logic more
  querier/src/table/mod.rs
  querier/src/table/query_access.rs
  querier/src/table/state_reconciler.rs
  querier/src/table/state_reconciler/interface.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4642 feat: add `measurement_fields` support to `influxdb_iox storage`
  influxdb_iox/src/commands/storage.rs
  influxdb_iox/src/commands/storage/request.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4643 fix: ensure that query tokio background tasks are canceled
  Cargo.lock
  datafusion_util/Cargo.toml
  datafusion_util/src/lib.rs
  datafusion_util/src/watch.rs
  iox_query/src/exec/non_null_checker.rs
  iox_query/src/exec/schema_pivot.rs
  iox_query/src/exec/split.rs
  iox_query/src/provider/deduplicate.rs
  parquet_file/src/storage.rs
Labels: automerge

#4645 chore: Update to Rust 1.61
  .circleci/config.yml
  compactor/src/compact.rs
  influxdb2_client/src/lib.rs
  influxdb2_client/tests/common/server_fixture.rs
  ingester/src/data.rs
  logfmt/src/lib.rs
  rust-toolchain.toml
  tracker/src/lock.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4656 test: add query test scenario w/ missing columns in different chunks
  query_tests/cases/in/two_chunks_missing_columns.expected
  query_tests/cases/in/two_chunks_missing_columns.sql
  query_tests/src/cases.rs
  query_tests/src/scenarios.rs
  query_tests/src/scenarios/library.rs
  query_tests/src/scenarios/util.rs
Labels: automerge

#4638 feat: Add ingester CLI and env option to skip to oldest available WB seq num
  clap_blocks/src/ingester.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ingester/src/handler.rs
  ingester/src/stream_handler/handler.rs
  ioxd_ingester/src/lib.rs
  write_buffer/src/core.rs
  write_buffer/src/file.rs
  write_buffer/src/kafka/mod.rs
  write_buffer/src/mock.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4649 perf: streaming RecordBatch -> parquet encoder
  Cargo.lock
  compactor/src/compact.rs
  compactor/src/query.rs
  ingester/src/persist.rs
  iox_tests/Cargo.toml
  iox_tests/src/util.rs
  parquet_file/Cargo.toml
  parquet_file/src/chunk.rs
  parquet_file/src/lib.rs
  parquet_file/src/metadata.rs
  parquet_file/src/serialise.rs
  parquet_file/src/storage.rs
  querier/src/chunk/query_access.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4659 feat: enable debugging of failed querier->ingester requests
  Cargo.lock
  clap_blocks/src/ingester.rs
  generated_types/Cargo.toml
  generated_types/src/ingester.rs
  influxdb_iox/src/commands/query_ingester.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/tests/end_to_end_cases/cli.rs
  influxdb_iox/tests/end_to_end_cases/querier.rs
  influxdb_iox_client/src/client/flight.rs
  ingester/src/server/grpc.rs
  ioxd_ingester/src/lib.rs
  querier/src/ingester/mod.rs
  service_grpc_flight/src/lib.rs
  test_helpers_end_to_end/src/client.rs
  test_helpers_end_to_end/src/config.rs
  test_helpers_end_to_end/src/server_fixture.rs
Labels: automerge

#4662 refactor: do not embed row count & min/max timestamps in IOxMetadata
  compactor/src/compact.rs
  generated_types/protos/influxdata/iox/ingester/v1/parquet_metadata.proto
  ingester/src/compact.rs
  ingester/src/persist.rs
  ingester/src/test_util.rs
  iox_tests/src/util.rs
  parquet_file/src/metadata.rs
  parquet_file/src/serialise.rs
  parquet_file/src/storage.rs
  parquet_file/tests/metadata.rs
Labels: kodiak: merge.method = 'merge'

#4661 feat: Add `ParquetFiles` cache and memory size estimation for ParquetMetadata
  data_types/src/lib.rs
  iox_tests/src/util.rs
  parquet_file/src/chunk.rs
  parquet_file/src/metadata.rs
  querier/src/cache/mod.rs
  querier/src/cache/parquet_file.rs
  test_helpers/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4672 fix: actually log error
  querier/src/ingester/mod.rs
Labels: automerge

#4675 chore: remove unused iox_gitops_adapter
  Cargo.lock
  Cargo.toml
  iox_gitops_adapter/Cargo.toml
  iox_gitops_adapter/build.rs
  iox_gitops_adapter/src/kafka_topic_list/api.rs
  iox_gitops_adapter/src/kafka_topic_list/mock_api.rs
  iox_gitops_adapter/src/kafka_topic_list/mod.rs
  iox_gitops_adapter/src/kafka_topic_list/resources.rs
  iox_gitops_adapter/src/main.rs
  iox_gitops_adapter/test/mock-iox-failure.sh
  iox_gitops_adapter/test/mock-iox-multi-topic.sh
  iox_gitops_adapter/test/mock-iox-single-topic.sh
  workspace-hack/Cargo.toml
Labels: automerge

#4663 feat: Add `Tombstone` to querier cache
  data_types/src/lib.rs
  querier/src/cache/mod.rs
  querier/src/cache/parquet_file.rs
  querier/src/cache/tombstones.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4677 test: panic handling, add compactor to end to end test harness
  influxdb_iox/tests/end_to_end_cases/error.rs
  influxdb_iox/tests/end_to_end_cases/mod.rs
  influxdb_iox_client/src/client.rs
  influxdb_iox_client/src/client/test.rs
  test_helpers_end_to_end/src/config.rs
  test_helpers_end_to_end/src/mini_cluster.rs
  test_helpers_end_to_end/src/server_fixture.rs
  test_helpers_end_to_end/src/server_type.rs
Labels: automerge

#4682 build: remove iox_gitops_adapter from build
  .circleci/config.yml
Labels: automerge, kodiak: merge.method = 'merge'

#4679 chore: Update datafusion (again)
  Cargo.lock
  datafusion/Cargo.toml
  iox_query/src/exec.rs
  iox_query/src/frontend/influxrpc.rs
  iox_query/src/frontend/reorg.rs
  iox_query/src/util.rs
  predicate/src/delete_expr.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4684 test: add debug output to test
  influxdb_iox/tests/end_to_end_cases/querier/multi_ingester.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4685 refactor: Implement `new_querier_chunk` and `new_querier_chunk_from_file_with_metadata`
  compactor/src/compact.rs
  querier/src/chunk/mod.rs
  querier/src/ingester/mod.rs
  querier/src/table/state_reconciler.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4660 fix: ensure querier cache is refreshed for partition sort key
  influxdb_iox/tests/end_to_end_cases/querier.rs
  iox_tests/src/util.rs
  querier/src/cache/partition.rs
  querier/src/chunk/mod.rs
  querier/src/chunk/query_access.rs
  querier/src/ingester/mod.rs
  querier/src/ingester/test_util.rs
  querier/src/table/mod.rs
  querier/src/table/state_reconciler.rs
  querier/src/table/state_reconciler/interface.rs
  query_tests/generate/src/main.rs
  query_tests/src/cases.rs
  test_helpers_end_to_end/src/config.rs
Labels: automerge

#4697 refactor: de-duplicate low-level arrow code
  Cargo.lock
  arrow_util/Cargo.toml
  arrow_util/src/optimize.rs
  ingester/src/server/grpc.rs
  service_grpc_flight/Cargo.toml
  service_grpc_flight/src/lib.rs
Labels: automerge

#4671 feat: teach compactor to compact smaller number of files
  clap_blocks/src/compactor.rs
  compactor/src/compact.rs
  compactor/src/handler.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ioxd_compactor/src/lib.rs
Labels: automerge

#4701 fix: expire empty parquet_files cache and empty tombstones cache
  querier/src/cache/parquet_file.rs
  querier/src/cache/tombstones.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4704 feat: Start of a read buffer chunk cache
  Cargo.lock
  cache_system/src/driver.rs
  compactor/src/compact.rs
  querier/Cargo.toml
  querier/src/cache/mod.rs
  querier/src/cache/read_buffer.rs
  querier/src/chunk/mod.rs
  querier/src/chunk/query_access.rs
  querier/src/table/state_reconciler.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4706 test: reproducer for 4695
  parquet_file/src/metadata.rs
  parquet_file/src/serialise.rs
  parquet_file/tests/metadata.rs
Labels: automerge

#4650 feat: avoid catalog access on each query
  influxdb_iox/tests/end_to_end_cases/querier.rs
  iox_tests/src/util.rs
  querier/src/cache/mod.rs
  querier/src/database.rs
  querier/src/namespace/mod.rs
  querier/src/namespace/query_access.rs
  querier/src/namespace/test_util.rs
  querier/src/table/mod.rs
  querier/src/table/state_reconciler.rs
  querier/src/table/state_reconciler/interface.rs
  querier/src/table/test_util.rs
  querier/src/tombstone.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4711 fix: fix one intermittent failure in `end_to_end_cases::querier::multi_ingester::basic_multi_ingesters`
  influxdb_iox/tests/end_to_end_cases/querier/multi_ingester.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4713 test: parquet meta decoded tests and more debug info
  parquet_file/src/metadata.rs
  parquet_file/src/storage.rs
  parquet_file/tests/metadata.rs
Labels: automerge

#4715 chore: point tests to the new ticket
  parquet_file/tests/metadata.rs
Labels: automerge

#4716 refactor: add partition ID into debug info and panic earlier to identify the bug easier
  compactor/src/compact.rs
  compactor/src/utils.rs
  ingester/src/data.rs
  parquet_file/src/metadata.rs
  parquet_file/src/serialise.rs
  parquet_file/src/storage.rs
  parquet_file/tests/metadata.rs
Labels: automerge

#4717 refactor: use consistent spelling of serialize in logging and code
  compactor/src/compact.rs
  generated_types/protos/influxdata/iox/ingester/v1/parquet_metadata.proto
  generated_types/src/google.rs
  ingester/src/persist.rs
  ingester/src/stream_handler/handler.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/postgres.rs
  mutable_batch_pb/tests/encode.rs
  parquet_file/src/lib.rs
  parquet_file/src/metadata.rs
  parquet_file/src/serialize.rs
  parquet_file/src/storage.rs
  parquet_file/tests/metadata.rs
  router/src/dml_handlers/schema_validation.rs
  router/src/server/http.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4719 test: test that hits panic becasue of no column meta data
  parquet_file/src/serialize.rs
  parquet_file/tests/metadata.rs
Labels: automerge

#4709 feat: Make a QuerierRBChunk wrapper that implement QueryChunk and QueryChunkMeta
  compactor/src/compact.rs
  data_types/src/lib.rs
  parquet_file/src/chunk.rs
  querier/src/cache/mod.rs
  querier/src/cache/read_buffer.rs
  querier/src/chunk/mod.rs
  querier/src/chunk/query_access.rs
  querier/src/database.rs
  querier/src/namespace/mod.rs
  querier/src/table/mod.rs
  querier/src/table/state_reconciler.rs
  querier/src/table/test_util.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4718 chore: reduce `debug!` log spew in `parquet_file`
  parquet_file/src/metadata.rs
  parquet_file/src/serialize.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4710 fix: Turn cargo doc warnings into errors
  .circleci/config.yml
  ioxd_querier/src/rpc/namespace.rs
  query_functions/src/selectors.rs
  service_grpc_influxrpc/src/service.rs
  test_helpers_end_to_end/src/config.rs
  test_helpers_end_to_end/src/mini_cluster.rs
Labels: automerge, kodiak: merge.method = 'squash'

#4723 chore: Update datafusion
  Cargo.lock
  datafusion/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#4703 feat: add concurrency limit for ingester queries
  clap_blocks/src/ingester.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ingester/src/handler.rs
  ingester/src/querier_handler.rs
  ioxd_ingester/src/lib.rs
Labels: automerge

#4727 fix: do NOT block in parquet file IO
  Cargo.lock
  parquet_file/Cargo.toml
  parquet_file/src/storage.rs
Labels: automerge

#4737 feat: limit tmp parquet file count and size
  parquet_file/src/storage.rs
Labels: automerge

#4741 refactor: do NOT use ANY file IO for parquet reading
  Cargo.lock
  parquet_file/Cargo.toml
  parquet_file/src/storage.rs
Labels: automerge

#4742 refactor: remove unused code
  Cargo.lock
  parquet_file/Cargo.toml
  parquet_file/src/storage.rs
Labels: automerge

#4745 test: fix test_metadata_from_parquet_metadata
  parquet_file/src/metadata.rs
Labels: automerge, kodiak: merge.method = 'merge'

#4746 chore: increase size of a compactor job and level of concurrency
  clap_blocks/src/compactor.rs
  compactor/src/compact.rs
Labels: automerge
