Repository influxdata/influxdb_iox, pull requests merged in 2022-01, with the labels that each got.

#3420 chore: lint markdown docs and use relative code references in docs
  .circleci/config.yml
  docs/catalog_persistence.md
  docs/catalogs.md
  docs/data_organization_lifecycle.md
  docs/logging.md
  scripts/lint_docs.py
Labels: automerge, kodiak: merge.method = 'squash'

#3421 feat: Add `table_name` to `Partition` response in management client
  data_types/src/partition_metadata.rs
  db/src/access.rs
  db/src/catalog.rs
  db/src/chunk.rs
  db/src/lib.rs
  db/src/lifecycle/compact.rs
  db/src/lifecycle/persist.rs
  db/src/utils.rs
  generated_types/protos/influxdata/iox/management/v1/partition.proto
  influxdb_iox/src/commands/database/partition.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/management.rs
  influxdb_iox/tests/end_to_end_cases/management_api.rs
  query/src/lib.rs
  query/src/test.rs
  query_tests/src/scenarios.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3424 refactor: Split database.rs into smaller modules
  server/src/database.rs
  server/src/database/init.rs
  server/src/database/owner.rs
  server/src/database/state.rs
  server/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3422 refactor: Remove `Result` in QueryDatabase trait (none of the functions can fail)
  db/src/access.rs
  db/src/lib.rs
  db/src/lifecycle/compact.rs
  db/src/lifecycle/load.rs
  db/src/lifecycle/persist.rs
  db/src/utils.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/management.rs
  query/src/lib.rs
  query/src/test.rs
  query_tests/src/scenarios/util.rs
  server/src/lib.rs
  server/tests/delete.rs
  server/tests/write_buffer_lifecycle.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3425 feat: Allow wipe catalog in `ReplayError` and `WriteBufferCreationError` states
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/error.rs
  influxdb_iox/tests/end_to_end_cases/management_cli.rs
  server/src/database.rs
  server/src/database/init.rs
  server/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3427 refactor: Clean up code by using `lit` and `lit_timestamp_nano`
  query/src/frontend/influxrpc.rs
  query/src/frontend/reorg.rs
  read_buffer/src/row_group.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3418 docs: document ingest flow
  docs/ingest.md
Labels: automerge, kodiak: merge.method = 'squash'

#3426 fix(influxrpc): support _field predicates in gRPC queries (support `*` wildcard in InfluxQL)
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/storage/expr.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3435 ci: use CLI-driven SSH for cargo
  .circleci/config.yml
Labels: automerge

#3432 chore: `cargo update`
  Cargo.lock
  db/src/lib.rs
  parquet_catalog/src/dump.rs
  parquet_file/src/metadata.rs
  workspace-hack/Cargo.toml
Labels: automerge

#3443 chore: Update datafusion dependency
  Cargo.lock
  datafusion/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#3444 fix: parquet column count statistics (#2124)
  parquet_file/src/metadata.rs
  parquet_file/src/test_utils.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3446 feat: router2 skeleton
  Cargo.lock
  Cargo.toml
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/run/mod.rs
  influxdb_iox/src/commands/run/router2.rs
  influxdb_iox/src/influxdb_ioxd/http/dml.rs
  influxdb_iox/src/influxdb_ioxd/http/error.rs
  influxdb_iox/src/influxdb_ioxd/server_type/mod.rs
  influxdb_iox/src/influxdb_ioxd/server_type/router2.rs
  router2/Cargo.toml
  router2/src/lib.rs
  router2/src/server.rs
  router2/src/server/grpc.rs
  router2/src/server/http.rs
Labels: automerge

#3429 test: Reproducer for #3428
  query_tests/src/influxrpc/read_filter.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3456 fix: undetected gzip HTTP body truncation
  influxdb_iox/src/influxdb_ioxd/http/utils.rs
Labels: bug, automerge

#3453 fix: Fix max timestamp value comparison in chunk metadata
  data_types/src/timestamp.rs
  mutable_buffer/src/snapshot.rs
  parquet_file/src/chunk.rs
  query/src/frontend/influxrpc.rs
  query_tests/src/influxrpc/read_filter.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3455 chore: update datafusion, arrow, prost, tonic, pbjson, etc
  Cargo.lock
  arrow_util/Cargo.toml
  client_util/Cargo.toml
  datafusion/Cargo.toml
  db/Cargo.toml
  db/src/lib.rs
  generated_types/Cargo.toml
  generated_types/build.rs
  grpc-router-test-gen/Cargo.toml
  grpc-router-test-gen/build.rs
  grpc-router/Cargo.toml
  grpc-router/src/lib.rs
  grpc-router/src/router.rs
  influxdb_iox/Cargo.toml
  influxdb_iox/tests/end_to_end_cases/operations_cli.rs
  influxdb_iox_client/Cargo.toml
  influxdb_storage_client/Cargo.toml
  mutable_batch/Cargo.toml
  mutable_batch_tests/Cargo.toml
  mutable_buffer/Cargo.toml
  packers/Cargo.toml
  parquet_catalog/Cargo.toml
  parquet_file/Cargo.toml
  parquet_file/src/metadata.rs
  predicate/Cargo.toml
  predicate/src/regex.rs
  query/Cargo.toml
  query/src/exec/seriesset/converter.rs
  query/src/func/selectors.rs
  query_tests/Cargo.toml
  read_buffer/Cargo.toml
  router2/Cargo.toml
  schema/Cargo.toml
  workspace-hack/Cargo.toml
  write_buffer/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#3449 fix: reduce "nothing to do" lifecycle messages from from debug to trace
  lifecycle/src/policy.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3461 chore: update rust to 1.58
  data_types/src/chunk_metadata.rs
  grpc-router/src/router.rs
  read_buffer/src/column.rs
  rust-toolchain.toml
Labels: automerge, kodiak: merge.method = 'squash'

#3460 feat: add query completion duration to queries system table
  arrow_util/src/display.rs
  db/src/access.rs
  db/src/lib.rs
  db/src/query_log.rs
  db/src/system_tables/queries.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/http.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/flight.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/storage/service.rs
  query/src/lib.rs
  query/src/test.rs
Labels: automerge

#3464 fix: reject empty org & bucket
  data_types/src/names.rs
Labels: bug, automerge

#3463 fix: Format `ParenExpression` RPC storage Expression `Node`s
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/storage/expr.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3469 fix: serde_json `arbitrary_precision` (#3458)
  Cargo.lock
  influxdb_iox/tests/end_to_end_cases/operations_cli.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3470 chore: upgrade clap to v3
  Cargo.lock
  influxdb_iox/Cargo.toml
  influxdb_iox/src/clap_blocks/boolean_flag.rs
  influxdb_iox/src/clap_blocks/mod.rs
  influxdb_iox/src/clap_blocks/object_store.rs
  influxdb_iox/src/clap_blocks/run_config.rs
  influxdb_iox/src/clap_blocks/server_id.rs
  influxdb_iox/src/clap_blocks/socket_addr.rs
  influxdb_iox/src/commands/database.rs
  influxdb_iox/src/commands/database/chunk.rs
  influxdb_iox/src/commands/database/partition.rs
  influxdb_iox/src/commands/database/recover.rs
  influxdb_iox/src/commands/debug/dump_catalog.rs
  influxdb_iox/src/commands/debug/mod.rs
  influxdb_iox/src/commands/operations.rs
  influxdb_iox/src/commands/router.rs
  influxdb_iox/src/commands/run/database.rs
  influxdb_iox/src/commands/run/mod.rs
  influxdb_iox/src/commands/run/router.rs
  influxdb_iox/src/commands/run/router2.rs
  influxdb_iox/src/commands/run/test.rs
  influxdb_iox/src/commands/server.rs
  influxdb_iox/src/commands/server_remote.rs
  influxdb_iox/src/commands/sql.rs
  influxdb_iox/src/influxdb_ioxd/server_type/common_state.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/mod.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/setup.rs
  influxdb_iox/src/influxdb_ioxd/server_type/test.rs
  influxdb_iox/src/main.rs
  influxdb_iox/src/structopt_blocks/mod.rs
  influxdb_iox/tests/end_to_end_cases/management_cli.rs
  iox_data_generator/Cargo.toml
  iox_data_generator/src/bin/create_database.rs
  iox_data_generator/src/bin/iox_data_generator.rs
  trace_exporters/Cargo.toml
  trace_exporters/src/lib.rs
  trogging/Cargo.toml
  trogging/src/cli.rs
  trogging/src/lib.rs
Labels: automerge

#3468 feat(router2): http write handler
  Cargo.lock
  dml/src/lib.rs
  influxdb_iox/src/commands/run/router2.rs
  influxdb_iox/src/influxdb_ioxd/server_type/router2.rs
  router2/Cargo.toml
  router2/src/dml_handler/mock.rs
  router2/src/dml_handler/mod.rs
  router2/src/dml_handler/nop.rs
  router2/src/dml_handler/trait.rs
  router2/src/lib.rs
  router2/src/server.rs
  router2/src/server/http.rs
Labels: automerge

#3441 feat: Add initial iox_catalog skeleton
  .circleci/config.yml
  Cargo.lock
  Cargo.toml
  iox_catalog/Cargo.toml
  iox_catalog/README.md
  iox_catalog/migrations/20211229171744_initial_schema.sql
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/postgres.rs
  workspace-hack/Cargo.toml
Labels: automerge

#3471 chore: Update datafusion deps
  Cargo.lock
  datafusion/Cargo.toml
  datafusion_util/src/lib.rs
  db/src/system_tables.rs
  query/src/exec/context.rs
  query/src/exec/non_null_checker.rs
  query/src/exec/query_tracing.rs
  query/src/exec/schema_pivot.rs
  query/src/exec/split.rs
  query/src/frontend.rs
  query/src/frontend/reorg.rs
  query/src/provider.rs
  query/src/provider/deduplicate.rs
  query/src/provider/physical.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3472 feat(router2): implement delete API handler
  Cargo.lock
  router2/Cargo.toml
  router2/src/dml_handler/mock.rs
  router2/src/dml_handler/nop.rs
  router2/src/dml_handler/trait.rs
  router2/src/server/http.rs
Labels: automerge

#3475 feat: implement memory backed iox_catalog
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
Labels: automerge

#3478 refactor: change all ids in catalog to their own types
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
Labels: automerge

#3480 feat: add Partition scaffolding to iox_catalog crate
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
Labels: automerge

#3481 refactor: add new type for Kafka Partition in Catalog
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
Labels: automerge

#3482 fix: typo in partitionid description
  iox_catalog/src/interface.rs
Labels: automerge

#3474 feat: add ingester crate and a few basic data structures for its data lifecycle
  Cargo.lock
  Cargo.toml
  ingester/Cargo.toml
  ingester/src/data.rs
  ingester/src/lib.rs
  ingester/src/server.rs
Labels: automerge

#3490 feat: Add parquet file records to iox_catalog
  Cargo.lock
  iox_catalog/Cargo.toml
  iox_catalog/migrations/20211229171744_initial_schema.sql
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
  workspace-hack/Cargo.toml
Labels: automerge

#3492 fix: clear postgres schema in test wasn't deleting parquet_file
  iox_catalog/src/postgres.rs
Labels: automerge

#3493 feat: add sequencer get_by_kafka_topic_id_and_partition to catalog
  ingester/src/data.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
Labels: automerge

#3494 feat: add get kafka_topic by name to catalog
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
Labels: automerge

#3495 refactor: add new fields and comments in ingest data buffer
  ingester/src/data.rs
Labels: automerge

#3476 feat: add `size` methods to DML-related types
  data_types/src/delete_predicate.rs
  db/src/lib.rs
  dml/src/lib.rs
  influxdb_iox/tests/end_to_end_cases/management_api.rs
  influxdb_iox/tests/end_to_end_cases/management_cli.rs
  mutable_batch/src/lib.rs
  mutable_buffer/src/lib.rs
  query_tests/src/sql.rs
  trace/src/ctx.rs
Labels: automerge

#3488 feat(router2): sharding abstraction & logic
  Cargo.lock
  router2/Cargo.toml
  router2/src/dml_handler/mock.rs
  router2/src/dml_handler/nop.rs
  router2/src/dml_handler/trait.rs
  router2/src/lib.rs
  router2/src/server/http.rs
  router2/src/sharder/mod.rs
  router2/src/sharder/table_namespace_sharder.rs
  router2/src/sharder/trait.rs
Labels: automerge

#3484 chore: Update datafusion (and get fix for influxql test failure)
  Cargo.lock
  datafusion/Cargo.toml
  db/src/system_tables.rs
  query/src/func/selectors.rs
  query/src/provider.rs
  query_tests/src/influxrpc/read_filter.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3485 fix: Special case tag_keys with max timestamp range
  data_types/src/timestamp.rs
  predicate/src/predicate.rs
  query/src/frontend/influxrpc.rs
  query_tests/src/influxrpc/tag_keys.rs
  query_tests/src/scenarios.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3497 refactor: rename `storage_api.rs` end to end test to `influxrpc.rs` for consistency
  influxdb_iox/tests/end_to_end_cases/influxrpc.rs
  influxdb_iox/tests/end_to_end_cases/mod.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3487 fix(InfluxQL): Limit `TimestampRange` to Min/Max times
  data_types/src/delete_predicate.rs
  data_types/src/timestamp.rs
  db/src/catalog/chunk.rs
  db/src/lifecycle/compact.rs
  db/src/lifecycle/compact_object_store.rs
  db/src/lifecycle/persist.rs
  db/src/pred.rs
  db/src/replay.rs
  dml/src/lib.rs
  generated_types/src/delete_predicate.rs
  influxdb_iox/src/influxdb_ioxd/server_type/router/http.rs
  influxdb_iox/tests/end_to_end_cases/delete_api.rs
  parquet_catalog/src/test_helpers.rs
  predicate/src/delete_predicate.rs
  predicate/src/predicate.rs
  query_tests/src/influxrpc/read_filter.rs
  query_tests/src/influxrpc/read_group.rs
  query_tests/src/influxrpc/read_window_aggregate.rs
  query_tests/src/scenarios.rs
  query_tests/src/scenarios/delete.rs
  router/src/router.rs
  server/tests/delete.rs
  server/tests/write_buffer_delete.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3496 feat: RSKafka-driven write buffer
  Cargo.lock
  write_buffer/Cargo.toml
  write_buffer/src/config.rs
  write_buffer/src/core.rs
  write_buffer/src/kafka.rs
  write_buffer/src/lib.rs
  write_buffer/src/rskafka.rs
Labels: automerge

#3503 feat: simplify linking of spans
  trace/src/span.rs
Labels: automerge

#3502 fix(InfluxQL): Support RegEx with escape sequences not supported by Rust regex
  Cargo.lock
  predicate/Cargo.toml
  predicate/src/regex.rs
  query_tests/src/influxrpc/read_filter.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3505 refactor: Clean up the Catalog API
  ingester/src/data.rs
  ingester/src/server.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
Labels: automerge

#3514 feat: ingester's compaction
  Cargo.lock
  ingester/Cargo.toml
  ingester/src/compact.rs
  ingester/src/data.rs
  ingester/src/lib.rs
  ingester/src/query.rs
Labels: automerge

#3516 feat: chunk pruning metrics
  db/src/access.rs
  query_tests/src/pruning.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3524 chore: temporarily hack around datafusion tempfiles
  Cargo.lock
  datafusion/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#3526 feat: support line protocol precision parameter (#3522)
  influxdb_iox/src/influxdb_ioxd/http/dml.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/http.rs
  influxdb_iox/src/influxdb_ioxd/server_type/router/http.rs
  mutable_batch_lp/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3527 chore: Set default to squash
  .kodiak.toml
Labels: automerge

#3519 refactor: have the deduplicate work without chunk statistics
  db/src/access.rs
  db/src/chunk.rs
  db/src/lifecycle/compact.rs
  db/src/lifecycle/compact_object_store.rs
  db/src/lifecycle/persist.rs
  ingester/src/compact.rs
  ingester/src/query.rs
  query/src/lib.rs
  query/src/provider.rs
  query/src/provider/overlap.rs
  query/src/provider/physical.rs
  query/src/pruning.rs
  query/src/test.rs
Labels: automerge

#3535 fix: merge record batches into one batch
  arrow_util/src/util.rs
  ingester/Cargo.toml
  ingester/src/compact.rs
  ingester/src/query.rs
  query/src/test.rs
  schema/src/merge.rs
Labels: automerge

#3521 refactor: remove unused const
  query/src/provider.rs
Labels: automerge

#3537 fix: bring back GIT revision to our prod images
  Dockerfile
  Dockerfile.dockerignore
Labels: automerge

#3536 fix: test logging
  Cargo.lock
  test_helpers/Cargo.toml
  test_helpers/src/lib.rs
  workspace-hack/Cargo.toml
  write_buffer/Cargo.toml
  write_buffer/src/kafka.rs
Labels: automerge

#3532 feat: add per-partition tracing
  influxdb_iox/src/influxdb_ioxd/server_type/database/mod.rs
  query/src/exec/query_tracing.rs
Labels: automerge

#3528 feat: initialise ShardedWriteBuffer
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/run/router2.rs
  router2/src/server.rs
Labels: automerge

#3529 feat: add trace collector to router2
  influxdb_iox/src/commands/run/router2.rs
  router2/src/server.rs
Labels: automerge

#3538 feat: decouple read buffer row group size from Datafusion batch size
  db/src/lifecycle.rs
  db/src/lifecycle/error.rs
  read_buffer/src/chunk.rs
  read_buffer/src/lib.rs
Labels: automerge

#3518 feat: Implement a snapshot method on DataBuffer
  Cargo.lock
  ingester/Cargo.toml
  ingester/src/data.rs
Labels: automerge

#3525 fix: Revert "chore: temporarily hack around datafusion tempfiles"
  Cargo.lock
  datafusion/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#3517 chore: Update datafusion, upgrade to arrow/parqet/arrow-flight 8.0.0
  Cargo.lock
  arrow_util/Cargo.toml
  datafusion/Cargo.toml
  datafusion_util/src/lib.rs
  db/Cargo.toml
  influxdb_iox/Cargo.toml
  influxdb_iox_client/Cargo.toml
  ingester/Cargo.toml
  ingester/src/query.rs
  mutable_batch/Cargo.toml
  mutable_buffer/Cargo.toml
  packers/Cargo.toml
  parquet_catalog/Cargo.toml
  parquet_file/Cargo.toml
  parquet_file/src/storage.rs
  predicate/Cargo.toml
  query/Cargo.toml
  query/src/exec/schema_pivot.rs
  query/src/exec/seriesset/converter.rs
  query/src/exec/split.rs
  query/src/provider.rs
  query/src/provider/adapter.rs
  query/src/pruning.rs
  query/src/statistics.rs
  query/src/test.rs
  query_tests/Cargo.toml
  read_buffer/Cargo.toml
  schema/Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#3531 feat: Add db_name/namespace to DmlWrite and DmlDelete
  db/src/lib.rs
  db/src/replay.rs
  db/src/write_buffer.rs
  dml/src/lib.rs
  influxdb_iox/src/influxdb_ioxd/http/dml.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/delete.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/write_pb.rs
  influxdb_iox/src/influxdb_ioxd/server_type/router/http.rs
  influxdb_iox/src/influxdb_ioxd/server_type/router/rpc/delete.rs
  influxdb_iox/src/influxdb_ioxd/server_type/router/rpc/write_pb.rs
  influxdb_iox/tests/end_to_end_cases/delete_api.rs
  influxdb_iox/tests/end_to_end_cases/write_pb.rs
  influxdb_iox_client/src/client/write.rs
  mutable_batch_tests/benches/write_pb.rs
  router/src/grpc_client.rs
  router/src/router.rs
  router/src/write_sink.rs
  router2/src/sharded_write_buffer.rs
  server/src/lib.rs
  server/tests/write_buffer_delete.rs
  write_buffer/src/codec.rs
  write_buffer/src/core.rs
  write_buffer/src/file.rs
  write_buffer/src/kafka.rs
  write_buffer/src/mock.rs
  write_buffer/src/rskafka.rs
Labels: automerge

#3545 refactor: remove table_names from Predicate
  Cargo.lock
  data_types/src/chunk_metadata.rs
  db/src/access.rs
  db/src/catalog.rs
  db/src/chunk.rs
  db/src/lib.rs
  db/src/utils.rs
  influxdb_iox/src/influxdb_ioxd/planner.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/management.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/storage/data.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/storage/expr.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/storage/service.rs
  predicate/Cargo.toml
  predicate/src/delete_predicate.rs
  predicate/src/lib.rs
  predicate/src/predicate.rs
  predicate/src/rpc_predicate.rs
  query/src/exec/seriesset/series.rs
  query/src/frontend/influxrpc.rs
  query/src/lib.rs
  query/src/plan/fieldlist.rs
  query/src/test.rs
  query_tests/src/influxrpc/field_columns.rs
  query_tests/src/influxrpc/read_filter.rs
  query_tests/src/influxrpc/read_group.rs
  query_tests/src/influxrpc/read_window_aggregate.rs
  query_tests/src/influxrpc/table_names.rs
  query_tests/src/influxrpc/tag_keys.rs
  query_tests/src/influxrpc/tag_values.rs
  query_tests/src/pruning.rs
  query_tests/src/scenarios.rs
  query_tests/src/scenarios/util.rs
  query_tests/src/table_schema.rs
  server/tests/delete.rs
  server_benchmarks/benches/read_filter.rs
  server_benchmarks/benches/read_group.rs
  server_benchmarks/benches/tag_values.rs
Labels: automerge

#3515 fix: Reuse the same DataFusion DiskManager and MemoryManager (Do not recreate temp files)
  query/src/exec.rs
  query/src/exec/context.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3552 build(iox_catalog): remove unused dependencies
  Cargo.lock
  iox_catalog/Cargo.toml
Labels: automerge

#3548 refactor: move chunk metrics to module
  read_buffer/src/chunk.rs
  read_buffer/src/lib.rs
  read_buffer/src/metrics.rs
Labels: automerge

#3551 chore: Update hashbrown
  Cargo.lock
  arrow_util/Cargo.toml
  db/Cargo.toml
  dml/Cargo.toml
  influxdb_iox/Cargo.toml
  lifecycle/Cargo.toml
  mutable_batch/Cargo.toml
  mutable_batch_lp/Cargo.toml
  mutable_batch_pb/Cargo.toml
  query/Cargo.toml
  read_buffer/Cargo.toml
  router/Cargo.toml
  router2/Cargo.toml
  schema/Cargo.toml
  server/Cargo.toml
  trace_http/Cargo.toml
  tracker/Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#3542 test: Delete application during Ingester's compaction
  ingester/src/compact.rs
  ingester/src/query.rs
Labels: automerge

#3556 feat: add chunk order to chunk columns table
  db/src/system_tables/columns.rs
Labels: automerge

#3558 feat: router2 sharder benchmarking
  Cargo.lock
  router2/Cargo.toml
  router2/benches/sharder.rs
Labels: automerge

#3550 refactor: include comments in test cases
  read_buffer/src/column/float.rs
Labels: automerge

#3561 fix: provide correct environment variable to change log filter
  influxdb_iox/src/main.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3554 feat: schema validation for MutableBuffer instances
  Cargo.lock
  iox_catalog/Cargo.toml
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
Labels: automerge

#3559 chore: run cargo update
  Cargo.lock
Labels: automerge

#3565 refactor: remove InfluxColumnType::IOx
  data_types/src/partition_metadata.rs
  generated_types/protos/influxdata/pbdata/v1/influxdb_pb_data_protocol.proto
  iox_catalog/src/interface.rs
  mutable_batch/src/column.rs
  mutable_batch_pb/src/decode.rs
  mutable_batch_pb/src/encode.rs
  mutable_buffer/src/lib.rs
  packers/src/packers.rs
  parquet_file/src/metadata.rs
  query/src/test.rs
  schema/src/builder.rs
  schema/src/lib.rs
Labels: automerge

#3555 fix: router2 writer buffer topic
  influxdb_iox/src/commands/run/router2.rs
Labels: automerge

#3566 build: update tokio
  Cargo.lock
Labels: automerge, dependencies

#3560 fix: chunk ordering
  db/src/lifecycle/compact.rs
  db/src/lifecycle/compact_object_store.rs
  db/src/lifecycle/persist.rs
  db/tests/chunk_ordering.rs
Labels: automerge

#3568 refactor: decouple error types for DmlHandler
  router2/src/dml_handlers/mock.rs
  router2/src/dml_handlers/nop.rs
  router2/src/dml_handlers/sharded_write_buffer.rs
  router2/src/dml_handlers/trait.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3571 feat: catalog timestamp pruning
  data_types/src/partition_metadata.rs
  db/src/access.rs
  db/src/catalog.rs
  db/src/catalog/chunk.rs
  db/src/catalog/table.rs
  mutable_buffer/src/lib.rs
Labels: automerge

#3547 feat: IoxMetadata for parquet file
  Cargo.lock
  ingester/Cargo.toml
  ingester/src/compact.rs
  ingester/src/query.rs
Labels: automerge

#3572 build: use rust 1.58.1
  rust-toolchain.toml
Labels: automerge, build, kodiak: merge.method = 'merge'

#3574 chore: feature flag consistency
  .guppy/hakari.toml
  Cargo.lock
  generated_types/Cargo.toml
  influxdb_iox/Cargo.toml
  influxdb_iox_client/Cargo.toml
  influxdb_storage_client/Cargo.toml
  parquet_catalog/Cargo.toml
  server/Cargo.toml
  workspace-hack/Cargo.toml
  write_buffer/Cargo.toml
Labels: automerge

#3575 feat: more benchmarks of router2
  router2/Cargo.toml
  router2/benches/e2e.rs
Labels: automerge

#3569 refactor: clean up ingester CLI
  influxdb_iox/src/commands/run/ingester.rs
Labels: automerge

#3563 test: add end to end tests that query missing tags
  influxdb_iox/tests/end_to_end_cases/influxrpc.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3580 refactor: Start consolidating test scenarios in query_tests
  query_tests/src/influxrpc/read_group.rs
  query_tests/src/influxrpc/read_window_aggregate.rs
  query_tests/src/scenarios.rs
  query_tests/src/scenarios/library.rs
  query_tests/src/scenarios/util.rs
  server_benchmarks/benches/read_filter.rs
  server_benchmarks/benches/read_group.rs
  server_benchmarks/benches/tag_values.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3583 feat: basic non-panic HTTP/gRPC interface for ingester
  influxdb_iox/src/influxdb_ioxd/server_type/ingester.rs
Labels: automerge

#3584 feat: allow IOx catalog to setup itself (no SQLx CLI required)
  .circleci/config.yml
  iox_catalog/README.md
  iox_catalog/build.rs
  iox_catalog/migrations/20211229171744_initial_schema.sql
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
Labels: automerge

#3581 feat: update catalog after persistence
  ingester/src/catalog_update.rs
  ingester/src/compact.rs
  ingester/src/data.rs
  ingester/src/handler.rs
  ingester/src/lib.rs
  ingester/src/query.rs
  ingester/src/test_util.rs
Labels: automerge

#3586 chore: Update datafusion
  Cargo.lock
  datafusion/Cargo.toml
  datafusion_util/src/lib.rs
  ingester/src/query.rs
  query/src/exec/schema_pivot.rs
  query/src/exec/split.rs
  query/src/util.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3544 feat: Ingester persistence
  Cargo.lock
  db/src/lifecycle/compact_object_store.rs
  db/src/lifecycle/write.rs
  generated_types/build.rs
  generated_types/protos/influxdata/iox/ingest/v1/parquet_metadata.proto
  generated_types/src/lib.rs
  influxdb_iox/src/commands/run/ingester.rs
  ingester/Cargo.toml
  ingester/src/catalog_update.rs
  ingester/src/compact.rs
  ingester/src/handler.rs
  ingester/src/lib.rs
  ingester/src/persist.rs
  ingester/src/test_util.rs
  iox_catalog/src/interface.rs
  parquet_catalog/src/dump.rs
  parquet_catalog/src/rebuild.rs
  parquet_file/Cargo.toml
  parquet_file/src/metadata.rs
  parquet_file/src/storage.rs
  parquet_file/src/test_utils/generator.rs
Labels: automerge, kodiak: merge.method = 'merge'
