Repository influxdata/influxdb_iox, pull requests merged in 2022-02, with the labels that each got.

#3520 feat: buffer writes when writing to RSKafka
  Cargo.lock
  influxdb_iox/src/commands/run/router2.rs
  router/src/connection_pool.rs
  router/src/server.rs
  router/src/write_sink.rs
  write_buffer/Cargo.toml
  write_buffer/src/codec.rs
  write_buffer/src/config.rs
  write_buffer/src/core.rs
  write_buffer/src/file.rs
  write_buffer/src/kafka.rs
  write_buffer/src/mock.rs
  write_buffer/src/rskafka/aggregator.rs
  write_buffer/src/rskafka/mod.rs
Labels: automerge

#3592 chore: upgrade rskafka and parking_lot
  Cargo.lock
  db/Cargo.toml
  influxdb2_client/Cargo.toml
  influxdb_iox/Cargo.toml
  ingester/Cargo.toml
  internal_types/Cargo.toml
  job_registry/Cargo.toml
  lifecycle/Cargo.toml
  logfmt/Cargo.toml
  metric/Cargo.toml
  mutable_buffer/Cargo.toml
  parquet_catalog/Cargo.toml
  parquet_file/Cargo.toml
  query/Cargo.toml
  read_buffer/Cargo.toml
  router/Cargo.toml
  router2/Cargo.toml
  server/Cargo.toml
  test_helpers/Cargo.toml
  time/Cargo.toml
  trace/Cargo.toml
  trace_http/Cargo.toml
  tracker/Cargo.toml
  write_buffer/Cargo.toml
Labels: automerge

#3593 fix: workspace-hack
  Cargo.lock
  workspace-hack/Cargo.toml
Labels: automerge

#3590 refactor: reusable ingester/router2 CLI pieces
  influxdb_iox/src/clap_blocks/catalog_dsn.rs
  influxdb_iox/src/clap_blocks/mod.rs
  influxdb_iox/src/clap_blocks/write_buffer.rs
  influxdb_iox/src/commands/run/ingester.rs
  influxdb_iox/src/commands/run/router2.rs
Labels: automerge

#3594 feat: add support for parsing sql expressions into RPCNode
  Cargo.lock
  predicate/Cargo.toml
  predicate/src/lib.rs
  predicate/src/sql.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3596 refactor: update dep with API change
  Cargo.lock
  read_buffer/Cargo.toml
  read_buffer/src/row_group.rs
Labels: automerge

#3595 feat: flush interface for write buffer producers
  write_buffer/src/core.rs
  write_buffer/src/file.rs
  write_buffer/src/kafka.rs
  write_buffer/src/mock.rs
  write_buffer/src/rskafka/mod.rs
Labels: automerge

#3597 refactor: introduce to_string clippy lints in read buffer
  read_buffer/src/chunk.rs
  read_buffer/src/column.rs
  read_buffer/src/column/encoding/string.rs
  read_buffer/src/column/encoding/string/dictionary.rs
  read_buffer/src/column/encoding/string/rle.rs
  read_buffer/src/column/float.rs
  read_buffer/src/column/string.rs
  read_buffer/src/lib.rs
  read_buffer/src/row_group.rs
  read_buffer/src/table.rs
  read_buffer/src/value.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3600 feat: Fold past CASE blocks / translate to boolean CASE
  predicate/src/lib.rs
  predicate/src/rewrite.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3602 fix: handle IS NULL / IS NOT NULL during rpc rewrite
  query/src/frontend/influxrpc.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3599 feat: expose all relevant configs for rskafka write buffers
  write_buffer/src/config.rs
  write_buffer/src/rskafka/config.rs
  write_buffer/src/rskafka/mod.rs
Labels: automerge

#3606 feat: add skeleton `storage` CLI command
  Cargo.lock
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/storage.rs
  influxdb_iox/src/main.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3609 chore: Use ubuntu mirror in test_perf
  .circleci/config.yml
Labels: automerge

#3608 refactor: Move query_test readme to standard location!
  query_tests/README.md
Labels: automerge, kodiak: merge.method = 'squash'

#3612 fix: Use recommended ubuntu mirror
  .circleci/config.yml
Labels: automerge

#3614 feat: increase trace buffer size
  trace_exporters/src/export.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3610 feat: catalog CLI command with update subcommand
  influxdb_iox/src/commands/catalog.rs
  influxdb_iox/src/commands/catalog/topic.rs
  influxdb_iox/src/main.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3613 chore: Update datafusion
  Cargo.lock
  datafusion/Cargo.toml
  predicate/src/rewrite.rs
  query/src/exec/context.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3576 feat(router2): write schema validation!
  Cargo.lock
  influxdb_iox/src/commands/run/router2.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  router2/Cargo.toml
  router2/src/dml_handlers/mod.rs
  router2/src/dml_handlers/schema_validation.rs
  router2/src/dml_handlers/trait.rs
  router2/src/server/http.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3588 feat: Simplify predicates in the `InfluxRpcFrontend` before using them
  db/src/access.rs
  db/src/lib.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/storage/expr.rs
  predicate/src/rpc_predicate.rs
  query/src/frontend/influxrpc.rs
  query/src/lib.rs
  query/src/test.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3618 feat: Allow sql test runner to compare sorted output
  query_tests/README.md
  query_tests/cases/in/sql_information_schema.expected
  query_tests/cases/in/sql_information_schema.sql
  query_tests/cases/in/sql_system_tables.expected
  query_tests/cases/in/sql_system_tables.sql
  query_tests/cases/in/sql_system_tables2.expected
  query_tests/cases/in/sql_system_tables2.sql
  query_tests/src/cases.rs
  query_tests/src/runner.rs
  query_tests/src/runner/parse.rs
  query_tests/src/scenarios.rs
  query_tests/src/sql.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3621 fix: Correct a 'long' argument name so the ingester command can run
  influxdb_iox/src/commands/run/ingester.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3615 refactor: remove unecessary #allow lints
  query_tests/src/pruning.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3617 feat: combine non-overlapping chunks without deletes
  query/src/provider.rs
  query_tests/cases/in/duplicates.expected
Labels: automerge, kodiak: merge.method = 'squash'

#3622 fix: remove incorrect comment
  query_tests/src/sql.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3533 feat: wire up the write buffer to the ingester process with partition creation
  Cargo.lock
  dml/src/lib.rs
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/run/ingester.rs
  ingester/Cargo.toml
  ingester/src/catalog_update.rs
  ingester/src/data.rs
  ingester/src/handler.rs
  ingester/src/lib.rs
  iox_catalog/src/lib.rs
  router2/src/dml_handlers/schema_validation.rs
Labels: automerge

#3557 fix(InfluxQL): treat null tags as `''` rather than `null` in storagerpc queries
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/storage/expr.rs
  influxdb_iox/tests/end_to_end_cases/influxrpc.rs
  predicate/src/rewrite.rs
  predicate/src/rpc_predicate.rs
  query/src/frontend/influxrpc.rs
  query/src/pruning.rs
  query/src/test.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3626 refactor: extract NamespaceSchema cache
  influxdb_iox/src/commands/run/router2.rs
  router2/src/dml_handlers/schema_validation.rs
  router2/src/lib.rs
  router2/src/namespace_cache.rs
  router2/src/namespace_cache/memory.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3624 test: ensure that rskafka and rdkakfa work together
  Cargo.lock
  workspace-hack/Cargo.toml
  write_buffer/Cargo.toml
  write_buffer/src/lib.rs
  write_buffer/src/rskafka/aggregator.rs
  write_buffer/src/rskafka/mod.rs
  write_buffer/src/rskafka_kafka_test.rs
Labels: automerge

#3625 chore: remove rdkafka dependency
  .circleci/config.yml
  Cargo.lock
  Dockerfile
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/run/ingester.rs
  perf/perf.py
  router/Cargo.toml
  server/Cargo.toml
  server/src/database/init.rs
  workspace-hack/Cargo.toml
  write_buffer/Cargo.toml
  write_buffer/src/config.rs
  write_buffer/src/kafka.rs
  write_buffer/src/kafka/aggregator.rs
  write_buffer/src/kafka/config.rs
  write_buffer/src/kafka/mod.rs
  write_buffer/src/lib.rs
  write_buffer/src/rskafka_kafka_test.rs
Labels: automerge

#3619 test: add end to end for read_filter and empty string predicates
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/storage/service.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3627 feat: catalog setup CLI command
  influxdb_iox/src/commands/catalog.rs
Labels: automerge

#3632 fix: use standard DSN argument for router2 CLI
  influxdb_iox/src/commands/run/router2.rs
Labels: automerge

#3639 refactor: Move more test scenarios into library.rs
  query_tests/src/influxrpc/read_group.rs
  query_tests/src/scenarios/library.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3641 fix: partition range in ingester CLI has INCLUSIVE end
  influxdb_iox/src/commands/run/ingester.rs
Labels: automerge

#3628 feat(router2): namespace auto-creation
  influxdb_iox/src/commands/run/router2.rs
  iox_catalog/src/lib.rs
  router2/src/dml_handlers/mod.rs
  router2/src/dml_handlers/ns_autocreation.rs
  router2/src/dml_handlers/trait.rs
  router2/src/server/http.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3643 test: Add logging to make `db` tests more debuggable
  db/src/replay.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3647 feat: emit tabular results for storage read_filter command
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/storage.rs
  influxdb_iox/src/commands/storage/request.rs
  influxdb_iox/src/commands/storage/response.rs
  influxdb_iox/src/main.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3631 refactor: improve writer buffer consumer interface
  db/src/lib.rs
  db/src/replay.rs
  db/src/write_buffer.rs
  influxdb_iox/src/commands/run/ingester.rs
  influxdb_iox/tests/end_to_end_cases/delete_api.rs
  influxdb_iox/tests/end_to_end_cases/write_pb.rs
  ingester/src/handler.rs
  server/src/database/init.rs
  write_buffer/src/config.rs
  write_buffer/src/core.rs
  write_buffer/src/file.rs
  write_buffer/src/kafka/config.rs
  write_buffer/src/kafka/mod.rs
  write_buffer/src/mock.rs
Labels: automerge

#3636 feat: insert the persisted info into the catalog in one transaction
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
  parquet_file/src/metadata.rs
Labels: automerge

#3648 refactor: Remove predicate module from predicate crate
  db/src/access.rs
  db/src/chunk.rs
  db/src/lib.rs
  db/src/pred.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/storage/expr.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/storage/service.rs
  ingester/src/query.rs
  parquet_file/src/chunk.rs
  parquet_file/src/storage.rs
  predicate/src/delete_predicate.rs
  predicate/src/lib.rs
  predicate/src/predicate.rs
  predicate/src/rpc_predicate.rs
  query/src/frontend/influxrpc.rs
  query/src/lib.rs
  query/src/provider.rs
  query/src/provider/physical.rs
  query/src/pruning.rs
  query_tests/src/influxrpc/field_columns.rs
  query_tests/src/influxrpc/read_filter.rs
  query_tests/src/influxrpc/read_group.rs
  query_tests/src/influxrpc/read_window_aggregate.rs
  query_tests/src/influxrpc/table_names.rs
  query_tests/src/influxrpc/tag_keys.rs
  query_tests/src/influxrpc/tag_values.rs
  query_tests/src/pruning.rs
  server_benchmarks/benches/read_filter.rs
  server_benchmarks/benches/read_group.rs
  server_benchmarks/benches/tag_values.rs
Labels: automerge

#3649 test: tests to show predicate simplification on chunks
  query/src/frontend/influxrpc.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3655 feat: add queries system table
  influxdb_iox/src/commands/sql/observer.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3652 fix: use a single metric registry for ingester
  influxdb_iox/src/commands/run/ingester.rs
  ingester/src/server.rs
Labels: automerge

#3651 feat: expose write buffer connection config via CLI
  influxdb_iox/src/clap_blocks/write_buffer.rs
  influxdb_iox/src/commands/run/ingester.rs
  influxdb_iox/src/commands/run/router2.rs
  write_buffer/src/kafka/config.rs
Labels: automerge

#3650 feat: add method to catalog to get its partition info by id
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
Labels: automerge

#3662 feat: add timeouts to write chunk
  db/src/lifecycle/error.rs
  db/src/lifecycle/write.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3663 feat: add tag_values to storage cli
  influxdb_iox/src/commands/storage.rs
  influxdb_iox/src/commands/storage/request.rs
  influxdb_iox/src/commands/storage/response.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3656 feat: gitops adapter
  Cargo.lock
  Cargo.toml
  gitops_adapter/Cargo.toml
  gitops_adapter/build.rs
  gitops_adapter/src/kafka_topic_list/api.rs
  gitops_adapter/src/kafka_topic_list/mock_api.rs
  gitops_adapter/src/kafka_topic_list/mod.rs
  gitops_adapter/src/kafka_topic_list/resources.rs
  gitops_adapter/src/main.rs
  gitops_adapter/test/mock-iox-failure.sh
  gitops_adapter/test/mock-iox-multi-topic.sh
  gitops_adapter/test/mock-iox-single-topic.sh
  workspace-hack/Cargo.toml
Labels: automerge

#3660 refactor: catalog transaction
  Cargo.lock
  influxdb_iox/src/commands/catalog/topic.rs
  influxdb_iox/src/commands/run/ingester.rs
  influxdb_iox/src/commands/run/router2.rs
  ingester/src/data.rs
  ingester/src/handler.rs
  iox_catalog/Cargo.toml
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
  router2/src/dml_handlers/ns_autocreation.rs
  router2/src/dml_handlers/schema_validation.rs
Labels: automerge

#3661 feat: lazy system tables
  db/src/system_tables.rs
  db/src/system_tables/chunks.rs
  db/src/system_tables/columns.rs
  db/src/system_tables/operations.rs
  db/src/system_tables/persistence.rs
  db/src/system_tables/queries.rs
Labels: automerge

#3664 feat: add WriteBufferErrorKind
  db/src/write_buffer.rs
  router/src/write_sink.rs
  write_buffer/src/codec.rs
  write_buffer/src/config.rs
  write_buffer/src/core.rs
  write_buffer/src/file.rs
  write_buffer/src/kafka/config.rs
  write_buffer/src/kafka/mod.rs
  write_buffer/src/mock.rs
Labels: automerge

#3642 feat: special case max timestamp range for table_names and field_columns
  query/src/frontend/influxrpc.rs
  query_tests/src/influxrpc/field_columns.rs
  query_tests/src/influxrpc/table_names.rs
  query_tests/src/influxrpc/tag_keys.rs
Labels: automerge

#3644 perf(router2): sharded namespace cache
  influxdb_iox/src/commands/run/router2.rs
  router2/benches/e2e.rs
  router2/benches/sharder.rs
  router2/src/namespace_cache.rs
  router2/src/namespace_cache/sharded_cache.rs
  router2/src/sharder/jumphash.rs
  router2/src/sharder/mod.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3676 fix: write buffer traces
  trace/src/ctx.rs
  trace/src/span.rs
  write_buffer/src/core.rs
  write_buffer/src/kafka/aggregator.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3681 feat: make stop/stop/predicate global
  influxdb_iox/src/commands/storage.rs
Labels: automerge

#3684 feat: add timed/quiet output for storage CLI
  influxdb_iox/src/commands/storage.rs
  influxdb_iox/src/commands/storage/response.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3682 refactor: Complete move of test scenarios into library.rs
  query_tests/src/influxrpc/read_window_aggregate.rs
  query_tests/src/scenarios/library.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3683 refactor: extract predicate sql tests out of rust
  query_tests/cases/in/pushdown.expected
  query_tests/cases/in/pushdown.sql
  query_tests/src/sql.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3686 fix: increase default `producer_max_batch_size`
  write_buffer/src/kafka/config.rs
Labels: automerge

#3671 feat: create new sequencers in ingester on demand
  influxdb_iox/src/commands/run/ingester.rs
Labels: automerge

#3688 feat: add read_window_aggregate storage sub-command
  influxdb_iox/src/commands/storage.rs
  influxdb_iox/src/commands/storage/request.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3689 refactor: simplify Database retry backoff logic (#3368)
  server/src/database/init.rs
Labels: automerge

#3691 feat: install cargo hakari in ci image
  docker/Dockerfile.ci
Labels: automerge, kodiak: merge.method = 'squash'

#3623 feat: Ingester Flight gRPC API
  Cargo.lock
  Cargo.toml
  generated_types/build.rs
  generated_types/protos/influxdata/iox/ingester/v1/parquet_metadata.proto
  generated_types/protos/influxdata/iox/ingester/v1/query.proto
  generated_types/src/lib.rs
  influxdb_iox/Cargo.toml
  influxdb_iox/src/clap_blocks/catalog_dsn.rs
  influxdb_iox/src/clap_blocks/write_buffer.rs
  influxdb_iox/src/commands/catalog.rs
  influxdb_iox/src/commands/catalog/topic.rs
  influxdb_iox/src/commands/run/ingester.rs
  influxdb_iox/src/commands/run/router2.rs
  influxdb_iox/src/influxdb_ioxd/server_type/ingester.rs
  influxdb_iox/tests/common/server_fixture.rs
  influxdb_iox/tests/end_to_end_cases/ingester.rs
  influxdb_iox/tests/end_to_end_cases/mod.rs
  influxdb_iox_client/src/client/health.rs
  ingester/Cargo.toml
  ingester/src/data.rs
  ingester/src/handler.rs
  ingester/src/server/grpc.rs
  parquet_file/src/metadata.rs
  querier/Cargo.toml
  querier/src/flight.rs
  querier/src/lib.rs
Labels: automerge

#3633 chore: update datafusion, stop repartitioning so aggressively
  Cargo.lock
  datafusion/Cargo.toml
  db/src/system_tables.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/mod.rs
  predicate/src/rewrite.rs
  predicate/src/rpc_predicate.rs
  query/src/exec/context.rs
  query/src/exec/non_null_checker.rs
  query/src/exec/query_tracing.rs
  query/src/exec/schema_pivot.rs
  query/src/exec/split.rs
  query/src/frontend/influxrpc.rs
  query/src/func/selectors.rs
  query/src/provider/deduplicate.rs
  query/src/provider/physical.rs
  query_tests/cases/in/duplicates.expected
  query_tests/cases/in/no_stats_plans.expected
  query_tests/cases/in/pushdown.expected
  query_tests/cases/in/stats_plans.expected
Labels: automerge, kodiak: merge.method = 'squash'

#3694 chore: improve semantic check
  .github/workflows/semantic_check.sh
Labels: automerge

#3692 feat: gitops adapter ci build
  .circleci/config.yml
  Cargo.lock
  Cargo.toml
  iox_gitops_adapter/Cargo.toml
  iox_gitops_adapter/build.rs
  iox_gitops_adapter/src/kafka_topic_list/api.rs
  iox_gitops_adapter/src/kafka_topic_list/mock_api.rs
  iox_gitops_adapter/src/kafka_topic_list/mod.rs
  iox_gitops_adapter/src/kafka_topic_list/resources.rs
  iox_gitops_adapter/src/main.rs
  iox_gitops_adapter/test/mock-iox-failure.sh
  iox_gitops_adapter/test/mock-iox-multi-topic.sh
  iox_gitops_adapter/test/mock-iox-single-topic.sh
Labels: automerge, kodiak: merge.method = 'squash'

#3711 feat: restartable `Database` (#3368)
  db/src/utils.rs
  generated_types/protos/influxdata/iox/management/v1/service.proto
  generated_types/src/database_state.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/mod.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/management.rs
  influxdb_iox/tests/end_to_end_cases/database_migration.rs
  server/src/database.rs
  server/src/database/init.rs
  server/src/database/state.rs
  server/src/lib.rs
Labels: automerge

#3717 feat: preempt init shutdown (#3368)
  server/src/database.rs
  server/src/database/init.rs
Labels: automerge

#3722 feat: server and database state gauge metrics
  server/src/lib.rs
Labels: automerge

#3724 fix: hard-code prod kafka config
  write_buffer/src/kafka/config.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3725 feat: static router configuration (#2436)
  generated_types/protos/influxdata/iox/router/v1/router.proto
  generated_types/src/google.rs
  influxdb_iox/src/commands/run/router.rs
  influxdb_iox/src/influxdb_ioxd/server_type/router/http.rs
  influxdb_iox/src/influxdb_ioxd/server_type/router/mod.rs
  influxdb_iox/src/influxdb_ioxd/server_type/router/rpc/mod.rs
  influxdb_iox/src/influxdb_ioxd/server_type/router/rpc/router.rs
  influxdb_iox/tests/end_to_end_cases/router_cli.rs
Labels: automerge

#3727 chore: Update datafusion
  Cargo.lock
  datafusion/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#3730 refactor: traitify database configuration (#2436)
  influxdb_iox/src/influxdb_ioxd/server_type/database/http.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/setup.rs
  influxdb_iox/tests/end_to_end_cases/management_api.rs
  server/src/application.rs
  server/src/config.rs
  server/src/config/object_store.rs
  server/src/database.rs
  server/src/database/init.rs
  server/src/lib.rs
  server/src/rules.rs
  server/tests/write_buffer_lifecycle.rs
Labels: automerge

#3736 chore: update gitops adapter k8s deps (via dependabot)
  Cargo.lock
  iox_gitops_adapter/Cargo.toml
  iox_gitops_adapter/src/main.rs
  workspace-hack/Cargo.toml
Labels: automerge

#3707 feat: Turn protobuf predicates into predicate::Predicate
  Cargo.lock
  generated_types/protos/influxdata/iox/ingester/v1/query.proto
  ingester/src/data.rs
  predicate/Cargo.toml
  predicate/src/ingester.rs
  predicate/src/lib.rs
Labels: automerge

#3732 feat: static database configuration (#2436)
  generated_types/protos/influxdata/iox/management/v1/server_config.proto
  generated_types/src/google.rs
  influxdb_iox/src/commands/run/database.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/config.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/http.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/mod.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/management.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/mod.rs
  influxdb_iox/src/influxdb_ioxd/server_type/database/setup.rs
  influxdb_iox/tests/end_to_end_cases/management_cli.rs
  server/src/application.rs
  server/src/config.rs
  server/src/config/object_store.rs
  server/src/config/owner.rs
  server/src/database.rs
  server/src/database/init.rs
Labels: automerge

#3735 feat: allow catalog access w/o a transaction
  influxdb_iox/src/commands/catalog/topic.rs
  ingester/src/data.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
  router2/src/dml_handlers/ns_autocreation.rs
  router2/src/dml_handlers/schema_validation.rs
Labels: automerge

#3745 fix: defined behaviour when seeking to an unknown sequence number
  Cargo.lock
  db/src/write_buffer.rs
  write_buffer/Cargo.toml
  write_buffer/src/core.rs
  write_buffer/src/file.rs
  write_buffer/src/kafka/aggregator.rs
  write_buffer/src/kafka/mod.rs
  write_buffer/src/mock.rs
Labels: automerge

#3733 chore: Update datafusion, update `arrow`/`parquet`/`arrow-flight` to 9.0
  Cargo.lock
  arrow_util/Cargo.toml
  datafusion/Cargo.toml
  db/Cargo.toml
  influxdb_iox/Cargo.toml
  influxdb_iox_client/Cargo.toml
  ingester/Cargo.toml
  ingester/src/persist.rs
  mutable_batch/Cargo.toml
  mutable_buffer/Cargo.toml
  packers/Cargo.toml
  parquet_catalog/Cargo.toml
  parquet_catalog/src/dump.rs
  parquet_file/Cargo.toml
  parquet_file/src/metadata.rs
  parquet_file/src/storage.rs
  parquet_file/src/test_utils.rs
  parquet_file/src/test_utils/generator.rs
  predicate/Cargo.toml
  querier/Cargo.toml
  query/Cargo.toml
  query_tests/Cargo.toml
  read_buffer/Cargo.toml
  schema/Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#3748 fix: start Kafka write buffer stream at "earliest" offset, not at "0"
  db/src/replay.rs
  db/src/write_buffer.rs
  influxdb_iox/tests/end_to_end_cases/delete_api.rs
  influxdb_iox/tests/end_to_end_cases/write_pb.rs
  ingester/src/handler.rs
  write_buffer/src/core.rs
  write_buffer/src/file.rs
  write_buffer/src/kafka/mod.rs
  write_buffer/src/mock.rs
Labels: automerge

#3742 feat: build Query Plan that queries QueryableBatch with filters
  ingester/src/lib.rs
  ingester/src/querier_handler.rs
  ingester/src/query.rs
  query/src/frontend/reorg.rs
Labels: automerge

#3749 chore: The k8s-iox promotion is no longer used and can be removed
  .circleci/get-deploy-tags.sh
Labels: automerge, kodiak: merge.method = 'squash'

#3751 refactor: influxRPC operation logging
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/storage/service.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3685 feat: wire up persistence in ingester
  influxdb_iox/src/commands/run/ingester.rs
  ingester/src/data.rs
  ingester/src/handler.rs
  ingester/src/lifecycle.rs
  ingester/src/query.rs
  ingester/src/test_util.rs
Labels: automerge

#3756 feat: API and steps to prepare data to send back to the Querier per its request
  ingester/src/data.rs
  ingester/src/querier_handler.rs
Labels: automerge

#3760 docs: Improve iox_catalog testing docs
  iox_catalog/README.md
Labels: automerge

#3746 feat(router2): MutableBatch partitioning
  Cargo.lock
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/run/router2.rs
  influxdb_iox/src/influxdb_ioxd/server_type/router2.rs
  router2/Cargo.toml
  router2/benches/e2e.rs
  router2/src/dml_handlers/mock.rs
  router2/src/dml_handlers/mod.rs
  router2/src/dml_handlers/nop.rs
  router2/src/dml_handlers/ns_autocreation.rs
  router2/src/dml_handlers/partitioner.rs
  router2/src/dml_handlers/schema_validation.rs
  router2/src/dml_handlers/sharded_write_buffer.rs
  router2/src/dml_handlers/trait.rs
  router2/src/lib.rs
  router2/src/server.rs
  router2/src/server/http.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3768 fix: Use a string literal with unreachable
  read_buffer/src/column/encoding/string/dictionary.rs
Labels: automerge

#3766 feat: Add namespace and sequencer id fields to IngesterQueryRequest protobuf
  generated_types/protos/influxdata/iox/ingester/v1/query.proto
  ingester/src/data.rs
Labels: automerge

#3771 feat: generate a trace ID when using gRPC client
  influxdb_iox/src/main.rs
  trace_exporters/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3775 fix: upgrade rskafka for bugfixes and race-free start offsets
  Cargo.lock
  write_buffer/Cargo.toml
  write_buffer/src/kafka/mod.rs
Labels: automerge

#3764 feat: router2 metrics
  influxdb_iox/src/commands/run/router2.rs
  router2/src/dml_handlers/instrumentation.rs
  router2/src/dml_handlers/mod.rs
  router2/src/dml_handlers/schema_validation.rs
  router2/src/namespace_cache.rs
  router2/src/namespace_cache/metrics.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3767 fix: Make errors in rewriting return `Error` rather than a `panic`
  influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/storage/expr.rs
  predicate/src/rpc_predicate.rs
  query/src/frontend/influxrpc.rs
  query_tests/src/influxrpc/read_filter.rs
  query_tests/src/influxrpc/util.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3776 test: isolated catalog tests
  Cargo.lock
  iox_catalog/Cargo.toml
  iox_catalog/migrations/20210217134322_create_schema.sql
  iox_catalog/migrations/20211229171744_initial_schema.sql
  iox_catalog/src/postgres.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3769 fix: supervise and shutdown ingester background tasks
  Cargo.lock
  influxdb_iox/src/commands/run/ingester.rs
  influxdb_iox/src/influxdb_ioxd/server_type/ingester.rs
  ingester/Cargo.toml
  ingester/src/handler.rs
  ingester/src/lib.rs
  ingester/src/lifecycle.rs
  ingester/src/poison.rs
  ingester/src/server.rs
Labels: automerge

#3781 feat: template static router config
  generated_types/protos/influxdata/iox/router/v1/router.proto
  influxdb_iox/src/commands/run/router.rs
  influxdb_iox/tests/end_to_end_cases/router_cli.rs
Labels: automerge

#3779 fix: catalog spurious writes
  iox_catalog/src/postgres.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3787 feat: catalog now supports dsn-file://
  Cargo.lock
  iox_catalog/Cargo.toml
  iox_catalog/src/postgres.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3772 feat: Send IngesterQueryResponse data back as response of doGet Flight request
  generated_types/protos/influxdata/iox/ingester/v1/query.proto
  ingester/Cargo.toml
  ingester/src/data.rs
  ingester/src/handler.rs
  ingester/src/querier_handler.rs
  ingester/src/server/grpc.rs
Labels: automerge

#3791 feat: trigger persistence if over soft limit and no evictable chunks
  influxdb_iox/tests/end_to_end_cases/persistence.rs
  lifecycle/src/policy.rs
Labels: automerge

#3789 fix: "catalog setup" migrations in non-public schema
  .circleci/config.yml
  iox_catalog/src/postgres.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3803 feat: adding compactor CLI command and crate
  Cargo.lock
  Cargo.toml
  compactor/Cargo.toml
  compactor/src/handler.rs
  compactor/src/lib.rs
  compactor/src/server.rs
  compactor/src/server/grpc.rs
  compactor/src/server/http.rs
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/run/compactor.rs
  influxdb_iox/src/commands/run/mod.rs
  influxdb_iox/src/influxdb_ioxd/server_type/compactor.rs
  influxdb_iox/src/influxdb_ioxd/server_type/mod.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3788 refactor(router2): non-intrusive handler chain
  influxdb_iox/src/commands/run/router2.rs
  router2/benches/e2e.rs
  router2/src/dml_handlers/chain.rs
  router2/src/dml_handlers/fan_out.rs
  router2/src/dml_handlers/instrumentation.rs
  router2/src/dml_handlers/mock.rs
  router2/src/dml_handlers/mod.rs
  router2/src/dml_handlers/nop.rs
  router2/src/dml_handlers/ns_autocreation.rs
  router2/src/dml_handlers/partitioner.rs
  router2/src/dml_handlers/schema_validation.rs
  router2/src/dml_handlers/sharded_write_buffer.rs
  router2/src/dml_handlers/trait.rs
  router2/src/server/http.rs
  router2/tests/http.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3808 feat: remove remaining table-granularity metrics
  db/src/access.rs
  db/src/catalog/metrics.rs
  db/src/lib.rs
  query_tests/src/pruning.rs
Labels: automerge

#3811 refactor: generic+reusable task registry
  job_registry/src/lib.rs
  lifecycle/src/policy.rs
  tracker/src/task.rs
  tracker/src/task/history.rs
  tracker/src/task/metrics.rs
  tracker/src/task/registry.rs
Labels: automerge

#3806 feat: sequencer metrics during replay
  db/src/lib.rs
  db/src/replay.rs
  db/src/write_buffer.rs
Labels: automerge

#3807 feat: routing service protection
  iox_catalog/migrations/20220221145409_routing_limits.sql
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
  router2/src/dml_handlers/ns_autocreation.rs
Labels: automerge

#3770 feat: apply tombstones to the batches of the ingest life-cycle
  ingester/src/data.rs
  ingester/src/querier_handler.rs
  ingester/src/query.rs
  iox_catalog/src/lib.rs
Labels: automerge

#3785 feat: Add min_sequence_number tracking for sequencers in ingester
  ingester/src/data.rs
  ingester/src/handler.rs
  ingester/src/lifecycle.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
Labels: automerge

#3819 refactor: move `DedicatedExecutor` from `query` to `executor`
  Cargo.lock
  Cargo.toml
  executor/Cargo.toml
  executor/src/lib.rs
  query/Cargo.toml
  query/src/exec.rs
  query/src/exec/context.rs
Labels: automerge

#3824 feat: allow overriding CLI request timeout
  influxdb_iox/src/main.rs
Labels: automerge

#3831 feat: add sort ordinal to chunk_columns system table (#2035)
  db/src/catalog.rs
  db/src/catalog/chunk.rs
  db/src/system_tables/columns.rs
Labels: automerge

#3834 test: catalog `maybe_skip_integration!` and `should_panic`
  iox_catalog/src/postgres.rs
Labels: automerge

#3836 feat: track ingester jobs
  Cargo.lock
  influxdb_iox/src/commands/run/ingester.rs
  ingester/Cargo.toml
  ingester/src/data.rs
  ingester/src/handler.rs
  ingester/src/job.rs
  ingester/src/lib.rs
  ingester/src/lifecycle.rs
  tracker/src/task.rs
Labels: automerge

#3839 fix: Remove min_time and max_time from IngesterQueryRequest
  generated_types/protos/influxdata/iox/ingester/v1/query.proto
  ingester/src/data.rs
Labels: automerge

#3837 feat: catalog instrumentation
  Cargo.lock
  influxdb_iox/src/clap_blocks/catalog_dsn.rs
  influxdb_iox/src/commands/catalog.rs
  influxdb_iox/src/commands/catalog/topic.rs
  influxdb_iox/src/commands/run/compactor.rs
  influxdb_iox/src/commands/run/ingester.rs
  influxdb_iox/src/commands/run/router2.rs
  iox_catalog/Cargo.toml
  iox_catalog/src/lib.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3830 feat: emit trace spans for router stages
  router2/src/dml_handlers/instrumentation.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3838 chore: update database rebuild instructions
  docs/server_startup.md
Labels: automerge

#3841 feat: backoff retries in ingester
  Cargo.lock
  Cargo.toml
  backoff/Cargo.toml
  backoff/src/lib.rs
  ingester/Cargo.toml
  ingester/src/data.rs
  ingester/src/handler.rs
Labels: automerge

#3846 refactor: early schema validation
  influxdb_iox/src/commands/run/router2.rs
  router2/benches/e2e.rs
  router2/src/dml_handlers/schema_validation.rs
  router2/tests/http.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3852 feat: extend catalog so we can recover `ParquetChunk`s from it
  db/src/lib.rs
  ingester/src/data.rs
  ingester/src/persist.rs
  iox_catalog/migrations/20220224080910_add_file_size_bytes.sql
  iox_catalog/migrations/20220224082147_add_parquet_metadata.sql
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  parquet_catalog/src/rebuild.rs
  parquet_file/src/metadata.rs
  parquet_file/src/storage.rs
  parquet_file/src/test_utils.rs
Labels: automerge

#3847 feat: Add row count to the parquet_file record in the catalog
  generated_types/protos/influxdata/iox/ingester/v1/parquet_metadata.proto
  ingester/src/compact.rs
  ingester/src/data.rs
  ingester/src/persist.rs
  ingester/src/test_util.rs
  iox_catalog/migrations/20220223192306_add_row_count_to_parquet_file.sql
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  parquet_file/src/metadata.rs
Labels: automerge

#3843 feat: skeleton of querier CLI
  Cargo.lock
  influxdb_iox/src/commands/run/mod.rs
  influxdb_iox/src/commands/run/querier.rs
  influxdb_iox/src/influxdb_ioxd/server_type/mod.rs
  influxdb_iox/src/influxdb_ioxd/server_type/querier.rs
  querier/Cargo.toml
  querier/src/handler.rs
  querier/src/lib.rs
  querier/src/server.rs
Labels: automerge

#3853 feat: wire up `ParquetFilePath` for NG
  Cargo.lock
  db/src/lib.rs
  ingester/src/persist.rs
  iox_object_store/Cargo.toml
  iox_object_store/src/lib.rs
  iox_object_store/src/paths/parquet_file.rs
  parquet_catalog/src/rebuild.rs
  parquet_file/src/storage.rs
Labels: automerge

#3848 feat: add method to get table persistence information from catalog
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
Labels: automerge

#3855 fix: compactor server stays up; removed unused delegates
  compactor/src/handler.rs
  compactor/src/server.rs
  compactor/src/server/grpc.rs
  compactor/src/server/http.rs
  influxdb_iox/src/commands/run/compactor.rs
  influxdb_iox/src/influxdb_ioxd/server_type/compactor.rs
Labels: automerge, kodiak: merge.method = 'squash'

#3854 feat: namespace cache table/column count metrics
  influxdb_iox/src/commands/run/router2.rs
  metric/src/gauge.rs
  router2/src/namespace_cache/metrics.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3858 refactor: use ChunkMetadata in catalog interface (#3845)
  db/src/catalog/chunk.rs
  db/src/catalog/partition.rs
  db/src/chunk.rs
  db/src/lifecycle/compact.rs
  db/src/lifecycle/compact_object_store.rs
  db/src/lifecycle/persist.rs
  db/src/load.rs
Labels: automerge

#3856 fix: Remove greater_than_sequence_number from IngesterQueryRequest
  generated_types/protos/influxdata/iox/ingester/v1/query.proto
  ingester/src/data.rs
Labels: automerge

#3860 refactor: parallel column resolution
  ingester/src/data.rs
  ingester/src/handler.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/postgres.rs
  router2/src/dml_handlers/schema_validation.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3849 feat: have ingester ignore already persisted data
  ingester/src/data.rs
Labels: automerge

#3857 feat: create `ParquetChunk` in querier
  Cargo.lock
  db/src/lifecycle/compact_object_store.rs
  db/src/load.rs
  parquet_catalog/src/dump.rs
  parquet_catalog/src/rebuild.rs
  parquet_catalog/src/test_helpers.rs
  parquet_file/src/metadata.rs
  parquet_file/src/storage.rs
  querier/Cargo.toml
  querier/src/chunk.rs
  querier/src/lib.rs
Labels: automerge

#3844 fix: chunk overlap missing columns
  query/src/provider.rs
  query/src/provider/overlap.rs
Labels: automerge

#3863 refactor: configurable max catalog connections
  influxdb_iox/src/clap_blocks/catalog_dsn.rs
  iox_catalog/src/postgres.rs
Labels: automerge, kodiak: merge.method = 'merge'

#3861 fix: while executing deduplication, do not return empty record batches
  ingester/src/compact.rs
  ingester/src/test_util.rs
  query/src/provider/deduplicate.rs
Labels: automerge

#3864 feat: correctly sort data and store in catalog metadata
  db/src/catalog/chunk.rs
  db/src/chunk.rs
  db/src/lib.rs
  db/src/lifecycle/compact.rs
  db/src/lifecycle/compact_object_store.rs
  db/src/lifecycle/persist.rs
  db/src/lifecycle/write.rs
  db/src/load.rs
  db/src/system_tables/columns.rs
  generated_types/protos/influxdata/iox/preserved_catalog/v1/parquet_metadata.proto
  influxdb_iox/tests/end_to_end_cases/persistence.rs
  influxdb_iox/tests/end_to_end_cases/system_tables.rs
  ingester/src/query.rs
  parquet_catalog/src/dump.rs
  parquet_catalog/src/rebuild.rs
  parquet_file/src/metadata.rs
  parquet_file/src/storage.rs
  parquet_file/src/test_utils/generator.rs
  query/src/frontend.rs
  query/src/frontend/reorg.rs
  query/src/lib.rs
  query/src/provider.rs
  query/src/test.rs
  query/src/util.rs
  query_tests/src/table_schema.rs
  schema/src/builder.rs
  schema/src/lib.rs
  schema/src/merge.rs
  schema/src/sort.rs
Labels: automerge

#3872 fix: Update hakari files for cargo-hakari 0.9.12
  workspace-hack/Cargo.toml
Labels: automerge

#3866 fix: do not ignore failed persist tasks
  ingester/src/lifecycle.rs
Labels: automerge

#3873 chore: `cargo update` + less rustsec exceptions
  .cargo/audit.toml
  Cargo.lock
Labels: automerge

#3865 feat: sync namespaces in querier
  Cargo.lock
  influxdb_iox/src/commands/run/querier.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  querier/Cargo.toml
  querier/src/database.rs
  querier/src/handler.rs
  querier/src/lib.rs
  querier/src/namespace.rs
Labels: automerge

#3875 chore: upgrade Rust to 1.59
  data_types/src/delete_predicate.rs
  db/src/lib.rs
  db/src/replay.rs
  db/src/system_tables/columns.rs
  dml/src/lib.rs
  influxdb_iox/src/commands/sql/observer.rs
  influxdb_iox/tests/common/server_fixture.rs
  influxdb_iox/tests/end_to_end_cases/operations_cli.rs
  influxdb_line_protocol/src/lib.rs
  influxdb_storage_client/src/lib.rs
  influxrpc_parser/src/predicate.rs
  logfmt/tests/logging.rs
  parquet_catalog/src/test_helpers.rs
  parquet_file/src/chunk.rs
  predicate/src/delete_predicate.rs
  query/src/exec/schema_pivot.rs
  query/src/exec/seriesset/series.rs
  query/src/provider.rs
  query_tests/src/runner.rs
  read_buffer/benches/plain.rs
  read_buffer/benches/sum_fixed.rs
  read_buffer/src/column/encoding/scalar/fixed.rs
  read_buffer/src/column/encoding/scalar/fixed_null.rs
  read_buffer/src/column/integer.rs
  read_buffer/src/table.rs
  rust-toolchain.toml
  tracker/src/lock.rs
  write_buffer/src/core.rs
  write_buffer/src/file.rs
Labels: automerge

#3862 feat: create CatalogChunk in querier
  Cargo.lock
  db/src/catalog/chunk.rs
  db/src/lib.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  querier/Cargo.toml
  querier/src/chunk.rs
  querier/src/namespace.rs
Labels: automerge

#3877 feat: harden write buffer aggregator (#3805)
  write_buffer/src/kafka/aggregator.rs
Labels: automerge
