Repository influxdata/influxdb_iox, pull requests merged in 2023-04, with the labels that each got.

#7416 test: Use a setup that never persists for a test that expects ingester data
  influxdb_iox/tests/query_tests2/cases.rs
  influxdb_iox/tests/query_tests2/framework.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7413 refactor: tidy NamespaceName from org & bucket
  Cargo.lock
  data_types/Cargo.toml
  data_types/src/lib.rs
  data_types/src/namespace_name.rs
  import/src/aggregate_tsm_schema/update_catalog.rs
  router/src/server/http.rs
  service_grpc_influxrpc/src/service.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7431 fix: Incorrect results when planning aggregate expressions
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql.expected
  iox_query_influxql/src/plan/planner.rs
Labels: automerge, query/language/influxql

#7440 chore: Update datafusion again
  Cargo.lock
  Cargo.toml
  datafusion_util/src/lib.rs
  datafusion_util/src/sort_exprs.rs
  iox_query/src/exec/gapfill/mod.rs
  iox_query/src/physical_optimizer/sort/parquet_sortness.rs
  iox_query/src/provider/deduplicate.rs
  workspace-hack/Cargo.toml
Labels: automerge

#7443 refactor: make null-as-missing default behavior for LOCF
  influxdb_iox/tests/query_tests2/cases/in/gapfill.sql
  influxdb_iox/tests/query_tests2/cases/in/gapfill.sql.expected
  influxdb_iox/tests/query_tests2/setups.rs
  iox_query/src/exec/gapfill/algo.rs
  iox_query/src/exec/gapfill/exec_tests.rs
  iox_query/src/exec/gapfill/mod.rs
  iox_query/src/logical_optimizer/handle_gapfill.rs
  iox_query_influxql/src/plan/planner.rs
Labels: automerge

#7444 test: Add additional tests for reorg plans
  iox_query/src/frontend.rs
  iox_query/src/frontend/reorg.rs
Labels: automerge, kodiak: merge.method = 'squash'

#7415 feat(namespace): Update support for namespace service protection limits
  generated_types/protos/influxdata/iox/namespace/v1/service.proto
  influxdb_iox/src/commands/namespace/create.rs
  influxdb_iox/src/commands/namespace/delete.rs
  influxdb_iox/src/commands/namespace/mod.rs
  influxdb_iox/src/commands/namespace/retention.rs
  influxdb_iox/src/commands/namespace/update_limit.rs
  influxdb_iox/tests/end_to_end_cases/cli.rs
  influxdb_iox_client/src/client/namespace.rs
  ioxd_querier/src/rpc/namespace.rs
  router/tests/grpc.rs
  service_grpc_namespace/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7442 chore: Update datafusion again
  Cargo.lock
  Cargo.toml
  iox_query/src/exec/split.rs
  workspace-hack/Cargo.toml
Labels: automerge

#7450 feat: expand 'vertical splitting' to improve compaction efficiency
  compactor2/src/components/divide_initial/multiple_branches.rs
  compactor2/src/components/split_or_compact/metrics.rs
  compactor2/src/components/split_or_compact/split_compact.rs
  compactor2/src/components/split_or_compact/start_level_files_to_split.rs
  compactor2/src/file_classification.rs
  compactor2/tests/layouts/backfill.rs
  compactor2/tests/layouts/knobs.rs
  compactor2/tests/layouts/large_files.rs
Labels: automerge

#7447 feat: Teach InfluxQL how to plan `LIMIT` and `OFFSET` with `GROUP BY`
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql.expected
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/planner/select.rs
Labels: automerge, query/language/influxql

#7448 test: `ChunkTableProvider::scan` + fix "not dedup"
  iox_query/src/provider.rs
  iox_query/src/test.rs
Labels: automerge

#7469 fix: tracing span hierarchy in querier
  querier/src/parquet/creation.rs
Labels: automerge

#7472 fix: don't panic for unsupported features
  service_grpc_influxrpc/src/expr.rs
  service_grpc_influxrpc/src/service.rs
Labels: automerge

#7449 refactor: remove old query planning code
  Cargo.lock
  compactor/src/parquet_file_combining.rs
  compactor2/src/components/df_planner/planner_v1.rs
  ingester/src/compact.rs
  ingester2/src/persist/compact.rs
  iox_query/Cargo.toml
  iox_query/src/frontend.rs
  iox_query/src/frontend/common.rs
  iox_query/src/frontend/reorg.rs
  iox_query/src/lib.rs
  iox_query/src/physical_optimizer/chunk_extraction.rs
  iox_query/src/physical_optimizer/combine_chunks.rs
  iox_query/src/physical_optimizer/dedup/dedup_null_columns.rs
  iox_query/src/physical_optimizer/dedup/dedup_sort_order.rs
  iox_query/src/physical_optimizer/dedup/partition_split.rs
  iox_query/src/physical_optimizer/dedup/remove_dedup.rs
  iox_query/src/physical_optimizer/dedup/test_util.rs
  iox_query/src/physical_optimizer/dedup/time_split.rs
  iox_query/src/physical_optimizer/mod.rs
  iox_query/src/provider.rs
  iox_query/src/provider/physical.rs
  iox_query_influxrpc/src/lib.rs
  querier/src/namespace/mod.rs
  querier/src/table/mod.rs
  querier/src/table/query_access/mod.rs
  querier/src/table/test_util.rs
Labels: automerge

#7473 fix: Remove old compactor and ioxd_compactor
  Cargo.lock
  Cargo.toml
  clap_blocks/src/compactor.rs
  clap_blocks/src/lib.rs
  compactor/Cargo.toml
  compactor/README.md
  compactor/src/cold.rs
  compactor/src/compact.rs
  compactor/src/garbage_collector.rs
  compactor/src/handler.rs
  compactor/src/hot.rs
  compactor/src/lib.rs
  compactor/src/parquet_file.rs
  compactor/src/parquet_file_combining.rs
  compactor/src/parquet_file_filtering.rs
  compactor/src/parquet_file_lookup.rs
  compactor/src/query.rs
  compactor/src/server.rs
  compactor/src/server/grpc.rs
  compactor/src/utils.rs
  compactor/src/warm.rs
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/compactor.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/src/commands/run/compactor.rs
  influxdb_iox/src/commands/run/compactor2.rs
  influxdb_iox/src/commands/run/mod.rs
  influxdb_iox/src/main.rs
  influxdb_iox/tests/end_to_end_cases/mode_switching.rs
  ioxd_compactor/Cargo.toml
  ioxd_compactor/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7464 refactor: `limit` function supports multiple measurements and tag sets
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql.expected
  influxdb_iox/tests/query_tests2/setups.rs
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/planner/select.rs
Labels: automerge, query/language/influxql

#7466 feat: Add `FILL(linear)` support
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql.expected
  iox_query_influxql/src/plan/planner.rs
Labels: automerge, query/language/influxql

#7488 chore: Update crossbeam-channel to 0.5.8
  Cargo.lock
Labels: automerge

#7492 feat: scale compactor concurrency based on table column count
  compactor2/src/driver.rs
  tracker/src/async_semaphore.rs
Labels: automerge

#7471 chore: enable frame-pointer
  .cargo/config
Labels: automerge

#7491 chore: Remove unused dependencies, found by cargo-machete
  Cargo.lock
  compactor2/Cargo.toml
  import/Cargo.toml
  ioxd_common/Cargo.toml
  ioxd_querier/Cargo.toml
Labels: automerge

#7441 chore: end to end tests for authorization
  Cargo.lock
  influxdb_iox/Cargo.toml
  influxdb_iox/tests/end_to_end_cases/all_in_one.rs
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
  influxdb_iox/tests/end_to_end_cases/influxql.rs
  influxdb_iox/tests/end_to_end_cases/ingester.rs
  influxdb_iox/tests/end_to_end_cases/namespace.rs
  influxdb_iox/tests/end_to_end_cases/querier.rs
  influxdb_iox/tests/end_to_end_cases/router.rs
  influxdb_iox_client/src/client/flight/mod.rs
  test_helpers_end_to_end/src/authz.rs
  test_helpers_end_to_end/src/client.rs
  test_helpers_end_to_end/src/config.rs
  test_helpers_end_to_end/src/lib.rs
  test_helpers_end_to_end/src/mini_cluster.rs
  test_helpers_end_to_end/src/snapshot_comparison.rs
  test_helpers_end_to_end/src/steps.rs
Labels: automerge

#7476 fix: Improve span names for query access
  iox_query/src/exec/context.rs
  querier/src/namespace/query_access.rs
  querier/src/table/query_access/mod.rs
Labels: automerge

#7475 chore(querier): Remove more dead planning code
  iox_query/src/exec.rs
Labels: automerge

#7502 chore(authz): Change "namespace" to "database"
  authz/src/permission.rs
  generated_types/protos/influxdata/iox/authz/v1/authz.proto
  router/src/server/http.rs
  service_grpc_flight/src/lib.rs
  test_helpers_end_to_end/src/authz.rs
Labels: automerge, incompatible protobuf

#7429 feat(router): CST mode
  clap_blocks/src/router.rs
  clap_blocks/src/router2.rs
  data_types/src/namespace_name.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ioxd_router/src/lib.rs
  router/benches/e2e.rs
  router/src/server/http.rs
  router/src/server/http/write/mod.rs
  router/src/server/http/write/multi_tenant.rs
  router/src/server/http/write/params.rs
  router/src/server/http/write/single_tenant.rs
  router/src/server/http/write/v1.rs
  router/src/server/http/write/v2.rs
  router/tests/common/mod.rs
Labels: kodiak: merge.method = 'merge'

#7505 chore: `cargo update`
  Cargo.lock
Labels: automerge

#7501 feat: improve querier->ingester tracing
  querier/src/ingester/circuit_breaker.rs
  querier/src/ingester/flight_client.rs
  querier/src/ingester/invalidate_on_error.rs
  querier/src/ingester/mod.rs
Labels: automerge

#7496 feat(flightsql): Support `GetPrimaryKeys` metadata endpoint with an empty RecordBatch
  flightsql/src/cmd.rs
  flightsql/src/planner.rs
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
  influxdb_iox/tests/jdbc_client/Main.java
  influxdb_iox_client/src/client/flightsql.rs
  service_grpc_flight/src/lib.rs
Labels: automerge

#7509 chore: make compactor concurrency scale non-linearly
  compactor2/src/driver.rs
Labels: automerge

#7510 chore: increasing concurrency a little more
  compactor2/src/driver.rs
Labels: automerge

#7500 feat: Validate the semantics of the projection clause of a SELECT
  influxdb_influxql_parser/src/select.rs
  iox_query_influxql/src/plan/expr_type_evaluator.rs
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/rewriter.rs
Labels: automerge, query/language/influxql

#7405 feat: `SHOW FIELD KEYS` InfluxQL plan+exec
  influxdb_iox/tests/query_tests2/cases.rs
  influxdb_iox/tests/query_tests2/cases/in/influxql_metadata.influxql
  influxdb_iox/tests/query_tests2/cases/in/influxql_metadata.influxql.expected
  influxdb_iox/tests/query_tests2/setups.rs
  iox_query_influxql/src/frontend/planner.rs
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/planner/select.rs
Labels: automerge

#7514 test(bench): ingester2 write benchmarks
  Cargo.lock
  Cargo.toml
  ingester2/Cargo.toml
  ingester2/benches/write.rs
  ingester2/tests/write.rs
  ingester2_test_ctx/Cargo.toml
  ingester2_test_ctx/README.md
  ingester2_test_ctx/src/lib.rs
Labels: kodiak: merge.method = 'merge'

#7503 feat(router): Use a read-through decorator for `NamespaceCache` usage
  ioxd_router/src/lib.rs
  router/benches/e2e.rs
  router/benches/schema_validator.rs
  router/src/dml_handlers/retention_validation.rs
  router/src/dml_handlers/schema_validation.rs
  router/src/namespace_cache.rs
  router/src/namespace_cache/memory.rs
  router/src/namespace_cache/metrics.rs
  router/src/namespace_cache/read_through_cache.rs
  router/src/namespace_cache/sharded_cache.rs
  router/src/namespace_resolver.rs
  router/src/namespace_resolver/ns_autocreation.rs
  router/tests/common/mod.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7518 fix: Remove old router
  Cargo.lock
  clap_blocks/src/lib.rs
  clap_blocks/src/router.rs
  influxdb_iox/src/commands/run/mod.rs
  influxdb_iox/src/commands/run/router.rs
  influxdb_iox/tests/end_to_end_cases/mode_switching.rs
  ioxd_router/Cargo.toml
  ioxd_router/src/lib.rs
  router/Cargo.toml
  router/benches/e2e.rs
  router/src/dml_handlers/mod.rs
  router/src/dml_handlers/sharded_write_buffer.rs
  router/src/dml_handlers/trait.rs
  router/src/lib.rs
  router/src/server.rs
  router/src/server/grpc.rs
  router/src/server/grpc/sharder.rs
  router/src/server/http.rs
  router/src/shard.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7521 fix: Remove the write buffer crate
  Cargo.lock
  Cargo.toml
  clap_blocks/Cargo.toml
  clap_blocks/src/lib.rs
  clap_blocks/src/write_buffer.rs
  write_buffer/Cargo.toml
  write_buffer/src/codec.rs
  write_buffer/src/config.rs
  write_buffer/src/core.rs
  write_buffer/src/file.rs
  write_buffer/src/kafka/config.rs
  write_buffer/src/kafka/instrumentation.rs
  write_buffer/src/kafka/mod.rs
  write_buffer/src/kafka/record_aggregator.rs
  write_buffer/src/lib.rs
  write_buffer/src/mock.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7417 feat: Add the ability to specify a max threshold duration on CatalogToCompactPartitionsSource
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/partitions_source/catalog_to_compact.rs
  iox_catalog/src/mem.rs
  iox_tests/src/builders.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7523 chore: add logging around compaction job semaphore
  compactor2/src/driver.rs
  tracker/src/async_semaphore.rs
Labels: automerge

#7520 docs: Improve documentation on query API
  service_grpc_flight/src/request.rs
Labels: automerge

#7515 refactor: Use workspace dependencies for `tonic`, `tonic-build`, etc
  Cargo.toml
  authz/Cargo.toml
  client_util/Cargo.toml
  flightsql/Cargo.toml
  generated_types/Cargo.toml
  grpc-binary-logger-proto/Cargo.toml
  grpc-binary-logger-test-proto/Cargo.toml
  grpc-binary-logger/Cargo.toml
  import/Cargo.toml
  influxdb_iox/Cargo.toml
  influxdb_iox_client/Cargo.toml
  influxdb_storage_client/Cargo.toml
  ingester2/Cargo.toml
  ingester2_test_ctx/Cargo.toml
  ioxd_common/Cargo.toml
  ioxd_querier/Cargo.toml
  router/Cargo.toml
  service_common/Cargo.toml
  service_grpc_catalog/Cargo.toml
  service_grpc_flight/Cargo.toml
  service_grpc_influxrpc/Cargo.toml
  service_grpc_namespace/Cargo.toml
  service_grpc_object_store/Cargo.toml
  service_grpc_schema/Cargo.toml
  service_grpc_testing/Cargo.toml
  test_helpers_end_to_end/Cargo.toml
Labels: automerge

#7522 fix: Remove the write_summary crate and write info service
  Cargo.lock
  Cargo.toml
  data_types/src/lib.rs
  generated_types/build.rs
  generated_types/protos/influxdata/iox/ingester/v1/write_info.proto
  generated_types/protos/influxdata/iox/write_summary/v1/write_summary.proto
  generated_types/src/lib.rs
  generated_types/src/write_info.rs
  influxdb_iox_client/src/client.rs
  influxdb_iox_client/src/client/write_info.rs
  ioxd_querier/src/lib.rs
  ioxd_querier/src/rpc/mod.rs
  ioxd_querier/src/rpc/write_info.rs
  ioxd_router/Cargo.toml
  ioxd_router/src/lib.rs
  querier/src/ingester/mod.rs
  querier/src/ingester/test_util.rs
  router/Cargo.toml
  router/src/dml_handlers/fan_out.rs
  router/src/dml_handlers/instrumentation.rs
  router/src/dml_handlers/mock.rs
  router/src/dml_handlers/mod.rs
  router/src/dml_handlers/write_summary.rs
  router/src/server/http.rs
  router/tests/common/mod.rs
  service_grpc_influxrpc/src/id.rs
  write_summary/Cargo.toml
  write_summary/src/lib.rs
  write_summary/src/progress.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7507 feat: Add process/service names to spans, fix ingester span propagation
  ingester2/src/buffer_tree/table.rs
  ingester2/src/query/tracing.rs
  ingester2/src/server/grpc/query.rs
  ioxd_common/src/http/mod.rs
  ioxd_common/src/rpc.rs
  ioxd_common/src/server_type.rs
  ioxd_compactor2/src/lib.rs
  ioxd_garbage_collector/src/lib.rs
  ioxd_ingester2/src/lib.rs
  ioxd_querier/src/lib.rs
  ioxd_router/src/lib.rs
  ioxd_test/src/lib.rs
  service_grpc_influxrpc/src/service.rs
  trace/src/span.rs
  trace_http/src/tower.rs
Labels: automerge

#7511 feat(flightsql): support `database`, `bucket`, and `bucket-name` as grpc header names
  docs/flightsql.md
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
  influxdb_iox/tests/jdbc_client/README.md
  service_grpc_flight/src/lib.rs
Labels: automerge

#7525 docs: note that Span::child() does not automatically emit spans
  trace/src/span.rs
Labels: automerge

#7478 refactor: input buffering for gap filling interpolate null-as-missing
  iox_query/src/exec/gapfill/algo.rs
  iox_query/src/exec/gapfill/buffered_input.rs
  iox_query/src/exec/gapfill/exec_tests.rs
  iox_query/src/exec/gapfill/mod.rs
  iox_query/src/exec/gapfill/stream.rs
Labels: automerge

#7490 fix: make interpolate() fill null values in input
  iox_query/src/exec/gapfill/algo/interpolate.rs
  iox_query/src/exec/gapfill/exec_tests.rs
Labels: automerge

#7494 feat: update gap fill planner rule to use `interpolate`
  influxdb_iox/tests/query_tests2/cases/in/gapfill.sql
  influxdb_iox/tests/query_tests2/cases/in/gapfill.sql.expected
  iox_query/src/logical_optimizer/handle_gapfill.rs
  query_functions/src/gapfill.rs
  query_functions/src/registry.rs
Labels: automerge

#7512 feat: Update InfluxQL end-to-end test output
  Cargo.lock
  arrow_util/src/test_util.rs
  influxdb_iox/src/commands/query.rs
  influxdb_iox/tests/query_tests2/cases/in/influxql_metadata.influxql.expected
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql.expected
  influxdb_iox_client/src/format/influxql.rs
  iox_query_influxql/src/plan/planner.rs
  test_helpers_end_to_end/Cargo.toml
  test_helpers_end_to_end/src/snapshot_comparison.rs
  test_helpers_end_to_end/src/snapshot_comparison/queries.rs
Labels: automerge

#7516 chore: Update DataFusion pin, upgrade `date_bin` and `InfluxQL` to use `Interval(MonthDayNano)`
  Cargo.lock
  Cargo.toml
  datafusion_util/src/lib.rs
  datafusion_util/src/sort_exprs.rs
  influxdb_iox/tests/query_tests2/cases/in/gapfill.sql.expected
  influxdb_iox/tests/query_tests2/sql_errors.rs
  iox_query/src/exec/gapfill/exec_tests.rs
  iox_query/src/exec/gapfill/mod.rs
  iox_query/src/exec/gapfill/params.rs
  iox_query/src/exec/split.rs
  iox_query/src/physical_optimizer/sort/parquet_sortness.rs
  iox_query/src/provider/deduplicate.rs
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/planner_time_range_expression.rs
  query_functions/src/gapfill.rs
  test_helpers_end_to_end/src/error.rs
  workspace-hack/Cargo.toml
Labels: automerge, query/language/influxql

#7524 fix: Remove old querier
  clap_blocks/src/querier.rs
  data_types/src/lib.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/src/commands/run/querier.rs
  influxdb_iox/tests/end_to_end_cases/mode_switching.rs
  ioxd_querier/src/lib.rs
  ioxd_querier/src/rpc/namespace.rs
  querier/src/cache/parquet_file.rs
  querier/src/database.rs
  querier/src/handler.rs
  querier/src/ingester/mod.rs
  querier/src/ingester/test_util.rs
  querier/src/namespace/mod.rs
  querier/src/namespace/test_util.rs
  querier/src/parquet/creation.rs
  querier/src/parquet/mod.rs
  querier/src/table/mod.rs
  querier/src/table/state_reconciler.rs
  querier/src/table/test_util.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7540 chore: update DataFusion pin (right before arrow 37 update)
  Cargo.lock
  Cargo.toml
  iox_query/src/physical_optimizer/projection_pushdown.rs
  iox_query/src/physical_optimizer/sort/parquet_sortness.rs
  iox_query/src/physical_optimizer/sort/redundant_sort.rs
  iox_query/src/physical_optimizer/sort/sort_pushdown.rs
  iox_query/src/provider.rs
  workspace-hack/Cargo.toml
Labels: automerge

#7546 feat(flightsql): Support `GetImportedKeys` metadata endpoint with an empty RecordBatch
  flightsql/src/cmd.rs
  flightsql/src/planner.rs
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
  influxdb_iox/tests/jdbc_client/Main.java
  influxdb_iox_client/src/client/flightsql.rs
  service_grpc_flight/src/lib.rs
Labels: automerge

#7529 chore: add more test and logic to grpc database header names
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
  service_grpc_flight/src/lib.rs
Labels: automerge

#7548 feat(flightsql): Support `GetCrossReference` metadata endpoint with an empty RecordBatch
  flightsql/src/cmd.rs
  flightsql/src/planner.rs
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
  influxdb_iox/tests/jdbc_client/Main.java
  influxdb_iox_client/src/client/flightsql.rs
  service_grpc_flight/src/lib.rs
Labels: automerge

#7544 chore: Update DataFusion + arrow ecosystem to 37
  Cargo.lock
  Cargo.toml
  arrow_util/src/dictionary.rs
  arrow_util/src/flight.rs
  arrow_util/src/optimize.rs
  datafusion_util/src/lib.rs
  flightsql/src/sql_info/value.rs
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
  iox_query/Cargo.toml
  iox_query/src/exec/seriesset/converter.rs
  iox_query/src/lib.rs
  iox_query/src/physical_optimizer/dedup/test_util.rs
  iox_query/src/physical_optimizer/sort/parquet_sortness.rs
  iox_query/src/provider.rs
  iox_query/src/provider/deduplicate/key_ranges.rs
  iox_query/src/provider/physical.rs
  predicate/src/delete_expr.rs
  querier/Cargo.toml
  query_functions/src/selectors.rs
  query_functions/src/selectors/internal.rs
  schema/src/lib.rs
  service_grpc_influxrpc/src/service.rs
  workspace-hack/Cargo.toml
Labels: automerge

#7559 feat: coalesce partition catalog fetches
  ingester2/src/buffer_tree/partition/resolver/cache.rs
  ingester2/src/buffer_tree/partition/resolver/catalog.rs
  ingester2/src/buffer_tree/partition/resolver/coalesce.rs
  ingester2/src/buffer_tree/partition/resolver/mock.rs
  ingester2/src/buffer_tree/partition/resolver/mod.rs
  ingester2/src/buffer_tree/partition/resolver/trait.rs
  ingester2/src/buffer_tree/table.rs
  ingester2/src/init.rs
Labels: kodiak: merge.method = 'merge'

#7560 fix: Remove outdated documentation and infrastructure having to do with Kafka
  .circleci/config.yml
  docker/Dockerfile.ci.dockerignore
  docs/metrics.md
  docs/testing.md
  docs/underground_guide.md
  integration-docker-compose.yml
  iox_data_generator/README.md
Labels: automerge, kodiak: merge.method = 'merge'

#7557 chore: Update datafusion again
  Cargo.lock
  Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge

#7556 chore: deny unknown and copyleft licenses
  deny.toml
  flightsql/Cargo.toml
  ingester2_test_ctx/Cargo.toml
Labels: automerge

#7526 feat: basic InfluxQL `SHOW TAG VALUES` support
  influxdb_iox/tests/query_tests2/cases/in/influxql_metadata.influxql
  influxdb_iox/tests/query_tests2/cases/in/influxql_metadata.influxql.expected
  influxdb_iox/tests/query_tests2/setups.rs
  iox_query_influxql/src/frontend/planner.rs
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/planner/select.rs
Labels: automerge

#7504 feat: basic InfluxQL `SHOW MEASUREMENTS`
  influxdb_iox/tests/query_tests2/cases/in/influxql_metadata.influxql
  influxdb_iox/tests/query_tests2/cases/in/influxql_metadata.influxql.expected
  iox_query_influxql/src/frontend/planner.rs
  iox_query_influxql/src/plan/planner.rs
Labels: automerge

#7451 feat: InfluxQL `SHOW TAG KEYS` planner+exec
  influxdb_iox/tests/end_to_end_cases/influxql.rs
  influxdb_iox/tests/query_tests2/cases/in/influxql_metadata.influxql
  influxdb_iox/tests/query_tests2/cases/in/influxql_metadata.influxql.expected
  influxdb_iox/tests/query_tests2/setups.rs
  iox_query_influxql/src/frontend/planner.rs
  iox_query_influxql/src/plan/planner.rs
  test_helpers_end_to_end/src/steps.rs
Labels: automerge

#7561 fix: Remove tombstone code that isn't functional currently
  compactor2/src/components/df_planner/query_chunk.rs
  data_types/src/lib.rs
  docs/compactor.md
  docs/ingester_querier_protocol.md
  influxdb_iox/tests/end_to_end_cases/querier.rs
  ingester2/src/buffer_tree/table.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
  iox_tests/src/catalog.rs
  predicate/src/delete_predicate.rs
  querier/src/cache/mod.rs
  querier/src/cache/processed_tombstones.rs
  querier/src/cache/tombstones.rs
  querier/src/ingester/mod.rs
  querier/src/lib.rs
  querier/src/namespace/mod.rs
  querier/src/namespace/query_access.rs
  querier/src/parquet/creation.rs
  querier/src/parquet/mod.rs
  querier/src/table/mod.rs
  querier/src/table/state_reconciler.rs
  querier/src/table/state_reconciler/interface.rs
  querier/src/table/test_util.rs
  querier/src/tombstone.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7563 feat: Teach InfluxQL `last`, `first`, `min` and `max` selector functions
  Cargo.lock
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql.expected
  iox_query_influxql/Cargo.toml
  iox_query_influxql/src/plan/error.rs
  iox_query_influxql/src/plan/expr_type_evaluator.rs
  iox_query_influxql/src/plan/field_mapper.rs
  iox_query_influxql/src/plan/mod.rs
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/planner_time_range_expression.rs
  iox_query_influxql/src/plan/rewriter.rs
  iox_query_influxql/src/plan/test_utils.rs
  iox_query_influxql/src/plan/timestamp.rs
  iox_query_influxql/src/plan/util.rs
  iox_query_influxql/src/plan/util_copy.rs
Labels: automerge, kodiak: merge.method = 'merge', query/language/influxql

#7578 fix: Update h2 crate because 0.3.17 was yanked
  Cargo.lock
Labels: automerge, kodiak: merge.method = 'merge'

#7584 feat: Teach IOx how to process `COUNT(DISTINCT)` and `DISTINCT` queries
  influxdb_influxql_parser/src/identifier.rs
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql.expected
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/planner/select.rs
  iox_query_influxql/src/plan/rewriter.rs
Labels: automerge, kodiak: merge.method = 'merge', query/language/influxql

#7573 feat: Delete delete parsing code from router
  router/src/dml_handlers/chain.rs
  router/src/dml_handlers/fan_out.rs
  router/src/dml_handlers/instrumentation.rs
  router/src/dml_handlers/mock.rs
  router/src/dml_handlers/nop.rs
  router/src/dml_handlers/partitioner.rs
  router/src/dml_handlers/retention_validation.rs
  router/src/dml_handlers/rpc_write.rs
  router/src/dml_handlers/rpc_write/circuit_breaking_client.rs
  router/src/dml_handlers/rpc_write/lazy_connector.rs
  router/src/dml_handlers/schema_validation.rs
  router/src/dml_handlers/trait.rs
  router/src/server/http.rs
  router/src/server/http/delete_predicate.rs
  router/tests/http.rs
Labels: automerge

#7577 fix: remove old, unused catalog functions (and a few types)
  data_types/src/lib.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
  iox_tests/src/catalog.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7585 chore: remove unused dependencies
  Cargo.lock
  garbage_collector/Cargo.toml
  querier/Cargo.toml
  router/Cargo.toml
  schema/Cargo.toml
Labels: automerge, kodiak: merge.method = 'merge'

#7587 refactor: move HTTP authz helpers into authz
  Cargo.lock
  Cargo.toml
  authz/Cargo.toml
  authz/src/http.rs
  authz/src/lib.rs
  ioxd_common/Cargo.toml
  ioxd_common/src/http/mod.rs
  router/Cargo.toml
  router/src/server/http.rs
  server_util/Cargo.toml
  server_util/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7588 refactor(router): remove unused deps
  Cargo.lock
  router/Cargo.toml
  router/src/dml_handlers/rpc_write/client.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7586 feat: allow overwriting DataFusion's default config
  clap_blocks/src/querier.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  iox_query/src/config.rs
  iox_query/src/exec/context.rs
  ioxd_querier/src/lib.rs
  ioxd_querier/src/rpc/namespace.rs
  querier/src/database.rs
  querier/src/handler.rs
  querier/src/namespace/mod.rs
  querier/src/namespace/query_access.rs
Labels: automerge

#7591 fix: consistent NamespaceName validation
  Cargo.lock
  data_types/src/namespace_name.rs
  service_grpc_namespace/Cargo.toml
  service_grpc_namespace/src/lib.rs
Labels: kind/bug, automerge, kodiak: merge.method = 'merge'

#7593 fix(ingester): always drive partition resolve futures to completion
  ingester2/src/buffer_tree/partition/resolver/coalesce.rs
Labels: kodiak: merge.method = 'merge'

#7589 feat: `SHOW TAG VALUES ... WHERE <condition>`
  influxdb_iox/tests/query_tests2/cases/in/influxql_metadata.influxql
  influxdb_iox/tests/query_tests2/cases/in/influxql_metadata.influxql.expected
  influxdb_iox/tests/query_tests2/setups.rs
  iox_query_influxql/src/frontend/planner.rs
  iox_query_influxql/src/plan/planner.rs
  test_helpers_end_to_end/src/config.rs
Labels: automerge

#7567 fix: Garbage collector hangs indefinitely on shutdown
  Cargo.lock
  garbage_collector/Cargo.toml
  garbage_collector/src/lib.rs
  garbage_collector/src/objectstore/checker.rs
  garbage_collector/src/objectstore/deleter.rs
  garbage_collector/src/objectstore/lister.rs
Labels: automerge

#7595 refactor: let date_bin_gapfill allow omitted origin
  influxdb_iox/tests/query_tests2/cases/in/gapfill.sql
  influxdb_iox/tests/query_tests2/cases/in/gapfill.sql.expected
  iox_query/src/exec/gapfill/exec_tests.rs
  iox_query/src/exec/gapfill/mod.rs
  iox_query/src/exec/gapfill/params.rs
  iox_query/src/logical_optimizer/handle_gapfill.rs
  iox_query_influxql/src/plan/planner.rs
  query_functions/src/gapfill.rs
Labels: automerge

#7596 test: add tests for gap filling with nanosecond precision
  influxdb_iox/tests/query_tests2/cases/in/gapfill.sql
  influxdb_iox/tests/query_tests2/cases/in/gapfill.sql.expected
Labels: automerge

#7530 feat: Cold compaction CLI that only selects partitions and logs them
  clap_blocks/src/compactor2.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/partitions_source/logging.rs
  compactor2/src/components/report.rs
  compactor2/src/config.rs
  compactor2/tests/integration.rs
  compactor2_test_utils/src/lib.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ioxd_compactor2/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7604 fix: also include metadata in empty InfluxQL select results
  influxdb_iox/tests/query_tests2/cases/in/influxql_metadata.influxql.expected
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql.expected
  iox_query_influxql/src/plan/planner.rs
  test_helpers_end_to_end/src/snapshot_comparison.rs
Labels: automerge

#7608 chore(flightsql): rename Namespace to Database in error message
  influxdb_iox/tests/end_to_end_cases/cli.rs
  influxdb_iox/tests/end_to_end_cases/namespace.rs
  service_grpc_flight/src/lib.rs
Labels: automerge

#7613 fix: Rewrite time range expressions so they apply to entire result set
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql.expected
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/planner_rewrite_expression.rs
Labels: automerge, kodiak: merge.method = 'merge', query/language/influxql

#7619 fix: process query param for token, even when header is not present.
  router/src/server/http/write/single_tenant/auth.rs
  router/src/server/http/write/single_tenant/mod.rs
Labels: automerge

#7622 fix(garbage collector): decrease info msg; don't loop immediately
  garbage_collector/src/objectstore/deleter.rs
  garbage_collector/src/parquetfile/deleter.rs
Labels: automerge

#7630 chore: update DF to `181e5ccf2816ccaa05d8aaef0b375d4b7bbceece`
  Cargo.lock
  Cargo.toml
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql.expected
  workspace-hack/Cargo.toml
Labels: automerge

#7633 fix: InfluxQL output sorting
  influxdb_iox/tests/query_tests2/cases/in/influxql_metadata.influxql
  influxdb_iox/tests/query_tests2/cases/in/influxql_metadata.influxql.expected
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql.expected
  iox_query_influxql/src/plan/planner.rs
Labels: automerge

#7543 fix: Remove uses and tests for RPC mode env var
  arrow_util/src/test_util.rs
  compactor2/tests/integration.rs
  influxdb_iox/src/commands/remote/partition.rs
  influxdb_iox/src/commands/run/compactor2.rs
  influxdb_iox/src/commands/run/ingester2.rs
  influxdb_iox/src/commands/run/querier.rs
  influxdb_iox/src/commands/run/router2.rs
  influxdb_iox/tests/end_to_end_cases/compactor.rs
  influxdb_iox/tests/end_to_end_cases/mod.rs
  influxdb_iox/tests/end_to_end_cases/mode_switching.rs
  influxdb_iox/tests/query_tests2/cases/in/dedup_and_predicates_parquet.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/dedup_and_predicates_parquet_ingester.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_ingester.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_parquet.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_parquet_many.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/gapfill.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql.expected
  influxdb_iox/tests/query_tests2/cases/in/pushdown.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/retention.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/several_chunks.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/two_chunks.sql.expected
  ingester2/README.md
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
  querier/src/ingester/mod.rs
  querier/src/namespace/query_access.rs
  service_grpc_catalog/src/lib.rs
  test_helpers_end_to_end/src/config.rs
  test_helpers_end_to_end/src/server_type.rs
  test_helpers_end_to_end/src/snapshot_comparison.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7638 chore(garbage collector): info logging for deleting parquet file
  garbage_collector/src/objectstore/deleter.rs
Labels: automerge

#7620 feat: teach parser to allow arithmetic functions
  influxdb_influxql_parser/src/expression/conditional.rs
  influxdb_influxql_parser/src/functions.rs
  influxdb_influxql_parser/src/lib.rs
  influxdb_influxql_parser/src/select.rs
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql.expected
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/planner_time_range_expression.rs
  iox_query_influxql/src/plan/rewriter.rs
Labels: automerge

#7639 fix: In DmlMeta, only use SequenceNumber rather than Sequence (shard index plus seq num)
  data_types/src/lib.rs
  dml/src/lib.rs
  ingester2/benches/write.rs
  ingester2/src/buffer_tree/namespace.rs
  ingester2/src/dml_sink/tracing.rs
  ingester2/src/init/wal_replay.rs
  ingester2/src/server/grpc/rpc_write.rs
  ingester2/src/test_util.rs
  ingester2/src/wal/wal_sink.rs
  ingester2_test_ctx/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7642 feat: add compactor concurrency within single partition's plans
  compactor2/src/driver.rs
  compactor2/tests/layouts/backfill.rs
  compactor2/tests/layouts/knobs.rs
Labels: automerge

#7629 feat: Add `pre` and `post` visit events for `Literal`
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__delete_statement-2.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__select_statement-6.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__show_measurements_statement-4.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__show_measurements_statement-7.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__delete_statement-2.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__select_statement-6.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__show_measurements_statement-4.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__show_measurements_statement-7.snap
  influxdb_influxql_parser/src/visit.rs
  influxdb_influxql_parser/src/visit_mut.rs
Labels: automerge, query/language/influxql

#7607 refactor: push authz into specific configs
  clap_blocks/src/authz.rs
  clap_blocks/src/lib.rs
  clap_blocks/src/querier.rs
  clap_blocks/src/router2.rs
  clap_blocks/src/single_tenant.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/src/commands/run/querier.rs
  influxdb_iox/src/commands/run/router2.rs
  ioxd_querier/src/lib.rs
  ioxd_router/src/lib.rs
Labels: automerge

#7648 test: add tests on month and year date_bin
  influxdb_iox/tests/query_tests2/cases.rs
  influxdb_iox/tests/query_tests2/cases/in/date_bin.sql
  influxdb_iox/tests/query_tests2/cases/in/date_bin.sql.expected
Labels: automerge

#7651 refactor: Extract commonly duplicated test code into helpers
  ingester2/src/buffer_tree/namespace.rs
  ingester2/src/buffer_tree/namespace/name_resolver.rs
  ingester2/src/buffer_tree/partition.rs
  ingester2/src/buffer_tree/partition/resolver/cache.rs
  ingester2/src/buffer_tree/partition/resolver/coalesce.rs
  ingester2/src/buffer_tree/partition/resolver/mock.rs
  ingester2/src/buffer_tree/partition/resolver/trait.rs
  ingester2/src/buffer_tree/root.rs
  ingester2/src/buffer_tree/table.rs
  ingester2/src/buffer_tree/table/name_resolver.rs
  ingester2/src/init/graceful_shutdown.rs
  ingester2/src/init/wal_replay.rs
  ingester2/src/persist/handle.rs
  ingester2/src/persist/hot_partitions.rs
  ingester2/src/persist/mod.rs
  ingester2/src/test_util.rs
  ingester2/src/wal/rotate_task.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7576 feat(flightsql): Support `CommandGetXdbcTypeInfo` metadata endpoint with an empty RecordBatch
  flightsql/src/cmd.rs
  flightsql/src/planner.rs
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
  influxdb_iox/tests/jdbc_client/Main.java
  influxdb_iox_client/src/client/flightsql.rs
  service_grpc_flight/src/lib.rs
Labels: automerge

#7645 test: Add a test for `The data type inlist should be same` error
  influxdb_iox/tests/query_tests2/cases.rs
  influxdb_iox/tests/query_tests2/cases/in/bugs.sql
  influxdb_iox/tests/query_tests2/cases/in/bugs.sql.expected
  influxdb_iox/tests/query_tests2/setups.rs
Labels: automerge

#7660 feat(service_grpc_flight): JDBC compatible Handshake
  Cargo.lock
  authz/Cargo.toml
  authz/src/lib.rs
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
  influxdb_iox/tests/jdbc_client/Main.java
  router/src/server/http/write/single_tenant/auth.rs
  router/src/server/http/write/single_tenant/mod.rs
  service_grpc_flight/src/lib.rs
Labels: automerge

#7672 test: property test namespace schema merging
  Cargo.lock
  router/Cargo.toml
  router/src/namespace_cache/memory.rs
Labels: kodiak: merge.method = 'merge'

#7658 chore: Run end to end integration tests as part of a separate circle CI Job
  .circleci/config.yml
Labels: automerge

#7670 feat: Evaluate data types of binary expressions
  iox_query_influxql/src/plan/expr_type_evaluator.rs
  iox_query_influxql/src/plan/rewriter.rs
  iox_query_influxql/src/plan/test_utils.rs
Labels: automerge, query/language/influxql

#7679 refactor: do not block on querier cache warm-up
  querier/src/table/mod.rs
Labels: automerge

#7678 fix: racy JDBC tests
  .circleci/config.yml
  influxdb_iox/tests/jdbc_client/Makefile
  influxdb_iox/tests/jdbc_client/jdbc_client
Labels: automerge

#7680 refactor: remove `QueryChunk::partition_sort_key`
  compactor2/src/components/df_planner/query_chunk.rs
  ingester2/src/query_adaptor.rs
  iox_query/src/lib.rs
  iox_query/src/test.rs
  querier/src/ingester/mod.rs
  querier/src/parquet/creation.rs
  querier/src/parquet/mod.rs
  querier/src/parquet/query_access.rs
  querier/src/table/state_reconciler.rs
Labels: automerge

#7674 build: bump rust version
  influxdb_influxql_parser/src/literal.rs
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
  router/src/dml_handlers/rpc_write/balancer.rs
  rust-toolchain.toml
Labels: automerge, kodiak: merge.method = 'merge'

#7681 feat: classify panics
  Cargo.lock
  panic_logging/Cargo.toml
  panic_logging/src/lib.rs
  test_helpers/src/tracing.rs
Labels: automerge

#7636 refactor: only use struct-style `select` in InfluxQL planner
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/util.rs
  query_functions/src/coalesce_struct.rs
  query_functions/src/lib.rs
Labels: automerge

#7675 feat: add interior mutability to compactor's scratchpad
  compactor2/src/components/scratchpad/mod.rs
  compactor2/src/components/scratchpad/noop.rs
  compactor2/src/components/scratchpad/prod.rs
  compactor2/src/driver.rs
Labels: automerge

#7652 chore(garbage collector): backoff first connect to objectstore
  Cargo.lock
  garbage_collector/Cargo.toml
  garbage_collector/src/lib.rs
  garbage_collector/src/objectstore/lister.rs
Labels: automerge

#7686 chore: renaming compaction job concurrency to df concurrency
  clap_blocks/src/compactor2.rs
  compactor2/src/compactor.rs
  compactor2/src/components/report.rs
  compactor2/src/config.rs
  compactor2/src/driver.rs
  compactor2_test_utils/src/lib.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ioxd_compactor2/src/lib.rs
Labels: automerge

#7676 feat: Improve InfluxQL rewriter for subquery support
  influxdb_influxql_parser/src/common.rs
  iox_query_influxql/src/plan/field.rs
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/rewriter.rs
  schema/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge', query/language/influxql

#7689 fix(garbage collector): respect lister limit, display source errors
  garbage_collector/src/objectstore/lister.rs
Labels: automerge

#7682 chore(clap_blocks): remove unused dep
  Cargo.lock
  clap_blocks/Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'merge'

#7694 chore: add compactor logging
  compactor2/src/driver.rs
Labels: automerge

#7695 chore(garbage collector): improve logging in lister
  garbage_collector/src/objectstore/lister.rs
Labels: automerge
