Repository influxdata/influxdb_iox, pull requests merged in 2023-02, with the labels that each got.

#6772 feat: IOx InfluxQL planner learns how to process time range expressions
  Cargo.lock
  influxdb_influxql_parser/Cargo.toml
  influxdb_influxql_parser/src/common.rs
  influxdb_influxql_parser/src/expression/arithmetic.rs
  influxdb_influxql_parser/src/expression/conditional.rs
  influxdb_influxql_parser/src/lib.rs
  influxdb_influxql_parser/src/literal.rs
  iox_query/Cargo.toml
  iox_query/src/plan/influxql.rs
  iox_query/src/plan/influxql/expr_type_evaluator.rs
  iox_query/src/plan/influxql/planner.rs
  iox_query/src/plan/influxql/planner_time_range_expression.rs
  iox_query/src/plan/influxql/rewriter.rs
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__time_range_in_where-2.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__time_range_in_where-3.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__time_range_in_where-4.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__time_range_in_where.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__simple_arithmetic_in_projection-2.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__simple_arithmetic_in_projection-3.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__simple_arithmetic_in_projection-4.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__simple_arithmetic_in_projection.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__single_measurement-2.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__single_measurement-3.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__single_measurement-4.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__single_measurement-5.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__single_measurement-6.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__single_measurement-7.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__single_measurement-8.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__single_measurement.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__unsupported_statements-10.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__unsupported_statements-2.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__unsupported_statements-3.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__unsupported_statements-4.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__unsupported_statements-5.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__unsupported_statements-6.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__unsupported_statements-7.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__unsupported_statements-8.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__unsupported_statements-9.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__unsupported_statements.snap
  iox_query/src/plan/influxql/timestamp.rs
  iox_query/src/plan/influxql/util.rs
Labels: automerge, query/language/influxql

#6794 refactor: extract early ID-based partition filters into new components
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/id_only_partition_filter/and.rs
  compactor2/src/components/id_only_partition_filter/by_id.rs
  compactor2/src/components/id_only_partition_filter/mod.rs
  compactor2/src/components/id_only_partition_filter/shard.rs
  compactor2/src/components/mod.rs
  compactor2/src/components/partition_filter/mod.rs
  compactor2/src/components/partitions_source/filter.rs
  compactor2/src/components/partitions_source/mod.rs
Labels: automerge

#6796 feat: allow partition filters to error + flag partitions
  compactor2/src/components/partition_done_sink/catalog.rs
  compactor2/src/components/partition_done_sink/error_kind.rs
  compactor2/src/components/partition_done_sink/logging.rs
  compactor2/src/components/partition_done_sink/metrics.rs
  compactor2/src/components/partition_done_sink/mock.rs
  compactor2/src/components/partition_done_sink/mod.rs
  compactor2/src/components/partition_filter/and.rs
  compactor2/src/components/partition_filter/has_files.rs
  compactor2/src/components/partition_filter/has_matching_file.rs
  compactor2/src/components/partition_filter/logging.rs
  compactor2/src/components/partition_filter/max_files.rs
  compactor2/src/components/partition_filter/max_parquet_bytes.rs
  compactor2/src/components/partition_filter/metrics.rs
  compactor2/src/components/partition_filter/mod.rs
  compactor2/src/components/partition_filter/never_skipped.rs
  compactor2/src/driver.rs
  compactor2/src/error.rs
Labels: automerge

#6795 fix(router): 0 value retention periods
  Cargo.lock
  router/tests/grpc.rs
  service_grpc_namespace/Cargo.toml
  service_grpc_namespace/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6798 docs: retention period value mappings
  generated_types/protos/influxdata/iox/namespace/v1/service.proto
  influxdb_iox_client/src/client/namespace.rs
Labels: kodiak: merge.method = 'merge'

#6800 feat: allow selection of different compactor algo versions
  clap_blocks/src/compactor2.rs
  compactor2/src/compactor.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/report.rs
  compactor2/src/config.rs
  compactor2/src/test_util.rs
  ioxd_compactor2/src/lib.rs
Labels: automerge

#6799 fix(iox): Add transition shard to catalog setup
  data_types/src/lib.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/postgres.rs
Labels: automerge

#6801 test: Port tag_values query_tests to end-to-end tests
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/metadata.rs
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/metadata/tag_values.rs
  query_tests/src/influxrpc.rs
  query_tests/src/influxrpc/tag_values.rs
  query_tests/src/influxrpc/util.rs
  query_tests/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6804 feat: start adding piece by piece for hotcold compaction
  compactor2/src/components/commit/catalog.rs
  compactor2/src/components/commit/logging.rs
  compactor2/src/components/commit/metrics.rs
  compactor2/src/components/commit/mock.rs
  compactor2/src/components/commit/mod.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/driver.rs
Labels: automerge

#6792 feat: Regular expression operator support
  iox_query/src/plan/influxql/planner.rs
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__time_range_in_where-10.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__time_range_in_where-5.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__time_range_in_where-6.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__time_range_in_where-7.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__time_range_in_where-8.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__time_range_in_where-9.snap
Labels: automerge, query/language/influxql

#6778 feat: throttle partitions that do not receive commits
  compactor2/src/compactor.rs
  compactor2/src/components/combos/mod.rs
  compactor2/src/components/combos/throttle_partition.rs
  compactor2/src/components/hardcoded.rs
Labels: automerge

#6814 ci: use new influx gpg signing key
  docker/Dockerfile.ci
Labels: kodiak: merge.method = 'merge'

#6815 feat(catalog): use explicit UTC time zone
  iox_catalog/src/postgres.rs
Labels: kodiak: merge.method = 'merge'

#6806 chore: add definition for the output of compacting a partition
  compactor2/src/driver.rs
Labels: automerge

#6807 test: Port remaining query_tests/src/sql.rs tests to end-to-end
  influxdb_iox/tests/query_tests2/cases.rs
  influxdb_iox/tests/query_tests2/cases/in/aggregates.expected
  influxdb_iox/tests/query_tests2/cases/in/aggregates.sql
  influxdb_iox/tests/query_tests2/cases/in/aggregates_with_nulls.expected
  influxdb_iox/tests/query_tests2/cases/in/aggregates_with_nulls.sql
  influxdb_iox/tests/query_tests2/cases/in/different_tag_sets.expected
  influxdb_iox/tests/query_tests2/cases/in/different_tag_sets.sql
  influxdb_iox/tests/query_tests2/cases/in/duplicates_ingester.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_ingester.sql
  influxdb_iox/tests/query_tests2/cases/in/duplicates_parquet.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_parquet.sql
  influxdb_iox/tests/query_tests2/cases/in/restaurant.expected
  influxdb_iox/tests/query_tests2/cases/in/restaurant.sql
  influxdb_iox/tests/query_tests2/cases/in/schema_merge.expected
  influxdb_iox/tests/query_tests2/cases/in/schema_merge.sql
  influxdb_iox/tests/query_tests2/cases/in/union_all.expected
  influxdb_iox/tests/query_tests2/cases/in/union_all.sql
  influxdb_iox/tests/query_tests2/mod.rs
  influxdb_iox/tests/query_tests2/setups.rs
  influxdb_iox/tests/query_tests2/sql_errors.rs
  query_tests/src/lib.rs
  query_tests/src/sql.rs
  test_helpers_end_to_end/src/snapshot_comparison.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6820 revert: throttle partitions that do not receive commits (#6778)
  compactor2/src/compactor.rs
  compactor2/src/components/combos/mod.rs
  compactor2/src/components/combos/throttle_partition.rs
  compactor2/src/components/hardcoded.rs
Labels: automerge

#6810 refactor: Framework for compact version2: hotcold
  compactor2/src/components/hardcoded.rs
  compactor2/src/driver.rs
Labels: automerge

#6811 feat: Updating to new services for all-in-one
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/tests/end_to_end_cases/all_in_one.rs
  influxdb_iox/tests/end_to_end_cases/cli.rs
  influxdb_iox/tests/end_to_end_cases/metrics.rs
  influxdb_iox/tests/end_to_end_cases/tracing.rs
  parquet_file/src/lib.rs
  wal/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6805 feat: find time range in WHERE clause for gap-filling
  iox_query/src/exec/gapfill.rs
  iox_query/src/logical_optimizer/handle_gapfill.rs
  iox_query/src/logical_optimizer/handle_gapfill/range_predicate.rs
Labels: automerge

#6822 chore: reduce scope of `#[allow(dead_code)]`
  wal/src/lib.rs
Labels: automerge

#6821 fix: Correct a normalization regex to fix a flaky test, print query test diffs in CI
  test_helpers_end_to_end/src/snapshot_comparison.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6830 feat: Add support for data-driven InfluxQL tests
  influxdb_iox/build.rs
  influxdb_iox/tests/query_tests2/cases.rs
  influxdb_iox/tests/query_tests2/cases/in/aggregates.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/aggregates_with_nulls.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/basic.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/dedup_and_predicates_parquet.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/dedup_and_predicates_parquet_ingester.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/different_tag_sets.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_ingester.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_parquet.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_parquet_many.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql.expected
  influxdb_iox/tests/query_tests2/cases/in/new_sql_system_tables.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/periods.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/pushdown.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/restaurant.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/retention.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/schema_merge.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/selectors.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/several_chunks.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/sql_information_schema.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/timestamps.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/two_chunks.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/two_chunks_missing_columns.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/union_all.sql.expected
  influxdb_iox/tests/query_tests2/framework.rs
  influxdb_iox/tests/query_tests2/setups.rs
  test_helpers_end_to_end/src/snapshot_comparison.rs
  test_helpers_end_to_end/src/steps.rs
Labels: automerge, kodiak: merge.method = 'squash', testing, query/language/influxql, query/language/sql

#6840 refactor(wal): remove unused checksum
  wal/src/blocking/reader.rs
  wal/src/blocking/writer.rs
  wal/src/lib.rs
Labels: kodiak: merge.method = 'merge'

#6833 chore: Update `influxql` end to end tests to kafkaless write path
  influxdb_iox/tests/end_to_end_cases/influxql.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6835 chore: Port `flightsql` end to end tests for new kafkaless writepath
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6836 chore: port `cli` end to end tests to kafkaless write path
  influxdb_iox/tests/end_to_end_cases/cli.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6837 chore: Remove old ingester end to end tests
  influxdb_iox/tests/end_to_end_cases/ingester.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6839 chore: Port `influxrpc` end to end tests to new writepath
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc.rs
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/read_filter.rs
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/read_group.rs
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/read_window_aggregate.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6841 refactor: rename compact algo versions to reflect their actual work
  clap_blocks/src/compactor2.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/config.rs
  compactor2/src/test_util.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ioxd_compactor2/src/lib.rs
Labels: automerge

#6834 chore: remove duplicated kafka full querier end to end tests
  influxdb_iox/tests/end_to_end_cases/querier.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6838 chore: port `remote` end to end tests to new write path
  influxdb_iox/tests/end_to_end_cases/remote.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6843 refactor(iox): lower default table limit
  iox_catalog/src/lib.rs
  iox_catalog/src/postgres.rs
Labels: kodiak: merge.method = 'merge'

#6845 fix: Normalize for flaky tests
  influxdb_iox/tests/query_tests2/cases/in/dedup_and_predicates_parquet.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/dedup_and_predicates_parquet_ingester.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_ingester.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_parquet.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_parquet_many.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/pushdown.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/retention.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/several_chunks.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/two_chunks.sql.expected
  test_helpers_end_to_end/src/snapshot_comparison.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6828 test: Port table_schema tests to end-to-end and get rid of query_tests
  .gitignore
  .guppy/hakari.toml
  Cargo.lock
  Cargo.toml
  influxdb_iox/tests/end_to_end_cases/schema.rs
  query_tests/Cargo.toml
  query_tests/src/db.rs
  query_tests/src/lib.rs
  query_tests/src/scenarios.rs
  query_tests/src/scenarios/delete.rs
  query_tests/src/scenarios/library.rs
  query_tests/src/scenarios/util.rs
  query_tests/src/table_schema.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6844 Revert "chore: preserve `query_tests2` output in CI (#6782)"
  .circleci/config.yml
Labels: automerge, kodiak: merge.method = 'squash'

#6829 feat: split higher target level files from compact ones
  compactor2/src/components/files_split/all_at_once_target_level_split.rs
  compactor2/src/components/files_split/mod.rs
  compactor2/src/components/files_split/target_level_target_level_split.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/mod.rs
  compactor2/src/components/report.rs
  compactor2/src/driver.rs
  compactor2/src/test_util.rs
Labels: automerge

#6846 refactor: Break snapshot_comparison into smaller modules
  test_helpers_end_to_end/src/snapshot_comparison.rs
  test_helpers_end_to_end/src/snapshot_comparison/normalization.rs
  test_helpers_end_to_end/src/snapshot_comparison/queries.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6847 test: Port more query tests to kafkaless
  influxdb_iox/tests/end_to_end_cases/querier.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6849 feat: split non-overlapping files and not compact them
  compactor2/src/components/files_split/all_at_once_non_overlap_split.rs
  compactor2/src/components/files_split/all_at_once_target_level_split.rs
  compactor2/src/components/files_split/mod.rs
  compactor2/src/components/files_split/target_level_non_overlap_split.rs
  compactor2/src/components/files_split/target_level_target_level_split.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/mod.rs
  compactor2/src/components/report.rs
  compactor2/src/driver.rs
  compactor2/src/test_util.rs
  data_types/src/lib.rs
Labels: automerge

#6852 feat: split files to upgrade and compact
  compactor2/src/components/files_split/all_at_once_upgrade_split.rs
  compactor2/src/components/files_split/mod.rs
  compactor2/src/components/files_split/target_level_non_overlap_split.rs
  compactor2/src/components/files_split/target_level_target_level_split.rs
  compactor2/src/components/files_split/target_level_upgrade_split.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/mod.rs
  compactor2/src/components/report.rs
  compactor2/src/driver.rs
  compactor2/src/test_util.rs
  data_types/src/lib.rs
Labels: automerge

#6854 refactor: extract timerange calculations
  compactor2/src/components/files_split/target_level_non_overlap_split.rs
  compactor2/src/file_group.rs
  compactor2/src/lib.rs
Labels: automerge

#6855 refactor: reduce code duplication in compactor
  compactor2/src/components/files_split/target_level_upgrade_split.rs
  compactor2/src/file_group.rs
Labels: automerge

#6856 refactor: reduce more code duplication in compactor
  compactor2/src/components/files_split/target_level_upgrade_split.rs
Labels: automerge

#6857 chore: refactor splitting files by level
  compactor2/src/components/files_split/target_level_non_overlap_split.rs
  compactor2/src/components/files_split/target_level_upgrade_split.rs
  compactor2/src/file_group.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6818 docs: high-level documentation for `compactor2`
  compactor2/img/driver.svg
  compactor2/src/lib.rs
Labels: automerge

#6831 feat: throttle partitions that do not receive commits
  compactor2/src/compactor.rs
  compactor2/src/components/combos/mod.rs
  compactor2/src/components/combos/tests.rs
  compactor2/src/components/combos/throttle_partition.rs
  compactor2/src/components/combos/unique_partitions.rs
  compactor2/src/components/hardcoded.rs
Labels: automerge

#6803 refactor: use "endless" stream for compactor work
  clap_blocks/src/compactor2.rs
  compactor2/src/compactor.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/mod.rs
  compactor2/src/components/partition_stream/endless.rs
  compactor2/src/components/partition_stream/mod.rs
  compactor2/src/components/partition_stream/once.rs
  compactor2/src/components/report.rs
  compactor2/src/config.rs
  compactor2/src/driver.rs
  compactor2/src/test_util.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ioxd_compactor2/src/lib.rs
Labels: automerge

#6756 chore: update DataFusion, upgrade `arrow` `arrow-flight` and `parquet` to `32.0.0`
  Cargo.lock
  Cargo.toml
  compactor/src/warm.rs
  compactor2/src/components/df_plan_exec/dedicated.rs
  datafusion_util/src/lib.rs
  datafusion_util/src/watch.rs
  influxdb_iox/tests/end_to_end_cases/querier.rs
  ingest_replica/Cargo.toml
  ingest_replica/src/grpc/query.rs
  ingest_replica/src/query/response.rs
  ingester/Cargo.toml
  ingester/src/data.rs
  ingester/src/querier_handler.rs
  ingester2/Cargo.toml
  ingester2/src/query/response.rs
  ingester2/src/server/grpc/query.rs
  iox_query/src/exec/context.rs
  iox_query/src/exec/cross_rt_stream.rs
  iox_query/src/exec/fieldlist.rs
  iox_query/src/exec/non_null_checker.rs
  iox_query/src/exec/query_tracing.rs
  iox_query/src/exec/schema_pivot.rs
  iox_query/src/exec/seriesset/converter.rs
  iox_query/src/exec/split.rs
  iox_query/src/provider/adapter.rs
  iox_query/src/provider/deduplicate.rs
  parquet_file/src/metadata.rs
  parquet_file/src/serialize.rs
  parquet_file/src/storage.rs
  querier/src/system_tables/mod.rs
  schema/src/sort.rs
  service_grpc_flight/src/lib.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#6867 refactor: pass more information to `commit`
  compactor2/src/components/combos/throttle_partition.rs
  compactor2/src/components/commit/catalog.rs
  compactor2/src/components/commit/logging.rs
  compactor2/src/components/commit/metrics.rs
  compactor2/src/components/commit/mock.rs
  compactor2/src/components/commit/mod.rs
  compactor2/src/driver.rs
Labels: automerge

#6871 feat: rework commit log+metrics
  compactor2/src/components/commit/logging.rs
  compactor2/src/components/commit/metrics.rs
  compactor2/src/test_util.rs
Labels: automerge

#6869 fix: correct http content-type header for error responses
  Cargo.lock
  influxdb_iox/Cargo.toml
  influxdb_iox/tests/end_to_end_cases/mod.rs
  influxdb_iox/tests/end_to_end_cases/router.rs
  ioxd_common/src/http/error.rs
Labels: kodiak: merge.method = 'merge'

#6874 chore: debug info
  compactor2/src/driver.rs
Labels: automerge

#6853 refactor: add / cleanup some comments in compactor2
  compactor2/src/components/divide_initial/mod.rs
  compactor2/src/components/files_split/mod.rs
  compactor2/src/driver.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6872 fix: Remove compactor generate
  influxdb_iox/src/commands/compactor.rs
  influxdb_iox/src/commands/compactor/generate.rs
  influxdb_iox/tests/end_to_end_cases/compactor.rs
  influxdb_iox/tests/end_to_end_cases/mod.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6848 refactor: Consolidate end to end normalization code
  test_helpers_end_to_end/src/snapshot_comparison.rs
  test_helpers_end_to_end/src/snapshot_comparison/normalization.rs
  test_helpers_end_to_end/src/snapshot_comparison/queries.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6879 refactor: reduce duplication for compactor_tests
  compactor2/src/compactor_tests.rs
  compactor2/src/test_util.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6878 docs(compactor): Update comments about what `PartitionFilter` does
  compactor2/src/components/partition_filter/mod.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6851 feat: Initial SQLite catalog schema
  Cargo.lock
  clap_blocks/src/catalog_dsn.rs
  data_types/src/lib.rs
  iox_catalog/.gitignore
  iox_catalog/Cargo.toml
  iox_catalog/sqlite/migrations/20230203080000_initial_schema.sql
  iox_catalog/sqlite/migrations/20230204082400_parquet_file_triggers.sql
  iox_catalog/src/lib.rs
  iox_catalog/src/sqlite.rs
  workspace-hack/Cargo.toml
Labels: automerge, domain/iox/catalog

#6875 refactor: better validation of gap filling queries
  iox_query/src/exec/gapfill.rs
  iox_query/src/exec/gapfill/algo.rs
  iox_query/src/logical_optimizer/handle_gapfill.rs
Labels: automerge

#6873 perf(router): cheap table limit enforcement + better errors
  compactor2/src/test_util.rs
  data_types/src/lib.rs
  ingester/src/data.rs
  ingester/tests/common/mod.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_tests/src/util.rs
  mutable_batch/src/lib.rs
  router/src/dml_handlers/schema_validation.rs
  router/src/namespace_cache/memory.rs
  router/src/namespace_cache/metrics.rs
  router/src/namespace_cache/sharded_cache.rs
  router/src/namespace_resolver.rs
  router/src/namespace_resolver/ns_autocreation.rs
  router/src/server/http.rs
Labels: kodiak: merge.method = 'merge'

#6859 feat: verified test output display for compactor
  compactor2/src/components/files_split/target_level_target_level_split.rs
  compactor2/src/test_util.rs
  compactor2/src/test_util/display.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6882 fix: partition-done metrics/logs
  compactor2/src/components/hardcoded.rs
Labels: automerge

#6883 fix: metric buckets
  compactor2/src/components/commit/metrics.rs
Labels: automerge

#6886 fix: `--compaction-process-once` should exit
  compactor2/src/compactor.rs
  compactor2/src/compactor_tests.rs
  compactor2/src/components/hardcoded.rs
  influxdb_iox/src/commands/run/compactor2.rs
Labels: automerge

#6877 feat: to prevent OOMs/crash/skip compaction, let u…
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/partition_filter/greater_size_matching_files.rs
  compactor2/src/components/partition_filter/mod.rs
Labels: automerge

#6880 feat: Do not skip partition based on num files and size until we reach compaction plan
  compactor2/src/compactor_tests.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/mod.rs
  compactor2/src/components/partition_filter/logging.rs
  compactor2/src/components/partition_filter/metrics.rs
  compactor2/src/components/report.rs
  compactor2/src/driver.rs
  compactor2/src/test_util.rs
Labels: automerge

#6891 chore: Update tests in compactor2 to use insta
  compactor2/src/components/files_split/target_level_target_level_split.rs
  compactor2/src/test_util.rs
  compactor2/src/test_util/display.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6892 chore(compactor): Update `target_level_upgrade_split` to use insta snapshots for file split verificiation
  compactor2/src/components/files_split/target_level_upgrade_split.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6864 fix: Implement EXPLAIN, ORDER BY and default ordering
  influxdb_iox/tests/query_tests2/cases.rs
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql.expected
  iox_query/src/plan/influxql/planner.rs
  iox_query/src/plan/influxql/rewriter.rs
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__explain-2.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__explain-3.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__explain-4.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__explain.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__time_range_in_where-10.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__time_range_in_where-2.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__time_range_in_where-4.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__time_range_in_where-5.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__time_range_in_where-6.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__time_range_in_where-7.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__time_range_in_where-8.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__time_range_in_where-9.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__time_range_in_where.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__simple_arithmetic_in_projection-2.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__simple_arithmetic_in_projection-3.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__simple_arithmetic_in_projection-4.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__simple_arithmetic_in_projection.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__single_measurement-2.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__single_measurement-3.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__single_measurement-4.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__single_measurement-5.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__single_measurement-6.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__single_measurement-7.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__single_measurement-8.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__single_measurement.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__unsupported_statements-10.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__unsupported_statements-4.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__unsupported_statements-5.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__unsupported_statements-6.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__unsupported_statements-7.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__unsupported_statements-8.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__unsupported_statements-9.snap
Labels: automerge, query/language/influxql

#6894 chore: add more insta snapshots for initial setup
  compactor2/src/components/files_split/target_level_non_overlap_split.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6887 feat: allow the compactor to process all known partitions
  clap_blocks/src/compactor2.rs
  compactor2/src/components/combos/unique_partitions.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/id_only_partition_filter/by_id.rs
  compactor2/src/components/partitions_source/catalog_all.rs
  compactor2/src/components/partitions_source/catalog_to_compact.rs
  compactor2/src/components/partitions_source/mod.rs
  compactor2/src/components/report.rs
  compactor2/src/config.rs
  compactor2/src/test_util.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
  ioxd_compactor2/src/lib.rs
Labels: automerge

#6906 refactor: avoid nested test modules
  compactor2/src/compactor_tests.rs
  compactor2/src/lib.rs
  compactor2/src/tests.rs
Labels: automerge

#6907 refactor: make `TestSetup` immutable
  compactor2/src/test_util.rs
  compactor2/src/tests.rs
Labels: automerge

#6904 fix(compactor): metric labels
  compactor2/src/components/partition_filter/metrics.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6893 chore: Update datafusion
  Cargo.lock
  Cargo.toml
  iox_query/src/exec/gapfill.rs
  iox_query/src/exec/gapfill/algo.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#6908 test: allow testing the compactor w/o any real data
  compactor2/src/components/df_plan_exec/mod.rs
  compactor2/src/components/df_plan_exec/noop.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/parquet_file_sink/dedicated.rs
  compactor2/src/components/parquet_file_sink/mock.rs
  compactor2/src/components/report.rs
  compactor2/src/components/scratchpad/mod.rs
  compactor2/src/components/scratchpad/noop.rs
  compactor2/src/config.rs
  compactor2/src/test_util.rs
  compactor2/src/tests.rs
  ioxd_compactor2/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6909 test(compactor): Improve file size display in compactor tests
  compactor2/src/components/files_split/target_level_non_overlap_split.rs
  compactor2/src/components/files_split/target_level_target_level_split.rs
  compactor2/src/components/files_split/target_level_upgrade_split.rs
  compactor2/src/test_util/display.rs
  compactor2/src/tests.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6449 fix: query annotations and params
  influxdb2_client/src/models/ast/dialect.rs
  influxdb2_client/src/models/query.rs
Labels: automerge

#6889 fix(ingester2): always maintain persist interval
  ingester2/Cargo.toml
  ingester2/src/wal/rotate_task.rs
  workspace-hack/Cargo.toml
Labels: kodiak: merge.method = 'merge', kafkaless

#6923 chore: gitignore pending insta snapshots
  .gitignore
Labels: automerge

#6922 refactor: introduce IR before creating actual DF plan
  compactor2/src/components/df_planner/logging.rs
  compactor2/src/components/df_planner/mod.rs
  compactor2/src/components/df_planner/panic.rs
  compactor2/src/components/df_planner/planner_v1.rs
  compactor2/src/components/df_planner/query_chunk.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/ir_planner/logging.rs
  compactor2/src/components/ir_planner/mod.rs
  compactor2/src/components/ir_planner/planner_v1.rs
  compactor2/src/components/mod.rs
  compactor2/src/components/report.rs
  compactor2/src/driver.rs
  compactor2/src/lib.rs
  compactor2/src/plan_ir.rs
Labels: automerge

#6925 feat: measure scratchpad store
  Cargo.lock
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/scratchpad/mod.rs
  compactor2/src/lib.rs
  compactor2/src/object_store/ignore_writes.rs
  compactor2/src/object_store/metrics.rs
  compactor2/src/object_store/mod.rs
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/src/commands/run/compactor2.rs
Labels: automerge

#6924 refactor(catalog): soft delete namespace column
  iox_catalog/migrations/20230207103859_namespace-soft-delete-column.sql
  iox_catalog/sqlite/migrations/20230207103944_namespace-soft-delete-column.sql
Labels: kodiak: merge.method = 'merge'

#6927 feat: add log around job semaphore and per-partition
  compactor2/src/driver.rs
Labels: automerge

#6910 test(compactor): show compactor working
  compactor2/src/test_util.rs
  compactor2/src/tests.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6930 refactor: `PartitionInfoSource`
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/mod.rs
  compactor2/src/components/partition_info_source/mod.rs
  compactor2/src/components/partition_info_source/sub_sources.rs
  compactor2/src/components/report.rs
  compactor2/src/driver.rs
Labels: automerge

#6926 docs(proto): ingester persist API strangeness
  generated_types/build.rs
  generated_types/protos/influxdata/iox/ingester/v1/persist.proto
  generated_types/protos/influxdata/iox/ingester/v1/write.proto
Labels: documentation, kodiak: merge.method = 'merge'

#6850 fix: Switch more tests over to the kafkaless architecture
  influxdb_iox/tests/end_to_end_cases/cli.rs
  influxdb_iox/tests/end_to_end_cases/error.rs
  influxdb_iox/tests/end_to_end_cases/namespace.rs
  influxdb_iox/tests/end_to_end_cases/querier.rs
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc.rs
  influxdb_iox/tests/end_to_end_cases/querier/multi_ingester.rs
  influxdb_iox/tests/end_to_end_cases/remote.rs
  influxdb_iox/tests/end_to_end_cases/schema.rs
  influxdb_iox/tests/query_tests2/framework.rs
  influxdb_iox/tests/query_tests2/sql_errors.rs
  test_helpers_end_to_end/src/client.rs
  test_helpers_end_to_end/src/config.rs
  test_helpers_end_to_end/src/mini_cluster.rs
  test_helpers_end_to_end/src/server_fixture.rs
  test_helpers_end_to_end/src/server_type.rs
  test_helpers_end_to_end/src/steps.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6913 fix: Consolidate ingester address specification
  clap_blocks/src/ingest_replica.rs
  clap_blocks/src/ingester_address.rs
  clap_blocks/src/lib.rs
  clap_blocks/src/querier.rs
  clap_blocks/src/router2.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ioxd_ingest_replica/src/lib.rs
  ioxd_querier/src/lib.rs
  ioxd_router/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6929 chore: Update datafusion again
  Cargo.lock
  Cargo.toml
  datafusion_util/src/config.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#6945 fix: `clap_blocks` clippy warning
  clap_blocks/src/ingester_address.rs
Labels: automerge

#6947 refactor(catalog): expose deleted_at on Namespace
  compactor2/src/test_util.rs
  data_types/src/lib.rs
  iox_catalog/src/mem.rs
  router/src/namespace_resolver/ns_autocreation.rs
Labels: kodiak: merge.method = 'merge'

#6932 feat(compactor): Implement ParquetFileSimulator and use it to show layout testing
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/parquet_file_sink/mock.rs
  compactor2/src/components/parquet_files_sink/dispatch.rs
  compactor2/src/components/parquet_files_sink/mod.rs
  compactor2/src/components/parquet_files_sink/simulator.rs
  compactor2/src/config.rs
  compactor2/src/plan_ir.rs
  compactor2/src/test_util.rs
  compactor2/src/test_util/display.rs
  compactor2/src/tests.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6936 test: Test with multiple ingesters, like in production
  influxdb_iox/tests/end_to_end_cases/ingester.rs
  influxdb_iox/tests/end_to_end_cases/querier.rs
  influxdb_iox/tests/end_to_end_cases/querier/multi_ingester.rs
  test_helpers_end_to_end/src/config.rs
  test_helpers_end_to_end/src/mini_cluster.rs
  test_helpers_end_to_end/src/steps.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6953 refactor: move test builders out of compactor2 code
  compactor/src/cold.rs
  compactor/src/compact.rs
  compactor/src/garbage_collector.rs
  compactor/src/hot.rs
  compactor/src/lib.rs
  compactor/src/parquet_file.rs
  compactor/src/parquet_file_combining.rs
  compactor/src/parquet_file_lookup.rs
  compactor/src/query.rs
  compactor/src/warm.rs
  compactor2/src/components/commit/logging.rs
  compactor2/src/components/commit/metrics.rs
  compactor2/src/components/commit/mock.rs
  compactor2/src/components/divide_initial/single_branch.rs
  compactor2/src/components/file_filter/level_range.rs
  compactor2/src/components/level_exist/one_level.rs
  compactor2/src/components/partition_files_source/mock.rs
  compactor2/src/components/partition_filter/greater_matching_files.rs
  compactor2/src/components/partition_filter/greater_size_matching_files.rs
  compactor2/src/components/partition_filter/has_files.rs
  compactor2/src/components/partition_filter/has_matching_file.rs
  compactor2/src/components/partition_filter/logging.rs
  compactor2/src/components/partition_filter/max_files.rs
  compactor2/src/components/partition_filter/max_parquet_bytes.rs
  compactor2/src/components/partition_filter/metrics.rs
  compactor2/src/components/partition_source/logging.rs
  compactor2/src/components/partition_source/metrics.rs
  compactor2/src/components/partition_source/mock.rs
  compactor2/src/components/round_split/all_now.rs
  compactor2/src/components/skipped_compactions_source/mock.rs
  compactor2/src/components/tables_source/mock.rs
  compactor2/src/components/target_level_chooser/all_at_once.rs
  compactor2/src/components/target_level_chooser/target_level.rs
  compactor2/src/file_group.rs
  compactor2/src/test_util.rs
  compactor2/src/test_util/display.rs
  compactor2/src/tests.rs
  iox_tests/src/builders.rs
  iox_tests/src/catalog.rs
  iox_tests/src/lib.rs
  ioxd_querier/src/rpc/namespace.rs
  querier/src/cache/namespace.rs
  querier/src/cache/parquet_file.rs
  querier/src/cache/partition.rs
  querier/src/cache/processed_tombstones.rs
  querier/src/cache/tombstones.rs
  querier/src/database.rs
  querier/src/ingester/mod.rs
  querier/src/namespace/mod.rs
  querier/src/namespace/query_access.rs
  querier/src/namespace/test_util.rs
  querier/src/parquet/mod.rs
  querier/src/table/mod.rs
  querier/src/table/test_util.rs
  router/src/dml_handlers/retention_validator.rs
  router/src/dml_handlers/schema_validation.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6911 feat: partial implementation of gap filling operator
  influxdb_iox/tests/query_tests2/cases.rs
  influxdb_iox/tests/query_tests2/cases/in/gapfill.sql
  influxdb_iox/tests/query_tests2/cases/in/gapfill.sql.expected
  influxdb_iox/tests/query_tests2/setups.rs
  iox_query/src/exec/gapfill.rs
  iox_query/src/exec/gapfill/algo.rs
  iox_query/src/exec/gapfill/builder.rs
  iox_query/src/exec/gapfill/series.rs
Labels: automerge

#6954 chore: Update display, and add initial scenario tests
  compactor2/src/test_util/display.rs
  compactor2/src/tests.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6957 fix: Remove the use of write buffer config from import schema command
  import/src/aggregate_tsm_schema/update_catalog.rs
  influxdb_iox/src/commands/import/schema.rs
Labels: automerge

#6958 chore: Update datafusion again
  Cargo.lock
  Cargo.toml
  influxdb_iox/tests/query_tests2/cases/in/dedup_and_predicates_parquet.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/dedup_and_predicates_parquet_ingester.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_ingester.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_parquet.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_parquet_many.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/gapfill.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/pushdown.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/retention.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/several_chunks.sql.expected
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#6968 chore: add extra debugging to help track down jdbc_client failures
  influxdb_iox/tests/jdbc_client/jdbc_client
Labels: automerge, kodiak: merge.method = 'squash'

#6952 feat: namespace soft-delete support
  compactor/src/compact.rs
  compactor2/src/components/namespaces_source/catalog.rs
  import/src/aggregate_tsm_schema/update_catalog.rs
  influxdb_iox/src/commands/remote/partition.rs
  ingester/src/buffer_tree/namespace/name_resolver.rs
  ingester/tests/common/mod.rs
  ingester2/src/buffer_tree/namespace/name_resolver.rs
  ingester2/src/persist/mod.rs
  ingester2/src/server/grpc/persist.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
  iox_tests/src/catalog.rs
  querier/src/cache/namespace.rs
  querier/src/database.rs
  querier/src/namespace/test_util.rs
  querier/src/table/test_util.rs
  router/src/dml_handlers/retention_validator.rs
  router/src/dml_handlers/schema_validation.rs
  router/src/namespace_resolver.rs
  router/src/namespace_resolver/ns_autocreation.rs
  router/tests/common/mod.rs
  router/tests/grpc.rs
  router/tests/http.rs
  service_grpc_catalog/src/lib.rs
  service_grpc_namespace/src/lib.rs
  service_grpc_schema/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6956 fix: Port router unit tests to the RPC write path
  router/src/dml_handlers/rpc_write.rs
  router/src/dml_handlers/rpc_write/client.rs
  router/tests/common/mod.rs
  router/tests/http.rs
Labels: automerge

#6971 test(router): router restarts + caching effects
  router/tests/common/mod.rs
  router/tests/grpc.rs
Labels: kodiak: merge.method = 'merge'

#6946 refactor: extract `FileClassifer` component
  compactor2/src/components/file_classifier/all_at_once.rs
  compactor2/src/components/file_classifier/logging.rs
  compactor2/src/components/file_classifier/mod.rs
  compactor2/src/components/file_classifier/split_based.rs
  compactor2/src/components/files_split/all_at_once_non_overlap_split.rs
  compactor2/src/components/files_split/all_at_once_target_level_split.rs
  compactor2/src/components/files_split/all_at_once_upgrade_split.rs
  compactor2/src/components/files_split/mod.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/mod.rs
  compactor2/src/components/report.rs
  compactor2/src/components/target_level_chooser/all_at_once.rs
  compactor2/src/components/target_level_chooser/mod.rs
  compactor2/src/driver.rs
  compactor2/src/file_classification.rs
  compactor2/src/lib.rs
Labels: automerge

#6969 chore: remove dead code
  arrow_util/src/util.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6955 chore: Add some comments about fatal panic rationale
  influxdb_iox/src/commands/run/ingester2.rs
  influxdb_iox/src/commands/run/router2.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6977 chore: Layout tests with `TargetLevel` algorithm + update display
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/parquet_file_sink/mod.rs
  compactor2/src/components/parquet_files_sink/mod.rs
  compactor2/src/components/report.rs
  compactor2/src/config.rs
  compactor2/src/lib.rs
  compactor2/src/plan_ir.rs
  compactor2/tests/integration.rs
  compactor2_test_utils/src/lib.rs
  compactor2_test_utils/src/simulator.rs
  ioxd_compactor2/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6980 chore: `cargo update`
  Cargo.lock
  workspace-hack/Cargo.toml
Labels: automerge

#6970 docs: explain new physical plan construction
  docs/physical_plan_construction.md
Labels: automerge

#6983 chore: ignore `RUSTSEC-2022-0090`
  deny.toml
Labels: automerge

#6978 feat: skip partitions of wide tables
  clap_blocks/src/compactor2.rs
  compactor2/src/components/df_planner/panic.rs
  compactor2/src/components/file_classifier/all_at_once.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/parquet_file_sink/dedicated.rs
  compactor2/src/components/parquet_file_sink/mock.rs
  compactor2/src/components/partition_filter/and.rs
  compactor2/src/components/partition_filter/greater_matching_files.rs
  compactor2/src/components/partition_filter/greater_size_matching_files.rs
  compactor2/src/components/partition_filter/has_files.rs
  compactor2/src/components/partition_filter/has_matching_file.rs
  compactor2/src/components/partition_filter/logging.rs
  compactor2/src/components/partition_filter/max_files.rs
  compactor2/src/components/partition_filter/max_num_columns.rs
  compactor2/src/components/partition_filter/max_parquet_bytes.rs
  compactor2/src/components/partition_filter/metrics.rs
  compactor2/src/components/partition_filter/mod.rs
  compactor2/src/components/partition_filter/never_skipped.rs
  compactor2/src/components/partition_filter/or.rs
  compactor2/src/components/report.rs
  compactor2/src/config.rs
  compactor2/src/driver.rs
  compactor2/src/partition_info.rs
  compactor2/src/test_utils.rs
  compactor2_test_utils/src/lib.rs
  data_types/src/lib.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ioxd_compactor2/src/lib.rs
Labels: automerge

#6982 refactor: replace IF-statement w/ optimizer rule
  Cargo.lock
  iox_query/Cargo.toml
  iox_query/src/exec/context.rs
  iox_query/src/lib.rs
  iox_query/src/logical_optimizer/mod.rs
  iox_query/src/physical_optimizer/mod.rs
  iox_query/src/physical_optimizer/test_util.rs
  iox_query/src/physical_optimizer/union/mod.rs
  iox_query/src/physical_optimizer/union/one_union.rs
  iox_query/src/provider.rs
  iox_query/src/provider/physical.rs
  iox_query/src/test.rs
Labels: automerge

#6981 feat(compactor): Add more tests, improve sizes to simulator run display more
  compactor2/tests/integration.rs
  compactor2/tests/layouts/mod.rs
  compactor2_test_utils/src/display.rs
  compactor2_test_utils/src/lib.rs
  compactor2_test_utils/src/simulator.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6988 test: more compactor layout tests
  clap_blocks/src/compactor2.rs
  compactor2/src/components/partition_filter/or.rs
  compactor2/tests/layouts/mod.rs
Labels: automerge

#6987 feat: Add logging of commands sent via the `influxdb_iox storage` command
  influxdb_iox/src/commands/storage.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6986 feat: allow gap filling to produce multiple batches
  iox_query/src/exec/gapfill.rs
  iox_query/src/exec/gapfill/algo.rs
  iox_query/src/exec/gapfill/builder.rs
  iox_query/src/exec/gapfill/series.rs
Labels: automerge

#6985 feat: add compaction level to commit metrics
  Cargo.lock
  compactor2/Cargo.toml
  compactor2/src/components/commit/metrics.rs
  data_types/src/lib.rs
  iox_tests/src/builders.rs
Labels: automerge

#6992 refactor: SequenceNumberSet::as_bytes -> to_bytes
  data_types/src/sequence_number_set.rs
Labels: kodiak: merge.method = 'merge'

#7005 test: Add another layout test to compactor
  compactor2/tests/layouts/mod.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6998 refactor: `group_potential_duplicates` cannot fail
  iox_query/src/provider.rs
  iox_query/src/provider/overlap.rs
Labels: automerge

#6999 feat: `RecordBatchesExec` remembers chunks
  iox_query/src/lib.rs
  iox_query/src/provider/physical.rs
  iox_query/src/provider/record_batch_exec.rs
Labels: automerge

#7000 feat: remember `QueryChunk` for every parquet file
  iox_query/src/provider/physical.rs
Labels: automerge

#7002 test: Write an e2e test of namespace soft-deletion
  influxdb_iox/tests/end_to_end_cases/namespace.rs
  influxdb_iox_client/src/client/namespace.rs
  test_helpers_end_to_end/src/mini_cluster.rs
  test_helpers_end_to_end/src/steps.rs
Labels: automerge

#7011 fix: Fails to execute RPC query when predicates refer to columns with periods
  iox_query/src/frontend/influxrpc.rs
  predicate/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash', query/api/storage-grpc

#7014 refactor: move GapFillParams to its own module
  iox_query/src/exec/gapfill.rs
  iox_query/src/exec/gapfill/algo.rs
  iox_query/src/exec/gapfill/builder.rs
  iox_query/src/exec/gapfill/params.rs
  iox_query/src/exec/gapfill/series.rs
Labels: automerge

#6997 chore: Update datafusion
  Cargo.lock
  Cargo.toml
  influxdb_iox/tests/query_tests2/cases/in/dedup_and_predicates_parquet.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/dedup_and_predicates_parquet_ingester.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_ingester.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_parquet.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/gapfill.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/retention.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/several_chunks.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/two_chunks.sql.expected
  iox_query/src/exec/gapfill.rs
  iox_query/src/physical_optimizer/test_util.rs
  iox_query/src/provider.rs
  iox_query/src/test.rs
  querier/src/namespace/query_access.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#7009 test: Ingester integration tests that can have a little a internal state
  Cargo.lock
  ingester2/Cargo.toml
  ingester2/src/init.rs
  ingester2/src/server/grpc.rs
  ingester2/tests/common/mod.rs
  ingester2/tests/write.rs
  ioxd_ingester2/Cargo.toml
  ioxd_ingester2/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7007 feat: Compact partition with many L0 files
  clap_blocks/src/compactor2.rs
  compactor2/src/components/divide_initial/mod.rs
  compactor2/src/components/divide_initial/multiple_branches.rs
  compactor2/src/components/divide_initial/single_branch.rs
  compactor2/src/components/file_classifier/all_at_once.rs
  compactor2/src/components/file_classifier/split_based.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/ir_planner/planner_v1.rs
  compactor2/src/components/partition_filter/and.rs
  compactor2/src/components/partition_filter/max_files.rs
  compactor2/src/components/partition_filter/mod.rs
  compactor2/src/components/partition_filter/or.rs
  compactor2/src/components/report.rs
  compactor2/src/components/round_info_source/mod.rs
  compactor2/src/components/round_split/all_now.rs
  compactor2/src/components/round_split/many_files.rs
  compactor2/src/components/round_split/mod.rs
  compactor2/src/config.rs
  compactor2/src/driver.rs
  compactor2/src/round_info.rs
  compactor2/tests/integration.rs
  compactor2/tests/layouts/mod.rs
  compactor2_test_utils/src/lib.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  iox_tests/src/builders.rs
  ioxd_compactor2/src/lib.rs
Labels: automerge

#7013 test: `chunks_to_physical_nodes`
  iox_query/src/lib.rs
  iox_query/src/provider/physical.rs
  iox_query/src/test.rs
  parquet_file/src/storage.rs
Labels: automerge

#7017 test: add a test that have over 2 times of limit files per plan
  compactor2/tests/layouts/mod.rs
  ingester2/tests/common/mod.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6989 feat: streaming parquet --> line protocol conversion
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/debug/parquet_to_lp.rs
  influxdb_iox/src/commands/write.rs
  parquet_to_line_protocol/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#7018 feat: extract chunks from phys. plan
  iox_query/src/physical_optimizer/chunk_extraction.rs
  iox_query/src/physical_optimizer/mod.rs
  iox_query/src/provider.rs
  iox_query/src/provider/physical.rs
  iox_query/src/provider/record_batch_exec.rs
Labels: automerge

#7022 docs(compactor2): Update compactor2 config parameter documentation
  clap_blocks/src/compactor2.rs
Labels: automerge, kodiak: merge.method = 'squash'

#7012 fix: Refactor storage to properly handle binary and text meta tags
  influxdb_iox/src/commands/storage.rs
  influxdb_iox/src/commands/storage/request.rs
  influxdb_iox/src/commands/storage/response.rs
Labels: kind/bug, automerge

#7027 feat: Implement all-in-one local persistence testing mode
  Cargo.lock
  README.md
  clap_blocks/src/catalog_dsn.rs
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/run/all_in_one.rs
  trogging/src/cli.rs
  trogging/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#7031 feat: Rewrite logical expression to match InfluxQL behaviour
  influxdb_influxql_parser/src/expression/arithmetic.rs
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql.expected
  iox_query/src/plan/influxql.rs
  iox_query/src/plan/influxql/expr_type_evaluator.rs
  iox_query/src/plan/influxql/planner.rs
  iox_query/src/plan/influxql/planner_rewrite_expression.rs
  iox_query/src/plan/influxql/planner_time_range_expression.rs
  iox_query/src/plan/influxql/rewriter.rs
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__explain-2.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__explain-3.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__explain-4.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__explain.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__time_range_in_where-10.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__time_range_in_where-2.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__time_range_in_where-3.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__time_range_in_where-4.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__time_range_in_where-5.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__time_range_in_where-6.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__time_range_in_where-7.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__time_range_in_where-8.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__time_range_in_where-9.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select__time_range_in_where.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__simple_arithmetic_in_projection-2.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__simple_arithmetic_in_projection-3.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__simple_arithmetic_in_projection-4.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__simple_arithmetic_in_projection.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__single_measurement-2.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__single_measurement-3.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__single_measurement-4.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__single_measurement-5.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__single_measurement-6.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__single_measurement-7.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__single_measurement-8.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__select_raw__single_measurement.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__unsupported_statements-2.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__unsupported_statements-3.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__unsupported_statements-4.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__unsupported_statements-5.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__unsupported_statements-6.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__unsupported_statements-7.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__unsupported_statements-8.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__unsupported_statements-9.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__planner__test__unsupported_statements.snap
  iox_query/src/plan/influxql/test_utils.rs
  iox_query/src/plan/influxql/util.rs
  iox_query/src/plan/influxql/var_ref.rs
  iox_query/src/test.rs
Labels: automerge, query/language/influxql

#7019 refactor: remove `TaskConfig` param from `chunks_to_physical_nodes`
  iox_query/src/physical_optimizer/chunk_extraction.rs
  iox_query/src/provider.rs
  iox_query/src/provider/physical.rs
Labels: automerge

#7039 chore: update heappy to `1d6ac77a4026fffce8680a7b31a9f6e9859b5e73`
  Cargo.lock
  ioxd_common/Cargo.toml
Labels: automerge

#7036 test(ingester): helper macros
  ingester2/src/test_util.rs
Labels: kodiak: merge.method = 'merge'

#7044 chore: update TODO comment about all in one mode
  influxdb_iox/src/commands/run/all_in_one.rs
Labels: automerge, kodiak: merge.method = 'squash'

#7023 fix: Use shard_id in fewer protobuf serializations
  generated_types/protos/influxdata/iox/catalog/v1/parquet_file.proto
  generated_types/protos/influxdata/iox/catalog/v1/service.proto
  influxdb_iox/src/commands/remote/partition.rs
  influxdb_iox/tests/end_to_end_cases/remote.rs
  ingest_replica/src/cache.rs
  ingester/src/data.rs
  ingester2/src/init.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
  service_grpc_catalog/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7038 refactor: Make InfluxQL planning sync
  iox_query/src/frontend/influxql.rs
  iox_query/src/plan/influxql.rs
  iox_query/src/plan/influxql/expr_type_evaluator.rs
  iox_query/src/plan/influxql/field_mapper.rs
  iox_query/src/plan/influxql/planner.rs
  iox_query/src/plan/influxql/rewriter.rs
  iox_query/src/plan/influxql/test_utils.rs
  iox_query/src/plan/influxql/util.rs
  service_common/src/planner.rs
  service_grpc_flight/src/lib.rs
Labels: automerge, query/language/influxql

#7045 chore: Update DataFusion and `arrow` / `arrow-flight` / `parquet` to `33.0.0`
  Cargo.lock
  Cargo.toml
  arrow_util/src/display.rs
  arrow_util/src/optimize.rs
  influxdb_iox/tests/end_to_end_cases/cli.rs
  influxdb_iox/tests/query_tests2/cases/in/aggregates.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/basic.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/dedup_and_predicates_parquet.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/dedup_and_predicates_parquet_ingester.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/different_tag_sets.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_ingester.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_parquet.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_parquet_many.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/gapfill.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql.expected
  influxdb_iox/tests/query_tests2/cases/in/periods.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/pushdown.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/retention.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/schema_merge.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/selectors.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/several_chunks.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/timestamps.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/two_chunks_missing_columns.sql.expected
  ingester/src/buffer_tree/partition.rs
  ingester/src/buffer_tree/partition/buffer/state_machine.rs
  ingester/src/compact.rs
  ingester/src/querier_handler.rs
  ingester/tests/write.rs
  ingester2/src/buffer_tree/partition.rs
  ingester2/src/buffer_tree/partition/buffer/state_machine.rs
  ingester2/src/buffer_tree/root.rs
  ingester2/src/persist/compact.rs
  ingester2/tests/write.rs
  iox_query/src/exec/seriesset/converter.rs
  iox_query/src/provider/deduplicate.rs
  iox_query/src/provider/deduplicate/algo.rs
  mutable_batch/tests/extend_range.rs
  mutable_batch/tests/writer.rs
  mutable_batch_lp/src/lib.rs
  mutable_batch_pb/src/decode.rs
  mutable_batch_pb/tests/encode.rs
  querier/src/namespace/query_access.rs
  querier/src/table/mod.rs
  query_functions/src/selectors.rs
  workspace-hack/Cargo.toml
Labels: automerge

#7028 fix: Understandable compactor2 config report
  compactor2/src/components/report.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
  iox_query/src/exec.rs
  iox_time/src/lib.rs
  parquet_file/src/storage.rs
Labels: automerge, kodiak: merge.method = 'squash'

#7043 refactor: better panic message for column lookup
  ingester2/src/persist/worker.rs
Labels: kodiak: merge.method = 'merge'

#7046 perf(wal): dedicated file writer I/O thread
  wal/src/lib.rs
  wal/src/writer_thread.rs
Labels: kodiak: merge.method = 'merge'

#7037 feat: streaming implementation of gap filling
  influxdb_iox/tests/query_tests2/cases/in/gapfill.sql
  influxdb_iox/tests/query_tests2/cases/in/gapfill.sql.expected
  iox_query/src/exec/gapfill.rs
  iox_query/src/exec/gapfill/algo.rs
  iox_query/src/exec/gapfill/series.rs
  iox_query/src/exec/gapfill/stream.rs
Labels: automerge

#7047 refactor: n_threads and n_target_partitions are non-zero
  Cargo.lock
  clap_blocks/src/compactor2.rs
  clap_blocks/src/querier.rs
  compactor/src/parquet_file_combining.rs
  executor/src/lib.rs
  influxdb_iox/src/commands/compactor.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/src/commands/run/compactor.rs
  influxdb_iox/src/commands/run/compactor2.rs
  influxdb_iox/src/commands/run/ingest_replica.rs
  influxdb_iox/src/commands/run/ingester.rs
  influxdb_iox/src/commands/run/ingester2.rs
  influxdb_iox/src/commands/run/querier.rs
  iox_query/src/exec.rs
  iox_query/src/exec/context.rs
  iox_tests/Cargo.toml
  iox_tests/src/catalog.rs
Labels: automerge

#7052 fix: do not panic for unsupported expressions
  iox_query/src/frontend/influxrpc.rs
  predicate/src/lib.rs
  predicate/src/rpc_predicate.rs
  predicate/src/rpc_predicate/field_rewrite.rs
  service_grpc_influxrpc/src/expr.rs
  service_grpc_influxrpc/src/service.rs
Labels: automerge

#7053 refactor(iox): log query errors
  ingester2/src/server/grpc/query.rs
Labels: kodiak: merge.method = 'merge'
