Repository influxdata/influxdb_iox, pull requests merged in 2023-08, with the labels that each got.

#8377 refactor(influxql): make MOVING_AVERAGE a user-defined window function
  iox_query_influxql/src/plan/mod.rs
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/udaf.rs
  iox_query_influxql/src/window.rs
  iox_query_influxql/src/window/moving_average.rs
Labels: automerge

#8373 feat: use single per-migration txn when possible
  iox_catalog/src/migrate.rs
Labels: automerge

#8380 feat(router): Expose `num_probes` request count used to health-check ingesters as config option
  clap_blocks/src/router.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ioxd_router/src/lib.rs
  router/src/dml_handlers/rpc_write.rs
  router/src/dml_handlers/rpc_write/balancer.rs
  router/src/dml_handlers/rpc_write/circuit_breaker.rs
  router/src/dml_handlers/rpc_write/circuit_breaking_client.rs
  router/tests/common/mod.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8375 feat: add sort_key_ids as array of bigints into catalog partition
  iox_catalog/migrations/20230731143030_add_column_sort_key_array_ids.sql
Labels: automerge

#8379 feat(gossip): schema diff message proto
  generated_types/build.rs
  generated_types/protos/influxdata/iox/gossip/v1/message.proto
  generated_types/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8384 feat: add sort_key_ids into sqlite catalog
  iox_catalog/sqlite/migrations/20230731143030_add_column_sort_key_array_ids.sql
Labels: automerge

#8387 docs: explain migration transaction handling
  iox_catalog/src/migrate.rs
Labels: automerge

#8382 feat(router): schema gossip skeleton
  router/src/gossip/dispatcher.rs
  router/src/gossip/handle.rs
  router/src/gossip/mod.rs
  router/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8388 refactor: migration checksum type
  Cargo.lock
  iox_catalog/Cargo.toml
  iox_catalog/src/migrate.rs
  iox_catalog/src/postgres.rs
Labels: automerge

#8391 refactor: expose partition template protos
  data_types/src/columns.rs
  data_types/src/partition_template.rs
  gossip/src/builder.rs
  gossip/src/handle.rs
Labels: kodiak: merge.method = 'merge'

#8392 perf(router): Add benchmark for additions to namespace schema cache
  router/Cargo.toml
  router/benches/namespace_schema_cache.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8389 refactor: use errors instead of panic
  iox_catalog/src/migrate.rs
  iox_catalog/src/postgres.rs
Labels: automerge

#8390 chore: Update DataFusion pin
  Cargo.lock
  Cargo.toml
  influxdb_iox/tests/query_tests/cases/in/aggregates.sql.expected
  influxdb_iox/tests/query_tests/cases/in/aggregates_with_nulls.sql.expected
  influxdb_iox/tests/query_tests/cases/in/basic.sql.expected
  influxdb_iox/tests/query_tests/cases/in/duplicates_ingester.sql.expected
  influxdb_iox/tests/query_tests/cases/in/duplicates_parquet.sql.expected
  influxdb_iox/tests/query_tests/cases/in/duplicates_parquet_20.sql.expected
  influxdb_iox/tests/query_tests/cases/in/duplicates_parquet_20_and_ingester.sql.expected
  influxdb_iox/tests/query_tests/cases/in/gapfill.sql.expected
  predicate/src/rpc_predicate/rewrite.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#8393 feat: NamespaceSchemaGossip cache decorator
  router/src/gossip/mod.rs
  router/src/gossip/namespace_cache.rs
  router/src/namespace_cache/memory.rs
Labels: kodiak: merge.method = 'merge'

#8398 chore(doc): fix typo in partition template example
  docs/cli-create-namespace-table.md
Labels: automerge

#8399 chore: remove dead code compute_sort_key_for_chunks
  iox_query/src/lib.rs
Labels: automerge

#8405 feat: send-side schema gossip implementation
  router/src/gossip/handle.rs
  router/src/gossip/mock_schema_broadcast.rs
  router/src/gossip/mod.rs
  router/src/gossip/schema_change_observer.rs
  router/src/gossip/traits.rs
Labels: kodiak: merge.method = 'merge'

#8408 perf(ingester): catalog bloom filter for partition IDs
  Cargo.lock
  data_types/src/partition.rs
  ingester/Cargo.toml
  ingester/src/buffer_tree/partition/resolver/mod.rs
  ingester/src/buffer_tree/partition/resolver/old_filter.rs
Labels: kodiak: merge.method = 'merge'

#8409 feat(router): intra-cluster schema diff gossiping
  ioxd_router/src/lib.rs
  router/src/gossip/mod.rs
  router/src/gossip/namespace_cache.rs
  router/src/namespace_cache.rs
  router/src/server.rs
Labels: kodiak: merge.method = 'merge'

#8410 chore(compactor): move divide & branches to RoundInfo calculation
  compactor/src/components/round_info_source/mod.rs
  compactor/src/driver.rs
Labels: automerge

#8394 feat: allow fixing migrations
  iox_catalog/src/migrate.rs
Labels: automerge

#8406 refactor: simplify code, harden PG locking
  iox_catalog/src/migrate.rs
Labels: automerge

#8407 feat: post-migration sanity checks
  iox_catalog/src/migrate.rs
Labels: automerge

#8414 feat: retry failed migrations
  iox_catalog/README.md
  iox_catalog/src/migrate.rs
Labels: automerge

#8415 feat: harden migration version checks
  iox_catalog/src/migrate.rs
Labels: automerge

#8433 feat(influxql): minimal SHOW RETENTION POLICIES implementation
  influxdb_iox/tests/query_tests/cases/in/influxql_metadata.influxql
  influxdb_iox/tests/query_tests/cases/in/influxql_metadata.influxql.expected
  iox_query_influxql/src/plan/planner.rs
Labels: automerge

#8416 fix: `O(n^2)` delete handling in LRU
  Cargo.lock
  cache_system/Cargo.toml
  cache_system/src/addressable_heap.rs
  cache_system/src/backend/policy/lru.rs
  cache_system/src/resource_consumption.rs
  querier/src/cache/ram.rs
Labels: automerge

#8434 feat: static migrations checks
  .circleci/config.yml
  iox_catalog/check_linear_migrations.sh
Labels: automerge

#8447 chore: Update DataFusion
  Cargo.lock
  Cargo.toml
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/util_copy.rs
  iox_query_influxrpc/src/lib.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#8423 feat: push sort through union
  iox_query/src/physical_optimizer/sort/mod.rs
  iox_query/src/physical_optimizer/sort/push_sort_through_union.rs
Labels: automerge, kodiak: merge.method = 'squash'

#8455 refactor(flightsql): Use upstream implementation of XdbcTypeInfo builder, support filter by datatype
  flightsql/src/planner.rs
  flightsql/src/xdbc_type_info/mod.rs
  flightsql/src/xdbc_type_info/value.rs
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
Labels: automerge, kodiak: merge.method = 'squash'

#8451 refactor(influxql): remove `copy_with_replacement` and use upstream API
  iox_query_influxql/src/plan/mod.rs
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/udf.rs
  iox_query_influxql/src/plan/util.rs
  iox_query_influxql/src/plan/util_copy.rs
Labels: automerge, kodiak: merge.method = 'squash'

#8446 chore(ingester): Add `IngestStateError::DiskFull`
  ingester/src/ingest_state.rs
  ingester/src/server/grpc/rpc_write.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8457 test: more automatic tests for migrations
  iox_catalog/src/migrate.rs
  iox_catalog/src/postgres.rs
Labels: automerge

#8452 chore: Update `datafusion` / `arrow` / `parquet` to `45.0.0`
  Cargo.lock
  Cargo.toml
  iox_query_influxql/src/window/difference.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#8458 fix: avoid tracing flood
  cache_system/src/backend/policy/remove_if.rs
  querier/src/cache/partition.rs
Labels: automerge

#8453 refactor(flightsql): Use upstream `SqlInfoData` implementation
  flightsql/src/planner.rs
  flightsql/src/sql_info/mod.rs
  flightsql/src/sql_info/value.rs
Labels: automerge, kodiak: merge.method = 'squash'

#8450 fix: make concurrent index creations idempotent
  iox_catalog/check_linear_migrations.sh
  iox_catalog/migrations/20230524151854_add_parquet_file_table_and_deleted_index.sql
  iox_catalog/migrations/20230530132809_add_parquet_file_partition_and_deleted_index.sql
  iox_catalog/migrations/20230707195110_add_created_at_index.sql
  iox_catalog/migrations/20230710141740_partition_hash_id_index.sql
Labels: automerge

#8465 refactor: replace `Predicate` w/ `&[Expr]` in querier internals
  iox_query/src/provider.rs
  iox_query/src/pruning.rs
  predicate/src/lib.rs
  querier/src/ingester/mod.rs
  querier/src/ingester/test_util.rs
  querier/src/namespace/query_access.rs
  querier/src/table/mod.rs
  querier/src/table/query_access/mod.rs
Labels: automerge

#8460 chore: Update DataFusion
  Cargo.lock
  Cargo.toml
  iox_query/src/physical_optimizer/sort/push_sort_through_union.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#8468 refactor: remove `Predicate` usage from `QueryNamespace`
  iox_query/src/lib.rs
  iox_query/src/test.rs
  iox_query_influxrpc/src/lib.rs
  querier/src/namespace/query_access.rs
Labels: automerge

#8462 feat: fill catalog `sort_key_ids` for partitions with coming data
  compactor_test_utils/src/lib.rs
  data_types/src/columns.rs
  data_types/src/partition.rs
  generated_types/protos/influxdata/iox/catalog/v1/service.proto
  import_export/src/file/import.rs
  ingester/src/buffer_tree/partition.rs
  ingester/src/buffer_tree/partition/resolver/cache.rs
  ingester/src/buffer_tree/partition/resolver/old_filter.rs
  ingester/src/buffer_tree/partition/resolver/sort_key.rs
  ingester/src/persist/mod.rs
  ingester/src/persist/worker.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
  iox_tests/src/builders.rs
  iox_tests/src/catalog.rs
  querier/src/cache/partition.rs
  querier/src/parquet/mod.rs
  service_grpc_catalog/src/lib.rs
Labels: automerge

#8443 feat: gRPC interface for ingester->querier v2
  Cargo.lock
  ingester_query_grpc/Cargo.toml
  ingester_query_grpc/build.rs
  ingester_query_grpc/protos/influxdata/iox/ingester/v2/query.proto
  ingester_query_grpc/src/lib.rs
Labels: automerge

#8473 refactor: remove LIST operations on cached object store
  querier/src/cache/object_store.rs
Labels: automerge

#8474 refactor: decouple runtimes in `CachedObjectStore`
  querier/src/cache/mod.rs
  querier/src/cache/object_store.rs
Labels: automerge

#8475 feat: Just the querier changes needed for using the bloom filter to avoid catalog requests in the ingester
  querier/src/table/mod.rs
  querier/src/table/test_util.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8478 fix: compactor simulator math error creates 0 byte files
  compactor/tests/layouts/backfill.rs
  compactor/tests/layouts/common_use_cases.rs
  compactor/tests/layouts/core.rs
  compactor/tests/layouts/created_at.rs
  compactor/tests/layouts/knobs.rs
  compactor/tests/layouts/large_files.rs
  compactor/tests/layouts/large_overlaps.rs
  compactor/tests/layouts/many_files.rs
  compactor/tests/layouts/stuck.rs
  compactor_test_utils/src/simulator.rs
Labels: automerge

#8492 feat: expose DataFusion mem pool metrics
  iox_query/src/exec.rs
  iox_query/src/exec/metrics.rs
Labels: automerge

#8454 refactor(router): Revert configurable health-check `ERROR_WINDOW`
  clap_blocks/src/router.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ioxd_router/src/lib.rs
  router/src/dml_handlers/rpc_write.rs
  router/src/dml_handlers/rpc_write/balancer.rs
  router/src/dml_handlers/rpc_write/circuit_breaker.rs
  router/src/dml_handlers/rpc_write/circuit_breaking_client.rs
  router/tests/common/mod.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8493 feat: track why bytes are written in compactor simulator
  compactor/tests/layouts/backfill.rs
  compactor/tests/layouts/mod.rs
  compactor/tests/layouts/stuck.rs
  compactor_test_utils/src/lib.rs
  compactor_test_utils/src/simulator.rs
Labels: automerge

#8508 refactor: extract InfluxRPC-specific code to `iox_query_influxrpc` (part 1)
  Cargo.lock
  iox_query/src/frontend.rs
  iox_query/src/frontend/common.rs
  iox_query/src/frontend/reorg.rs
  iox_query/src/lib.rs
  iox_query/src/provider.rs
  iox_query/src/util.rs
  iox_query_influxrpc/Cargo.toml
  iox_query_influxrpc/src/lib.rs
  iox_query_influxrpc/src/missing_columns.rs
  iox_query_influxrpc/src/scan_plan.rs
Labels: automerge

#8501 chore: Make it clear there is only a single DataFusion memory pool
  iox_query/src/exec.rs
  iox_query/src/exec/metrics.rs
Labels: automerge, kodiak: merge.method = 'squash'

#8513 fix: do not panic in Influx selectors
  query_functions/src/selectors.rs
  query_functions/src/selectors/internal.rs
Labels: automerge

#8516 fix: Clean up some tiny things in import-export
  import_export/src/file/import.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8412 feat: Use the bloom filter to reduce ingester catalog queries, Luke
  ingester/src/buffer_tree/partition.rs
  ingester/src/buffer_tree/partition/resolver/cache.rs
  ingester/src/buffer_tree/partition/resolver/mod.rs
  ingester/src/buffer_tree/partition/resolver/old_filter.rs
  ingester/src/buffer_tree/partition/resolver/sort_key.rs
  ingester/src/init.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
  test_helpers_end_to_end/src/mini_cluster.rs
  test_helpers_end_to_end/src/steps.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8489 feat: read null sort_key_ids
  data_types/src/columns.rs
  data_types/src/partition.rs
  influxdb_iox/tests/end_to_end_cases/all_in_one.rs
  ingester/src/buffer_tree/partition.rs
  ingester/src/buffer_tree/partition/resolver/cache.rs
  ingester/src/buffer_tree/partition/resolver/old_filter.rs
  ingester/src/buffer_tree/partition/resolver/sort_key.rs
  ingester/src/persist/mod.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
  iox_tests/src/builders.rs
  iox_tests/src/catalog.rs
  service_grpc_catalog/src/lib.rs
Labels: automerge

#8523 fix: fix flaky partition tests with a retry
  test_helpers_end_to_end/src/steps.rs
Labels: automerge, kodiak: merge.method = 'squash'

#8524 refactor: Clean up some of the end-to-end CLI tests
  Cargo.lock
  influxdb_iox/Cargo.toml
  influxdb_iox/tests/end_to_end_cases/cli.rs
  influxdb_iox/tests/end_to_end_cases/cli/helpers.rs
  influxdb_iox/tests/end_to_end_cases/cli/namespace.rs
  influxdb_iox/tests/end_to_end_cases/cli/table.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8517 feat: fill sort_key_ids when partition is inserted and updated
  compactor_test_utils/src/lib.rs
  data_types/src/columns.rs
  data_types/src/partition.rs
  generated_types/protos/influxdata/iox/catalog/v1/service.proto
  import_export/src/file/import.rs
  ingester/src/buffer_tree/partition.rs
  ingester/src/buffer_tree/partition/resolver/cache.rs
  ingester/src/buffer_tree/partition/resolver/sort_key.rs
  ingester/src/persist/handle.rs
  ingester/src/persist/mod.rs
  ingester/src/persist/worker.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
  iox_tests/src/catalog.rs
  querier/src/cache/partition.rs
  querier/src/parquet/mod.rs
  service_grpc_catalog/src/lib.rs
Labels: automerge

#8506 feat: move vertical splitting & detect non-linear data
  compactor/src/components/divide_initial/multiple_branches.rs
  compactor/src/components/file_classifier/split_based.rs
  compactor/src/components/round_info_source/mod.rs
  compactor/src/components/round_split/many_files.rs
  compactor/src/components/split_or_compact/metrics.rs
  compactor/src/components/split_or_compact/split_compact.rs
  compactor/src/components/split_or_compact/start_level_files_to_split.rs
  compactor/src/driver.rs
  compactor/src/file_classification.rs
  compactor/src/round_info.rs
  compactor/tests/layouts/backfill.rs
  compactor/tests/layouts/common_use_cases.rs
  compactor/tests/layouts/knobs.rs
  compactor/tests/layouts/large_files.rs
  compactor/tests/layouts/large_overlaps.rs
  compactor/tests/layouts/many_files.rs
  compactor/tests/layouts/stuck.rs
  compactor_test_utils/src/display.rs
  compactor_test_utils/src/lib.rs
  data_types/src/lib.rs
Labels: automerge

#8537 test: harden `end_to_end_cases::debug::build_catalog`
  influxdb_iox/tests/end_to_end_cases/debug.rs
Labels: automerge

#8531 chore: manual `cargo update`
  Cargo.lock
Labels: automerge

#8540 revert: #8491
  iox_catalog/migrations/20230814162327_sort_key_ids_from_names.sql
  iox_catalog/migrations/20230814162336_sort_key_ids_remove_helper_index.sql
  iox_catalog/migrations/20230815091507_sort_key_ids_not_null.sql
  iox_catalog/src/postgres.rs
Labels: automerge

#8538 refactor(gossip): rename GossipMessage
  generated_types/build.rs
  generated_types/protos/influxdata/iox/gossip/v1/schema.proto
  router/src/gossip/dispatcher.rs
  router/src/gossip/mock_schema_broadcast.rs
  router/src/gossip/mod.rs
  router/src/gossip/namespace_cache.rs
  router/src/gossip/schema_change_observer.rs
Labels: kodiak: merge.method = 'merge'

#8545 chore: upgrade `rustls-webpki` to fix `RUSTSEC-2023-0053`
  Cargo.lock
Labels: automerge

#8541 feat: reusable schema notifications via gossip_schema crate
  Cargo.lock
  Cargo.toml
  data_types/src/columns.rs
  gossip_schema/Cargo.toml
  gossip_schema/src/dispatcher.rs
  gossip_schema/src/handle.rs
  gossip_schema/src/lib.rs
Labels: kodiak: merge.method = 'merge'

#8549 refactor(router): use gossip_schema
  Cargo.lock
  ioxd_router/Cargo.toml
  ioxd_router/src/lib.rs
  router/Cargo.toml
  router/src/gossip/dispatcher.rs
  router/src/gossip/mock_schema_broadcast.rs
  router/src/gossip/mod.rs
  router/src/gossip/namespace_cache.rs
  router/src/gossip/schema_change_observer.rs
  router/src/gossip/traits.rs
Labels: kodiak: merge.method = 'merge'

#8550 refactor(ingester): full parquet file metadata
  ingester/src/persist/completion_observer.rs
  ingester/src/persist/context.rs
  ingester/src/persist/file_metrics.rs
  ingester/src/persist/queue.rs
  ingester/src/persist/worker.rs
  ingester/src/test_util.rs
Labels: kodiak: merge.method = 'merge'

#8554 refactor: impl observer where type defined
  ingester/src/persist/completion_observer.rs
  ingester/src/wal/reference_tracker/handle.rs
Labels: kodiak: merge.method = 'merge'

#8557 perf: enable TCP_NODELAY on gRPC servers
  ioxd_common/src/rpc.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8543 feat: re-land #8491
  iox_catalog/migrations/20230822120632_sort_key_ids_add_helper_index_take_2.sql
  iox_catalog/migrations/20230822120702_sort_key_ids_from_name_take_2.sql
  iox_catalog/migrations/20230822120750_sort_key_ids_remove_helper_index_take_2.sql
  iox_catalog/migrations/20230822120825_sort_key_ids_not_null_take_2.sql
  iox_catalog/src/postgres.rs
Labels: automerge

#8567 docs(gossip): move crate docs to README
  gossip/README.md
  gossip/src/lib.rs
Labels: kodiak: merge.method = 'merge'

#8569 chore: add log message before compacting partition
  compactor/src/driver.rs
Labels: automerge

#8560 feat: teach compactor to use sort_key_ids instead of sort_key
  compactor/src/components/columns_source/catalog.rs
  compactor/src/components/columns_source/mock.rs
  compactor/src/components/columns_source/mod.rs
  compactor/src/components/hardcoded.rs
  compactor/src/components/mod.rs
  compactor/src/components/partition_info_source/sub_sources.rs
  compactor/tests/layouts/backfill.rs
  compactor/tests/layouts/stuck.rs
  data_types/src/partition.rs
  iox_tests/src/builders.rs
  iox_tests/src/lib.rs
Labels: automerge

#8544 chore: Update DataFusion pin
  Cargo.lock
  Cargo.toml
  iox_query/src/exec/context.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#8572 refactor: `is_terminal` no longer requires an external crate
  Cargo.lock
  trogging/Cargo.toml
  trogging/src/lib.rs
  workspace-hack/Cargo.toml
Labels: automerge

#8565 feat(gossip): new parquet file gossip crate
  Cargo.lock
  Cargo.toml
  generated_types/src/lib.rs
  gossip_parquet_file/Cargo.toml
  gossip_parquet_file/src/lib.rs
  gossip_parquet_file/src/rx.rs
  gossip_parquet_file/src/tx.rs
Labels: kodiak: merge.method = 'merge'

#8574 chore: revert teaching compactor to use sort_key_ids
  compactor/src/components/columns_source/catalog.rs
  compactor/src/components/columns_source/mock.rs
  compactor/src/components/columns_source/mod.rs
  compactor/src/components/hardcoded.rs
  compactor/src/components/mod.rs
  compactor/src/components/partition_info_source/sub_sources.rs
  compactor/tests/layouts/backfill.rs
  compactor/tests/layouts/stuck.rs
  data_types/src/partition.rs
  iox_tests/src/builders.rs
  iox_tests/src/lib.rs
Labels: automerge

#8559 feat: Add Compaction Regions
  compactor/src/components/divide_initial/multiple_branches.rs
  compactor/src/components/file_classifier/split_based.rs
  compactor/src/components/files_split/upgrade_split.rs
  compactor/src/components/round_info_source/mod.rs
  compactor/src/components/round_split/many_files.rs
  compactor/src/components/split_or_compact/start_level_files_to_split.rs
  compactor/src/driver.rs
  compactor/src/round_info.rs
  compactor/tests/integration.rs
  compactor/tests/layouts/backfill.rs
  compactor/tests/layouts/core.rs
  compactor/tests/layouts/knobs.rs
  compactor/tests/layouts/large_files.rs
  compactor/tests/layouts/large_overlaps.rs
  compactor/tests/layouts/many_files.rs
  compactor/tests/layouts/single_timestamp.rs
  compactor/tests/layouts/stuck.rs
  data_types/src/lib.rs
Labels: automerge

#8587 fix: don't add empty compact branches
  compactor/src/components/divide_initial/multiple_branches.rs
Labels: automerge

#8590 fix: Update to a non-yanked version of nix
  Cargo.lock
Labels: automerge

#8499 feat(ingester): Disk full protection
  ingester/src/init.rs
  ingester/src/init/graceful_shutdown.rs
  ingester/src/wal/disk_full_protection.rs
  ingester/src/wal/mod.rs
  tracker/src/disk_metric.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8599 fix(bench): schema validator bench panic
  router/benches/schema_validator.rs
Labels: kodiak: merge.method = 'merge'

#8586 chore: compact available regions before splitting everything
  compactor/src/components/round_info_source/mod.rs
  compactor/tests/layouts/backfill.rs
Labels: automerge

#8597 feat(router): merkle tree cache observer for anti-entropy
  Cargo.lock
  data_types/src/columns.rs
  data_types/src/lib.rs
  data_types/src/namespace_name.rs
  data_types/src/partition_template.rs
  generated_types/build.rs
  router/Cargo.toml
  router/src/gossip/anti_entropy/merkle.rs
  router/src/gossip/anti_entropy/mod.rs
  router/src/gossip/mod.rs
  sharder/src/jumphash.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8601 ci: lint failures as warnings
  router/src/lib.rs
Labels: kodiak: merge.method = 'merge'

#8603 chore: enable more ManySmallFiles compactions
  compactor/src/components/round_info_source/mod.rs
  compactor/tests/layouts/many_files.rs
Labels: automerge

#8606 chore: remove compactor concurrency scaling
  compactor/src/driver.rs
Labels: automerge

#8598 refactor: protobuf serialisation primitives for ParquetFile
  data_types/src/lib.rs
  data_types/src/partition.rs
  generated_types/protos/influxdata/iox/catalog/v1/parquet_file.proto
  gossip_parquet_file/src/lib.rs
  service_grpc_catalog/src/lib.rs
Labels: incompatible protobuf, kodiak: merge.method = 'merge'

#8600 perf: asynchronously maintain merkle search tree
  router/benches/namespace_schema_cache.rs
  router/src/gossip/anti_entropy/actor.rs
  router/src/gossip/anti_entropy/handle.rs
  router/src/gossip/anti_entropy/merkle.rs
  router/src/gossip/anti_entropy/mod.rs
Labels: kodiak: merge.method = 'merge'

#8609 feat(gossip): broadcast to randomised peer subset
  Cargo.lock
  gossip/Cargo.toml
  gossip/src/handle.rs
  gossip/src/peers.rs
  gossip/src/reactor.rs
  gossip/tests/smoke.rs
Labels: kodiak: merge.method = 'merge'

#8610 feat(gossip): expose peer identity & socket address
  gossip/src/dispatcher.rs
  gossip/src/handle.rs
  gossip/src/lib.rs
  gossip/src/peers.rs
  gossip/src/reactor.rs
  gossip/tests/smoke.rs
  gossip_parquet_file/src/rx.rs
  gossip_schema/src/dispatcher.rs
Labels: kodiak: merge.method = 'merge'

#8617 feat(gossip): schema sync proto message & topic
  generated_types/build.rs
  generated_types/protos/influxdata/iox/gossip/v1/schema_sync.proto
  generated_types/src/lib.rs
Labels: kodiak: merge.method = 'merge'

#8614 feat(cli): Queries for namespaces and tables should return their `PartitionTemplate`
  generated_types/protos/influxdata/iox/namespace/v1/service.proto
  generated_types/protos/influxdata/iox/table/v1/service.proto
  influxdb_iox/tests/end_to_end_cases/cli/helpers.rs
  influxdb_iox/tests/end_to_end_cases/cli/namespace.rs
  influxdb_iox/tests/end_to_end_cases/cli/table.rs
  ioxd_querier/src/rpc/namespace.rs
  service_grpc_namespace/src/lib.rs
  service_grpc_table/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8612 refactor: move MST et al into module
  router/benches/namespace_schema_cache.rs
  router/src/gossip/anti_entropy/mod.rs
  router/src/gossip/anti_entropy/mst/actor.rs
  router/src/gossip/anti_entropy/mst/handle.rs
  router/src/gossip/anti_entropy/mst/merkle.rs
  router/src/gossip/anti_entropy/mst/mod.rs
Labels: kodiak: merge.method = 'merge'

#8611 feat(ingester): gossip new parquet file persistence
  Cargo.lock
  ingester/Cargo.toml
  ingester/src/gossip/mod.rs
  ingester/src/gossip/persist_parquet.rs
  ingester/src/init.rs
  ingester/src/lib.rs
  ingester/src/persist/completion_observer.rs
Labels: kodiak: merge.method = 'merge'

#8627 feat(proto): Define GetTables RPC for TableService
  generated_types/protos/influxdata/iox/table/v1/service.proto
  service_grpc_table/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8625 fix: clippy
  influxdb_iox/tests/end_to_end_cases/cli/helpers.rs
Labels: automerge

#8629 feat(table): `GetTables` gRPC endpoint implementation
  data_types/src/lib.rs
  service_grpc_table/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8630 refactor(proto): unsigned port numbers
  generated_types/protos/influxdata/iox/gossip/v1/schema_sync.proto
Labels: incompatible protobuf, kodiak: merge.method = 'merge'

#8626 refactor: prep work for #8349
  client_util/src/lib.rs
  client_util/src/tower.rs
  data_types/src/lib.rs
  ingester_query_grpc/protos/influxdata/iox/ingester/v2/query.proto
  ingester_query_grpc/src/arrow_serde.rs
  ingester_query_grpc/src/lib.rs
Labels: automerge

#8624 feat: re-introduce sqlx pool "used" counter
  iox_catalog/src/postgres.rs
Labels: automerge
