Repository influxdata/influxdb_iox, pull requests merged in 2023-09, with the labels that each got.

#8632 feat: scaffolding for ingester->querier V2 client
  Cargo.lock
  Cargo.toml
  ingester_query_client/Cargo.toml
  ingester_query_client/src/error.rs
  ingester_query_client/src/interface.rs
  ingester_query_client/src/layer.rs
  ingester_query_client/src/layers/mod.rs
  ingester_query_client/src/layers/testing.rs
  ingester_query_client/src/lib.rs
  ingester_query_client/src/testing.rs
Labels: automerge

#8634 feat(cli): Add `table list <DATABASE>` command
  influxdb_iox/src/commands/table/create.rs
  influxdb_iox/src/commands/table/list.rs
  influxdb_iox/src/commands/table/mod.rs
  influxdb_iox/tests/end_to_end_cases/cli/table.rs
  influxdb_iox_client/src/client/table.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8644 refactor(wal): Consume `CrcReader` when invoking `checksum()`
  wal/src/blocking/reader.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8645 refactor(persist): load sort key once
  ingester/src/persist/compact.rs
  ingester/src/persist/worker.rs
Labels: kodiak: merge.method = 'merge'

#8647 fix(ingester): Correctly compute min sequence number for WAL replay debug log
  ingester/src/init/wal_replay.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8646 feat(gossip): define CompactionEvent protobuf
  generated_types/build.rs
  generated_types/protos/influxdata/iox/gossip/v1/compaction.proto
Labels: kodiak: merge.method = 'merge'

#8635 feat: use recurring L0 end time as hint for split times
  compactor/src/components/round_info_source/mod.rs
  compactor/tests/layouts/backfill.rs
  compactor/tests/layouts/large_files.rs
  compactor/tests/layouts/mod.rs
  compactor/tests/layouts/stuck.rs
  compactor_test_utils/src/lib.rs
  compactor_test_utils/src/simulator.rs
Labels: automerge

#8649 test(ingester): Cover WAL replay of empty files
  ingester/src/init/wal_replay.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8665 refactor(proto): SyncMessage -> ConsistencyProbe
  generated_types/protos/influxdata/iox/gossip/v1/schema_sync.proto
Labels: kodiak: merge.method = 'merge'

#8664 feat(gossip): compaction events crate
  Cargo.lock
  Cargo.toml
  generated_types/src/lib.rs
  gossip_compaction/Cargo.toml
  gossip_compaction/src/lib.rs
  gossip_compaction/src/rx.rs
  gossip_compaction/src/tx.rs
Labels: kodiak: merge.method = 'merge'

#8669 docs: remove outdated cache race warning
  router/src/namespace_cache.rs
Labels: kodiak: merge.method = 'merge'

#8668 refactor(router): remove unnecessary Arc wrapper in NamespaceCache stack
  ioxd_router/src/lib.rs
  router/benches/namespace_schema_cache.rs
  router/benches/schema_validator.rs
  router/src/dml_handlers/schema_validation.rs
  router/src/gossip/anti_entropy/mst/actor.rs
  router/src/gossip/schema_change_observer.rs
  router/src/namespace_cache.rs
  router/src/namespace_cache/memory.rs
  router/src/namespace_cache/metrics.rs
  router/src/namespace_cache/read_through_cache.rs
  router/src/namespace_cache/sharded_cache.rs
  router/src/namespace_resolver.rs
  router/src/namespace_resolver/ns_autocreation.rs
  router/tests/common/mod.rs
Labels: kodiak: merge.method = 'merge'

#8575 chore: reland 'teach compactor to use sortkey_ids' after catalog migration is fixed
  compactor/src/components/columns_source/catalog.rs
  compactor/src/components/columns_source/mock.rs
  compactor/src/components/columns_source/mod.rs
  compactor/src/components/hardcoded.rs
  compactor/src/components/mod.rs
  compactor/src/components/partition_info_source/sub_sources.rs
  compactor/tests/layouts/large_overlaps.rs
  compactor/tests/layouts/stuck.rs
  influxdb_iox/tests/end_to_end_cases/cli/table.rs
  iox_tests/src/builders.rs
  iox_tests/src/lib.rs
Labels: automerge

#8673 chore: prepare a revert PR just in case
  compactor/src/components/columns_source/catalog.rs
  compactor/src/components/columns_source/mock.rs
  compactor/src/components/columns_source/mod.rs
  compactor/src/components/hardcoded.rs
  compactor/src/components/mod.rs
  compactor/src/components/partition_info_source/sub_sources.rs
  compactor/tests/layouts/large_overlaps.rs
  compactor/tests/layouts/stuck.rs
  influxdb_iox/tests/end_to_end_cases/cli/table.rs
  iox_tests/src/builders.rs
  iox_tests/src/lib.rs
Labels: automerge

#8674 feat: reland compactor consumes sort_key_ids
  compactor/src/components/columns_source/catalog.rs
  compactor/src/components/columns_source/mock.rs
  compactor/src/components/columns_source/mod.rs
  compactor/src/components/hardcoded.rs
  compactor/src/components/mod.rs
  compactor/src/components/partition_info_source/sub_sources.rs
  compactor/tests/layouts/large_overlaps.rs
  compactor/tests/layouts/stuck.rs
  influxdb_iox/tests/end_to_end_cases/cli/table.rs
  iox_tests/src/builders.rs
  iox_tests/src/lib.rs
Labels: automerge

#8556 feat: have ingester's SortKeyState include sort_key_ids
  ingester/src/buffer_tree/partition.rs
  ingester/src/buffer_tree/partition/resolver/catalog.rs
  ingester/src/buffer_tree/partition/resolver/sort_key.rs
  ingester/src/persist/context.rs
  ingester/src/persist/handle.rs
  ingester/src/persist/mod.rs
  ingester/src/persist/worker.rs
  ingester/src/test_util.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
Labels: automerge

#8663 refactor: unpack record batches later during query
  influxdb_iox/tests/query_tests/cases/in/dedup_and_predicates_parquet_ingester.sql.expected
  influxdb_iox/tests/query_tests/cases/in/duplicates_ingester.sql.expected
  influxdb_iox/tests/query_tests/cases/in/duplicates_parquet_20_and_ingester.sql.expected
  influxdb_iox/tests/query_tests/cases/in/retention.sql.expected
  influxdb_iox/tests/query_tests/cases/in/several_chunks.sql.expected
  influxdb_iox/tests/query_tests/cases/in/two_chunks.sql.expected
  iox_query/src/frontend/reorg.rs
  iox_query/src/physical_optimizer/combine_chunks.rs
  iox_query/src/physical_optimizer/dedup/partition_split.rs
  iox_query/src/physical_optimizer/dedup/remove_dedup.rs
  iox_query/src/physical_optimizer/dedup/time_split.rs
  iox_query/src/physical_optimizer/projection_pushdown.rs
  iox_query/src/physical_optimizer/sort/parquet_sortness.rs
  iox_query/src/physical_optimizer/sort/push_sort_through_union.rs
  iox_query/src/provider.rs
  iox_query/src/provider/physical.rs
  iox_query/src/provider/record_batch_exec.rs
  iox_query_influxrpc/src/scan_plan.rs
Labels: automerge

#8641 feat: "logging" layer for i->q V2 client
  Cargo.lock
  ingester_query_client/Cargo.toml
  ingester_query_client/src/layers/logging.rs
  ingester_query_client/src/layers/mod.rs
  ingester_query_client/src/layers/testing.rs
Labels: automerge

#8638 feat: add "serialize" layer for i->q V2 client
  Cargo.lock
  ingester_query_client/Cargo.toml
  ingester_query_client/src/layers/mod.rs
  ingester_query_client/src/layers/serialize.rs
Labels: automerge

#8640 feat: network layer for i->q V2 client
  Cargo.lock
  ingester_query_client/Cargo.toml
  ingester_query_client/src/layers/mod.rs
  ingester_query_client/src/layers/network.rs
Labels: automerge

#8639 feat: add "deserialize" layer for i->q V2 client
  ingester_query_client/src/layers/deserialize.rs
  ingester_query_client/src/layers/mod.rs
Labels: automerge

#8396 fix(influxql): FILL(linear) for selectors
  influxdb_iox/tests/query_tests/cases/in/gapfill.sql
  influxdb_iox/tests/query_tests/cases/in/gapfill.sql.expected
  influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql
  influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql.expected
  iox_query/src/exec/gapfill/algo.rs
  iox_query/src/exec/gapfill/algo/interpolate.rs
  iox_query/src/exec/gapfill/buffered_input.rs
  iox_query/src/exec/gapfill/exec_tests.rs
  iox_query/src/logical_optimizer/handle_gapfill.rs
  query_functions/src/gapfill.rs
Labels: automerge

#8678 chore: reland have ingester's SortKeyState include sort_key_ids
  ingester/src/buffer_tree/partition.rs
  ingester/src/buffer_tree/partition/resolver/catalog.rs
  ingester/src/buffer_tree/partition/resolver/sort_key.rs
  ingester/src/persist/context.rs
  ingester/src/persist/handle.rs
  ingester/src/persist/mod.rs
  ingester/src/persist/worker.rs
  ingester/src/test_util.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
Labels: automerge

#8650 feat: Optionally specify a table name to get just its schema
  generated_types/protos/influxdata/iox/schema/v1/service.proto
  influxdb_iox/src/commands/debug/schema.rs
  influxdb_iox/src/commands/debug/wal/regenerate_lp.rs
  influxdb_iox/tests/end_to_end_cases/schema.rs
  influxdb_iox_client/src/client/schema.rs
  iox_catalog/src/interface.rs
  service_grpc_schema/src/lib.rs
  test_helpers_end_to_end/src/mini_cluster.rs
Labels: automerge

#8675 fix(compactor): prevent sort order mismatches from creating overlapping chains
  compactor/src/components/round_info_source/mod.rs
  compactor/src/components/split_or_compact/start_level_files_to_split.rs
  compactor/tests/layouts/core.rs
  compactor/tests/layouts/many_files.rs
Labels: automerge

#8687 feat: i->q V2 metrics integration
  Cargo.lock
  ingester_query_client/Cargo.toml
  ingester_query_client/src/layers/metrics.rs
  ingester_query_client/src/layers/mod.rs
Labels: automerge

#8688 feat: backoff & retry for i->q V2 client
  Cargo.lock
  ingester_query_client/Cargo.toml
  ingester_query_client/src/error_classifier.rs
  ingester_query_client/src/layers/backoff.rs
  ingester_query_client/src/layers/mod.rs
  ingester_query_client/src/lib.rs
Labels: automerge

#8577 chore: Update datafusion, arrow/flight/parquet to `46.0.0` , object_store to `0.7.0`
  Cargo.lock
  Cargo.toml
  arrow_util/Cargo.toml
  compactor/tests/integration.rs
  iox_query/src/exec.rs
  iox_query/src/exec/gapfill/algo.rs
  iox_query/src/exec/seriesset/converter.rs
  iox_query/src/physical_optimizer/predicate_pushdown.rs
  iox_query/src/physical_optimizer/projection_pushdown.rs
  iox_query/src/physical_optimizer/sort/parquet_sortness.rs
  iox_query_influxql/src/window/non_negative.rs
  object_store_metrics/src/lib.rs
  parquet_file/src/storage.rs
  parquet_to_line_protocol/src/lib.rs
  querier/src/cache/object_store.rs
  query_functions/src/selectors/internal.rs
  service_common/src/error.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#8699 chore: adjust compactor catalog query rate limiter for small clusters
  compactor/src/components/compaction_job_stream/endless.rs
Labels: automerge

#8697 chore: Add ticket reference to comment
  querier/src/cache/object_store.rs
Labels: automerge, kodiak: merge.method = 'squash'

#8695 feat: reconnect layer for i->q V2
  ingester_query_client/src/layers/mod.rs
  ingester_query_client/src/layers/reconnect_on_error.rs
Labels: automerge

#8686 feat: add easy-to-use compositions of i->q V2 client layers
  ingester_query_client/src/composition.rs
  ingester_query_client/src/lib.rs
Labels: automerge

#8706 refactor: wrap `CachedPartition` into `Arc`
  querier/src/cache/partition.rs
  querier/src/parquet/creation.rs
  querier/src/table/mod.rs
Labels: automerge

#8707 refactor: optimize hash-collection constructions
  querier/src/parquet/creation.rs
  querier/src/table/mod.rs
Labels: automerge

#8698 chore: Update DataFusion pin
  Cargo.lock
  Cargo.toml
  iox_query/src/logical_optimizer/influx_regex_to_datafusion_regex.rs
  parquet_file/src/storage.rs
  test_helpers_end_to_end/src/error.rs
  test_helpers_end_to_end/src/steps.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#8710 refactor: use `BTreeSet` in addressable heap
  cache_system/benches/addressable_heap.rs
  cache_system/src/addressable_heap.rs
Labels: automerge

#8709 fix(router): health probe livelock / missing probes
  router/src/dml_handlers/rpc_write.rs
  router/src/dml_handlers/rpc_write/balancer.rs
  router/src/dml_handlers/rpc_write/upstream_snapshot.rs
Labels: kodiak: merge.method = 'merge'

#8714 chore: Revert "chore: Update DataFusion pin (#8698)"
  Cargo.lock
  Cargo.toml
  iox_query/src/logical_optimizer/influx_regex_to_datafusion_regex.rs
  parquet_file/src/storage.rs
  test_helpers_end_to_end/src/error.rs
  test_helpers_end_to_end/src/steps.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#8700 fix: handle oversized files in compactor
  compactor/src/components/divide_initial/multiple_branches.rs
  compactor/tests/layouts/large_files.rs
Labels: automerge

#8712 refactor: optimize `PartitionHashId` hashing
  data_types/src/partition.rs
Labels: automerge

#8722 refactor: move table metadata alongside resolver
  ingester/src/buffer_tree/partition.rs
  ingester/src/buffer_tree/partition/resolver/cache.rs
  ingester/src/buffer_tree/partition/resolver/catalog.rs
  ingester/src/buffer_tree/partition/resolver/coalesce.rs
  ingester/src/buffer_tree/partition/resolver/mock.rs
  ingester/src/buffer_tree/partition/resolver/old_filter.rs
  ingester/src/buffer_tree/partition/resolver/trait.rs
  ingester/src/buffer_tree/root.rs
  ingester/src/buffer_tree/table.rs
  ingester/src/buffer_tree/table/metadata.rs
  ingester/src/buffer_tree/table/metadata_resolver.rs
  ingester/src/persist/compact.rs
  ingester/src/persist/context.rs
  ingester/src/test_util.rs
Labels: kodiak: merge.method = 'merge'

#8724 feat: allow fallback to generic TS column range for chunk stats
  iox_query/src/chunk_statistics.rs
Labels: automerge

#8725 feat: decode time portion of the partition key
  data_types/src/partition_template.rs
  ingester/src/buffer_tree/table.rs
  mutable_batch/src/payload/partition.rs
  querier/src/cache/partition.rs
Labels: automerge

#8672 feat(ingester): Allow read of `IngestState` with exceptions
  ingester/src/ingest_state.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8723 feat(ingester): buffered partition limit
  clap_blocks/src/ingester.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ingester/src/arcmap.rs
  ingester/src/buffer_tree/namespace.rs
  ingester/src/buffer_tree/partition.rs
  ingester/src/buffer_tree/partition/counter.rs
  ingester/src/buffer_tree/root.rs
  ingester/src/buffer_tree/table.rs
  ingester/src/dml_sink/trait.rs
  ingester/src/init.rs
  ingester/src/persist/handle.rs
  ingester/src/persist/mod.rs
  ingester/src/server/grpc/rpc_write.rs
  ingester_test_ctx/src/lib.rs
  ioxd_ingester/src/lib.rs
Labels: kodiak: merge.method = 'merge'

#8588 feat: ingester reads `sort_key_ids` instead of `sort_key`
  ingester/src/buffer_tree/partition/resolver/catalog.rs
  ingester/src/buffer_tree/partition/resolver/sort_key.rs
  ingester/src/test_util.rs
Labels: automerge

#8733 test: accept PartitionDataBuilder in provider
  ingester/src/buffer_tree/namespace.rs
  ingester/src/buffer_tree/partition/resolver/cache.rs
  ingester/src/buffer_tree/partition/resolver/coalesce.rs
  ingester/src/buffer_tree/partition/resolver/mock.rs
  ingester/src/buffer_tree/partition/resolver/trait.rs
  ingester/src/buffer_tree/root.rs
  ingester/src/buffer_tree/table.rs
  ingester/src/persist/handle.rs
  ingester/src/test_util.rs
Labels: kodiak: merge.method = 'merge'

#8735 perf: use half of logical cores for persist exec
  Cargo.lock
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/run/ingester.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'merge'

#8742 feat(query_functions): suport timezone in selector_* functions
  query_functions/src/selectors.rs
  query_functions/src/selectors/internal.rs
  query_functions/src/selectors/type_handling.rs
Labels: automerge

#8738 test: Add a test encoding expected behavior of validate_or_insert_schema
  iox_catalog/src/lib.rs
Labels: automerge

#8743 feat: i->q V2 circuit breaker
  Cargo.lock
  ingester_query_client/Cargo.toml
  ingester_query_client/src/error_classifier.rs
  ingester_query_client/src/layers/circuit_breaker.rs
  ingester_query_client/src/layers/mod.rs
Labels: automerge

#8754 feat: error "ignore" layer for i->q V2 client
  ingester_query_client/src/error_classifier.rs
  ingester_query_client/src/layers/error_to_option.rs
  ingester_query_client/src/layers/mod.rs
Labels: automerge

#8734 feat(ingester): limit non-empty partitions per namespace
  ingester/src/buffer_tree/namespace.rs
  ingester/src/buffer_tree/partition.rs
  ingester/src/buffer_tree/partition/counter.rs
  ingester/src/buffer_tree/partition/resolver/cache.rs
  ingester/src/buffer_tree/partition/resolver/catalog.rs
  ingester/src/buffer_tree/partition/resolver/coalesce.rs
  ingester/src/buffer_tree/partition/resolver/mock.rs
  ingester/src/buffer_tree/partition/resolver/old_filter.rs
  ingester/src/buffer_tree/partition/resolver/trait.rs
  ingester/src/buffer_tree/root.rs
  ingester/src/buffer_tree/table.rs
  ingester/src/test_util.rs
Labels: kodiak: merge.method = 'merge'

#8749 chore: Update DataFusion pin
  Cargo.lock
  Cargo.toml
  influxdb_iox/tests/query_tests/cases/in/custom_partitioning.sql.expected
  influxdb_iox/tests/query_tests/cases/in/date_bin.sql.expected
  influxdb_iox/tests/query_tests/cases/in/dedup_and_predicates_parquet.sql.expected
  influxdb_iox/tests/query_tests/cases/in/dedup_and_predicates_parquet_ingester.sql.expected
  influxdb_iox/tests/query_tests/cases/in/duplicates_parquet.sql.expected
  influxdb_iox/tests/query_tests/cases/in/gapfill.sql.expected
  influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql.expected
  influxdb_iox/tests/query_tests/cases/in/percentile.influxql.expected
  influxdb_iox/tests/query_tests/cases/in/pushdown.sql.expected
  influxdb_iox/tests/query_tests/cases/in/retention.sql.expected
  influxdb_iox/tests/query_tests/cases/in/several_chunks.sql.expected
  influxdb_iox/tests/query_tests/cases/in/sql_information_schema.sql
  influxdb_iox/tests/query_tests/cases/in/sql_information_schema.sql.expected
  iox_query/src/exec/split.rs
  iox_query/src/logical_optimizer/influx_regex_to_datafusion_regex.rs
  iox_query/src/provider/adapter.rs
  iox_query_influxql/src/aggregate/percentile.rs
  query_functions/src/selectors/type_handling.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#8763 fix(compactor): retry OOM error at reduced concurrency
  compactor/src/driver.rs
Labels: automerge

#8753 feat(gossip): schema cache anti-entropy service
  generated_types/protos/influxdata/iox/gossip/v1/schema_sync.proto
Labels: kodiak: merge.method = 'merge'

#8732 feat: use time-based column ranges in querier
  Cargo.lock
  querier/Cargo.toml
  querier/src/cache/partition.rs
Labels: automerge

#8666 feat(ingester): Automatically recover from an incomplete WAL write
  ingester/src/init/wal_replay.rs
  wal/src/blocking/reader.rs
  wal/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8766 refactor: clean up chunk pruning metrics/observers
  iox_query/src/provider.rs
  querier/src/table/metrics.rs
  querier/src/table/mod.rs
  querier/src/table/query_access.rs
  querier/src/table/query_access/mod.rs
Labels: automerge

#8770 build: latest merkle-search-tree version
  Cargo.lock
  router/Cargo.toml
Labels: kodiak: merge.method = 'merge'

#8750 feat: make sory_key_ids non-optional
  data_types/src/columns.rs
  data_types/src/partition.rs
  import_export/src/file/import.rs
  ingester/src/buffer_tree/partition.rs
  ingester/src/buffer_tree/partition/resolver/cache.rs
  ingester/src/buffer_tree/partition/resolver/catalog.rs
  ingester/src/buffer_tree/partition/resolver/old_filter.rs
  ingester/src/buffer_tree/partition/resolver/sort_key.rs
  ingester/src/persist/context.rs
  ingester/src/persist/mod.rs
  ingester/src/persist/worker.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
  iox_tests/src/builders.rs
  iox_tests/src/catalog.rs
  querier/src/cache/partition.rs
  service_grpc_catalog/src/lib.rs
Labels: automerge

#8736 chore(compactor): move CompactRange up to RoundInfo
  compactor/src/components/divide_initial/mod.rs
  compactor/src/components/divide_initial/multiple_branches.rs
  compactor/src/components/file_classifier/logging.rs
  compactor/src/components/file_classifier/mod.rs
  compactor/src/components/file_classifier/split_based.rs
  compactor/src/components/round_info_source/mod.rs
  compactor/src/components/round_split/many_files.rs
  compactor/src/components/round_split/mod.rs
  compactor/src/components/split_or_compact/start_level_files_to_split.rs
  compactor/src/driver.rs
  compactor/src/file_classification.rs
  compactor/src/round_info.rs
  compactor/tests/integration.rs
  compactor/tests/layouts/backfill.rs
  compactor/tests/layouts/common_use_cases.rs
  compactor/tests/layouts/core.rs
  compactor/tests/layouts/large_files.rs
  compactor/tests/layouts/large_overlaps.rs
  compactor/tests/layouts/many_files.rs
  compactor/tests/layouts/single_timestamp.rs
  compactor/tests/layouts/stuck.rs
Labels: automerge

#8765 chore: Update DataFusion
  Cargo.lock
  Cargo.toml
  influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql.expected
  iox_query/src/physical_optimizer/projection_pushdown.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#8768 refactor: allow streaming record batches into query
  ingester/src/query_adaptor.rs
  iox_query/src/lib.rs
  iox_query/src/provider/adapter.rs
  iox_query/src/provider/record_batch_exec.rs
  iox_query/src/test.rs
  querier/src/ingester/mod.rs
Labels: automerge

#8771 feat: prune partitions before creating parquet chunks
  querier/src/parquet/creation.rs
  querier/src/parquet/mod.rs
  querier/src/table/metrics.rs
  querier/src/table/mod.rs
Labels: automerge

#8775 refactor: clean up query log impl
  iox_query/src/lib.rs
  iox_query/src/test.rs
  querier/src/database.rs
  querier/src/lib.rs
  querier/src/namespace/query_access.rs
  querier/src/query_log.rs
  service_grpc_flight/src/lib.rs
  service_grpc_influxrpc/src/service.rs
Labels: automerge

#8776 feat: merkle search tree snapshot generation
  router/src/gossip/anti_entropy/mst/actor.rs
  router/src/gossip/anti_entropy/mst/handle.rs
  router/src/gossip/anti_entropy/mst/mod.rs
Labels: kodiak: merge.method = 'merge'

#8777 build: bump rust to 1.72.1
  rust-toolchain.toml
Labels: kodiak: merge.method = 'merge'

#8778 refactor: isolate V1 ingester->querier client
  querier/src/ingester/mod.rs
  querier/src/ingester/test_util.rs
  querier/src/ingester/v1/circuit_breaker.rs
  querier/src/ingester/v1/flight_client.rs
  querier/src/ingester/v1/invalidate_on_error.rs
  querier/src/ingester/v1/mod.rs
  querier/src/lib.rs
  querier/src/table/mod.rs
  querier/src/table/test_util.rs
Labels: automerge

#8780 feat(router): init anti-entropy merkle search tree
  Cargo.lock
  ioxd_router/Cargo.toml
  ioxd_router/src/lib.rs
  router/src/gossip/anti_entropy/mst/handle.rs
Labels: kodiak: merge.method = 'merge'

#8782 refactor: Improvements made during UpsertSchema work that are actually independent
  Cargo.lock
  data_types/src/lib.rs
  service_grpc_schema/Cargo.toml
  service_grpc_schema/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8767 feat(ingester): Respect `IngestState` during WAL replay
  ingester/benches/wal.rs
  ingester/src/ingest_state.rs
  ingester/src/init.rs
  ingester/src/init/wal_replay.rs
  ingester/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8786 feat: Prepare SchemaValidator to be shared with schema upsert as well as writes
  ioxd_router/src/lib.rs
  router/benches/schema_validator.rs
  router/src/dml_handlers/mod.rs
  router/src/dml_handlers/schema_validation.rs
  router/src/dml_handlers/trait.rs
  router/src/lib.rs
  router/src/schema_validator.rs
  router/src/server/http.rs
  router/tests/common/mod.rs
  router/tests/grpc.rs
  router/tests/http.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8787 chore: derive compactors DF memory pool size from a percent of total
  Cargo.lock
  clap_blocks/src/compactor.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/src/commands/run/compactor.rs
  ioxd_compactor/Cargo.toml
  ioxd_compactor/src/lib.rs
Labels: automerge

#8798 refactor: Extract more functionality that schema upsert will need too
  iox_catalog/src/lib.rs
  router/src/schema_validator.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8783 feat(router): schema cache anti-entropy/sync actor
  Cargo.lock
  data_types/src/columns.rs
  router/Cargo.toml
  router/src/gossip/anti_entropy/mod.rs
  router/src/gossip/anti_entropy/sync/actor.rs
  router/src/gossip/anti_entropy/sync/consistency_prober.rs
  router/src/gossip/anti_entropy/sync/mock_consistency_prober.rs
  router/src/gossip/anti_entropy/sync/mock_rpc_client.rs
  router/src/gossip/anti_entropy/sync/mod.rs
  router/src/gossip/anti_entropy/sync/rpc_worker.rs
  router/src/gossip/anti_entropy/sync/traits.rs
Labels: kodiak: merge.method = 'merge'

#8807 refactor: move RpcWorker into a submod
  router/src/gossip/anti_entropy/sync/rpc_worker/mod.rs
  router/src/gossip/anti_entropy/sync/rpc_worker/worker_task.rs
Labels: kodiak: merge.method = 'merge'

#8809 feat(router): Merkle Search Tree diff computation support
  data_types/src/namespace_name.rs
  router/src/gossip/anti_entropy/mst/actor.rs
  router/src/gossip/anti_entropy/mst/handle.rs
Labels: kodiak: merge.method = 'merge'

#8808 feat(router): sync task concurrency restrictions
  router/src/gossip/anti_entropy/sync/actor.rs
  router/src/gossip/anti_entropy/sync/mock_rpc_client.rs
  router/src/gossip/anti_entropy/sync/rpc_worker/mod.rs
  router/src/gossip/anti_entropy/sync/rpc_worker/task_set.rs
  router/src/lib.rs
Labels: kodiak: merge.method = 'merge'

#8810 feat(router): query merkle tree for key ranges
  router/src/gossip/anti_entropy/mst/actor.rs
  router/src/gossip/anti_entropy/mst/handle.rs
Labels: kodiak: merge.method = 'merge'

#8814 fix(influxql): DISTINCT with GROUP BY TIME
  influxdb_iox/tests/query_tests/cases/in/window_like.influxql
  influxdb_iox/tests/query_tests/cases/in/window_like.influxql.expected
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/rewriter.rs
Labels: automerge

#8781 refactor: prune parquet chunks earlier
  querier/src/database.rs
  querier/src/namespace/mod.rs
  querier/src/parquet/creation.rs
  querier/src/parquet/mod.rs
  querier/src/table/metrics.rs
  querier/src/table/mod.rs
  querier/src/table/test_util.rs
Labels: automerge

#8821 test: schema cache convergence via merkle tree
  router/src/gossip/anti_entropy/mst/mod.rs
Labels: kodiak: merge.method = 'merge'

#8824 docs: mark sqlite as for non-production use only
  clap_blocks/src/catalog_dsn.rs
Labels: kodiak: merge.method = 'merge'

#8812 chore: Update DataFusion
  Cargo.lock
  Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#8816 chore: make `prost`, `prost-build`, `pbjson` and `pbjson-build` workspace dependencies
  Cargo.toml
  flightsql/Cargo.toml
  generated_types/Cargo.toml
  gossip/Cargo.toml
  grpc-binary-logger-proto/Cargo.toml
  grpc-binary-logger-test-proto/Cargo.toml
  grpc-binary-logger/Cargo.toml
  influxdb_iox/Cargo.toml
  influxdb_iox_client/Cargo.toml
  influxdb_storage_client/Cargo.toml
  ingester/Cargo.toml
  ingester_query_grpc/Cargo.toml
  ingester_test_ctx/Cargo.toml
  mutable_batch_tests/Cargo.toml
  parquet_file/Cargo.toml
  querier/Cargo.toml
  service_grpc_flight/Cargo.toml
  service_grpc_influxrpc/Cargo.toml
  test_helpers_end_to_end/Cargo.toml
  wal/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#8822 refactor: consolidate chunk stat creation
  compactor/src/components/df_planner/query_chunk.rs
  ingester/src/buffer_tree/partition.rs
  ingester/src/buffer_tree/table.rs
  ingester/src/query_adaptor.rs
  iox_query/src/chunk_statistics.rs
  iox_query/src/util.rs
  querier/src/ingester/mod.rs
  querier/src/parquet/creation.rs
  querier/src/table/mod.rs
Labels: automerge

#8823 refactor: move prop data generators and deterministic ID mapping
  router/src/gossip/anti_entropy/mod.rs
  router/src/gossip/anti_entropy/mst/merkle.rs
  router/src/gossip/anti_entropy/mst/mod.rs
Labels: kodiak: merge.method = 'merge'

#8801 chore(compactor): Limit active range count to twice the concurrency limit
  compactor/src/components/round_info_source/mod.rs
  compactor/src/driver.rs
  compactor/src/round_info.rs
  compactor/tests/layouts/backfill.rs
Labels: automerge

#8813 chore: delete SimlulatedLeadingEdge
  compactor/src/components/divide_initial/multiple_branches.rs
  compactor/src/components/file_classifier/split_based.rs
  compactor/src/components/round_info_source/mod.rs
  compactor/src/components/round_split/many_files.rs
  compactor/src/round_info.rs
Labels: automerge

#8830 feat: add return body size to tracing
  Cargo.lock
  ingester_query_client/src/layers/tracing.rs
  iox_query/src/exec/context.rs
  querier/src/ingester/v1/circuit_breaker.rs
  querier/src/ingester/v1/invalidate_on_error.rs
  trace/src/span.rs
  trace_exporters/src/jaeger.rs
  trace_exporters/src/jaeger/span.rs
  trace_http/Cargo.toml
  trace_http/src/tower.rs
Labels: automerge

#8829 feat: selective NamespaceSchema field MST coverage
  router/src/gossip/anti_entropy/mst/actor.rs
  router/src/gossip/anti_entropy/mst/merkle.rs
Labels: kodiak: merge.method = 'merge'

#8832 test: anti-entropy integration sync
  Cargo.lock
  router/Cargo.toml
  router/src/gossip/anti_entropy/mst/actor.rs
  router/src/gossip/anti_entropy/sync/actor.rs
  router/src/gossip/anti_entropy/sync/mod.rs
Labels: kodiak: merge.method = 'merge'

#8833 feat(sync): SyncRpcClient implementation for gRPC
  router/src/gossip/anti_entropy/sync/mod.rs
  router/src/gossip/anti_entropy/sync/rpc_worker/grpc_connector.rs
  router/src/gossip/anti_entropy/sync/rpc_worker/mod.rs
Labels: kodiak: merge.method = 'merge'

#8835 test: wait for convergence
  router/src/gossip/anti_entropy/mst/mod.rs
Labels: kodiak: merge.method = 'merge'

#8834 feat(gossip): consistency probe dispatcher
  router/src/gossip/anti_entropy/sync/consistency_prober.rs
Labels: kodiak: merge.method = 'merge'

#8836 feat(router): anti-entropy service
  gossip_schema/src/handle.rs
  gossip_schema/src/lib.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/src/commands/run/router.rs
  ioxd_router/src/lib.rs
  router/src/gossip/anti_entropy/mst/handle.rs
  router/src/gossip/anti_entropy/sync/rpc_server.rs
  router/src/server.rs
  router/src/server/grpc.rs
  router/tests/common/mod.rs
Labels: kodiak: merge.method = 'merge'

#8728 feat: make column sort_key null before we can stop populating it
  iox_catalog/migrations/20230921180000_set_partition_sort_key_to_null.sql
  iox_catalog/sqlite/migrations/20230921180000_set_partition_sort_key_to_null.sql
Labels: automerge

#8839 chore: prepare for schema timezone change
  arrow_util/src/test_util.rs
  datafusion_util/Cargo.toml
  datafusion_util/src/config.rs
  datafusion_util/src/lib.rs
  influxdb_iox/src/commands/storage/response.rs
  influxdb_iox/tests/query_tests/cases/in/percentile.influxql.expected
  influxdb_iox_client/src/format/influxql.rs
  iox_query/src/chunk_statistics.rs
  iox_query/src/exec/fieldlist.rs
  iox_query/src/exec/gapfill/algo.rs
  iox_query/src/exec/gapfill/algo/interpolate.rs
  iox_query/src/logical_optimizer/handle_gapfill.rs
  iox_query/src/provider/deduplicate.rs
  iox_query/src/provider/overlap.rs
  iox_query/src/test.rs
  iox_query_influxql/src/plan/planner.rs
  parquet_file/src/metadata.rs
  parquet_file/tests/metadata.rs
  query_functions/src/gapfill.rs
  query_functions/src/lib.rs
  query_functions/src/window.rs
  schema/src/lib.rs
  service_grpc_influxrpc/src/data.rs
Labels: automerge

#8840 fix(compactor): empty list panic
  compactor/src/components/file_classifier/split_based.rs
  compactor/src/components/post_classification_partition_filter/logging.rs
  compactor/src/components/post_classification_partition_filter/metrics.rs
  compactor/src/components/post_classification_partition_filter/mock.rs
  compactor/src/components/post_classification_partition_filter/mod.rs
  compactor/src/components/post_classification_partition_filter/possible_progress.rs
  compactor/src/driver.rs
  compactor/src/file_classification.rs
  compactor/tests/layouts/boundary_conditions.rs
  compactor/tests/layouts/mod.rs
  compactor/tests/layouts/single_timestamp.rs
Labels: automerge

#8837 refactor: prepare i->q v2 integration into querier
  querier/src/ingester/mod.rs
  querier/src/ingester/test_util.rs
  querier/src/ingester/v1/mod.rs
  querier/src/table/mod.rs
  querier/src/table/test_util.rs
Labels: automerge

#8850 feat: enable schema cache gossiping
  ioxd_router/src/lib.rs
Labels: kodiak: merge.method = 'merge'

#8853 refactor: increase maximum grpc sync message size
  ioxd_router/src/lib.rs
  router/src/gossip/anti_entropy/sync/rpc_server.rs
  router/src/gossip/anti_entropy/sync/rpc_worker/grpc_connector.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8849 fix: `ingester_query_client` interface issues
  ingester_query_client/src/layer.rs
  ingester_query_client/src/layers/network.rs
  ingester_query_client/src/layers/serialize.rs
  ingester_query_client/src/layers/testing.rs
Labels: automerge

#8851 feat: feature flag for V2 ingester API (querier side)
  clap_blocks/src/querier.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ioxd_querier/src/lib.rs
  querier/src/ingester/mod.rs
Labels: automerge

#8815 chore: Update DataFusion + arrow/parquet/arrow-flight to 47.0.0
  Cargo.lock
  Cargo.toml
  arrow_util/Cargo.toml
  authz/src/permission.rs
  generated_types/Cargo.toml
  grpc-binary-logger-proto/Cargo.toml
  ingester_query_client/Cargo.toml
  ingester_query_grpc/Cargo.toml
  mutable_batch_pb/src/decode.rs
  parquet_file/Cargo.toml
  parquet_file/src/metadata.rs
  service_grpc_influxrpc/src/expr.rs
  service_grpc_influxrpc/src/service.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#8764 fix: fixing validation of max tables/max columns per table
  compactor/src/components/namespaces_source/mock.rs
  data_types/src/lib.rs
  data_types/src/service_limits.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
  iox_tests/src/catalog.rs
  ioxd_querier/src/rpc/namespace.rs
  router/benches/namespace_schema_cache.rs
  router/benches/partitioner.rs
  router/benches/schema_validator.rs
  router/src/dml_handlers/schema_validation.rs
  router/src/gossip/anti_entropy/mod.rs
  router/src/gossip/anti_entropy/sync/rpc_worker/worker_task.rs
  router/src/gossip/namespace_cache.rs
  router/src/namespace_cache/memory.rs
  router/src/namespace_cache/metrics.rs
  router/src/schema_validator.rs
  router/src/server/http.rs
  router/tests/grpc.rs
  router/tests/http.rs
  service_grpc_namespace/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8852 feat: payload distributor / demuxer for ingester response
  querier/src/ingester/mod.rs
  querier/src/ingester/v2/mod.rs
  querier/src/ingester/v2/payload_distributor.rs
Labels: automerge

#8855 chore: Enable rustls-tls-native-roots in reqwest
  Cargo.lock
  client_util/Cargo.toml
  influxdb2_client/Cargo.toml
  influxdb_iox_client/Cargo.toml
  ioxd_common/Cargo.toml
  test_helpers_end_to_end/Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge

#8856 feat: hook up ingester->querier V2 into querier
  Cargo.lock
  querier/Cargo.toml
  querier/src/ingester/mod.rs
  querier/src/ingester/test_util.rs
  querier/src/ingester/v1/mod.rs
  querier/src/ingester/v2/mod.rs
Labels: automerge
