Repository influxdata/influxdb_iox, pull requests merged in 2023-03, with the labels that each got.

#7085 fix: `extract_chunks` schema handling
  iox_query/src/physical_optimizer/chunk_extraction.rs
Labels: automerge

#7086 feat: "collect chunks" phys. optimizer rule
  iox_query/src/physical_optimizer/combine_chunks.rs
  iox_query/src/physical_optimizer/dedup/mod.rs
  iox_query/src/physical_optimizer/mod.rs
Labels: automerge

#7083 feat: predicate pushdown phys. optimizer rule
  iox_query/src/physical_optimizer/mod.rs
  iox_query/src/physical_optimizer/predicate_pushdown.rs
  iox_query/src/provider/deduplicate.rs
  iox_query/src/provider/deduplicate/algo.rs
Labels: automerge

#7082 docs: update router diagrams for kafkaless
  router/src/dml_handlers/mod.rs
  router/src/dml_handlers/retention_validation.rs
  router/src/dml_handlers/trait.rs
  router/src/lib.rs
Labels: kodiak: merge.method = 'merge'

#7084 chore: Update datafusion + arrow/arrow-flight/parquet to 34.0.0
  Cargo.lock
  Cargo.toml
  arrow_util/src/test_util.rs
  influxdb_iox/tests/query_tests2/cases/in/dedup_and_predicates_parquet.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/dedup_and_predicates_parquet_ingester.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_parquet.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_parquet_many.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/pushdown.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/retention.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/several_chunks.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/two_chunks.sql.expected
  querier/Cargo.toml
  querier/src/namespace/query_access.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#7091 docs: ingester overview + subsystem docs
  ingester/src/dml_sink/mod.rs
  ingester2/src/buffer_tree/mod.rs
  ingester2/src/buffer_tree/partition.rs
  ingester2/src/buffer_tree/root.rs
  ingester2/src/dml_sink/mod.rs
  ingester2/src/ingest_state.rs
  ingester2/src/ingester_id.rs
  ingester2/src/init.rs
  ingester2/src/lib.rs
  ingester2/src/partition_iter.rs
  ingester2/src/persist/handle.rs
  ingester2/src/persist/hot_partitions.rs
  ingester2/src/persist/mod.rs
  ingester2/src/server/mod.rs
Labels: kodiak: merge.method = 'merge'

#7074 test: Change more querier tests to only use Kafkaless
  querier/src/ingester/mod.rs
  querier/src/table/test_util.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7097 test(compactor2): layout tests for scenarios of large size overlap files
  compactor2/tests/layouts/large_overlaps.rs
  compactor2/tests/layouts/mod.rs
Labels: automerge, kodiak: merge.method = 'squash'

#7096 feat(compactor2): add invariant checks to the compactor tests
  compactor2/tests/layouts/core.rs
  compactor2/tests/layouts/many_files.rs
  compactor2/tests/layouts/mod.rs
  compactor2_test_utils/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#7104 feat: allow no lower bound gap fill implementation
  iox_query/src/exec/gapfill.rs
  iox_query/src/exec/gapfill/algo.rs
  iox_query/src/exec/gapfill/params.rs
Labels: automerge

#7106 chore: remove folder that was acidentaly added by vs code
  compactor2/src/components/split_or_compact/split_compact.rs
Labels: automerge

#7102 fix: Use the same normalization code for explain tests as e2e tests do
  Cargo.lock
  arrow_util/Cargo.toml
  arrow_util/src/test_util.rs
  querier/Cargo.toml
  querier/src/namespace/query_access.rs
  test_helpers_end_to_end/Cargo.toml
  test_helpers_end_to_end/src/lib.rs
  test_helpers_end_to_end/src/snapshot_comparison.rs
  test_helpers_end_to_end/src/snapshot_comparison/normalization.rs
  test_helpers_end_to_end/src/snapshot_comparison/queries.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7101 chore(compactor2): add documentation about the compactor2 file level invariants
  compactor2/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#7105 chore(compactor2): Improve documentation on split times
  compactor2/src/plan_ir.rs
  iox_query/src/frontend/reorg.rs
Labels: automerge, kodiak: merge.method = 'squash'

#7095 feat: sort-related phys. optimizers
  iox_query/src/physical_optimizer/mod.rs
  iox_query/src/physical_optimizer/sort/mod.rs
  iox_query/src/physical_optimizer/sort/redundant_sort.rs
  iox_query/src/physical_optimizer/sort/sort_pushdown.rs
Labels: automerge

#7098 fix(compactor2): fix off by one error in time ranges of simulator
  compactor2/tests/layouts/core.rs
  compactor2/tests/layouts/knobs.rs
  compactor2/tests/layouts/many_files.rs
  compactor2/tests/layouts/mod.rs
  compactor2_test_utils/src/simulator.rs
Labels: automerge, kodiak: merge.method = 'squash'

#7094 perf(wal): avoid batch buffer reallocations
  wal/src/lib.rs
Labels: kodiak: merge.method = 'merge'

#7110 feat(wal): track set of write IDs in a segment file
  data_types/src/sequence_number_set.rs
  ingester2/src/wal/rotate_task.rs
  wal/src/lib.rs
  wal/src/writer_thread.rs
  wal/tests/end_to_end.rs
Labels: kodiak: merge.method = 'merge'

#7113 refactor: sort key cleanups
  iox_query/src/provider.rs
  schema/src/sort.rs
Labels: automerge

#7093 fix: wal flusher task / memory leak
  wal/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7114 chore: verify split time invariants within simulator
  compactor2_test_utils/src/simulator.rs
Labels: automerge

#7112 fix(wal): write commit cancellation safety
  ingester2/src/cancellation_safe.rs
  ingester2/src/dml_sink/instrumentation.rs
  ingester2/src/dml_sink/tracing.rs
  ingester2/src/lib.rs
  ingester2/src/wal/wal_sink.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7115 fix: account for memory in `GapFillStream`
  iox_query/src/exec/gapfill.rs
  iox_query/src/exec/gapfill/stream.rs
Labels: automerge

#7120 style: remove unnecessary nesting
  ingester2/src/persist/drain_buffer.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7121 feat: SequenceNumberSet intersection + helpers
  data_types/src/sequence_number_set.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7123 test(compactor): Add test for large amounts of data with a single timestamp
  compactor2/tests/layouts/mod.rs
  compactor2/tests/layouts/single_timestamp.rs
  compactor2_test_utils/src/simulator.rs
Labels: automerge, kodiak: merge.method = 'squash'

#7134 chore: add deploy tools to CI image
  docker/Dockerfile.ci
Labels: automerge

#7126 chore: add warnings to compaction simulator for excessively oversized files
  compactor2/tests/layouts/mod.rs
  compactor2/tests/layouts/single_timestamp.rs
  compactor2_test_utils/src/display.rs
  compactor2_test_utils/src/lib.rs
Labels: automerge

#7137 test: reproducer for bug 17221
  compactor2/tests/layouts/many_files.rs
Labels: automerge

#7139 fix: L1 files must be sorted in their min_time if they need to split before compacting
  compactor2/src/components/divide_initial/multiple_branches.rs
  compactor2/tests/layouts/many_files.rs
Labels: automerge

#7148 feat: sub-traces for `create_chunks`
  querier/src/parquet/creation.rs
Labels: automerge

#7140 feat(compactor2): Verify invariants for intermediate parquet files created by compactor2
  compactor2/tests/integration.rs
  compactor2_test_utils/src/commit_wrapper.rs
  compactor2_test_utils/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#7150 feat: add a type to characterize fill strategy
  iox_query/src/exec/gapfill.rs
  iox_query/src/exec/gapfill/algo.rs
  iox_query/src/exec/gapfill/params.rs
  iox_query/src/logical_optimizer/handle_gapfill.rs
Labels: automerge

#7079 feat: handle large-size overlapped files
  compactor2/src/components/commit/metrics.rs
  compactor2/src/components/divide_initial/multiple_branches.rs
  compactor2/src/components/file_classifier/logging.rs
  compactor2/src/components/file_classifier/split_based.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/ir_planner/logging.rs
  compactor2/src/components/ir_planner/mod.rs
  compactor2/src/components/ir_planner/planner_v1.rs
  compactor2/src/components/mod.rs
  compactor2/src/components/partition_filter/max_parquet_bytes.rs
  compactor2/src/components/partition_filter/mod.rs
  compactor2/src/components/partition_filter/unable_to_compact.rs
  compactor2/src/components/round_info_source/mod.rs
  compactor2/src/components/round_split/many_files.rs
  compactor2/src/components/split_or_compact/files_to_compact.rs
  compactor2/src/components/split_or_compact/files_to_split.rs
  compactor2/src/components/split_or_compact/logging.rs
  compactor2/src/components/split_or_compact/mod.rs
  compactor2/src/components/split_or_compact/split_compact.rs
  compactor2/src/driver.rs
  compactor2/src/file_classification.rs
  compactor2/src/round_info.rs
  compactor2/tests/integration.rs
  compactor2/tests/layouts/core.rs
  compactor2/tests/layouts/knobs.rs
  compactor2/tests/layouts/large_overlaps.rs
  compactor2/tests/layouts/mod.rs
  compactor2/tests/layouts/single_timestamp.rs
  compactor2_test_utils/src/lib.rs
  compactor2_test_utils/src/simulator.rs
  data_types/src/lib.rs
Labels: automerge

#7141 chore: add panic at compactor startup for invalid config options
  ioxd_compactor2/src/lib.rs
Labels: automerge

#7109 feat: Support `GROUP BY` with tags in raw `SELECT` queries
  Cargo.lock
  generated_types/protos/influxdata/iox/querier/v1/flight.proto
  influxdb_influxql_parser/src/expression/arithmetic.rs
  influxdb_influxql_parser/src/select.rs
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__select_statement-3.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__select_statement-4.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__select_statement-3.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__select_statement-4.snap
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql.expected
  influxdb_iox/tests/query_tests2/setups.rs
  iox_query/Cargo.toml
  iox_query/src/frontend/influxql.rs
  iox_query/src/plan/influxql/field.rs
  iox_query/src/plan/influxql/planner.rs
  iox_query/src/plan/influxql/rewriter.rs
  schema/src/lib.rs
  service_grpc_flight/src/lib.rs
Labels: automerge, query/language/influxql

#7133 feat: Output formatting for InfluxQL
  Cargo.lock
  influxdb_iox/src/commands/query.rs
  influxdb_iox_client/Cargo.toml
  influxdb_iox_client/src/format.rs
  influxdb_iox_client/src/format/influxql.rs
Labels: automerge, query/language/influxql

#7154 refactor: convert gap fill exec tests to use insta snapshots
  iox_query/src/exec/gapfill.rs
  iox_query/src/exec/gapfill/exec_tests.rs
  iox_query/src/exec/gapfill/mod.rs
Labels: automerge

#7147 feat: determine cheap de-dup sort order
  Cargo.lock
  iox_query/Cargo.toml
  iox_query/src/physical_optimizer/dedup/dedup_sort_order.rs
  iox_query/src/physical_optimizer/dedup/mod.rs
  iox_query/src/physical_optimizer/dedup/test_util.rs
Labels: automerge

#7146 feat: remove all-NULL columns from dedup
  iox_query/src/physical_optimizer/dedup/dedup_null_columns.rs
  iox_query/src/physical_optimizer/dedup/mod.rs
Labels: automerge

#7158 chore: update DataFusion to `deeaa5632ed99a58b91767261570756db736d158`
  Cargo.lock
  Cargo.toml
  iox_query/src/config.rs
  iox_query/src/exec/gapfill/mod.rs
  iox_query/src/exec/non_null_checker.rs
  iox_query/src/exec/schema_pivot.rs
  iox_query/src/exec/split.rs
  iox_query/src/physical_optimizer/predicate_pushdown.rs
  iox_query/src/plan/influxql/planner.rs
  predicate/src/rpc_predicate.rs
  workspace-hack/Cargo.toml
Labels: automerge

#7159 feat: phys. pred. pushdown to parquet
  iox_query/src/physical_optimizer/predicate_pushdown.rs
Labels: automerge

#7160 chore(iox/compactor): rename max_input_parquet_bytes_per_partition
  clap_blocks/src/compactor2.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/report.rs
  compactor2/src/config.rs
  compactor2/tests/integration.rs
  compactor2/tests/layouts/knobs.rs
  compactor2/tests/layouts/mod.rs
  compactor2_test_utils/src/lib.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ioxd_compactor2/src/lib.rs
Labels: automerge

#7151 chore: log column count in IR compact plan
  compactor2/src/components/ir_planner/logging.rs
Labels: automerge

#7156 refactor: Move InfluxQL behaviour from iox_query to new crate
  Cargo.lock
  Cargo.toml
  iox_query/Cargo.toml
  iox_query/src/frontend.rs
  iox_query/src/plan.rs
  iox_query/src/plan/influxql/test_utils.rs
  iox_query_influxql/Cargo.toml
  iox_query_influxql/src/frontend/mod.rs
  iox_query_influxql/src/frontend/planner.rs
  iox_query_influxql/src/lib.rs
  iox_query_influxql/src/plan/expr_type_evaluator.rs
  iox_query_influxql/src/plan/field.rs
  iox_query_influxql/src/plan/field_mapper.rs
  iox_query_influxql/src/plan/mod.rs
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/planner_rewrite_expression.rs
  iox_query_influxql/src/plan/planner_time_range_expression.rs
  iox_query_influxql/src/plan/rewriter.rs
  iox_query_influxql/src/plan/test_utils.rs
  iox_query_influxql/src/plan/timestamp.rs
  iox_query_influxql/src/plan/util.rs
  iox_query_influxql/src/plan/var_ref.rs
  service_common/Cargo.toml
  service_common/src/planner.rs
Labels: automerge, query/language/influxql

#7164 revert: streamline CD (#7163)
  .circleci/config.yml
Labels: automerge

#7165 chore: streamline CD
  .circleci/config.yml
Labels: automerge

#7138 feat: compactor metrics for number of split files
  compactor2/src/components/commit/metrics.rs
  compactor2/src/components/divide_initial/mod.rs
  compactor2/src/components/divide_initial/multiple_branches.rs
  compactor2/src/components/files_split/mod.rs
  compactor2/src/components/files_split/non_overlap_split.rs
  compactor2/src/components/files_split/target_level_split.rs
  compactor2/src/components/files_split/upgrade_split.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/ir_planner/planner_v1.rs
  compactor2/src/components/partition_done_sink/metrics.rs
  compactor2/src/components/partition_filter/metrics.rs
  compactor2/src/components/partition_source/metrics.rs
  compactor2/src/components/partitions_source/metrics.rs
  compactor2/src/components/round_info_source/mod.rs
  compactor2/src/components/round_split/many_files.rs
  compactor2/src/components/round_split/mod.rs
  compactor2/src/components/split_or_compact/files_to_compact.rs
  compactor2/src/components/split_or_compact/files_to_split.rs
  compactor2/src/components/split_or_compact/metrics.rs
  compactor2/src/components/split_or_compact/mod.rs
  compactor2/src/driver.rs
  ingester2/src/query/result_instrumentation.rs
  metric/src/counter.rs
  metric/src/histogram.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7166 test: very large input compacting files
  compactor2/src/components/split_or_compact/split_compact.rs
  compactor2/tests/layouts/large_files.rs
  compactor2/tests/layouts/mod.rs
Labels: automerge

#7172 feat: Enable TLS feature so that CLI can speak to https
  Cargo.lock
  client_util/Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge

#7124 chore(compactor2): Assign all rows and sizes in simulator
  compactor2/tests/layouts/core.rs
  compactor2/tests/layouts/knobs.rs
  compactor2/tests/layouts/large_files.rs
  compactor2/tests/layouts/large_overlaps.rs
  compactor2/tests/layouts/many_files.rs
  compactor2_test_utils/src/simulator.rs
Labels: automerge, kodiak: merge.method = 'squash'

#7174 feat: upgrade upgradable files when there are nothing else to compact or split
  compactor2/src/driver.rs
  compactor2/src/file_classification.rs
  compactor2/tests/layouts/large_files.rs
  compactor2/tests/layouts/single_timestamp.rs
Labels: automerge

#7176 test: provide correct input to the limit_files_to_compact function
  compactor2/src/components/split_or_compact/files_to_compact.rs
  compactor2/src/components/split_or_compact/files_to_split.rs
  compactor2/src/components/split_or_compact/split_compact.rs
  compactor2_test_utils/src/lib.rs
Labels: automerge

#7175 chore: Upgrade to Rust 1.68
  influxdb_line_protocol/src/ffi.rs
  ingester/src/buffer_tree/table.rs
  iox_data_generator/src/agent.rs
  iox_query/src/frontend/influxrpc.rs
  mutable_batch/src/column.rs
  mutable_batch/tests/writer.rs
  rust-toolchain.toml
  write_buffer/src/mock.rs
Labels: automerge

#7173 feat: `SchemaAdapterStream` may create virtual columns
  iox_query/src/provider/adapter.rs
  iox_query/src/provider/record_batch_exec.rs
Labels: automerge

#7183 chore: Remove unused dependencies found with cargo-machete @alamb
  Cargo.lock
  compactor2_test_utils/Cargo.toml
  grpc-binary-logger/Cargo.toml
  influxdb_iox_client/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#7161 feat: projection pushdown phys. optimizer
  iox_query/src/physical_optimizer/mod.rs
  iox_query/src/physical_optimizer/projection_pushdown.rs
  iox_query/src/physical_optimizer/test_util.rs
Labels: automerge

#7194 docs: Update dml_handlers module docs
  router/src/dml_handlers/mod.rs
Labels: automerge

#7196 chore: Update dependencies (to fix cargo_audit failures)
  Cargo.lock
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#7178 refactor: move trailing_gaps bit into cursor
  iox_query/src/exec/gapfill/algo.rs
Labels: automerge

#7167 chore: Update datafusion
  Cargo.lock
  Cargo.toml
  iox_query/src/exec/gapfill/mod.rs
  iox_query/src/exec/non_null_checker.rs
  iox_query/src/exec/schema_pivot.rs
  iox_query/src/exec/split.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#7206 chore: opt-in for sparse registry protocol
  .cargo/config
Labels: automerge

#7199 refactor: Rename the filter to reflect exactly what it does
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/mod.rs
  compactor2/src/components/partition_filter/unable_to_compact.rs
  compactor2/src/components/report.rs
  compactor2/src/driver.rs
  compactor2/tests/layouts/large_files.rs
  compactor2/tests/layouts/single_timestamp.rs
Labels: automerge

#7179 refactor: formalize abstraction for building gap filled columns
  iox_query/src/exec/gapfill/algo.rs
Labels: automerge

#7180 feat: further split the smallest possible set to compact but too large to do so
  compactor2/src/components/file_classifier/split_based.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/ir_planner/planner_v1.rs
  compactor2/src/components/partition_filter/greater_size_matching_files.rs
  compactor2/src/components/split_or_compact/files_to_compact.rs
  compactor2/src/components/split_or_compact/large_files_to_split.rs
  compactor2/src/components/split_or_compact/metrics.rs
  compactor2/src/components/split_or_compact/mod.rs
  compactor2/src/components/split_or_compact/split_compact.rs
  compactor2/src/components/split_or_compact/start_level_files_to_split.rs
  compactor2/src/driver.rs
  compactor2/src/file_classification.rs
  compactor2/tests/integration.rs
  compactor2/tests/layouts/core.rs
  compactor2/tests/layouts/knobs.rs
  compactor2/tests/layouts/large_files.rs
  compactor2/tests/layouts/large_overlaps.rs
  compactor2/tests/layouts/many_files.rs
  compactor2/tests/layouts/single_timestamp.rs
  compactor2_test_utils/src/commit_wrapper.rs
  compactor2_test_utils/src/lib.rs
  compactor2_test_utils/src/simulator.rs
Labels: automerge

#7197 fix: Remove the max_compact_size knob and hardcode a multiple
  clap_blocks/src/compactor2.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/report.rs
  compactor2/src/components/split_or_compact/large_files_to_split.rs
  compactor2/src/config.rs
  compactor2/tests/integration.rs
  compactor2/tests/layouts/core.rs
  compactor2/tests/layouts/knobs.rs
  compactor2/tests/layouts/large_files.rs
  compactor2/tests/layouts/large_overlaps.rs
  compactor2/tests/layouts/mod.rs
  compactor2/tests/layouts/single_timestamp.rs
  compactor2_test_utils/src/lib.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ioxd_compactor2/src/lib.rs
Labels: automerge

#7207 chore: Update datafusion pin
  Cargo.lock
  Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#7211 test: compaction output of common use cases
  compactor2/tests/layouts/common_use_cases.rs
  compactor2/tests/layouts/mod.rs
Labels: automerge

#7219 refactor(metric): assert macro import scopes
  compactor2/src/components/commit/metrics.rs
  compactor2/src/components/partition_done_sink/metrics.rs
  compactor2/src/components/partition_filter/metrics.rs
  compactor2/src/components/partition_source/metrics.rs
  compactor2/src/components/partitions_source/metrics.rs
  compactor2/src/components/split_or_compact/metrics.rs
  metric/src/counter.rs
  metric/src/histogram.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7209 feat(wal): segment file reference counting
  ingester2/src/persist/completion_observer.rs
  ingester2/src/wal/mod.rs
  ingester2/src/wal/reference_tracker.rs
  wal/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7182 feat: implement gap fill with previous value
  iox_query/src/exec/gapfill/algo.rs
  iox_query/src/exec/gapfill/exec_tests.rs
Labels: automerge

#7223 feat: debug-log errors during chunk extraction
  iox_query/src/physical_optimizer/chunk_extraction.rs
Labels: automerge

#7212 feat(flightsql): implement basic `CommandGetCatalogs` support
  flightsql/src/cmd.rs
  flightsql/src/planner.rs
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
  influxdb_iox/tests/jdbc_client/Main.java
  influxdb_iox_client/src/client/flightsql.rs
  iox_query/src/exec/context.rs
Labels: automerge, kodiak: merge.method = 'squash'

#7218 feat: more projection pushdown
  iox_query/src/physical_optimizer/projection_pushdown.rs
Labels: automerge

#7213 feat(flightsql): Implement GetDbSchemas metadata API
  Cargo.lock
  flightsql/src/cmd.rs
  flightsql/src/planner.rs
  influxdb_iox/Cargo.toml
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
  influxdb_iox/tests/jdbc_client/Main.java
  influxdb_iox_client/src/client/flightsql.rs
  service_grpc_flight/src/request.rs
Labels: automerge, kodiak: merge.method = 'squash'

#7220 feat(wal): reference tracker metrics
  ingester2/src/wal/reference_tracker.rs
Labels: kodiak: merge.method = 'merge'

#7237 chore: split reference_tracker module into submods
  ingester2/src/wal/reference_tracker/actor.rs
  ingester2/src/wal/reference_tracker/handle.rs
  ingester2/src/wal/reference_tracker/mod.rs
  ingester2/src/wal/reference_tracker/wal_deleter.rs
Labels: kodiak: merge.method = 'merge'

#7231 refactor: `extract_chunks` return arrow schema
  iox_query/src/physical_optimizer/chunk_extraction.rs
  iox_query/src/physical_optimizer/combine_chunks.rs
  iox_query/src/physical_optimizer/dedup/dedup_null_columns.rs
  iox_query/src/physical_optimizer/dedup/dedup_sort_order.rs
  iox_query/src/physical_optimizer/dedup/partition_split.rs
  iox_query/src/physical_optimizer/dedup/remove_dedup.rs
  iox_query/src/physical_optimizer/dedup/time_split.rs
Labels: automerge

#7232 refactor(flightsql): simplfy parameterized statement generation
  flightsql/src/cmd.rs
  flightsql/src/planner.rs
Labels: automerge, kodiak: merge.method = 'squash'

#7236 chore(flightsql): `insta`ize flightsql end to end tests
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
Labels: automerge, kodiak: merge.method = 'squash'

#7224 feat: Don't add a partition to skipped_compactions if it makes progress
  Cargo.lock
  compactor2/Cargo.toml
  compactor2/src/driver.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7243 chore(influxdb_line_protocol): add description to cargo metadata
  influxdb_line_protocol/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#7226 refactor(iox_query): Rename `prepare_sql` to `sql_to_physical_plan`
  flightsql/src/planner.rs
  iox_query/src/exec/context.rs
  iox_query/src/exec/gapfill/mod.rs
  iox_query/src/exec/gapfill/params.rs
  iox_query/src/frontend/sql.rs
Labels: automerge, kodiak: merge.method = 'squash'

#7233 feat: recover desired output sort in in `extract_chunks`
  iox_query/src/physical_optimizer/chunk_extraction.rs
  iox_query/src/physical_optimizer/combine_chunks.rs
  iox_query/src/physical_optimizer/dedup/dedup_null_columns.rs
  iox_query/src/physical_optimizer/dedup/dedup_sort_order.rs
  iox_query/src/physical_optimizer/dedup/partition_split.rs
  iox_query/src/physical_optimizer/dedup/remove_dedup.rs
  iox_query/src/physical_optimizer/dedup/time_split.rs
  iox_query/src/physical_optimizer/projection_pushdown.rs
  iox_query/src/provider/physical.rs
  iox_query/src/provider/record_batch_exec.rs
Labels: automerge

#7240 feat: virtual chunk order col
  data_types/src/lib.rs
  ingester/src/buffer_tree/partition.rs
  ingester/src/query_adaptor.rs
  ingester2/src/buffer_tree/partition.rs
  ingester2/src/query_adaptor.rs
  iox_query/src/lib.rs
  iox_query/src/physical_optimizer/dedup/dedup_null_columns.rs
  iox_query/src/physical_optimizer/dedup/dedup_sort_order.rs
  iox_query/src/physical_optimizer/dedup/partition_split.rs
  iox_query/src/physical_optimizer/dedup/test_util.rs
  iox_query/src/physical_optimizer/dedup/time_split.rs
  iox_query/src/physical_optimizer/predicate_pushdown.rs
  iox_query/src/physical_optimizer/projection_pushdown.rs
  iox_query/src/provider.rs
  iox_query/src/provider/deduplicate.rs
  iox_query/src/provider/physical.rs
  iox_query/src/provider/record_batch_exec.rs
Labels: automerge

#7242 feat(flightsql): Support `GetTableTypes` metadata API
  flightsql/src/cmd.rs
  flightsql/src/planner.rs
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
  influxdb_iox/tests/jdbc_client/Main.java
  influxdb_iox_client/src/client/flightsql.rs
Labels: automerge, kodiak: merge.method = 'squash'

#7244 fix: Rename crate `influxdb_line_protocol` to `influxdb-line-protocol`
  .config/hakari.toml
  Cargo.lock
  data_types/Cargo.toml
  influxdb_iox_client/Cargo.toml
  influxdb_line_protocol/Cargo.toml
  mutable_batch_lp/Cargo.toml
  parquet_to_line_protocol/Cargo.toml
  router/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#7216 feat(authz): authorization service client and write integration
  Cargo.lock
  Cargo.toml
  authz/Cargo.toml
  authz/src/lib.rs
  authz/src/permission.rs
  clap_blocks/Cargo.toml
  clap_blocks/src/authz.rs
  clap_blocks/src/lib.rs
  generated_types/build.rs
  generated_types/protos/influxdata/iox/authz/v1/authz.proto
  generated_types/src/lib.rs
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/src/commands/run/router.rs
  influxdb_iox/src/commands/run/router2.rs
  ioxd_router/Cargo.toml
  ioxd_router/src/lib.rs
  router/Cargo.toml
  router/benches/e2e.rs
  router/src/server/http.rs
  router/tests/common/mod.rs
Labels: automerge

#7241 refactor(iox_query): extract influxrpc planner to its own crate
  Cargo.lock
  Cargo.toml
  iox_query/src/frontend.rs
  iox_query_influxrpc/Cargo.toml
  iox_query_influxrpc/src/lib.rs
  service_common/Cargo.toml
  service_common/src/planner.rs
Labels: automerge, kodiak: merge.method = 'squash'

#7245 feat: add null-as-missing gap filling
  iox_query/src/exec/gapfill/algo.rs
  iox_query/src/exec/gapfill/exec_tests.rs
Labels: automerge

#7252 test: Re-enable running compactor once in step tests
  influxdb_iox/tests/end_to_end_cases/cli.rs
  test_helpers_end_to_end/src/config.rs
  test_helpers_end_to_end/src/mini_cluster.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7238 feat(flightsql): Add `GetTables` metadata endpoint without filters
  flightsql/src/cmd.rs
  flightsql/src/planner.rs
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
  influxdb_iox/tests/jdbc_client/Main.java
  influxdb_iox_client/src/client/flightsql.rs
Labels: automerge

#7198 feat(flightsql): Implement FlightSQL `GetSqlInfo` endpoint
  Cargo.lock
  flightsql/Cargo.toml
  flightsql/src/cmd.rs
  flightsql/src/lib.rs
  flightsql/src/planner.rs
  flightsql/src/sql_info/meta.rs
  flightsql/src/sql_info/mod.rs
  flightsql/src/sql_info/value.rs
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
  influxdb_iox/tests/jdbc_client/Main.java
  influxdb_iox_client/src/client/flightsql.rs
  iox_query/src/exec/context.rs
Labels: automerge

#7267 refactor(router): stateful upstream iter for RPC balancer
  Cargo.lock
  router/Cargo.toml
  router/src/dml_handlers/rpc_write.rs
  router/src/dml_handlers/rpc_write/balancer.rs
  router/src/dml_handlers/rpc_write/circuit_breaking_client.rs
  router/src/dml_handlers/rpc_write/upstream_snapshot.rs
Labels: kodiak: merge.method = 'merge'

#7280 chore(flightsql): Add tests that schema and data matches
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
Labels: automerge

#7268 refactor(router): Utilise builder pattern for construction of `TestContext`s
  router/src/namespace_resolver/ns_autocreation.rs
  router/tests/common/mod.rs
  router/tests/grpc.rs
  router/tests/http.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7276 chore: Update datafusion again
  Cargo.lock
  Cargo.toml
  iox_query_influxql/src/frontend/planner.rs
  predicate/src/lib.rs
  workspace-hack/Cargo.toml
Labels: automerge

#7284 test(ingester): graceful shutdown
  ingester2/tests/common/mod.rs
  ingester2/tests/write.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7291 chore: expose partition_timeout in the compactor simulator
  compactor2_test_utils/src/lib.rs
Labels: automerge

#7286 test: set max_l0_created_at to reasonable values for the tests and al…
  compactor2/src/components/split_or_compact/split_compact.rs
  compactor2/tests/layouts/large_files.rs
  compactor2_test_utils/src/lib.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
  iox_tests/src/catalog.rs
Labels: automerge

#7281 feat(flightsql): Avoid planning Flight queries twice
  flightsql/src/planner.rs
  flightsql/src/sql_info/mod.rs
  flightsql/src/sql_info/value.rs
Labels: automerge, kodiak: merge.method = 'squash'

#7270 test: Add compactor shard e2e tests
  influxdb_iox/tests/end_to_end_cases/compactor.rs
  influxdb_iox/tests/end_to_end_cases/mod.rs
  ioxd_compactor2/src/lib.rs
  test_helpers_end_to_end/src/config.rs
  test_helpers_end_to_end/src/mini_cluster.rs
  test_helpers_end_to_end/src/steps.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7293 chore(compactor/simulator): add data backfill test cases
  compactor2/tests/layouts/many_files.rs
Labels: automerge

#7283 fix(flightsql): Send correct schema in GetFlightInfo for Queries
  Cargo.lock
  arrow_util/src/flight.rs
  arrow_util/src/lib.rs
  flightsql/Cargo.toml
  flightsql/src/planner.rs
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
  service_grpc_flight/src/lib.rs
Labels: automerge

#7289 feat(flightsql): Add filters to `GetTables` metadata endpoint
  flightsql/src/planner.rs
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
  influxdb_iox/tests/jdbc_client/Main.java
  influxdb_iox_client/src/client/flightsql.rs
Labels: automerge

#7181 chore(iox/compactor): add test cases tracking max_l0_created_at
  compactor2/tests/integration.rs
  compactor2/tests/layouts/created_at.rs
  compactor2/tests/layouts/mod.rs
  compactor2_test_utils/src/lib.rs
Labels: automerge

#7230 feat: Teach InfluxQL how to plan an aggregate query
  influxdb_influxql_parser/src/literal.rs
  influxdb_influxql_parser/src/select.rs
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__select_statement-6.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__select_statement-6.snap
  influxdb_influxql_parser/src/visit.rs
  influxdb_influxql_parser/src/visit_mut.rs
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql.expected
  iox_query_influxql/src/frontend/planner.rs
  iox_query_influxql/src/plan/field_mapper.rs
  iox_query_influxql/src/plan/mod.rs
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/planner/select.rs
  iox_query_influxql/src/plan/planner_time_range_expression.rs
  iox_query_influxql/src/plan/rewriter.rs
  iox_query_influxql/src/plan/test_utils.rs
  iox_query_influxql/src/plan/util_copy.rs
  schema/src/lib.rs
  test_helpers_end_to_end/src/client.rs
  test_helpers_end_to_end/src/snapshot_comparison.rs
Labels: automerge, query/language/influxql

#7302 feat(persist): Add hot partition persistence counter metric
  ingester2/src/init.rs
  ingester2/src/persist/hot_partitions.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7288 refactor: non-empty RPC endpoint sets
  router/src/dml_handlers/rpc_write.rs
  router/src/dml_handlers/rpc_write/balancer.rs
  router/src/dml_handlers/rpc_write/upstream_snapshot.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7314 feat(cli): Add namespace delete command
  influxdb_iox/src/commands/namespace/delete.rs
  influxdb_iox/src/commands/namespace/mod.rs
  influxdb_iox/tests/end_to_end_cases/cli.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7305 test: set max_l0_created_at approriately for tests in single_timestamp
  compactor2/tests/layouts/single_timestamp.rs
Labels: automerge

#7264 feat: add version and uuid to startup message
  influxdb_iox/src/commands/run/main.rs
Labels: automerge

#7312 fix: Parse empty single-line comments
  influxdb_influxql_parser/src/common.rs
  influxdb_influxql_parser/src/lib.rs
Labels: automerge, query/language/influxql

#7324 refactor(flightsql): Build `GetTableTypes` response directly from the catalog
  flightsql/src/planner.rs
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
  influxdb_iox_client/src/client/flightsql.rs
Labels: automerge

#7327 refactor(flightsql): Build `GetCatalogs` directly from DataFusion catalog
  flightsql/src/get_catalogs.rs
  flightsql/src/lib.rs
  flightsql/src/planner.rs
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
Labels: automerge

#7329 chore: Update DataFusion again
  Cargo.lock
  Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge

#7317 feat: add interpolation fill strategy to GapFillExec
  iox_query/src/exec/gapfill/algo.rs
  iox_query/src/exec/gapfill/algo/interpolate.rs
  iox_query/src/exec/gapfill/exec_tests.rs
  iox_query/src/exec/gapfill/mod.rs
  iox_query/src/exec/gapfill/params.rs
Labels: automerge

#7325 refactor(flightsql): Build `GetTables` directly from DataFusion catalog
  flightsql/src/get_tables.rs
  flightsql/src/lib.rs
  flightsql/src/planner.rs
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
Labels: automerge

#7340 fix: ensure we don't loose predicates in chunk roundtrips
  iox_query/src/physical_optimizer/chunk_extraction.rs
Labels: automerge

#7350 chore: update `spin` to 0.9.7
  Cargo.lock
Labels: automerge

#7342 refactor(test): generic return iterator
  router/src/dml_handlers/rpc_write.rs
  router/src/dml_handlers/rpc_write/client.rs
Labels: kodiak: merge.method = 'merge'

#7344 test: Add an e2e test for write replication and fix it because it didn't work 😜
  influxdb_iox/tests/end_to_end_cases/ingester.rs
  influxdb_iox/tests/end_to_end_cases/querier/multi_ingester.rs
  ioxd_router/src/lib.rs
  router/src/dml_handlers/rpc_write.rs
  test_helpers_end_to_end/src/config.rs
  test_helpers_end_to_end/src/mini_cluster.rs
Labels: automerge

#7345 docs: update gRPC example
  README.md
Labels: automerge

#7347 feat: add scalar function LOCF
  iox_query/src/logical_optimizer/handle_gapfill.rs
  query_functions/src/gapfill.rs
  query_functions/src/lib.rs
  query_functions/src/registry.rs
Labels: automerge

#7353 chore: Update datafusion again
  Cargo.lock
  Cargo.toml
  iox_query/src/frontend/common.rs
  iox_query/src/logical_optimizer/handle_gapfill.rs
  iox_query/src/logical_optimizer/handle_gapfill/range_predicate.rs
  iox_query/src/logical_optimizer/influx_regex_to_datafusion_regex.rs
  iox_query/src/physical_optimizer/chunk_extraction.rs
  iox_query/src/physical_optimizer/combine_chunks.rs
  iox_query/src/physical_optimizer/dedup/dedup_null_columns.rs
  iox_query/src/physical_optimizer/dedup/dedup_sort_order.rs
  iox_query/src/physical_optimizer/dedup/partition_split.rs
  iox_query/src/physical_optimizer/dedup/remove_dedup.rs
  iox_query/src/physical_optimizer/dedup/time_split.rs
  iox_query/src/physical_optimizer/predicate_pushdown.rs
  iox_query/src/physical_optimizer/projection_pushdown.rs
  iox_query/src/physical_optimizer/sort/redundant_sort.rs
  iox_query/src/physical_optimizer/sort/sort_pushdown.rs
  iox_query/src/physical_optimizer/union/nested_union.rs
  iox_query/src/physical_optimizer/union/one_union.rs
  iox_query/src/util.rs
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/planner_rewrite_expression.rs
  predicate/src/lib.rs
  predicate/src/rpc_predicate.rs
  predicate/src/rpc_predicate/column_rewrite.rs
  predicate/src/rpc_predicate/field_rewrite.rs
  predicate/src/rpc_predicate/measurement_rewrite.rs
  predicate/src/rpc_predicate/rewrite.rs
  predicate/src/rpc_predicate/value_rewrite.rs
  workspace-hack/Cargo.toml
Labels: automerge

#7333 feat: InfluxQL learns the `LOG(x, base)` function
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql.expected
  iox_query_influxql/src/plan/planner.rs
Labels: automerge, query/language/influxql

#7352 test: extend retention policy query test
  influxdb_iox/tests/query_tests2/cases/in/retention.sql.expected
  influxdb_iox/tests/query_tests2/setups.rs
  querier/src/ingester/mod.rs
  querier/src/ingester/test_util.rs
  querier/src/table/mod.rs
  querier/src/table/state_reconciler.rs
Labels: automerge

#7355 feat: more aggressive `CombineChunks`
  iox_query/src/physical_optimizer/combine_chunks.rs
Labels: automerge

#7343 feat(ingester2): Add test coverage for hot partition persistence
  ingester2/src/persist/hot_partitions.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7357 feat(flight): Support influxql queries via JSON encoded tickets
  service_grpc_flight/src/request.rs
Labels: automerge

#7354 chore: Update datafusion + arrow/parquet/arrow-flight to 36
  Cargo.lock
  Cargo.toml
  arrow_util/src/bitset.rs
  arrow_util/src/dictionary.rs
  arrow_util/src/optimize.rs
  arrow_util/src/string.rs
  mutable_batch/src/column.rs
  parquet_file/src/serialize.rs
  workspace-hack/Cargo.toml
Labels: automerge

#7358 feat: update gap fill planner rule to use LOCF
  influxdb_iox/tests/query_tests2/cases/in/gapfill.sql
  influxdb_iox/tests/query_tests2/cases/in/gapfill.sql.expected
  iox_query/src/exec/gapfill/mod.rs
  iox_query/src/logical_optimizer/handle_gapfill.rs
Labels: automerge

#7359 feat: Teach InfluxQL how to process `FILL(null|previous|<value>)`
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql.expected
  influxdb_iox/tests/query_tests2/setups.rs
  iox_query/src/exec.rs
  iox_query/src/exec/gapfill/mod.rs
  iox_query/src/logical_optimizer/handle_gapfill.rs
  iox_query/src/logical_optimizer/handle_gapfill/range_predicate.rs
  iox_query/src/logical_optimizer/mod.rs
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/util.rs
  iox_query_influxql/src/plan/util_copy.rs
Labels: automerge, query/language/influxql

#7362 fix: phys. optimizers must respect sort partitioning
  iox_query/src/physical_optimizer/projection_pushdown.rs
  iox_query/src/physical_optimizer/sort/sort_pushdown.rs
  iox_query/src/physical_optimizer/test_util.rs
Labels: automerge

#7385 test(flightsql): add new test `GetTables` -- ensure returned table_schema can be decoded
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
Labels: automerge

#7386 refactor(flightsql): Build `GetDBSchemas` directly from DataFusion catalog
  flightsql/src/get_db_schemas.rs
  flightsql/src/lib.rs
  flightsql/src/planner.rs
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
Labels: automerge

#7369 feat: Save Parquet file state and check it remains the same before committing compaction
  compactor2/src/compactor.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/driver.rs
  compactor2/src/error.rs
  compactor2/src/partition_info.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7390 revert: Merge pull request #7369
  compactor2/src/compactor.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/driver.rs
  compactor2/src/error.rs
  compactor2/src/partition_info.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7389 chore: move compaction progress notification up (to be more frequent)
  compactor2/src/driver.rs
Labels: automerge

#7392 fix: Only look at the current branch files' status when looking for concurrent modifications
  compactor2/src/compactor.rs
  compactor2/src/components/changed_files_filter/logging.rs
  compactor2/src/components/changed_files_filter/mod.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/mod.rs
  compactor2/src/components/report.rs
  compactor2/src/driver.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7384 feat: allow gap-fill logical opt. to handle inline filters
  iox_query/src/logical_optimizer/handle_gapfill/range_predicate.rs
Labels: automerge

#7351 feat(service_grpc_flight): optional query authorization
  Cargo.lock
  authz/src/lib.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/src/commands/run/querier.rs
  influxdb_iox/src/commands/run/router2.rs
  ioxd_querier/Cargo.toml
  ioxd_querier/src/lib.rs
  ioxd_querier/src/rpc/query.rs
  router/src/server/http.rs
  service_grpc_flight/Cargo.toml
  service_grpc_flight/src/lib.rs
Labels: automerge

#7383 feat: "parquet sortness" optimizer pass
  iox_query/src/config.rs
  iox_query/src/physical_optimizer/sort/mod.rs
  iox_query/src/physical_optimizer/sort/parquet_sortness.rs
Labels: automerge

#7394 fix: default the write cli comment to the http default port.
  influxdb_iox/src/commands/write.rs
  influxdb_iox/src/main.rs
  influxdb_iox_client/README.md
  influxdb_iox_client/src/client/write.rs
Labels: automerge
