Repository influxdata/influxdb_iox, pull requests merged in 2023-07, with the labels that each got.

#8111 refactor: remove `QueryChunk::column_values`
  Cargo.lock
  compactor/Cargo.toml
  compactor/src/components/df_planner/query_chunk.rs
  ingester/Cargo.toml
  ingester/src/query_adaptor.rs
  iox_query/src/lib.rs
  iox_query/src/test.rs
  iox_query_influxrpc/src/lib.rs
  querier/src/ingester/mod.rs
  querier/src/parquet/query_access.rs
Labels: automerge

#8134 chore: manual `cargo update`
  Cargo.lock
  workspace-hack/Cargo.toml
Labels: automerge

#8135 test(e2e): ingester shutdown persist file discovery
  influxdb_iox/tests/end_to_end_cases/querier.rs
  test_helpers_end_to_end/src/config.rs
  test_helpers_end_to_end/src/mini_cluster.rs
  test_helpers_end_to_end/src/server_fixture.rs
  test_helpers_end_to_end/src/steps.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8136 build: don't force tokio_unstable / override user config
  .cargo/config
  executor/src/lib.rs
  influxdb_iox/src/process_info.rs
  tokio_metrics_bridge/build.rs
  tokio_metrics_bridge/src/bridge.rs
  tokio_metrics_bridge/src/lib.rs
Labels: kodiak: merge.method = 'merge'

#8137 feat(querier): Log errors that happen *during* query SQL execution
  service_grpc_flight/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#8145 chore: update heappy to `1de977a241cdd768acc5b6c82c0728b30c7db7b4`
  Cargo.lock
  ioxd_common/Cargo.toml
Labels: automerge

#8058 chore: add test to demonstrate aliasing rules for conflict
  iox_query_influxql/src/plan/rewriter.rs
Labels: automerge, kodiak: merge.method = 'merge', query/language/influxql

#8150 chore: update `hermit-abi` to 0.3.2
  Cargo.lock
Labels: automerge

#8152 refactor: normalize catalog metric names
  iox_catalog/src/metrics.rs
Labels: automerge

#8153 fix: include `PartitionHashId` in size estimations
  data_types/src/lib.rs
  data_types/src/partition.rs
  querier/src/cache/parquet_file.rs
Labels: automerge

#8069 refactor(ingester): Use unsigned sequence number, remove its `Sqlx::Type`
  data_types/src/lib.rs
  data_types/src/sequence_number_set.rs
  ingester/src/init.rs
  ingester/src/init/wal_replay.rs
  ingester/src/test_util.rs
  ingester/src/timestamp_oracle.rs
  ingester/src/wal/reference_tracker/handle.rs
  ingester/src/wal/wal_sink.rs
  ingester_test_ctx/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8154 perf(ingester): projection pushdown to data source
  ingester/Cargo.toml
  ingester/benches/query.rs
  ingester/src/buffer_tree/namespace.rs
  ingester/src/buffer_tree/partition.rs
  ingester/src/buffer_tree/partition/buffer.rs
  ingester/src/buffer_tree/partition/buffer/mutable_buffer.rs
  ingester/src/buffer_tree/partition/buffer/state_machine.rs
  ingester/src/buffer_tree/partition/buffer/state_machine/buffering.rs
  ingester/src/buffer_tree/partition/buffer/state_machine/persisting.rs
  ingester/src/buffer_tree/partition/buffer/state_machine/snapshot.rs
  ingester/src/buffer_tree/partition/buffer/traits.rs
  ingester/src/buffer_tree/root.rs
  ingester/src/buffer_tree/table.rs
  ingester/src/init/graceful_shutdown.rs
  ingester/src/persist/compact.rs
  ingester/src/persist/hot_partitions.rs
  ingester/src/query/exec_instrumentation.rs
  ingester/src/query/mock_query_exec.rs
  ingester/src/query/mod.rs
  ingester/src/query/projection.rs
  ingester/src/query/result_instrumentation.rs
  ingester/src/query/tracing.rs
  ingester/src/query/trait.rs
  ingester/src/query_adaptor.rs
  ingester/src/server/grpc/query.rs
  ingester/tests/query.rs
  ingester/tests/write.rs
  schema/src/builder.rs
  schema/src/merge.rs
Labels: kodiak: merge.method = 'merge'

#8143 feat(influxql): support TOP and BOTTOM functions
  influxdb_iox/tests/query_tests/cases.rs
  influxdb_iox/tests/query_tests/cases/in/top_bottom.influxql
  influxdb_iox/tests/query_tests/cases/in/top_bottom.influxql.expected
  influxdb_iox/tests/query_tests/data/top_bottom.lp
  influxdb_iox/tests/query_tests/setups.rs
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/udaf.rs
Labels: automerge

#8144 fix: send flight keep-alives
  Cargo.lock
  service_grpc_flight/Cargo.toml
  service_grpc_flight/src/keep_alive.rs
  service_grpc_flight/src/lib.rs
Labels: automerge

#8158 fix: return error rather than panic on unsupported predicate
  predicate/src/rpc_predicate/field_rewrite.rs
Labels: automerge, kodiak: merge.method = 'squash'

#8175 Revert "feat(idpe-17789): scheduler job_status()"
  Cargo.lock
  compactor/src/components/combos/mod.rs
  compactor/src/components/combos/tests.rs
  compactor/src/components/combos/throttle_partition.rs
  compactor/src/components/combos/unique_partitions.rs
  compactor/src/components/commit.rs
  compactor/src/components/commit/catalog.rs
  compactor/src/components/commit/logging.rs
  compactor/src/components/commit/metrics.rs
  compactor/src/components/commit/mock.rs
  compactor/src/components/commit/mod.rs
  compactor/src/components/hardcoded.rs
  compactor/src/components/mod.rs
  compactor/src/components/partition_done_sink/catalog.rs
  compactor/src/components/partition_done_sink/error_kind.rs
  compactor/src/components/partition_done_sink/logging.rs
  compactor/src/components/partition_done_sink/metrics.rs
  compactor/src/components/partition_done_sink/mock.rs
  compactor/src/components/partition_done_sink/mod.rs
  compactor/src/components/partition_done_sink/outcome.rs
  compactor/src/components/report.rs
  compactor/src/config.rs
  compactor/src/error.rs
  compactor/src/lib.rs
  compactor_scheduler/Cargo.toml
  compactor_scheduler/src/error.rs
  compactor_scheduler/src/lib.rs
  compactor_scheduler/src/local_scheduler.rs
  compactor_scheduler/src/local_scheduler/partition_done_sink/mod.rs
  compactor_scheduler/src/scheduler.rs
  compactor_test_utils/src/commit_wrapper.rs
  compactor_test_utils/src/lib.rs
  ioxd_compactor/src/lib.rs
  ioxd_compactor/src/scheduler_config.rs
Labels: automerge

#8174 feat: log query and namespace on querier error
  service_grpc_flight/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#8176 chore: add logging when compactor fetches partitions
  compactor_scheduler/src/local_scheduler/partitions_source/catalog_to_compact.rs
Labels: automerge

#8178 chore: unwrap option in log
  compactor_scheduler/src/local_scheduler/partitions_source/catalog_to_compact.rs
Labels: automerge

#8184 fix: InfluxQL planner promotes integer division to floats
  influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql
  influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql.expected
  iox_query_influxql/src/plan/expr_type_evaluator.rs
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/planner_rewrite_expression.rs
  iox_query_influxql/src/plan/rewriter.rs
Labels: automerge, kodiak: merge.method = 'merge', query/language/influxql

#8070 refactor(wal): Remove op-level `sequence_number`, use per table map
  generated_types/protos/influxdata/iox/wal/v1/wal.proto
  influxdb_iox/src/commands/debug/wal/inspect.rs
  ingester/benches/wal.rs
  ingester/src/init/wal_replay.rs
  ingester/src/wal/wal_sink.rs
  wal/src/lib.rs
  wal/src/writer_thread.rs
  wal/tests/end_to_end.rs
  wal_inspect/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8185 refactor: replace `println!` w/ `info!`
  influxdb_iox/src/commands/run/all_in_one.rs
Labels: automerge, kodiak: merge.method = 'squash'

#8067 feat: add `influxdb_iox debug build-catalog` command
  Cargo.lock
  import_export/Cargo.toml
  import_export/src/file/import.rs
  import_export/src/file/mod.rs
  influxdb_iox/src/commands/debug/build_catalog.rs
  influxdb_iox/src/commands/debug/mod.rs
  influxdb_iox/src/commands/remote/store.rs
  influxdb_iox/tests/end_to_end_cases/debug.rs
  test_helpers_end_to_end/src/config.rs
Labels: automerge, kodiak: merge.method = 'squash'

#8189 fix: Plumb tracing header name env/flag to client
  Cargo.lock
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/src/commands/run/querier.rs
  ioxd_querier/src/lib.rs
  querier/Cargo.toml
  querier/src/ingester/flight_client.rs
  querier/src/ingester/mod.rs
Labels: automerge

#8188 test(bench): concurrent ingester partition queries
  ingester/benches/query.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8190 chore: Update DataFusion
  Cargo.lock
  Cargo.toml
  datafusion_util/src/lib.rs
  influxdb_iox/tests/query_tests/cases/in/date_bin.sql.expected
  influxdb_iox/tests/query_tests/cases/in/gapfill.sql.expected
  influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql.expected
  iox_query/src/exec/gapfill/mod.rs
  iox_query/src/logical_optimizer/handle_gapfill.rs
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/udaf.rs
  query_functions/src/registry.rs
  query_functions/src/selectors.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#8094 feat(ingester): Assign individual sequence numbers for writes per partition
  data_types/src/sequence_number_set.rs
  influxdb_iox/tests/end_to_end_cases/debug.rs
  ingester/src/init/wal_replay.rs
  ingester/src/server/grpc/rpc_write.rs
  ingester/src/test_util.rs
  wal/src/lib.rs
  wal/src/writer_thread.rs
  wal/tests/end_to_end.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8187 feat(influxql): PERCENTILE function
  influxdb_iox/tests/query_tests/cases.rs
  influxdb_iox/tests/query_tests/cases/in/percentile.influxql
  influxdb_iox/tests/query_tests/cases/in/percentile.influxql.expected
  influxdb_iox/tests/query_tests/data/percentile.lp
  influxdb_iox/tests/query_tests/setups.rs
  iox_query_influxql/src/aggregate.rs
  iox_query_influxql/src/aggregate/percentile.rs
  iox_query_influxql/src/error.rs
  iox_query_influxql/src/lib.rs
  iox_query_influxql/src/plan/expr_type_evaluator.rs
  iox_query_influxql/src/plan/ir.rs
  iox_query_influxql/src/plan/mod.rs
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/planner/select.rs
  iox_query_influxql/src/plan/rewriter.rs
  iox_query_influxql/src/plan/test_utils.rs
  iox_query_influxql/src/plan/udaf.rs
  iox_query_influxql/src/plan/udf.rs
  iox_query_influxql/src/plan/util.rs
  iox_query_influxql/src/window.rs
  iox_query_influxql/src/window/percent_row_number.rs
Labels: automerge

#8214 fix(all-in-one): Run compactor in all-in-one mode
  compactor/src/driver.rs
  influxdb_iox/src/commands/run/all_in_one.rs
Labels: automerge, kodiak: merge.method = 'squash'

#8215 fix: Implement influxql ExecutionPlan::children
  iox_query_influxql/src/frontend/planner.rs
Labels: automerge

#8219 refactor(ingester): emit spans for query handler
  ingester/src/server/grpc/query.rs
Labels: kodiak: merge.method = 'merge'

#8083 feat: Query the catalog with PartitionHashId if you have it, otherwise with PartitionId
  compactor/src/components/partition_files_source/catalog.rs
  compactor/src/components/partition_source/catalog.rs
  garbage_collector/src/objectstore/checker.rs
  import_export/src/file/import.rs
  ingester/src/buffer_tree/partition.rs
  ingester/src/buffer_tree/partition/resolver/catalog.rs
  ingester/src/buffer_tree/partition/resolver/sort_key.rs
  ingester/src/persist/mod.rs
  ingester/src/persist/worker.rs
  iox_catalog/migrations/20230710141740_partition_hash_id_index.sql
  iox_catalog/sqlite/migrations/20230710141740_partition_hash_id_index.sql
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
  iox_tests/src/catalog.rs
  querier/src/cache/partition.rs
  service_grpc_catalog/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8223 chore: Update datafusion pin
  Cargo.lock
  Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#8222 perf: only send metadata for relevant partitions
  ingester/src/buffer_tree/root.rs
  ingester/src/buffer_tree/table.rs
Labels: kodiak: merge.method = 'merge'

#8224 chore: Add longer sleep in `end_to_end_cases::debug::build_catalog` and extra logging
  influxdb_iox/tests/end_to_end_cases/debug.rs
Labels: automerge, kodiak: merge.method = 'squash'

#8227 fix: ignore flaky `end_to_end_cases::debug::build_catalog` while it is debugged
  influxdb_iox/tests/end_to_end_cases/debug.rs
Labels: automerge, kodiak: merge.method = 'squash'

#8220 feat(router): Propagate tracing spans for RPC write to Ingester
  Cargo.lock
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/src/commands/run/router.rs
  ingester/benches/query.rs
  ingester/benches/write.rs
  ingester/src/server/grpc/rpc_write.rs
  ingester/tests/query.rs
  ingester/tests/write.rs
  ingester_test_ctx/Cargo.toml
  ingester_test_ctx/src/lib.rs
  ioxd_router/src/lib.rs
  querier/src/ingester/mod.rs
  router/Cargo.toml
  router/src/dml_handlers/rpc_write.rs
  router/src/dml_handlers/rpc_write/balancer.rs
  router/src/dml_handlers/rpc_write/circuit_breaking_client.rs
  router/src/dml_handlers/rpc_write/client.rs
  router/src/dml_handlers/rpc_write/lazy_connector.rs
  router/src/server/http.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8233 chore: Update to Rust 1.71
  arrow_util/src/bitset.rs
  cache_system/src/backend/policy/lru.rs
  cache_system/src/backend/policy/mod.rs
  cache_system/src/backend/policy/refresh.rs
  cache_system/src/backend/policy/remove_if.rs
  cache_system/src/backend/policy/ttl.rs
  cache_system/src/loader/mod.rs
  cache_system/src/resource_consumption.rs
  compactor/src/components/df_plan_exec/noop.rs
  compactor/src/components/df_planner/panic.rs
  compactor/src/components/divide_initial/multiple_branches.rs
  compactor/src/components/partition_filter/has_files.rs
  compactor/src/components/round_split/many_files.rs
  compactor/src/components/scratchpad/noop.rs
  grpc-binary-logger/src/middleware.rs
  ingester/benches/wal.rs
  ingester/src/arcmap.rs
  ingester/src/init.rs
  ingester/src/persist/handle.rs
  ingester/src/wal/wal_sink.rs
  iox_query/src/logical_optimizer/handle_gapfill.rs
  iox_query/src/physical_optimizer/combine_chunks.rs
  iox_query/src/physical_optimizer/dedup/dedup_null_columns.rs
  iox_query/src/physical_optimizer/dedup/dedup_sort_order.rs
  iox_query/src/physical_optimizer/dedup/partition_split.rs
  iox_query/src/physical_optimizer/dedup/remove_dedup.rs
  iox_query/src/physical_optimizer/dedup/time_split.rs
  iox_query/src/physical_optimizer/mod.rs
  iox_query/src/physical_optimizer/predicate_pushdown.rs
  iox_query/src/physical_optimizer/projection_pushdown.rs
  iox_query/src/physical_optimizer/sort/parquet_sortness.rs
  iox_query/src/physical_optimizer/union/nested_union.rs
  iox_query/src/physical_optimizer/union/one_union.rs
  iox_query_influxql/src/plan/planner.rs
  mutable_batch/src/payload/filter.rs
  mutable_batch/src/payload/partition.rs
  mutable_batch/tests/writer_fuzz.rs
  router/src/dml_handlers/rpc_write/circuit_breaking_client.rs
  router/src/server/http/write/multi_tenant.rs
  rust-toolchain.toml
Labels: automerge, kodiak: merge.method = 'merge'

#8234 fix: correctly catch field/tag discrepancy
  influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql
  influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql.expected
  iox_query_influxql/src/plan/ir.rs
  iox_query_influxql/src/plan/planner.rs
Labels: automerge

#8186 refactor: some `cache_system` clean-ups
  cache_system/src/backend/policy/integration_tests.rs
  cache_system/src/backend/policy/refresh.rs
  cache_system/src/cache/driver.rs
  cache_system/src/cache/metrics.rs
  cache_system/src/cache/test_util.rs
  cache_system/src/cancellation_safe_future.rs
  cache_system/src/loader/mod.rs
  cache_system/src/loader/test_util.rs
Labels: automerge

#8230 feat: Use PartitionHashId, when present, on QueryChunks
  compactor/src/components/df_planner/query_chunk.rs
  compactor/src/partition_info.rs
  data_types/src/lib.rs
  data_types/src/partition.rs
  ingester/src/buffer_tree/partition.rs
  ingester/src/buffer_tree/root.rs
  ingester/src/persist/compact.rs
  ingester/src/persist/context.rs
  ingester/src/query/result_instrumentation.rs
  ingester/src/query_adaptor.rs
  ingester/src/server/grpc/query.rs
  ingester/src/test_util.rs
  iox_query/src/lib.rs
  iox_query/src/physical_optimizer/dedup/partition_split.rs
  iox_query/src/test.rs
  querier/src/ingester/mod.rs
  querier/src/parquet/creation.rs
  querier/src/parquet/mod.rs
  querier/src/parquet/query_access.rs
  querier/src/table/mod.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8249 fix: recurse through SubqueryAlias when finding gap fill time range
  influxdb_iox/tests/query_tests/cases/in/gapfill.sql
  influxdb_iox/tests/query_tests/cases/in/gapfill.sql.expected
  iox_query/src/logical_optimizer/handle_gapfill/range_predicate.rs
Labels: automerge

#8252 fix: improve error for malformed gap fill query
  influxdb_iox/tests/query_tests/cases/in/gapfill.sql
  influxdb_iox/tests/query_tests/cases/in/gapfill.sql.expected
  iox_query/src/logical_optimizer/handle_gapfill.rs
  iox_query/src/logical_optimizer/handle_gapfill/range_predicate.rs
Labels: automerge, kodiak: merge.method = 'squash'

#8248 feat(influxql): CUMULATIVE_SUM window function
  influxdb_iox/tests/query_tests/cases/in/window_like.influxql
  influxdb_iox/tests/query_tests/cases/in/window_like.influxql.expected
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/rewriter.rs
  iox_query_influxql/src/plan/udf.rs
  iox_query_influxql/src/window.rs
  iox_query_influxql/src/window/cumulative_sum.rs
  iox_query_influxql/src/window/percent_row_number.rs
Labels: automerge

#8258 refactor: cache system code moves
  cache_system/src/backend/policy/integration_tests.rs
  cache_system/src/backend/policy/refresh.rs
  cache_system/src/cache/metrics.rs
  cache_system/src/cache/test_util.rs
  cache_system/src/lib.rs
  cache_system/src/loader/test_util.rs
  cache_system/src/test_util.rs
Labels: automerge

#8260 docs: adjust querier cache docs
  docs/query_processing.md
Labels: automerge

#8237 refactor: refactor `Schemas` type in InfluxQL planner
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/planner_rewrite_expression.rs
  iox_query_influxql/src/plan/util.rs
Labels: automerge, kodiak: merge.method = 'squash'

#8266 chore: upgrade to sqlx 0.7.1
  Cargo.lock
  data_types/Cargo.toml
  data_types/src/columns.rs
  data_types/src/partition_template.rs
  deny.toml
  garbage_collector/Cargo.toml
  iox_catalog/Cargo.toml
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
  sqlx-hotswap-pool/Cargo.toml
  test_helpers_end_to_end/Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge

#8261 chore: update doc to say `remote store get-table`
  influxdb_iox/src/commands/debug/mod.rs
Labels: automerge, kodiak: merge.method = 'squash'

#8265 refactor(influxql): make DERIVATIVE a user-defined window function
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/udaf.rs
  iox_query_influxql/src/plan/udf.rs
  iox_query_influxql/src/window.rs
  iox_query_influxql/src/window/derivative.rs
Labels: automerge

#8269 feat: batch partition catalog requests in querier
  querier/src/cache/partition.rs
  querier/src/parquet/mod.rs
  querier/src/table/mod.rs
Labels: automerge

#8283 revert: batch partition catalog requests in querier (#8269)
  querier/src/cache/partition.rs
  querier/src/parquet/mod.rs
  querier/src/table/mod.rs
Labels: automerge

#8281 fix: `end_to_end_cases::cli::query_ingester` flakyness
  influxdb_iox/tests/end_to_end_cases/cli.rs
Labels: automerge

#8282 fix: use correct error code when querier is shutting down
  Cargo.lock
  compactor/src/components/df_plan_exec/dedicated.rs
  compactor/src/components/parquet_file_sink/dedicated.rs
  compactor/tests/integration.rs
  executor/Cargo.toml
  executor/src/lib.rs
  iox_query/src/exec/context.rs
  iox_query/src/exec/cross_rt_stream.rs
  service_common/Cargo.toml
  service_common/src/error.rs
Labels: automerge

#8285 refactor(catalog): Allow kafka columns to be nullable
  iox_catalog/migrations/20230714154828_make-kafka-columns-nullable.sql
Labels: automerge, kodiak: merge.method = 'merge'

#8274 fix: aggregate fns called on tags should return null
  influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql
  influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql.expected
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/planner/select.rs
  iox_query_influxql/src/plan/planner_rewrite_expression.rs
Labels: automerge, kodiak: merge.method = 'squash'

#8273 chore(docs): add `influxdb_iox debug build-catalog` to debug.md
  docs/README.md
  docs/debug.md
Labels: automerge

#8271 fix: add retry loop to avoid CI flake in build-catalog test
  influxdb_iox/tests/end_to_end_cases/debug.rs
Labels: automerge, kodiak: merge.method = 'squash'

#8247 chore: Update datafusion again
  Cargo.lock
  Cargo.toml
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
  iox_query_influxql/src/aggregate/percentile.rs
  iox_query_influxql/src/plan/util_copy.rs
  iox_query_influxql/src/window/non_negative.rs
  predicate/src/lib.rs
  predicate/src/rpc_predicate/rewrite.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#8288 fix: Remove namespace ID from a partition identifier type
  ingester/src/buffer_tree/partition/resolver/coalesce.rs
Labels: automerge

#8289 fix: Clean up some comments and unused imports that were allowed
  ingester/src/buffer_tree/partition/resolver/cache.rs
  ingester/src/buffer_tree/partition/resolver/coalesce.rs
  ingester/src/buffer_tree/partition/resolver/mod.rs
  ingester/src/buffer_tree/partition/resolver/trait.rs
  ingester/src/buffer_tree/root.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8303 fix(influxql): advanced syntax window functions with selector aggregates
  influxdb_iox/tests/query_tests/cases/in/window_like.influxql
  influxdb_iox/tests/query_tests/cases/in/window_like.influxql.expected
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/rewriter.rs
Labels: automerge

#8284 fix(influxql): fill count aggregates with 0 by default
  influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql
  influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql.expected
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/util.rs
Labels: automerge

#8299 feat: batch partition catalog requests in querier (take 2)
  cache_system/src/loader/batch.rs
  querier/src/cache/partition.rs
  querier/src/parquet/mod.rs
  querier/src/table/mod.rs
Labels: automerge

#8305 fix(ingester): Graceful shutdown must wait for file rotation receiver
  ingester/src/init/graceful_shutdown.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8321 fix: Reject `time` as a tag value for custom partition templates
  data_types/src/partition_template.rs
  router/tests/grpc.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8301 chore: build annotated OCI images
  .circleci/config.yml
  .circleci/docker_build_release.bash
Labels: automerge

#8323 fix: detect empty list in compactor before assert
  compactor/src/driver.rs
Labels: automerge

#8328 chore: manual cargo update
  Cargo.lock
  workspace-hack/Cargo.toml
Labels: automerge

#8327 feat: metrics for sqlx conn pools
  iox_catalog/src/postgres.rs
Labels: automerge

#8324 test(bench): ingester query partition pruning
  ingester/benches/query.rs
  ingester/benches/write.rs
  ingester/tests/query.rs
  ingester/tests/write.rs
  ingester_test_ctx/src/lib.rs
Labels: kodiak: merge.method = 'merge'

#8329 refactor: remove unused projection code
  ingester/src/query_adaptor.rs
Labels: kodiak: merge.method = 'merge'

#8330 feat(router): Expose circuit breaker healthcheck `ERROR_WINDOW` for config
  clap_blocks/src/router.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ioxd_router/src/lib.rs
  router/src/dml_handlers/rpc_write.rs
  router/src/dml_handlers/rpc_write/balancer.rs
  router/src/dml_handlers/rpc_write/circuit_breaker.rs
  router/src/dml_handlers/rpc_write/circuit_breaking_client.rs
  router/tests/common/mod.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8337 fix(ingester): Skip empty writes with no data during WAL replay
  ingester/src/dml_payload/write/op.rs
  ingester/src/init/wal_replay.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8333 perf(ingester): reusable FSM / RecordBatch schemas
  ingester/src/buffer_tree/partition/buffer.rs
  ingester/src/buffer_tree/partition/buffer/state_machine.rs
  ingester/src/buffer_tree/partition/buffer/state_machine/buffering.rs
  ingester/src/buffer_tree/partition/buffer/state_machine/persisting.rs
  ingester/src/buffer_tree/partition/buffer/state_machine/snapshot.rs
  ingester/src/buffer_tree/partition/buffer/traits.rs
Labels: kodiak: merge.method = 'merge'

#8336 fix: remove sqlx "used" metrics
  iox_catalog/src/postgres.rs
Labels: automerge

#8338 fix: compactor loop splitting then undoing it
  compactor/src/components/round_info_source/mod.rs
  compactor/tests/layouts/stuck.rs
Labels: automerge

#8332 feat(gossip): peer exchange
  gossip/proto/gossip.proto
  gossip/src/dispatcher.rs
  gossip/src/lib.rs
  gossip/src/peers.rs
  gossip/src/reactor.rs
  gossip/src/seed.rs
  gossip/tests/smoke.rs
Labels: kodiak: merge.method = 'merge'

#8354 feat(router): Include table/column diff for namespace schema cache update
  data_types/src/lib.rs
  router/src/namespace_cache.rs
  router/src/namespace_cache/memory.rs
  router/src/namespace_cache/metrics.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8339 feat: Make parquet_file.partition_id optional in the catalog
  compactor/src/components/df_planner/query_chunk.rs
  compactor/src/components/parquet_file_sink/mock.rs
  compactor/src/components/partition_files_source/mock.rs
  compactor_scheduler/src/commit/logging.rs
  compactor_scheduler/src/commit/metrics.rs
  compactor_scheduler/src/commit/mock.rs
  compactor_scheduler/tests/local_scheduler/mod.rs
  compactor_test_utils/src/simulator.rs
  data_types/src/lib.rs
  data_types/src/partition.rs
  garbage_collector/src/objectstore/checker.rs
  generated_types/build.rs
  generated_types/protos/influxdata/iox/catalog/v1/parquet_file.proto
  generated_types/protos/influxdata/iox/catalog/v1/partition_identifier.proto
  generated_types/protos/influxdata/iox/catalog/v1/service.proto
  import_export/src/file/export.rs
  import_export/src/file/import.rs
  influxdb_iox/src/commands/remote/store.rs
  influxdb_iox/tests/end_to_end_cases/compactor.rs
  influxdb_iox/tests/end_to_end_cases/remote.rs
  influxdb_iox_client/src/client/catalog.rs
  ingester/src/persist/completion_observer.rs
  ingester/src/persist/file_metrics.rs
  ingester/src/persist/mod.rs
  ingester/src/persist/queue.rs
  ingester/src/test_util.rs
  iox_catalog/migrations/20230726175943_make_parquet_file_partition_id_optional.sql
  iox_catalog/sqlite/migrations/20230726175943_make_parquet_file_partition_id_optional.sql
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
  iox_tests/src/builders.rs
  iox_tests/src/catalog.rs
  iox_tests/src/lib.rs
  parquet_file/src/lib.rs
  parquet_file/src/metadata.rs
  querier/src/cache/parquet_file.rs
  querier/src/cache/partition.rs
  querier/src/ingester/mod.rs
  querier/src/parquet/creation.rs
  querier/src/parquet/mod.rs
  querier/src/parquet/query_access.rs
  querier/src/table/mod.rs
  service_grpc_catalog/src/lib.rs
  service_grpc_object_store/src/lib.rs
Labels: automerge

#8374 refactor(tracker): Return disk usage watcher from `DiskUsageMetrics`
  Cargo.lock
  ingester/src/init.rs
  tracker/Cargo.toml
  tracker/src/disk_metric.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8345 fix: re-design LRU cache to be deadlock-free
  Cargo.lock
  cache_system/Cargo.toml
  cache_system/src/backend/policy/integration_tests.rs
  cache_system/src/backend/policy/lru.rs
  cache_system/src/backend/policy/mod.rs
  cache_system/src/resource_consumption.rs
  querier/src/cache/mod.rs
  querier/src/cache/ram.rs
Labels: automerge

#8363 fix: compaction looping fixes
  compactor/src/components/round_info_source/mod.rs
  compactor/src/components/split_or_compact/start_level_files_to_split.rs
  compactor/tests/integration.rs
  compactor/tests/layouts/backfill.rs
  compactor/tests/layouts/many_files.rs
  compactor/tests/layouts/stuck.rs
Labels: automerge

#8362 perf(ingester): persisting list & cached statistics
  ingester/src/buffer_tree/partition.rs
  ingester/src/buffer_tree/partition/buffer/mutable_buffer.rs
  ingester/src/buffer_tree/partition/buffer/state_machine.rs
  ingester/src/buffer_tree/partition/persisting.rs
  ingester/src/buffer_tree/partition/persisting_list.rs
Labels: kodiak: merge.method = 'merge'

#8372 feat: optional gossip clustering for router/ingester
  Cargo.lock
  clap_blocks/src/gossip.rs
  clap_blocks/src/ingester.rs
  clap_blocks/src/lib.rs
  clap_blocks/src/router.rs
  gossip/src/dispatcher.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/src/commands/run/router.rs
  ingester/Cargo.toml
  ingester/src/init.rs
  ingester/src/lib.rs
  ingester_test_ctx/src/lib.rs
  ioxd_ingester/src/lib.rs
  ioxd_router/Cargo.toml
  ioxd_router/src/lib.rs
  router/Cargo.toml
  router/src/server.rs
Labels: kodiak: merge.method = 'merge'

#8355 chore: Update datafusion
  Cargo.lock
  Cargo.toml
  influxdb_iox/tests/query_tests/cases/in/gapfill.sql.expected
  iox_query/src/logical_optimizer/handle_gapfill.rs
  iox_query_influxql/src/plan/planner.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'
