Repository influxdata/influxdb_iox, pull requests merged in 2023-06, with the labels that each got.

#7905 refactor: remove unused PG indices (round 2)
  iox_catalog/migrations/20230601130730_remove_unused_parquet_file_indices_2.sql
Labels: automerge

#7903 test: reproducer for panic bug attempt to calculate the remainder with a divisor of zero
  influxdb_iox/tests/query_tests/sql_errors.rs
Labels: automerge

#7904 feat: aggregator for DataFusion statistics
  iox_query/src/statistics.rs
Labels: automerge

#7907 refactor: faster PG `ParquetFileRepo`
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
  iox_tests/src/catalog.rs
Labels: automerge

#7913 refactor: Move time range simplification to InfluxQL parser module
  Cargo.lock
  influxdb_influxql_parser/Cargo.toml
  influxdb_influxql_parser/src/expression/arithmetic.rs
  influxdb_influxql_parser/src/lib.rs
  influxdb_influxql_parser/src/literal.rs
  influxdb_influxql_parser/src/time_range.rs
  influxdb_influxql_parser/src/timestamp.rs
  iox_query_influxql/Cargo.toml
  iox_query_influxql/src/plan/error.rs
  iox_query_influxql/src/plan/mod.rs
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/planner_rewrite_expression.rs
  iox_query_influxql/src/plan/planner_time_range_expression.rs
Labels: automerge, kodiak: merge.method = 'merge', query/language/influxql

#7908 refactor: migrate `iox_query` to use DataFusion statistics
  compactor/src/components/df_planner/query_chunk.rs
  ingester/src/query_adaptor.rs
  iox_query/src/lib.rs
  iox_query/src/provider/overlap.rs
  iox_query/src/provider/physical.rs
  iox_query/src/provider/record_batch_exec.rs
  iox_query/src/pruning.rs
  iox_query/src/statistics.rs
  iox_query/src/test.rs
  iox_query/src/util.rs
  querier/src/ingester/mod.rs
  querier/src/ingester/test_util.rs
  querier/src/parquet/creation.rs
  querier/src/parquet/mod.rs
  querier/src/parquet/query_access.rs
Labels: automerge

#7906 fix(partitioner): no invalid partitioner panic
  Cargo.lock
  data_types/src/partition_template.rs
  mutable_batch/Cargo.toml
  mutable_batch/src/payload.rs
  mutable_batch/src/payload/partition.rs
  mutable_batch/tests/writer_fuzz.rs
  mutable_batch_pb/tests/encode.rs
  router/src/dml_handlers/partitioner.rs
  router/src/server/http.rs
  router/tests/grpc.rs
Labels: kodiak: merge.method = 'merge'

#7914 test(bench): router partitioner
  router/Cargo.toml
  router/benches/partitioner.rs
  router/benches/schema_validator.rs
Labels: kodiak: merge.method = 'merge'

#7911 fix: update proto path for parquet meta script
  scripts/parquet-meta-iox
Labels: automerge

#7920 build: bump Rust version
  cache_system/src/cancellation_safe_future.rs
  flightsql/src/sql_info/value.rs
  garbage_collector/src/server.rs
  influxdb_iox/tests/end_to_end_cases/cli.rs
  influxdb_iox/tests/end_to_end_cases/ingester.rs
  influxdb_iox/tests/end_to_end_cases/querier/multi_ingester.rs
  influxdb_tsm/src/mapper.rs
  iox_query/src/util.rs
  rust-toolchain.toml
  test_helpers/src/timeout.rs
  trogging/src/cli.rs
  trogging/src/lib.rs
Labels: automerge, build, kodiak: merge.method = 'merge'

#7926 perf: pre-allocate partition key string buffer
  mutable_batch/src/payload/partition.rs
  router/tests/grpc.rs
Labels: kodiak: merge.method = 'merge'

#7910 refactor: replace namespace with database for flight proto
  generated_types/protos/influxdata/iox/querier/v1/flight.proto
  influxdb_iox_client/src/client/flight/mod.rs
  service_grpc_flight/src/lib.rs
  service_grpc_flight/src/request.rs
Labels: automerge, incompatible protobuf

#7916 chore: Update DataFusion pin
  Cargo.lock
  Cargo.toml
  influxdb_iox/tests/query_tests/cases/in/date_bin.sql.expected
  influxdb_iox/tests/query_tests/cases/in/duplicates_parquet.sql.expected
  influxdb_iox/tests/query_tests/cases/in/gapfill.sql.expected
  iox_query/src/exec/gapfill/mod.rs
  iox_query/src/logical_optimizer/handle_gapfill.rs
  iox_query/src/physical_optimizer/predicate_pushdown.rs
  iox_query/src/physical_optimizer/projection_pushdown.rs
  iox_query/src/physical_optimizer/sort/parquet_sortness.rs
  iox_query/src/provider/physical.rs
  iox_query/src/pruning.rs
  iox_query_influxql/src/plan/planner.rs
  parquet_file/src/storage.rs
  parquet_to_line_protocol/src/lib.rs
  predicate/src/delete_expr.rs
  predicate/src/lib.rs
  predicate/src/rpc_predicate/rewrite.rs
  workspace-hack/Cargo.toml
Labels: automerge

#7934 fix: Subqueries respect parent time ranges
  influxdb_influxql_parser/src/expression/conditional.rs
  influxdb_influxql_parser/src/time_range.rs
  influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql
  influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql.expected
  iox_query_influxql/src/plan/ir.rs
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/planner_time_range_expression.rs
  iox_query_influxql/src/plan/rewriter.rs
Labels: automerge, kodiak: merge.method = 'merge', query/language/influxql

#7882 fix: Adding tag columns used in a table partition template in a transaction with table creation
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
  service_grpc_table/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7939 perf: strftime partitioner caching
  mutable_batch/src/payload/partition.rs
  mutable_batch/src/payload/partition/strftime.rs
Labels: kodiak: merge.method = 'merge'

#7930 feat: Validate custom partition templates on their creation
  Cargo.lock
  data_types/Cargo.toml
  data_types/src/partition_template.rs
  ingester_test_ctx/src/lib.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
  mutable_batch/src/payload/partition.rs
  router/benches/partitioner.rs
  router/tests/grpc.rs
  service_grpc_namespace/src/lib.rs
  service_grpc_table/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7942 chore: Update DataFusion, arrow, object_store pins
  Cargo.lock
  Cargo.toml
  compactor/src/object_store/ignore_writes.rs
  compactor/src/object_store/metrics.rs
  flightsql/src/cmd.rs
  flightsql/src/planner.rs
  garbage_collector/src/objectstore/checker.rs
  garbage_collector/src/objectstore/deleter.rs
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
  influxdb_iox/tests/query_tests/cases/in/gapfill.sql.expected
  influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql.expected
  influxdb_iox_client/src/client/flightsql.rs
  ingester/src/server/grpc/query.rs
  iox_query/src/physical_optimizer/sort/parquet_sortness.rs
  iox_query/src/test.rs
  object_store_metrics/src/dummy.rs
  object_store_metrics/src/lib.rs
  parquet_file/src/storage.rs
  parquet_file/src/writer.rs
  querier/src/cache/object_store.rs
  service_grpc_flight/src/lib.rs
  service_grpc_flight/src/request.rs
  workspace-hack/Cargo.toml
Labels: automerge

#7957 refactor: remove unused replication proto
  generated_types/build.rs
  generated_types/protos/influxdata/iox/ingester/v1/replication.proto
Labels: kodiak: merge.method = 'merge'

#7941 feat: Allow passing service protection limits in create db gRPC call
  data_types/src/lib.rs
  generated_types/protos/influxdata/iox/namespace/v1/service.proto
  influxdb_iox/src/commands/namespace/create.rs
  influxdb_iox/src/commands/namespace/update_limit.rs
  influxdb_iox/tests/end_to_end_cases/cli.rs
  influxdb_iox/tests/end_to_end_cases/namespace.rs
  influxdb_iox_client/src/client/namespace.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
  iox_tests/src/catalog.rs
  router/src/namespace_cache/read_through_cache.rs
  router/src/namespace_resolver.rs
  router/src/namespace_resolver/ns_autocreation.rs
  router/tests/grpc.rs
  router/tests/http.rs
  service_grpc_namespace/src/lib.rs
  service_grpc_table/src/lib.rs
Labels: automerge

#7949 chore: use upstream FlightSQL metadata implementation
  flightsql/src/get_catalogs.rs
  flightsql/src/get_db_schemas.rs
  flightsql/src/get_tables.rs
  flightsql/src/lib.rs
  flightsql/src/planner.rs
  flightsql/src/sql_info/mod.rs
  service_common/src/planner.rs
  service_grpc_flight/src/lib.rs
Labels: automerge

#7956 docs: Remove TODO comment that's TODONE
  data_types/src/partition_template.rs
Labels: automerge

#7959 refactor: Extract a test helper method for creating ParquetFileParams
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
Labels: automerge

#7972 chore: update CI and prod image to Debian 12 / bookworm
  Dockerfile
  docker/Dockerfile.ci
  trace_exporters/README.md
Labels: automerge

#7975 feat: catalog parquet file cache TTL
  cache_system/src/backend/policy/ttl.rs
  querier/src/cache/parquet_file.rs
Labels: automerge

#7980 chore: fix JDK for integration tests
  .circleci/config.yml
  docker/Dockerfile.ci
Labels: automerge

#7961 feat: bound partition key size
  Cargo.lock
  data_types/src/partition_template.rs
  mutable_batch/Cargo.toml
  mutable_batch/src/payload/partition.rs
  mutable_batch/src/payload/partition/strftime.rs
Labels: kodiak: merge.method = 'merge'

#7979 refactor(ingester): Add `data_types` module with `IngestOp` enumeration
  ingester/src/dml_payload/ingest_op.rs
  ingester/src/dml_payload/mod.rs
  ingester/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7988 fix: deploy_release after debian upgrade
  .circleci/config.yml
Labels: automerge

#7991 chore: prune mockito dependencies
  Cargo.lock
  client_util/Cargo.toml
  deny.toml
  influxdb2_client/Cargo.toml
Labels: automerge

#7990 refactor: remove `procspawn`
  Cargo.lock
  service_grpc_influxrpc/Cargo.toml
  service_grpc_influxrpc/src/lib.rs
  service_grpc_influxrpc/src/service.rs
  service_grpc_influxrpc/src/test_util.rs
  service_grpc_influxrpc/tests/log_on_panic.rs
  workspace-hack/Cargo.toml
Labels: automerge

#7993 chore: minimize proptest features
  Cargo.lock
  data_types/Cargo.toml
  influxdb_iox/Cargo.toml
  mutable_batch/Cargo.toml
  router/Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge

#7994 revert: #7953
  mutable_batch/src/payload/partition.rs
  mutable_batch/src/payload/partition/strftime.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7989 refactor: cache slices instead of vecs
  querier/src/cache/namespace.rs
  querier/src/cache/parquet_file.rs
  querier/src/cache/partition.rs
  querier/src/cache/projected_schema.rs
  querier/src/parquet/creation.rs
  querier/src/parquet/mod.rs
Labels: automerge

#7987 feat: cache partition template in querier
  Cargo.lock
  data_types/src/partition_template.rs
  iox_tests/Cargo.toml
  iox_tests/src/catalog.rs
  querier/Cargo.toml
  querier/src/cache/namespace.rs
  querier/src/cache/partition.rs
  querier/src/cache/projected_schema.rs
  querier/src/ingester/mod.rs
  querier/src/namespace/test_util.rs
  querier/src/parquet/mod.rs
Labels: automerge

#7995 chore: add compactor option to disable scratchpad
  clap_blocks/src/compactor.rs
  compactor/src/components/hardcoded.rs
  compactor/src/components/report.rs
  compactor/src/config.rs
  compactor_test_utils/src/lib.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ioxd_compactor/src/lib.rs
Labels: automerge

#8000 chore: Match InfluxQL OG time range behaviour when gap filling
  influxdb_influxql_parser/src/common.rs
  influxdb_influxql_parser/src/expression/conditional.rs
  influxdb_influxql_parser/src/lib.rs
  influxdb_influxql_parser/src/time_range.rs
  iox_query_influxql/src/plan/ir.rs
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/planner_time_range_expression.rs
  iox_query_influxql/src/plan/rewriter.rs
Labels: automerge, kodiak: merge.method = 'merge', query/language/influxql

#8002 feat: cache decoded partition value ranges
  data_types/src/lib.rs
  querier/src/cache/partition.rs
Labels: automerge

#7981 chore: Update `datafusion` and other dependencies
  Cargo.lock
  Cargo.toml
  influxdb_iox/tests/query_tests/cases/in/duplicates_parquet_50.sql.expected
  iox_query/src/exec/context.rs
  iox_query/src/physical_optimizer/chunk_extraction.rs
  iox_query/src/physical_optimizer/predicate_pushdown.rs
  iox_query/src/physical_optimizer/projection_pushdown.rs
  iox_query/src/physical_optimizer/sort/parquet_sortness.rs
  iox_query/src/provider/physical.rs
  iox_query/src/test.rs
  iox_query_influxql/src/plan/planner.rs
  parquet_file/src/chunk.rs
  parquet_file/src/storage.rs
  parquet_to_line_protocol/src/lib.rs
  querier/src/namespace/query_access.rs
  query_functions/src/gapfill.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#8014 chore: Update DataFusion and other dependencies
  Cargo.lock
  Cargo.toml
  iox_query/src/logical_optimizer/influx_regex_to_datafusion_regex.rs
  iox_query/src/physical_optimizer/predicate_pushdown.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash', dependencies

#8012 chore: add L1/L2 accumulated size test
  compactor/tests/layouts/accumulated_size.rs
  compactor/tests/layouts/mod.rs
Labels: automerge

#7997 fix(lp parser): adjust parsing tagsets: better error message and error on corner case
  influxdb_line_protocol/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#8009 chore(garbage-collector): increase batch size for clearing deleted files
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
Labels: automerge, kodiak: merge.method = 'squash'

#8024 chore: bump `max_connections` for integration test PG
  .circleci/config.yml
Labels: automerge

#8003 refactor: restore partition key generation dedupe
  Cargo.lock
  mutable_batch/src/payload/partition.rs
  mutable_batch/src/payload/partition/strftime.rs
  router/Cargo.toml
  router/src/dml_handlers/partitioner.rs
Labels: kodiak: merge.method = 'merge'

#8025 feat: query support for custom partitioning
  influxdb_iox/src/commands/namespace/create.rs
  influxdb_iox/tests/end_to_end_cases/namespace.rs
  influxdb_iox/tests/query_tests/cases.rs
  influxdb_iox/tests/query_tests/cases/in/custom_partitioning.sql
  influxdb_iox/tests/query_tests/cases/in/custom_partitioning.sql.expected
  influxdb_iox/tests/query_tests/setups.rs
  influxdb_iox_client/src/client.rs
  influxdb_iox_client/src/client/namespace.rs
  influxdb_iox_client/src/client/table.rs
  querier/src/cache/partition.rs
  querier/src/df_stats.rs
  querier/src/ingester/mod.rs
  querier/src/ingester/test_util.rs
  querier/src/lib.rs
  querier/src/parquet/creation.rs
  querier/src/parquet/mod.rs
  querier/src/table/mod.rs
  querier/src/table/test_util.rs
Labels: automerge

#8032 docs: Update docs about the relationship between the IOx client protocol, FlightSQL and InfluxQL
  service_grpc_flight/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#8036 chore: Update datafusion + arrow/arrow-flight/parquet to version `42.0.0`
  Cargo.lock
  Cargo.toml
  iox_query/src/exec/context.rs
  iox_query/src/exec/gapfill/mod.rs
  iox_query/src/exec/non_null_checker.rs
  iox_query/src/exec/schema_pivot.rs
  iox_query/src/exec/split.rs
  iox_query/src/provider/deduplicate.rs
  iox_query/src/provider/record_batch_exec.rs
  iox_query/src/test.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#8039 fix: compactor stuck looping with unproductive compactions (needs vertical split)
  compactor/src/components/divide_initial/multiple_branches.rs
  compactor/src/components/round_info_source/mod.rs
  compactor/tests/layouts/backfill.rs
  compactor/tests/layouts/large_overlaps.rs
  compactor/tests/layouts/mod.rs
  compactor/tests/layouts/stuck.rs
Labels: automerge

#8041 Revert "fix: compactor stuck looping with unproductive compactions (needs vertical split)"
  compactor/src/components/divide_initial/multiple_branches.rs
  compactor/src/components/round_info_source/mod.rs
  compactor/tests/layouts/backfill.rs
  compactor/tests/layouts/large_overlaps.rs
  compactor/tests/layouts/mod.rs
  compactor/tests/layouts/stuck.rs
Labels: automerge

#8043 chore: Update pest as 2.6.1 was yanked
  Cargo.lock
Labels: automerge, dependencies

#8023 feat: Support `moving_average`, `difference` and `non_negative_difference`
  Cargo.lock
  influxdb_iox/tests/query_tests/cases.rs
  influxdb_iox/tests/query_tests/cases/in/window_like.influxql
  influxdb_iox/tests/query_tests/cases/in/window_like.influxql.expected
  influxdb_iox/tests/query_tests/data/window_like.lp
  influxdb_iox/tests/query_tests/setups.rs
  iox_query_influxql/Cargo.toml
  iox_query_influxql/src/plan/mod.rs
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/rewriter.rs
  iox_query_influxql/src/plan/udaf.rs
  iox_query_influxql/src/plan/udf.rs
  iox_query_influxql/src/plan/util_copy.rs
Labels: automerge, kodiak: merge.method = 'merge', query/language/influxql

#8034 refactor: remove dead querier code
  querier/src/cache/mod.rs
  querier/src/cache/object_store.rs
  querier/src/database.rs
  querier/src/handler.rs
  querier/src/ingester/test_util.rs
  querier/src/lib.rs
  querier/src/poison.rs
  querier/src/table/mod.rs
Labels: automerge

#8045 refactor: clean up querier server interface
  Cargo.lock
  ioxd_querier/Cargo.toml
  ioxd_querier/src/lib.rs
  querier/Cargo.toml
  querier/src/server.rs
Labels: automerge

#8046 refactor: remove querier state reconciler
  querier/src/ingester/mod.rs
  querier/src/parquet/creation.rs
  querier/src/parquet/mod.rs
  querier/src/table/mod.rs
  querier/src/table/state_reconciler.rs
  querier/src/table/state_reconciler/interface.rs
Labels: automerge

#8047 refactor: clean up rustflags and build args
  .cargo/config
  .circleci/config.yml
  Dockerfile
Labels: automerge

#8031 feat(ingester): Replace `DmlOperation` with `IngestOp` in RPC write path
  Cargo.lock
  ingester/Cargo.toml
  ingester/benches/wal.rs
  ingester/benches/write.rs
  ingester/src/buffer_tree/namespace.rs
  ingester/src/buffer_tree/root.rs
  ingester/src/dml_payload/encode.rs
  ingester/src/dml_payload/ingest_op.rs
  ingester/src/dml_payload/mod.rs
  ingester/src/dml_payload/write/mod.rs
  ingester/src/dml_payload/write/op.rs
  ingester/src/dml_payload/write/partitioned_data.rs
  ingester/src/dml_payload/write/table_data.rs
  ingester/src/dml_sink/instrumentation.rs
  ingester/src/dml_sink/mock_sink.rs
  ingester/src/dml_sink/tracing.rs
  ingester/src/dml_sink/trait.rs
  ingester/src/init/wal_replay.rs
  ingester/src/lib.rs
  ingester/src/persist/handle.rs
  ingester/src/persist/mod.rs
  ingester/src/server/grpc/rpc_write.rs
  ingester/src/test_util.rs
  ingester/src/wal/mod.rs
  ingester/src/wal/traits.rs
  ingester/src/wal/wal_sink.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8049 Revert "chore: Update datafusion + arrow/arrow-flight/parquet to version `42.0.0` (#8036)"
  Cargo.lock
  Cargo.toml
  iox_query/src/exec/context.rs
  iox_query/src/exec/gapfill/mod.rs
  iox_query/src/exec/non_null_checker.rs
  iox_query/src/exec/schema_pivot.rs
  iox_query/src/exec/split.rs
  iox_query/src/provider/deduplicate.rs
  iox_query/src/provider/record_batch_exec.rs
  iox_query/src/test.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#8048 fix: `tokio_unstable` for Linux x64
  .cargo/config
Labels: automerge

#8035 feat(compactor): partition fetch query rate limit
  clap_blocks/src/compactor.rs
  compactor/src/components/hardcoded.rs
  compactor/src/components/partition_files_source/catalog.rs
  compactor/src/components/partition_files_source/mod.rs
  compactor/src/components/partition_files_source/rate_limit.rs
  compactor/src/components/report.rs
  compactor/src/config.rs
  compactor_test_utils/src/lib.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ioxd_compactor/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7963 feat: Start generating PartitionHashIds
  Cargo.lock
  arrow_util/src/test_util.rs
  compactor/src/components/parquet_file_sink/mock.rs
  compactor/src/components/parquet_file_sink/object_store.rs
  compactor/src/components/partition_info_source/sub_sources.rs
  compactor/src/components/scratchpad/prod.rs
  compactor/src/components/scratchpad/test_util.rs
  compactor/src/components/scratchpad/util.rs
  compactor/src/partition_info.rs
  compactor/src/test_utils.rs
  compactor_test_utils/src/lib.rs
  compactor_test_utils/src/simulator.rs
  data_types/Cargo.toml
  data_types/src/lib.rs
  data_types/src/partition.rs
  garbage_collector/src/objectstore/checker.rs
  garbage_collector/src/objectstore/deleter.rs
  ingester/src/buffer_tree/partition.rs
  ingester/src/buffer_tree/partition/resolver/cache.rs
  ingester/src/buffer_tree/partition/resolver/catalog.rs
  ingester/src/buffer_tree/table.rs
  ingester/src/persist/completion_observer.rs
  ingester/src/persist/context.rs
  ingester/src/persist/file_metrics.rs
  ingester/src/persist/mod.rs
  ingester/src/persist/worker.rs
  ingester/src/query/partition_response.rs
  ingester/src/query/result_instrumentation.rs
  ingester/src/server/grpc/query.rs
  ingester/src/test_util.rs
  ingester/src/wal/reference_tracker/handle.rs
  ingester_query_grpc/protos/influxdata/iox/ingester/v1/query.proto
  iox_catalog/migrations/20230417173102_deterministic_partition_id.sql
  iox_catalog/sqlite/migrations/20230417173102_deterministic_partition_id.sql
  iox_catalog/src/lib.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
  iox_tests/src/builders.rs
  iox_tests/src/catalog.rs
  parquet_file/src/lib.rs
  parquet_file/src/metadata.rs
  parquet_file/src/storage.rs
  parquet_file/tests/metadata.rs
  querier/src/cache/parquet_file.rs
  querier/src/ingester/mod.rs
  querier/src/table/test_util.rs
  service_grpc_catalog/src/lib.rs
  service_grpc_object_store/src/lib.rs
  test_helpers_end_to_end/src/snapshot_comparison.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8052 fix: do not use empty `RUSTFLAGS` for docker build
  Dockerfile
Labels: automerge

#8054 fix: do not exclude cargo configs in docker build
  Dockerfile.dockerignore
Labels: automerge

#8053 feat: wrap flight DoGet ticket in "Any"
  service_grpc_flight/src/request.rs
Labels: automerge

#8016 feat: basic non-aggregates w/ InfluxQL selector functions
  influxdb_iox/tests/query_tests/cases/in/influxql_metadata.influxql.expected
  influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql
  influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql.expected
  influxdb_iox/tests/query_tests/setups.rs
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/util.rs
Labels: automerge

#8033 docs: query processing
  docs/README.md
  docs/query_processing.md
  iox_query/README.md
Labels: automerge

#8056 fix: compactor stuck looping with unproductive compactions (needs vertical split)
  compactor/src/components/divide_initial/multiple_branches.rs
  compactor/src/components/file_classifier/split_based.rs
  compactor/src/components/hardcoded.rs
  compactor/src/components/round_info_source/mod.rs
  compactor/src/components/split_or_compact/files_to_compact.rs
  compactor/src/components/split_or_compact/metrics.rs
  compactor/src/components/split_or_compact/split_compact.rs
  compactor/src/round_info.rs
  compactor/tests/layouts/accumulated_size.rs
  compactor/tests/layouts/backfill.rs
  compactor/tests/layouts/knobs.rs
  compactor/tests/layouts/large_overlaps.rs
  compactor/tests/layouts/many_files.rs
  compactor/tests/layouts/mod.rs
  compactor/tests/layouts/stuck.rs
Labels: automerge

#8062 refactor: set up jemalloc metrics in a more central place
  influxdb_iox/src/commands/run/main.rs
  influxdb_iox/src/jemalloc.rs
  influxdb_iox/src/main.rs
  influxdb_iox/src/process_info.rs
Labels: automerge

#8064 docs: add counter-example back
  docs/query_processing.md
Labels: automerge, kodiak: merge.method = 'merge'

#8018 feat: Add catalog method for looking up partitions by their hash ID
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
Labels: automerge

#8082 fix: compactor loop on L1 files
  compactor/src/components/round_info_source/mod.rs
  compactor/src/components/split_or_compact/files_to_compact.rs
  compactor/src/driver.rs
  compactor/tests/layouts/backfill.rs
  compactor/tests/layouts/many_files.rs
  compactor/tests/layouts/stuck.rs
Labels: automerge

#8080 fix: panics in querier->ingester circuit breaker
  querier/src/ingester/circuit_breaker.rs
Labels: automerge

#8061 fix: do not override all rustflags in circleci
  .circleci/config.yml
Labels: automerge

#8090 refactor: gather column ranges after decoding
  querier/src/ingester/mod.rs
  querier/src/ingester/test_util.rs
  querier/src/lib.rs
  querier/src/parquet/creation.rs
  querier/src/table/test_util.rs
Labels: automerge

#8093 refactor: single entry point for partition cache
  querier/src/cache/partition.rs
  querier/src/ingester/mod.rs
  querier/src/parquet/creation.rs
Labels: automerge

#8101 fix: compactor shouldn't leave small L1s in non-overlap leading edge pattern
  compactor/src/components/files_split/non_overlap_split.rs
  compactor/src/components/hardcoded.rs
  compactor/src/file_group.rs
  compactor/tests/layouts/accumulated_size.rs
  compactor/tests/layouts/backfill.rs
  compactor/tests/layouts/common_use_cases.rs
  compactor/tests/layouts/core.rs
  compactor/tests/layouts/knobs.rs
  compactor/tests/layouts/large_files.rs
  compactor/tests/layouts/many_files.rs
  compactor_test_utils/src/lib.rs
Labels: automerge

#8098 fix: Use modern form of read_window_aggregate RPC request in `influxdb_iox storage`
  influxdb_iox/src/commands/storage.rs
Labels: automerge, kodiak: merge.method = 'squash'

#8103 feat(influxql): add derivative and non_negative_derivative
  influxdb_iox/tests/query_tests/cases/in/window_like.influxql
  influxdb_iox/tests/query_tests/cases/in/window_like.influxql.expected
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/udaf.rs
  iox_query_influxql/src/plan/udf.rs
Labels: automerge

#8102 refactor: bundle partition cache requests
  querier/src/cache/mod.rs
  querier/src/cache/namespace.rs
  querier/src/cache/parquet_file.rs
  querier/src/cache/partition.rs
  querier/src/cache/test_util.rs
  querier/src/ingester/mod.rs
  querier/src/ingester/test_util.rs
  querier/src/parquet/creation.rs
  querier/src/parquet/mod.rs
  querier/src/table/mod.rs
  querier/src/table/test_util.rs
Labels: automerge

#8091 feat: tokio metrics bridge
  Cargo.lock
  Cargo.toml
  tokio_metrics_bridge/Cargo.toml
  tokio_metrics_bridge/src/lib.rs
Labels: automerge

#8107 refactor: fuse `QueryChunk` and `QueryChunkMeta`
  compactor/src/components/df_planner/query_chunk.rs
  ingester/src/persist/compact.rs
  ingester/src/persist/handle.rs
  ingester/src/query_adaptor.rs
  iox_query/src/frontend.rs
  iox_query/src/lib.rs
  iox_query/src/physical_optimizer/chunk_extraction.rs
  iox_query/src/physical_optimizer/combine_chunks.rs
  iox_query/src/physical_optimizer/dedup/dedup_null_columns.rs
  iox_query/src/physical_optimizer/dedup/dedup_sort_order.rs
  iox_query/src/physical_optimizer/dedup/partition_split.rs
  iox_query/src/physical_optimizer/dedup/remove_dedup.rs
  iox_query/src/physical_optimizer/dedup/time_split.rs
  iox_query/src/provider.rs
  iox_query/src/provider/physical.rs
  iox_query/src/pruning.rs
  iox_query/src/test.rs
  querier/src/ingester/mod.rs
  querier/src/parquet/mod.rs
  querier/src/parquet/query_access.rs
Labels: automerge

#8050 feat: hook up tokio metrics
  Cargo.lock
  executor/Cargo.toml
  executor/src/lib.rs
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/src/commands/run/compactor.rs
  influxdb_iox/src/commands/run/ingester.rs
  influxdb_iox/src/commands/run/querier.rs
  influxdb_iox/src/process_info.rs
  iox_query/Cargo.toml
  iox_query/src/exec.rs
  iox_tests/src/catalog.rs
Labels: automerge

#8109 refactor: remove `QueryChunk::column_names`
  compactor/src/components/df_planner/query_chunk.rs
  ingester/src/query_adaptor.rs
  iox_query/src/lib.rs
  iox_query/src/test.rs
  iox_query_influxrpc/src/lib.rs
  parquet_file/src/chunk.rs
  querier/src/ingester/mod.rs
  querier/src/parquet/query_access.rs
  service_grpc_influxrpc/src/service.rs
Labels: automerge

#8085 refactor: Use test constants in more places
  ingester/src/buffer_tree/partition/resolver/coalesce.rs
  ingester/src/buffer_tree/root.rs
  ingester/src/dml_sink/instrumentation.rs
  ingester/src/dml_sink/tracing.rs
  ingester/src/persist/compact.rs
  ingester/src/persist/completion_observer.rs
  ingester/src/persist/file_metrics.rs
  ingester/src/query/result_instrumentation.rs
  ingester/src/server/grpc/query.rs
  ingester/src/server/grpc/rpc_write.rs
  ingester/src/test_util.rs
  ingester/src/wal/reference_tracker/handle.rs
  ingester/src/wal/wal_sink.rs
Labels: automerge, kodiak: merge.method = 'merge'

#8112 feat: conditionally expand lookback for active partitions to avoid skipping any
  compactor_scheduler/src/local_scheduler/partitions_source/catalog_to_compact.rs
Labels: automerge

#8108 refactor: bundle projection schema calculation
  Cargo.lock
  querier/Cargo.toml
  querier/src/cache/projected_schema.rs
  querier/src/parquet/creation.rs
  querier/src/parquet/mod.rs
  querier/src/table/mod.rs
  querier/src/table/query_access/metrics.rs
  querier/src/table/query_access/mod.rs
Labels: automerge

#8113 chore: Update datafusion + arrow/arrow-flight/parquet to patched version `42.0.0`
  Cargo.lock
  Cargo.toml
  iox_query/src/exec/context.rs
  iox_query/src/exec/gapfill/mod.rs
  iox_query/src/exec/non_null_checker.rs
  iox_query/src/exec/schema_pivot.rs
  iox_query/src/exec/split.rs
  iox_query/src/provider/deduplicate.rs
  iox_query/src/provider/record_batch_exec.rs
  iox_query/src/test.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'
