Repository influxdata/influxdb_iox, pull requests merged in 2023-01, with the labels that each got.

#6236 feat: InfluxQL planner learns how to normalise InfluxQL AST
  Cargo.lock
  influxdb_influxql_parser/src/common.rs
  influxdb_influxql_parser/src/expression/arithmetic.rs
  iox_query/Cargo.toml
  iox_query/src/frontend/influxql.rs
  iox_query/src/plan/influxql.rs
  iox_query/src/plan/influxql/expr_type_evaluator.rs
  iox_query/src/plan/influxql/field.rs
  iox_query/src/plan/influxql/field_mapper.rs
  iox_query/src/plan/influxql/rewriter.rs
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__rewriter__test__walk_expr-2.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__rewriter__test__walk_expr-3.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__rewriter__test__walk_expr.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__rewriter__test__walk_expr_mut-2.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__rewriter__test__walk_expr_mut-3.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__rewriter__test__walk_expr_mut.snap
  iox_query/src/plan/influxql/test_utils.rs
  iox_query/src/plan/influxql/var_ref.rs
Labels: automerge, influxql

#6467 chore: Upgrade datafusion
  Cargo.lock
  Cargo.toml
  influxdb_iox/tests/end_to_end_cases/querier.rs
  iox_query/src/exec/context.rs
  iox_query/src/provider/physical.rs
  parquet_file/src/storage.rs
  parquet_to_line_protocol/src/lib.rs
  query_tests/cases/in/pushdown.expected
  query_tests/src/sql.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#6481 feat: Teach InfluxQL rewriter how to name columns
  influxdb_influxql_parser/src/expression/arithmetic.rs
  influxdb_influxql_parser/src/keywords.rs
  iox_query/src/plan/influxql/field.rs
  iox_query/src/plan/influxql/rewriter.rs
  iox_query/src/plan/influxql/test_utils.rs
  iox_query/src/plan/influxql/var_ref.rs
  iox_query/src/test.rs
Labels: automerge, influxql

#6460 feat: Extract encoding from `RecordBatch` --> `FlightData` from flight implementations
  Cargo.lock
  arrow_util/src/optimize.rs
  ingester/Cargo.toml
  ingester/src/querier_handler.rs
  ingester/src/server/grpc.rs
  ingester/src/server/grpc/query.rs
  ingester2/Cargo.toml
  ingester2/src/init.rs
  ingester2/src/server/grpc.rs
  ingester2/src/server/grpc/query.rs
  iox_arrow_flight/src/encode.rs
  iox_arrow_flight/src/error.rs
  iox_arrow_flight/src/lib.rs
  service_grpc_flight/Cargo.toml
  service_grpc_flight/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6484 fix: Fix max RecordBatch size limit calculation to avoid gRPC message too large errors
  iox_arrow_flight/src/encode.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6480 test: Lay the groundwork for porting query_tests to the RPC write path
  influxdb_iox/tests/end_to_end_cases/ingester.rs
  influxdb_iox/tests/end_to_end_cases/querier.rs
  test_helpers_end_to_end/src/client.rs
  test_helpers_end_to_end/src/config.rs
  test_helpers_end_to_end/src/mini_cluster.rs
  test_helpers_end_to_end/src/server_fixture.rs
  test_helpers_end_to_end/src/server_type.rs
  test_helpers_end_to_end/src/steps.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6493 refactor: improve influxRPC warning logging
  iox_query/src/frontend/influxrpc.rs
Labels: automerge

#6496 chore: index for selecting partitions with parquet files created after a given time
  iox_catalog/migrations/20230104114545_create_indexes_without_shard.sql
Labels: automerge

#6504 fix(router2): lazily connect to ingesters
  ioxd_router/src/lib.rs
  router/src/dml_handlers/rpc_write.rs
  router/src/dml_handlers/rpc_write/client.rs
Labels: kodiak: merge.method = 'merge', kafkaless

#6502 refactor: improve "Parquet files after filtering" dbg log
  querier/src/table/state_reconciler.rs
Labels: automerge

#6509 fix(router2): drive ingester node (re)-discovery
  Cargo.lock
  router/Cargo.toml
  router/src/dml_handlers/rpc_write.rs
Labels: kind/bug, automerge, kodiak: merge.method = 'merge'

#6514 feat: trigger that updates partition table when a parquet file is created
  iox_catalog/migrations/20230105120822_trigger_update_partition.sql
Labels: automerge

#6507 refactor: decouple influxql from SchemaProvider
  iox_query/src/plan/influxql/expr_type_evaluator.rs
  iox_query/src/plan/influxql/field_mapper.rs
  iox_query/src/plan/influxql/rewriter.rs
  iox_query/src/plan/influxql/test_utils.rs
Labels: automerge

#6511 refactor: cleanup schema boxing
  compactor/src/parquet_file_combining.rs
  compactor/src/query.rs
  compactor/src/utils.rs
  datafusion_util/src/lib.rs
  ingester/src/compact.rs
  ingester/src/query_adaptor.rs
  ingester2/src/persist/compact.rs
  ingester2/src/persist/handle.rs
  ingester2/src/query_adaptor.rs
  iox_arrow_flight/src/client.rs
  iox_query/src/frontend.rs
  iox_query/src/frontend/common.rs
  iox_query/src/frontend/influxrpc.rs
  iox_query/src/frontend/reorg.rs
  iox_query/src/lib.rs
  iox_query/src/plan/influxql/test_utils.rs
  iox_query/src/provider.rs
  iox_query/src/provider/physical.rs
  iox_query/src/pruning.rs
  iox_query/src/test.rs
  iox_tests/src/util.rs
  parquet_file/src/chunk.rs
  parquet_file/src/metadata.rs
  predicate/src/rpc_predicate.rs
  predicate/src/rpc_predicate/column_rewrite.rs
  predicate/src/rpc_predicate/field_rewrite.rs
  querier/src/cache/namespace.rs
  querier/src/cache/partition.rs
  querier/src/cache/projected_schema.rs
  querier/src/ingester/mod.rs
  querier/src/ingester/test_util.rs
  querier/src/namespace/mod.rs
  querier/src/namespace/query_access.rs
  querier/src/parquet/creation.rs
  querier/src/parquet/mod.rs
  querier/src/parquet/query_access.rs
  querier/src/table/mod.rs
  querier/src/table/query_access/mod.rs
  querier/src/table/test_util.rs
  schema/src/interner.rs
  schema/src/merge.rs
  service_grpc_influxrpc/src/expr.rs
Labels: automerge

#6523 docs: Update docstring on Schema
  schema/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6519 feat: function to get parttion candidates from partition table
  data_types/src/lib.rs
  import/src/aggregate_tsm_schema/update_catalog.rs
  ingester/src/buffer_tree/partition/resolver/cache.rs
  ingester2/src/buffer_tree/partition/resolver/cache.rs
  iox_catalog/migrations/20230105120822_trigger_update_partition.sql
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
Labels: automerge

#6525 feat: integrate new way to get partition candidates for hot compaction
  compactor/src/compact.rs
  compactor/src/hot.rs
Labels: automerge

#6526 fix: make trigger modification in different file
  iox_catalog/migrations/20230105120822_trigger_update_partition.sql
  iox_catalog/migrations/20230106145820_modify_trigger.sql
Labels: automerge

#6527 fix: create statistics for nulled columns in RecordBatchExec
  iox_query/src/statistics.rs
Labels: automerge

#6513 feat(data_types): SequenceNumberSet
  Cargo.lock
  data_types/Cargo.toml
  data_types/src/lib.rs
  data_types/src/sequence_number_set.rs
Labels: kodiak: merge.method = 'merge'

#6538 refactor: remove unused QueryExec impl
  ingester2/src/query/exec.rs
  ingester2/src/query/mod.rs
Labels: kodiak: merge.method = 'merge'

#6537 feat(ingester2): track buffered op sequence numbers
  ingester2/src/buffer_tree/partition.rs
  ingester2/src/buffer_tree/partition/buffer/state_machine.rs
  ingester2/src/buffer_tree/partition/buffer/state_machine/buffering.rs
  ingester2/src/buffer_tree/partition/buffer/state_machine/persisting.rs
  ingester2/src/buffer_tree/partition/buffer/state_machine/snapshot.rs
  ingester2/src/persist/context.rs
Labels: kodiak: merge.method = 'merge', kafkaless

#6539 refactor: remove atty & bump tokio
  Cargo.lock
  deny.toml
  trogging/Cargo.toml
  trogging/src/lib.rs
  workspace-hack/Cargo.toml
Labels: kodiak: merge.method = 'merge'

#6529 feat: Ingest replica skeleton
  Cargo.lock
  clap_blocks/src/ingest_replica.rs
  clap_blocks/src/lib.rs
  generated_types/protos/influxdata/iox/ingester/v1/replication.proto
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/run/ingest_replica.rs
  influxdb_iox/src/commands/run/mod.rs
  ingest_replica/Cargo.toml
  ingest_replica/README.md
  ingest_replica/src/buffer.rs
  ingest_replica/src/cache.rs
  ingest_replica/src/grpc.rs
  ingest_replica/src/grpc/query.rs
  ingest_replica/src/grpc/replication.rs
  ingest_replica/src/lib.rs
  ingest_replica/src/query/instrumentation.rs
  ingest_replica/src/query/mock_query_exec.rs
  ingest_replica/src/query/mod.rs
  ingest_replica/src/query/partition_response.rs
  ingest_replica/src/query/response.rs
  ingest_replica/src/query/tracing.rs
  ingest_replica/src/query/trait.rs
  ingest_replica/src/query_adaptor.rs
  ioxd_ingest_replica/Cargo.toml
  ioxd_ingest_replica/src/lib.rs
Labels: automerge, incompatible protobuf

#6512 fix: ensure ingester state tracked in querier cache is always in-sync
  querier/src/cache/parquet_file.rs
Labels: automerge

#6550 refactor: invalidate querier cache if ingester is gone
  querier/src/cache/parquet_file.rs
Labels: automerge

#6542 feat: have cold compaction work with Compactor2
  clap_blocks/src/compactor.rs
  clap_blocks/src/compactor2.rs
  compactor/src/cold.rs
  compactor/src/compact.rs
  compactor/src/handler.rs
  compactor/src/hot.rs
  compactor/src/lib.rs
  compactor/src/parquet_file_lookup.rs
  compactor/src/warm.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  ioxd_compactor/src/lib.rs
Labels: automerge

#6554 fix: use `create_at` to order querier chunks under kafkaless
  querier/src/database.rs
  querier/src/namespace/mod.rs
  querier/src/namespace/test_util.rs
  querier/src/parquet/creation.rs
  querier/src/parquet/mod.rs
  querier/src/table/test_util.rs
  query_tests/src/scenarios/util.rs
Labels: automerge

#6553 refactor: replace PersistState with IngestState
  ingester2/src/ingest_state.rs
  ingester2/src/init.rs
  ingester2/src/lib.rs
  ingester2/src/persist/backpressure.rs
  ingester2/src/persist/handle.rs
  ingester2/src/server/grpc.rs
  ingester2/src/server/grpc/rpc_write.rs
Labels: kodiak: merge.method = 'merge', kafkaless

#6556 fix: using created_at to order chunks for deduplication
  compactor/src/cold.rs
  compactor/src/parquet_file_combining.rs
  compactor/src/query.rs
Labels: automerge

#6520 feat: InfluxQL learns how to plan some InfluxQL queries
  Cargo.lock
  influxdb_iox/tests/end_to_end_cases/influxql.rs
  iox_query/Cargo.toml
  iox_query/src/plan/influxql.rs
  iox_query/src/plan/influxql/test_utils.rs
  iox_query/src/plan/snapshots/iox_query__plan__influxql__test__select_raw__simple_arithmetic_in_projection-2.snap
  iox_query/src/plan/snapshots/iox_query__plan__influxql__test__select_raw__simple_arithmetic_in_projection-3.snap
  iox_query/src/plan/snapshots/iox_query__plan__influxql__test__select_raw__simple_arithmetic_in_projection-4.snap
  iox_query/src/plan/snapshots/iox_query__plan__influxql__test__select_raw__simple_arithmetic_in_projection.snap
  iox_query/src/plan/snapshots/iox_query__plan__influxql__test__select_raw__single_measurement-2.snap
  iox_query/src/plan/snapshots/iox_query__plan__influxql__test__select_raw__single_measurement-3.snap
  iox_query/src/plan/snapshots/iox_query__plan__influxql__test__select_raw__single_measurement-4.snap
  iox_query/src/plan/snapshots/iox_query__plan__influxql__test__select_raw__single_measurement-5.snap
  iox_query/src/plan/snapshots/iox_query__plan__influxql__test__select_raw__single_measurement-6.snap
  iox_query/src/plan/snapshots/iox_query__plan__influxql__test__select_raw__single_measurement-7.snap
  iox_query/src/plan/snapshots/iox_query__plan__influxql__test__select_raw__single_measurement-8.snap
  iox_query/src/plan/snapshots/iox_query__plan__influxql__test__select_raw__single_measurement.snap
  iox_query/src/plan/snapshots/iox_query__plan__influxql__test__unsupported_statements-10.snap
  iox_query/src/plan/snapshots/iox_query__plan__influxql__test__unsupported_statements-2.snap
  iox_query/src/plan/snapshots/iox_query__plan__influxql__test__unsupported_statements-3.snap
  iox_query/src/plan/snapshots/iox_query__plan__influxql__test__unsupported_statements-4.snap
  iox_query/src/plan/snapshots/iox_query__plan__influxql__test__unsupported_statements-5.snap
  iox_query/src/plan/snapshots/iox_query__plan__influxql__test__unsupported_statements-6.snap
  iox_query/src/plan/snapshots/iox_query__plan__influxql__test__unsupported_statements-7.snap
  iox_query/src/plan/snapshots/iox_query__plan__influxql__test__unsupported_statements-8.snap
  iox_query/src/plan/snapshots/iox_query__plan__influxql__test__unsupported_statements-9.snap
  iox_query/src/plan/snapshots/iox_query__plan__influxql__test__unsupported_statements.snap
  iox_query/src/test.rs
  query_tests/Cargo.toml
  test_helpers_end_to_end/src/steps.rs
Labels: automerge, influxql

#6562 chore: bump rust to 1.66.1
  rust-toolchain.toml
Labels: automerge, kodiak: merge.method = 'merge'

#6564 chore: exclude arrow and datafusion from dependabot
  .github/dependabot.yml
Labels: automerge

#6565 ci: use rust 1.66.0 for CI
  .circleci/config.yml
Labels: kodiak: merge.method = 'merge'

#6567 fix: node discovery shutdown panic
  ingester2/src/persist/backpressure.rs
  router/src/dml_handlers/rpc_write.rs
Labels: kodiak: merge.method = 'merge'

#6541 test: Record number of Parquet files before a write
  generated_types/protos/influxdata/iox/catalog/v1/service.proto
  influxdb_iox/tests/end_to_end_cases/querier.rs
  influxdb_iox_client/src/client/catalog.rs
  service_grpc_catalog/src/lib.rs
  test_helpers_end_to_end/src/client.rs
  test_helpers_end_to_end/src/steps.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6572 fix: bug in count processed partitions
  compactor/src/lib.rs
Labels: automerge

#6569 refactor: same function to select partition candidates for hot & cold
  compactor/src/cold.rs
  compactor/src/compact.rs
  compactor/src/hot.rs
  compactor/src/lib.rs
  compactor/src/utils.rs
  compactor/src/warm.rs
Labels: automerge

#6571 fix: have warm compaction work with compactor2
  clap_blocks/src/compactor.rs
  clap_blocks/src/compactor2.rs
  compactor/src/cold.rs
  compactor/src/compact.rs
  compactor/src/handler.rs
  compactor/src/hot.rs
  compactor/src/lib.rs
  compactor/src/parquet_file_lookup.rs
  compactor/src/warm.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ioxd_compactor/src/lib.rs
Labels: automerge

#6576 revert: "ci: use rust 1.66.0 for CI"
  .circleci/config.yml
Labels: kodiak: merge.method = 'merge'

#6579 refactor: improve thread naming
  executor/src/lib.rs
  influxdb_iox/src/main.rs
  iox_query/src/exec.rs
Labels: automerge

#6580 refactor: delegate frontend shutdown to backend
  Cargo.lock
  ingester2/Cargo.toml
  ingester2/src/init.rs
  ingester2/src/init/graceful_shutdown.rs
  ioxd_common/src/lib.rs
  ioxd_common/src/server_type.rs
  ioxd_compactor/Cargo.toml
  ioxd_compactor/src/lib.rs
  ioxd_garbage_collector/Cargo.toml
  ioxd_garbage_collector/src/lib.rs
  ioxd_ingest_replica/Cargo.toml
  ioxd_ingest_replica/src/lib.rs
  ioxd_ingester/Cargo.toml
  ioxd_ingester/src/lib.rs
  ioxd_ingester2/Cargo.toml
  ioxd_ingester2/src/lib.rs
  ioxd_querier/Cargo.toml
  ioxd_querier/src/lib.rs
  ioxd_router/src/lib.rs
  ioxd_test/Cargo.toml
  ioxd_test/src/lib.rs
Labels: kodiak: merge.method = 'merge', kafkaless

#6570 test: API to tell an ingester to persist on demand
  Cargo.lock
  generated_types/protos/influxdata/iox/ingester/v1/write.proto
  influxdb_iox/tests/end_to_end_cases/ingester.rs
  influxdb_iox_client/src/client.rs
  influxdb_iox_client/src/client/ingester.rs
  ingester2/src/init.rs
  ingester2/src/server/grpc.rs
  ingester2/src/server/grpc/persist.rs
  ioxd_ingester2/src/lib.rs
  test_helpers_end_to_end/Cargo.toml
  test_helpers_end_to_end/src/mini_cluster.rs
  test_helpers_end_to_end/src/steps.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6575 chore: Move InfluxQL AST walk_ APIs to parser crate
  influxdb_influxql_parser/src/expression.rs
  influxdb_influxql_parser/src/expression/conditional.rs
  influxdb_influxql_parser/src/expression/snapshots/influxdb_influxql_parser__expression__walk__test__walk_expr-2.snap
  influxdb_influxql_parser/src/expression/snapshots/influxdb_influxql_parser__expression__walk__test__walk_expr.snap
  influxdb_influxql_parser/src/expression/snapshots/influxdb_influxql_parser__expression__walk__test__walk_expr_mut-2.snap
  influxdb_influxql_parser/src/expression/snapshots/influxdb_influxql_parser__expression__walk__test__walk_expr_mut.snap
  influxdb_influxql_parser/src/expression/snapshots/influxdb_influxql_parser__expression__walk__test__walk_expression-2.snap
  influxdb_influxql_parser/src/expression/snapshots/influxdb_influxql_parser__expression__walk__test__walk_expression.snap
  influxdb_influxql_parser/src/expression/walk.rs
  iox_query/src/plan/influxql/rewriter.rs
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__rewriter__test__walk_expr-2.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__rewriter__test__walk_expr-3.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__rewriter__test__walk_expr.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__rewriter__test__walk_expr_mut-2.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__rewriter__test__walk_expr_mut-3.snap
  iox_query/src/plan/influxql/snapshots/iox_query__plan__influxql__rewriter__test__walk_expr_mut.snap
Labels: automerge, influxql

#6582 refactor: improve executor panic/error handling
  executor/src/lib.rs
  iox_query/src/exec/context.rs
Labels: automerge

#6583 fix: Wait the interval and *then* persist
  influxdb_iox/tests/end_to_end_cases/querier.rs
  ingester2/src/wal/rotate_task.rs
  test_helpers_end_to_end/src/lib.rs
Labels: kodiak: merge.method = 'merge'

#6589 perf: remove double-ref Partition map
  ingester2/src/buffer_tree/namespace.rs
  ingester2/src/buffer_tree/table.rs
Labels: kodiak: merge.method = 'merge'

#6590 perf: optimize not to update partitions with newly created level 2 files
  compactor/src/compact.rs
  iox_catalog/migrations/20230113075522_modify_trigger_new_file_at.sql
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
Labels: automerge

#6591 refactor: use system-wide ingester ID
  ingester2/src/ingester_id.rs
  ingester2/src/init.rs
  ingester2/src/lib.rs
  ingester2/src/server/grpc.rs
  ingester2/src/server/grpc/query.rs
Labels: automerge, kodiak: merge.method = 'merge', kafkaless

#6585 feat: Parse IANA timezones in an InfluxQL TZ clause
  Cargo.lock
  influxdb_influxql_parser/Cargo.toml
  influxdb_influxql_parser/src/select.rs
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit__test__select_statement-6.snap
  influxdb_influxql_parser/src/snapshots/influxdb_influxql_parser__visit_mut__test__select_statement-6.snap
  influxdb_influxql_parser/src/visit.rs
  influxdb_influxql_parser/src/visit_mut.rs
  iox_query/src/plan/influxql/field.rs
  iox_query/src/plan/influxql/rewriter.rs
  workspace-hack/Cargo.toml
Labels: automerge, influxql

#6599 refactor(persist): decouple persist job Context & logic
  ingester2/src/persist/context.rs
  ingester2/src/persist/mod.rs
  ingester2/src/persist/worker.rs
Labels: kodiak: merge.method = 'merge', kafkaless

#6586 feat: safely stream data from one tokio runtime to another
  iox_query/src/exec.rs
  iox_query/src/exec/context.rs
  iox_query/src/exec/cross_rt_stream.rs
Labels: automerge

#6595 feat: create (stubbed) DATE_BIN_GAPFILL UDF
  query_functions/src/gapfill.rs
  query_functions/src/lib.rs
  query_functions/src/registry.rs
Labels: automerge

#6601 refactor(persist): pluggable completion observer
  ingester2/src/init.rs
  ingester2/src/persist/completion_observer.rs
  ingester2/src/persist/context.rs
  ingester2/src/persist/handle.rs
  ingester2/src/persist/mod.rs
  ingester2/src/persist/worker.rs
Labels: kodiak: merge.method = 'merge', kafkaless

#6603 chore: Update datafusion to Jan 9, 2023 (1 / 2)
  Cargo.lock
  Cargo.toml
  datafusion_util/src/config.rs
  iox_query/src/exec/context.rs
  iox_query/src/frontend/influxql.rs
  iox_query/src/logical_optimizer/mod.rs
  iox_query/src/plan/influxql.rs
  iox_query/src/provider/deduplicate.rs
  iox_query/src/provider/physical.rs
  iox_query/src/test.rs
  parquet_file/src/storage.rs
  parquet_to_line_protocol/src/lib.rs
  predicate/src/delete_expr.rs
  predicate/src/rpc_predicate/rewrite.rs
  querier/src/namespace/query_access.rs
  querier/src/system_tables/mod.rs
  query_functions/src/gapfill.rs
  query_functions/src/lib.rs
  query_functions/src/regex.rs
  query_functions/src/selectors.rs
  query_tests/cases/in/dedup_and_predicates_parquet.expected
  query_tests/cases/in/dedup_and_predicates_parquet_ingester.expected
  query_tests/cases/in/duplicates_ingester.expected
  query_tests/cases/in/duplicates_parquet.expected
  query_tests/cases/in/pushdown.expected
  query_tests/cases/in/retention.expected
  query_tests/cases/in/several_chunks.expected
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#6604 chore: Update datafusion to Jan 17, 2023 (2 / 2) and arrow/parquet `30.0.1`
  Cargo.lock
  Cargo.toml
  ingest_replica/src/grpc/query.rs
  ingester/src/server/grpc/query.rs
  ingester2/src/server/grpc/query.rs
  iox_arrow_flight/src/client.rs
  iox_arrow_flight/src/encode.rs
  iox_arrow_flight/src/flightsql.rs
  iox_query/src/exec/seriesset/series.rs
  service_grpc_flight/src/lib.rs
  service_grpc_flight/src/request.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#6612 chore: Update dependencies
  Cargo.lock
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#6614 feat: very basic compactor2 skeleton
  Cargo.lock
  Cargo.toml
  clap_blocks/src/compactor2.rs
  compactor2/Cargo.toml
  compactor2/src/compactor.rs
  compactor2/src/config.rs
  compactor2/src/lib.rs
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/run/compactor2.rs
  ioxd_compactor/src/lib.rs
  ioxd_compactor2/Cargo.toml
  ioxd_compactor2/src/lib.rs
Labels: automerge

#6602 feat: create a logical plan node and rule for gap-filling
  iox_query/src/exec.rs
  iox_query/src/exec/gapfill.rs
  iox_query/src/logical_optimizer/handle_gapfill.rs
  iox_query/src/logical_optimizer/mod.rs
  query_functions/src/lib.rs
Labels: automerge

#6616 feat: basic compactor2 algo layout
  Cargo.lock
  clap_blocks/src/compactor2.rs
  compactor2/Cargo.toml
  compactor2/src/compact.rs
  compactor2/src/compactor.rs
  compactor2/src/config.rs
  compactor2/src/driver.rs
  compactor2/src/lib.rs
  compactor2/src/rules/file_filter/mod.rs
  compactor2/src/rules/mod.rs
  compactor2/src/rules/partition_filter/mod.rs
  ioxd_compactor2/src/lib.rs
Labels: automerge

#6497 feat: Reimagining query_tests sql cases
  Cargo.lock
  Cargo.toml
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/metadata.rs
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/read_filter.rs
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/read_group.rs
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/read_window_aggregate.rs
  influxdb_iox/tests/end_to_end_cases/querier/multi_ingester.rs
  query_tests2/Cargo.toml
  query_tests2/src/cases.rs
  query_tests2/src/framework.rs
  query_tests2/src/lib.rs
  query_tests2/src/setups.rs
  test_helpers_end_to_end/Cargo.toml
  test_helpers_end_to_end/src/config.rs
  test_helpers_end_to_end/src/grpc.rs
  test_helpers_end_to_end/src/lib.rs
  test_helpers_end_to_end/src/snapshot_comparison.rs
  test_helpers_end_to_end/src/steps.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6618 chore: Update to latest datafusion / arrow `31.0.0`
  Cargo.lock
  Cargo.toml
  service_common/src/error.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#6628 chore: clarify cli args for iox gc
  garbage_collector/src/lib.rs
Labels: automerge

#6625 chore: uncomment now working tests in query_tests2
  query_tests2/src/cases.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6619 feat: invokes catalog functions for compactor2
  Cargo.lock
  clap_blocks/src/compactor2.rs
  compactor2/Cargo.toml
  compactor2/src/config.rs
  compactor2/src/driver.rs
  ioxd_compactor2/Cargo.toml
  ioxd_compactor2/src/lib.rs
Labels: automerge

#6629 test: add log level in test tracing capture
  test_helpers/src/tracing.rs
Labels: automerge

#6631 refactor: lift up compactor2 CLI args, set mem limit to 8GB
  clap_blocks/src/compactor2.rs
  influxdb_iox/src/commands/run/compactor2.rs
Labels: automerge

#6630 refactor: more components for compactor2
  Cargo.lock
  compactor2/Cargo.toml
  compactor2/src/compactor.rs
  compactor2/src/components/file_filter/mod.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/mod.rs
  compactor2/src/components/partition_filter/mod.rs
  compactor2/src/components/partitions_source/catalog.rs
  compactor2/src/components/partitions_source/logging.rs
  compactor2/src/components/partitions_source/mock.rs
  compactor2/src/components/partitions_source/mod.rs
  compactor2/src/components/partitions_source/randomize_order.rs
  compactor2/src/driver.rs
  compactor2/src/lib.rs
  compactor2/src/rules/file_filter/mod.rs
  compactor2/src/rules/mod.rs
  compactor2/src/rules/partition_filter/mod.rs
Labels: automerge

#6632 refactor: extract "fetch files" component
  Cargo.lock
  compactor2/Cargo.toml
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/mod.rs
  compactor2/src/components/partition_files_source/catalog.rs
  compactor2/src/components/partition_files_source/mock.rs
  compactor2/src/components/partition_files_source/mod.rs
  compactor2/src/driver.rs
  compactor2/src/lib.rs
  compactor2/src/test_util.rs
Labels: automerge

#6615 docs: Document semantics of selector functions
  query_functions/src/lib.rs
  query_functions/src/selectors.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6623 refactor: remove iox_arrow_flight use in ingester2
  Cargo.lock
  ingester2/Cargo.toml
  ingester2/src/init.rs
  ingester2/src/server/grpc.rs
  ingester2/src/server/grpc/query.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6633 feat: partition error sink
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/mod.rs
  compactor2/src/components/partition_error_sink/catalog.rs
  compactor2/src/components/partition_error_sink/logging.rs
  compactor2/src/components/partition_error_sink/metrics.rs
  compactor2/src/components/partition_error_sink/mock.rs
  compactor2/src/components/partition_error_sink/mod.rs
  compactor2/src/driver.rs
Labels: automerge

#6637 refactor: converters for `ParquetFile`<>`ParquetFileParams`
  data_types/src/lib.rs
  iox_catalog/src/mem.rs
Labels: automerge

#6638 feat: catalog commits for compactor2
  compactor2/src/compact.rs
  compactor2/src/components/commit/catalog.rs
  compactor2/src/components/commit/logging.rs
  compactor2/src/components/commit/metrics.rs
  compactor2/src/components/commit/mock.rs
  compactor2/src/components/commit/mod.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/mod.rs
  compactor2/src/driver.rs
Labels: automerge

#6624 refactor: remove iox_arrow_flight use in `influxdb_iox_client ` and `querier`
  Cargo.lock
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/query_ingester.rs
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
  influxdb_iox/tests/end_to_end_cases/ingester.rs
  influxdb_iox_client/Cargo.toml
  influxdb_iox_client/src/client.rs
  influxdb_iox_client/src/client/flight/mod.rs
  influxdb_iox_client/src/client/flightsql.rs
  iox_arrow_flight/src/error.rs
  querier/Cargo.toml
  querier/src/ingester/circuit_breaker.rs
  querier/src/ingester/flight_client.rs
  querier/src/ingester/mod.rs
  query_tests/Cargo.toml
  query_tests/src/scenarios/util.rs
  test_helpers_end_to_end/Cargo.toml
  test_helpers_end_to_end/src/mini_cluster.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6621 chore: Remove `iox_arrow_flight`
  Cargo.lock
  Cargo.toml
  influxdb_iox_client/Cargo.toml
  iox_arrow_flight/Cargo.toml
  iox_arrow_flight/src/client.rs
  iox_arrow_flight/src/encode.rs
  iox_arrow_flight/src/error.rs
  iox_arrow_flight/src/flightsql.rs
  iox_arrow_flight/src/lib.rs
  service_grpc_flight/Cargo.toml
  service_grpc_flight/src/lib.rs
  service_grpc_flight/src/request.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6636 refactor: reorganize compact_files core function
  Cargo.lock
  compactor2/Cargo.toml
  compactor2/src/compact.rs
  compactor2/src/components/compact/compact_builder.rs
  compactor2/src/components/compact/compact_files.rs
  compactor2/src/components/compact/mod.rs
  compactor2/src/components/compact/partition.rs
  compactor2/src/components/compact/query_chunk.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/mod.rs
  compactor2/src/components/namespaces_source/catalog.rs
  compactor2/src/components/namespaces_source/mock.rs
  compactor2/src/components/namespaces_source/mod.rs
  compactor2/src/components/partitions_source/catalog.rs
  compactor2/src/components/partitions_source/logging.rs
  compactor2/src/components/partitions_source/mock.rs
  compactor2/src/components/partitions_source/mod.rs
  compactor2/src/components/partitions_source/randomize_order.rs
  compactor2/src/components/tables_source/catalog.rs
  compactor2/src/components/tables_source/mock.rs
  compactor2/src/components/tables_source/mod.rs
  compactor2/src/driver.rs
  compactor2/src/lib.rs
  compactor2/src/test_util.rs
Labels: automerge

#6652 feat: improve compactor2 metrics and logging
  compactor2/src/compactor.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/mod.rs
  compactor2/src/components/partition_filter/has_files.rs
  compactor2/src/components/partition_filter/metrics.rs
  compactor2/src/components/partition_filter/mod.rs
  compactor2/src/components/partitions_source/metrics.rs
  compactor2/src/components/partitions_source/mod.rs
  compactor2/src/components/report.rs
Labels: automerge

#6653 feat: filter out L2 files from compaction
  compactor2/src/components/file_filter/and.rs
  compactor2/src/components/file_filter/level_range.rs
  compactor2/src/components/file_filter/mod.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/driver.rs
  compactor2/src/test_util.rs
Labels: automerge

#6641 feat: create a GapFillExec type
  iox_query/src/exec/context.rs
  iox_query/src/exec/gapfill.rs
  iox_query/src/logical_optimizer/handle_gapfill.rs
  iox_query/src/logical_optimizer/mod.rs
Labels: automerge

#6654 refactor: execute compaction plan
  Cargo.lock
  clap_blocks/src/compactor2.rs
  compactor2/Cargo.toml
  compactor2/src/components/compact/compact_builder.rs
  compactor2/src/components/compact/compact_executor.rs
  compactor2/src/components/compact/compact_files.rs
  compactor2/src/components/compact/mod.rs
  compactor2/src/components/compact/partition.rs
  compactor2/src/components/compact/query_chunk.rs
  compactor2/src/components/namespaces_source/catalog.rs
  compactor2/src/components/namespaces_source/mock.rs
  compactor2/src/components/namespaces_source/mod.rs
  compactor2/src/config.rs
  compactor2/src/driver.rs
  compactor2/src/test_util.rs
  iox_tests/src/util.rs
  ioxd_compactor2/src/lib.rs
Labels: automerge

#6658 fix: Get shard id from a constant (topic, shard_index) to avoid error of shard_id FK violation
  compactor2/src/components/compact/compact_executor.rs
  compactor2/src/components/compact/compact_files.rs
  compactor2/src/config.rs
  compactor2/src/driver.rs
  compactor2/src/test_util.rs
  influxdb_iox/src/commands/run/compactor2.rs
  ioxd_compactor2/src/lib.rs
Labels: automerge

#6656 chore: Update datafusion again
  Cargo.lock
  Cargo.toml
  query_tests/cases/in/dedup_and_predicates_parquet.expected
  query_tests/cases/in/dedup_and_predicates_parquet_ingester.expected
  query_tests/cases/in/duplicates_ingester.expected
  query_tests/cases/in/duplicates_parquet.expected
  query_tests/cases/in/duplicates_parquet_many.expected
  query_tests/cases/in/pushdown.expected
  query_tests/cases/in/retention.expected
  query_tests/cases/in/several_chunks.expected
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#6663 refactor: extract "exec DF plan" and "store stream to file" components
  compactor2/src/components/compact/compact_builder.rs
  compactor2/src/components/compact/compact_executor.rs
  compactor2/src/components/compact/compact_files.rs
  compactor2/src/components/compact/mod.rs
  compactor2/src/components/compact/partition.rs
  compactor2/src/components/df_plan_exec/dedicated.rs
  compactor2/src/components/df_plan_exec/mod.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/mod.rs
  compactor2/src/components/parquet_file_sink/dedicated.rs
  compactor2/src/components/parquet_file_sink/logging.rs
  compactor2/src/components/parquet_file_sink/mod.rs
  compactor2/src/components/parquet_file_sink/object_store.rs
  compactor2/src/components/report.rs
  compactor2/src/driver.rs
  compactor2/src/lib.rs
  compactor2/src/partition_info.rs
  compactor2/src/test_util.rs
  iox_query/src/exec.rs
  parquet_file/src/serialize.rs
  parquet_file/src/storage.rs
Labels: automerge

#6666 refactor: ignore partitions in table skipped compactions
  compactor2/src/compactor_tests.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/mod.rs
  compactor2/src/components/report.rs
  compactor2/src/components/skipped_compactions_source/catalog.rs
  compactor2/src/components/skipped_compactions_source/mock.rs
  compactor2/src/components/skipped_compactions_source/mod.rs
  compactor2/src/driver.rs
  compactor2/src/lib.rs
  compactor2/src/test_util.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_tests/src/util.rs
Labels: automerge

#6668 fix: `error arrow/ipc: could not read message schema: EOF`
  influxdb_iox/tests/end_to_end_cases/querier.rs
  service_grpc_flight/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6672 feat: enable object store metrics on ingester2
  influxdb_iox/src/commands/run/ingester2.rs
Labels: automerge

#6662 feat: low-overhead circuit breaker
  Cargo.lock
  router/Cargo.toml
  router/src/dml_handlers/rpc_write.rs
  router/src/dml_handlers/rpc_write/circuit_breaker.rs
Labels: automerge, kodiak: merge.method = 'merge', kafkaless

#6673 refactor: integrate "skipped" handling into the partition filter framework
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/mod.rs
  compactor2/src/components/partition_filter/and.rs
  compactor2/src/components/partition_filter/has_files.rs
  compactor2/src/components/partition_filter/logging.rs
  compactor2/src/components/partition_filter/metrics.rs
  compactor2/src/components/partition_filter/mod.rs
  compactor2/src/components/partition_filter/never_skipped.rs
  compactor2/src/components/report.rs
  compactor2/src/driver.rs
Labels: automerge

#6675 perf(router): circuit break ingester connections
  ioxd_router/src/lib.rs
  router/src/dml_handlers/rpc_write.rs
  router/src/dml_handlers/rpc_write/balancer.rs
  router/src/dml_handlers/rpc_write/circuit_breaker.rs
  router/src/dml_handlers/rpc_write/circuit_breaking_client.rs
  router/src/server/http.rs
Labels: kodiak: merge.method = 'merge', kafkaless

#6676 feat: compactor2 error classification
  Cargo.lock
  compactor2/Cargo.toml
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/partition_error_sink/catalog.rs
  compactor2/src/components/partition_error_sink/kind.rs
  compactor2/src/components/partition_error_sink/logging.rs
  compactor2/src/components/partition_error_sink/metrics.rs
  compactor2/src/components/partition_error_sink/mock.rs
  compactor2/src/components/partition_error_sink/mod.rs
  compactor2/src/driver.rs
  compactor2/src/error.rs
  compactor2/src/lib.rs
Labels: automerge

#6677 revert: influxdata/dom/rpc-balancer
  ioxd_router/src/lib.rs
  router/src/dml_handlers/rpc_write.rs
  router/src/dml_handlers/rpc_write/balancer.rs
  router/src/dml_handlers/rpc_write/circuit_breaker.rs
  router/src/dml_handlers/rpc_write/circuit_breaking_client.rs
  router/src/server/http.rs
Labels: automerge, kodiak: merge.method = 'merge', kafkaless

#6679 feat(ingester2): metrics
  ingester2/src/dml_sink/instrumentation.rs
  ingester2/src/dml_sink/mod.rs
  ingester2/src/dml_sink/tracing.rs
  ingester2/src/init.rs
  ingester2/src/persist/context.rs
  ingester2/src/persist/handle.rs
  ingester2/src/persist/mod.rs
  ingester2/src/persist/worker.rs
  ingester2/src/query/instrumentation.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6686 feat: add per-partition timeout
  clap_blocks/src/compactor2.rs
  compactor2/src/compactor.rs
  compactor2/src/compactor_tests.rs
  compactor2/src/config.rs
  compactor2/src/driver.rs
  compactor2/src/error.rs
  compactor2/src/test_util.rs
  ioxd_compactor2/src/lib.rs
Labels: automerge

#6640 refactor: Move `flightsql` code into its own module, add docs and tests
  Cargo.lock
  Cargo.toml
  flightsql/Cargo.toml
  flightsql/src/lib.rs
  flightsql/src/planner.rs
  generated_types/protos/influxdata/iox/querier/v1/flight.proto
  influxdb_iox_client/src/client/flight/mod.rs
  iox_query/src/exec/context.rs
  service_common/Cargo.toml
  service_common/src/planner.rs
  service_grpc_flight/Cargo.toml
  service_grpc_flight/src/lib.rs
  service_grpc_flight/src/request.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6687 refactor(router): set sensible RPC timeouts
  router/src/dml_handlers/rpc_write/lazy_connector.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6689 fix(router): force rediscovery of nodes
  router/src/dml_handlers/rpc_write/lazy_connector.rs
Labels: kodiak: merge.method = 'merge'

#6690 refactor: propagate gapfill stride to exec
  iox_query/src/exec/gapfill.rs
  iox_query/src/logical_optimizer/handle_gapfill.rs
Labels: automerge

#6688 feat(metrics): router upstream RPC endpoint metrics
  ioxd_router/src/lib.rs
  router/src/dml_handlers/rpc_write.rs
  router/src/dml_handlers/rpc_write/balancer.rs
  router/src/dml_handlers/rpc_write/circuit_breaker.rs
  router/src/dml_handlers/rpc_write/circuit_breaking_client.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6696 feat: job semaphore
  Cargo.lock
  clap_blocks/src/compactor2.rs
  compactor2/Cargo.toml
  compactor2/src/compactor.rs
  compactor2/src/compactor_tests.rs
  compactor2/src/config.rs
  compactor2/src/driver.rs
  compactor2/src/test_util.rs
  ioxd_compactor2/src/lib.rs
Labels: automerge

#6682 docs: document how the garbage collector works
  docs/garbage_collector.md
Labels: automerge, kodiak: merge.method = 'squash'

#6678 chore: Move garbage collector configuration into clap_blocks
  clap_blocks/src/garbage_collector.rs
  clap_blocks/src/lib.rs
  garbage_collector/Cargo.toml
  garbage_collector/src/lib.rs
  influxdb_iox/src/commands/run/garbage_collector.rs
  ioxd_garbage_collector/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6667 feat: Implement basic prepared statement support in IOx
  flightsql/src/planner.rs
  influxdb_iox/tests/end_to_end_cases/cli.rs
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
  influxdb_iox_client/src/client/flightsql.rs
  service_common/src/planner.rs
  service_grpc_flight/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6700 perf(router): faster balancer node recovery
  router/src/dml_handlers/rpc_write/balancer.rs
  router/src/dml_handlers/rpc_write/circuit_breaking_client.rs
Labels: kodiak: merge.method = 'merge', kafkaless

#6698 test: CircuitBreaker recovery property fuzz test
  router/src/dml_handlers/rpc_write/circuit_breaker.rs
Labels: kodiak: merge.method = 'merge'

#6697 feat: divide&conquer framework
  compactor2/src/components/divide_initial/mod.rs
  compactor2/src/components/divide_initial/single_branch.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/mod.rs
  compactor2/src/components/partition_filter/has_matching_file.rs
  compactor2/src/components/partition_filter/mod.rs
  compactor2/src/components/report.rs
  compactor2/src/components/round_split/all_now.rs
  compactor2/src/components/round_split/mod.rs
  compactor2/src/driver.rs
Labels: automerge

#6701 feat: export persist config metrics
  ingester2/src/persist/handle.rs
  ingester2/src/persist/mod.rs
Labels: kodiak: merge.method = 'merge', kafkaless

#6702 refactor: appropriate queue wait histogram buckets
  ingester2/src/persist/handle.rs
Labels: kodiak: merge.method = 'merge', kafkaless

#6655 test: Start of porting InfluxRpc query_tests
  .circleci/config.yml
  Cargo.lock
  generated_types/protos/influxdata/iox/ingester/v1/write.proto
  influxdb_iox/Cargo.toml
  influxdb_iox/tests/end_to_end.rs
  influxdb_iox/tests/end_to_end_cases/querier.rs
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc.rs
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/metadata.rs
  influxdb_iox/tests/query.rs
  influxdb_iox/tests/query_tests2/framework.rs
  influxdb_iox/tests/query_tests2/mod.rs
  influxdb_iox_client/src/client/ingester.rs
  ingester/src/server/grpc/persist.rs
  ingester2/src/server/grpc.rs
  ingester2/src/server/grpc/persist.rs
  test_helpers_end_to_end/src/mini_cluster.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6707 test: Port all field columns query_tests to end-to-end tests
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/metadata.rs
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/metadata/measurement_fields.rs
  influxdb_iox/tests/query_tests2/setups.rs
  query_tests/src/influxrpc.rs
  query_tests/src/influxrpc/field_columns.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6703 refactor: split flightsql crate into smaller modules
  flightsql/src/cmd.rs
  flightsql/src/error.rs
  flightsql/src/lib.rs
  flightsql/src/planner.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6693 feat: JDBC integration tests with FlightSQL
  .circleci/config.yml
  docs/flightsql.md
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
  influxdb_iox/tests/jdbc_client/.gitignore
  influxdb_iox/tests/jdbc_client/Main.java
  influxdb_iox/tests/jdbc_client/Makefile
  influxdb_iox/tests/jdbc_client/README.md
  influxdb_iox/tests/jdbc_client/flight-sql-jdbc-driver-10.0.0.jar.sha
  influxdb_iox/tests/jdbc_client/jdbc_client
  service_grpc_flight/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6706 feat: introduce scratchpad store for compactor
  clap_blocks/src/compactor2.rs
  compactor2/src/compactor_tests.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/mod.rs
  compactor2/src/components/report.rs
  compactor2/src/components/scratchpad/mod.rs
  compactor2/src/components/scratchpad/prod.rs
  compactor2/src/components/scratchpad/test_util.rs
  compactor2/src/components/scratchpad/util.rs
  compactor2/src/config.rs
  compactor2/src/driver.rs
  compactor2/src/test_util.rs
  influxdb_iox/src/commands/run/compactor2.rs
  ioxd_compactor2/src/lib.rs
  parquet_file/src/lib.rs
Labels: automerge

#6692 feat: introduce a new way of max_sequence_number for ingester, compactor and querier
  compactor/src/compact.rs
  compactor/src/garbage_collector.rs
  compactor/src/parquet_file_combining.rs
  compactor/src/parquet_file_filtering.rs
  compactor2/src/compactor_tests.rs
  compactor2/src/components/df_planner/query_chunk.rs
  compactor2/src/components/parquet_file_sink/dedicated.rs
  compactor2/src/components/parquet_file_sink/logging.rs
  compactor2/src/components/parquet_file_sink/mock.rs
  compactor2/src/components/parquet_file_sink/mod.rs
  compactor2/src/components/parquet_file_sink/object_store.rs
  compactor2/src/driver.rs
  compactor2/src/test_util.rs
  data_types/src/lib.rs
  garbage_collector/src/objectstore/checker.rs
  generated_types/protos/influxdata/iox/catalog/v1/parquet_file.proto
  generated_types/protos/influxdata/iox/ingester/v1/parquet_metadata.proto
  influxdb_iox/src/commands/remote/partition.rs
  influxdb_iox/tests/end_to_end_cases/cli.rs
  ingester/src/buffer_tree/namespace.rs
  ingester/src/data.rs
  ingester2/src/persist/mod.rs
  ingester2/src/persist/worker.rs
  iox_catalog/migrations/20230125103737_create_max_l0_crrated_at.sql
  iox_catalog/src/interface.rs
  iox_catalog/src/postgres.rs
  iox_tests/src/util.rs
  iox_time/src/lib.rs
  parquet_file/src/metadata.rs
  parquet_file/src/serialize.rs
  parquet_file/src/storage.rs
  parquet_file/tests/metadata.rs
  querier/src/cache/parquet_file.rs
  querier/src/namespace/mod.rs
  querier/src/parquet/creation.rs
  service_grpc_catalog/src/lib.rs
  service_grpc_object_store/src/lib.rs
  test_fixtures/cpu.parquet
Labels: automerge

#6712 feat: shadow mode
  Cargo.lock
  clap_blocks/src/compactor2.rs
  compactor2/Cargo.toml
  compactor2/src/compactor.rs
  compactor2/src/compactor_tests.rs
  compactor2/src/components/commit/mod.rs
  compactor2/src/components/df_plan_exec/dedicated.rs
  compactor2/src/components/df_planner/mod.rs
  compactor2/src/components/df_planner/panic.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/mod.rs
  compactor2/src/components/parquet_file_sink/dedicated.rs
  compactor2/src/components/parquet_file_sink/mock.rs
  compactor2/src/components/parquet_file_sink/mod.rs
  compactor2/src/components/parquet_file_sink/test_util.rs
  compactor2/src/components/partition_done_sink/mock.rs
  compactor2/src/components/partition_done_sink/mod.rs
  compactor2/src/components/partition_filter/by_id.rs
  compactor2/src/components/partition_filter/mod.rs
  compactor2/src/components/partitions_source/catalog.rs
  compactor2/src/components/scratchpad/ignore_writes_object_store.rs
  compactor2/src/components/scratchpad/mod.rs
  compactor2/src/components/scratchpad/prod.rs
  compactor2/src/components/scratchpad/test_util.rs
  compactor2/src/config.rs
  compactor2/src/lib.rs
  compactor2/src/test_util.rs
  ioxd_compactor2/Cargo.toml
  ioxd_compactor2/src/lib.rs
Labels: automerge

#6715 fix(router): restore NamespaceService
  ioxd_router/src/lib.rs
  router/src/server/grpc.rs
Labels: kodiak: merge.method = 'merge', kafkaless

#6716 fix: "timeout" as a reason to skip a partition
  compactor2/src/components/hardcoded.rs
Labels: automerge

#6718 feat: improve compactor2 debugging
  compactor2/src/components/df_planner/logging.rs
  compactor2/src/components/df_planner/mod.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/mod.rs
  compactor2/src/components/partition_source/catalog.rs
  compactor2/src/components/partition_source/logging.rs
  compactor2/src/components/partition_source/metrics.rs
  compactor2/src/components/partition_source/mock.rs
  compactor2/src/components/partition_source/mod.rs
  compactor2/src/components/partitions_source/catalog.rs
  compactor2/src/components/partitions_source/logging.rs
  compactor2/src/components/partitions_source/metrics.rs
  compactor2/src/components/partitions_source/mock.rs
  compactor2/src/components/partitions_source/mod.rs
  compactor2/src/components/partitions_source/randomize_order.rs
  compactor2/src/components/report.rs
  compactor2/src/driver.rs
Labels: automerge

#6720 fix(router): reject new namespaces / deny namespace auto-creation
  ioxd_router/src/lib.rs
  router/src/namespace_resolver/mock.rs
  router/src/namespace_resolver/ns_autocreation.rs
  router/src/server/grpc.rs
  router/src/server/http.rs
  router/tests/common/mod.rs
  router/tests/grpc.rs
  router/tests/http.rs
Labels: kodiak: merge.method = 'merge'

#6713 chore: remove unecessary checks for persisted in end to end tests
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
  influxdb_iox/tests/end_to_end_cases/influxql.rs
  influxdb_iox/tests/end_to_end_cases/querier.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6708 refactor: Move sql script files from query_tests and into end to end query tests
  influxdb_iox/tests/query_tests2/cases.rs
  influxdb_iox/tests/query_tests2/cases/.gitignore
  influxdb_iox/tests/query_tests2/cases/in/basic.expected
  influxdb_iox/tests/query_tests2/cases/in/basic.sql
  influxdb_iox/tests/query_tests2/cases/in/dedup_and_predicates_parquet.expected
  influxdb_iox/tests/query_tests2/cases/in/dedup_and_predicates_parquet.sql
  influxdb_iox/tests/query_tests2/cases/in/dedup_and_predicates_parquet_ingester.expected
  influxdb_iox/tests/query_tests2/cases/in/dedup_and_predicates_parquet_ingester.sql
  influxdb_iox/tests/query_tests2/cases/in/duplicates_ingester.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_ingester.sql
  influxdb_iox/tests/query_tests2/cases/in/duplicates_parquet.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_parquet.sql
  influxdb_iox/tests/query_tests2/cases/in/duplicates_parquet_many.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_parquet_many.sql
  influxdb_iox/tests/query_tests2/cases/in/new_sql_system_tables.expected
  influxdb_iox/tests/query_tests2/cases/in/new_sql_system_tables.sql
  influxdb_iox/tests/query_tests2/cases/in/periods.expected
  influxdb_iox/tests/query_tests2/cases/in/periods.sql
  influxdb_iox/tests/query_tests2/cases/in/pushdown.expected
  influxdb_iox/tests/query_tests2/cases/in/pushdown.sql
  influxdb_iox/tests/query_tests2/cases/in/retention.expected
  influxdb_iox/tests/query_tests2/cases/in/retention.sql
  influxdb_iox/tests/query_tests2/cases/in/selectors.expected
  influxdb_iox/tests/query_tests2/cases/in/selectors.sql
  influxdb_iox/tests/query_tests2/cases/in/several_chunks.expected
  influxdb_iox/tests/query_tests2/cases/in/several_chunks.sql
  influxdb_iox/tests/query_tests2/cases/in/sql_information_schema.expected
  influxdb_iox/tests/query_tests2/cases/in/sql_information_schema.sql
  influxdb_iox/tests/query_tests2/cases/in/timestamps.expected
  influxdb_iox/tests/query_tests2/cases/in/timestamps.sql
  influxdb_iox/tests/query_tests2/cases/in/two_chunks.expected
  influxdb_iox/tests/query_tests2/cases/in/two_chunks.sql
  influxdb_iox/tests/query_tests2/cases/in/two_chunks_missing_columns.expected
  influxdb_iox/tests/query_tests2/cases/in/two_chunks_missing_columns.sql
  influxdb_iox/tests/query_tests2/framework.rs
  query_tests/README.md
  query_tests/cases/in/new_sql_system_tables.expected
  query_tests/cases/out/.gitkeep
  query_tests/generate/Cargo.lock
  query_tests/generate/Cargo.toml
  query_tests/generate/src/main.rs
  query_tests/src/cases.rs
  query_tests/src/lib.rs
  query_tests/src/runner.rs
  query_tests/src/runner/parse.rs
  query_tests/src/runner/setup.rs
  test_helpers_end_to_end/src/snapshot_comparison.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6723 fix: update clap parser for --ingester-addresses
  clap_blocks/src/ingest_replica.rs
  clap_blocks/src/querier.rs
  clap_blocks/src/router2.rs
Labels: automerge

#6714 feat(metrics): separate service limit counters
  router/src/dml_handlers/schema_validation.rs
Labels: kodiak: merge.method = 'merge'

#6732 feat(router): configurable partition key
  clap_blocks/src/router2.rs
  ioxd_router/src/lib.rs
Labels: kodiak: merge.method = 'merge', kafkaless

#6704 fix: reduce logging verbosity in `parquet_file_lookup`
  compactor/src/parquet_file_lookup.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6733 fix(iox): Use a transition shard id that doesn't overlap with legacy
  ingester2/src/lib.rs
Labels: automerge

#6709 test: Port query_tests read_filter tests to end-to-end
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/read_filter.rs
  influxdb_iox/tests/query_tests2/setups.rs
  query_tests/src/influxrpc.rs
  query_tests/src/influxrpc/read_filter.rs
  test_helpers_end_to_end/src/grpc.rs
  test_helpers_end_to_end/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6735 feat(ingester2): New objecstore paths will have no shard id
  parquet_file/src/lib.rs
Labels: automerge

#6722 chore: Update datafusion again
  Cargo.lock
  Cargo.toml
  iox_query/src/exec/gapfill.rs
  iox_query/src/provider/deduplicate.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#6734 test: Translate the filter_on_value test using field ref
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/read_filter.rs
  test_helpers_end_to_end/src/grpc.rs
  test_helpers_end_to_end/src/lib.rs
Labels: automerge

#6741 refactor: Make some nicer methods on the GrpcRequestBuilder
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/read_filter.rs
  test_helpers_end_to_end/src/grpc.rs
  test_helpers_end_to_end/src/lib.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6740 chore: validate ingester URIs on querier CLI
  Cargo.lock
  clap_blocks/Cargo.toml
  clap_blocks/src/querier.rs
  influxdb_iox/tests/end_to_end_cases/mode_switching.rs
Labels: automerge

#6730 feat: configurable RPC write request timeout
  clap_blocks/src/router2.rs
  ioxd_router/src/lib.rs
  router/src/dml_handlers/rpc_write/lazy_connector.rs
Labels: kodiak: merge.method = 'merge', kafkaless

#6728 feat: simple compactor2 self-protection
  clap_blocks/src/compactor2.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/partition_filter/by_id.rs
  compactor2/src/components/partition_filter/max_files.rs
  compactor2/src/components/partition_filter/max_parquet_bytes.rs
  compactor2/src/components/partition_filter/mod.rs
  compactor2/src/config.rs
  compactor2/src/test_util.rs
  ioxd_compactor2/src/lib.rs
Labels: automerge

#6747 fix: invalidate querier->ingester conn on error
  querier/src/ingester/circuit_breaker.rs
  querier/src/ingester/flight_client.rs
  querier/src/ingester/invalidate_on_error.rs
  querier/src/ingester/mod.rs
  query_tests/src/scenarios/util.rs
Labels: automerge

#6751 fix(router): envoy network error translation
  router/src/dml_handlers/rpc_write/lazy_connector.rs
Labels: kodiak: merge.method = 'merge', kafkaless

#6742 docs: Add docstring to Scratchpad
  compactor2/src/components/scratchpad/mod.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6752 feat: throttle when there are not partitions to compact
  compactor2/src/compactor_tests.rs
  compactor2/src/components/hardcoded.rs
  compactor2/src/components/partitions_source/mock.rs
  compactor2/src/components/partitions_source/mod.rs
  compactor2/src/components/partitions_source/not_empty.rs
  compactor2/src/test_util.rs
Labels: automerge

#6743 test: Port read_group query_tests to end-to-end tests
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/read_group.rs
  influxdb_iox/tests/query_tests2/setups.rs
  query_tests/src/influxrpc.rs
  query_tests/src/influxrpc/read_filter.rs
  query_tests/src/influxrpc/read_group.rs
  test_helpers_end_to_end/src/grpc.rs
Labels: automerge

#6754 chore: Add test for `SHOW TABLES`
  influxdb_iox/tests/query_tests2/cases/in/sql_information_schema.expected
  influxdb_iox/tests/query_tests2/cases/in/sql_information_schema.sql
Labels: automerge, kodiak: merge.method = 'squash'

#6753 chore: Update DataFusion
  Cargo.lock
  Cargo.toml
  influxdb_iox/tests/query_tests2/cases/in/duplicates_parquet.expected
  iox_query/src/exec/query_tracing.rs
  workspace-hack/Cargo.toml
Labels: automerge, kodiak: merge.method = 'squash'

#6776 refactor: log IDs in panic messages
  ingester2/src/buffer_tree/namespace/name_resolver.rs
  ingester2/src/buffer_tree/partition/resolver/sort_key.rs
  ingester2/src/buffer_tree/table/name_resolver.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6775 refactor: add partition ID to commit
  compactor2/src/components/commit/catalog.rs
  compactor2/src/components/commit/logging.rs
  compactor2/src/components/commit/metrics.rs
  compactor2/src/components/commit/mock.rs
  compactor2/src/components/commit/mod.rs
  compactor2/src/driver.rs
Labels: automerge

#6773 fix: do not panic when partition was removed from catalog
  querier/src/cache/partition.rs
  querier/src/ingester/mod.rs
Labels: automerge

#6755 test: Port read_window_aggregate query_tests to end-to-end tests
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/read_window_aggregate.rs
  influxdb_iox/tests/query_tests2/setups.rs
  query_tests/src/influxrpc.rs
  query_tests/src/influxrpc/read_window_aggregate.rs
  test_helpers_end_to_end/src/grpc.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6721 chore: reenable `cases/in/retention.sql` sql test
  influxdb_iox/tests/query_tests2/cases.rs
  influxdb_iox/tests/query_tests2/cases/in/retention.expected
  influxdb_iox/tests/query_tests2/cases/in/retention.sql
  influxdb_iox/tests/query_tests2/setups.rs
  influxdb_iox_client/src/client/namespace.rs
  service_grpc_namespace/src/lib.rs
  test_helpers_end_to_end/src/snapshot_comparison.rs
  test_helpers_end_to_end/src/steps.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6757 test: Port measurement_names/table_names query_tests to end-to-end tests
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/metadata.rs
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/metadata/measurement_names.rs
  query_tests/src/influxrpc.rs
  query_tests/src/influxrpc/table_names.rs
  test_helpers_end_to_end/src/grpc.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6779 refactor: disable ns delete
  service_grpc_namespace/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#6760 test: Port tag_keys query_tests to end-to-end tests
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/metadata.rs
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/metadata/tag_keys.rs
  influxdb_iox/tests/query_tests2/setups.rs
  query_tests/src/influxrpc.rs
  query_tests/src/influxrpc/tag_keys.rs
Labels: automerge, kodiak: merge.method = 'squash'

#6781 feat: Add number of rows to explain of RecordBatchesExec
  influxdb_iox/tests/query_tests2/cases/in/dedup_and_predicates_parquet_ingester.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_ingester.expected
  influxdb_iox/tests/query_tests2/cases/in/several_chunks.expected
  influxdb_iox/tests/query_tests2/cases/in/two_chunks.expected
  iox_query/src/provider.rs
  iox_query/src/provider/record_batch_exec.rs
Labels: automerge, kodiak: merge.method = 'squash'
