Repository influxdata/influxdb_iox, pull requests merged in 2023-05, with the labels that each got.

#7685 feat: Add --partition_filter to `remote get table` command
  influxdb_iox/src/commands/remote/partition.rs
  influxdb_iox/src/commands/remote/store.rs
Labels: automerge

#7710 fix: Fix cargo_audit and downgrade tracing to `0.1.37`
  Cargo.lock
Labels: automerge

#7688 fix: Remove `remote store pull` command
  influxdb_iox/src/commands/remote/partition.rs
  influxdb_iox/tests/end_to_end_cases/cli.rs
  influxdb_iox/tests/end_to_end_cases/remote.rs
Labels: automerge

#7712 fix: Use only humantime; get rid of chrono-english
  .config/hakari.toml
  Cargo.lock
  Cargo.toml
  deny.toml
  garbage_collector/Cargo.toml
  iox_data_generator/Cargo.toml
  iox_data_generator/src/bin/iox_data_generator.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7691 fix: make influx RPC interface break up series into multiple frames
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/read_filter.rs
  iox_query/src/exec/context.rs
  iox_query/src/exec/seriesset/converter.rs
  iox_query/src/exec/seriesset/series.rs
  service_grpc_influxrpc/src/data.rs
  service_grpc_influxrpc/src/service.rs
Labels: automerge

#7699 fix: Round sizes in compactor2 insta snapshots to the nearest KB or MB
  compactor2/tests/integration.rs
  compactor2/tests/layouts/backfill.rs
  compactor2/tests/layouts/common_use_cases.rs
  compactor2/tests/layouts/core.rs
  compactor2/tests/layouts/created_at.rs
  compactor2/tests/layouts/knobs.rs
  compactor2/tests/layouts/large_files.rs
  compactor2/tests/layouts/large_overlaps.rs
  compactor2/tests/layouts/many_files.rs
  compactor2_test_utils/src/display.rs
Labels: automerge

#7708 refactor: Change catalog configuration so it is entirely dsn based / support end to end testing without postgres
  clap_blocks/src/catalog_dsn.rs
  docs/testing.md
  garbage_collector/src/lib.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/tests/end_to_end_cases/compactor.rs
  iox_catalog/src/sqlite.rs
  test_helpers_end_to_end/src/config.rs
  test_helpers_end_to_end/src/database.rs
Labels: automerge

#7714 revert: PR #7708
  clap_blocks/src/catalog_dsn.rs
  docs/testing.md
  garbage_collector/src/lib.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/tests/end_to_end_cases/compactor.rs
  iox_catalog/src/sqlite.rs
  test_helpers_end_to_end/src/config.rs
  test_helpers_end_to_end/src/database.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7716 chore: move to the smaller, cargo-team maintained `home` crate
  Cargo.lock
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/run/all_in_one.rs
  workspace-hack/Cargo.toml
Labels: automerge

#7711 fix: removed clean files from hashtable to enable re-adding them later
  compactor2/src/components/scratchpad/prod.rs
Labels: automerge

#7718 fix: use correct sort key in projection_pushdown
  influxdb_iox/tests/query_tests2/cases/in/date_bin.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_ingester.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_parquet.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/gapfill.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql.expected
  influxdb_iox/tests/query_tests2/cases/in/several_chunks.sql.expected
  iox_query/src/physical_optimizer/projection_pushdown.rs
Labels: automerge

#7719 chore: Update DataFusion
  Cargo.lock
  Cargo.toml
  influxdb_iox/tests/end_to_end_cases/cli.rs
  influxdb_iox/tests/end_to_end_cases/querier.rs
  influxdb_iox/tests/query_tests2/cases/in/date_bin.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_ingester.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_parquet.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/gapfill.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql.expected
  influxdb_iox/tests/query_tests2/cases/in/several_chunks.sql.expected
  influxdb_iox/tests/query_tests2/sql_errors.rs
  iox_query/src/exec/context.rs
  iox_query/src/physical_optimizer/dedup/dedup_sort_order.rs
  iox_query/src/physical_optimizer/sort/parquet_sortness.rs
  workspace-hack/Cargo.toml
Labels: automerge

#7722 chore: Update DataFusion again
  Cargo.lock
  Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge

#7728 test: add test for InfluxQL md queries w/ `FROM ""`
  influxdb_iox/tests/query_tests2/cases/in/influxql_metadata.influxql
  influxdb_iox/tests/query_tests2/cases/in/influxql_metadata.influxql.expected
Labels: automerge

#7697 fix: Require some metadata, delete some metadata
  compactor2/src/components/parquet_file_sink/mock.rs
  compactor2/src/components/parquet_file_sink/object_store.rs
  compactor2_test_utils/src/simulator.rs
  data_types/src/lib.rs
  docs/ingester_querier_protocol.md
  garbage_collector/src/objectstore/checker.rs
  generated_types/protos/influxdata/iox/catalog/v1/parquet_file.proto
  generated_types/protos/influxdata/iox/ingester/v1/parquet_metadata.proto
  generated_types/protos/influxdata/iox/ingester/v1/query.proto
  import/src/aggregate_tsm_schema/update_catalog.rs
  ingester2/src/persist/mod.rs
  ingester2/src/persist/worker.rs
  ingester2/src/server/grpc/query.rs
  ingester2/src/test_util.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/kafkaless_transition.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
  iox_tests/src/builders.rs
  iox_tests/src/catalog.rs
  parquet_file/src/metadata.rs
  parquet_file/src/serialize.rs
  parquet_file/src/storage.rs
  parquet_file/tests/metadata.rs
  querier/src/cache/parquet_file.rs
  querier/src/ingester/mod.rs
  querier/src/namespace/query_access.rs
  querier/src/parquet/creation.rs
  querier/src/parquet/mod.rs
  querier/src/table/mod.rs
  querier/src/table/state_reconciler/interface.rs
  querier/src/table/test_util.rs
  service_grpc_catalog/src/lib.rs
  service_grpc_object_store/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7725 fix: handle aliases in gapfill aggregate columns
  influxdb_iox/tests/query_tests2/cases/in/gapfill.sql
  influxdb_iox/tests/query_tests2/cases/in/gapfill.sql.expected
  iox_query/src/logical_optimizer/handle_gapfill.rs
Labels: automerge

#7732 chore: update DataFusion to `2787e7a36a6be83d91201df20827d3695f933300`
  Cargo.lock
  Cargo.toml
  workspace-hack/Cargo.toml
Labels: automerge

#7733 chore: conditionally parse shard_id from HOSTNAME
  clap_blocks/src/compactor2.rs
  compactor2/src/components/hardcoded.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/tests/end_to_end_cases/compactor.rs
  ioxd_compactor2/src/lib.rs
Labels: automerge

#7737 test: num files to read exceed the max_parquet_fanout and all sorted …
  influxdb_iox/tests/query_tests2/cases.rs
  influxdb_iox/tests/query_tests2/cases/in/duplicates_parquet_50_files.sql
  influxdb_iox/tests/query_tests2/cases/in/duplicates_parquet_50_files.sql.expected
  influxdb_iox/tests/query_tests2/setups.rs
Labels: automerge

#7727 chore: Ensure time column is projected in subqueries
  influxdb_influxql_parser/src/expression/arithmetic.rs
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql.expected
  iox_query_influxql/src/plan/error.rs
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/planner/select.rs
  iox_query_influxql/src/plan/planner_rewrite_expression.rs
  iox_query_influxql/src/plan/rewriter.rs
  iox_query_influxql/src/plan/util.rs
  iox_query_influxql/src/plan/var_ref.rs
Labels: automerge, kodiak: merge.method = 'merge', query/language/influxql

#7742 refactor: use struct-style selectors in InfluxRPC
  iox_query_influxrpc/src/lib.rs
Labels: automerge

#7743 refactor: remove non-struct selector functions
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxrpc/src/lib.rs
  query_functions/src/selectors.rs
  query_functions/src/selectors/internal.rs
Labels: automerge

#7721 chore: Stop using cargo cache in CI (CI goes 2x faster)
  .circleci/config.yml
Labels: automerge

#7735 chore: Add test for `dsn-file://` catalog urls
  Cargo.lock
  influxdb_iox/tests/end_to_end_cases/catalog.rs
  influxdb_iox/tests/end_to_end_cases/mod.rs
  iox_catalog/src/postgres.rs
  test_helpers_end_to_end/Cargo.toml
  test_helpers_end_to_end/src/database.rs
Labels: automerge

#7734 fix: Move topic and query pool within iox catalog
  clap_blocks/src/catalog_dsn.rs
  clap_blocks/src/router2.rs
  compactor2/src/components/namespaces_source/mock.rs
  data_types/src/lib.rs
  docs/cli.md
  docs/underground_guide.md
  garbage_collector/src/objectstore/checker.rs
  generated_types/protos/influxdata/iox/schema/v1/service.proto
  import/src/aggregate_tsm_schema/update_catalog.rs
  influxdb_iox/src/commands/catalog.rs
  influxdb_iox/src/commands/catalog/topic.rs
  influxdb_iox/src/commands/import/schema.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ingester2/src/buffer_tree/partition/resolver/catalog.rs
  ingester2/src/test_util.rs
  ingester2_test_ctx/src/lib.rs
  iox_catalog/README.md
  iox_catalog/src/interface.rs
  iox_catalog/src/kafkaless_transition.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
  iox_tests/src/catalog.rs
  ioxd_router/src/lib.rs
  router/src/namespace_cache/memory.rs
  router/src/namespace_cache/metrics.rs
  router/src/namespace_cache/read_through_cache.rs
  router/src/namespace_cache/sharded_cache.rs
  router/src/namespace_resolver.rs
  router/src/namespace_resolver/ns_autocreation.rs
  router/src/server/grpc.rs
  router/tests/common/mod.rs
  router/tests/http.rs
  scripts/docker_catalog.sh
  service_grpc_catalog/src/lib.rs
  service_grpc_namespace/src/lib.rs
  service_grpc_object_store/src/lib.rs
  service_grpc_schema/src/lib.rs
  test_helpers_end_to_end/src/database.rs
Labels: automerge

#7745 refactor: simplify `{First,Last}Selector`
  query_functions/src/selectors.rs
  query_functions/src/selectors/internal.rs
Labels: automerge

#7696 feat(flightsql): Support `CommandGetXdbcTypeInfo` metadata endpoint with actual data type info
  flightsql/src/lib.rs
  flightsql/src/planner.rs
  flightsql/src/xdbc_type_info/mod.rs
  flightsql/src/xdbc_type_info/value.rs
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
Labels: automerge

#7738 fix(garbage collector): larger list batches and another tunable
  clap_blocks/src/garbage_collector.rs
  garbage_collector/src/lib.rs
  garbage_collector/src/objectstore/lister.rs
Labels: automerge, kodiak: merge.method = 'squash'

#7747 test: add test for gap fill query missing time bounds
  influxdb_iox/tests/query_tests2/cases/in/gapfill.sql
  influxdb_iox/tests/query_tests2/cases/in/gapfill.sql.expected
  iox_query/src/logical_optimizer/handle_gapfill.rs
  test_helpers_end_to_end/src/snapshot_comparison.rs
Labels: automerge

#7749 chore: add plan_id to compactor logging
  compactor2/src/driver.rs
Labels: automerge

#7753 refactor: Use intermediate representation of `SELECT` in InfluxQL planner
  influxdb_influxql_parser/src/select.rs
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql.expected
  iox_query_influxql/src/plan/expr_type_evaluator.rs
  iox_query_influxql/src/plan/field.rs
  iox_query_influxql/src/plan/ir.rs
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/rewriter.rs
Labels: automerge, kodiak: merge.method = 'merge', query/language/influxql

#7754 refactor: Remove fragile `is_tag_field` API
  influxdb_influxql_parser/src/select.rs
  iox_query_influxql/src/plan/ir.rs
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/rewriter.rs
  iox_query_influxql/src/plan/util.rs
Labels: automerge, kodiak: merge.method = 'merge', query/language/influxql

#7756 chore: Update DataFusion
  Cargo.lock
  Cargo.toml
  influxdb_iox/tests/query_tests2/cases/in/date_bin.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/dedup_and_predicates_parquet.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/dedup_and_predicates_parquet_ingester.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_ingester.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_parquet.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_parquet_50_files.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/duplicates_parquet_many.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/gapfill.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/issue_6112.influxql.expected
  influxdb_iox/tests/query_tests2/cases/in/pushdown.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/retention.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/several_chunks.sql.expected
  influxdb_iox/tests/query_tests2/cases/in/two_chunks.sql.expected
  iox_query/src/physical_optimizer/combine_chunks.rs
  iox_query/src/physical_optimizer/dedup/dedup_null_columns.rs
  iox_query/src/physical_optimizer/dedup/dedup_sort_order.rs
  iox_query/src/physical_optimizer/dedup/partition_split.rs
  iox_query/src/physical_optimizer/dedup/time_split.rs
  iox_query/src/physical_optimizer/predicate_pushdown.rs
  iox_query/src/physical_optimizer/projection_pushdown.rs
  iox_query/src/physical_optimizer/sort/parquet_sortness.rs
  iox_query/src/physical_optimizer/sort/redundant_sort.rs
  iox_query/src/provider.rs
  iox_query/src/provider/physical.rs
  querier/src/namespace/query_access.rs
  workspace-hack/Cargo.toml
Labels: automerge

#7762 test(ingester): fix flappy tests
  ingester2/src/buffer_tree/namespace.rs
  ingester2/src/buffer_tree/partition/resolver/cache.rs
  ingester2/src/buffer_tree/partition/resolver/coalesce.rs
  ingester2/src/buffer_tree/partition/resolver/trait.rs
  ingester2/src/buffer_tree/root.rs
  ingester2/src/buffer_tree/table.rs
  ingester2/src/dml_sink/instrumentation.rs
  ingester2/src/dml_sink/tracing.rs
  ingester2/src/persist/handle.rs
  ingester2/src/persist/mod.rs
  ingester2/src/test_util.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7765 fix(flightsql): do not panic on unimplemented
  flightsql/src/planner.rs
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
Labels: automerge

#7767 fix: Rename ioxd_ingester2 and ingester2_test_ctx
  Cargo.lock
  Cargo.toml
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/src/commands/run/ingester.rs
  ingester/Cargo.toml
  ingester/benches/write.rs
  ingester/tests/write.rs
  ingester_test_ctx/Cargo.toml
  ingester_test_ctx/README.md
  ingester_test_ctx/src/lib.rs
  ioxd_ingester/Cargo.toml
  ioxd_ingester/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7049 fix: Small remaining cleanups from the big deletion PR
  .circleci/config.yml
  Cargo.lock
  clap_blocks/Cargo.toml
  data_types/src/lib.rs
  docs/compactor.md
  generated_types/build.rs
  generated_types/protos/influxdata/iox/write_buffer/v1/write_buffer.proto
  generated_types/src/ingester.rs
  generated_types/src/lib.rs
  import/Cargo.toml
  influxdb_iox/Cargo.toml
  influxdb_iox/tests/end_to_end_cases/cli.rs
  ingester/README.md
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_tests/Cargo.toml
  router/src/dml_handlers/rpc_write/balancer.rs
Labels: kodiak: merge.method = 'merge'

#7692 feat: If namespace or table partition templates are specified, use those
  Cargo.lock
  clap_blocks/src/router2.rs
  compactor/src/components/df_planner/query_chunk.rs
  compactor/src/components/namespaces_source/mock.rs
  compactor/src/test_utils.rs
  data_types/Cargo.toml
  data_types/src/columns.rs
  data_types/src/lib.rs
  data_types/src/partition_template.rs
  import/src/aggregate_tsm_schema/update_catalog.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  ingester/src/persist/worker.rs
  ingester_test_ctx/src/lib.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_tests/src/catalog.rs
  ioxd_router/src/lib.rs
  mutable_batch/src/payload.rs
  mutable_batch/src/payload/partition.rs
  mutable_batch/tests/writer_fuzz.rs
  mutable_batch_pb/tests/encode.rs
  querier/src/cache/namespace.rs
  querier/src/table/test_util.rs
  router/benches/schema_validator.rs
  router/src/dml_handlers/chain.rs
  router/src/dml_handlers/fan_out.rs
  router/src/dml_handlers/instrumentation.rs
  router/src/dml_handlers/mock.rs
  router/src/dml_handlers/nop.rs
  router/src/dml_handlers/partitioner.rs
  router/src/dml_handlers/retention_validation.rs
  router/src/dml_handlers/rpc_write.rs
  router/src/dml_handlers/schema_validation.rs
  router/src/dml_handlers/trait.rs
  router/src/namespace_cache/memory.rs
  router/src/namespace_cache/metrics.rs
  router/src/namespace_cache/read_through_cache.rs
  router/src/namespace_cache/sharded_cache.rs
  router/src/namespace_resolver.rs
  router/src/namespace_resolver/mock.rs
  router/src/namespace_resolver/ns_autocreation.rs
  router/src/server/http.rs
  router/tests/common/mod.rs
Labels: kodiak: merge.method = 'merge'

#7769 refactor(router): separate RPC client error types
  router/src/dml_handlers/rpc_write.rs
  router/src/dml_handlers/rpc_write/circuit_breaking_client.rs
  router/src/dml_handlers/rpc_write/client.rs
  router/src/dml_handlers/rpc_write/lazy_connector.rs
  router/src/server/http.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7786 fix: Size of ColumnSet shouldn't be using ChunkId
  data_types/src/columns.rs
  querier/src/cache/parquet_file.rs
Labels: automerge

#7774 refactor: accept `NamespaceName` instead of `&str` with `NamespaceRepo::create`
  garbage_collector/src/objectstore/checker.rs
  import/src/aggregate_tsm_schema/update_catalog.rs
  ingester/src/buffer_tree/partition/resolver/catalog.rs
  ingester/src/test_util.rs
  ingester_test_ctx/src/lib.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
  iox_tests/src/catalog.rs
  ioxd_router/src/lib.rs
  router/src/namespace_resolver/ns_autocreation.rs
  router/tests/http.rs
  service_grpc_catalog/src/lib.rs
  service_grpc_object_store/src/lib.rs
  service_grpc_schema/src/lib.rs
Labels: automerge

#7775 refactor: accept `impl Into<String>` instead of `&str` for schema methods
  data_types/src/columns.rs
  mutable_batch/src/lib.rs
  parquet_file/tests/metadata.rs
  schema/src/builder.rs
Labels: automerge

#7788 chore: accept database in addition to namespace_name
  service_grpc_flight/src/request.rs
Labels: automerge

#7792 refactor: Extract some catalog test helper methods to reduce places that need to change
  garbage_collector/src/objectstore/checker.rs
  import/src/aggregate_tsm_schema/update_catalog.rs
  ingester/src/buffer_tree/partition/resolver/catalog.rs
  ingester/src/test_util.rs
  ingester_test_ctx/src/lib.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
  iox_tests/src/catalog.rs
  ioxd_router/src/lib.rs
  router/tests/http.rs
  service_grpc_catalog/src/lib.rs
  service_grpc_object_store/src/lib.rs
  service_grpc_schema/src/lib.rs
Labels: kodiak: merge.method = 'merge'

#7787 perf(router): parallel write replication
  router/src/dml_handlers/rpc_write.rs
  router/src/dml_handlers/rpc_write/balancer.rs
  router/src/dml_handlers/rpc_write/client.rs
  router/src/dml_handlers/rpc_write/upstream_snapshot.rs
  router/src/server/http.rs
Labels: kodiak: merge.method = 'merge'

#7729 feat(wal): Add `wal_inspect` crate & a write op entry decoder
  Cargo.lock
  Cargo.toml
  parquet_to_line_protocol/src/batch.rs
  parquet_to_line_protocol/src/lib.rs
  wal/Cargo.toml
  wal/src/lib.rs
  wal_inspect/Cargo.toml
  wal_inspect/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7797 feat(metrics): Parquet file attribute statistics
  ingester/src/init.rs
  ingester/src/persist/completion_observer.rs
  ingester/src/persist/context.rs
  ingester/src/persist/file_metrics.rs
  ingester/src/persist/mod.rs
  ingester/src/persist/worker.rs
  ingester/src/wal/reference_tracker/handle.rs
  ingester/tests/write.rs
  ingester_test_ctx/src/lib.rs
Labels: kodiak: merge.method = 'merge'

#7793 chore: update DataFusion and arrow / arrow-flight / parquet to `39.0.0`
  Cargo.lock
  Cargo.toml
  arrow_util/src/bitset.rs
  iox_query/src/exec/seriesset/converter.rs
  query_functions/src/coalesce_struct.rs
  workspace-hack/Cargo.toml
Labels: automerge

#7801 fix: correct time range buckets
  ingester/src/persist/file_metrics.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7802 chore: add a go_package option to the authz proto file
  generated_types/protos/influxdata/iox/authz/v1/authz.proto
Labels: automerge

#7799 refactor: rename `import` to `iox_import_export`
  Cargo.lock
  Cargo.toml
  import_export/Cargo.toml
  import_export/src/lib.rs
  import_export/src/tsm/mod.rs
  import_export/src/tsm/tsm_schema/fetch.rs
  import_export/src/tsm/tsm_schema/merge.rs
  import_export/src/tsm/tsm_schema/mod.rs
  import_export/src/tsm/tsm_schema/update_catalog.rs
  import_export/src/tsm/tsm_schema/validate.rs
  influxdb_iox/Cargo.toml
  influxdb_iox/src/commands/import/schema.rs
Labels: automerge

#7773 feat: Initial support for subqueries
  influxdb_influxql_parser/src/select.rs
  influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql
  influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql.expected
  iox_query_influxql/src/plan/expr_type_evaluator.rs
  iox_query_influxql/src/plan/field.rs
  iox_query_influxql/src/plan/field_mapper.rs
  iox_query_influxql/src/plan/ir.rs
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/planner/select.rs
  iox_query_influxql/src/plan/rewriter.rs
  iox_query_influxql/src/plan/test_utils.rs
  iox_query_influxql/src/plan/var_ref.rs
Labels: automerge, kodiak: merge.method = 'merge', query/language/influxql

#7798 refactor: remove output sorting from scan provider
  iox_query/src/frontend.rs
  iox_query/src/frontend/common.rs
  iox_query/src/frontend/reorg.rs
  iox_query/src/provider.rs
  iox_query/src/util.rs
Labels: automerge

#7778 fix: correctly recurse in `ParquetSortness`
  influxdb_iox/tests/query_tests/cases.rs
  influxdb_iox/tests/query_tests/cases/in/duplicates_parquet_20.sql
  influxdb_iox/tests/query_tests/cases/in/duplicates_parquet_20.sql.expected
  influxdb_iox/tests/query_tests/cases/in/duplicates_parquet_20_and_ingester.sql
  influxdb_iox/tests/query_tests/cases/in/duplicates_parquet_20_and_ingester.sql.expected
  influxdb_iox/tests/query_tests/cases/in/duplicates_parquet_50.sql
  influxdb_iox/tests/query_tests/cases/in/duplicates_parquet_50.sql.expected
  influxdb_iox/tests/query_tests/setups.rs
  iox_query/src/physical_optimizer/mod.rs
  iox_query/src/physical_optimizer/sort/parquet_sortness.rs
Labels: automerge

#7807 refactor: remove `SortPushdown` optimizer pass
  iox_query/src/physical_optimizer/mod.rs
  iox_query/src/physical_optimizer/sort/mod.rs
  iox_query/src/physical_optimizer/sort/sort_pushdown.rs
Labels: automerge

#7811 feat(wal_inspect): Make table batch writing a trait, support table ID based line protocol
  wal_inspect/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7736 refactor: Change catalog configuration so it is entirely dsn based / support end to end testing without postgres
  clap_blocks/src/catalog_dsn.rs
  docs/testing.md
  garbage_collector/src/lib.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  influxdb_iox/tests/end_to_end_cases/catalog.rs
  influxdb_iox/tests/end_to_end_cases/command_rename_support.rs
  influxdb_iox/tests/end_to_end_cases/compactor.rs
  iox_catalog/src/sqlite.rs
  test_helpers_end_to_end/src/config.rs
  test_helpers_end_to_end/src/database.rs
Labels: automerge

#7813 refactor: upgrade DataFusion to `19b03240920ad63cac916b42951754c0337b…
  Cargo.lock
  Cargo.toml
  influxdb_iox/tests/query_tests/cases/in/duplicates_parquet.sql.expected
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/util_copy.rs
  workspace-hack/Cargo.toml
Labels: automerge

#7800 feat(proto): partition template type
  generated_types/build.rs
  generated_types/protos/influxdata/iox/partition_template/v1/template.proto
Labels: kodiak: merge.method = 'merge'

#7817 test: Add an invalid test configuration checker and fix potentially flaky test setups it detects
  influxdb_iox/tests/end_to_end_cases/cli.rs
  influxdb_iox/tests/end_to_end_cases/compactor.rs
  influxdb_iox/tests/end_to_end_cases/ingester.rs
  influxdb_iox/tests/end_to_end_cases/querier.rs
  influxdb_iox/tests/end_to_end_cases/querier/multi_ingester.rs
  influxdb_iox/tests/end_to_end_cases/remote.rs
  influxdb_iox/tests/query_tests/cases.rs
  influxdb_iox/tests/query_tests/framework.rs
  influxdb_iox/tests/query_tests/setups.rs
  test_helpers_end_to_end/src/steps.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7804 refactor: remove `influxdb_iox import` and related code
  import_export/src/lib.rs
  import_export/src/tsm/mod.rs
  import_export/src/tsm/tsm_schema/fetch.rs
  import_export/src/tsm/tsm_schema/merge.rs
  import_export/src/tsm/tsm_schema/mod.rs
  import_export/src/tsm/tsm_schema/update_catalog.rs
  import_export/src/tsm/tsm_schema/validate.rs
  influxdb_iox/src/commands/import/mod.rs
  influxdb_iox/src/commands/import/schema.rs
  influxdb_iox/src/main.rs
Labels: automerge

#7823 refactor(cli): update replication help text
  clap_blocks/src/router.rs
  influxdb_iox/src/commands/run/all_in_one.rs
  router/src/dml_handlers/rpc_write.rs
  router/tests/common/mod.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7779 feat: download catalog objects as part of `remote store get-table`
  Cargo.lock
  import_export/Cargo.toml
  import_export/src/file/export.rs
  import_export/src/file/import.rs
  import_export/src/file/mod.rs
  import_export/src/lib.rs
  influxdb_iox/src/commands/remote/store.rs
  influxdb_iox/tests/end_to_end_cases/remote.rs
  influxdb_iox_client/src/client/catalog.rs
  test_helpers_end_to_end/src/steps.rs
Labels: automerge

#7822 chore: Add rationale for `clippy::future_not_send`
  arrow_util/src/lib.rs
  authz/src/lib.rs
  backoff/src/lib.rs
  cache_system/src/lib.rs
  clap_blocks/src/lib.rs
  client_util/src/lib.rs
  compactor/src/lib.rs
  compactor_test_utils/src/lib.rs
  data_types/src/lib.rs
  dml/src/lib.rs
  executor/src/lib.rs
  garbage_collector/src/lib.rs
  grpc-binary-logger/src/lib.rs
  influxdb2_client/src/lib.rs
  influxdb_influxql_parser/src/lib.rs
  influxdb_iox/src/main.rs
  influxdb_iox_client/src/lib.rs
  influxdb_storage_client/src/lib.rs
  influxrpc_parser/src/lib.rs
  ingester/src/lib.rs
  ingester_test_ctx/src/lib.rs
  iox_catalog/src/lib.rs
  iox_data_generator/src/bin/iox_data_generator.rs
  iox_data_generator/src/lib.rs
  iox_query/src/lib.rs
  iox_query_influxql/src/lib.rs
  iox_tests/src/lib.rs
  iox_time/src/lib.rs
  ioxd_garbage_collector/src/lib.rs
  mutable_batch/src/lib.rs
  mutable_batch_lp/src/lib.rs
  mutable_batch_pb/src/lib.rs
  parquet_file/src/lib.rs
  predicate/src/lib.rs
  querier/src/lib.rs
  query_functions/src/lib.rs
  router/src/lib.rs
  service_grpc_catalog/src/lib.rs
  service_grpc_object_store/src/lib.rs
  sharder/src/lib.rs
  sqlx-hotswap-pool/src/lib.rs
  trace/src/lib.rs
  trace_exporters/src/lib.rs
  trace_http/src/lib.rs
  tracker/src/lib.rs
  trogging/src/lib.rs
  wal_inspect/src/lib.rs
Labels: automerge

#7825 chore: update DataFusion
  Cargo.lock
  Cargo.toml
  influxdb_iox/tests/query_tests/cases/in/duplicates_parquet_20.sql.expected
  influxdb_iox/tests/query_tests/cases/in/duplicates_parquet_20_and_ingester.sql.expected
  workspace-hack/Cargo.toml
Labels: automerge

#7821 docs(README): Update link to datafusion
  README.md
Labels: automerge

#7831 chore: remove config lines to skip failed rules, as it is now default
  datafusion_util/src/config.rs
Labels: automerge

#7815 refactor: consolidate pruning code
  iox_query/src/lib.rs
  iox_query/src/test.rs
  iox_query_influxrpc/src/lib.rs
  predicate/src/lib.rs
  service_grpc_influxrpc/src/service.rs
Labels: automerge

#7837 chore: remove unused deps
  Cargo.lock
  wal/Cargo.toml
Labels: automerge, kodiak: merge.method = 'merge'

#7810 feat: hide `system.queries` table from prod by default
  docs/sql.md
  generated_types/protos/influxdata/iox/querier/v1/flight.proto
  influxdb_iox/tests/end_to_end_cases/all_in_one.rs
  influxdb_iox/tests/end_to_end_cases/flightsql.rs
  influxdb_iox/tests/end_to_end_cases/querier.rs
  influxdb_iox_client/src/client/flight/mod.rs
  querier/src/database.rs
  querier/src/namespace/mod.rs
  querier/src/namespace/query_access.rs
  querier/src/system_tables/mod.rs
  service_common/src/lib.rs
  service_common/src/test_util.rs
  service_grpc_flight/src/lib.rs
  service_grpc_flight/src/request.rs
  service_grpc_influxrpc/src/service.rs
  test_helpers_end_to_end/src/client.rs
  test_helpers_end_to_end/src/snapshot_comparison.rs
  test_helpers_end_to_end/src/steps.rs
Labels: automerge

#7808 fix: Ensure each table is processed in its own `LogicalPlan` graph
  influxdb_influxql_parser/src/expression/arithmetic.rs
  influxdb_influxql_parser/src/expression/walk.rs
  influxdb_influxql_parser/src/identifier.rs
  influxdb_influxql_parser/src/select.rs
  influxdb_influxql_parser/src/visit.rs
  influxdb_influxql_parser/src/visit_mut.rs
  influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql
  influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql.expected
  iox_query_influxql/src/plan/expr_type_evaluator.rs
  iox_query_influxql/src/plan/ir.rs
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/planner/select.rs
  iox_query_influxql/src/plan/rewriter.rs
  test_helpers_end_to_end/src/snapshot_comparison.rs
Labels: automerge, kodiak: merge.method = 'merge', query/language/influxql

#7847 revert: refactor: consolidate pruning code (#7815)
  iox_query/src/lib.rs
  iox_query/src/test.rs
  iox_query_influxrpc/src/lib.rs
  predicate/src/lib.rs
  service_grpc_influxrpc/src/service.rs
Labels: automerge

#7850 fix: flaky `service::tests::test_log_on_panic`
  Cargo.lock
  influxdb_iox/src/commands/run/main.rs
  panic_logging/src/lib.rs
  service_grpc_influxrpc/Cargo.toml
  service_grpc_influxrpc/src/service.rs
  workspace-hack/Cargo.toml
Labels: automerge

#7812 fix(ingester): re-transmit schema over flight if it changes
  ingester/Cargo.toml
  ingester/src/buffer_tree/root.rs
  ingester/src/buffer_tree/table.rs
  ingester/src/query/partition_response.rs
  ingester/src/query/response.rs
  ingester/src/query/result_instrumentation.rs
  ingester/src/server/grpc/query.rs
  ingester/src/test_util.rs
  ingester/tests/write.rs
Labels: automerge

#7853 refactor: clean up catalog `parquet_files` interface
  compactor/src/components/commit/catalog.rs
  compactor_test_utils/src/lib.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
  iox_tests/src/catalog.rs
Labels: automerge

#7852 refactor: re-land #7815.
  influxdb_iox/tests/end_to_end_cases/querier/influxrpc/read_filter.rs
  iox_query/src/lib.rs
  iox_query/src/test.rs
  iox_query_influxrpc/src/lib.rs
  predicate/src/lib.rs
  service_grpc_influxrpc/src/service.rs
Labels: automerge

#7790 feat: Set, store, and use custom namespace and table partitions on write
  Cargo.lock
  compactor/src/components/namespaces_source/mock.rs
  compactor/src/partition_info.rs
  compactor/src/test_utils.rs
  data_types/Cargo.toml
  data_types/src/lib.rs
  data_types/src/partition_template.rs
  generated_types/protos/influxdata/iox/namespace/v1/service.proto
  generated_types/protos/influxdata/iox/partition_template/v1/template.proto
  generated_types/src/lib.rs
  influxdb_iox_client/src/client/namespace.rs
  ingester/benches/write.rs
  ingester/src/test_util.rs
  ingester_test_ctx/src/lib.rs
  iox_catalog/Cargo.toml
  iox_catalog/migrations/20230501173720_add_partition_templates.sql
  iox_catalog/sqlite/migrations/20230501173720_add_partition_templates.sql
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
  iox_tests/src/builders.rs
  iox_tests/src/catalog.rs
  ioxd_router/src/lib.rs
  mutable_batch/src/payload.rs
  mutable_batch/src/payload/partition.rs
  mutable_batch/tests/writer_fuzz.rs
  mutable_batch_pb/tests/encode.rs
  router/src/dml_handlers/instrumentation.rs
  router/src/dml_handlers/partitioner.rs
  router/src/dml_handlers/rpc_write.rs
  router/src/dml_handlers/schema_validation.rs
  router/src/namespace_cache/memory.rs
  router/src/namespace_cache/metrics.rs
  router/src/namespace_cache/read_through_cache.rs
  router/src/namespace_cache/sharded_cache.rs
  router/src/namespace_resolver.rs
  router/src/namespace_resolver/mock.rs
  router/src/namespace_resolver/ns_autocreation.rs
  router/tests/common/mod.rs
  router/tests/grpc.rs
  router/tests/http.rs
  service_grpc_namespace/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7862 refactor(catalog): mark metrics() as test only
  iox_catalog/src/interface.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
Labels: kodiak: merge.method = 'merge'

#7864 chore: Update DataFusion and arrow to `40.0.0`
  Cargo.lock
  Cargo.toml
  influxdb_iox_client/src/format.rs
  workspace-hack/Cargo.toml
Labels: automerge

#7826 feat: table creation gRPC API with optional custom table template
  Cargo.lock
  Cargo.toml
  data_types/src/partition_template.rs
  generated_types/build.rs
  generated_types/protos/influxdata/iox/table/v1/service.proto
  generated_types/src/lib.rs
  influxdb_iox/tests/end_to_end_cases/namespace.rs
  ioxd_router/src/lib.rs
  router/Cargo.toml
  router/src/server/grpc.rs
  router/tests/grpc.rs
  service_grpc_namespace/src/lib.rs
  service_grpc_table/Cargo.toml
  service_grpc_table/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7875 chore: Minor cleanup
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/rewriter.rs
Labels: automerge, kodiak: merge.method = 'merge', query/language/influxql

#7820 chore(7618): trace ingester response encoding v2
  influxdb_iox/tests/end_to_end_cases/tracing.rs
  ingester/src/server/grpc/query.rs
  ingester/src/server/grpc/query/instrumentation.rs
  test_helpers_end_to_end/src/config.rs
  trace/src/lib.rs
Labels: automerge

#7870 feat: Add decoded payload type and size to querier <--> ingester tracing
  querier/src/ingester/flight_client.rs
  querier/src/ingester/mod.rs
Labels: automerge

#7878 chore(docs): Update tracing.md with latest jaeger
  docs/tracing.md
Labels: automerge

#7869 feat: add more tag predicate rewrite logic for InfluxQL
  Cargo.lock
  influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql
  influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql.expected
  iox_query_influxql/Cargo.toml
  iox_query_influxql/src/frontend/planner.rs
  iox_query_influxql/src/plan/ir.rs
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/planner_rewrite_expression.rs
  iox_query_influxql/src/plan/test_utils.rs
  predicate/src/rpc_predicate.rs
  predicate/src/rpc_predicate/rewrite.rs
Labels: automerge, query/language/influxql

#7876 docs: describe what the spans capture
  ingester/src/server/grpc/query/instrumentation.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7881 docs(flightsql): Add upstream ticket link
  flightsql/src/sql_info/mod.rs
Labels: automerge

#7890 refactor: explicit submod for partition_template
  data_types/src/lib.rs
  ingester_test_ctx/src/lib.rs
  iox_catalog/src/interface.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
  mutable_batch/src/payload.rs
  mutable_batch/src/payload/partition.rs
  mutable_batch/tests/writer_fuzz.rs
  router/src/dml_handlers/partitioner.rs
  router/src/dml_handlers/schema_validation.rs
  service_grpc_namespace/src/lib.rs
  service_grpc_table/src/lib.rs
Labels: automerge, kodiak: merge.method = 'merge'

#7891 docs: Add ticket reference for other upstream implementations of flig…
  flightsql/src/get_catalogs.rs
  flightsql/src/get_db_schemas.rs
  flightsql/src/get_tables.rs
Labels: automerge

#7889 fix: gap filling with multiple lower or upper time bounds
  influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql
  influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql.expected
  iox_query_influxql/src/plan/planner.rs
  iox_query_influxql/src/plan/planner_rewrite_expression.rs
Labels: automerge, kodiak: merge.method = 'merge', query/language/influxql

#7842 refactor: add `parquet_file` PG index for querier
  Cargo.lock
  iox_catalog/Cargo.toml
  iox_catalog/README.md
  iox_catalog/migrations/20230524151854_add_parquet_file_partition_and_deleted_index.sql
  iox_catalog/src/interface.rs
  iox_catalog/src/kafkaless_transition.rs
  iox_catalog/src/lib.rs
  iox_catalog/src/mem.rs
  iox_catalog/src/metrics.rs
  iox_catalog/src/migrate.rs
  iox_catalog/src/postgres.rs
  iox_catalog/src/sqlite.rs
Labels: automerge

#7894 feat: add index for compactor
  iox_catalog/migrations/20230524151854_add_parquet_file_table_and_deleted_index.sql
  iox_catalog/migrations/20230530132809_add_parquet_file_partition_and_deleted_index.sql
Labels: automerge

#7880 feat(parquet): reduce and limit buffering when writing parquet files
  Cargo.lock
  Cargo.toml
  compactor/src/components/hardcoded.rs
  compactor/src/components/parquet_file_sink/object_store.rs
  datafusion_util/src/lib.rs
  ingester/src/persist/worker.rs
  iox_data_generator/src/write.rs
  iox_query/src/exec.rs
  iox_tests/src/catalog.rs
  parquet_file/Cargo.toml
  parquet_file/src/lib.rs
  parquet_file/src/metadata.rs
  parquet_file/src/serialize.rs
  parquet_file/src/storage.rs
  parquet_file/src/writer.rs
  parquet_file/tests/metadata.rs
  workspace-hack/Cargo.toml
Labels: automerge

#7893 feat: unambiguously reversible partition keys
  Cargo.lock
  data_types/Cargo.toml
  data_types/src/partition_template.rs
  mutable_batch/Cargo.toml
  mutable_batch/src/payload/partition.rs
  router/src/dml_handlers/partitioner.rs
  router/tests/grpc.rs
Labels: kodiak: merge.method = 'merge'
